### ISSUE TITLE
Changes in frontmatter not updated using HMR

### ISSUE THREAD

**Issue by meta7x** [vuejs/vitepress#10]
## Describe the bug

Changing the frontmatter of any markdown file is not reflected in the browser until reloading the page.

## System Info

- `vitepress` version: 0.1.1
- Operating System: macOS 10.14.6
- Node version: 12.10.0

## Reproduction

https://github.com/meta7x/vitepress-frontmatter-hrm-bug

- start vitepress
- make changes to `index.md`, in particular to the frontmatter
- **expected behaviour**: changes appear on saving the file
- **observed behaviour**: changes appear only on reloading the page

**Comment by f3ltron** [comment]
Hello update your version to v0.13.2 it's working for me 👍

**Comment by meta7x** [comment]
Nice, thx for letting me know!
