### ISSUE TITLE
No language registration for yml

### ISSUE THREAD

**Issue by wulisensen** [vuejs/vitepress#1001]
### Describe the bug

Today I migration to 1.0.0-alpha.4 from  0.13.0

it throw error

`No language registration for yml`

![image](https://user-images.githubusercontent.com/22022130/179359629-c2517f12-ebe6-47ed-a9b7-2e688047e667.png)

### Reproduction

migration to 1.0.0-alpha.4

### Expected behavior

dont throw error

### System Info

```shell
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 712.17 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 78.0.1
    Safari: 13.1.1
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wulisensen** [comment]
conf is also not supported

**Comment by brc-dd** [comment]
Only these languages are supported: https://github.com/shikijs/shiki/blob/main/docs/languages.md#all-languages

Instead of `yml`, use `yaml`. And I'm not sure what is `conf`.

**Comment by wulisensen** [comment]
> Only these languages are supported: https://github.com/shikijs/shiki/blob/main/docs/languages.md#all-languages
> 
> Instead of `yml`, use `yaml`. And I'm not sure what is `conf`.

nginx.conf

**Comment by brc-dd** [comment]
Use `nginx` for that.

**Comment by wulisensen** [comment]
> > nginx.conf
> 
> Use `nginx` for that.

Thanks
