### ISSUE TITLE
vitepress v1.0.0-alpha.4 `yarn docs:build` fail

### ISSUE THREAD

**Issue by MrMJY** [vuejs/vitepress#1004]
### Describe the bug

1. This is a new project.
2. `yarn docs:dev` can start normally.
3. `yarn docs:build` fail.

### Reproduction

This is a new project. Only one file(`index.md`) is added in the `docs` directory. Then `yarn docs:build` fail.

### Expected behavior

`yarn docs:build` success.

### System Info

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz     
    Memory: 7.11 GB / 15.86 GB
  Binaries:
    Node: 16.13.1 - D:\software\nodejs\node.EXE
    Yarn: 1.22.17 - D:\software\nodejs\yarn.CMD
    npm: 8.1.2 - D:\software\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.18362.1533.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Additional context

```js
$ yarn docs:build
yarn run v1.22.17
$ vitepress build docs
vitepress v1.0.0-alpha.4
✓ building client + server bundles...
✓ rendering pages...
build error:
 [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Administrator\Desktop\blog\docs\.vitepress\.temp'] {
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Administrator\\Desktop\\blog\\docs\\.vitepress\\.temp'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by MrMJY** [comment]
```md
```

**Comment by brc-dd** [comment]
Try removing that `.vitepress\.temp` directory manually. This won't happen on the Vite 3 branch, I'd changed deletion there to be recursive-forced.

**Comment by MrMJY** [comment]
1. Why not  remove `dist` directory before each `yarn docs:build`?
2. Can it be optimized? `yarn docs:build` fail, automatically delete the `dist` and `.temp` directory.

**Comment by MrMJY** [comment]
```
docs
  |-directoryA
      |-directoryA-B
         |-index.md
      |-other.md
```
The construction of this directory `build` is always failed.
```
vitepress v1.0.0-alpha.4
✓ building client + server bundles...
✓ rendering pages...
build error:
 [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Administrator\Desktop\blog\docs\.vitepress\.temp'] {
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Administrator\\Desktop\\blog\\docs\\.vitepress\\.temp'
}
```
Manually delete the `.temp` directory also `build` failed.

**Comment by MrMJY** [comment]
```bash
pnpm add -D vitepress@npm:@brc-dd/vitepress@next
```
The problem has been resolved.

I want to ask about custom styles, theme related configuration. Because some of the default styles are not appropriate.

**Comment by brc-dd** [comment]
Yeah, about that, don't use that package for your site. It updates daily and might break stuff without any notice.

**Comment by xiezijie4396** [comment]
Hello, do you resolve this problem?

**Comment by xiezijie4396** [comment]
> ```shell
> pnpm add -D vitepress@npm:@brc-dd/vitepress@next
> ```
> 
> The problem has been resolved.
> 
> I want to ask about custom styles, theme related configuration. Because some of the default styles are not appropriate.

I can't resolve this problem by this way, did you use another solution ?

**Comment by lmq352489099** [comment]
> > ```shell
> > pnpm add -D vitepress@npm:@brc-dd/vitepress@next
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个问题已经解决。
> > 我想问一下自定义样式，主题相关的配置。因为有些默认的样式不合适。
> 
> 我无法通过这种方式解决此问题，您是否使用了其他解决方案？

我也遇到了该问题
