### ISSUE TITLE
docs: separate logo for dark mode

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/vitepress#1006]
### Is your feature request related to a problem? Please describe.

My logo is a wordmark, so it includes text (in a dark color).

For dark mode this should be a lighter color (eg. white).

Currently the logo is added as svg, but Vitepress uses the image tag, so I can't even overwrite the colors via CSS.

### Describe the solution you'd like

either include the logo as inline SVG or allow us to set a dark mode separate logo.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! its already supported. Refer this: https://github.com/vuejs/vitepress/pull/745#issue-1263907545. Though we haven't added it to docs yet.

**Comment by mesqueeb** [comment]
@brc-dd Great! thanks so much.
