### ISSUE TITLE
Multiple Nav bars

### ISSUE THREAD

**Issue by soongsta** [vuejs/vitepress#1008]
### Is your feature request related to a problem? Please describe.

Functionality to have a secondary nav bar

### Describe the solution you'd like

Ability to have a secondary nav bar

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What's the use case?

**Comment by soongsta** [comment]
Instead of a sidebar, it would be nice to have a secondary nav bar. Or have both. It's a feature request. It's ok to ignore this request.

**Comment by brc-dd** [comment]
Yeah, I understand that it's a feature request. But can you show some demo/sketch on what would be there on it? Like what would people use it for? We have navigation slots, so it might be possible what you're asking can already be done.

**Comment by brc-dd** [comment]
Ah, you want sidebar items to be on navbar? Any particular UI that you have in mind for this? I guess this can be done at your end using the provided navigation slots.

**Comment by soongsta** [comment]
Bootstrap has an example multiple navbars eg https://getbootstrap.com/docs/5.2/examples/offcanvas-navbar/

**Comment by MarkusKeck** [comment]
I just tried to find a solution for this. It seems like siteData is read-only, so it is simply not possible to change the navigation based on the route.

```ts

export default {
    ...DefaultTheme,
    setup() {},

    enhanceApp(ctx) {
        DefaultTheme.enhanceApp(ctx)
        ctx.router.onAfterRouteChanged = (to) => {
            ctx.siteData.value.themeConfig.nav = {
                text: 'Ecosystem',
                activeMatch: '^/ecosystem/',
                link: '/guide/what-is-vitepress'
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/19492739/222610638-589d5a59-ca84-4db7-8e68-c9e50b537a8f.png)

@brc-dd Is there a specific reason that thisi is readonly?
Is there maybe an easy workarround for this?

I think there are some real world usecases for "dynamic" navigation bars.

**Comment by kiaking** [comment]
I think this should be done in custom theme. We do have nested sidebar for nesting the menu.

Although this secondary navbar is totally valid UI design, I don't think we should keep adding many different navigations to a single theme.
