### ISSUE TITLE
Cant figure out how to use components inside .md file

### ISSUE THREAD

**Issue by alekspetrov** [vuejs/vitepress#101]
Hello!

Documentation says "...allowing the user to freely mix Vue components inside markdown content..." but it doesn't work as VuePress.

To reproduce init project according to documentation.
Create `.vitepress/components/NewComponent.vue` with a `<template><p>Hello VitePress</p></template>`
Try to use `<NewComponent />` inside index.md

Expected to see rendered component on the page see nothing.
Console says "Failed to resolve component: NewComponent"

What I'm doing wrong?

**Comment by kiaking** [comment]
You need to create `.vitepress/theme/index.js` and register it.

```js
import DefaultTheme from 'vitepress/dist/client/theme-default'
import NewComponent from './components/NewComponent.vue'

export default {
  ...DefaultTheme,
  enhanceApp({ app, router, siteData }) {
    app.component('NewComponent', NewComponent)
  }
}
```
