### ISSUE TITLE
crash on the first load of `examples/minimal`

### ISSUE THREAD

**Issue by fi3ework** [vuejs/vitepress#1016]
### Describe the bug

When starts to dev the `examples/minimal` in this repository. The first load will trigger a runtime error which is the same as https://github.com/vuejs/core/issues/4344. Everything goes well unless using a linked vitepress so the users won't encounter this error. But it breaks https://github.com/vuejs/vitepress/pull/1012 because of the first load crash. And after a page reload, everything goes well and won't crash anymore, the crash only happens when creating `.vite` cache. I think it's because packages are optimized by Vite which does not in an un-linked scenario.

<img width="819" alt="image" src="https://user-images.githubusercontent.com/12322740/179678356-6b19091d-d254-41ee-9fca-5fecd46362f6.png">

link

<img width="494" alt="image" src="https://user-images.githubusercontent.com/12322740/179677782-a76acda1-d4c3-4611-931a-c88f1f3e687a.png">

un-link

<img width="683" alt="image" src="https://user-images.githubusercontent.com/12322740/179677814-e22f0dbc-355b-4fee-9fe7-c5b68fdf7116.png">

I have a workaround to make https://github.com/vuejs/vitepress/pull/1012 pass but I don't really know why packages such as body-scroll-lock are optimized by Vite 🤔. Also, since we are migrating to Vite3, does this issue still exists in Vite3 based vitepress yet? @brc-dd 

### Reproduction

1. clone `main` branch
2. `pnpm i && pnpm build`
3. `cd examples/minimal`
4. `pnpm dev --force`

### Expected behavior

no crash at the first page load

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 267.59 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/Library/Caches/fnm_multishells/22311_1658125341110/bin/node
    npm: 8.5.5 - ~/Library/Caches/fnm_multishells/22311_1658125341110/bin/npm
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> does this issue still exists in Vite3 based vitepress

No, not happening for me on [`chore/vite-3`](https://github.com/vuejs/vitepress/tree/chore/vite-3) branch.

**Comment by fi3ework** [comment]
> > does this issue still exists in Vite3 based vitepress
> 
> No, not happening for me on [`chore/vite-3`](https://github.com/vuejs/vitepress/tree/chore/vite-3) branch.

Good to hear that. When would the `chore/vite-3` branches be merged into `main`? I will use a workaround to make #1012 pass if `chore/vite-3` still needs some time to be merged.

**Comment by brc-dd** [comment]
> When would the chore/vite-3 branches be merged into main?

It will likely take some time because there are a lot of changes, its hard to review and test them. You can add that workaround if you want. It can be removed later if Vite 3 PR is merged before your one.
