### ISSUE TITLE
Show `popover` when the mouse is over the `sidebar`

### ISSUE THREAD

**Issue by newives** [vuejs/vitepress#1018]
### Is your feature request related to a problem? Please describe.

Show `popover` when the mouse is over the `sidebar`, display specific information method Quick positioning of users

### Describe the solution you'd like

such as https://www.naiveui.com/en-US/dark/components/popover
<img width="579" alt="图片" src="https://user-images.githubusercontent.com/81661030/179704665-cf470bfa-bba7-45ec-aee5-b169b865cf63.png">

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by fi3ework** [comment]
I think the tooltip or popover on sidebar item is rarely seen. Could you provide a document site that with this usage? 🤔
