### ISSUE TITLE
localhost dead links

### ISSUE THREAD

**Issue by johanjvrens** [vuejs/vitepress#1019]
### Describe the bug

When running Vitepress I get the following dead link error messages for my localhost server: 
-(!) Found dead link `http://localhost:4000/#/...`

When I click on the links they open up without any issues.
When I set the config to ignore the dead links:
```js
import { defineConfig } from "vitepress";

export default defineConfig({
  ignoreDeadLinks: true
});
```
and try to build I still get the following error:
```sh
⠼ building client + server bundles...[vitepress] One or more pages contain dead links.
✖ building client + server bundles...
build error:
 Error: One or more pages contain dead links.
```

### Reproduction

Point a link to a local server running on localhost. In my case, I'm pointing it to [cubejs](https://cube.dev/) dev server running on localhost port 4000 `http://localhost:4000/#/build?query={}`

code in Vitepress:
```md
[link to localhost endpoint](http://localhost:4000/#/build?query={})
```

### Expected behavior

The link should not be reported as a dead link as it is working, maybe display a warning as this is a link pointing to localhost to make sure this is the desired host in my case it is.

If I set the config to ignore deadlink, it should build and not fail
```js
import { defineConfig } from "vitepress";

export default defineConfig({
  ignoreDeadLinks: true
});
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 25.68 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/opt/node@16/bin/node
    npm: 8.11.0 - /usr/local/opt/node@16/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.5
  npmPackages:
    vitepress: 1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/issues/941#issuecomment-1178590512
