### ISSUE TITLE
Switch language error when build with a base path

### ISSUE THREAD

**Issue by dewfall123** [vuejs/vitepress#103]
**Describe the bug**
Switch language error when build with a base path

**To Reproduce**
[](https://github.com/dewfall123/vitepress-issues)
1. clone [https://github.com/dewfall123/vitepress-issues](https://github.com/dewfall123/vitepress-issues)
2. run 
`yarn` 
`yarn build`
`yarn build-dev`
3. open  http://127.0.0.1:3001 and switch language several times.
It go to error path like http://127.0.0.1:3001/vhooks/vhooks/zh/index.html.

**Expected behavior**
Switch language and go to the correct path.

**System Info**
- vitepress version: 0.7.0
- vite version: v1.0.0-rc.4
- Node version: 14
- OS version: window 10

**Comment by kiaking** [comment]
Confirmed this is a bug. We should fix it.
