### ISSUE TITLE
Front Matter aside configuration is invalid

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#1030]
### Describe the bug

Hi!  

There are some pages where I don't want to show a sidebar, but `aside: false` is set in `Front Matter` and the sidebar still exists.

![image](https://user-images.githubusercontent.com/25446948/180138806-7cb53698-c79f-4553-bd70-f45bd681d06d.png)

### Reproduction

My `Front Matter` configuration is as follows:
```
---
author: Charles7c
date: 2022/7/20 22:52
aside: false
layout: doc
tags:
 - SQL
 - 网络攻击
---
```

### Expected behavior

Hide the sidebar so that my content is centered.

Taking effect as configured:
![image](https://user-images.githubusercontent.com/25446948/180139434-aa968edd-35ce-4103-82c6-f8b7e35e6e58.png)

### System Info

```shell
System:
  OS: Windows 10 10.0.19044
  CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Memory: 3.69 GB / 13.87 GB
Binaries:
  Node: 14.18.1 - D:\Develop\nodejs\node.EXE
  Yarn: 1.22.17 - D:\Develop\nodejs\node_global\yarn.CMD
  npm: 6.14.15 - D:\Develop\nodejs\npm.CMD
Browsers:
  Internet Explorer: 11.0.19041.906
npmPackages:
  vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/issues/1031#issuecomment-1191080365
