### ISSUE TITLE
The theme's docFooter configuration is invalid

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#1031]
### Describe the bug

![image](https://user-images.githubusercontent.com/25446948/180140414-cb71417c-9b94-49f6-ba65-0d41639021f4.png)
![image](https://user-images.githubusercontent.com/25446948/180141198-07ffab64-2132-43e7-a973-c4cb50bd45eb.png)

### Reproduction

My partial theme configuration is as follows:

```
import DefaultTheme from 'vitepress/theme'
import { nav } from './nav'
import { sidebar } from './sidebar'

export const themeConfig: DefaultTheme.Config = {
  logo: '/logo.jpg',
  outlineTitle: '目录', // 右侧边栏的大纲标题文本
  lastUpdatedText: '最后更新', // 最后更新时间文本, 需配置 lastUpdated 为 true
  docFooter: {
    prev: '上一页',
    next: '下一页'
  },
  // 编辑链接
  editLink: {
    pattern: 'https://github.com/Charles7c/charles7c.github.io/edit/main/repos/:path',
    text: '在 GitHub 上编辑此页面'
  },
  ...
  nav, // 导航栏
  sidebar // 侧边栏
}
```

### Expected behavior

Show the docFooter I set up.

### System Info

```shell
System:
  OS: Windows 10 10.0.19044
  CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Memory: 3.69 GB / 13.87 GB
Binaries:
  Node: 14.18.1 - D:\Develop\nodejs\node.EXE
  Yarn: 1.22.17 - D:\Develop\nodejs\node_global\yarn.CMD
  npm: 6.14.15 - D:\Develop\nodejs\npm.CMD
Browsers:
  Internet Explorer: 11.0.19041.906
npmPackages:
  vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please avoid creating multiple issues when you already know (#1003) these are fixed and will be there in the next release.
