### ISSUE TITLE
Copyright configuration rendering changed from {{}} to v-html

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#1032]
### Is your feature request related to a problem? Please describe.

Hi!

I found that I could not use HTML in the copyright configuration. I looked at the code and found that the reason was {{}}. 

![image](https://user-images.githubusercontent.com/25446948/180141436-72b6ac0a-c52c-4464-bd8b-b3da937f4e4d.png)
![image](https://user-images.githubusercontent.com/25446948/180141553-8ad0ee14-7175-41c3-ac9a-ce02600554f5.png)

### Describe the solution you'd like

I would like to support HTML rendering or more customization.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can use the `layout-bottom` slot if you need more customisation. (https://vitepress.vuejs.org/guide/theme-introduction.html#layout-slots)
