### ISSUE TITLE
How to disable auto code splitting in notation :(..) in fence?

### ISSUE THREAD

**Issue by kingcw** [vuejs/vitepress#1033]
Hi,

I'm trying to display this code block:

    ```html
    <div class="hover:(bg-blue-400 font-medium)"/>
    ```

expected output is:

```
<div class="hover:(bg-blue-400 font-medium)"/>
```

but the output is:

```
<div class="hover:bg-blue-400 hover:font-medium"/>
```

Anyway to disable this behavior and display as-is?

Thank you.

**Comment by brc-dd** [comment]
I don't think we are doing that:

![image](https://user-images.githubusercontent.com/40380293/180271741-25ab6004-327f-4b5b-8d0c-26ac7a4edeb7.png)

Can you share a minimal reproducible example?

**Comment by kingcw** [comment]
yeah, it's Unocss that does that, needs to add @unocss-ignore to that file.

Thank you for quick response.
