### ISSUE TITLE
Unable to load Layout.vue file (No loader is configured for ".vue" files)

### ISSUE THREAD

**Issue by Beriu** [vuejs/vitepress#1035]
### Describe the bug

I've been following the guide on how to set up Vitepress with a custom theme, and when I try to load a diferent vue file as a Layout it give me an error: 

> No loader is configured for ".vue" files: docs/.vitepress/theme/Layout.vue

What is more weird is that if I substitute that file with a function and and run serve the project in dev mode, while under HMR I can get it to work by replacing it back with the vue file.

### Reproduction

Clone
`git clone git@github.com:Beriu/blog.git`

Install Deps
`cd blog && npm install`

Run dev command
`npm run docs:dev`

### Expected behavior

To properly load the vue file

### System Info

```shell
System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 7.84 GB / 12.36 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Your `.vitepress/config.ts` file has issues. You can remove line 2 and line 10. `themeConfig` is a different thing than theme. If you're writing your custom one, you probably don't need `themeConfig`.

**Comment by Beriu** [comment]
Ok I understand where the confusion was, so if I  want a custom theme, I just add one in `theme/index.ts/js` and it will be picked up automatically so you don't need to pass the custom theme config to the main config file (Leaving this comment here just in case someone else was confused).
