### ISSUE TITLE
Anyway to set vue global variable?

### ISSUE THREAD

**Issue by kingcw** [vuejs/vitepress#1038]
HI,

I couldn't find where to set vue global variable.  What I wanted to do is to do a provide/inject.  For a normal vue app, it would be in src/main.ts:

```
import { createApp } from "vue";
import App from "./App.vue";

const app = createApp(App);

app.provide(name, variable);

app.mount("#app");
```

Thank you

**Comment by Charles7c** [comment]
Maybe you could take a look at this：https://vitepress.vuejs.org/guide/theme-introduction.html#using-a-custom-theme.

**Comment by Charles7c** [comment]
Or refer to my configuration: https://github.com/Charles7c/charles7c.github.io/blob/main/repos/.vitepress/theme/index.ts

**Comment by kingcw** [comment]
awesome, thank you.
