### ISSUE TITLE
Add `target="_blank"` attr to a inner link

### ISSUE THREAD

**Issue by SamWangCoder** [vuejs/vitepress#1040]
### Is your feature request related to a problem? Please describe.

I would like to add  `target="_blank"` attr to a inner link, but can not find a way to do it after read  vitepress`s docs.

### Describe the solution you'd like

Can I add a `isExternal` attr when config nav?
``` ts
function nav() {
  return [
    { text: 'Guide', link: '/guide/what-is-vitepress', activeMatch: '/guide/' },
    { text: 'Configs', link: '/config/introduction', activeMatch: '/config/' },
    { text: 'ConfigsEx', link: '/config/introduction', activeMatch: '/config/' , isExternal: true },
  ]
}
```

### Describe alternatives you've considered

``` ts
  export type NavItemWithLink = {
    text: string
    link: string
    activeMatch?: string
    isExternal?: boolen
  }


  export interface NavItemWithChildren {
    text?: string
    items: (NavItemChildren | NavItemWithLink)[]
    activeMatch?: string
    isExternal?: boolen
  }
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! This requests seems weird and is less likely to be supported officially. You can patch our NavLink component for now (this will mark all links as external):

```ts
// vite.config.ts

import type { Plugin } from 'vite';
import { defineConfig } from 'vite';

const VPLinkPatch = (): Plugin => ({
  name: 'make-all-external',
  enforce: 'pre',
  transform: (code, id) => {
    if (id.endsWith('VPLink.vue')) {
      return code.replace(/^const isExternal.*$/m, 'const isExternal = true');
    }
  },
});

export default defineConfig({
  plugins: [VPLinkPatch()],
});
```

Demo: https://stackblitz.com/edit/vite-bg3uyi?file=docs%2Fvite.config.ts

I  am closing this for now. If we see more demand regarding this in future we may consider supporting this.

**Comment by brc-dd** [comment]
Alternatively an easier approach will be to just make it external:

```
    { text: 'ConfigsEx', link: 'https://foo.bar/config/introduction', activeMatch: '/config/' },
```

**Comment by SamWangCoder** [comment]
I want to remove NavBar and Footer in a specific page that has a full screen vue component, 
so, if I can open this page independently would be great.

Thanks for your demo, I'll try modify `EXTERNAL_URL_RE`  to get done.

**Comment by brc-dd** [comment]
> I want to remove NavBar and Footer in a specific page that has a full screen vue component,

Ah, ok. So using absolute URL should work fine like I wrote in the second comment. I don't think there would be any need to patch the external url thing.

**Comment by brc-dd** [comment]
Okay! Just a tip, if you want to only externalize `/config/introduction`, then make that replace call above to something like this:

```js
      return code.replace('/^[a-z]+:/i', '/^([a-z]+:|\/config\/introduction)/i');
```

**Comment by SamWangCoder** [comment]
Thanks for your help!
