### ISSUE TITLE
Dynamic Component with External Script - 'Failed to load module script:'

### ISSUE THREAD

**Issue by akil-rails** [vuejs/vitepress#1042]
### Discussed in https://github.com/vuejs/vitepress/discussions/1041

<div type='discussions-op-text'>

<sup>Originally posted by **akil-rails** July 22, 2022</sup>
The [guide](https://vitepress.vuejs.org/guide/using-vue.html) explains:

> To use code that assumes a browser environment on import, you need to dynamically import them in proper lifecycle hooks: how to use components th

```vue
<script>
export default {
  mounted() {
    import('./lib-that-access-window-on-import').then((module) => {
      // use code
    })
  }
}
</script>
```

When the library is directly referenced (instead of a dependency), the load fails. Is this the expected behaviour? If so, the docs could mention that.

`mermaid:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

```vue
<script>
export default {
  mounted() {
    import('https://cdn.skypack.dev/mermaid').then((module) => {
      // use code
    })
  }
}
</script>
```
</div>

### Steps to reproduce
```
git clone git@github.com:akil-rails/vitepress-starter.git
cd vitepress-starter
pnpm i
pnpm run docs:build
pnpm run docs:serve
```
1. Open the URL in chrome
2. In chrome developer tools/console, you'll see the message 
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by brc-dd** [comment]
Actually that error is because invalid `modulepreload` link is being added:

```html
<link rel="modulepreload" href="/base/https://cdn.skypack.dev/mermaid">
```

**Comment by brc-dd** [comment]
Even with the fix, I don't think mermaid works like that.

**Comment by akil-rails** [comment]
> Even with the fix, I don't think mermaid works like that.

Yes, mermaid isn't working - I suppose this is because whitespace is stripped out .
