### ISSUE TITLE
code group surpport

### ISSUE THREAD

**Issue by Sepush** [vuejs/vitepress#1043]
### Is your feature request related to a problem? Please describe.

when we write a guide docs.
We need a goup of code blocks to tell user how to do something.
If surpport code group I will become quite convenient.

### Describe the solution you'd like

I prefer nuxt's solution like the following

UI:
https://v3.nuxtjs.org/guide/directory-structure/layouts#overriding-a-layout-on-a-per-page-basis
![图片](https://user-images.githubusercontent.com/39197136/180388145-13ca68bb-7e58-4125-b87c-aed7dc3b17ee.png)

Grammar:
https://github.com/nuxt/framework/blob/d135608ef0d607259c0ae6f5156c8f46ff78ddc3/docs/content/2.guide/3.directory-structure/7.layouts.md?plain=1#L140-L175

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! This is on the v1 milestone. We'll add this. You can comment your suggestions on #728 .

**Comment by Sepush** [comment]
> Hi! This is on the v1 milestone. We'll add this. You can comment your suggestions on #728 .

Got it.
