### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': 'staging,name:test' is not a valid attribute name.

### ISSUE THREAD

**Issue by xinconan** [vuejs/vitepress#1044]
### Describe the bug

md file with table that contains like ` { app: { platform: "staging", name: "test" }` , It's cause error:  
runtime-dom.esm-bundler.js:216 Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': 'staging,name:test' is not a valid attribute name.

### Reproduction

md file contains table like this, It's cause error
```md
| 命令：                                                            | `env` 参数值：                                   |
| -------------------------------------------------------------- | -------------------------------------------- |
| npx webpack --env app.platform="staging" --env app.name="test" | { app: { platform: "staging", name: "test" } |
```

### Expected behavior

should generate html exactly.

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.85 GB / 7.89 GB
  Binaries:
    Node: 14.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^0.22.4 => 0.22.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Refer: https://github.com/vuejs/vitepress/issues/449
