### ISSUE TITLE
markdown.lineNumbers doesn't work under default theme

### ISSUE THREAD

**Issue by chengpeiquan** [vuejs/vitepress#1046]
### Describe the bug

According to [the configuration option](https://vitepress.vuejs.org/config/app-configs.html#markdown) of the documentation, this option is enabled:

```ts
// .vitepress/config.ts
export default defineConfig({
  // ...
  markdown: {
    lineNumbers: true,
  },
  // ...
})
```

Not getting the expected result showing line numbers , by the way, the code snippets of the documentation also have no line numbers:

![1](https://user-images.githubusercontent.com/24845958/180411252-2a968b00-893f-4768-b52d-c32b83fd7804.jpg)

### Reproduction

```ts
// .vitepress/config.ts
export default defineConfig({
  // ...
  markdown: {
    lineNumbers: true,
  },
  // ...
})
```

### Expected behavior

Show the code line numbers.

![2](https://user-images.githubusercontent.com/24845958/180412761-1fae7645-d554-4dbb-bd55-c8cd0fe3a2c4.jpg)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 8.46 GB / 15.91 GB
  Binaries:
    Node: 16.15.0 - D:\Programs\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - D:\Programs\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Its working fine for me:

![image](https://user-images.githubusercontent.com/40380293/180414499-ea3c6f69-01e5-4823-a259-f64e963d612f.png)

You probably need to restart your dev server.

> by the way, the code snippets of the documentation also have no line numbers:

because we haven't enabled it in our docs.

**Comment by chengpeiquan** [comment]
> Its working fine for me:
> 
> ![image](https://user-images.githubusercontent.com/40380293/180414499-ea3c6f69-01e5-4823-a259-f64e963d612f.png)
> 
> You probably need to restart your dev server.
> 
> > by the way, the code snippets of the documentation also have no line numbers:
> 
> because we haven't enabled it in our docs.

Yeah! It's fine after restarting! Because other options support hot reload, so I ignored the restart operation, thx!
