### ISSUE TITLE
Blur backdrop filter on navbar noticeably impacts scroll performance

### ISSUE THREAD

**Issue by vberlier** [vuejs/vitepress#1049]
### Describe the bug

The blurred background on the navbar looks nice but I noticed that it causes some lag when scrolling. I used the "Rendering" tab in the chrome devtools to measure the actual impact on performance and it looks like disabling the `backdrop-filter` property in the inspector improves the framerate by almost 30%.

This is a common problem that plagues the "frosted background" trend. If the content behind an element with a blurred backdrop updates rapidly (such as when scrolling), the page will start to stutter. This is even more noticeable on 4k displays where the blur filter has to process a lot more pixels.

![image](https://user-images.githubusercontent.com/24430071/180603883-9b99daf5-93e2-4658-9b06-88d61437101b.png)

| `backdrop-filter` enabled | `backdrop-filter` disabled |
| - | - |
| ![image](https://user-images.githubusercontent.com/24430071/180603945-4f370a68-3340-423d-93e9-6df938cd4dfe.png) | ![image](https://user-images.githubusercontent.com/24430071/180603925-de05287c-ce3b-466d-b24e-a1aab03d35fd.png) |

### Reproduction

To gather the above metrics I opened the official [vitepress website](https://vitepress.vuejs.org/guide/theme-introduction.html) and held the down arrow key to scroll continuously for a few seconds. For testing without the blur effect I disabled the `backdrop-filter` property on the `VPNavBar` component in the inspector.

### Expected behavior

This could be solved by removing the blur effect or only enabling it at low dpi using a media query. Another option would be to make it easy to disable the blur effect when extending the default theme.

### System Info

```shell
Chrome 103, Windows
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by gmqiyue** [comment]
has same problem on macos12.5/chrome 106

**Comment by kiaking** [comment]
I've removed blur background due to design finalization at #1790.
