### ISSUE TITLE
Update snippet importing syntax to look more markdownish

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#1051]
The syntax from [markdown-it-vuepress-code-snippet-enhanced](https://github.com/fabioaanthony/markdown-it-vuepress-code-snippet-enhanced) looks more markdown-like and extendable (I saw you have noticed that @brc-dd ), so I chose to implement it in vuepress-next (not as powerful as that plugin though).

Anyway, the `<<<` syntax has being always marked as `beta` in VuePress v1 ([link](https://v1.vuepress.vuejs.org/guide/markdown.html#import-code-snippets)), so we could still consider changing it.

_Originally posted by @meteorlxy in https://github.com/vuejs/vitepress/issues/875#issuecomment-1178450949_

**Comment by ringeringeraja** [comment]
I totally agree with you. Neovim highlights  the "<<<" as syntax error for some reason, moreover specifying a VSCode region alongside with a language (e.g. @/source/component.vue#props{typescript}) doesn't seem to work.

**Comment by brc-dd** [comment]
> moreover specifying a VSCode region alongside with a language (e.g. @/source/component.vue#props{typescript}) doesn't seem to work.

That language thing was added in #875, so its not in the latest release yet. It works fine though:

![image](https://user-images.githubusercontent.com/40380293/180657388-9e3be565-0ee3-43f6-8805-1a97d844f935.png)
