### ISSUE TITLE
Page's width is not right on mobile screen with long words

### ISSUE THREAD

**Issue by gyhyfj** [vuejs/vitepress#1057]
### Describe the bug

Page's width is not right on mobile screen with long words

### Reproduction

If md file have long word like this:

```
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Symbol
```
or this:
```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

the width of page on mobile could be wrong.   (my  browser is chrome, android 12)
![1](https://user-images.githubusercontent.com/98264874/180673708-2e3adb84-0114-4477-81bc-c00a8fbaa40e.png)

### Expected behavior

should add this rule?

```css
*{
  word-break: break-word;
}
```

### System Info

```shell
chrome
android 12
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by xfq** [comment]
PR: https://github.com/vuejs/vitepress/pull/1058
