### ISSUE TITLE
Frontmatter JSON not applying, also Frontmatter YAML is applied twice

### ISSUE THREAD

**Issue by staghouse** [vuejs/vitepress#1063]
### Describe the bug

Frontmatter properties as JSON does not seem to be applying to pages using the following:

```
---
{
  'title': 'Changelogs',
  'meta':
    [
      { 'property': 'og:title', 'content': 'Changelogs' },
      { 'name': 'description', 'content': 'Various Changelogs.' },
      { 'property': 'og:description', 'content': 'Various Changelog.' },
      { 'name': 'keywords', 'content': 'changelogs' },
    ],
}
---
```

additionally, when using yaml the properties are not "merged" but added in addition to the regular meta definitions in `/.vitepress/config.js` resulting in double tags.

### Reproduction

Apply Frontmatter meta configuration to any index.md page and view the rendered content. Only the title and description data in `/.vitepress/config.js` is applying to the page.

### Expected behavior

The meta tags in the `<head>` of the rendered page should match what is in the Frontmatter of the markdown page.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 168.33 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.2
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> when using yaml the properties are not "merged" but added in addition to the regular meta definitions in /.vitepress/config.js resulting in double tags.

This was fixed. Refer #975 for details. It'll be there in the next release.

**Comment by brc-dd** [comment]
Closing this for now. Feel free to comment if the issue persists.
