### ISSUE TITLE
md set formatter head tag but rendered html not have head tag

### ISSUE THREAD

**Issue by Otto-J** [vuejs/vitepress#1069]
### Describe the bug

1. see https://github.com/docschina/vue-tips-weekly/blob/main/posts/070.md . the file front-matter set head link 
2. clone, install, build
3. see view-source:https://vue-tips-weekly.vercel.app/070.html , the rendered source html file not have head link 
4. visit https://vue-tips-weekly.vercel.app/070.html in browser, have the head link

### Reproduction

- source https://github.com/docschina/vue-tips-weekly/blob/main/posts/070.md
- site https://vue-tips-weekly.vercel.app/070.html 

### Expected behavior

rendered source html file have head link

### System Info

```shell
"vitepress": "^1.0.0-alpha.4",
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I can see that link:

![image](https://user-images.githubusercontent.com/40380293/180985710-6732440f-30d5-44e0-9b88-e85a359b0f6c.png)

Probably it has something to do with your cache. Try hard reloading (ctrl+shift+r).
