### ISSUE TITLE
algolia search link is wrong

### ISSUE THREAD

**Issue by ZxBing0066** [vuejs/vitepress#1074]
### Describe the bug

When I search for something in vitejs.dev, the links in search results aren't right.

### Reproduction

Search `commonjsOptions`, the actual link should be `https://vitejs.dev/config/build-options.html#build-commonjsoptions` rather than `https://vitejs.dev/config/#build-commonjsoptions`, it seems like an old link before doing page-split.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/5652404/181174804-3a5ba1b5-f70d-4dcb-a8c9-f9571bd44c90.png">

### Expected behavior

give the right link

### System Info

```shell
MacOS chrome
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Fixed by https://github.com/vitejs/vite/commit/b26b84b568388790c78577e09868aadddad9799d . It's working fine in https://main.vitejs.dev and will work fine on https://vitejs.dev from the next version.

**Comment by ZxBing0066** [comment]
> Fixed by [vitejs/vite@b26b84b](https://github.com/vitejs/vite/commit/b26b84b568388790c78577e09868aadddad9799d) . It's working fine on https://main.vitejs.dev and will work fine on https://vitejs.dev from the next version.

👌 thanks for your reply.
