### ISSUE TITLE
VPTeamMembers -> SocialLinks -> custom svg not working

### ISSUE THREAD

**Issue by awacode21** [vuejs/vitepress#1075]
### Describe the bug

When you build up your team page and for the team member social links you would like to set your own icon. For example email icon for email link. Regarding the docs: https://vitepress.vuejs.org/config/theme-configs.html#sociallinks you should be able to set:

```
links: [
        { 
            icon: {
                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);"><path fill="currentColor" d="m20 8l-8 5l-8-5V6l8 5l8-5m0-2H4c-1.11 0-2 .89-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2Z"/></svg>'
            },
            link: 'mailto:john@doe.de'
        },
    ]
```
but the icon will not be rendered:
<img width="1419" alt="Bildschirmfoto 2022-07-28 um 00 12 43" src="https://user-images.githubusercontent.com/30939926/181381626-bdf02d0d-973c-4be2-87e8-f99f4c93ca18.png">

### Reproduction

https://stackblitz.com/edit/vitepress-sociallinks-custom-svg?file=docs%2Findex.md,package.json&terminal=dev

### Expected behavior

When defining a custom icon like defined on the docs:
https://vitepress.vuejs.org/config/theme-configs.html#sociallinks

i would expect this svg to get rendered.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
    Memory: 24.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you test this locally using our main branch. Probably that svg feature is not in the latest release.
