### ISSUE TITLE
Allow multiple entrypoints

### ISSUE THREAD

**Issue by mkilpatrick** [vuejs/vitepress#1077]
### Is your feature request related to a problem? Please describe.

`mainEntryPointFilePath` only allows a single entrypoint.

Let's say I have a repo that has multiple exports and types:
```
"exports": {
    ".": "./dist/index.js",
    "./foo": "./dist/foo/foo.js",
    "./util": "./dist/util/index.js"
  },
  "typesVersions": {
    "*": {
      "*": [
        "dist/types/src/index.d.ts"
      ],
      "foo": [
        "dist/types/src/foo/index.d.ts"
      ],
      "util": [
        "dist/types/src/util/index.d.ts"
      ]
    }
  },
```

I can't generate correct docs based on this. The only thing you can do is export all types at the root, but that is incorrect for this project structure.

### Describe the solution you'd like

Allow multiple entrypoints that reflects the setup of the repo.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What does this have to do with VitePress? We don't have anything like `mainEntryPointFilePath`.
