### ISSUE TITLE
How to use the search function, there is no documentation yet

### ISSUE THREAD

**Issue by sishen654** [vuejs/vitepress#1078]
### Describe the bug

none

### Reproduction

none

### Expected behavior

none

### System Info

```shell
none
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to apply for Algolia Docsearch, if it gets approved you need to configure crawler etc. there and add your Algolia config in `.vitepress/config.ts` like this: 

https://github.com/vuejs/vitepress/blob/bc47197f7b7c20014b322877edcef56e1374c012/docs/.vitepress/config.ts#L34-L38

**Comment by sishen654** [comment]
thank you!I'll give it a try.

**Comment by Szymon-dziewonski** [comment]
@brc-dd could you maybe help out how to set up crawler? i cant manage to run it to have index for algolia

**Comment by sishen654** [comment]
> @brc-dd could you maybe help out how to set up crawler? i cant manage to run it to have index for algolia

I'm sorry I don't have time to do this crawler yet, you can look at the user manual on the official website or some libraries that use crawler, such as Vite or Vue3

**Comment by Szymon-dziewonski** [comment]
@sishen654 maybe Im wrong but I read and heard from my friend who did it, crawler is available for some pro acc, for open source you need to file for it via this form https://www.algolia.com/for-open-source/ then they set up crawler for your page, I did it, when I will have some update will write here :)

**Comment by brc-dd** [comment]
@Szymon-dziewonski Yeah, when your docsearch account is approved, you'll get access to an admin console where you can configure the crawler. These are their recommended templates: https://docsearch.algolia.com/docs/templates/ . You can customize them accordingly if you're getting some weird results.

**Comment by e3d** [comment]
Search is essential for vitepress. Not every projects get supported by agolia docsearch. It would be great for vitepress to have its own.

**Comment by isuke01** [comment]
Yes What about the private repos? I could use standard algolia, just Have no idea how to setup crawler/push data from VP?
