### ISSUE TITLE
References cites support

### ISSUE THREAD

**Issue by Sepush** [vuejs/vitepress#1081]
### Is your feature request related to a problem? Please describe.

I need references cited in the paper in the docs like writing papers.

### Describe the solution you'd like

 references cited support can jump each other
![image](https://user-images.githubusercontent.com/39197136/181462944-f6f4c002-e17d-4043-9721-e29dead92019.png)
Docusaurus and GitHub support this.but not work for VitePress😭
![image](https://user-images.githubusercontent.com/39197136/181464655-d9281507-5aae-4e31-8496-966e57a7dfda.png)

eg.

```
sometext[^1]
[^1]: something
```
sometext[^1]
[^1]: something

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Sepush** [comment]
@brc-dd PTAL

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/discussions/704#discussioncomment-2872963

**Comment by Sepush** [comment]
> [#704 (comment)](https://github.com/vuejs/vitepress/discussions/704#discussioncomment-2872963)

Thank you for your quick response and useful info ,I will try it.not familiar with markdown-it.
Sorry to bother you.
