### ISSUE TITLE
ignoreDeadLinks doesn't work

### ISSUE THREAD

**Issue by Uncontained0** [vuejs/vitepress#1084]
### Describe the bug

When I enable the `ignoreDeadLinks` option in `/docs/.vitepress/config.js`, `yarn docs:build` still fails with the reason being `One or more pages contain dead links.`

### Reproduction

Create a new vitepress project.
In `/docs/.vitepress/config.js`:
```js
export default {
    ignoreDeadLinks: true,
    title: "test",
    description: "test stuff"
}
```

In `/docs/api/index.md`:
```md
[test](./test)
```

### Expected behavior

It is expected that the build process will succeed, because it should ignoreDeadLinks instead of failing because of them.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz       
    Memory: 6.63 GB / 15.93 GB
  Binaries:
    Node: 18.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)    
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by cy920820** [comment]
It'll be there in alpha-5.
