### ISSUE TITLE
Suggested support for two-level sidebars

### ISSUE THREAD

**Issue by jarvis-tang** [vuejs/vitepress#1085]
### Is your feature request related to a problem? Please describe.

抱歉，我英文不好，所以我写中文了。

我是从 VuePress 迁移来的用户，我有一个场景两级侧边栏的场景。

数据库文档，分为「表和字段」、「字典数据」、「默认配置数据」等一级栏目，其中数据表很多，所以「表和字段」侧边栏又对数据表进行了归类，形成了第二级侧边栏，效果如下图：

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/22316055/181681223-b143cbfe-0729-43af-bffb-9a136b8937b9.png">

### Describe the solution you'd like

如问题描述，建议 VitePress 支持两级侧边栏，希望能被采纳，谢谢。

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! This was already added (#851). It'll be there in the next release.
