### ISSUE TITLE
Navbar for i18n

### ISSUE THREAD

**Issue by fugaku** [vuejs/vitepress#1089]
### Is your feature request related to a problem? Please describe.

Currently, when changing languages, the navbar links stay the same.

### Describe the solution you'd like

Navbar should have links based on the languages selected.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
i18n is still a WIP. You can track #631 for progress.
