### ISSUE TITLE
Empty Layout option

### ISSUE THREAD

**Issue by darkmasta** [vuejs/vitepress#1091]
### Is your feature request related to a problem? Please describe.

I want to create a landing page for a documentation and I dont any layout option. How can I create a landing that points to a Vue component directly?

### Describe the solution you'd like

```
---
layout: none
---

<Landing />
 
<script setup>
import Landing from "./components/Landing.vue"

</script>
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`layout: page` ?

**Comment by darkmasta** [comment]
I dont want header too. `layout: page` brings header to top.

**Comment by brc-dd** [comment]
> I dont want header too. layout: page brings header to top.

Ah, okay! We should probably add some option to hide nav and footer as well. For now you can do something like this inside your `Landing` component:

```vue
<script setup>
import { onMounted, onUnmounted } from 'vue'
onMounted(() => {
  document.body.classList.add('no-nav')
})
onUnmounted(() => {
  document.body.classList.remove('no-nav')
})
</script>

<style>
.no-nav .VPNav {
  display: none;
}
</style>
```

**Comment by darkmasta** [comment]
I understand strict layout options in inner docs but landing should very customizable. Just for landing this feature request is kinda needful.
