### ISSUE TITLE
`[[toc]]` not working after using custom containers

### ISSUE THREAD

**Issue by trwnh** [vuejs/vitepress#1093]
### Describe the bug

Placing a table of contents shortcode after a custom container (tip, warning, danger, etc) will cause the table of contents element to render empty with no children.

### Reproduction

index.md:

```
# Test page

::: warning
This will cause the toc to be empty
:::

[[toc]]

## section 1
## section 2
### subsection 2a
## section 3
```

### Expected behavior

The TOC outline should be populated with children but instead it just renders as `<nav class="table-of-contents"></nav>`

### System Info

```shell
System:
    OS: Linux 5.18 Arch Linux
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 91.45 GB / 125.72 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    npm: 8.15.1 - /usr/bin/npm
  Browsers:
    Chromium: 103.0.5060.134
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by meteorlxy** [comment]
Caused by #768.

Seems that the token structure is somehow broken by the `md.renderInline` :thinking:

**Comment by meteorlxy** [comment]
Oh I know the reason. The headers are collected inside the toc-plugin, and calling `md.renderInline` will override the previously collected headers before they are rendered 🤦‍♂️
