### ISSUE TITLE
does not render some styles that is handy

### ISSUE THREAD

**Issue by lospringliu** [vuejs/vitepress#11]
# vuepress special markdown

## topic of contents
::: details code
```
[[toc]]
```
:::
[[toc]]

## emoji
::: details code
```
:tada: :100:
```
:::
:tada: :100:

## containers

::: tip
This is a tip
:::

::: warning
This is a warning
:::

::: danger
This is a dangerous warning
:::

::: details
This is a details block, which does not work in IE / Edge
:::

::: danger STOP
Danger zone, do not proceed
:::

::: details codes
```js{2}
console.log("Hello, VuePress!")
console.log("Hello, CICD!")
```
:::

## tables
::: details codes
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```
:::
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

**Comment by lospringliu** [comment]
![image](https://user-images.githubusercontent.com/9952753/81485853-8702c000-921e-11ea-8e70-7a7d9f64a8c7.png)

**Comment by lospringliu** [comment]
![image](https://user-images.githubusercontent.com/9952753/81485869-b1547d80-921e-11ea-965e-48afdd6d44d1.png)

**Comment by yyx990803** [comment]
This is still WIP - please don't open issues for features that are simply not implemented yet.
