### ISSUE TITLE
aside frontmatter config not doing as the docs suggest

### ISSUE THREAD

**Issue by CodyBontecou** [vuejs/vitepress#1100]
### Describe the bug

Adding the following frontmatter, as suggested in the [docs](https://vitepress.vuejs.org/config/frontmatter-configs.html#aside) is not hiding the aside content.
```
---
aside: false
---
```

### Reproduction

1. Place `aside: false` within the file's frontmatter.
2. View `aside` HTML and CSS still loading into the webpage.

### Expected behavior

I expect that the website will no longer render any `aside` related HTML or CSS after adding the `aside: false` frontmatter.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 807.22 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.6
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It'll be there in the next release.

**Comment by CodyBontecou** [comment]
Sound good. I just wanted to let you know in case you didn't. I was able to get past it using your suggested CSS. 

```
<style>
.aside {
  display: none !important;
}
</style>
```

**Comment by brc-dd** [comment]
Yeah that will work, but it will hide aside from all the pages, while using frontmatter it can be customized on per page basis.

**Comment by CodyBontecou** [comment]
I added that style tag to the specific markdown file that I didn't want the aside bar to show in and it hid it on only that page.

**Comment by brc-dd** [comment]
> I added that style tag to the specific markdown file that I didn't want the aside bar to show in and it hid it on only that page.

https://stackblitz.com/edit/vite-omtebl?file=docs%2Findex.md,docs%2Ffoo.md -- Doesn't seem to work for me (aside is hidden on both `/foo` and `/index`), are you doing anything different?

**Comment by CodyBontecou** [comment]
Odd, the CSS styling works locally in dev but not post-build.

**Comment by yzh990918** [comment]
> I added that style tag to the specific markdown file that I didn't want the aside bar to show in and it hid it on only that page.

I have the same issue.

**Comment by CodyBontecou** [comment]
> > I added that style tag to the specific markdown file that I didn't want the aside bar to show in and it hid it on only that page.
> 
> 
> 
> I have the same issue.

Try the aside frontmatter. Looks to be working now.
