### ISSUE TITLE
How do I get data for all articles? including frontmatter, link

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#1106]
Is there an API for that?

**Comment by Charles7c** [comment]
I found a solution that uses `fast-glob` and `gray-matter` to traverse the retrieval, but it felt cumbersome to write.

**Comment by Charles7c** [comment]
If no API is provided, do you have a better solution ?  thanks

**Comment by brc-dd** [comment]
> Is there an API for that?

No, not right now. You can track #96.
