### ISSUE TITLE
how to Custom compilation result directory

### ISSUE THREAD

**Issue by deyihu** [vuejs/vitepress#1111]
### Is your feature request related to a problem? Please describe.

default directory is /docs/.vitepress/dist

I hope I can customize the directory of the compilation package

### Describe the solution you'd like

```js
//config.js


export default{
// add output options config
  output:{
    path:'/dist/' ,//default value is /docs/.vitepress/dist/
  }

}

```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`outDir` probably. Use `defineConfig` it'll show these kind of things.
