### ISSUE TITLE
How can I make socialLinks: this configuration can be displayed normally in config.js

### ISSUE THREAD

**Issue by 1378056564** [vuejs/vitepress#1115]
### Is your feature request related to a problem? Please describe.

socialLinks:[
         {
              icon: {
                svg: '<svg></svg>'
              },
              link: '...'            }]

### Describe the solution you'd like

 I want this configuration to display properly. Or add QQ, WeChat, email, etc.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It'll be there in the next release.
