### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by Tyh2001** [vuejs/vitepress#1120]
### Describe the bug

很多时候在 `vitepress` 中难免使用到 `document`，但是 `vitepress` 使用服务端渲染方式，如何避免其打包的错误呢？

有什么第三方插件推荐或者配置项吗？

<hr />

It is inevitable to use `document` in `vitepress` many times, but how to avoid the packaging error when` vitepress` uses the server-side rendering method?

Are there any third-party plug-in recommendations or configuration items?

### Reproduction

```vue
<script setup>
  console.log(document)
</script>
```
![ee83828ee778bc7dddf33a5ace0a7b4](https://user-images.githubusercontent.com/73180970/182996499-5f7ffd20-3af7-4275-aff2-8a3fb66f2edd.jpg)

### Expected behavior

Build ok

### System Info

```shell
"vitepress": "^1.0.0-alpha.4",
"vue": "^3.2.33"
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by dewfall123** [comment]
https://vitepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions
