### ISSUE TITLE
Can expose the frontmatter to the md object?

### ISSUE THREAD

**Issue by dewfall123** [vuejs/vitepress#1122]
### Is your feature request related to a problem? Please describe.

I write a VirePress md plugin in this [project](https://dewfall123.github.io/ruabick/en/guide/). And i wanted to use frontmatter data in the markdown plugin, but I had to re-parse the file contents to get it. 

It would be much better to expose frontmatter to `md` object like `md.__path`
```ts
  md.renderer.rules.html_block = (tokens, idx, ...args) => {
    ...
    const mdContent = fsExtra.readFileSync(md.__path);
    const { data: frontmatter } = matter(mdContent);
    ...
  };
```

### Describe the solution you'd like

https://github.com/vuejs/vitepress/blob/main/src/node/markdownToVue.ts#L69

```ts
const { content, data: frontmatter } = matter(src)

md.__path = file
md.__relativePath = relativePath
// add this
md.__frontmatter = frontmatter
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
#856 will fix this
