### ISSUE TITLE
When clicking on the favorite and delete buttons in the docSearch box, the link will jump

### ISSUE THREAD

**Issue by zonemeen** [vuejs/vitepress#1139]
### Describe the bug

When clicking on the favorite and delete buttons in the docSearch box, the link will jump.

![docSearch-button-bug](https://user-images.githubusercontent.com/44596995/183326222-d6e9057b-9eee-43e7-9028-e55448beb8af.gif)

### Reproduction

https://vitepress.vuejs.org/

### Expected behavior

When clicking on the favorite and delete buttons in the docSearch box, the link do not jump.

![docSearch-button-normal](https://user-images.githubusercontent.com/44596995/183326368-0bfb4bf1-87f2-4f29-9535-6b44f27ee92d.gif)

![docSearch-button](https://user-images.githubusercontent.com/44596995/183326350-6234b0ca-f8d3-4a96-9935-6cf0705a041e.gif)

### System Info

```shell
System:
  OS: Windows 10 10.0.19044
  CPU: (8) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
  Memory: 2.59 GB / 15.9 GB
Binaries:
  Node: 16.10.0 - C:\Program Files\nodejs\node
  Yarn: 1.22.17 - C:\Program Files\nodejs\yarn
  npm: 7.24.0 - C:\Program Files\nodejs\npm
  pnpm: 7.2.1 - C:\Program Files\nodejs\pnpm
Browsers:
  Chromium (104.0.5112.79)
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
@brc-dd Hi, I submitted a PR that included a solution.

**Comment by brc-dd** [comment]
Sorry, but this fix should not be required at our end. According to HTML5 spec, a button cannot be nested inside an anchor tag. DocSearch is creating invalid HTML. I'll create an issue there.

**Comment by zonemeen** [comment]
Ok, I will close this pr 😀
