### ISSUE TITLE
Hydration completed but contains mismatches when using Github pages

### ISSUE THREAD

**Issue by laolarou726** [vuejs/vitepress#1143]
### Describe the bug

The browser console prints Hydration completed but contains mismatches when deploying the site using Github pages. And the page switch does not work as expected.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/25716486/183507530-a390b50c-49e1-4349-a5ba-e1add6883280.png">
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/25716486/183507583-86f736b4-7954-40e1-a5aa-a89298d68c72.png">

### Reproduction

Here is a reproduced repo: https://github.com/Corona-Studio/CSKB_Hosting

### Expected behavior

The page switch buttons should work after a click.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 13.26 GB / 31.82 GB
  Binaries:
    Node: 18.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\node_modules\.bin\yarn.CMD
    npm: 8.13.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.47)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by xfq** [comment]
I cloned the repo using `git clone --recurse-submodules https://github.com/Corona-Studio/CSKB_Hosting.git` and tried both `yarn run docs:dev` and `yarn run docs:build && yarn run docs:serve` and clicked through a few pages, but couldn't reproduce the issue.

**Comment by laolarou726** [comment]
It seems this error only exist in Github Pages deploy, here is the Github Page for the test repo: https://kb.corona.studio/
As you can see in the console, there is the error:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/25716486/183683501-d7a48843-e6bf-45e1-b4e8-9e6ae97dbc6d.png">

**Comment by brc-dd** [comment]
Are you using CloudFlare? It is likely you have auto minify enabled there.

**Comment by laolarou726** [comment]
Yeah, I'm using Cloudflare CDN with auto minify.

**Comment by brc-dd** [comment]
Disable auto minify for HTML, it would work. It is already written in the docs.

**Comment by laolarou726** [comment]
Got it. Thank you so much!

**Comment by chenyo2691** [comment]
一样的错误，但我没有使用githubpages，而是放到了自己服务器下的nginx，请问是怎么解决的？

**Comment by laolarou726** [comment]
@chenyo2691 参考：
<img width="569" alt="image" src="https://user-images.githubusercontent.com/25716486/184218312-b85a63f1-93e6-4989-a799-e5fa8a956504.png">

检查 Nginx 是否有任何自动优化 JS/HTML 资源的措施。如果有，尝试禁用。
