### ISSUE TITLE
I want to deploy to Github Pages, Vercel, Netlify at the same time, but something went wrong.

### ISSUE THREAD

**Issue by guhl0427** [vuejs/vitepress#1146]
### Describe the bug

![image](https://user-images.githubusercontent.com/22868220/183595065-243c1e1d-3184-467d-b7fd-f1a6a1985a4d.png)

I set `base` to `'/vitepress-docs/'` in `config.js`, and I deployed it to Github Pages successfully.

[Github Pages](https://guhl0427.github.io/vitepress-docs/)

With the same config, I deployed  it to Vercel or Netlify failed.

[Vercel](https://vitepress-docs-swart.vercel.app/)
[Netlify](https://guhlblog.netlify.app/)

Then I had tried set `base` to `'/'`, it deployed successfully in Vercel or Netlify, but failed in Github Pages.

### Reproduction

When I set `base` to `'/vitepress-docs/'` in `config.js`

Results of deployment:
+ [Github Pages(success)](https://guhl0427.github.io/vitepress-docs/)
+ [Vercel(failed)](https://vitepress-docs-swart.vercel.app/)
+ [Netlify(failed)](https://guhlblog.netlify.app/)

When I set `base` to `'/'` in `config.js`

Results of deployment:
+ Github Pages(failed)
+ Vercel(success)
+ Netlify(success)

### Expected behavior

I want to deploy to Github Pages, Vercel, Netlify with the same `config.js` at the same time.

Maybe I need do some extra configuration When I deploy to Vercel or Netlify.

![image](https://user-images.githubusercontent.com/22868220/183601295-a0fc98f8-e596-40a3-bd8c-c0b3296c5d50.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 5.25 GB / 15.88 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.80
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Refer this setup for your GitHub Pages: https://github.com/brc-dd/vitepress-pages-action/blob/main/.github/workflows/pages.yml

No need to specify `base` in your config. :)

**Comment by guhl0427** [comment]
Thanks for your help
