### ISSUE TITLE
custom containers style option

### ISSUE THREAD

**Issue by meganmeiyang** [vuejs/vitepress#1157]
### Is your feature request related to a problem? Please describe.

Noticing that there is a distinct difference from vue press custom containers to that of vite's

## vue press
<img width="784" alt="Screenshot 2022-08-11 at 3 38 20 PM" src="https://user-images.githubusercontent.com/1858427/184088154-0c171530-b416-4fab-96a9-4f587e8220dc.png">

## vite press
<img width="734" alt="Screenshot 2022-08-11 at 3 38 30 PM" src="https://user-images.githubusercontent.com/1858427/184088178-03b9564b-e9b9-4ba6-a197-f64c3249a923.png">

### Describe the solution you'd like

I know that the color can be overridden in https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/styles/vars.css

but, the for the style difference for this line 
<img width="76" alt="Screenshot 2022-08-11 at 3 53 52 PM" src="https://user-images.githubusercontent.com/1858427/184088784-33fdfeaf-115e-47bc-b43d-be355ef67f7d.png">

is it possible to expose an option to be configured, like
```
themeConfig : {
    logo: xxx,
    customContainer: {
        withLeftBorder: true,
        cornerRadius: "6px"
    }
}
```

Effect:
<img width="223" alt="Screenshot 2022-08-11 at 4 03 14 PM" src="https://user-images.githubusercontent.com/1858427/184090149-ca7ddd87-d574-4a4a-8704-d594588f7f3c.png">

### Describe alternatives you've considered

Alternatively,
these two properties can be exposed in css variables: https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/styles/vars.css

something like: 
```
//add corner radius
--vp-custom-block-border-radius: 6px;
//remove border, add lable left border
--vp-custom-block-info-border: none;
--vp-custom-block-info-left-border: var(--vp-c-green-darker);
--vp-custom-block-info-left-border-width: 5px 

```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can't you just override this using custom styles?

```css
.vp-doc .custom-block.tip {
  border-left-width: 6px;
}
```

**Comment by meganmeiyang** [comment]
yep it works 😂😅 thanks
<img width="157" alt="Screenshot 2022-08-12 at 9 15 22 AM" src="https://user-images.githubusercontent.com/1858427/184267451-3e61ac68-77c3-4356-9c7b-aa146b5226d5.png">
