### ISSUE TITLE
Broken Kotlin syntax hightlighting

### ISSUE THREAD

**Issue by SlamaFR** [vuejs/vitepress#1171]
### Describe the bug

I'm writing code blocks in Java and Kotlin but the Kotlin ones do not render correctly. There no 'Kt' or 'Kotlin' mention in the upper right corner like other languages and the syntax hightlighting is very poor.

### Reproduction

Write a code block with Kotlin code :
~~~
```kotlin
val notchHead = SkullBuilder()
    .ownerName("notch")
    .build()
```
~~~

Look at the produced result

### Expected behavior

The code block should mention 'Kotlin' in the upper right corner and the code should be correctly colored.

### System Info

```shell
❯ npx envinfo --system --npmPackages vitepress --binaries --browsers
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 78.88 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.4
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Additional context

Just to compare, here is a working block using Java syntax

![](http://i.slama.io/wfjkBjA3sE)

And here is a broken Kotlin one

![](http://i.slama.io/g7h3PYCwSv)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Regarding syntax highlighting, you can create an issue on Shiki's GitHub. And for that top corner thing, it was fixed and will be there in the next release.
