### ISSUE TITLE
alpha.5手机浏览器无法点击nav栏

### ISSUE THREAD

**Issue by yyrc** [vuejs/vitepress#1183]
### Describe the bug

alpha.5手机浏览器无法点击nav栏，alpha.4看到是正常的，电脑浏览器模拟设备仿真查看也是一样，应该是生成的时候产生的bug

### Reproduction

alpha.5手机浏览器无法点击nav栏
或者
电脑 浏览器模拟手机访问也是一样的bug

### Expected behavior

alpha.5手机浏览器无法点击nav栏

### System Info

```shell
浏览器
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Charles7c** [comment]
昨晚这个问题已经修复了，等 alpha.5 正式版发布就好了。
Issues：#1181 ，PR：#1182
