### ISSUE TITLE
Splitting the project into parts

### ISSUE THREAD

**Issue by Roman-00** [vuejs/vitepress#1186]
### Discussed in https://github.com/vuejs/vitepress/discussions/1185

<div type='discussions-op-text'>

<sup>Originally posted by **Roman-00** August 17, 2022</sup>
Please tell me how to make vitapress work as follows. 
I have created 2 folders in the docs directory and would like the questions to be available. 
Explanations I have a domain where the application is hosted https://www.site.com . 
I would like that at the transition https://www.site.com/kolesa / questions were opened with kolesa/questions, 
and if you clicked on https://www.site.com/krisha / questions were opened with krisha/question.
![kolesa-guide-info](https://user-images.githubusercontent.com/58338625/185068876-3311cbe1-8eb8-4639-bdbd-879ba8f2a8ba.jpg)

</div>

**Comment by brc-dd** [comment]
Isn't this the behavior by default?

**Comment by Roman-00** [comment]
The thing is different, I now have a config file that looks like this:
https://github.com/Roman-00/vitepress-docs/blob/main/docs/vitepress/config.js

There are config files in the folder of kolesa and krisha.json where there is a baseDir, the path from where to get the data.
https://github.com/Roman-00/vitepress-docs/blob/main/docs/kolesa/config.json

The question is as in config.js which lies in the vitepress folder. Substitute the desired config depending on which router you switched to i.e.

If you go over the route htttps:www.site.com/kolesa - the data must be substituted with config.the json that lies in the kolesa folder, if /krisha, then the data from the config that lies in the /krisha folder. After all, as far as I know, access to window with config.js no and no access to useData?

**Comment by Roman-00** [comment]
The thing is different, I now have a config file that looks like this:
https://github.com/Roman-00/vitepress-docs/blob/main/docs/vitepress/config.js

There are config files in the folder of kolesa and krisha.json where there is a baseDir, the path from where to get the data.
https://github.com/Roman-00/vitepress-docs/blob/main/docs/kolesa/config.json

The question is as in config.js which lies in the vitepress folder. Substitute the desired config depending on which router you switched to i.e.

If you go over the route htttps:www.site.com/kolesa - the data must be substituted with config.the json that lies in the kolesa folder, if /krisha, then the data from the config that lies in the /krisha folder. After all, as far as I know, access to window with config.js no and no access to useData?

**Comment by Roman-00** [comment]
> Isn't this the behavior by default?
> 
> Opening `https://www.site.com/krisha/questions/` will serve `docs/krisha/questions/index.md`

Yes, I understand that. It's a little different :)
Here is my config in the vitepress folder: https://github.com/Roman-00/vitepress-docs/blob/main/docs/vitepress/config.js

I have 2 projects of kolesa & krisha. each folder has config files.json with basic paths:
https://github.com/Roman-00/vitepress-docs/tree/main/docs
https://github.com/Roman-00/vitepress-docs/blob/main/docs/kolesa/config.json

The question is how do I substitute the necessary config in config js depending on the project. If we switch to www.mysite.com/kolesa then put the data with config.the json that lies in the docs/kolesa folder, if /krisha, then we substitute the data from the config that lies in docs/krisha config.json ?

As far as I know in config.js does not have access to window, it is also impossible to access useData there.

**Comment by brc-dd** [comment]
Ah, then this is similar to this request: https://github.com/vuejs/vitepress/discussions/1160

**Comment by Roman-00** [comment]
> Ах, тогда это похоже на этот запрос: #1160

Yes, but I have everything ready, I attached the links above to the repository. The only thing I can't figure out is how to throw configs correctly?

**Comment by Roman-00** [comment]
> Ах, тогда это похоже на этот запрос: #1160

I will be very grateful for your help. Since it is not clear now how this can be implemented?

**Comment by brc-dd** [comment]
There isn't a way currently other than creating separate VitePress projects for each folder.

**Comment by Roman-00** [comment]
> В настоящее время нет другого способа, кроме создания отдельных проектов VitePress для каждой папки.

Understood accepted! Thank you very much!

**Comment by Roman-00** [comment]
Maybe there is some way out? To solve this problem!

**Comment by Roman-00** [comment]
> There isn't a way currently other than creating separate VitePress projects for each folder.

Maybe there is some way out? To solve this problem!

**Comment by Roman-00** [comment]
> There isn't a way currently other than creating separate VitePress projects for each folder.

How can I get data on the router? In js files or in the config js file?
