### ISSUE TITLE
[next] js not working in prod

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#1187]

**Comment by qin-guan** [comment]
Not too sure, but could be caused by the introduction of `.js` extension in the imports from the latest release. See https://github.com/vuejs/vitepress/pull/856/files#diff-db1c8c88da8934bfda8cf3f0e5c9b3751400752ae3b8ad8688972f3b2073cee3L2

**Comment by brc-dd** [comment]
fixed by 04c4d0f01b6cb67fe842d9a88f8810f6959eb3ca

**Comment by qin-guan** [comment]
Hey @brc-dd, out of curiosity and for learning, could you explain the addition of the .js extension? 😅 Thank you (:

**Comment by brc-dd** [comment]
@qin-guan refer #917

**Comment by qin-guan** [comment]
I see, thanks! 🙏
