### ISSUE TITLE
show outline even without sidebar

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#1188]
You can checkout my [repo](https://github.com/Lexpeartha/nuxt-xstate) which had that right-side outline before bumping to the new alpha. I'm assuming something changed internally, since I changed nothing in the actual markdown?

_Originally posted by @Lexpeartha in https://github.com/vuejs/vitepress/issues/856#issuecomment-1217707549_

**Comment by brc-dd** [comment]
@Lexpeartha This actually had nothing to do with that Vite 3 PR and stuff. Outline is only visible when sidebar is there.

**Comment by Lexpeartha** [comment]
In the previous version it showed outline even If I had no sidebar

**Comment by Lexpeartha** [comment]
It can be seen in this previous [this](https://nuxt-xstate.netlify.app/getting-started.html) earlier version of the website

**Comment by brc-dd** [comment]
Which version of VP is that? I'm guessing #980 broke that.

**Comment by Lexpeartha** [comment]
> Which version of VP is that? I'm guessing #980 broke that.

might be alpha 5 or 4, but I'm almost certain it is alpha 5
