### ISSUE TITLE
Allow a custom development port

### ISSUE THREAD

**Issue by wraybowling** [vuejs/vitepress#119]
**Describe the bug**
`npx vitepress` seems to only run on port 3000. If there's a way to run it on some other port of my choosing, it is undocumented and I just don't know what I'm looking at sorry.

**To Reproduce**
1. set up a service that runs on port 3000 `python -m http.server 3000`
2. try to run `npx vitepress` at the same time.

**Expected behavior**
Ideally, I would love a graceful error stating that port 3000 is already in use, and maybe even the common practice of it trying 3001, or 3002. Just as well, and likely simplest solution, a way to set the port

**System Info**
- vitepress version: 0.7.3
- vite version: ?? whatever came with vitepress 0.7.3
- Node version: v10.22.0
- OS version: MacOS 10.13.6

**Additional context**
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Server.server.listen (/Users/wraybowling/play/vitepress-trial/node_modules/vite/dist/node/server/index.js:100:16)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by kiaking** [comment]
You can pass `port` option to `vitepress` command (this is Vote option).

```bash
$ vitepress dev --port 8080
```
