### ISSUE TITLE
There is a problem with accessing resources from the URL deployed from the GitHub Pages？

### ISSUE THREAD

**Issue by git136975643** [vuejs/vitepress#1194]
我的项目在这：https://github.com/git136975643/vitepress
部署后的url在这：https://git136975643.github.io/vitepress/,访问有东西，但不正常

**Comment by brc-dd** [comment]
You haven't set `base` there. Uncomment https://github.com/git136975643/vitepress/blob/master/docs/.vitepress/config.js#L17 and change `"/"` to `"/vitepress/"`
