### ISSUE TITLE
Provide option to change title delimiter

### ISSUE THREAD

**Issue by staghouse** [vuejs/vitepress#1195]
### Is your feature request related to a problem? Please describe.

Id like to not use a `|` in the browser title bar of my application, instead, any other string.

### Describe the solution you'd like

in config.js, at some place...

```js
{
  ...
  titleDelimiter: '·',
  ...
}
```

### Additional context

I should think it would be able to take even an HTML entity like `&middot;` and render that.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Perhaps we can change `titleTemplate` thing itself and make it like `editLink.pattern` 👀

**Comment by szsascha** [comment]
I just created a MR for this. Hopefully I didn't miss some conventions. It is my first commit for this project :)

It will not break the existing configurations.

**Comment by brc-dd** [comment]
@staghouse Pass something like `:title . foo` as titleTemplate.
