### ISSUE TITLE
Incompatible upgrade

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#1198]
### Describe the bug

The same configuration cannot be packaged after the upgrade.

v1.0.0-alpha.8, v1.0.0-alpha.7, v1.0.0-alpha.6, everything version has been tried, it is clear that the problem starts with v1.0.0-alpha.6.

see also: https://github.com/Charles7c/charles7c.github.io/runs/7880696807

### Reproduction

Upgrade VitePress version.

### Expected behavior

Build success. 
Give me some instructions on compatibility upgrades, thanks a lot.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 7.79 GB / 13.87 GB
  Binaries:
    Node: 14.18.1 - D:\Develop\nodejs\node.EXE
    Yarn: 1.22.17 - D:\Develop\nodejs\node_global\yarn.CMD
    npm: 6.14.15 - D:\Develop\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.19041.906
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Change that `include` array in vite.config to `[/\.vue$/, /\.vue\?vue/, /\.md$/]` . The rest of the errors are stuff like window/location/localStorage not defined, etc. These have to do with SSR compat. You cannot use them at top level. Either wrap non-compatible components in `ClientOnly` or use them inside `onMounted`.
