### ISSUE TITLE
Validate provided config and give descriptive errors

### ISSUE THREAD

**Issue by benmccann** [vuejs/vitepress#1201]
### Describe the bug

I'm trying to convert the Chart.js docs to Vitepress and am getting the following error in the console:
```
VPSidebarGroup.vue:25 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'some')
```

If I remove the sidebar theme config then the site loads. I expect that I've passed an invalid config or something like that, but it'd be nice if there were some sort of validation alerting me to what I might have done wrong as it's quite difficult to figure it out from the current error message

### Reproduction

Browse the code at https://github.com/benmccann/Chart.js/tree/vitepress/docs

Run with:
```
git clone git@github.com:benmccann/Chart.js.git
cd Chart.js/docs
git checkout vitepress
pnpm install
pnpm dev
```

### Expected behavior

Validates given config and alerts to invalid values

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  Binaries:
    Node: 16.15.0
  Browsers:
    Chrome: 104.0.5112.79
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You seem to be having completely wrong sidebar config. Please refer the docs: https://vitepress.vuejs.org/guide/theme-sidebar#multiple-sidebars

Regarding config validation, IG it would be difficult for us to do that in VitePress itself. If you were using TypeScript, you'd have already got those errors.
