### ISSUE TITLE
Improve navigation on mobile mode

### ISSUE THREAD

**Issue by Shinigami92** [vuejs/vitepress#1202]
### Is your feature request related to a problem? Please describe.

On mobile you don't have the right hand sidebar where `h2` are listed

### Describe the solution you'd like

Add some functionality to navigate faster through `h2` sections

For example click on a little arrow to skip to next section/h2

### Describe alternatives you've considered

Swipe the right hand side bar out of nothing from the right to open it
This has an issue with UX as users wont know it exists

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This was fixed way back IG. All screen sizes have outline now.
