### ISSUE TITLE
`verbatim` DNS result order breaks VSCode Vite extension

### ISSUE THREAD

**Issue by qin-guan** [vuejs/vitepress#1203]
### Describe the bug

When the Vite extension checks if the server is up, it resolves `localhost` to `127.0.0.1`, which will result in `ECONNREFUSED` as the server is no longer running on `127.0.0.1`.

Related commit: [`7787bbe` (#856)](https://github.com/vuejs/vitepress/pull/856/commits/7787bbe59a088f45025457587930308c25c84d27), 

Related code for extension: https://github.com/antfu/vscode-vite/blob/main/src/utils.ts#L31

### Reproduction

I am unable to provide a reproduction as this occurs on VSCode. However, any VitePress project after alpha 5 can reproduce this issue. It may be a Linux only issue

### Expected behavior

I'm not very sure what the right behavior would be. Since a new Vite project runs the server on `127.0.0.1` by default, VitePress could also follow the same behavior.

### System Info

```shell
System:
    OS: Linux 5.18 Pop!_OS 22.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 21.03 GB / 31.22 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.volta/tools/image/node/16.15.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.11.0 - ~/.volta/tools/image/node/16.15.1/bin/npm
  Browsers:
    Firefox: 103.0
  npmPackages:
    vitepress: 1.0.0-alpha.6 => 1.0.0-alpha.6
```

### Additional context

Temporary workaround is to start VitePress with `--host`

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's breaking even after removing that line 👀  Maybe create at issue at https://github.com/antfu/vscode-vite? But I'm not sure if Anthony is still maintaining that project.
