### ISSUE TITLE
Accent color

### ISSUE THREAD

**Issue by lancemao** [vuejs/vitepress#1208]
### Is your feature request related to a problem? Please describe.

accent color copied from vuepress doesn't work.
file under: .vuepress/styles/palette.styl
and value: $accentColor = #215AE5

### Describe the solution you'd like

if it works, it is easier to migrate from vuepress

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Yes,VitePress doesn't use `palette.styl`. See this: https://vitepress.vuejs.org/guide/theme-introduction#customizing-css
