### ISSUE TITLE
Cannot access 'DefaultTheme' before initialization

### ISSUE THREAD

**Issue by wuchaoxin** [vuejs/vitepress#1210]
MRE: [brc-dd/vp-default-theme-bug](https://github.com/brc-dd/vp-default-theme-bug)

---

### Describe the bug

I want to use element-plus.

I refer to the issue [603](https://github.com/vuejs/vitepress/issues/603) and  [brc-dd/vitepress-element-plus-demo](https://github.com/brc-dd/vitepress-element-plus-demo)

It works in 1.0.0-alpha.4, but building in 1.0.0-alpha.8 gives an error

build error:
 ReferenceError: Cannot access 'DefaultTheme' before initialization

### Reproduction

In 1.0.0-alpha.8 version,create a file `.vitepress\theme\index.js`

```js
import DefaultTheme from 'vitepress/theme'
import { install } from 'element-plus'
import 'element-plus/dist/index.css'

export default {
  ...DefaultTheme,
  enhanceApp({ app }) {
    install(app)
  }
}
```

### Expected behavior

No error in building

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) x64 Apple M1
    Memory: 29.13 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.3
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Sepush** [comment]
get the same error when build

**Comment by Tyh2001** [comment]
引入第三方组件库方式建议参考 [vitepress-template](https://github.com/Tyh2001/vitepress-template/blob/master/docs/.vitepress/theme/index.ts)

**Comment by Sepush** [comment]
> 引入第三方组件库方式建议参考 [vitepress-template](https://github.com/Tyh2001/vitepress-template/blob/master/docs/.vitepress/theme/index.ts)

didn't use third party lib still get this error

**Comment by Tyh2001** [comment]
引入第三方组件库方式建议参考 [vitepress-template](https://github.com/Tyh2001/vitepress-template/blob/master/docs/.vitepress/theme/index.ts)

**Comment by Tyh2001** [comment]
> > 引入第三方组件库方式建议参考 [vitepress-template](https://github.com/Tyh2001/vitepress-template/blob/master/docs/.vitepress/theme/index.ts)
> 
> didn't use third party lib still get this error


有项目地址吗？

**Comment by Sepush** [comment]
> > > 引入第三方组件库方式建议参考 [vitepress-template](https://github.com/Tyh2001/vitepress-template/blob/master/docs/.vitepress/theme/index.ts)
> > 
> > 
> > didn't use third party lib still get this error
> 
> 有项目地址吗？

you can try to bump up you template to alpha8 I think you will get this error

**Comment by wuchaoxin** [comment]
> 引入第三方组件库方式建议参考 [vitepress-template](https://github.com/Tyh2001/vitepress-template/blob/master/docs/.vitepress/theme/index.ts)

Your project version is 1.0.0-alpha.4, try using 1.0.0-alpha.8

你的项目版本号和描述不一致，请注意看下描述。

**Comment by Tyh2001** [comment]
> > > > 引入第三方组件库方式建议参考 [vitepress-template](https://github.com/Tyh2001/vitepress-template/blob/master/docs/.vitepress/theme/index.ts)
> > > 
> > > 
> > > didn't use third party lib still get this error
> > 
> > 
> > 有项目地址吗？
> 
> you can try to bump up you template to alpha8 I think you will get this error

不，经过我的测试，在 alpha8 版本中，构建会有错误，可以看下：
https://github.com/vuejs/vitepress/issues/1209

**Comment by Sepush** [comment]
> > > > > 引入第三方组件库方式建议参考 [vitepress-template](https://github.com/Tyh2001/vitepress-template/blob/master/docs/.vitepress/theme/index.ts)
> > > > 
> > > > 
> > > > didn't use third party lib still get this error
> > > 
> > > 
> > > 有项目地址吗？
> > 
> > 
> > you can try to bump up you template to alpha8 I think you will get this error
> 
> 不，经过我的测试，在 alpha8 版本中，构建会有错误，可以看下： #1209

that's why we talk about here

**Comment by Tyh2001** [comment]
应该是版本问题 先使用 alpha4 版本比较稳定一些

**Comment by brc-dd** [comment]
I am not able to reproduce this:

![image](https://user-images.githubusercontent.com/40380293/185751878-7860740e-abb1-459a-bc82-6edfa5e4dbe6.png)

**Comment by Sepush** [comment]
> I am not able to reproduce this:
> 
> ![image](https://user-images.githubusercontent.com/40380293/185751878-7860740e-abb1-459a-bc82-6edfa5e4dbe6.png)

https://github.com/Sepush/envd-docs/tree/up 
try this branch
it work fine on dev mode but when I run pnpm docs:buid it will get this error
![image](https://user-images.githubusercontent.com/39197136/185752626-eb2cc3b3-36e8-46e6-bcc1-6112616dd06f.png)

**Comment by wuchaoxin** [comment]
> I am not able to reproduce this:
> 
> ![image](https://user-images.githubusercontent.com/40380293/185751878-7860740e-abb1-459a-bc82-6edfa5e4dbe6.png)

This problem seems to be caused by `Team Page`. It works fine when I comment out `Team Page`.

**Comment by Sepush** [comment]
> > I am not able to reproduce this:
> > ![image](https://user-images.githubusercontent.com/40380293/185751878-7860740e-abb1-459a-bc82-6edfa5e4dbe6.png)
> 
> This problem seems to be caused by `Team Page`. It works fine when I comment out `Team Page`.

this also works for me seems this issue couse by `VPTeamPage`
