### ISSUE TITLE
nav support target: '_self'

### ISSUE THREAD

**Issue by lancemao** [vuejs/vitepress#1212]
### Is your feature request related to a problem? Please describe.

currently, when nav link is for example, https://github.com, it opens a new tab

### Describe the solution you'd like

in some cases, we want the link to be opened at the same tab, so something like:

nav: [
      { text: 'Configs', link: 'https://github.com', target: '_self'  }
]

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This should work for now: https://github.com/vuejs/vitepress/discussions/1015#discussioncomment-3177860

**Comment by brc-dd** [comment]
fixes in #1993
