### ISSUE TITLE
Support gitlab, reddit, tiktok, twitch social media.

### ISSUE THREAD

**Issue by Rollczi** [vuejs/vitepress#1214]
### Is your feature request related to a problem? Please describe.

I can't add  gitlab, reddit, tiktok, twitch to social media section in navigation.

### Describe the solution you'd like

solution #1213
:trollface: 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can manually add additional icons, we won't be adding any new ones now.

```js
// .vitepress/config.ts

export default {
  themeConfig: {
    socialLinks: [
      {
        icon: {
          svg: '<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>GitLab</title><path d="m23.6004 9.5927-.0337-.0862L20.3.9814a.851.851 0 0 0-.3362-.405.8748.8748 0 0 0-.9997.0539.8748.8748 0 0 0-.29.4399l-2.2055 6.748H7.5375l-2.2057-6.748a.8573.8573 0 0 0-.29-.4412.8748.8748 0 0 0-.9997-.0537.8585.8585 0 0 0-.3362.4049L.4332 9.5015l-.0325.0862a6.0657 6.0657 0 0 0 2.0119 7.0105l.0113.0087.03.0213 4.976 3.7264 2.462 1.8633 1.4995 1.1321a1.0085 1.0085 0 0 0 1.2197 0l1.4995-1.1321 2.4619-1.8633 5.006-3.7489.0125-.01a6.0682 6.0682 0 0 0 2.0094-7.003z"/></svg>',
        },
        link: '...',
      }, // gitlab
    ],
  },
};
```

**Comment by nils-van-zuijlen** [comment]
> You can manually add additional icons, we won't be adding any new ones now.

So, why did #1736 get merged?
