### ISSUE TITLE
Chrome Strict MIME type checking blocks dev server on Windows 10

### ISSUE THREAD

**Issue by koculu** [vuejs/vitepress#1215]
### Describe the bug

I have followed QuickStart guide to create a simple documentation page. I am getting following error in Chrome Console and the site is not loading. I am using npm run docs:dev command.

![image](https://user-images.githubusercontent.com/7453467/185719996-e212839d-a978-4811-a02e-38d25e3c91d2.png)

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/markdown". Strict MIME type checking is enforced for module scripts per HTML spec.

### Reproduction

Follow quick start guide.
start docs:dev server.
Browse to the doc site in Chrome.

### Expected behavior

QuickStart sample should work on Windows 10 with Chrome.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
    Memory: 37.05 GB / 63.90 GB
  Binaries:
    Node: 17.0.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vitepress: ^1.0.0-alpha.8 => 1.0.0-alpha.8
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I can't confirm the bug, and seeing no reactions on this its likely working fine for others too.

**Comment by koculu** [comment]
I have retried with version 1.0.0-alpha.13 and it works now. May be a bug that is already fixed?
