### ISSUE TITLE
Working with a file config

### ISSUE THREAD

**Issue by Roman-00** [vuejs/vitepress#1221]
### Discussed in https://github.com/vuejs/vitepress/discussions/1220

<div type='discussions-op-text'>

<sup>Originally posted by **Roman-00** August 22, 2022</sup>
Please tell me how to throw the data from the vue components into the config file?

For example, I want to take the router data and throw it into the config file for further use?</div>

**Comment by brc-dd** [comment]
Isn't currently possible.
