### ISSUE TITLE
How to fully customize the header nav with vue？

### ISSUE THREAD

**Issue by social-uni** [vuejs/vitepress#1222]
### Is your feature request related to a problem? Please describe.

I want to display the current user name on the nav header，

Are there any related functions or slots provided?

or can i  fully custom nav header by vue？

thank you ！！！

**Comment by kiaking** [comment]
If you want to fully customize, I would recommend copy pasting all VPNav component and tweak as you like 👍

**Comment by social-uni** [comment]
> If you want to fully customize, I would recommend copy pasting all VPNav component and tweak as you like 👍

[https://vitepress.vuejs.org/guide/theme-introduction#layout-slots](https://vitepress.vuejs.org/guide/theme-introduction#layout-slots)

This is the function I want, thanks

**Comment by kiaking** [comment]
So you can insert any custom component you like in:

- nav-bar-title-before
- nav-bar-title-after
- nav-bar-content-before
- nav-bar-content-after
- nav-screen-content-before
- nav-screen-content-after
