### ISSUE TITLE
Enable SidebarItem only menu in sidebar

### ISSUE THREAD

**Issue by benmccann** [vuejs/vitepress#1225]
### Is your feature request related to a problem? Please describe.

Chart.js has a mix of expandable groups and individual items within its sidebar. I can't migrate the docs from Vuepress to Vitepress because Vitepress will not allow individual items within the sidebar

### Describe the solution you'd like

The types are currently:
```
  export type Sidebar = SidebarGroup[] | SidebarMulti

  export interface SidebarMulti {
    [path: string]: SidebarGroup[]
  }
```

It would be nice to change them to:
```
  export type Sidebar = Array<SidebarGroup|SidebarItem> | SidebarMulti

  export interface SidebarMulti {
    [path: string]: Array<SidebarGroup|SidebarItem>
  }
```

### Describe alternatives you've considered

Make a group with just an individual item in it. It's kind of an annoying user experience though

### Additional context

The work-in-progress branch is here: https://github.com/benmccann/Chart.js/tree/vitepress

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
This config is tied to Default Theme. If Default Theme does not support this type of structure, it shouldn't have it. If you need custom type, that means you should create your own config types 👍 

If VitePress default theme gets support for this type of sidebar structure, then it will be modified as you mentioned. And actually this feature is planned.

**Comment by benmccann** [comment]
Given that the feature is planned, maybe it'd make sense to leave this open to track it? It'd be easier for folks who are interested to subscribe to this thread and be notified when it's closed than having to come back on a frequent basis to check the release notes to see whether it's been implemented

**Comment by kiaking** [comment]
Make sense. I'll adjust the title then 👍

**Comment by brc-dd** [comment]
Support for this was added some time last year IG.
