### ISSUE TITLE
Ability to hide Nav per-page

### ISSUE THREAD

**Issue by shadow-light** [vuejs/vitepress#1227]
### Is your feature request related to a problem? Please describe.

The nav bar currently cannot be disabled, and there are some use cases for wanting to disable it. For example, if you want to fully customise the homepage this isn't possible as the nav bar will still exist. Or if you want to create a different fully-customised page at some other route, that also isn't possible as the nav bar will be shown.

### Describe the solution you'd like

I'd like to be able to hide the nav bar globally as well as per-page via frontmatter.

### Describe alternatives you've considered

Hiding the nav bar via CSS can currently only be done globally, and it is also complicated as other parts of the page assume it exists (VPContent has top-padding on wide screens).

### Additional context

See https://github.com/vuejs/vitepress/issues/522

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
I guess adding this.

```yaml
---
nav: false
---
```
