### ISSUE TITLE
layout-slots don't support top-level-await

### ISSUE THREAD

**Issue by social-uni** [vuejs/vitepress#1229]
### Describe the bug

https://vitepress.vuejs.org/guide/theme-introduction#layout-slots

I wrote a custom component with reference to myLayout, I used top-level-await in the component, and then the view could not be displayed

I'm not sure if this issue is related to the following issues

[https://github.com/vuejs/vitepress/issues/599](https://github.com/vuejs/vitepress/issues/599)

**Comment by brc-dd** [comment]
Using top-level await will make Layout an async component, then we'll need Suspense to properly render it. It would be better to just create an async component for your slot and use suspense only inside named template instead of using it for whole layout.

**Comment by didoee** [comment]
能否将doc左侧的sidebar也做成插槽，并且将sidebar的数据暴漏出来，供外部使用
