### ISSUE TITLE
CommonJS modules can always be imported via the default export, for example using:

### ISSUE THREAD

**Issue by productdevbook** [vuejs/vitepress#1232]
### Describe the bug

import { createI18n, useI18n } from "vue-i18n/dist/vue-i18n.runtime.esm-bundler.js";
         ^^^^^^^^^^
SyntaxError: Named export 'createI18n' not found. The requested module 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js';
const { createI18n, useI18n } = pkg;

### Reproduction
branch: feat/date

https://github.com/huntersofbook/huntersofbook/tree/feat/date

### Expected behavior

1. pnpm install
2. cd apps/docs
3. pnpm build

and see error

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 17.10 GB / 31.12 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.15.0 - /usr/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
  npmPackages:
    vitepress: 1.0.0-alpha.10 => 1.0.0-alpha.10
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by linxiang07** [comment]
I've come across this too

**Comment by productdevbook** [comment]
@linxiang07 -> https://github.com/intlify/vue-i18n-next/issues/1131 follow

**Comment by productdevbook** [comment]
@kazupon thank you. install new version and fixed.

     "vue-i18n": "9.3.0-beta.3",
    "@intlify/vite-plugin-vue-i18n": "7.0.0-beta.2",
