### ISSUE TITLE
No language registration for flow

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#1233]
### Describe the bug

``` flow
st=>start: 开始
process1=>operation: 语句1
process2=>operation: 语句2
process3=>operation: 语句3
e=>end: 结束

st->process1->process2->process3->e
```

### Reproduction

N/A

### Expected behavior

![image](https://user-images.githubusercontent.com/25446948/186438084-396167bd-db25-422d-ac7b-0c412a16db20.png)

### System Info

```shell
N/A
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I'm not sure what exactly is that syntax, but VitePress doesn't support drawing flowcharts/diagrams out of the box yet. You probably need some markdown-it plugin or component to process such syntax.

**Comment by Charles7c** [comment]
I am using Typora as this Markdown editor.

**Comment by gltjk** [comment]
> I am using Typora as this Markdown editor.
> 
> see also: https://support.typoraio.cn/Draw-Diagrams-With-Markdown/

This is the syntax of [flowchart.js](https://flowchart.js.org). So far there is no vitepress plugin available for that. Maybe you can check out heck out this plugin [vitepress-plugin-mermaid](https://www.npmjs.com/package/vitepress-plugin-mermaid); it is based on [mermaid.js](https://mermaid-js.github.io/mermaid/), which shares similar syntax to flowchart.js.

**Comment by Charles7c** [comment]
> This is the syntax of [flowchart.js](https://flowchart.js.org). So far there is no vitepress plugin available for that. Maybe you can check out heck out this plugin [vitepress-plugin-mermaid](https://www.npmjs.com/package/vitepress-plugin-mermaid); it is based on [mermaid.js](https://mermaid-js.github.io/mermaid/), which shares similar syntax to flowchart.js.

Thank you. I'll have a try.
