### ISSUE TITLE
how to use vitepress code style(markdown theme) on vite-plugin-md?

### ISSUE THREAD

**Issue by social-uni** [vuejs/vitepress#1237]
### Is your feature request related to a problem? Please describe.

Hello
I want to use vitepress code style in vite-plugin-md, or markdown theme

Is the code style of vitepress open source?

Do you know what to do if I want to use vitepress' markdown theme in vite-plugin-md?

vite-plugin-md is implemented based on markdown-it, does vitepress use it?

Can you tell me if you know how to do it, please give me some pointers, thank you very much

[https://github.com/antfu/vite-plugin-md/issues/115](https://github.com/antfu/vite-plugin-md/issues/115)

I also submitted related issues in the issues of vite-plugin-md

**Comment by brc-dd** [comment]
> I want to use vitepress code style in vite-plugin-md, or markdown theme

Can you explain what you mean by "vitepress code style or markdown theme"?

> Is the code style of vitepress open source?

Everything of VitePress is open source.

> vite-plugin-md is implemented based on markdown-it, does vitepress use it?

VitePress uses markdown-it, but vite-plugin-md is a separate project.

**Comment by social-uni** [comment]
> > I want to use vitepress code style in vite-plugin-md, or markdown theme
> 
> Can you explain what you mean by "vitepress code style or markdown theme"?
> 
> > Is the code style of vitepress open source?
> 
> Everything of VitePress is open source.
> 
> > vite-plugin-md is implemented based on markdown-it, does vitepress use it?
> 
> VitePress uses markdown-it, but vite-plugin-md is a separate project.

![image](https://user-images.githubusercontent.com/14007972/186664361-14f56047-eca4-4754-8c61-93b65e4784fa.png)

thank you for your reply,
I want my .md file to also have this css style

**Comment by social-uni** [comment]
> > I want to use vitepress code style in vite-plugin-md, or markdown theme
> 
> Can you explain what you mean by "vitepress code style or markdown theme"?
> 
> > Is the code style of vitepress open source?
> 
> Everything of VitePress is open source.
> 
> > vite-plugin-md is implemented based on markdown-it, does vitepress use it?
> 
> VitePress uses markdown-it, but vite-plugin-md is a separate project.

Does vitepress have something like https://github.com/sindresorhus/github-markdown-css

**Comment by brc-dd** [comment]
> Does vitepress have something like https://github.com/sindresorhus/github-markdown-css

No. Our theme is quite complex and cannot be completely mimicked using some CSS file. Here is the default theme: https://github.com/vuejs/vitepress/tree/main/src/client/theme-default . You can try extracting styles manually, but it will likely not work as you expect because the styles need proper layout (the one we create using different components here). Also, our markdown-it plugins are quite customized so most of the stuff just won't work.
