### ISSUE TITLE
`_assets` folder not accessible when deploying to GitHub Page

### ISSUE THREAD

**Issue by xiaoxian521** [vuejs/vitepress#124]
**Describe the bug**
Package and deploy to GitHub, no resource package 404 error found

**To Reproduce**
Steps to reproduce the behavior: Package and deploy to GitHub, no resource package 404 error found

**Expected behavior**
Package and deploy to GitHub, no resource package 404 error found

**System Info**
- vitepress version: 0.7.4
- vite version: 1.20.0
- Node version: 12.13.1
- OS version: windows10

**Additional context**

**Comment by xiaoxian521** [comment]
After packaging, open http-server locally to allow the project to be fully OK, but the deployment of GitHub will report 404, and no resources can be found

as https://xiaoxian521.github.io/zh/standard/

**Comment by xiaoxian521** [comment]
@yyx990803 You da, this problem has troubled me for a long time. Can you solve it and support you forever

**Comment by kiaking** [comment]
@xiaoxian521 I think you need to add `base` option...?

```js
// .vitepress/config.js

module.exports = {
  base: '/standard/',
  ...
}
```

**Comment by yuxino** [comment]
@kiaking @xiaoxian521 i think i can answer this question . 

![image](https://user-images.githubusercontent.com/12481935/99228035-0b19ae00-2827-11eb-8b52-4cd546160bcb.png)

This seems to be a dns issues . If you are in China, you can try to use a global proxy.

**Comment by xiaoxian521** [comment]
The access path is as follows: https://xiaoxian521.github.io/

I am here config.js base: "/" is added to the, but it still doesn't work

**Comment by xiaoxian521** [comment]
@yuxino But there is no problem with vuepress，It should be the same

**Comment by yuxino** [comment]
@xiaoxian521 i can't access any `github.io` site today , i think it's same question not vitepress.u can't access that http://elemefe.github.io/mint-ui, right ?

**Comment by xiaoxian521** [comment]
@yuxino I can open it http://elemefe.github.io/mint-ui

**Comment by kiaking** [comment]
Oh wait, yea yea yea I recall this issue. We can't use underscore as a folder name in GitHub pages. So `_assets` folders doesn't work. We need to add `.nojekyll` file to the root.

@xiaoxian521 As a workaround, could you test placing `public/.nojekyll` file, and then deploy the build?

**Comment by xiaoxian521** [comment]
Perfect solution. Thank you very much

**Comment by kiaking** [comment]
Nice! OK let's make this issue an enhancement issue. Maybe we could automatically include `.nojekyll` file at the built time, or maybe we should rename `_assets` folder to `asstes` like VuePress does.

**Comment by xiaoxian521** [comment]
I support it very much

**Comment by xiaoxian521** [comment]
Of course, another way is to configure deploy.sh file as
```
#!/usr/bin/env sh

# 确保脚本抛出遇到的错误
set -e

# 生成静态文件
npm run docs:build

# 进入生成的文件夹
cd docs/.vitepress/dist

touch .nojekyll

# 如果是发布到自定义域名
# echo 'www.example.com' > CNAME

git init
git add -A
git commit -m 'deploy'

# 如果发布到 https://<USERNAME>.github.io
git push -f git@github.com:xiaoxian521/xiaoxian521.github.io.git master:main

# 如果发布到 https://<USERNAME>.github.io/<REPO>
# git push -f git@github.com:<USERNAME>/<REPO>.git master:gh-pages

cd -
```

**Comment by kiaking** [comment]
Yeah that works too 👍

**Comment by matias-capeletto** [comment]
@kiaking in Vite 2, `_assets` was renamed to `assets`. This issue could be closed.

**Comment by kiaking** [comment]
！ Actually I didn't know that. Maybe we should update docs about `.nojekyll` warning?
https://vitepress.vuejs.org/guide/deploy.html#github-pages

**Comment by matias-capeletto** [comment]
Yes, I forgot about that alert! I can send a PR removing it if you want 👍🏼 

It is actually configurable now: https://vitejs.dev/config/#build-assetsdir
But the default is `assets`, which is great 🙂

**Comment by kiaking** [comment]
Great! PR would be awesome 🙌  Not sure if adding `.nojekyll` is still preferable as a best practice, but even in that case I think we should just include `.nojekyll` at build time (if anyone one has problem related to it, then we would probably get anotehr issue opened so 😃 ).

**Comment by zain12321** [comment]
###
