### ISSUE TITLE
Allow use theme colors in code blocks

### ISSUE THREAD

**Issue by userquin** [vuejs/vitepress#1245]
### Is your feature request related to a problem? Please describe.

Currently VitePress has only code blocks to be dark, and so it is "hard/too repetitive" for ppl to use light colors in ligth theme.

### Describe the solution you'd like

Include code blocks variables and variants to allow use theme in the code blocks.

### Describe alternatives you've considered

Add styles manually to each repo, for example:
- https://github.com/vitest-dev/vitest/pull/1666
- https://github.com/antfu/vite-plugin-pwa/pull/341

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by didoee** [comment]
必须是英文的吗？

**Comment by userquin** [comment]
closing, fixed with #2319
