### ISSUE TITLE
Adding Custom Containers from the config.js file 

### ISSUE THREAD

**Issue by aadi58002** [vuejs/vitepress#1246]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

The custom container are a very useful feature and it can be configurable in the .vitepress/config.js file with color for 
name,border, border-dark, background, background-dark in the config file with these 5 options i think it will make a better for a better blog points.

### Describe alternatives you've considered

Having the lack of customization for the custom container boxes. I am aware that you can create components to do the same things but the "::: name :::" syntax is better to view in markdown as well as more read able than having it wrapped inside a html tag.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can manually create them using https://github.com/markdown-it/markdown-it-container
