### ISSUE TITLE
Markdown include not showing sometimes

### ISSUE THREAD

**Issue by HipyCas** [vuejs/vitepress#1247]
### Describe the bug

This is a pretty funny one. I was using a Markdown Include as described in [your docs](https://vitepress.vuejs.org/guide/markdown). I already had used one earlier in the file and worked perfectly, but strange enough, this didn't show up. This was the part that was failing:

```md
<!--@include: ../shared/servicios/recordatorios-nginx.md -->

## Integración con Authentik
```

**The fact that it is followed by a header is pretty important**

![wrong](https://user-images.githubusercontent.com/54776315/187096657-c32b6543-8cae-45f2-8aa0-bdb4fffe5022.png)

And that's what showed up, just not the Markdown that should be included. To check if the path or something was wrong, I copied the earlier one that was working just below this one, like this:

```md
<!--@include: ../shared/servicios/recordatorios-nginx.md -->
<!--@include: ../shared/servicios/puertos.md -->

## Integración con Authentik
```

![ok_include](https://user-images.githubusercontent.com/54776315/187096715-7a1ba6b2-b50d-4b9d-bb34-1c8a8705a44e.png)

And funny enough, it worked. **Note that again, I have the header below too**. So I went to remove the test purpose second include and, surprise! The Markdown that should be included disappeared again (as in the first picture). By pure chance, I uncommented the line and saw it worked, so I tried to just write some random text below the _include, to be precise this random text:

```md
<!--@include: ../shared/servicios/recordatorios-nginx.md -->

nice

## Integración con Authentik
```

![ok_below](https://user-images.githubusercontent.com/54776315/187096814-bf11c1c9-7e97-47ae-bb3a-a4c519e86caa.png)

And it showed up again! Things are getting pretty odd at this point, so I went a bit further and tested to put the test text below the header, like this:

```md
<!--@include: ../shared/servicios/recordatorios-nginx.md -->

## Integración con Authentik

nice
```

![ok_title](https://user-images.githubusercontent.com/54776315/187096856-74acc3fa-f528-4ae2-acf7-7a1b33914090.png)

It worked! At this point I'm pretty freaked out so I try one last thing, putting the included Markdown at the end of the file, and it works again!

![ok_end](https://user-images.githubusercontent.com/54776315/187096982-54d49050-4c5d-4425-be3f-bdd84031e5ac.png)

So, I ended up concluding that **Markdown include does not work directly above a heading** for some reason I cannot include.

But hey, it doesn't end here. The Markdown file that was being included was like the following:

```md
::: tip A nice title

Just some pretty nice text

:::
```

But, if I add a text line or a header below, it doesn't show up. For example, this wouldn't show up:

```md
::: tip A nice title

Just some pretty nice text

:::

nice paragraph

## Nice heading
```

And well, placing the text above the tip block doesn't fix it either, or even removing the tip block and putting just text.

> There's a chance it really is just me not knowing how to use the Markdown Include, if so I'm really sorry for the noise.

### Reproduction

I included examples above, but anywhay:

1. Create a Markdown file with a custom container
2. Include it in other and write a header below
3. See how it doesn't work and put text below or remove the header
4. See how now it works and add text in the included Markdown file above or below the container
5. See how the text doesn't show up

### Expected behavior

Well, just show up correcetly I guess

### System Info

```shell
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 7.22 GB / 15.48 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Brave Browser: 104.1.42.97
    Chromium: 104.0.5112.101
    Firefox: 103.0
  npmPackages:
    vitepress: ^1.0.0-alpha.12 => 1.0.0-alpha.12
```

### Additional context

BTW I tested on Brave

### Validations

- [x] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by HipyCas** [comment]
I've been doing some more testing, and I believe it must be a problem with the dev server. The server seems not to be picking up the changes of the included Markdown files, not even on page reload. If I restart the server, all the problems I mention above dissapear.

**Comment by brc-dd** [comment]
HMR doesn't work RN with included markdown. https://github.com/vuejs/vitepress/issues/117#issuecomment-1179290397

**Comment by HipyCas** [comment]
Thanks for the quick response!
