### ISSUE TITLE
Support public dir

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vitepress#125]
**Is your feature request related to a problem? Please describe.**

`.vitepress/public/`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I saw evan you add the build support in https://github.com/vuejs/vitepress/commit/ddc9d519c60423e2432c1f3c0ab5b2ccbabd34a6 while he then removes it in https://github.com/vuejs/vitepress/commit/c9fcea8a938b9f88f701730c0b5863652dfd6f4b

**Comment by ChrisShank** [comment]
I believe a `public` directory is already supported, but it must be located in the root directory of the `vitepress` project rather than in the `.vitepress` directory. The reason that code was removed is because `vite@^0.10.1` added support for it.

**Comment by kiaking** [comment]
Yes, as @ChrisShank mentioned, it's supported but you must place the directory at root, not under `.vitepress` 👍
