### ISSUE TITLE
#region doesn't seem to be respected..

### ISSUE THREAD

**Issue by kristiandupont** [vuejs/vitepress#1251]
### Describe the bug

I am trying to embed a `// #region` snippet, but no matter what I do, it insists on embedding the entire file.

With this snippet:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/847742/187148926-d1d02428-3f8e-4b27-a0be-db45cb0de4a4.png">

I get this result:
![Screen Shot 2022-08-29 at 09 41 43](https://user-images.githubusercontent.com/847742/187149866-f9187f25-dcef-408c-8093-7ee3309d3f7b.png)

The only related issue I can find is #600 which is marked as resolved but that was seemingly about highlighting lines. What am I missing?

### Reproduction

Create an `md` file with a region-specific imported snippet from a typescript file.

### Expected behavior

Only the region should appear in the output, not the entire file.

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (4) arm64 unknown
    Memory: 1.15 GB / 7.75 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.10.0 - /usr/bin/node
    Yarn: 1.22.15 - /usr/bin/yarn
    npm: 7.18.1 - ~/.npm-global/bin/npm
  npmPackages:
    vitepress: ^1.0.0-alpha.12 => 1.0.0-alpha.12
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`#endregion Config`

**Comment by kristiandupont** [comment]
:face-palm:

Thank you. :-)
