### ISSUE TITLE
[i18n]: always naviageto init page when language change not the corresponding URL

### ISSUE THREAD

**Issue by Sepush** [vuejs/vitepress#1253]
### Describe the bug

with a config file like this https://github.com/tensorchord/envd-docs/blob/main/docs/.vitepress/config.ts
when we change the language of doc it did not naviagative to corresponding URL

### Reproduction

eg.
when we in this page https://envd.tensorchord.ai/zh/guide/build-envd.html
we click the button to change the language
![image](https://user-images.githubusercontent.com/39197136/187357999-46221a6d-96bd-4fe2-8793-e3099758d5a4.png)
we expect it naviagte to https://envd.tensorchord.ai/guide/build-envd.html
not https://envd.tensorchord.ai/guide/getting-started.html

### Expected behavior

naviagte to corresponding URL

### System Info

```shell
win 10 chrome 103
```

### Additional context

I'm not sure whether it been fixed on i18n branch or is there any way I have miss to achive this for now.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Zhengqbbb** [comment]
I think it hasn't started yet, related https://github.com/vuejs/vitepress/issues/631

You can find not only URL router, like navbar text, search text ... We are all looking forward to the feature, maybe we need to complete other features before designing it. The current I18 I use the double site to complete.

**Comment by brc-dd** [comment]
> We are all looking forward to the feature

Yeah, its definitely on my priority list. i18n hopefully will be ready for review before next week.

---

But still I don't think we'll be able to cover this use-case initially. There are complexities with this, like many people like to change file name too, not just the `zh`/`en` part, or maybe a page might not have a corresponding page in the other language. What to do in such cases?

**Comment by Sepush** [comment]
> > We are all looking forward to the feature
> 
> Yeah, its definitely on my priority list. i18n hopefully will be ready for review before next week.
> 
> But still I don't think we'll be able to cover this use-case initially. There are complexities with this, like many people like to change file name too, not just the `zh`/`en` part, or maybe a page might not have a corresponding page in the other language. What to do in such cases?

It's not easy.How about resolve base on the sidebar config? As usually if we have different language docs we also have the different sidebar config. So that we cant get the info of correct path from it.
