### ISSUE TITLE
Expose __path and __relativePath options on md instance for md plugins

### ISSUE THREAD

**Issue by flingyp** [vuejs/vitepress#1258]
### Is your feature request related to a problem? Please describe.

I found that #1240 has removed these two parameters, which makes it impossible for me to customize the MD plugin on this basis

### Describe the solution you'd like

Can you `__ Path ` and `__ Relativepath ` these two attributes are added to the MD instance to better customize the MD plugin

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
These were not removed, they were moved to `env`.

**Comment by meteorlxy** [comment]
FYI:

> An `env` sandbox can be used alongside tokens to inject external variables for your parsers and renderers.

https://github.com/vuejs/vitepress/blob/1e312f5792540f17d00b1088135db9a661b7d65b/src/node/markdown/env.ts#L4-L9

**Comment by meteorlxy** [comment]
Just noticed that `MarkdownEnv` type did not get exposed. See #1259

**Comment by flingyp** [comment]
@meteorlxy  I see `__ data. Hoistedtags` has also been deleted. If I need to add a script setup script code to the MD file to introduce my components. I should report to `env.sfcBlocks.customBlocks` insert script？

**Comment by meteorlxy** [comment]
`env.sfcBlocks.scriptSetup` would help

**Comment by flingyp** [comment]
@meteorlxy 

I finally used ` env.sfcblocks.scripts` because vitepress does not seem to handle 'env.sfcblocks.scriptsetup` code logic. But thank you for guiding me to solve the problem.

```ts
const vueSrc = [
    ...injectPageDataCode(
      sfcBlocks?.scripts.map((item) => item.content) ?? [],
      pageData,
      replaceRegex
    ),
    `<template><div>${replaceConstants(
      html,
      replaceRegex,
      vueTemplateBreaker
    )}</div></template>`,
    ...(sfcBlocks?.styles.map((item) => item.content) ?? []),
    ...(sfcBlocks?.customBlocks.map((item) => item.content) ?? [])
  ].join('\n')
```
