### ISSUE TITLE
Unexpected render after the build.

### ISSUE THREAD

**Issue by yunying1** [vuejs/vitepress#1261]
### Describe the bug

I use the global variable window in component, It will cause the content below it to be rendered repeatedly.
**Also, it only happens after the build.**

### Reproduction

```
// Component.vue

<script setup>
    const url = `${window.location.protocol}//www.xxx.com`;
</script>

<template>
    <h1>{{ url }}</h1>
</template>
```

```
// index.md

<Component />

// Here! `- test content ...` repeat render! it shows two.
- test content ...
```

### Expected behavior

Successfully rendered only once.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Apple M1
    Memory: 43.79 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.6
  npmPackages:
    vitepress: ^1.0.0-alpha.13 => 1.0.0-alpha.13
```

### Additional context

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/50652358/187465157-4ea24772-f3ef-4ec3-8717-298579837525.png">

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yunying1** [comment]
I provide a minimal reproduction.
[https://github.com/yunying1/vitepress-build-bug-fix](https://github.com/yunying1/vitepress-build-bug-fix)

**Comment by brc-dd** [comment]
Do it like this: `window` is a browser-only API and cannot be used while SSR (that was causing hydration issues)

```ts
import { ref, onMounted } from 'vue'
const url = ref('')
onMounted(() => {
  url.value = `${window.location.protocol}//www.yuanx.me`
})
```
