### ISSUE TITLE
Frontmatter config not behaving as expected

### ISSUE THREAD

**Issue by ruanspies** [vuejs/vitepress#1265]
### Describe the bug

There seems to be an error with using multiline configs in the Frontmatter. The error is best seen in attempting to recreate the Hero and Features sections from the Frontmatter Configs docs.

## Hero
When attempting to recreate the [hero section from the docs](https://vitepress.vuejs.org/config/frontmatter-configs#hero), I get the following error: 

```
[vite] Internal server error: duplicated mapping key at line 10, column 4:
                        text: Get Started
       ^
```

👉 Removing the actions such that the Frontmatter only contains the code below, does not result in an error of any kind but does not render anything on the page.

```md
---
layout: home

hero:
  name: VuePress
  text: Vite & Vue powered static site generator.
  tagline: Lorem ipsum...
---
```

## Features
Similarly, in attempting to recreate the [features section](https://vitepress.vuejs.org/config/frontmatter-configs#features) I get the error:

```
[vite] Internal server error: end of the stream or a document separator is expected at line 8, column 2:
        - icon: 🖖
     ^
```
👉 Removing all but one feature, as shown in the code below, does not give errors but results in only icon being displayed.

```md
---
layout: home

features:
  - icon: ⚡️
    title: Vite, The DX that can't be beat
    details: Lorem ipsum...
---
```

<img width="555" alt="image" src="https://user-images.githubusercontent.com/69503530/187670575-04cf7cfe-68da-44f4-9094-183b79bced58.png">

👉 Removing the icon field results in the following:

```md
---
layout: home

features:
  - title: Vite, The DX that can't be beat
    details: Lorem ipsum...
---
```
<img width="490" alt="image" src="https://user-images.githubusercontent.com/69503530/187670887-7ea23b49-93fb-470b-aafb-7f7311fa63f1.png">

### Reproduction

File containing the exact code as per the hero section of the docs:

```md
---
layout: home

hero:
  name: VuePress
  text: Vite & Vue powered static site generator.
  tagline: Lorem ipsum...
  actions:
    - theme: brand
      text: Get Started
      link: /guide/what-is-vitepress
    - theme: alt
      text: View on GitHub
      link: https://github.com/vuejs/vitepress
---
```

### Expected behavior

Reproduce the hero section as per the docs

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 98.45 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.2
  npmPackages:
    vitepress: ^1.0.0-alpha.13 => 1.0.0-alpha.13
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not reproducible (https://stackblitz.com/edit/vite-b2syw2):

![image](https://user-images.githubusercontent.com/40380293/187671720-bcc8f97e-807b-43f5-a9e3-4766483d7004.png)

**Comment by ruanspies** [comment]
Any idea what might be causing this issue then?

My `package.json` contains the following:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/69503530/187673190-222f3519-8f89-40fa-a9ae-9d3266536f50.png">

The `.vitepress` directory is under `docs`, which contains the relevant `.md` files:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/69503530/187673938-61ee57a2-2da9-48ab-884b-979d6931ac44.png">


## .../boilerplate/docs/.vitepress/config.ts
<img width="463" alt="image" src="https://user-images.githubusercontent.com/69503530/187674080-7f57a0f5-1f9e-4d40-ae18-050cc12d6a82.png">


## .../boilerplate/docs/.vitepress/theme/index.ts
<img width="376" alt="image" src="https://user-images.githubusercontent.com/69503530/187674166-46d6d286-a9d1-4c3a-8af6-5205b70a9539.png">

**Comment by brc-dd** [comment]
Can you share a "screenshot" of the file where you have that home code?

**Comment by ruanspies** [comment]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/69503530/187676454-1c10f218-53e3-4298-8dc4-fef6c2076c7b.png">

**Comment by ruanspies** [comment]
Thanks for the assistance, it did turn out to be an indentation issue that was caused by auto-formatting settings in the IDE.
