### ISSUE TITLE
[i18n]make Nav have NavMulti config

### ISSUE THREAD

**Issue by Sepush** [vuejs/vitepress#1267]
### Is your feature request related to a problem? Please describe.

when I do the i18n support I want show different navbar 
eg:

```
 const zhNav = [
    { text: '起步', link: '/zh/guide/'},
    { text: '博客', link: '/zh/blog/' },
  ]
  const enNav = [
    { text: 'Get Started', link: '/guide/getting-started'},
    { text: 'Blog', link: '/blog/welcome',activeMatch: '/blog/' },
  ]
```

### Describe the solution you'd like

there is two way to do this
- make Nav have the same type of sidebar
```ts
interface SidebarMulti {
  [path: string]: SidebarGroup[]
}
```
so that we can config nav for different langage like sidebar
with the following way
```
nav:{
'/zh/':[]
'/': []
}
```
or
- make useData could work in .ts file not only use in page so that we cant dynamic determinant the nav 
```
import { useData } from 'vitepress'
import type { DefaultTheme } from 'vitepress'

export const getNav = (): DefaultTheme.Config['nav'] => {
  const { lang } = useData()
  const zhNav = [
    { text: '起步', link: '/zh/guide/'},
    { text: '博客', link: '/zh/blog/'},
  ]
  const enNav = [
    { text: 'Get Started', link: '/guide/'},
    { text: 'Blog', link: '/blog/: '/blog/' },
  ]
  return lang === 'zh-CN' ? zhNav: enNav
}

```
current this way not work becouse it not in an page
get the following error
```
failed to start server. error:
 TypeError: (0 , import_vitepress2.useData) is not a function
```

### Additional context

any workaround for now?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! Everything will be supported 😅, just track #631 for now and comment there if you have some suggestions. You'll be able to override all of these:

```
      lang?: string
      title?: string
      titleTemplate?: string | boolean
      description?: string
      head?: HeadConfig[]
      themeConfig?: ThemeConfig
```

**Comment by Sepush** [comment]
> Hi! Everything will be supported 😅, just track #631 for now and comment there if you have some suggestions. You'll be able to override all of these for each locale you specify:
> 
> ```
>       lang?: string
>       title?: string
>       titleTemplate?: string | boolean
>       description?: string
>       head?: HeadConfig[]
>       themeConfig?: ThemeConfig
> ```

great
