### ISSUE TITLE
Brand images for dark and light mode

### ISSUE THREAD

**Issue by uwinkler** [vuejs/vitepress#1282]
### Is your feature request related to a problem? Please describe.

It would be nice if one could provide two `logo` files in the `themeConfig`, one for the dark, and one for the light mode.

### Describe the solution you'd like

Something like this:

```js
export default {
  themeConfig: {
    logo: '/imgs/logo.svg',
    logoDark: '/imgs/logo-dark.svg',
    ...
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Its already supported:

```ts
themeConfig: {
  logo: {
    light: '...',
    dark: '...'
  }
}
```
