### ISSUE TITLE
client js not working

### ISSUE THREAD

**Issue by productdevbook** [vuejs/vitepress#1284]
### Describe the bug

![image](https://user-images.githubusercontent.com/38668796/188362588-66539979-61aa-46e4-be40-23bb8406ebf1.png)

http://localhost:4173/docs/ui/hdatetime/

pnpm dev working but build after serve dont working all buttons 

### Reproduction

https://github.com/huntersofbook/huntersofbook/tree/feat/i18n

branch: feat/i18n

1. pnpm install
2. pnpm build
3. cd/apps/docs
4. pnpm build
5. pnpm serve

### Expected behavior

click buttons

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 19.96 GB / 31.12 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.15.0 - /usr/bin/npm
  Browsers:
    Chrome: 105.0.5195.102


open-source on  feat/i18n via  v16.17.0 took 2s
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ananyadhananjaya** [comment]
Could you please give more information? I just checked and the buttons look fine to me. What exactly you mean by "not working"?
![image](https://user-images.githubusercontent.com/43600997/188502480-c0d501c4-00ea-41b0-8435-89278428357e.png)

**Comment by productdevbook** [comment]
It wasn't working for me very much, now it is working. Thanks for the feedback.

**Comment by productdevbook** [comment]
https://opensource.huntersofbook.com/docs/ui/hdatetime/

interested now not working buttons :D

**Comment by brc-dd** [comment]
Most likely the issue is with the custom i18n stuff you are doing not VitePress itself.

**Comment by productdevbook** [comment]
> Most likely the issue is with the custom i18n stuff you are doing not VitePress itself.

How do I find a bug, it's working on the dev. but dont working serve :(
