### ISSUE TITLE
Chinese Version Document

### ISSUE THREAD

**Issue by buduan** [vuejs/vitepress#1285]
### Is your feature request related to a problem? Please describe.

希望官方能出一套中文的文档，感谢

### Describe the solution you'd like

希望官方能出一套中文的文档，感谢

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by awxiaoxian2020** [comment]
is PR welcome? @brc-dd

**Comment by brc-dd** [comment]
@awxiaoxian2020 I don't think we will be able to have both English and Chinese docs in this repo itself considering that i18n is not yet implemented. In future (after #1339 is merged) it might be possible to have both `/en/` and `/zh/` docs side by side here.

**Comment by awxiaoxian2020** [comment]
> @awxiaoxian2020 I don't think we will be able to have both English and Chinese docs in this repo itself considering that i18n is not yet implemented. In future (after #1339 is merged) it might be possible to have both `/en/` and `/zh/` docs side by side here.

@brc-dd I think I can draft a pull request for `/zh` docs and be ready for review after #1339 done.

**Comment by awxiaoxian2020** [comment]
@buduan @dong-lufei you can review Chinese doc [here](https://deploy-preview-1593--vitepress-docs.netlify.app/zh/).

**Comment by CHOYSEN** [comment]
Great idea, but I'm a little worried that after adding more translation languages in the future, the bundle time and size of the document itself will increase, and the issue/PR will be filled with trivial translation tasks. Can we consider dividing different languages into different repo for maintenance like vite :)

**Comment by awxiaoxian2020** [comment]
@CHOYSEN Please see https://github.com/vuejs-translations/docs-zh-cn/discussions/561
And @brc-dd I think we can close this issue now :)

**Comment by brc-dd** [comment]
Yeah so in future, if there are many requests for different languages we can probably move them to separate repos in translations org, and give the contributors write access there. But for now, it seems fine to have Chinese translations here itself. Till now, I haven't seen requests for any other languages, and considering that the amount of contributors that understand Chinese is significant, I hope it won't be much of a burden to maintain. I'm not a Chinese speaker, so I'm mostly reviewing the PRs using translation tools and stuff. This might not result in top-notch quality for Chinese docs, but it should be fine as long as our Chinese users keep contributing.
