### ISSUE TITLE
Customize footer padding

### ISSUE THREAD

**Issue by vedxp** [vuejs/vitepress#1307]
I've tried all the way I could to figure out how to customize the footer padding, but couldn't succeed.

Will be glad if someone guides me.

##### I'm trying to reduce that (reference image) too large padding (big white space) between the `Home Content` and `Footer Section`

<details><summary>Reference Image</summary>

![chrome_screenshot_1662623941764](https://user-images.githubusercontent.com/87353286/189068734-8e25cbc6-6ead-4722-b20b-136570dbf9bf.png)

</details>

**Comment by brc-dd** [comment]
Show us your code.
