### ISSUE TITLE
themeConfig logo option results in an `img` output without `alt` attribute

### ISSUE THREAD

**Issue by Volker-E** [vuejs/vitepress#1309]
### Describe the bug

When using 
```
themeConfig: {
		logo: '/logo-Wikimedia.svg'
}
```
the `img` output doesn't feature an `alt` attribute required for screenreaders. 
Either a duplication of the title or better a required `logoAlt` key would be useful.

### Reproduction

Go to https://doc.wikimedia.org/codex/main/ and inspect the source:
`<img class="VPImage logo" src="/codex/main/logo-Wikimedia.svg" data-v-d5fed348="">`

### Expected behavior

`img` tags need to feature an `alt` attribute to be valid HTML. Starting with an empty one and providing an option to define the value would be necessary.

### System Info

```shell
VitePress 1.0.0-alpha.10
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Zhengqbbb** [comment]
> ### Describe the bug
> When using
> 
> ```
> themeConfig: {
> 		logo: '/logo-Wikimedia.svg'
> }
> ```


```ts
  export type ThemeableImage = Image | { light: Image; dark: Image }
  export type Image = string | { src: string; alt?: string }
```

You  can use like:
```
themeConfig: {
      logo: {
         src: '/logo-Wikimedia.svg',
         alt: 'logo'
   }
}
```

Maybe we can provide default `alt` text like `logo` ?

**Comment by Volker-E** [comment]
@brc-dd Thanks, haven't seen that piece of the docs. 👍🏼 

Having not set the `alt` should still result in at least `alt=""`.

**Comment by brc-dd** [comment]
Yeah, feel free to create a PR. `src/client/theme-default/components/VPImage.vue` needs something like `:alt="image.alt || ''"` (after line 22).
