### ISSUE TITLE
Support error lines in code blocks

### ISSUE THREAD

**Issue by Newbie012** [vuejs/vitepress#1314]
### Is your feature request related to a problem? Please describe.

I want to be able to write an error message inside my code block and make it look like it's an error.

Currently, it blends with the code:

![image](https://user-images.githubusercontent.com/10504365/189338096-550ba47e-b931-4049-9b8b-3d4a26a5f673.png)

### Describe the solution you'd like

I'm not sure if there's a known syntax for it, but I would like the option to "highlight" a row as an error row:

```
```typescript{2:error}
client.query(sql`
    SELECT idd FROM comments
           ~~~ <<<< Invalid Query: column "idd" does not exist
`);

 ```.
```

![image](https://user-images.githubusercontent.com/10504365/189338146-42a983f4-2a21-4061-b3b2-ec4aef034856.png)

### Describe alternatives you've considered

Haven't found any

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
As a workaround, [add these styles](https://vitepress.vuejs.org/guide/theme-introduction#customizing-css):

```css
.error {
    --vp-code-line-highlight-color: var(--vp-c-red-dimm-2);
}
```

And in markdown, do something like this:

````
<div class="error">

```ts{3}
client.query(sql`
    SELECT idd FROM comments
           ~~~ <<<< Invalid Query: column "idd" does not exist
`);
```

</div>
````

This won't work if you want normal as well as error highlighting in same code block.

**Comment by Newbie012** [comment]
That's amazing! thanks!
