### ISSUE TITLE
Module "fs" has been externalized for browser compatibility. Cannot access "fs.readdirSync" in client code.

### ISSUE THREAD

**Issue by LadyChatterleyLover** [vuejs/vitepress#1315]
### Describe the bug

vue component use fs module:   Module "fs" has been externalized for browser compatibility. Cannot access "fs.readdirSync" in client code.

### Reproduction

import fs from 'fs'
fs.readdirSync()

### Expected behavior

vue component can use fs module

### System Info

```shell
Chrome 105.0.5195.102
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
No, you cannot use fs in client-side code.
