### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by yeojongki** [vuejs/vitepress#1329]
### Describe the bug

An error occurred while building with `vitepress@1.0.0-alpha.13` (`vite@3.1.0`) and `ant-design-vue`  **(dev working!)**
> SyntaxError: Cannot use import statement outside a module

![image](https://user-images.githubusercontent.com/21023676/189799200-9eba0378-cbac-4754-9916-eee2f6d3039e.png)

### Reproduction

# Steps:
1. create a new project
2. register a custom component `custom-button`
3. use the `custom-button` in `index.md`
4. building with vitepress

Reproduction repo: 
https://github.com/yeojongki/vitepress-cannot-use-import-statement-outside-a-module `(cd docs && pnpm i && pnpm build)`

### Expected behavior

success build

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 12.70 GB / 31.97 GB
  Binaries:
    Node: 16.13.0 - E:\nodejs\node.EXE
    Yarn: 1.22.17 - E:\nodejs\yarn.CMD
    npm: 8.1.3 - E:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-alpha.13 => 1.0.0-alpha.13
```

### Additional context

relative issue https://github.com/vuejs/vitepress/issues/324, but closed

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Same reason as https://github.com/vuejs/vitepress/issues/1399#issuecomment-1258364648. Create an issue on their repo.
