### ISSUE TITLE
UserConfig allows `markdown` prop but it is then ignored

### ISSUE THREAD

**Issue by ksnyde** [vuejs/vitepress#133]
**Describe the bug**
The typing for `UserConfig` includes a `markdown` property which gives you access to the **mardown-it** options. This is an incredibly useful feature but sadly even though I put this into the `.vitepress/config.js` and it is indeed picked up and placed into the UserConfig that property is then ignored and not processed by the `createVitePressPlugin()`. 

I can create a PR for this if that of any help.

**To Reproduce**
add a `.vitepress/config.js` which includes:

```js
modules.exports = {
  // ...
  markdown: {
    config: md => { console.log("made it") }
 }
}
```

**Expected behavior**
it should report "made it" when running `vitepress dev`

**System Info**
- vitepress version: 0.7.4
- vite version: v1.0.0-rc.9
- Node version: 12.19.0
- OS version: macOS

**Additional context**

**Comment by ksnyde** [comment]
Interestingly I can see that the `resolveConfig` function in the `src/node/config.ts` file DOES put the markdown from the user's config into the site config. However, Using the same release of `0.7.4` it appears that this change did not make it into the JS build!

**Comment by kiaking** [comment]
Yes, this is already implemented but not released yet! We'll be making a release soon so please stay tuned 🙌

**Comment by ksnyde** [comment]
@kiaking ok great! btw, I believe I have a very useful fix to the way Vuepress and Vitepress configure the `htmlBlock` rule. It's pretty broken right now when you use components with slot content which you don't want processed by markdown. With this fix I can put this change in place for myself but would it be worth adding it as a PR?

**Comment by kiaking** [comment]
@ksnyde Cool! I think it would be great to have an issue opened for that topic first, describing what the problems are, and how to fix it. Currently, I'm not 100% sure if I'm following your thoughts so 😳

**Comment by ksnyde** [comment]
Since this code is in effect the same for Vitepress and Vuepress in this area, shall i just do it here first?

**Comment by kiaking** [comment]
Hmmmm good question. I think you can do it here first, might be quicker to get responses due to less traffic 😅
