### ISSUE TITLE
How to add register language/grammar for shiki?

### ISSUE THREAD

**Issue by lslzl3000** [vuejs/vitepress#1331]
when use some new language blocks in `md`, such as `wgsl`, it shows `No language registration for wgsl`

The shiki support add custom languages: https://github.com/shikijs/shiki/blob/main/docs/languages.md#supporting-your-own-languages-with-shiki

Then, how to use it in VitePress to add custom languages?

**Comment by brc-dd** [comment]
Pass custom highlighter (`markdown.highlighter`) using config.

**Comment by lslzl3000** [comment]
is there an option `highlighter` in `MarkdownOptions`?

https://github.com/vuejs/vitepress/blob/6b16dad22f944cb173dbf67ef04be5cb0d09279f/src/node/markdown/markdown.ts#L33-L49

**Comment by brc-dd** [comment]
Sorry it's `highlight`. It's there in `MarkdownIt.Options`

**Comment by lslzl3000** [comment]
@brc-dd the `highlight` seems to be an `async` function by calling `getHighlighter` or `loadLanguage`.
The default `hightlight.ts` also works with `await`

So it is not working with an async `option.hightlight` in `config.ts`, or use Top-level `await` in config

maybe it should be :
```ts
highlight: options.highlight ? (await options.hightlight(options.theme)) : (await highlight(options.theme)),
```
or just pass custom `hightlighter` in `hightlight.ts`
```ts
highlight: await highlight(options.theme, option.hightlighter),
```

**Comment by brc-dd** [comment]
You can return async config too. Refer https://github.com/vuejs/vitepress/issues/1067#issuecomment-1195187680

**Comment by lslzl3000** [comment]
> You can return async config too. Refer [#1067 (comment)](https://github.com/vuejs/vitepress/issues/1067#issuecomment-1195187680)

thanks, I will try

**Comment by huyikai** [comment]
Supplement a method  [https://github.com/shikijs/shiki/blob/main/docs/languages.md#adding-grammar](https://github.com/shikijs/shiki/blob/main/docs/languages.md#adding-grammar)
