### ISSUE TITLE
build error with code: ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by edgexie** [vuejs/vitepress#1335]
### Describe the bug

I used the third part lib named [troisjs](https://github.com/troisjs/trois),

build error with code: ERR_REQUIRE_ESM

### Reproduction

my project is at https://github.com/edgexie/edgexie.github.io
with the [action records](https://github.com/edgexie/edgexie.github.io/actions/runs/3045694918/jobs/4907563820) , it show the error at build step, the error screen shot:

![image](https://user-images.githubusercontent.com/18474752/189923527-cc432068-9bcb-4fe8-abda-fdc9d5544742.png)

### Expected behavior

build pass

### System Info

```shell
sys: Windows 10 Version 21H2
node: 16.17.0
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Some stuff needs to be done at Trois' side. If I patch the package to use .mjs instead of .module.js and change the import to 'troisjs/build/trois.mjs' it works fine. (You'ld also need to wrap `Renderer` with `ClientOnly` as canvas won't be available during SSR.)
