### ISSUE TITLE
Passing a ref() variable to Vuetify v-model

### ISSUE THREAD

**Issue by dulimarta** [vuejs/vitepress#1336]
### Describe the bug

Variable declared in the setup script using Vue3 composition API is not recognized by Vuetify 3 components

### Reproduction

I have the following in an `.md` file

```
<script setup>
import {ref} from "vue"

const myArr = ref([10, 20, 30]);
const myTab = ref(0)
</script>

Some text here

The following works file

<MyCustomComponent v-for="x in myArr">
</MyCustomComponent>

But the following DOES not work

<v-tabs v-model="myTab">
  <v-tab>One</v-tab>
  </v-tab>Two</v-tab>
</v-tabs>
```

The error I saw in the browser console is:

```
runtime-core.esm-bundler.js:2779 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at invokeDirectiveHook (runtime-core.esm-bundler.js:2779:47)
    at Array.<anonymous> (runtime-core.esm-bundler.js:5349:25)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:339:32)
    at flushJobs (runtime-core.esm-bundler.js:393:9)
```

### Expected behavior

No error expected

### System Info

```shell
Works on Firefox (Windows 11), but does not work on Chrome (Windows 11 and OSX)
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I'm not able to reproduce this on chrome on osx. You probably need `ref(null)` instead of `ref(0)` or maybe `v-tab` needs `value`: `<v-tab value="one">Item One</v-tab>`.
