### ISSUE TITLE
Syntax highlight on inline code

### ISSUE THREAD

**Issue by Zhengqbbb** [vuejs/vitepress#1343]
### Is your feature request related to a problem? Please describe.

Support syntax highlight on inline code of docs. It would be cool when writing the type, default value ... of option

### Describe the solution you'd like

```md
## appearance
  - Type: `boolean`{ts}
  - Default: `true`{ts}
```
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/40693636/190310833-38d80ab3-1475-43ca-ba39-4f987898ce2a.png">

### Describe alternatives you've considered

Currently I can use the `transformHtml` hook to do it. But i think if vitepress could have built in support, it would be nice.

### Additional context

https://twitter.com/Atinux/status/1531266838583296001

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/40693636/190311477-56741220-d497-484f-89e9-be3677d5ebde.png">

https://github.com/nuxt/content/blob/b4e9591fc61c91551fb6e032f3bf62f8fe8e6159/docs/editor/useShiki.ts#L92-L108

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not seeing any demand for this. Closing as stale.
