### ISSUE TITLE
Built content when served manually (not `vitepress dev <src>`) adds a 404 page at end of page, and later navigation loads the page there at bottom replacing 404 at the bottom.

### ISSUE THREAD

**Issue by Animeshz** [vuejs/vitepress#1345]
### Describe the bug

Mainly described in the title, further description is at 4th point of reproducing the error. This is reproduced in normal python http server, and seems to happen in github pages as well.

Might be related to #412, but I don't think its exactly the same behavior & cause.

### Reproduction

1. Download the repro and unzip, it should have the following content:

```bash
.
├── content
│   ├── first
│   │   ├── index.md
│   │   └── second.md
│   └── index.md
├── package.json
└── yarn.lock
```

[vitepress-repro.zip](https://github.com/vuejs/vitepress/files/9575259/vitepress-repro.zip)

2. Run `yarn && yarn run content:build`
  a `site` folder at project root should be created.
4. Run `python3 -m http.server -d . 4000`, and lookup `localhost:4000/site`.
  Everything looks fine, you can navigate to First using navbar, and second.md file in first by left panel.
5. Now refresh at the same `localhost:4000/site/first/second`.
  You should see the page is loaded but a 404 page is added at the bottom too, now if you try to navigate, the top of page remains as is, the bottom of page is instead replaced by the new content.

### Expected behavior

Page should not append a 404 page, nor it should load navigated pages in bottom of page instead of replacing current page.

### System Info

```shell
System:
    OS: Linux 5.18 Void
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 3.97 GB / 7.56 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 16.15.1 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.11.0 - /usr/bin/npm
```

### Additional context

Full page screenshot

![screencapture-localhost-4000-site-first-second-2022-09-15-17_56_03](https://user-images.githubusercontent.com/26714676/190403628-11e614b2-d16f-4582-ac2b-5ccc53ec746e.png)

Two errors, in order appears in the browser's console:

```
Failed to load resource: the server responded with a status of 404 (File not found) :4000/site/assets/first_second_index.md.undefined.lean.js:1

Hydration completed but contains mismatches. app.558d10a0.js:1
```

Point to be noted is that `first_second_index.md.undefined.lean.js` is trying to get fetched, i.e. the "undefined" hash.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Animeshz** [comment]
Seems to be that it happens only with `cleanUrls: 'with-subfolders'` in the `content/.vitepress/config.js` file.

So might be related with cache validation or etc. in the clean-url feature.

**Comment by brc-dd** [comment]
For with-subfolders option to work, your server must serve `foo/index.md` (without redirect) when requesting `/foo` (without trailing slash). I don't think a python http server will do that by default.
