### ISSUE TITLE
language-c# missing 'line-numbers-mode' class

### ISSUE THREAD

**Issue by lslzl3000** [vuejs/vitepress#1352]
### Describe the bug

I have enabled `lineNumbers` option in `config`
The `ts`, `html`, `js` works fine

But the `c#` is missing `line-numbers-mode` class so that losing `padding-left` style
![Screen Shot 2022-09-17 at 20 39 53](https://user-images.githubusercontent.com/3398981/190857215-d2931827-9d41-4fa6-89ed-662183bd7100.png)

Is this a bug? maybe the `#` problem?

By vitepress-1.0.0-alpha.15

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> Is this a bug? maybe the `#` problem?

Yeah. This regex needs to be updated:

https://github.com/vuejs/vitepress/blob/50f4105752623599426ffef0087d18c8775c55c9/src/node/markdown/plugins/lineNumbers.ts#L24

**Comment by sun0day** [comment]
I can offer a PR @brc-dd
