### ISSUE TITLE
Options to force dark mode as default theme?

### ISSUE THREAD

**Issue by lslzl3000** [vuejs/vitepress#1359]
Is there any way to force dark color theme as default one, even if the user system preference is lightmode?

**Comment by kiaking** [comment]
We don't have this feature at the moment, but sounds like a nice to have 👍  Maybe `appearance` option could take `'light' | 'dark'` as an option and make it default?

**Comment by innocenzi** [comment]
I PR'd #1498 to support this feature. In the meantime, my workaround is to add the following to my config's `head`:

```ts
['script', {}, 'window?.localStorage?.setItem("vitepress-theme-appearance", window?.localStorage?.getItem("vitepress-theme-appearance") ?? "dark")'],
```
