### ISSUE TITLE
Add support for collapsible multi-level sidebar

### ISSUE THREAD

**Issue by LittleSound** [vuejs/vitepress#1360]
### Is your feature request related to a problem? Please describe.

I would like to have to collapsible navigation sidebar since I organize my documents  by using multiple layers of folders, which is frustrating to browse or lookup the content/page I want.

VitePress only supports the top-level folders to be collapsible in the navigation sidebar currently.

### Describe the solution you'd like

The default theme that VitePress provided could support multi-level sidebar to be collapsible since many of the people may also face such kind of the problem while using VitePress.

### Describe alternatives you've considered

I have tried to override the `VPSidebarNav` component from default theme that VitePress provided, however, the theme configuration overridding is not supported currently (related issue is still open, ref: #235 ), or I would have to duplicate the default theme as a single repository and publish it as a npm package after the development is done by myself. Anyways, I may think this kind of the feature is general for most of the users, it should be provided by VitePress, nor by users.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by awbait** [comment]
+

**Comment by LittleSound** [comment]
> -

What's happening?

**Comment by awbait** [comment]
![image](https://user-images.githubusercontent.com/12417799/195571256-c1d9cac5-7ea0-444c-8d5c-6ef0365f4ee6.png)
How can I collapse this item?

**Comment by nekomeowww** [comment]
This kind of feature is awesome, I would really need it!
Do you guys have a roadmap or plan for when the feature would be released?

**Comment by brc-dd** [comment]
I'm currently working on the code groups feature, will review and try to get #1361 merged within this week. Sorry for the delay 😓

**Comment by kiaking** [comment]
I'll take that PR over to adjust the design a bit 👍

**Comment by Goozoon** [comment]
> I'll take that PR over to adjust the design a bit 👍

Great. Please add (i think it is called --vp-c-brand element) so it will look something like this
<img width="179" alt="Screenshot 2022-12-07 101905" src="https://user-images.githubusercontent.com/48757340/206139249-3361d7d2-1461-4b74-971c-424c29232432.png">

We have it already for the right side 'on this page' already. For that part i would add some padding under 'on this page' text and some multileveling for the rest. Something like this but in Vitepress style
<img width="205" alt="Screenshot 2022-12-07 101939" src="https://user-images.githubusercontent.com/48757340/206139735-a7d4d2fe-dbb7-40ef-890e-c20af33952c8.png">

Thank you Kia King

**Comment by awbait** [comment]
we are looking forward to it

**Comment by mrcego** [comment]
Waiting for this. In the company I'm currently working we are populating a doc with Vitepress, and we need three levels of categories in one of the team page.

**Comment by Zhengqbbb** [comment]
Expecting and waiting for this. I think the next step should be to push this feature.
