### ISSUE TITLE
Character Appearance changed vom 1.0.0-alpha.13 to 1.0.0-alpha.14

### ISSUE THREAD

**Issue by MarkusKeck** [vuejs/vitepress#1362]
### Describe the bug

The character appearance changed from vitepress version 1.0.0-alpha.13 to 1.0.0-alpha.14.

The character:
https://www.compart.com/de/unicode/U+21A9

↩︎ gets now displayed as icon. Before it was displayed as normal entity.

I am currently using markdown-it-footnote which uses this character to link at every occurence of the given footnote.

Before:
![image](https://user-images.githubusercontent.com/19492739/190913714-b3282ffe-5629-4c68-a304-55e89524d434.png)

After:
![image](https://user-images.githubusercontent.com/19492739/190913747-8f1a7b15-192f-4795-b7dd-ffae7e7eb259.png)

### Reproduction

Use markdown-it-footnote with both versions.

### Expected behavior

Should not display the character as icon

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 107.12 GB / 127.91 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.14 => 1.0.0-alpha.14
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's still a unicode character. It depends on your available fonts what it will be rendered like. Unless a suitable font (having glyph for that character) is explicitly defined in theme, it will be system and browser dependent.

**Comment by brc-dd** [comment]
Try overriding the font family in some custom CSS file.
