### ISSUE TITLE
virtual modules are blocked in github pages

### ISSUE THREAD

**Issue by emersonbottero** [vuejs/vitepress#1364]
### Describe the bug

I done some plugins for vitepress that uses virtual modules.. 
but as those start with _ github pages block them.. 
I fount [this issue for vite](https://github.com/vitejs/vite/issues/9119) but didn't manage to implement the solution!

you can check the behavior in [Mermaid Plugin](https://emersonbottero.github.io/vitepress-plugin-mermaid/)

![image](https://user-images.githubusercontent.com/12377432/190934328-edeae22d-001a-4200-a305-e22533114d59.png)

### Reproduction

use virtual modules...

### Expected behavior

the output should not generate files starting with _

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 5.68 GB / 15.92 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 105.0.5195.127
    Edge: Spartan (44.22621.598.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can emit a `.nojekyll` file from your plugin to outDir?

**Comment by brc-dd** [comment]
We can fix this here too. Custom `sanitizeFileName` function should work. We probably can borrow [the default one](https://github.com/rollup/rollup/blob/71eefd13c8b147fdcb9847b9373971e49139c026/src/utils/sanitizeFileName.ts) and replace leading underscores. PRs are welcome.

**Comment by emersonbottero** [comment]
> You can emit a `.nojekyll` file from your plugin to outDir?

it worked when I placed this file inside Public folder.
Maybe the docs should warn about that, not sure if in vitepress or vite docs but one of the 2?
