### ISSUE TITLE
Could not resolve ".../node_modules/vue/dist/vue.runtime.esm-bundler.js"

### ISSUE THREAD

**Issue by GordonSmith** [vuejs/vitepress#1367]
### Describe the bug

When launching developer server I get the following error:

`Could not resolve ".../node_modules/vue/dist/vue.runtime.esm-bundler.js"`

### Reproduction

Install vitepress without installing vue

### Expected behavior

No dependency on vue

### System Info

```shell
v1.0.0-alpha15
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you share your code. I am unable to reproduce this:

![image](https://user-images.githubusercontent.com/40380293/191021912-d85d4de1-0ec1-4353-9934-abc9d600470d.png)

**Comment by GordonSmith** [comment]
Sure - FWIW the issue happened once I bumped the version from 0.22.4 to the latest alpha:  https://github.com/hpcc-systems/Visualization
And the rendered page:  https://hpcc-systems.github.io/Visualization/

**Comment by kiaking** [comment]
Is this still happening on latest VitePress version?

**Comment by GordonSmith** [comment]
@kiaking - this appears to be resolved now - thx.
