### ISSUE TITLE
In Monoreop Failed to start dev, prompting Cannot read property 'accept' of undefined

### ISSUE THREAD

**Issue by chenyo2691** [vuejs/vitepress#1374]
### Describe the bug

In Monorepo, when the document starts dev, the error `Uncaught TypeError: Cannot read property 'accept' of undefined` is reported. An attempt was made to comment out the wrong vue file, but the error still exists, except that the vue file that reported the error is different.

my .nrmrc file only sets `shamefull host=true`, and it is no problem to use non monorepo on my computer.

Please help.

![图片](https://user-images.githubusercontent.com/8911831/191205358-90ef85e5-1868-4006-b74f-b21a55c0f9ab.png)

### Reproduction

Use monoeop, then use the steps in the tutorial to install vitepress and start it

### Expected behavior

normal operation

### System Info

```shell
System:
    OS: Windows 10 10.0.16299
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 10.34 GB / 15.89 GB
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (41.16299.1004.0)
    Internet Explorer: 11.0.16299.371
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by tada5hi** [comment]
having the same issue...

**Comment by brc-dd** [comment]
Any example (minimal) monorepo where I can test this out?

**Comment by flingyp** [comment]
I just encountered this problem, but I can't describe it well This problem occurs when I downgrade and upgrade the vitepress version to 9, 13 and 15 But both modes are in Local mode. When I switch to Network mode and start it once, both modes are normal and this error does not occur.

**Comment by chenyo2691** [comment]
> Any example (minimal) monorepo where I can test this out? And which version of VitePress are you using? Was it also happening on earlier versions too?

Monorepo test environment is difficult to provide for you. This problem occurs above alpha 6, including alpha 6

**Comment by brc-dd** [comment]
> Monorepo test environment is difficult to provide for you.

If code cannot be provided, at least more context? Like how is your monorepo structured and what tools are you using (like pnpm/yarn workspaces, lerna/nx)?

**Comment by flingyp** [comment]
> 

![image](https://user-images.githubusercontent.com/57666140/191999686-8ee7f33d-318b-420a-b548-fbc2bed78061.png)

**Comment by flingyp** [comment]
> 

![image](https://user-images.githubusercontent.com/57666140/191999686-8ee7f33d-318b-420a-b548-fbc2bed78061.png)

**Comment by brc-dd** [comment]
Refer #1395. It'll be fixed once Vite releases a new version.

**Comment by hminghe** [comment]
tsconfig.json set target = ESNext

**Comment by jinan5694** [comment]
> 

helpful for me.
