### ISSUE TITLE
[i18n] allow translating docsearch labels

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#1381]
### Discussed in https://github.com/vuejs/vitepress/discussions/1368

<div type='discussions-op-text'>

<sup>Originally posted by **Zogsha** September 19, 2022</sup>
Hi, thanks for your work on vitepress!

My documentation site is written in French, so I need the Docsearch component in French.

I have two problems :

1. There is a `algolia.buttonText` option in `themeConfig`. I set it to "Rechercher" instead of the default "Search", but whenever I click on the search component or use "CTRL+K", the placeholder turns back to "Search". It only displays "Rechercher" when the page refreshes. I only tested in dev.

2. In the Docsearch API Reference, there is `translations` option (https://docsearch.algolia.com/docs/api#translations). I can't figure out how to configure it.

I think __1.__ is not intended, but I didn't look further. Is __2.__ intended ? If that is the case, do you plan to let us translate the Doscsearch modal via `algolia` config in `themeConfig`?

Thanks,
Aliosha</div>

**Comment by kiaking** [comment]
Well currently at the initial render, we display placeholder that mimics Algolia search button, and when user clicks on the button, Algolia will render its button.

So, we should pass in those VitePress config to Algolia I guess 👀 

For (2), the `translations` key... maybe we should support it? I mean if it's set, we use that for VitePress's placeholder too.

**Comment by brc-dd** [comment]
@Zogsha Regarding (2), you can configure it like this:

https://github.com/vuejs/theme/pull/77/files#diff-585adda3a14269070e46c75cbf581e313461a97f7a6edfe4ca0e12a114a6f243R38-R50

**Comment by fake-car** [comment]
Could the rest apis supported? Like resultsFooterComponent or transformSearchClient

**Comment by brc-dd** [comment]
@fake-car I haven't tested those, but IG that would break the app as the resultant site data after that won't be serializable.

**Comment by fake-car** [comment]
@brc-dd Thanks a lot, I will give it try.
