### ISSUE TITLE
Allow custom markdown-it plugin to be loaded first

### ISSUE THREAD

**Issue by JingMatrix** [vuejs/vitepress#1382]
### Is your feature request related to a problem? Please describe.

Current user's config in the markdown option is loaded after all pre-defined plugins. This enables use to do some initial works for other plugins but not able to hook their results.

### Describe the solution you'd like

I would like to have `configAfter` and `configBefore` two different options to load my own markdown-it plugin.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah, we can add that for sure. But it will be the users' responsibility to not generate (intermediate) output that may break our internal plugins (as they have highly linked logic).
