### ISSUE TITLE
Docker build error:Error: spawn git ENOENT

### ISSUE THREAD

**Issue by ringgoyao** [vuejs/vitepress#1383]
### Describe the bug

I run vitepress in docker, it works fine  when 1.0.0-alpha.4,after I upgrade  1.0.0-alpha15, it show errors:
![image](https://user-images.githubusercontent.com/5906943/191634880-acfdc95e-02b9-4298-a2d1-18af83ea22ce.png)
after try times, I add one line code:
RUN  apk add --no-cache git
then it works as before.so  I want to know what casuse it?

### Reproduction

``` yml
FROM node:16.14-alpine AS builder

ENV PORT 80
ENV HOST 0.0.0.0

WORKDIR  /usr/src/app

COPY package.json ./
# RUN  apk add --no-cache git
RUN  yarn
COPY . .
RUN yarn  build
CMD yarn serve
```

### Expected behavior

If  I  keep  the dockfile as follows ,it still can work
```
 FROM node:16.14-alpine AS builder

ENV PORT 80
ENV HOST 0.0.0.0

WORKDIR  /usr/src/app

COPY package.json ./
RUN  yarn
COPY . .
RUN yarn  build
CMD yarn serve

```

### System Info

```shell
Centos 8
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you share your .vitepress/config too?

**Comment by ringgoyao** [comment]
@brc-dd   The config.ts code 
 `import { defineConfig } from 'vitepress'
export default defineConfig({
  lang:"zh-CN",
  head: [
    [
      'meta',
      {
        name: 'viewport',
        content:
          'width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no',
      },
    ],
    ['meta', { name: 'keywords', content: '' }],
    ['link', { rel: 'icon', href: '/favicon.ico' }],
  ],
  title: '',
  description: '',
  base: '/',
  lastUpdated: true,
  themeConfig: {
    logo: './logo.png',
    nav: [
      { text: 'home', link: '/' },
      {text:'markdown',link:'/about/index'}
    ],
    socialLinks:[],
    sidebar: [
        {
          text: 'share',
          items:[
            {
              text:'uni-app+vite+ts',
              link:'/share/uni-app'
            }
          ]
        }
    ]
  }
})`

**Comment by Zhengqbbb** [comment]
> RUN apk add --no-cache git then it works as before.so I want to know what casuse it?

Base git command to getGitTimestamp:
https://github.com/vuejs/vitepress/blob/ce8d139a8e70e4d0a8d06711c50119990b041078/src/node/utils/getGitTimestamp.ts#L5

Maybe we can check git command is found. And then throw warm msg of term.

**Comment by brc-dd** [comment]
You have lastUpdated set to true. To use it you need git installed. Disable it if you don't want to install git.
