### ISSUE TITLE
didn't process local logo in home page when build

### ISSUE THREAD

**Issue by fyzhu** [vuejs/vitepress#1386]
### Describe the bug

didn't process local logo in home page when build

### Reproduction

add a home page 
```
layout: home
hero:
  name: xxx
  image:
    src: /images/xxx.jpeg
...
```

npm run build
 

### Expected behavior

copy `/images/xxx.jpeg` to `dist/assets` when build

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 66.69 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.0.2 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 88.0
    Safari: 16.0
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by votommy** [comment]
Yea, this seems to be an ongoing problem with how Vitepress is building the projects. It ignores all references to images that aren't directly linked in .md files. A workaround is to use a permalink for those images. Upload the image somewhere online and link to that image. For me, I just push the image to GitHub and link the raw.githubusercontent.com URL.

**Comment by brc-dd** [comment]
> Upload the image somewhere online and link to that image. For me, I just push the image to GitHub and link the raw.githubusercontent.com URL.

Why not use public directory instead?

**Comment by votommy** [comment]
> Why not use public directory instead?

As long as it's not relying on a local path to the non-existent image file within ```/dist```, it should be fine. But assuming you want to host your website online after building it, as long as the website has access to those images, it should show up.

I guess another workaround is to just manually copy the image over to the ```/dist/assets``` folder after building.

**Comment by kiaking** [comment]
I'm not sure what this means. If you place logo in `public` folder, it gets accessible no matter how you build it. And that's what `public` folder is for.

If you need to copy images from `images` folder to `public` folder, that is pretty much the responsibility of users in my opinion 👀
