### ISSUE TITLE
最新版本出现这样

### ISSUE THREAD

**Issue by gfl13453001** [vuejs/vitepress#1387]
![image](https://user-images.githubusercontent.com/48872288/191914464-2d5ab19b-f390-4411-a7c5-06554750ecb3.png)

有大佬可以帮忙指导下这是什么问题吗

**Comment by Zhengqbbb** [comment]
> 麻烦以后请根据 ISSUE 模版进行规则创建，不然很难帮助你

运行一下命令：
`npx envinfo --system --npmPackages vitepress --binaries --browsers`

查看一下你的 Node 版本，最好使用 Node 16 最新版
