### ISSUE TITLE
JS files prefixed with an underscore name will have the html suffix added

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#1393]
### Describe the bug

![image](https://user-images.githubusercontent.com/25446948/192099566-2f125f02-855c-4be3-a8a9-0b6397da7ac1.png)
![image](https://user-images.githubusercontent.com/25446948/192099654-cd39c15c-dc6f-4c2c-bede-0ed67b623962.png)

![image](https://user-images.githubusercontent.com/25446948/192099608-9c424b4b-46d7-4f2f-9cb5-4cedf9fb99e6.png)
![image](https://user-images.githubusercontent.com/25446948/192099685-69d77a21-ea27-4b25-9b6a-67f20e454a51.png)

### Reproduction

JS files prefixed with an underscore name will have the html suffix added.

### Expected behavior

N/A

### System Info

```shell
N/A
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Are you deploying this to GitHub pages? If yes then add an empty file named `.nojekyll` in your public directory.

**Comment by Charles7c** [comment]
> Are you deploying this to GitHub pages? If yes then add an empty file named `.nojekyll` in your public directory. Probably a duplicate of #1364?

No wonder those deployed on another platform don't have this problem. thanks a lot.
