### ISSUE TITLE
Theme assets missing in MPA mode

### ISSUE THREAD

**Issue by tommie** [vuejs/vitepress#1401]
### Describe the bug

When using `img src=../static/image.png` with `--mpa`, the assets don't make it to the output.

### Reproduction

Build a theme component like

```
<template>
  <img src="../static/logo.svg">
</template>
```

And an image in `.vitepress/theme/static/logo.svg`.

Run `vitepress build`.

### Expected behavior

That `.vitepress/dist/assets/logo.XXXXXX.svg` is present after build.

### System Info

```shell
Vitepress 1.0.0-alpha15
```

### Additional context

Changing `bundle()` so it runs `build(resolveViteConfig(false)` even in MPA mode brings the theme assets over.

(What I'm after is a mode that doesn't include the sitemap on every HTML page. I'm happy to run JS in the client. Was just playing with MPA to see if that would help.)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah I'd noticed this earlier too (https://github.com/vuejs/vitepress/issues/848#issuecomment-1166348478). But considering the default theme is mostly broken too without client js, I don't think MPA can ever be fully supported.

**Comment by kiaking** [comment]
Yeah... I think we should document this when we add `mpa` mode documentation saying that it wouldn't work with Default Theme and that it's meant for more simple usage.

**Comment by brc-dd** [comment]
Docs are updated: https://vitepress.dev/guide/mpa-mode, but still thinks that assets needs to be properly resolved (shouldn't be related to JS, somewhere the logic is wrong IG)

**Comment by Pandapip1** [comment]
I am also having this issue. Any chance this can be fixed?
