### ISSUE TITLE
Consider rolling back the global `word-break: break-word` style

### ISSUE THREAD

**Issue by fvsch** [vuejs/vitepress#1402]
### Describe the bug

A recent update (https://github.com/vuejs/vitepress/pull/1064) added a `word-break: break-word` style to all HTML elements. This leads to unpleasant results such as this in table cells (see the first and last column):

<img width="724" alt="Table after" src="https://user-images.githubusercontent.com/243601/192322921-5ab4d6a1-00e3-48d4-af11-c39c8c3e0265.png">

While before this update the result was much more readable:

<img width="729" alt="Table before" src="https://user-images.githubusercontent.com/243601/192323027-c7ffff4a-5989-497d-9aa0-b50b4c3cf216.png">

### Reproduction

StackBlitz reproduction with a table:
https://stackblitz.com/edit/vitepress-theme-word-break-issue?file=index.md

### Expected behavior

Risky styles such as `word-break: break-word` should not be applied to all elements.

Handling overflowing content (if any) should be done at the component level, probably with specific solutions for each component.

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 117.00 MB / 8.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /Volumes/Pieces/.npm/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox Nightly: 107.0a1
    Safari: 16.0
  npmPackages:
    vitepress: ^1.0.0-alpha.16 => 1.0.0-alpha.16
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Ah right. What if we set `overflow-wrap: break-word;` instead?

**Comment by brc-dd** [comment]
Actually stuff not inside `.vp-doc` was overflowing too (like in #1088). We probably can just use that on all h* and p elements, irrespective of vp-doc/vp-home?

**Comment by brc-dd** [comment]
I've reverted #1064. Haven't added anything new, we will discuss later what might be the best option here.
