### ISSUE TITLE
How to add ssl configure to support https

### ISSUE THREAD

**Issue by yuetaibai** [vuejs/vitepress#1403]
### Discussed in https://github.com/vuejs/vitepress/discussions/1398

<div type='discussions-op-text'>

<sup>Originally posted by **yuetaibai** September 25, 2022</sup>
Thanks in advance~

I need to add the ssl certificate to support https access from internet, here is ./docs/.vitepress/config.js

```js
module.exports = {
  server: {
      https: {
        cert: fs.readFileSync(path.join(__dirname, 'cert/cert.crt')),
        key: fs.readFileSync(path.join(__dirname, 'cert/cert.key')),
        ca: fs.readFileSync(path.join(__dirname, 'cert/ca.crt')),
      }
    }
}
```

here is ./package.json
```js
{
  "scripts": {
    "docs:dev": "vitepress dev docs --port 3002 --https",
  },
}
```
With the above config, run the server by "yarn docs:dev --host" successfully. But when access the Vitepress, always prompt "ERR_SSL_VERSION_OR_CIPHER_MISMATCH"

Any help would be appreciated !

</div>

**Comment by brc-dd** [comment]
That stuff should go in vite.config.ts not .vitepress/config.ts

**Comment by yuetaibai** [comment]
Thanks for the support.
With the vite.config.ts config:
```shell
export default defineConfig({
  plugins: [
      vue()
  ],
  server: {
    https: {
      cert: fs.readFileSync('./server.crt')),
      key: fs.readFileSync('./server.key'))
    }
  }
})
```

Run command:
```shell
yarn docs:dev --host --https --config vite.config.ts
```

It shows:
```shell
$ vitepress dev docs --port 3002 --host --https --config vite.config.ts
vitepress v1.0.0-alpha.15

  ➜  Local:   https://localhost:3002/
  ➜  Network: https://192.168.0.193:3002/
```

However, when I access the website with Chrome, it prompts "ERR_SSL_VERSION_OR_CIPHER_MISMATCH".

New to vite and vitepress, thanks for your patience.

**Comment by brc-dd** [comment]
Not sure, but looks like some issue with your certificates as using the official plugin seems to work fine:

```ts
// docs/vite.config.js
import basicSsl from '@vitejs/plugin-basic-ssl'

export default {
  plugins: [
    basicSsl()
  ]
}
```

**Comment by yuetaibai** [comment]
It works! Thanks for your support.

Here is the file structure:

```shell
├── .cert
│   ├── server.crt
│   └── server.key
├── docs
│   ├── index.md
│   ├── vite.config.js
├── package.json
```

vite.config.js:
```shell
import { defineConfig } from 'vite'

const fs = require('fs')

export default defineConfig({
  server: {
    https: {
      key: fs.readFileSync('./.cert/server.key'),
      cert: fs.readFileSync('./.cert/server.crt')
    },
    port: 443
  },
})
```

**Comment by yuetaibai** [comment]
I come across another problem, with the below command:
```js
yarn docs:build
yarn docs:serve --https

# It comes with the prompt:
yarn run v1.22.19
warning ../package.json: No license field
$ vitepress serve docs --https --port 443
vitepress v1.0.0-alpha.22
Built site served at http://localhost:443/
```
**Here is the question:** How to run the vitepress web app with https by command `yarn docs:serve`, thanks a lot~~

*BTW, 'yarn docs:dev --https --port 443 --host' command run the https://localhost:443/, which could satisfy the requirements, but the web can't show on mobile chrome~

**Comment by brc-dd** [comment]
Use https://www.npmjs.com/package/http-server to serve `docs/.vitepress/dist`. Command will be something like this:

```sh
npx http-server ./docs/vitepress/dist -p 443 -S -C  ./.cert/server.crt -K ./.cert/server.key
```
