### ISSUE TITLE
Add vite.conf.js to overloading config

### ISSUE THREAD

**Issue by kugatsu765** [vuejs/vitepress#1406]
### Describe the bug

Hello, 

I want to add vite.config.js because i have to add entry to my server allow list

<img width="1245" alt="Capture d’écran 2022-09-27 à 14 20 52" src="https://user-images.githubusercontent.com/41836255/192524958-f2f2189c-47ef-40ae-a817-dd95c1b8de8b.png">

But It seem not to be use by vitepress. Maybe i did something wrong.

Thanks by advance

### Reproduction

- Create new vitepress project
- Add vite.config.js at the root of the project
- Add some specific configuration

```js
import { defineConfig } from 'vite'
export default defineConfig({
    server: {
        port: 3030
    }
})

```

- restart.

### Expected behavior

Should use the new port to serve app

### System Info

```shell
Use the default config instead of custom
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You probably have placed vite.config.js at wrong place. It's working fine for me:

![image](https://user-images.githubusercontent.com/40380293/192854676-f1780dfc-f2f1-4a17-a145-7e5772c92bbb.png)

If you run `vitepress foo`, then you need to put it inside `foo` not cwd.

**Comment by kugatsu765** [comment]
Ok, thanks. 

It works when i put vite.conf.ts in docs folder. 

Have a good day
