### ISSUE TITLE
ReferenceError: Cannot access 'xxx' before initialization When use `v-bind(xxx)` in <style>

### ISSUE THREAD

**Issue by geotify** [vuejs/vitepress#1411]
### Describe the bug

ReferenceError: Cannot access 'xxx' before initialization When use `v-bind(xxx)` in <style>

### Reproduction

// .md
\<ClientOnly\>\<TheCp \/\>\<\/ClientOnly\>

// .vue script setup
const xxx = ref('0')

// .vue style
.test {
  right: v-bind(xxx);
}

### Expected behavior

support v-bind in style

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
    Memory: 3.26 GB / 15.80 GB
  Binaries:
    Node: 16.13.1 - D:\src\node\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.0 - D:\src\node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.50)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.15 => 1.0.0-alpha.15
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It should work. What's the structure of template of your vue file?

**Comment by geotify** [comment]
> It should work. What's the structure of template in your vue file? See this: https://stackblitz.com/edit/vite-qqq1jl?file=docs%2Findex.md,docs%2FFooBar.vue -- it works fine.

when use computed, the error show

![2022-09-29_140435](https://user-images.githubusercontent.com/97531038/192952369-c71380c6-3467-4708-8df9-a97b7b704b2b.png)

https://stackblitz.com/edit/vite-wvcapx?file=docs%2Findex.md,docs%2FFooBar.vue

**Comment by geotify** [comment]
i known. it need import computed. maybe my vitepress not use auto-import.
