### ISSUE TITLE
 Error: Missing "./preload-helper" export in "vite" package

### ISSUE THREAD

**Issue by gengzhaoji** [vuejs/vitepress#1412]
### Is your feature request related to a problem? Please describe.

npm run build 错误

### Describe the solution you'd like

解决该打包问题

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Create this issue with bug template and fill out the details including a minimal reproducible example.
