### ISSUE TITLE
Deploying to github pages and lost both router and content 

### ISSUE THREAD

**Issue by Hellager** [vuejs/vitepress#1413]
### Describe the bug

Just follow the document, add workflow and push docs to repo.
Vitepress works well locally with `pnpm docs:dev`, but after deploy to github pages, it losts the index.md content, or in another word, useful part of them, as you can see, it does have the notes part
[![xniiA1.md.png](https://s1.ax1x.com/2022/09/29/xniiA1.md.png)](https://imgse.com/i/xniiA1)
I have checked the local build file, it contains the correct content.
Since i used the exact workflow and already set the `base` config, i can't figure out why it leads to this.

### Reproduction

clone this repo [Youbei](https://github.com/Hellager/Youbei) and deploy its docs to the github pages

### Expected behavior

Github pages show normally like docs in local
[![xniuBd.md.png](https://s1.ax1x.com/2022/09/29/xniuBd.md.png)](https://imgse.com/i/xniuBd)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 2.11 GB / 7.78 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.50)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-alpha.17 => 1.0.0-alpha.17
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Go to your repository settings and in the pages section, choose deploy from a branch and choose gh-pages branch. Also that folder should be .github/workflows (you're missing an `s`).

**Comment by Hellager** [comment]
> Go to your repository settings and in the pages section, choose deploy from a branch and choose gh-pages branch. Also that folder should be .github/workflows (you're missing an `s`).

Greet thanks for your help, it works now.
