### ISSUE TITLE
打包可能会报错,提示 Error: Missing "./preload-helper" export in "vite" package ,

### ISSUE THREAD

**Issue by gengzhaoji** [vuejs/vitepress#1414]
### Describe the bug

vitepress build docs 打包可能会报错,提示 Error: Missing "./preload-helper" export in "vite" package ,

### Reproduction

vitepress build docs 打包可能会报错,提示 Error: Missing "./preload-helper" export in "vite" package ,

### Expected behavior

打包没有错误

### System Info

```shell
Error: Missing "./preload-helper" export in "vite" package ,
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah but how do we reproduce this? This error does not occur on a basic project. You must have done some customization. Please provide a link to some repo or paste your vite.config.ts and .vitepress/config.ts if overridden. Also, on which VitePress and Node version are you on? You were supposed to fill this in "System Info" section of issue form.

**Comment by fvena** [comment]
https://github.com/liyao1520/vitepress-demo-editor#%E6%89%93%E5%8C%85%E6%8A%A5%E9%94%99
