### ISSUE TITLE
[sidebar] infer collapsible from collapsed and drop the former

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#1418]
can't we only have this property? and if collapsed != undefined we assume the toggle should show?, this way we don't need the collapsible property. 
I know we already have collapsible but collapsed? should cover all options with that logic. 

_Originally posted by @emersonbottero in https://github.com/vuejs/vitepress/pull/1361#discussion_r984184979_
      

---

Just to clarify:

```
collapsed == null -> not collapsible
collapsed === true -> collapsible and collapsed
collapsed === false -> collapsible but expanded
```

This will be a breaking change, but IG it'll a minor one and can be done before more people adopt collapsible sidebar group.

**Comment by kiaking** [comment]
Good point. Yeah that should work 👀 I'm good with this config 👍
