### ISSUE TITLE
Cannot read properties of undefined (reading 'hoistedTags')

### ISSUE THREAD

**Issue by Hollelihanqi** [vuejs/vitepress#1420]
### Describe the bug

hoistedTags undefined appears after install vitepress-theme-demoblock configures the markdown slot

### Reproduction

import DefaultTheme from 'vitepress/theme'
import HqUI from '../../../src/entry'
import 'vitepress-theme-demoblock/theme/styles/index.css'
import { registerComponents } from './register-components'

export default {
    ...DefaultTheme,
    enhanceApp({app}){
        app.use(HqUI)
        registerComponents(app)
    }
}
import Demo from 'vitepress-theme-demoblock/components/Demo.vue'
import DemoBlock from 'vitepress-theme-demoblock/components/DemoBlock.vue'
export function registerComponents(app) {
  app.component('Demo', Demo)
  app.component('DemoBlock', DemoBlock)
}

### Expected behavior

import DefaultTheme from 'vitepress/theme'
import HqUI from '../../../src/entry'
import 'vitepress-theme-demoblock/theme/styles/index.css'
import { registerComponents } from './register-components'

export default {
    ...DefaultTheme,
    enhanceApp({app}){
        app.use(HqUI)
        registerComponents(app)
    }
}
import Demo from 'vitepress-theme-demoblock/components/Demo.vue'
import DemoBlock from 'vitepress-theme-demoblock/components/DemoBlock.vue'
export function registerComponents(app) {
  app.component('Demo', Demo)
  app.component('DemoBlock', DemoBlock)
}

### System Info

```shell
import DefaultTheme from 'vitepress/theme'
import HqUI from '../../../src/entry'
import 'vitepress-theme-demoblock/theme/styles/index.css'
import { registerComponents } from './register-components'

export default {
    ...DefaultTheme,
    enhanceApp({app}){
        app.use(HqUI)
        registerComponents(app)
    }
}
import Demo from 'vitepress-theme-demoblock/components/Demo.vue'
import DemoBlock from 'vitepress-theme-demoblock/components/DemoBlock.vue'
export function registerComponents(app) {
  app.component('Demo', Demo)
  app.component('DemoBlock', DemoBlock)
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Create an issue on their repo: https://github.com/xinlei3166/vitepress-theme-demoblock/issues (Many of such issues exist there, indicating that theme doesn't work with vitepress v1+)
