### ISSUE TITLE
Zip files are not part of the final Build

### ISSUE THREAD

**Issue by aadi58002** [vuejs/vitepress#1421]
### Describe the bug

I have a zip which i want to be downloaded from the blog site when running with the development server. The link works fine and i get a prompt to install the zip.

In production build the zip file is not part of the asserts folder as well as the link becoming "file.zip.html" instead of "file.zip"

### Reproduction

1. Create a md page which links to a zip file ( file.zip)
2. Start the dev server and click on the link which points to the zip file
3. You should get a prompt to install the zip
4. Build the vitepress project with npm build
5. Then start the project with npm serve
6. Click on the zip link again and you will be redirected to the file.zip.html
7. ( even if you remove the .html in the end you can't install the zip as it is not part of the final build ( in the asserts folder))

### Expected behavior

The dev and build should behave the same in case there is a compression format like ( zip, 7z or other ) which are present as links

### System Info

```shell
System:
    OS: Linux 5.19 Arch Linux
    CPU: (16) x64 AMD Ryzen 9 4900HS with Radeon Graphics
    Memory: 11.85 GB / 15.05 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.10.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Brave Browser: 106.1.44.101
```

### Additional context

![Screenshot_20220930_121636](https://user-images.githubusercontent.com/96418027/193207800-fc589a28-d1e7-4e07-bf2a-1f06f4861638.png)
There is no zip in the output ( dist folder in my case)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Put it in public directory and link it using `/foo.zip`.
