### ISSUE TITLE
Dev mode not working

### ISSUE THREAD

**Issue by ST-DDT** [vuejs/vitepress#1422]
### Describe the bug

The dev mode doesn't work/serve a working website.

Firefox v105:

````txt
Uncaught TypeError: import_meta.hot is undefined
    <anonymous> http://localhost:5173/@fs/~/faker/node_modules/.pnpm/vitepress@1.0.0-alpha.17_w6dk4dwpgdxdglls4cxrxtpqg4/node_modules/vitepress/dist/client/theme-default/components/VPSkipLink.vue?v=341ae09c:51
````

Chrome v105:

```txt
Uncaught TypeError: Cannot read properties of undefined (reading 'accept')
    at VPSkipLink.vue:37:3
```

Building and serving (prod) works fine.

### Reproduction

````sh
git clone git@github.com:faker-js/faker.git
pnpm install
pnpm run build
pnpm run docs:dev
# Open Browser
````

### Expected behavior

A working website is shown.

### System Info

```shell
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
    Memory: 53.71 GB / 63.69 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.521.0), Chromium (105.0.1343.53)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-alpha.17 => 1.0.0-alpha.17 
```

### Additional context

Fails with:
- 1.0.0-alpha.17
- 1.0.0-alpha.16
- 1.0.0-alpha.15
- 1.0.0-alpha.10
- No more versions tested

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's fixed. Will be there in the next release.

**Comment by ST-DDT** [comment]
Looks like I missed the other issues in my search. 🤔 
(Well, they don't contain the Firefox error message)

Thanks for your fast response! ❤️
