### ISSUE TITLE
Support cleanURLs for index.html files in public folder

### ISSUE THREAD

**Issue by thepaperpilot** [vuejs/vitepress#1432]
### Is your feature request related to a problem? Please describe.

I want to make a website that contains pre-built websites inside the public folder, so my public folder has let's say a file called `foo/index.html`. I want it to be accessible by going to `mysite.com/foo`, however that brings me to a 404 page. I have to go to `mysite.com/foo/index.html` in order for the page to load.

### Describe the solution you'd like

I have the cleanURLs setting set to with-subfolders, which is supposed to do the above transformation, but it appears to only do so for generated files. I'd like it to also perform the transformation for any index.html files inside the public folder.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to configure your server for that. Most likely accessing `mysite.com/foo/` won't give you errors (even without cleanUrls option).
