### ISSUE TITLE
Outlines Do Not Include h1 Even When Specified

### ISSUE THREAD

**Issue by wspeirs** [vuejs/vitepress#1434]
### Describe the bug

The [docs](https://vitepress.vuejs.org/config/theme-configs#outline) specify that you can pick the levels at which to outline. However, even if you specify h1, it will not generate an outline for that level:

```js
export default {
    themeConfig: {
        outline: [1,3]
    }
}
```

This was already mentioned as needing to be fixed in #954 and claimed to be fixed/added in #965.

### Reproduction

- Set the theme config as shown above to include h1 - h3 in the outline
- Create an MD file with an h1 (or #) heading

### Expected behavior

Should see all headings h1 - h3 in the outline

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (6) x64 AMD FX(tm)-6300 Six-Core Processor
    Memory: 6.91 GB / 31.25 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 105.0.1
```

### Additional context

This _might_ be an error/issue with the [mdit-vue](https://github.com/mdit-vue/mdit-vue) package.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's intentional. We recommend having only one h1 per page. Adding it to outline doesn't make sense if there is only one (at the top).

**Comment by intellijboy** [comment]
> It's intentional. We recommend having only one h1 per page. Adding it to outline doesn't make sense if there is only one (at the top).

This should be up to the user，and I think H1 just a html tag just like H2,H3... , So we don't need to force users to use H1 once in a article.

**Comment by YQisme** [comment]
> It's intentional. We recommend having only one h1 per page. Adding it to outline doesn't make sense if there is only one (at the top).

Everyone has own custom of classing titles,It can't be better to make it an option.
