### ISSUE TITLE
Build fails when filename has special characters

### ISSUE THREAD

**Issue by OlivierArgentieri** [vuejs/vitepress#1439]
### Describe the bug

Here is an example of the issue:

Docs hierarchy is like this:
```
📦docs
 ┣ 📂.vitepress
 ┗ 📂lang
   ┣ 📂C++
   ┃ ┃ ┣ 📜index.html
   ┃ ┃ ┗ 📜links.html
   ┃ ┗ 📜index.html
   ┗ 📜index.md
```

In my .vitepress/config.js :
```js
themeConfig: {
    nav: [
           <MY_NAV>
        ],
  sidebar: [ 
    {
       text: 'LanguageExample',
       collapsible: true,
       items: [
         { text: 'Home', link: '/lang/'},
         { text: 'C++', link: '/lang/C++/'}
       ]
   },
}
````

so the build failed with errors :
>  Error [ERR_MODULE_NOT_FOUND]: Cannot find module <MY_PROJECT_PATH>\docs\.vitepress\.temp\lang_C++_index.md.js imported from <MY_PROJECT_PATH>\node_modules\vitepress\dist\node\serve-c2318085.js
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:437:11)
    at moduleResolve (node:internal/modules/esm/resolve:1009:10)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ESMLoader.import (node:internal/modules/esm/loader:380:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)

### Reproduction

- Named a doc folder with "+" character in his name and put her name/path in custom sidebar links.
- run `yarn docs:build`

### Expected behavior

Successful build when running yarn docs:build

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 10.89 GB / 31.92 GB
Binaries:
    Node: 16.15.0 - E:\Program_Files\Node16\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.6.0 - E:\Program_Files\Node16\npm.CMD
Browsers:
    Edge: Spartan (44.22000.120.0)
    Internet Explorer: 11.0.22000.120
npmPackages:
    vitepress: ^1.0.0-alpha.19 => 1.0.0-alpha.19
```

### Additional context

I don't know if this issue has already been reported, i just found [this](https://github.com/vuejs/vitepress/issues/1039) issue, and maybe the both are related.

And yes, in my case i can just replace "+" characters with a "P" one, but, i think this issue can be interest to be fixed for other case.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's actually unrelated to sidebar and anchors. The root cause is when you've some file having one of these characters in its path (``/[\u0000-\u001F"#$&*+,:;<=>?[\]^`{|}\u007F]/g``), the generated assets name is different (special character is replaced by `_` as a part of sanitization). VitePress is currently unable to handle those edge cases (while guessing the filename that needs to imported).
