### ISSUE TITLE
CleanUrls with with-subfolders/without-subfolders fails lookup from `__VP_HASH_MAP__` upon trailing slash

### ISSUE THREAD

**Issue by pkkummermo** [vuejs/vitepress#1442]
### Describe the bug

When entering a page from outside the main index `/`, the hydration fails when trying to access the chunk in [pathToFile](https://github.com/vuejs/vitepress/blob/main/src/client/app/utils.ts#L42) requesting `/assets/docs_quick-reference_index.md.undefined.lean.js` leading to a  `Hydration completed but contains mismatches.`

The underlying page loads successfully, but any further navigation is broken.

**NOTE**: This only occurs when there's a trailing slash. 

The key being used is `docs_quick-reference_index.md`, but the key should be `docs_quick-reference.md`. 

### Reproduction

Set cleanUrls with `with-subfolders` or `without-subfolders`, add a page further down the content tree, build the project, and access it directly from the browser with a trailing slash.

### Expected behavior

The lookup from `__VP_HASH_MAP__` should be successful and correctly load the lean chunk making the page interactive.

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 16.96 GB / 23.44 GB
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.17 - ~/.npm-global/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
  npmPackages:
    vitepress: ^1.0.0-alpha.19 => 1.0.0-alpha.19
```

### Additional context

Possible solution could be to check for both an `index.md` key as well as a stripped key to cover both use cases.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah, we are aware of this. Ideally we want `with-subfolders` option to generate `/foo/index.html` and serve it properly at `/foo/`. But it's sort of blocked by #285. There might be other ways to fix this, but I believe supporting permalinks is crucial to solving many of similar issues.

**Comment by pkkummermo** [comment]
Let me know if you want a PR based on the proposed solution, and I'll create one :)
