### ISSUE TITLE
yarn docs:dev success but yarn docs:build error！

### ISSUE THREAD

**Issue by JiaZhiheng** [vuejs/vitepress#1443]
build error:
 file:///Users/development/Documents/GitHub/Blog/docs/.vitepress/.temp/app.js:6
import { NCarousel } from "naive-ui";
         ^^^^^^^^^
SyntaxError: Named export 'NCarousel' not found. The requested module 'naive-ui' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'naive-ui';
const { NCarousel } = pkg;

**Comment by JiaZhiheng** [comment]
引入naive-ui第三方组件库后，打包报错

**Comment by brc-dd** [comment]
Duplicate of #1399

**Comment by sky124380729** [comment]
> thank you very much

请问解决了吗，我现在引入还是会报这个错
