### ISSUE TITLE
代码块中的行高亮如果时hosts 会报错。

### ISSUE THREAD

**Issue by jerry-f** [vuejs/vitepress#1454]
### Describe the bug

在markdown 中 如果有代码是这样：

```hosts
127.0.0.1       www.baidu.com
```
去掉该代码则不会。 说明插件中语法高亮不支持该类型，所以报错了。
建议： 1. catch 错误， 然后用一种相近的进行高亮，或者不进行高亮。
则会报错， 报错为： 
 [vite] Internal server error: No language registration for hosts
  Plugin: vitepress

### Reproduction

markdown 文件中有这样的代码（语法高亮代码）

```hosts
127.0.0.1       www.baidu.com
```

### Expected behavior

建议： 1. catch 错误， 然后用一种相近的进行高亮，或者不进行高亮。

### System Info

```shell
[vite] Internal server error: No language registration for hosts
  Plugin: vitepress
```

### Additional context

![image](https://user-images.githubusercontent.com/30689170/194823622-7f8a3bcc-a5a2-494b-96bf-0d729c3db4e5.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Zhengqbbb** [comment]
> No language registration for hosts
> Shiki no support `hosts` lang. Need to customize

从报错信息来看，是 shiki 不支持 `hosts` 语法. 可以参照 https://vitepress.vuejs.org/config/app-configs#markdown | https://github.com/shikijs/shiki/blob/main/docs/languages.md 自定义语法以及高亮

**Comment by jerry-f** [comment]
没有高亮，可以选择静默高亮设置，但是直接就报错的话就太暴力了。
用户正常使用，语法也是对的。不支持该高亮行为可以选择静默高亮行为就好了。 不应该报错~~。 也不认为应该让用户必须更改其高亮的语法（比如将hosts -> bash）

**Comment by jerry-f** [comment]
> > No language registration for hosts
> > Shiki no support `hosts` lang. Need to customize
> 
> 从报错信息来看，shiki 不支持 `hosts` 语法导致报错. 可参照 https://vitepress.vuejs.org/config/app-configs#markdown | https://github.com/shikijs/shiki/blob/main/docs/languages.md 自定义语法以及高亮 从 vscode 实验高亮选择来看，hosts record 是没有高亮的

没有高亮，可以选择静默高亮设置，但是直接就报错的话就太暴力了。
用户正常使用，语法也是对的。不支持该高亮行为可以选择静默高亮行为就好了。 不应该报错~~。 也不认为应该让用户必须更改其高亮的语法（比如将hosts -> bash）
