### ISSUE TITLE
Old vuepress service worker cached

### ISSUE THREAD

**Issue by adrianthedev** [vuejs/vitepress#1469]
### Describe the bug

Hi👋

Amazing work with vitepress! Thanks for that!

I have a small issue with my docs site.
I used to have a vuepress app running my old docs and switched to vitepress. Some users are still seeing the same old site (vuepress) when they navigate to a URL instead of the new one (vitepress).

My question is: **How can I bust the client cache from the server?**

The website is https://docs.avohq.io/ and it's hosted on netlify.

Thank you,

### Reproduction

I can't offer a reproduction unless you've previously visited the old site.

### Expected behavior

The new site (vitepress) should be visible, not the old one (vuepress).

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) x64 Apple M1 Max
    Memory: 40.16 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 104.0
    Safari: 16.0
    Safari Technology Preview: 16.0
  npmPackages:
    vitepress: ^1.0.0-alpha.19 => 1.0.0-alpha.19
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
[Extend the default theme](https://vitepress.vuejs.org/guide/theme-introduction#extending-the-default-theme) and add something like this:

```ts
import DefaultTheme from 'vitepress/theme'
import { inBrowser } from 'vitepress'

export default {
  ...DefaultTheme,
  setup: () => {
    if (inBrowser) {
      navigator.serviceWorker.getRegistrations().then((registrations) => {
        for (let registration of registrations) registration.unregister()
      })
    }
  }
}
```

**Comment by adrianthedev** [comment]
Any ideas on how this can be achieved? I'm sure I'm not the only one doing this upgrade path (vuepress->vitepress) and running into issues.

**Comment by kiaking** [comment]
That depends on what hosting service you're using so hard to tell 😅 I think posting this in discussion or at Discord is better to get help 👍

**Comment by adrianthedev** [comment]
Well, why close it @kiaking? 
It's actually an issue I encountered with this upgrade. More people will have the same problem.

> That depends on what hosting service you're using so hard to tell
The hosting provider is Netlify, but I'd love to get a solution for **any** provider.

> I think posting this in discussion or at Discord is better to get help.
What Discord server do you have in mind? 
Would posting in discussions would make a difference?

**Comment by kiaking** [comment]
@adrianthedev Issues are for actual issues (bug reports) or feature requests. When you say "Some users are still seeing the same old site..." this is not a VitePress problem. VitePress has nothing to do with your old site. So it sounds very much like your hosting service settings issue.

For those questions would be better handled in Discord or in Discussions. You can join Vue.js Official Discord here (which has VitePress channel).
https://discord.com/invite/HBherRA

**Comment by brc-dd** [comment]
> What Discord server do you have in mind?

https://chat.vuejs.org/

This likely should not have happened as browsers automatically update the service worker if not fetched in last 24 hours. Can't say for sure, I really don't have much experience in this field. But there are people on Discord who have good experience with stuff like this. Also, this discussion is not exactly relevant (limited) to VitePress. Some script that deregisters all service workers would've worked. This was more of a StackOverflow question.

**Comment by adrianthedev** [comment]
> this is not a VitePress problem. 

I know it's not a VitePress problem. 

> VitePress has nothing to do with your old site.

The old site is VuePress. It's just something that people will run into in the upgrade path from vuepress to vitepress.

Thanks for your time.

**Comment by BasilaryGroup** [comment]
Sorry for adding to a close issue. 

I was able to track down the Discord discussion related to this problem and I thought it would help others who face the same problem.

* see [discord](https://discord.com/channels/325477692906536972/790509637598314527/1032614068164493402
)

You have an existing VuePress site deployed on a host like netlify, gitlab pages, github, etc. You deploy your new VitePress site and the old site keeps displaying.

0. assumes you have defined a `base: /yourbaseurl/` in  `docs/.vitepress/config.js`
1. copy your old `manifest.json` into `docs/public/manifest.json`
2. in `docs/.vitepress/config.js` add a `header: []` section containing

```txt
    head: [
        ['link', { rel: 'manifest', href: '/manifest.json' }],
        ['script', { id: "unregister-sw" },
            "if('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('/fracbrainops/service-worker.js', { scope: '/yourbaseurl/' }))",
        ]
    ]
```

3. add `docs/public/service-worker.js` with the following,

```js
// force an unregister
// see https://discord.com/channels/325477692906536972/790509637598314527/1032614068164493402
self.addEventListener('install', function (e) {
    self.skipWaiting();
});
self.addEventListener('activate', function (e) {
    self.registration.unregister()
        .then(function () {
            return self.clients.matchAll();
        })
        .then(function (clients) {
            clients.forEach(client => client.navigate(client.url))
        });
});
```

4. build and deploy
5. when you display the new VitePress site, the old service worker will start and then unregister itself.

The one downside I see is each time the service worker is run you get another Application entry. Maybe later you remove this assuming all of your users have unregistered the old VuePress site?
