### ISSUE TITLE
chrome failed to load the docs website

### ISSUE THREAD

**Issue by yxw007** [vuejs/vitepress#1476]
### Describe the bug

Chrome failed to load the dev docs website

### Reproduction

1. git clone https://github.com/Tyh2001/vitepress-template
2. pnpm i
3. pnpm dev

Errors found, following screenshots

![image](https://user-images.githubusercontent.com/9338717/195524190-950c8b14-8762-442a-9445-ac7907dfb087.png)

### Expected behavior

Display the website properly

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 18.85 GB / 31.93 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD       
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-alpha.20 => 1.0.0-alpha.20
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
One of your extensions (likely some ad blocker) is blocking the resources. Try disabling them.

**Comment by yxw007** [comment]
> One of your extensions (likely some ad blocker) is blocking the resources. Try disabling them.

thanks，How did you find out?

**Comment by brc-dd** [comment]
> How did you find out?

Looking at the very first error 👀
