### ISSUE TITLE
embed video in markdown with vitepress

### ISSUE THREAD

**Issue by arcqiufeng** [vuejs/vitepress#1477]
### Is your feature request related to a problem? Please describe.

I've embed a video in my markdown by search the help of Typora.
It works fine in Typora.
It is like this in my markdown:
```
<video controls="controls" src="在家办公指南.assets\Video_2020-02-23_230241.mp4" />
```
It works fine with the localhost via the command ` yarn docs:dev`
but when `yarn docs:build`, I got an error.
How can I do?

### Describe the solution you'd like

Support the video control.

I set up the site in LAN and won't expose to the WAN, the storage is no problem.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What was the error? It should've worked.

**Comment by arcqiufeng** [comment]
> 

```
yarn docs:build
yarn run v1.22.19
$ vitepress build docs
vitepress v1.0.0-alpha.20
⠋ building client + server bundles...[vite]: Rollup failed to resolve import "20.在家办公指南.assets/Video_2020-02-23_230241.mp4" from "docs/guide/010.文件服务器/20.在家办公指南.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
✖ building client + server bundles...
build error:
 Error: [vite]: Rollup failed to resolve import "20.在家办公指南.assets/Video_2020-02-23_230241.mp4" from "docs/guide/010.文件服务器/20.在家办公指南.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
....

```
sorry I cannot understand the message....and have no mind to do

**Comment by brc-dd** [comment]
Can you try using relative path to your video file like this:

```
../在家办公指南.assets/Video_2020-02-23_230241.mp4
```

Or maybe try storing that video file in `docs/public` directory and linking using:

```
/Video_2020-02-23_230241.mp4
```

**Comment by arcqiufeng** [comment]
Thank you for reply me, I will try the `./` later. 
However, I don't want to place the video to public dir because I hope the attachment of the markdown will be in the same place.

**Comment by arcqiufeng** [comment]
> Can you try using relative path to your video file like this:
> 
> ```
> ../在家办公指南.assets/Video_2020-02-23_230241.mp4
> ```

Now it's work fine with this:
```
./在家办公指南.assets/Video_2020-02-23_230241.mp4
```

Thank you for your help.
