### ISSUE TITLE
vue3+vite 页面引入子组件后热更新失效，去掉该子组件后页面热更新正常

### ISSUE THREAD

**Issue by 1131476232** [vuejs/vitepress#1481]
### Describe the bug

例如：引入import AceEditor from '@/components/aceEditor/index.vue'这个组件页面热更新失效，去掉则正常
![688afdbd51a43e603064b7bef1916a7](https://user-images.githubusercontent.com/22586008/195757740-60e959ab-b238-4f0f-b915-f5a5897d1e64.png)

### Reproduction

略

### Expected behavior

期待引入子组件后页面热更新也正常

### System Info

```shell
略
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Zhengqbbb** [comment]
...  所以是什么问题

**Comment by brc-dd** [comment]
What's the error you're getting? Also share a minimal reproduction and system details (especially your vitepress version).
