### ISSUE TITLE
Adding container without any global styling inside vp-docs

### ISSUE THREAD

**Issue by Exotelis** [vuejs/vitepress#1482]
### Is your feature request related to a problem? Please describe.

I'd like to showcase components of a component library with vitepress. I put all of those components in a `<div class="preview">*</div>`  container. The problem is that the `vp-doc` styling is affecting and breaking a lot of those components as you can see here:

![vitepress01](https://user-images.githubusercontent.com/7863239/195786923-f0fd1d69-42d0-46be-901f-4faa704fc849.png)

However, I can fix this by wrapping the default layout and replacing the `vp-doc` class by a custom one and by re-applying all the styles I need in a `custom.css` file. I'm aware that I also could use `layout: page`, but I really like how much love you put in the default theme and would like to continue using it.

### Describe the solution you'd like

If there is no simple way of ignoring the `vp-doc.css` I'd suggest updating the css selector slightly. For exmaple, convert `.vp-doc h1 {` to `.vp-doc :not(.preview) > h1 {`. This would obviously not apply the styling of this selector inside the preview container. 

I'd like to hear your ideas about that :-)

### Describe alternatives you've considered

Please see the `Is your feature request related to a problem?` section. If this feature is not useful for others, I'm fine with my workaround :-)

### Additional context

I'm happy to file a pr if you would like to add this 'feature'.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.vuejs.org/guide/markdown#raw
