### ISSUE TITLE
Vitepress docs are 404

### ISSUE THREAD

**Issue by PeterPetrik** [vuejs/vitepress#1483]
### Describe the bug

open https://vitepress.vuejs.org - > it shows 404

![Screenshot 2022-10-14 at 12 32 53](https://user-images.githubusercontent.com/804608/195826781-b3d08320-7cd2-4424-ab9c-ba313944edc2.png)

### Reproduction

open https://vitepress.vuejs.org - > it shows 404

### Expected behavior

it shows docs

### System Info

```shell
browser - any
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Should be fixed now.
