### ISSUE TITLE
lastUpdated无效

### ISSUE THREAD

**Issue by TaoChen321** [vuejs/vitepress#1495]
### Describe the bug

lastUpdated:true 不起作用

### Reproduction

lastUpdated:true 不起作用

### Expected behavior

lastUpdated:true 不起作用

### System Info

```shell
时间那一行空白
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please create a new issue with proper details (reproduction and your system details).

**Comment by brc-dd** [comment]
Also, `lastUpdated` is git based and it will work only if the file is committed.
