### ISSUE TITLE
allow using symlinks with pages

### ISSUE THREAD

**Issue by jerry-f** [vuejs/vitepress#1496]
### Describe the bug

访问一个软连接内的目录， 会导致页面显示404。
点击时有两个返回， 一个返回是正常的文件。 但是contetn-type: text/markdown
另一个是 hashmap.json 404

### Reproduction

软连接目录文件（windows）;软链接使用的是：

mklink /j "D:\pro\doc\my-docs\docs\xx "D:\pro\xxx\xx"

生成的目录

### Expected behavior

能够正常的返回并显示

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 3.55 GB / 15.86 GB
  Binaries:
    Node: 16.17.1 - D:\dev\nodejs\node.EXE
    Yarn: 1.22.19 - D:\dev\nodejs\yarn.CMD
    npm: 8.15.0 - D:\dev\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1566
```

### Additional context

![image](https://user-images.githubusercontent.com/30689170/196105769-b288a073-4f3e-43ce-8fca-95b308c099bb.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jerry-f** [comment]
应该是返回的格式的问题。 Content-Type: text/markdown  返回的结果也是一个正常的markdown 格式的文件， 正常情况返回的应该是一个 Content-Type: application/javascript

看了一下源码， src/client/app/index.ts 中  `123 行 import(/*@vite-ignore*/ pageFilePath)  内触发的错误`， 具体就没有深入了

**Comment by brc-dd** [comment]
Try creating a `vite.config.js` file inside your `docs` directory having this:

```js
export default {
  resolve: {
    preserveSymlinks: true
  }
}
```
