### ISSUE TITLE
Add banner slot

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#1497]
similar to @vue/theme (and adjust styles to respect `--vp-banner-height`)

**Comment by ylw5** [comment]
In @vue/theme, you should set style for banner like this
[Banner.vue in vuejs/docs](https://github.com/vuejs/docs/blob/3b928f7630eb8039cc316dc8604513bd43cf810c/.vitepress/theme/components/Banner.vue)
```
<style>
html:not(.banner-dismissed) {
  --vt-banner-height: 60px;
}
</style>
<style scoped>
.banner {
  position: fixed;
  z-index: var(--vp-z-index-banner);
  box-sizing: border-box;
  top: 0;
  left: 0;
  right: 0;
  height: var(--vt-banner-height);
}
```
 it's a little hard and inflexible for developer, if there is a better way to set banner that developer only focus banner's content

**Comment by kiaking** [comment]
Hmmm... How about we change VPNav to have `position: sticky` and then just insert banner on top of `nav`. And I think it would adjust the height automatically?

```html
<div>
  <Banner />
  <div class="main">
    <VPNav />
  </div>
</div>
```

**Comment by kiaking** [comment]
No wait, forget about it, it wouldn't work... 😅
