### ISSUE TITLE
Favicon not found in serve when base is set

### ISSUE THREAD

**Issue by emersonbottero** [vuejs/vitepress#1500]
### Describe the bug

Favicon not found in serve when base is set

### Reproduction

add a favicon and set base

### Expected behavior

favicon should be found and used

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 7.13 GB / 15.92 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Spartan (44.22621.746.0), Chromium (106.0.1370.47)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.19 => 1.0.0-alpha.19
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
How are you adding the favicon?

**Comment by YoavDn** [comment]
Is there a way to add favicon?

**Comment by emersonbottero** [comment]
I just place it in the public folder.
is there a different way? it works in dev, not in serve

**Comment by brc-dd** [comment]
> Is there a way to add favicon?

Yeah. If your favicon file is named `favicon.ico`, you can simply put it in your public directory and the browsers will pick that up. This won't work when base is set because browsers look for `/favicon.ico` but your file will be present at `/base/favicon.ico`. You need to manually specify the link tag in this case:

```ts
// .vitepress/config.ts

export default {
  head: [
    ['link', { rel: 'icon', type: 'image/x-icon', href: '/base/favicon.ico' }],
  ]
}
```

You can use this way to specify files other than favicon.ico as favicon too.

**Comment by emersonbottero** [comment]
Oh. Maybe add to the docs..
Is a commom use l guess

**Comment by emersonbottero** [comment]
Even Better the build process take care of adding the link when the file Is found in the public folder 😆

**Comment by emersonbottero** [comment]
> Even Better the build process take care of adding the link when the file Is found in the public folder 😆

@brc-dd cant this be a feature? If the favicon.ico exists in public folder then add header with base in the build workflows!

**Comment by kiaking** [comment]
I'm against that. When serving the site from the sub directly, the user might want to serve the favicon from the parent directory. We don't know, but this is a very basic feature of how a website works and is not specific to VitePress.

The same goes for `robots.txt` and `sitemap.xml` and so on. Not only a favicon. I think mention it in the doc and it would be fine 👍
