### ISSUE TITLE
Cannot render html table

### ISSUE THREAD

**Issue by arcqiufeng** [vuejs/vitepress#1502]
### Describe the bug

We get the markdown file like this, and get the follow message:
```
[plugin:vite:vue] Whitespace was expected.
```

The markdown file can be displayed correctly in `Typora` and `MPE plugin for vscode`

The markdown file is:
```
# test Coming soon...

<table><colgroup><col><col><col><col><col><col><col></colgroup><tbody><tr><td rowspan="2"colspan="3"><br></td><td colspan="2">垂直通车道方向的最小停车位宽度（m）</td><td rowspan="2">平行通车道方向的最小停车位宽度Lt（m）</td><td rowspan="2">通（停）车道最小宽度Wd（m）</td></tr><tr><td>We1</td><td>We2</td></tr><tr><td colspan="2">平行式</td><td>后退停车</td><td>2.4</td><td>2.1</td><td>6.0</td><td>3.8</td></tr><tr><td rowspan="4">斜<br>列<br>式</td><td>30</td><td>前进（后退）停车</td><td>4.8</td><td>3.6</td><td>4.8</td><td>3.8</td></tr><tr><td>45</td><td>前进（后退）停车</td><td>5.5</td><td>4.6</td><td>3.4</td><td>3.8</td></tr><tr><td>60</td><td>前进停车</td><td>5.8</td><td>5.0</td><td>2.8</td><td>4.5</td></tr><tr><td>60</td><td>后退停车</td><td>5.8</td><td>5.0</td><td>2.8</td><td>4.2</td></tr><tr><td rowspan="2" colspan="2">垂直式</td><td>前进停车</td><td>5.3</td><td>5.1</td><td>2.4</td><td>9.0</td></tr><tr><td>后退停车</td><td>5.3</td><td>5.1</td><td>2.4</td><td>5.5</td></tr></tbody></table>
```

### Reproduction

place the markdown and try it can reproduction the error.

### Expected behavior

Render correctly.

### System Info

```shell
Windows 11, 1.0Alpha.20
```

### Additional context

None

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Your HTML is invalid. There is no space between attributes: `rowspan="2"colspan="3"`

**Comment by arcqiufeng** [comment]
That fixed. Thank u.
