### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by DonXander** [vuejs/vitepress#1506]
### Describe the bug

![image](https://user-images.githubusercontent.com/25742814/196668710-24eb0696-1c87-4070-9bc6-ec1c9bec1965.png)

vitepress v1.0.0-alpha.20
failed to start server. error:
 TypeError: dns.setDefaultResultOrder is not a function
    at createServer (file:///D:/project/web/fighting-design/docs/node_modules/vitepress/dist/node/serve-585d953a.js:36077:7)
    at async createDevServer (file:///D:/project/web/fighting-design/docs/node_modules/vitepress/dist/node/cli.js:285:20)

### Reproduction

执行pnpm dev:docs

### Expected behavior

正常启动server

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
    Memory: 3.04 GB / 15.81 GB
  Binaries:
    Node: 16.3.0 - D:\nodejs\node.EXE
    npm: 7.15.1 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.22000.120
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you try updating your Node.js to latest LTS?

**Comment by DonXander** [comment]
> Can you try updating your Node.js to latest LTS (v16.18.x)?

Updating works。Thanks，and my node.js to 19.0.0

**Comment by liuliangsir** [comment]
@brc-dd why not add suitable node version to package.json like engines option?
