### ISSUE TITLE
dev server fails with: Cannot set properties of undefined (setting 'id')

### ISSUE THREAD

**Issue by lukashroch** [vuejs/vitepress#1507]
Pnpm monorepo setup with:
- top-level vitepress docs
- some vue apps withih `apps/`

When you run vitepress dev server (`pnpm docs:dev`) and try to open the docs site. it fails with following error

```
12:07:21 [vite] Internal server error: Cannot set properties of undefined (setting 'id')
  Plugin: vite:vue
  File: C:/Apps/wp-test/node_modules/.pnpm/vitepress@1.0.0-alpha.21/node_modules/vitepress/dist/client/theme-default/components/VPTeamMembers.vue
      at createDescriptor (file:///C:/Apps/wp-test/node_modules/.pnpm/@vitejs+plugin-vue@3.1.2_vite@3.1.8+vue@3.2.41/node_modules/@vitejs/plugin-vue/dist/index.mjs:67:17)
      at transformMain (file:///C:/Apps/wp-test/node_modules/.pnpm/@vitejs+plugin-vue@3.1.2_vite@3.1.8+vue@3.2.41/node_modules/@vitejs/plugin-vue/dist/index.mjs:2158:34)
      at TransformContext.transform (file:///C:/Apps/wp-test/node_modules/.pnpm/@vitejs+plugin-vue@3.1.2_vite@3.1.8+vue@3.2.41/node_modules/@vitejs/plugin-vue/dist/index.mjs:2646:16)
      at Object.transform (file:///C:/Apps/wp-test/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:41111:44)
      at async loadAndTransform (file:///C:/Apps/wp-test/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:37373:29)
```

### Reproduction

Repo link to reproduce: https://github.com/lukashroch/vitepress-test

```
git clone https://github.com/lukashroch/vitepress-test
pnpm install
pnpm docs:dev
```

open the browser with the docs URL to receive the error

### Expected behavior

vitepress docs server should not fail

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.3.15
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Spartan (44.22621.674.0), Chromium (106.0.1370.47)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-alpha.21 => 1.0.0-alpha.21
```

**Comment by brc-dd** [comment]
It looks like you've installed vue@2.7 at workspace root. VitePress is not compatible with that. You can do something like this instead: https://github.com/brc-dd/vitepress-monorepo-isolation

**Comment by lukashroch** [comment]
Vue2 is in apps subfolder, not the ws root. It's a bit strange, this was actually working with pnpm@6.

**Comment by brc-dd** [comment]
Ah, ok. Sorry I misread that. Can you try installing vue@3 at root?

**Comment by lukashroch** [comment]
That's what I was just thinking about seeing your repo example. I'll try that now!

**Comment by lukashroch** [comment]
It's working if you explicitly put vue@3 as dep.

Though everything else is working, like `docs:build` without explicitly setting vue@3

**Comment by yyx990803** [comment]
This has to do with `pnpm run` trying to emulate `npm run` compatibility by implicitily adding `NODE_PATH` env variables and end up causing `@vitejs/plugin-vue` to resolve the wrong version of `vue`...

Should be fixed by https://github.com/vitejs/vite-plugin-vue/commit/cf36b3e42a16295bac5cef6c21ef1b6683a429ef (pending 4.1 release)
