### ISSUE TITLE
🧐Can monaco-editor be used in vitepress?

### ISSUE THREAD

**Issue by kevinsheep** [vuejs/vitepress#1508]
I customized my Layout, put a component in slot #doc-after and import the monaco-editor to realize some commentary functions.
It works fine in develop mode.
But when building it...

```bash
$ yarn docs:build
vitepress v1.0.0-alpha.21
✓ building client + server bundles...
(node:22790) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
build error:
 /home/kevinsheep/Documents/Codebase/blog-gitee/node_modules/monaco-editor/esm/vs/editor/editor.main.js:1
import '../basic-languages/monaco.contribution';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
```

I noticed these issuses about esbuild and monaco-editor: 
[https://github.com/evanw/esbuild/issues/723](https://github.com/evanw/esbuild/issues/723)
[https://github.com/vitejs/vite/discussions/1791](https://github.com/vitejs/vite/discussions/1791)
The issue seems to have been solved in esbuild?

And then I also tried the sample in my project. It can be built sucessfully.
[https://github.com/microsoft/monaco-editor/blob/main/samples/browser-esm-esbuild/build.js](https://github.com/microsoft/monaco-editor/blob/main/samples/browser-esm-esbuild/build.js)

```javascript
// ~/monaco-editor/index.js'
import * as monaco from 'monaco-editor/esm/vs/editor/editor.main.js';
self.MonacoEnvironment = { getWorkerUrl: './vs/editor/editor.worker.js' };

export const createEditor = (dom) =>
    monaco.editor.create(dom, {
        language: 'markdown',
        lineNumbers: 'off',
        wordWrap: 'on',
        scrollbar: { verticalScrollbarSize: 10 },
        minimap: {
            enabled: false,
        },
    });
```

```javascript
<script setup>
// component.vue
import { ref, onMounted } from 'vue';
import { createEditor } from '../../monaco-editor/index.js';
//...
onMounted(() => {
    const editor = createEditor(document.querySelector('#container'));
});
</script>
```

So, what can i do to solve the problem when I run `yarn docs:build` ?

**Comment by brc-dd** [comment]
Hi, can you share a repo where dev was working? It'll be helpful to quicky debug stuff.

**Comment by kevinsheep** [comment]
> Hi, can you share a repo where dev is working? It'll be helpful to quicky debug stuff.

Tks.

repo is here: [https://gitee.com/kevinsheep/blog/tree/master/](https://gitee.com/kevinsheep/blog/tree/master/)
And I created an editor instance [here](https://gitee.com/kevinsheep/blog/blob/master/docs/.vitepress/components/Editor.vue#L179)
After running `docs:dev`, the editor works fine in docs page.

**Comment by brc-dd** [comment]
So, I really tried debugging it for some time and using vite plugins / vue components. But nothing worked. I'm keeping this open for now, somebody else might be able to help with this. And BTW if you just want a editor component for comments, I'd recommend something simpler like https://vueup.github.io/vue-quill/.

**Comment by kevinsheep** [comment]
> So, I really tried debugging it for some time and using vite plugins / vue components. But nothing worked. I'm keeping this open for now, somebody else might be able to help with this. And BTW if you just want a editor component for comments, I'd recommend something simpler like https://vueup.github.io/vue-quill/.

Looking forward to better solution in vitepress.
vue-quill is an exellent editor of course. And i'd tried it and its plugins for mardown.
But it doesn't meet my requirement anyway.
I'm looking for / customizing an editor supporting markdown, and it can export pure markdown content when saved. Just like this editor we using in github.

**Comment by sky124380729** [comment]
I have the same problem with monaco-editor, when `yarn docs:dev` is ok, but `yarn docs:build` does't work,
```
build error:
 E:\vueProjects\levi-notebook\node_modules\.pnpm\registry.npmmirror.com+monaco-editor@0.34.1\node_modules\monaco-editor\esm\vs\editor\editor.main.js:1
import '../basic-languages/monaco.contribution';
^^^^^^
```
I hope this problem will be resolved soon, it's really usefull for me

**Comment by kevinsheep** [comment]
@sky124380729 Inspired by @brc-dd 's answer, I replaced monaco-editor with [vditor](https://github.com/Vanessa219/vditor), everything goes well now.
But if you have to use monaco-editor, just look forward to this discussion [https://github.com/vitejs/vite/discussions/1791](https://github.com/vitejs/vite/discussions/1791)

**Comment by XiaoYang943** [comment]
I can use monaco-editor，but I can not use `axios` or `fetch` get local HTML files content。The request was intercepted by devserver，how can i do this ？ 

help，thanks

**Comment by brc-dd** [comment]
> The request was intercepted by devserver，how can i do this ？

You can import the file as raw if it's static or maybe use build time data loading. Refer discussion on #2636.

**Comment by brc-dd** [comment]
For anyone else coming to this thread, refer https://github.com/vuejs/vitepress/issues/2832. It has a working solution: https://stackblitz.com/edit/github-ud4nff?file=index.md,.vitepress/config.mts
