### ISSUE TITLE
Can I use nodejs to call Vitepress's API?

### ISSUE THREAD

**Issue by yangmiao7** [vuejs/vitepress#1509]
### Is your feature request related to a problem? Please describe.

Can I use nodejs to call Vitepress's API?Or will there be such a change in the future？

Because I want to encapsulate VitePress to make it easier to generate some functionally similar documents in different projects, rather than duplicating VitePress configuration in different projects.

### Describe the solution you'd like

Use an API like this in nodejs:

```
vuepress.dev({
// some config or specify the configuration file location
})

vuepress.build({
// some config or specify the configuration file location
})
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by yangmiao7** [comment]
What I want to do is like vue-cli wrapping webpack.

**Comment by brc-dd** [comment]
Most of the stuff is exported, so yes, you should be able to use VitePress programmatically.

Refer https://github.com/vuejs/vitepress/blob/main/src/node/cli.ts for usage (replace `.` in imports with `vitepress` and remove that version thing or try importing `vitepress/package.json` directly). It should work.

**Comment by yangmiao7** [comment]
First of all thanks for your reply.

I did read part of the source code,But haven't tried coding my program yet.

My consideration is that these APIs are not officially exposed (or written in the document), and future updates of Vitepress may cause these methods to not be used correctly, and it will be difficult for my program to use the latest and better Vitepress.

**Comment by brc-dd** [comment]
If you look at the history of that cli file, there haven't been much change in those three functions API-wise. Unless there is some big stuff, it will likely remain the same. But obviously we can't guarantee that they won't change between releases.

> will there be an official node-api for users in the future?

Can't say for sure. The best bet at the moment is you'll need to check that file for changes from time to time.

**Comment by yangmiao7** [comment]
>
Sorry for my poor English, I didn't understand the content in brackets, do you suggest me to use the source code, or the dist product? I'm going to write my code in TypeScript, can I use Vitepress production package to export methods and types?

**Comment by brc-dd** [comment]
Yeah, you can import those functions from the our published package. Most likely TypeScript won't complain.

**Comment by yangmiao7** [comment]
> Yeah, you can import those functions from the our published package. Most likely TypeScript won't complain.

ok i'll try. Thank you very much.
