### ISSUE TITLE
vitepress可以支持vue2.7

### ISSUE THREAD

**Issue by aslrz-club** [vuejs/vitepress#1514]
### Is your feature request related to a problem? Please describe.

无

### Describe the solution you'd like

新的vue组件库是基于vue2.7写的，使用vitepress搭过自己的博客觉得很舒服，希望vitepress支持下vue2.7版本，这样整个生态就比较舒服

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Thank you for the feedback! I understand your feelings but I don't think we're going to support Vue 2.7. you could always create separate repo for docs and use VitePress there so I think the complexity added by supporting 2.7 is not worth it 😓
