### ISSUE TITLE
Support `editLink` per page

### ISSUE THREAD

**Issue by posva** [vuejs/vitepress#1516]
### Is your feature request related to a problem? Please describe.

This was an existing feature:

- https://github.com/vuejs/vitepress/issues/334

It was really useful for generated doc pages like APIs that shouldn't be modified manually

### Describe the solution you'd like

- See https://github.com/vuejs/vitepress/issues/334

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We still have that:

https://github.com/vuejs/vitepress/blob/d5ef380e59aa653fedb655d5538c9ead597ded21/src/client/theme-default/components/VPDocFooter.vue#L16-L18

Is it not working?

**Comment by posva** [comment]
I had an `s` in `editLink` 🥲
