### ISSUE TITLE
Support the sidebar to display three-level titles in the article

### ISSUE THREAD

**Issue by codehzy** [vuejs/vitepress#1520]
### Is your feature request related to a problem? Please describe.

Support the sidebar to display three-level titles in the article

### Describe the solution you'd like

I usually need to write a third-level title in an article, but Vitepress can't help me display the third-level title in the right navigation bar, which annoys me

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi, it's already supported: https://vitepress.vuejs.org/config/theme-configs#outline

**Comment by codehzy** [comment]
Sorry, I may have misdescribed my problem. What I need is Markdown to support the display of three-level titles. markdown navigation is show in right rather than left sidebar

**Comment by brc-dd** [comment]
Yeah, set themeConfig.outline to `[2, 3]` in your .vitepress/config.js. It should work.

**Comment by codehzy** [comment]
Cool. It shoul work now.
