### ISSUE TITLE
About article lastUpdated

### ISSUE THREAD

**Issue by codehzy** [vuejs/vitepress#1522]
### Is your feature request related to a problem? Please describe.

The last update time of the file is the file I modified one time, not the last update time of all files becomes the last commit time

### Describe the solution you'd like

I through vitepress docs,https://vitepress.vuejs.org/guide/deploying#github-pages.And create deploy.yml inside .github/workflows . Even if I change a certain file, at this time commit and push, the workflow work is completed. At this time, the last update time of all articles on my page is changed to this commit time. I hope that only the specific files I submit this time will be updated. The latest modification time

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> I hope that only the specific files I submit this time will be updated. The latest modification time

Yeah that should be happening. Like in VitePress' docs, https://vitepress.vuejs.org/guide/deploying has `Last updated: 8/23/2022` while https://vitepress.vuejs.org/guide/markdown has `Last updated: 10/21/2022` as the markdown.md file was updated in a commit today, while that deploying.md hasn't been updated in any commits of the last two months. Is something else happening for you? Can you provide a reproduction?

**Comment by codehzy** [comment]
https://github.com/codehzy/blog/blob/master/.github/workflows/release.yml . This is my blog action yml,Can you give me some advice

**Comment by brc-dd** [comment]
Can you try replacing first step by this:

```yml
- uses: actions/checkout@v3
  with:
    fetch-depth: 0
```

**Comment by codehzy** [comment]
Cool. You are my savior and I change my files as you say.The redeployment met my expectations.


name: release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BLOG_TOKEN }}
          publish_dir: docs/.vitepress/dist
