### ISSUE TITLE
Use web fonts on web containers

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#1523]
Context: Currently we emit a bunch of font files to dist while building. This causes error in StackBlitz if the user doesn't have subscription.

Solution: Add an option to use Inter from Google Fonts. And enable it by default on webcontainers. Env can be checked [like this](https://github.com/vitest-dev/vitest/pull/763/files#diff-c381e6de43a918512ead544ce9b936666a7066fdfddd83c19221b433a01e4ee4R67).

**Comment by rijkvanzanten** [comment]
@brc-dd We're now pinging Google's servers with the user's IP address as fonts are loaded client side. If I'm not mistaken, there were some privacy concerns with that, especially around GDPR in the European markets 🤔 https://www.theregister.com/2022/01/31/website_fine_google_fonts_gdpr/

**Comment by brc-dd** [comment]
Just to clarify: we don't use Google Fonts by default. They are only used inside webcontainers (on StackBlitz) or if the user has explicitly set that option. I think you shouldn't set that on production?

**Comment by rijkvanzanten** [comment]
Ahhh gotcha! My bad, didn't catch the bundler plugin that strips it out based on the comments 🙂
