### ISSUE TITLE
Support for Other Types of Renderer

### ISSUE THREAD

**Issue by RPDeshaies** [vuejs/vitepress#1532]
### Is your feature request related to a problem? Please describe.

While Vue is a fantastic rendering engine, some people are more used to working with others. Or sometimes, companies decide on a specific engine for the whole company, and having one project that doesn't use it can be seen as a showstoper for using a piece of technology.

### Describe the solution you'd like

Considering the name of this project is called Vitepress, I think it might be interesting to support other types of renderer (e.g. React) via official plugins like [Vite does](https://vitejs.dev/plugins/#vitejs-plugin-react).

That way, people could use the incredible features and toolset provided by Vitepress with the rendering technology of their choice. A little bit like [Astro](https://astro.build/) is going with their framework.

I do understand that Vitepress is Vuepress's spiritual successor, but I have the impression that this could benefit a lot more people considering how powerful and useful Vitepress is. Even more so considering altneratives like Docusaurus are built on older and slower sets of technologies.

### Describe alternatives you've considered

I've seen on a twitter thread that it was possible to render react components somehow, though I'm not sure I've seen this documented anywhere.

### Additional context

n/a

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
This could be cool, especially if we gonna name this VitePress. But, it's going to be really hard to do this since 100% of client code is written in Vue.

If we were to change the underlying framework, we need to re-write everything in that language. So, it would be easier if we create things like `vitepress-react` or `vitepress-svelte` as totally separate package.
