### ISSUE TITLE
Allow to pass additional languages to shiki

### ISSUE THREAD

**Issue by norskeld** [vuejs/vitepress#1533]
### Is your feature request related to a problem? Please describe.

It would be great to be able to pass additional languages/syntaxes to shiki (specifically `*.tmLanguage.json` files, also [see the shiki documentation](https://github.com/shikijs/shiki/blob/main/docs/languages.md#supporting-your-own-languages-with-shiki)), but currently there's no way to do that.

### Describe the solution you'd like

Not sure about the API, but I see two options here (not necessarily mutually-exclusive!):

Either allow to simply specify path to the grammar, so it would be loaded by VitePress automagically (I guess it is relatively easy to preload custom languages [here](https://github.com/vuejs/vitepress/blob/c9f04e045922a6f1e11136bd1ccc824c2e9928f1/src/node/markdown/plugins/highlight.ts)):

```ts
export default {
  markdown: {
    languages: [
      '/path/to/tmGrammar/json',
      '/path/to/tmGrammar/json'
    ],
    ...
  }
}
```

Or allow end users to read, parse and pass grammars manually, something like this ([this is roughly what shiki's docs suggest](https://github.com/shikijs/shiki/blob/a99c9df9818768f432a69387a4687a3344b4926e/docs/languages.md#supporting-your-own-languages-with-shiki)):

```ts
const bnfPath = join(languagesDir, 'bnf.tmLanguage.json')
const bnfJson = JSON.parse(await readFile(, 'utf8'))

const bnf = {
  id: bnfJson.name,
  scopeName: bnfJson.scopeName,
  aliases: bnfJson.aliases,
  path: bnfPath
}

export default {
  markdown: {
    languages: [bnf],
    ...
  }
}
```

The VitePress options then would look like this:

```ts
interface MarkdownOptions extends MarkdownIt.Options {
  theme?:
    | IThemeRegistration
    | { light: IThemeRegistration; dark: IThemeRegistration }

  languages?:
    | string[]
    | ILanguageRegistration[]

  ...
}
```

Let me know if I'm missing something, or maybe you have some thoughts/critique.

### Additional context

I'm migrating from custom Next.js setup to VitePress and overall it's a blast, but also it's a bit annoying to use `haskell` language for code blocks instead of `bnf` to get the code highlighted. :)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
There is this hack that will work if you wanna alias bnf for haskell: https://mysticmind.dev/vitepress-fenced-code-block-syntax-highlighting-quirks-with-net-or-other-languages

**Comment by AnWeber** [comment]
It is possible to define your own language if you implement the highlight method yourself. You can copy it from [highlight.ts](https://github.com/vuejs/vitepress/blob/3b7ff8d66e9eda3aab1fb126984efc63132bd22d/src/node/markdown/plugins/highlight.ts).

see https://github.com/vuejs/vitepress/issues/1331

```ts
import { defineConfig } from "vitepress";
import { join } from "path";
import type { HtmlRendererOptions } from "shiki";
import {
  createDiffProcessor,
  createFocusProcessor,
  createHighlightProcessor,
  createRangeProcessor,
  defineProcessor,
  getHighlighter,
  type Processor,
} from "shiki-processor";

const processors: Processor[] = [
  createFocusProcessor(),
  createHighlightProcessor({ hasHighlightClass: "highlighted" }),
  createDiffProcessor(),
  defineProcessor({
    name: "error-level",
    handler: createRangeProcessor({
      error: ["highlighted", "error"],
      warning: ["highlighted", "warning"],
    }),
  }),
];


export default async function init() {
  const highlighter = await getHighlighter({
    themes: ["css-variables"],
    processors,
  });

  highlighter.loadLanguage({
    id: "http",
    scopeName: "source.http",
    path: join(__dirname, "./http.tmLanguage.json"),
    aliases: ["Http", "HTTP"],
  });

  return defineConfig({
    markdown: {
      highlight: (str: string, lang: string, attrs: string) => {
        const vPre =  /-vue$/u.test(lang) ? "" : "v-pre";
        lang =
          lang.replace(/:(no-)?line-numbers$/u, "").replace( /-vue$/u, "").toLowerCase() || "http";

        const lineOptions = attrsToLines(attrs);
        const cleanup = (str: string) =>
          str
            .replace(/^<pre(.*?)>/u, (_, attributes) => `<pre ${vPre}${attributes}>`)
            .replace(/<pre[^>]*(style=".*?")/u, (_, style) => _.replace(style, ""));

        return cleanup(
          highlighter.codeToHtml(str, {
            lang,
            lineOptions,
          })
        );
      },
    },
  });
}

/**
 * 2 steps:
 *
 * 1. convert attrs into line numbers:
 *    {4,7-13,16,23-27,40} -> [4,7,8,9,10,11,12,13,16,23,24,25,26,27,40]
 * 2. convert line numbers into line options:
 *    [{ line: number, classes: string[] }]
 */
const attrsToLines = (attrs: string): HtmlRendererOptions["lineOptions"] => {
  attrs = attrs.replace(/^(?:\[.*?\])?.*?([\d,-]+).*/u, "$1").trim();
  const result: number[] = [];
  if (!attrs) {
    return [];
  }
  attrs
    .split(",")
    .map((v) => v.split("-").map((v) => parseInt(v, 10)))
    .forEach(([start, end]) => {
      if (start && end) {
        result.push(
          ...Array.from({ length: end - start + 1 }, (_, i) => start + i)
        );
      } else {
        result.push(start);
      }
    });
  return result.map((v) => ({
    line: v,
    classes: ["highlighted"],
  }));
};

```
