### ISSUE TITLE
VPNavBar colors setup

### ISSUE THREAD

**Issue by mchosc** [vuejs/vitepress#1540]
### Is your feature request related to a problem? Please describe.

maybe its possible already but I cannot seem to find a way to change custom colours on the VPNavBar when it has a sidebar active.
the path I tried to see if it could work was something like VPNavBar .has-sidebar.content[data-v-cf6e7c5e] in the custom.css but its def just a hack and I don't see an option on how to customise the colours easily.

### Describe the solution you'd like

add more options to vars.css regarding VPNavBar

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by emersonbottero** [comment]
you just have to override the css vars already in use.

https://github.com/emersonbottero/mermaid/blob/ec5568b943b18652f3aa9334e29cd9b6478f50c6/docs/.vitepress/theme/custom.css#L1

and import it in the theme.. 
https://github.com/emersonbottero/mermaid/blob/ec5568b943b18652f3aa9334e29cd9b6478f50c6/docs/.vitepress/theme/index.ts#L4

and it is in the docs too.. 
https://vitepress.vuejs.org/guide/theme-introduction#customizing-css

You may close this Issue!

**Comment by mchosc** [comment]
yes and it all works except when @media (min-width: 960px) {} is used then what I had to do exactly was something like this
`
@media (min-width: 960px) {
    .dark .VPNavBar {
        background: #223055; /* top at nav bar at dark mode */
    }
    .VPNavBar {
        background-color:  #FFFAE6; /* top at nav bar at light mode */
    }
    .dark .VPNavBar.has-sidebar .content[data-v-cf6e7c5e] {
        background: #223055; /* top at nav bar at dark mode */
    }
    .VPNavBar.has-sidebar .content[data-v-cf6e7c5e] {
        background-color:  #FFFAE6; /* top at nav bar at light mode*/
    }
}
`

**Comment by mchosc** [comment]
the issue is that if I try to use 
.dark .VPNavBar.has-sidebar .content
or
.dark .VPNavBar.has-sidebar

it doesn't work so no idea :-)

**Comment by ylw5** [comment]
try to add `!important`

**Comment by mchosc** [comment]
thank you all for help
@ylw5 !important worked in the end
it seems I need to learn more about css! :-)

**Comment by kissu** [comment]
> you just have to override the css vars already in use.
> 
> [emersonbottero/mermaid@`ec5568b`/docs/.vitepress/theme/custom.css#L1](https://github.com/emersonbottero/mermaid/blob/ec5568b943b18652f3aa9334e29cd9b6478f50c6/docs/.vitepress/theme/custom.css#L1)
> 
> and import it in the theme.. [emersonbottero/mermaid@`ec5568b`/docs/.vitepress/theme/index.ts#L4](https://github.com/emersonbottero/mermaid/blob/ec5568b943b18652f3aa9334e29cd9b6478f50c6/docs/.vitepress/theme/index.ts#L4)
> 
> and it is in the docs too.. [vitepress.vuejs.org/guide/theme-introduction#customizing-css](https://vitepress.vuejs.org/guide/theme-introduction#customizing-css)
> 
> You may close this Issue!

There is no way to use a local style for a single `.md` page?
Would be quite handy to pass a `style` inline.

**Comment by brc-dd** [comment]
@kissu Scoped style block / css modules will work, but only for the stuff you've inside your file, won't work for patching stuff in theme just for a single page. (BTW, we also add a page specific class to an element, it can also be used if overriding using global CSS.)

**Comment by kissu** [comment]
Thanks for the quick answer @brc-dd. 🙏🏻 
Right now I do use the following in `docs/.vitepress/theme/config.css`
```css
.VPButton.medium.brand {
  color: var(--vp-button-alt-text);
}
```

Is there a better way to style a `docs/index.md`?
I've tried with a `<style scoped>` but no success, only a global one works.

**Comment by brc-dd** [comment]
@kissu You can override it for all home pages:

```css
.is-home .VPButton.medium.brand {
  color: var(--vp-button-alt-text);
}
```

I am not sure what's your specific problem is. Looks like you want to have the button in hero section to have a different text color. Does overriding the way you've breaks some other section of the site?

Actually, I think we can solve the general issue of customizing CSS based on path, by adding the relative path as class to root. We add that currently too, but it's only there for docs pages, and that too inside `<main>` not on top.

**Comment by kissu** [comment]
I was wondering if a local block of `style` per `.md` was possible but in the end, my solution works perfectly fine.
Thanks anyway @brc-dd. 🙏🏻
