### ISSUE TITLE
The error when constructing the product

### ISSUE THREAD

**Issue by xianyue0224** [vuejs/vitepress#1541]
### Describe the bug

I'm really sorry to bother the vitepress developers with such a small problem, I love vitepress, but now run into problems that I can't solve. I try to build the production version and always report errors as shown but from the error stack I can t find the root of the problem it looks a lot like a bug inside vitepress and probably also because my limited personal level caused me unable to solve it so I decided to mention this issues.

### Reproduction

npm run docs:build

### Expected behavior

Successfully get the construction product

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 1.15 GB / 7.86 GB
  Binaries:
    Node: 16.16.0 - G:\Nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - G:\Nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vitepress: ^1.0.0-alpha.25 => 1.0.0-alpha.25
```

### Additional context

![bug](https://res.cloudinary.com/dbctxzoeq/image/upload/v1666791430/blogImage/Snipaste_2022-10-26_21-36-33_pybsij.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
There is some component using `window` directly at top-level. Use it inside something like `onMounted` or wrap the component in `<ClientOnly>` as browser APIs like `document`, `window`, `localStorage`, etc. are not present during SSR. It'll be quick if you can share your code.

**Comment by brc-dd** [comment]
Closing as stale.
