### ISSUE TITLE
different space in doc 

### ISSUE THREAD

**Issue by ylw5** [vuejs/vitepress#1549]
![屏幕截图 2022-10-29 013328](https://user-images.githubusercontent.com/93325995/198698453-d270772e-5e70-475b-a40b-98f4df2e7b6c.jpg)

[vitepress/guide/markdown/line-highlighting-in-code-blocks](https://vitepress.vuejs.org/guide/markdown#line-highlighting-in-code-blocks)

I don't know if it is a mistake in doc, the space between 'code' and 'hl' is different. And I test the second one, it can't word actually.
Should I make a PR?

**Comment by brc-dd** [comment]
It is intentional. If you remove that extra space in fences, that line will get highlighted and the comment will be stripped. We probably can add a note later why there are two spaces, so people don't get confused.

**Comment by ylw5** [comment]
Thanks for your answer !
