### ISSUE TITLE
unescaped \ escaping char in sidebar titles

### ISSUE THREAD

**Issue by matias-capeletto** [vuejs/vitepress#155]
From https://github.com/vuejs/vitepress/pull/152#issuecomment-733801888

The issue appears when using the escaping char in heading in markdown, for example:
```
## \$page
```

![image](https://user-images.githubusercontent.com/583075/100261613-50d32680-2f4b-11eb-92d5-738515f5540d.png)

**Comment by kiaking** [comment]
When escaping, the string seems to get double escape. See `\\$page`. Not sure where to look at, at the moment.

<img width="293" alt="Screen Shot 2020-11-26 at 17 43 00" src="https://user-images.githubusercontent.com/3753672/100327731-fdc2a780-300e-11eb-9f2e-765a188c246d.png">

**Comment by matias-capeletto** [comment]
I was reviewing unmerged PRs from vuepress and found two that are related to this issue:

This one is a direct fix: https://github.com/vuejs/vuepress/pull/2363
Also including support for superscript and subscript
```md
## \$accentColor
## Infomation about H~2~O
## $\S$ 1.1
```

This one fixed other cases https://github.com/vuejs/vuepress/pull/2688 (and if I think it also includes a fix for this issue)
```md
## [Subscript](https://github.com/markdown-it/markdown-it-sub) / [Superscript](https://github.com/markdown-it/markdown-it-sup)
## [\<ins>](https://github.com/markdown-it/markdown-it-ins)
## [\<mark>](https://github.com/markdown-it/markdown-it-mark)
```

I think all of the above examples are failing in vitepress too. 

Should we port the tests from 
https://github.com/vuejs/vuepress/blob/master/packages/@vuepress/shared-utils/__tests__/parseHeaders.spec.ts
into vitepress tests like:
`/__tests__/shared-utils/parseHeaders.spec.ts`
and port the fixes of these PRs? 

For later, If both vitepress and vuepress will coexist, maybe there could be a package at one point to share these utils so both projects will benefit from the fixes.

**Comment by matias-capeletto** [comment]
I started working on this one to better understand the issue. There are two tests more that we should port:
https://github.com/vuejs/vuepress/blob/master/packages/@vuepress/shared-utils/__tests__/deeplyParseHeaders.spec.ts
https://github.com/vuejs/vuepress/blob/master/packages/@vuepress/shared-utils/__tests__/removeNonCodeWrappedHTML.spec.ts

The changes in the PRs are working as expected. 

The only part I am not sure if should be added is this one from https://github.com/vuejs/vuepress/pull/2363:
> Also some people will use katex or mathjax, superscript and subscript to display math or chemistry expression in their headings. Though vuepress is not providing these plugins by default, it's better that vuepress can handle them
> 
> ```
> ## $\S$ 1.1                   // mathjax symbol
> 
> ## Infomation about H~2~O     // subscript, but it means strikethrough in github comments
> ```

I am inclined to also include it, but maybe this should be handled by markdown plugins.
