### ISSUE TITLE
[Question] How to create a dropdown version?

### ISSUE THREAD

**Issue by brunokunace** [vuejs/vitepress#1550]
I trying to create a dropdown with versions of my app, and remove (or add) elements based on this version. Anyone have example how to make it? or maybe its a proposal to make default in vite

**Comment by brc-dd** [comment]
#109?

**Comment by kiaking** [comment]
Yeah this is a feature request of "Versioning". We currently don't have it, and it's kinda tough one. Let's keep track in #109.
