### ISSUE TITLE
Italic font rendering doesn't work in Safari

### ISSUE THREAD

**Issue by LittleChimera** [vuejs/vitepress#1558]
### Describe the bug

Instead of italic font rendering, only regular font is displayed in Safari.

### Reproduction

Write a markdown with _italic rendering_, and open in Safari.

### Expected behavior

Expected to render italic font.

### System Info

```shell
not important
```

### Additional context

Relevant issue: https://github.com/vuejs/vitepress/issues/759

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Which version of VitePress and Safari are you using? It's working fine for me on Safari 15.6.

**Comment by brc-dd** [comment]
Closing as stale.

**Comment by infotexture** [comment]
@brc-dd This is still a problem in Safari 16.2 with 1.0.0-alpha.32.

Looks italic fonts were missing when you wrote  https://github.com/vuejs/vitepress/issues/759#issuecomment-1151364756. With the switch to Inter var for #759 with #777, it seems like it _should_ work, but still doesn't, even with a custom CSS rule to force `<em>` to _italic_:

```css
em {
  font-style: italic;
}
```

Works fine in Chrome & Firefox.

**Comment by infotexture** [comment]
@rsms ❓ Should this work — or do we need other CSS tricks to get Safari to render italics with Inter’s variable variant? 🤔

**Comment by rsms** [comment]
Make sure to use the official releases from rsms.me/inter (or GitHub.com/rsms/inter/releases) Google Fonts’ version of Inter does not include italics (and is pretty old.)
