### ISSUE TITLE
[code copy]: shell lang code block remove trailing newline

### ISSUE THREAD

**Issue by Zhengqbbb** [vuejs/vitepress#1559]
### Is your feature request related to a problem? Please describe.

https://github.com/vuejs/vitepress/blob/4b0b1ef35f38461514f3e97e0a509029a70d3086/src/client/app/composables/copyCode.ts#L20-L24

Use `innerText` will include element properties. Like block element will make `text` with  trailing newline `\n`

### Describe the solution you'd like

**code copy remove trailing newline**

And I'm not sure if all lang code copy should remove this hidden problem.

But should be removed in the shell lang . Because in SHELL env (like bash) or some termianl apps, there is a trailing newline in our copy, the command will to be executed directly after paste, which is dangerous.

### Describe alternatives you've considered

If maintainer agree, I will submit a PR
```ts
if (isShell)
  text = text.replace(/^ *($|>) /gm, '').replace(/[\n\r]$/, '')
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah I agree it's dangerous. Better directly put `.trim()` there. Feel free to create a PR! 🙌
