### ISSUE TITLE
无论是全局引入组件或者局部引入组件，都会影响顶部导航栏

### ISSUE THREAD

**Issue by ckcoding** [vuejs/vitepress#1562]
### Describe the bug

这个是没有引入组件的页面
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/63556878/199180251-ec705da3-e751-482f-8361-23fa89e83c5e.png">
这个是引入组件的页面，会导致顶部导航栏消失，且切换到别的页面需要刷新才能加载出来
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/63556878/199180338-b85b7d4e-f194-450b-9ff0-7b9f8e879038.png">

### Reproduction

如题

### Expected behavior

如题

### System Info

```shell
如题
```

### Additional context

如题

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and your system info (vitepress version and browser).

**Comment by ckcoding** [comment]
> 请提供一个[最小的可重现示例](https://stackoverflow.com/help/minimal-reproducible-example)和您的系统信息（vitepress 版本和浏览器）。


如题
path:vitepress/docs/.vitepress/theme/index.js

code:=====>

import DefaultTheme from 'vitepress/theme'
import testCode from '../../../components/test-code.vue' //测试组件
export default{
  ...DefaultTheme,
  enhanceApp({ctx}) {
    ctx.app.component('test-code',testCode)
  }
}

**Comment by brc-dd** [comment]
Are there any errors on your browser console? Also, can you share the code of your component.

**Comment by ckcoding** [comment]
> 您的浏览器控制台上是否有任何错误？另外，你能分享你的组件的代码吗？vitepress/config.ts？（如果您的项目是公开的，那么 repo 链接会很棒。）

my Github: https://github.com/ckcoding/ckcoding.github.io
this is public, no any error

**Comment by brc-dd** [comment]
Looks like you already fixed that. The issue was caused by your component overriding the styles. Making it scoped fixed that.
