### ISSUE TITLE
建议新增自动提取md标题作为sidebar

### ISSUE THREAD

**Issue by pxqq** [vuejs/vitepress#1566]
这个对于文档网页特别重要，如果没有这个，那关于文档目录的显示既需要我们自己配文件，又需要自己写组件，完全体验不到vitepress在文档网站的优越性，像hugo框架就可以提供这样的功能，这就导致vitepress在文档网站的优势被进一步削弱，希望能尽快完善该功能

**Comment by brc-dd** [comment]
Duplicate of #1297
