### ISSUE TITLE
How to use the merge cells plugin for markdown-it

### ISSUE THREAD

**Issue by arcqiufeng** [vuejs/vitepress#1567]
### Is your feature request related to a problem? Please describe.

I found a markdown-it plugins for table to support merged cells.

https://github.com/Menci/markdown-it-merge-cells

And try to use it in vitepress. So I did this:

cmd:
```cmd
yarn add markdown-it-merge-cells
```

Then:
```js
// .vitepress/config.js
...
import MarkdownItMergeCells from 'markdown-it-merge-cells';
...
export default {
    markdown: {
        config: (md) => {
            md.use(MarkdownItMergeCells); 
        },
    },
...
}
```

There's no effect. It did nothing.

Can anyone tell me how to use the plugin?

### Describe the solution you'd like

tell me how.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
[It is working fine for me:](https://stackblitz.com/edit/vite-o7lxrt?file=docs%2Findex.md,docs%2F.vitepress%2Fconfig.ts)

![image](https://user-images.githubusercontent.com/40380293/199404450-0d181413-ee60-42ff-9fd3-eddcda4d9237.png)

**Comment by arcqiufeng** [comment]
I copied the codes line by line from your demo and got it working.

Thank you very much.

It seems missing the key line?

```ts
import { defineConfig } from 'vitepress';
```
and this `defineConfig`?

> export default **defineConfig(** {

I notice my file is `config.js` and your file is `config.ts`

Is it the difference between TypeScript and JavaScript?

However, I just copy your code from your `config.ts` to my `config.js`. It works fine now.

Much appreciate！

**Comment by brc-dd** [comment]
There must have been some typo earlier. `defineConfig` and .ts doesn't actually matter.
