### ISSUE TITLE
在模板语法或标签语法中，是否可以增加一个类似块一样的标识，以至于块中的内容可以被`markdown`解析器识别并渲染为`html`

### ISSUE THREAD

**Issue by Justin3go** [vuejs/vitepress#1570]
### Is your feature request related to a problem? Please describe.

我想要通过一些控制语句实现`markdown`文档的快速编写，比如这样：
```html
// XXX.md
---
sidebar: false
---
<script setup>
import { beijing } from '../const/imgLink.ts'
</script>
# 标题一  

<div v-for='item in beijing'>
  ## {{item[0].title}}
  <many-pictures :srcImgs='item' :lazy='true' />
</div>
```
但显然`# 标题一 `可以被成功渲染为标题，而`## {{item[0].title}}`却只能是纯文本，因为这部分根本不会经过`markdown`渲染器的渲染。

### Describe the solution you'd like

我理解是否可以添加一个标识，比如：
```js
<div v-for='item in beijing'>
  ## {{item[0].title}}
  ::: markdown-block
    ## title
    // content
  ::: 
  <many-pictures :srcImgs='item' :lazy='true' />
</div>

```
然后预期中这个块会被`markdown`渲染器渲染之后再交给`vue`相关的编译器去解析。
如果可以支持这个功能，结合`vue`中的`v-if/v-for`等条件控制语句，可以帮助我实现许多页面的快速编写

### Describe alternatives you've considered

目前我只能直接在`v-for`语句中编写纯`html`语法的内容，这对于我来说有一定的心智负担，还是以上述的例子来说，这是我目前的替代方案：
```html
---
sidebar: false
---
<script setup>
import { beijing } from '../const/imgLink.ts'
</script>
# 标题一
<div v-for='item in beijing'>
  <h2 :id="item[0].title" tabindex="-1">
    {{item[0].title}}
    <a class="header-anchor" :href="`#${item[0].title}`" aria-hidden="true">#</a>
  </h2>
  <many-pictures :srcImgs='item' :lazy='true' />
</div>
```

### Additional context

我也许可以尝试实现该功能

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Just add empty lines between html and markdown:

```md
---
sidebar: false
---

<script setup>
import { beijing } from '../const/imgLink.ts'
</script>

# 标题一  

<div v-for='item in beijing'>

## {{item[0].title}}

  <many-pictures :srcImgs='item' :lazy='true' />
</div>
```
