### ISSUE TITLE
replaceAll is not a function

### ISSUE THREAD

**Issue by blankzust** [vuejs/vitepress#1574]
### Describe the bug

error happened here
![image](https://user-images.githubusercontent.com/8541906/199720374-4aab749a-778f-46df-9427-f60fa0fd46bc.png) version: 1.1.3

### Reproduction

node环境下，字符串类型没有replaceAll方法

### Expected behavior

能正常看到组件预览

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Memory: 126.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.16 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 15.6.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by blankzust** [comment]
![image](https://user-images.githubusercontent.com/8541906/199722924-3322890b-11e4-4c8e-b861-478fcedbe106.png)
错误现象

**Comment by brc-dd** [comment]
Can you share your code? Likely you're calling replaceAll on something that is not string, and this error is not related to VitePress itself. Also, in your first image, using replaceAll seems unnecessary as the regex already has the global flag. Just replace will also work there.

**Comment by blankzust** [comment]
This error happened in @vitepress-demo-preview/plugin.
