### ISSUE TITLE
Badge component does not work

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#1576]
### Describe the bug

```
[Vue warn]: Failed to resolve component: Badge
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
```

### Reproduction

NA

### Expected behavior

NA

### System Info

```shell
NA
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Are you having a custom theme? If so, then maybe you forgot to call DefaultTheme.enhanceApp inside your enhanceApp? Refer updated docs on how to extend the default theme.

**Comment by Charles7c** [comment]
> 

ok, I saw this configuration, but only doubted it, thanks.

```
import DefaultTheme from 'vitepress/theme'
import MyLayout from './MyLayout.vue'
import './styles/vars.css'
import './styles/custom.css'

export default {
  ...DefaultTheme,
  Layout: MyLayout,
  enhanceApp(ctx) {
    // extend default theme custom behaviour.
    DefaultTheme.enhanceApp(ctx)

    // register your custom global components
    // ctx.app.component('MyGlobalComponent' /* ... */)
  }
}
```
