### ISSUE TITLE
style conflict

### ISSUE THREAD

**Issue by UstinianMobius** [vuejs/vitepress#1577]
### Describe the bug

use vitepress@1.0.0-alpha.27,  i import the style package of ant-design-vue in theme.js,  vitepress/theme conflict with it

### Reproduction

my current approach is to only import globally ant-design-vue and import component styles file inside each file

### Expected behavior

no conflict

### System Info

```shell
MacBook Pro (13-inch, M1, 2020) 
Chrome 106.0.5249.119（正式版本） (arm64)
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by rookiePrgrmer** [comment]
try this, https://vitepress.vuejs.org/guide/markdown#raw

**Comment by eviovc67** [comment]
the same problem when i use "element-plus"  table component  is conflict with vp-doc .table class

**Comment by kiaking** [comment]
Try using `raw` feature 👍
