### ISSUE TITLE
vitepress serve tries to load an md.undefined.js file

### ISSUE THREAD

**Issue by you-hengh** [vuejs/vitepress#1578]
### Describe the bug

https://github.com/vuejs/vitepress/blob/9004a801305fa0c21a0064253da95fbad38148fe/src/client/app/utils.ts#L38

by 

https://github.com/vuejs/vitepress/blob/89cc718649b9be547c6ec08d2dc3d10a67f2a3ac/src/client/app/utils.ts#L38-L39

should fix this.

_Originally posted by @brc-dd in https://github.com/vuejs/vitepress/issues/412#issuecomment-1149704365_
      

I still have this problem

vitepress version:1.0.0-alpha.26  or npm:@brc-dd/vitepress@1.0.0-dev.50d1202

I try to configure `cleanUrls: 'with-subfolders'` or `cleanUrls:' without-subfolders'` or delete the cleanUrls configuration item makes no difference or is still reporting an error

I will temporarily open my [repo](https://github.com/you-hengh/myblog_vitepress) to find bugs.

### Reproduction

package.json
```json
{
  "name": "vitepress",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "vitepress dev docs",
    "build": "vitepress build docs",
    "serve": "vitepress serve docs"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@algolia/client-search": "^4.14.2",
    "vitepress": "npm:@brc-dd/vitepress@1.0.0-dev.50d1202"
  }
}
```

1. pnpm build

   ```bash
   > vitepress build docs

   vitepress v1.0.0-dev.50d1202
   ✓ building client + server bundles...
   ⠋ rendering pages...[Vue warn]: Component <Anonymous> is missing template or render    function.
   [Vue warn]: Component <Anonymous> is missing template or render function.
   [Vue warn]: Component <Anonymous> is missing template or render function.
   [Vue warn]: Component <Anonymous> is missing template or render function.
   [Vue warn]: Component <Anonymous> is missing template or render function.
   [Vue warn]: Component <Anonymous> is missing template or render function.
   [Vue warn]: Component <Anonymous> is missing template or render function.
   [Vue warn]: Component <Anonymous> is missing template or render function.
   ✓ rendering pages...
   build complete in 3.35s.
   ```

2. pnpm serve

   ```bash
   > vitepress@1.0.0 serve /Users/bddxg/Documents/网站/vitepress 站点
   > vitepress serve docs

   vitepress v1.0.0-dev.50d1202
   Built site served at http://localhost:4173/
   ```
![](https://user-images.githubusercontent.com/34816426/200002162-4c71e2bc-e500-433f-8a70-4ab12921d944.png)

### Expected behavior

fix bug or tell me the solution.

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.11 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.1
  npmPackages:
    @brc-dd/vitepress:  1.0.0-dev.50d1202
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by you-hengh** [comment]
I updated my [repo](https://github.com/you-hengh/myblog_vitepress), the main change is that some of my previous nav and sidebar are empty links, and now they all have content, and my error report has been reduced to one.
![image](https://user-images.githubusercontent.com/34816426/200176404-ee0bbcac-2ede-44d5-8814-81289f2cb248.png)
I'm surprised about this error, I've never written anything about guide_what-is-vitepress.md,I don't even know how to fix this error

**Comment by brc-dd** [comment]
>  I've never written anything about guide_what-is-vitepress.md

Sure you've: https://github.com/you-hengh/myblog_vitepress/blob/6466a1e6308b9fbb419b6c2e0a4869c314b39745/docs/index.md?plain=1#L14

**Comment by you-hengh** [comment]
> > I've never written anything about guide_what-is-vitepress.md
> 
> Sure you've: https://github.com/you-hengh/myblog_vitepress/blob/main/docs/index.md?plain=1#L14

Oh, my God, thank you very much, this part of the content I directly copy official website, I did not notice that it added a link,Anyway, thank you very much for your reply.
