### ISSUE TITLE
use solidjs in vitepress build error

### ISSUE THREAD

**Issue by laddish** [vuejs/vitepress#1586]
### Describe the bug

I try to use SolidJS in vitepress,
when in development mode, it works ok,
but when I build, during the render process,
it throws error like:
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at async render (file:///home/projects/vite-hnzcih/docs/.vitepress/.temp/app.js:4605:5)
    at async renderPage (file:///home/projects/vite-hnzcih/node_modules/vitepress/dist/node/serve-afe9b056.js:41460:19)
    at async Promise.all (index 1)
    at async Module.build (file:///home/projects/vite-hnzcih/node_modules/vitepress/dist/node/serve-afe9b056.js:42209:7)

![image](https://user-images.githubusercontent.com/49431692/200234165-48e92376-7854-4211-ae00-e7ae02ce62b8.png)

import { template, render } from 'solid-js/web';
         ^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'template'
![image](https://user-images.githubusercontent.com/49431692/200236217-d957bce4-e1ab-4ab1-be04-7f02ff63f560.png)

I don't know why.
In pure vite program, it builds success.
In the reproduction, it seems can't resolve solid-js/web

### Reproduction

https://stackblitz.com/edit/vite-hnzcih?file=docs/components/Home.tsx

run  
```
npm install && npm run docs:dev
```
 it renders ok,
but run
```
 npm install && npm run docs:build
```
it will throw error.

### Expected behavior

I hope it builds successfully.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vitepress: latest => 1.0.0-alpha.23
```

### Additional context

Alter ‘solid-js’ from ‘devDependencies’ to ‘dependencies’ still wasn't working.

``` 
 "dependencies": {
    "@babel/core": "^7.19.6",
    "babel-preset-solid": "^1.6.1",
    "solid-js": "^1.6.1",
    "vite-plugin-solid": "^2.4.0",
    "vitepress": "latest"
  }
```

```
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';

export default defineConfig({
  plugins: [solidPlugin()],
  server: {
    port: 3000,
  },
  build: {
    target: 'esnext',
  },
});
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by dream2023** [comment]
I have some error

**Comment by kiaking** [comment]
Ah, sorry but VitePress is made with Vue, and I don't think we gonna support directly importing other frameworks 😅 I'm surprised that it works on dev mode 👀
