### ISSUE TITLE
Doubled content on production env

### ISSUE THREAD

**Issue by breftejk** [vuejs/vitepress#1592]
### Describe the bug

When I use yarn run docs:serve on my PRODUCTION server, its content is duplicated. Also, when you switch to a new page, the content of the old page is still visible. I don't know what is causing this strange behaviour.

### Reproduction

https://github.com/Assistants-Center/Discord-Dashboard/tree/v3/docs
yarn run docs:serve

https://dbd-docs-v3.assistantscenter.com/

### Expected behavior

Content not expected to be doubled. Equally, it should not work so that when you switch to a new page, the content of the old page is still visible.

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) arm64 Neoverse-N1
    Memory: 20.84 GB / 23.43 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  npmPackages:
    vitepress: ^1.0.0-alpha.28 => 1.0.0-alpha.27
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
There are some errors with your code:

1. You've deployed your code to a platform that strips out comments from HTML (auto-minifies) that have meaning to Vue.
2. You've empty `icon:`s in index.md.
3. You've not extended the default theme properly (missing `DefaultTheme.enhanceApp(ctx)` in `.vitepress/theme/index.js`).
