### ISSUE TITLE
Line numbers don't work correctly with code group.

### ISSUE THREAD

**Issue by Rollczi** [vuejs/vitepress#1594]
### Describe the bug

Line numbers don't work correctly with code group.
![image](https://user-images.githubusercontent.com/49173834/200756926-c85accb7-37f5-4ed1-bf4c-ab47a54f6079.png)

### Reproduction

Enable line numbers:
![image](https://user-images.githubusercontent.com/49173834/200756403-db268382-9586-41c3-a393-3ba39a364201.png)
Add code group:
![image](https://user-images.githubusercontent.com/49173834/200756458-5f7c64d6-123c-47f6-b9fa-873ecfbb1011.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/49173834/200756770-eb74031c-1113-4d5a-b2bd-69c63c9d8e6a.png)

### System Info

```shell
System:                                                 
    OS: Windows 10 10.0.19045                             
    CPU: (6) x64 Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
    Memory: 1.83 GB / 15.94 GB                            
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.35)
  npmPackages:
    vitepress: 1.0.0-alpha.28 => 1.0.0-alpha.28
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
The issue is with whatever plugin you're using, not VitePress.
