### ISSUE TITLE
Config nav support custom target

### ISSUE THREAD

**Issue by godxiaoji** [vuejs/vitepress#1595]
### Is your feature request related to a problem? Please describe.

For example:
The `/docs` is bulit on vitepress, but `/docs/demo` is another project. 
By default, vitepress judge that it is not an external link. It will throw an error when click the nav item:
```js
demo/index.md?import&t=1668047882054  net::ERR_ABORTED 404 (Not Found) 
```
I think it is better to set `target="_blank"`  in such scenarios.

### Describe the solution you'd like

Add a configuration item.
```js
nav: [
  { text: 'NewTab', link: '/newTab', target: '_blank' }
]
```
The custom target has the highest priority.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [ ] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by godxiaoji** [comment]
> Regarding the alternatives, you can specify complete URL (`https://foo.bar/docs/demo`), it'll then treat it as external.

This is how I use it at present. However, it is not friendly to multiple domains.

**Comment by brc-dd** [comment]
https://vitepress.vuejs.org/guide/asset-handling#public-files
