### ISSUE TITLE
Import a file that's not in the root directory

### ISSUE THREAD

**Issue by clemvnt** [vuejs/vitepress#16]
**Is your feature request related to a problem? Please describe.**

Currently, I have a directory structure like :
```
project/
├── dist/
├── docs/
│   ├── .vitepress/
│   └── index.md
├── src/
│   └── components/
├── package.json
└── ...
```

The `docs` directory contains a vitepress app.

If I'm not mistaken, that's not possible to import a file that's not in the docs directory (a `.vue` file from `src` directory for example).

**Describe the solution you'd like**

I don't know what's the best solution to this problem. <s>But if we can add a custom vite resolver, it should work I guess ?

Moreover, it would also be necessary to expose the vite watcher instance to watch these resolved files.</s>

Since the recent Vite features, we can alias a path to a fs directory, but in Vitepress, we can't override the vite configuration to add our aliases.

**Comment by yyx990803** [comment]
That's a good point - should support passing options onto vite in VitePress' config file.

**Comment by adamdehaven** [comment]
This no longer appears to work, especially if the `../src/components/**/*.vue` file utilizes a `@/` alias for the `serc` directory (e.g. you want to utilize components from the same repo inside the `/docs` directory)

**Comment by brc-dd** [comment]
@adamdehaven Hi, its working for me: https://github.com/brc-dd/vitepress-with-alias, can you create a separate issue with a minimal, reproducible example?

**Comment by adamdehaven** [comment]
@brc-dd what if your `HelloWorld.vue` component imports another component from `/components`, utilizing the `@/` alias?

**Comment by brc-dd** [comment]
You'll need a separate vite config file for that. I've updated the example.

**Comment by adamdehaven** [comment]
Hmm, I have that as well.
