### ISSUE TITLE
Config page has a missing link

### ISSUE THREAD

**Issue by akauppi** [vuejs/vitepress#160]
**Describe the bug**
The Guide's [Configuration page] refers to [https://vitepress.vuejs.org/config/](https://vitepress.vuejs.org/config/) but that page gives a 404. 

This should likely be `https://vitepress.vuejs.org/config/basics` which can be reached from the top navigation bar.

**To Reproduce**
- visit https://vitepress.vuejs.org/guide/configuration.html

**Expected behavior**

I would have done a PR but not sure, whether the URL without `basics` is expected to work (different from changing the URL itself by appending that string).

**System Info**
- vitepress version: online docs

**Additional context**

**Comment by kiaking** [comment]
Thanks! Good catch. I'll fix this. Yes, the link should be pointing to `config/basics` in this case 👍
