### ISSUE TITLE
Is it possible to force light-mode?

### ISSUE THREAD

**Issue by wouter-muller** [vuejs/vitepress#1600]
Hello,

First of all, i want to say, I absolutely love Vitepress! I built an application with it that showcases our company's documentation (coding guidelines etc) but also a style guide where we showcase for example our reusable Vue components (that Vue components work out of the box was thrilling to discover!).

For this style-guide I also (next to the default Vitepress styles/theme) load our own .css file that contains our global styles. This works fine in light mode, except when i view the application in dark mode it clashes cause our global styles set a fixed `color: black` on for example `<p>` tags, so then you get black text on a black/dark background. So i've been looking for a way to force light mode in our Vitepress application.

In the documentation i only found that you can force dark mode, or that you can take the preferred color scheme of the user, and that you can remove the "Switch dark/light mode" toggle (i am guessing it then also takes the preferred color scheme of the user). by using the `appearance` boolean. 

I think for my use-case i'd need a 4th option, to force light mode. Is it possible to add this? And then i'd also need to hide or remove the dark/light mode toggle so users can't choose dark mode.

Thanks in advance!

I am on "vitepress": "^1.0.0-alpha.27"

**Comment by wouter-muller** [comment]
Here is a direct link to our Vitepress application in case the problem is not clear: https://mc-documentation.netlify.app/ (and then turn on dark mode).

**Comment by Soya-xy** [comment]
You can set `appearance:true`
[look here](https://vitepress.vuejs.org/config/app-configs#appearance)

**Comment by Soya-xy** [comment]
You can set `appearance : false`
When appearance is false, the toggle button is removed and the default light mode is locked 
[docs](https://vitepress.vuejs.org/config/app-configs#appearance)

**Comment by wouter-muller** [comment]
Thanks for your reply!

When reading the docs, i was under the assumption that setting `appearance: false` merely hides the toggle, and still listens to the preferred user color scheme, the docs are not that clear about it in my opinion. But i'll try that and see if that works! Thanks again :)

**Comment by wouter-muller** [comment]
OK, i tested it and it works! So this issue can be closed, but perhaps it could be considered to improve the documentation as at least I found this confusing.
