### ISSUE TITLE
Load codepen.io or similar websites

### ISSUE THREAD

**Issue by you-hengh** [vuejs/vitepress#1605]
### Is your feature request related to a problem? Please describe.

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/34816426/201522412-1c23a5cf-c53b-4e72-ab25-c02a7a9610f2.png">
I hope vuepress can easily load the code shared by codepen.io.

### Describe the solution you'd like

::: codepen
https://codepen.io/you-hengh/pen/ZEvZRPr?editors=1100
:::

### Describe alternatives you've considered

none

### Additional context

Ability to support loading of other online sites, such as
https://www.processon.com/mindmap/60c6b4910791296f0ab53bcb

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can already copy the embed from codepen and add it to your page. What's the problem?

**Comment by you-hengh** [comment]
> You can already copy the embed from codepen and add it to your page. What's the problem?
> 
> ```lisp
> # Grid Template Demo
> 
> CodePen:
> 
> <iframe height="300" style="width: 100%;" scrolling="no" title="grid-template-minmax" src="https://codepen.io/you-hengh/embed/preview/ZEvZRPr?default-tab=html%2Cresult&editable=true&theme-id=dark" frameborder="no" loading="lazy" allowtransparency="true" allowfullscreen="true">
>   See the Pen <a href="https://codepen.io/you-hengh/pen/ZEvZRPr">
>   grid-template-minmax</a> by Mr-Q (<a href="https://codepen.io/you-hengh">@you-hengh</a>)
>   on <a href="https://codepen.io">CodePen</a>.
> </iframe>
> ```

I didn't notice a link like you before.

> Src= "https://codepen.io/you-hengh/embed/preview/ZEvZRPr?default-tab=html%2Cresult&editable=true&theme-id=dark"

I wrote a link like this in src in iframe.

> < iframe src= "https://codepen.io/you-hengh/pen/LYevyzX".....>

This leads to false reports like this on the website.
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/34816426/201564666-e5c0e3ff-a203-4d12-9a8c-c5ec29930f78.png">

Anyway, thank you very much for your answer. I wish you a happy life.
