### ISSUE TITLE
Is there an alternative to additionalPages in VuePress?

### ISSUE THREAD

**Issue by cloydlau** [vuejs/vitepress#1614]
### Is your feature request related to a problem? Please describe.

Excuse me, is there an alternative to [additionalPages](https://vuepress.vuejs.org/plugin/option-api.html#additionalpages) in VuePress? What is the right way to render a remote markdown file in VitePress?

### Describe the solution you'd like

Providing an API that we can render remote markdown files if possible.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
To some extent this should be doable via [dynamic routes](https://vitepress.dev/guide/routing) + [build-time data loading](https://vitepress.dev/guide/data-loading).
