### ISSUE TITLE
Import code snippets from files without extension or symlinks is not working 

### ISSUE THREAD

**Issue by fessacchiotto** [vuejs/vitepress#1617]
### Describe the bug

Import code snippets from files without extension or symlinks is not working.  
The incorrect output is:

`Invalid code snippet option`

### Reproduction

This one doesn't work if `nginx.conf` is a symlink (mac os ventura)
`<<< @/nginx/nginx.conf{nginx}  `

This one doesnt work because an extension is missing (?)
`<<< @/nginx/q-track{nginx}
`

### Expected behavior

We should see the content of the imported file.

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 334.27 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Brave Browser: 98.1.35.101
    Chrome: 107.0.5304.110
    Firefox: 97.0
    Safari: 16.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by dukexie** [comment]
```
<<< @/.vscode/scss.code-snippets
```

Invalid code snippet option
