### ISSUE TITLE
Static resource build is not packaged

### ISSUE THREAD

**Issue by laterdays** [vuejs/vitepress#1626]
### Describe the bug

Static resource build is not packaged

![image](https://user-images.githubusercontent.com/112848218/202892016-477506fa-0782-439c-86e0-1ac27c95b9f7.png)

When I use it, I use the relative path `./modules/` , which works fine at runtime, but when packaged it prompts 404

### Reproduction

*

### Expected behavior

How do you ensure that your development and production environments are consistent

### System Info

```shell
windows
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by laterdays** [comment]
![image](https://user-images.githubusercontent.com/112848218/202892125-4218a90a-88e6-4f84-a4ec-49770ba1ac79.png)
![image](https://user-images.githubusercontent.com/112848218/202892143-61809882-4d4a-45df-a3a1-03eb9b92b55e.png)

**Comment by godxiaoji** [comment]
It's the same vite. If you need use static resources, place it in `public` folder .
eg:
```
machine-room
  public
    modules
  components
  index.md
```
You can visit it by  `/three-js/demos/machine-room/modules/cabinet-hover.jpg`.

**Comment by brc-dd** [comment]
Can you share the code where you're referencing that image?

**Comment by brc-dd** [comment]
Closing as stale.
