### ISSUE TITLE
Hydration completed but contains mismatches

### ISSUE THREAD

**Issue by laterdays** [vuejs/vitepress#1627]
### Describe the bug

It will report errors in production

app.b77605b4.js:1 Hydration completed but contains mismatches

### Reproduction

*

### Expected behavior

It will report errors in production

app.b77605b4.js:1 Hydration completed but contains mismatches

### System Info

```shell
windows
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by GOGOGOSIR** [comment]
I have the same problem, When I introduce elementplus in vitepress, it packs successfully, but after running docs:serve I get this problem. But I tried docs:dev, and it works fine

![image](https://user-images.githubusercontent.com/26272801/203047823-6d38b7bd-5796-4c35-b631-55f8c53231f6.png)

vitepress Configuration：
![image](https://user-images.githubusercontent.com/26272801/203048772-551e3403-3946-41bf-b8c7-327455f0b72b.png)

**Comment by godxiaoji** [comment]
> I have the same problem, When I introduce elementplus in vitepress, it packs successfully, but after running docs:serve I get this problem. But I tried docs:dev, and it works fine

It is possible the components of ElementPlus do not support SSR properly. Expand the error cause to see the error source.

**Comment by laterdays** [comment]
![图片](https://user-images.githubusercontent.com/112848218/203191315-5ede54c8-3a7e-4544-9caf-1a91a02bb304.png)
@godxiaoji

**Comment by laterdays** [comment]
You can only see this information, and you can't see the specific source

**Comment by brc-dd** [comment]
Try adding this in vite.config.ts:

```ts
export default {
  ssr: { noExternal: ['element-plus'] }
}
```

**Comment by laterdays** [comment]
@brc-dd  After the addition, the problem persists,    i use vitepress-plugin-search & naive-ui

**Comment by greenhat616** [comment]
> @brc-dd After the addition, the problem persists, i use vitepress-plugin-search & naive-ui

The Vitepress-plugin-search will result in this issue too.
Related:  https://github.com/emersonbottero/vitepress-plugin-search/issues/23

**Comment by tolking** [comment]
may be related to the [teleports](https://vuejs.org/guide/scaling-up/ssr.html#teleports)

**Comment by brc-dd** [comment]
The issue might be related to vitepress-plugin-search as some people have mentioned. Not with vitepress itself. We can't tell unless you provide us a minimal reproducible example. If removing the plugin fixes it, then create an issue on it's repo instead.

I'll review #1642 too, but it is less likely to be used by that plugin, using ClientOnly or [SafeTeleport](https://github.com/Akryum/vue-safe-teleport) might be better choices there.

**Comment by tolking** [comment]
The reason for the problem is that the [Teleport](https://vuejs.org/guide/scaling-up/ssr.html#teleports) needs special handling during SSR.

### Reproduction

- input

```md
<Teleport to="body">
  <p>any content</p>
</Teleport>
```

- docs-build
- docs-serve
- the error will occur when the relevant page is opened directly (or refresh the page)


Although the `ClientOnly` components can be used to wrap `Teleport`, but the relevant content will not be generated in the final page HTML. For SSG, should not it generate more static content?

The PR #1642 provides a way to inject the teleport markup into the correct location in final page HTML.

**Comment by haiting** [comment]
> @brc-dd After the addition, the problem persists, i use vitepress-plugin-search & naive-ui

Is the `vitepress-plugin-search` plugin working successfully after `build:docs` on your project ?
