### ISSUE TITLE
Problems with deploying to github pages

### ISSUE THREAD

**Issue by jtgober** [vuejs/vitepress#1634]
### Describe the bug

When I run the deploy.yml from ci, it succeeds, but the assets seemingly do not load properly.

### Reproduction

Deploy using CI yaml (i changed commands to npm instead of yarn)

- checked that file structure was correct
- checked that base was = '/vipress/' - https://jtgober.github.io/vipress/
- using the default build dir. (.vitepress/dist)

### Expected behavior

Should display normally

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 23.22 GB / 31.93 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.52)    
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.29 => 1.0.0-alpha.29
```

### Additional context

[repo can be found here](https://github.com/jtgober/vipress) 
[github page can be found here](https://jtgober.github.io/vipress/)

Note: i was able to get this to work with netlify. that link can be seen here - https://www.documentation-biome.xyz

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by CHOYSEN** [comment]
> If your site is to be served at a subdirectory (https://example.com/subdir/), then you have to set '/subdir/' as the [base](https://vitepress.vuejs.org/config/app-configs#base) in your `docs/.vitepress/config.js`.
https://vitepress.vuejs.org/guide/deploying

So, you should set `/vipress/` as your `base` in vitepress config file or update your ci config:

```
// https://github.com/jtgober/vipress/blob/main/.github/workflows/deploy.yml#L22
npm run docs:build --base /vipress/
```

**Comment by brc-dd** [comment]
`base` should be outside `themeConfig` here https://github.com/jtgober/vipress/blob/fb45e2788092541a6a33806350de86dffecac6a9/docs/.vitepress/config.js#L5

**Comment by jtgober** [comment]
> `base` should be outside `themeConfig` here https://github.com/jtgober/vipress/blob/fb45e2788092541a6a33806350de86dffecac6a9/docs/.vitepress/config.js#L5

This was accurate 😓. Thanks for your time!
