### ISSUE TITLE
Page outline should use textContent instead of innerText to avoid mutation from CSS text-transform property

### ISSUE THREAD

**Issue by wrainbird** [vuejs/vitepress#1637]
### Describe the bug

Currently the page outline uses a querySelectorAll which grabs the title using `el.innerText`. 

If we use `el.textContent` instead - it will copy the text exactly the same as what's in the markdown file.

### Reproduction

Style h2 tags to be `text-transform: uppercase;` then in page outline you will see that the text is hardcoded as uppercase text:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/1315304/203462026-7c3b1977-b531-4ac4-aefd-5aa3c55a4a9a.png">

### Expected behavior

The page outline should not output mutated text, it should use the same text as what is in the markdown file and leave it up to the CSS to mutate text. 

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.03 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 107.0
    Safari: 15.6.1
  npmPackages:
    vitepress: ^1.0.0-alpha.29 => 1.0.0-alpha.29
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Ah, I didn't know that text-transform effects innerText. Thanks for the report.

**Comment by brc-dd** [comment]
This was fixed earlier.
