### ISSUE TITLE
The head configuration, when packaged and deployed to GitHub Pages, did not have the desired effect

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#1643]
### Describe the bug

I added two <script> to the head configuration that I wanted to execute once per page opened, they worked fine in the development environment, but after packaging and deploying to GitHub Pages, they only executed when the browser was refreshed.

```
  // 百度统计代码：https://tongji.baidu.com
  ['script', {}, `var _hmt = _hmt || [];
  (function() {
    var hm = document.createElement("script");
    hm.src = "https://hm.baidu.com/hm.js?xxxxxxxxxx";
    var s = document.getElementsByTagName("script")[0]; 
    s.parentNode.insertBefore(hm, s);
  })();`],
  // 页面访问量统计
  ['script', {}, `var pageUrl = location.href;
  (function() {
    xhr = new XMLHttpRequest();
    xhr.open('GET', 'https://xxxxxxxxxx/pv?pageUrl=' + pageUrl + "&t=" + new Date().getTime());
    xhr.send();
  })();`]
```

### Reproduction

N/A

### Expected behavior

N/A

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 7.05 GB / 13.87 GB
  Binaries:
    Node: 16.17.1 - D:\Develop\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - D:\Develop\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This is expected behavior. The scripts will run only when your site is loaded or a page is reloaded (as after initial load, VitePress behaves similar to a SPA). You'll need to modify your scripts to watch for URL changes. Something like this might be helpful: https://stackoverflow.com/a/46428962/11613622
