### ISSUE TITLE
Do you offer a tertiary directory  for  vitepress 

### ISSUE THREAD

**Issue by lmq352489099** [vuejs/vitepress#1660]
### Describe the bug

I want a tertiary directory like this

#  h1
### h3

But i can only view directories for secondary classes, I would like to see this level 3 presentation how do ... 

Such as :
![image](https://user-images.githubusercontent.com/37898934/205231387-2ba9be64-d346-4638-ba47-232d98f05ff9.png)

### Reproduction

rt

### Expected behavior

rt

### System Info

```shell
rt
```

### Additional context

rt

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.vuejs.org/config/theme-configs#outline
https://vitepress.vuejs.org/config/frontmatter-configs#outline

**Comment by lmq352489099** [comment]
> [https://vitepress.vuejs.org/config/theme-configs#outline ](https://vitepress.vuejs.org/config/theme-configs#outline) https://vitepress.vuejs.org/config/frontmatter-configs#outline



> [https://vitepress.vuejs.org/config/theme-configs#outline ](https://vitepress.vuejs.org/config/theme-configs#outline) https://vitepress.vuejs.org/config/frontmatter-configs#outline

谢谢,3Q,thanks,(づ￣ 3￣)づ

**Comment by YQisme** [comment]
> > [https://vitepress.vuejs.org/config/theme-configs#outline ](https://vitepress.vuejs.org/config/theme-configs#outline) https://vitepress.vuejs.org/config/frontmatter-configs#outline
> 
> > [https://vitepress.vuejs.org/config/theme-configs#outline ](https://vitepress.vuejs.org/config/theme-configs#outline) https://vitepress.vuejs.org/config/frontmatter-configs#outline
> 
> 谢谢,3Q,thanks,(づ￣ 3￣)づ

你好，请问可以在大纲中解析一级标题吗，我怎么设置都只能从第二级标题开始解析
