### ISSUE TITLE
Need to fix TypeScript interface DefaultTheme.Config

### ISSUE THREAD

**Issue by SetsuikiHyoryu** [vuejs/vitepress#1662]
### Describe the bug

I used defineConfig in config, and I try to use i18n. But interface says it not support `themeConfig.locales`, 
and I can still use `themeConfig.localeLinks` where #1339 said `themeConfig.localeLinks` removed:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/57035251/205281084-2a56e910-896b-4760-9d61-14ade19d317c.png">

And `themeConfig.locales` type check failed but it still worked:

<img width="159" alt="image" src="https://user-images.githubusercontent.com/57035251/205282867-7a50d90c-5fe2-4648-90b5-1059a4704f27.png">

Sorry I don't have enough ability to create a pull request to fix it.

### Reproduction

1. create `docs/.vitepress/config.ts`
2. write code like:
   
   ```typescript
   import { defineConfig } from 'vitepress'
 
   export default defineConfig({
      // Any code ...

      themeConfig: {
        locales: {
          '/ja/': { nav: [{ text: 'トップ', link: '/ja/' }]}
        }
      }
    }) 
   ```

### Expected behavior

No type error warning and the type to be right.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
    Memory: 35.06 GB / 63.83 GB
  Binaries:
    Node: 16.14.0 - E:\SOFT\programming\package-manage\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.24.2 - E:\SOFT\programming\package-manage\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vitepress: ^1.0.0-alpha.29 => 1.0.0-alpha.29
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by SetsuikiHyoryu** [comment]
Oh, i find the defineConfigWithTheme method. There is no any errors whe use it!

**Comment by zRains** [comment]
This doesn't look like a bug. 

### Why theme settings support `locales`?

The `locales` is deconstructed in `themeConfig`  which type is `Record<string, any>`, after that, it will be accessed through `useData()`:
https://github.com/vuejs/vitepress/blob/d58ff77eb3810a891fba80d4b7a32b536e69d7a8/src/shared/shared.ts#L58-L62

### Why dosn't support locales in typescript?

As you can see, the `UserConfig` uses a theme of type `any` in `defineConfigWithTheme`:

https://github.com/vuejs/vitepress/blob/c9f04e045922a6f1e11136bd1ccc824c2e9928f1/src/node/config.ts#L31-L40

### How to solve？

This means you need to specify `ThemeConfig` manually in `defineConfigWithTheme`, for example:
```typescript
export default defineConfigWithTheme<
  DefaultTheme.Config & { locales: Record<string, { nav: DefaultTheme.NavItem[] }> }
>({
  themeConfig: {
    locales: {
      '/ja/': { nav: [{ text: 'トップ', link: '/ja/' }] },
      '/zh/': { nav: [{ text: '中文', link: '/zh/' }] },
    },
  },
})
```

Glad to help you.

**Comment by SetsuikiHyoryu** [comment]
> This doesn't look like a bug.
> 
> ### Why theme settings support `locales`?
> The `locales` is deconstructed in `themeConfig` which type is `Record<string, any>`, after that, it will be accessed through `useData()`:
> 
> https://github.com/vuejs/vitepress/blob/d58ff77eb3810a891fba80d4b7a32b536e69d7a8/src/shared/shared.ts#L58-L62
> 
> ### Why doesn't support locales in typescript?
> As you can see, the `UserConfig` uses a theme of type `any` in `defineConfigWithTheme`:
> 
> https://github.com/vuejs/vitepress/blob/c9f04e045922a6f1e11136bd1ccc824c2e9928f1/src/node/config.ts#L31-L40
> 
> ### How to solve？
> This means you need to specify `ThemeConfig` manually in `defineConfigWithTheme`, for example:
> 
> ```ts
> export default defineConfigWithTheme<
>   DefaultTheme.Config & { locales: Record<string, { nav: DefaultTheme.NavItem[] }> }
> >({
>   themeConfig: {
>     locales: {
>       '/ja/': { nav: [{ text: 'トップ', link: '/ja/' }] },
>       '/zh/': { nav: [{ text: '中文', link: '/zh/' }] },
>     },
>   },
> })
> ```
> 
> Glad to help you.

Thank for you answer.

l saw `defineConfig` is used `UserConfig<DefaultTheme.Config>`:  

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/57035251/205433538-30e46de2-d94f-4c99-ab90-a29f10492691.png">

Why didn't define locales type in `DefaultTheme.Config`?
