### ISSUE TITLE
Custom Font - Italic and Bold not visible

### ISSUE THREAD

**Issue by Goozoon** [vuejs/vitepress#1666]
### Describe the bug

When using custom font (via google api) _Italic_ and **Bold** is not visible on site at all.

### Reproduction

.vitepress/config.js

`
    head: [
      ['link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Open+Sans' }],
    ],
`

.vitepress/theme/custom.css

`    --vp-font-family-base: 'Open Sans';`

### Expected behavior

Italic and Bold (Bold is used in H1, H2...) should be visible

### System Info

```shell
Windows, v1.0.0-alpha.29, Edge
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You are only loading the regular font. Your url should be something like this: `https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap`

**Comment by brc-dd** [comment]
> not to waste 'space' with things not in use. 

It's just a micro optimization IMO. The difference will only be ~200B (0 if cache is hit). Browser won't load those non used fonts anyway.

**Comment by brc-dd** [comment]
Yeah sure, PRs are always welcome!
