### ISSUE TITLE
VitePress does not compile a HTML-markdown mixed file saying that 'Element is missing end tag'

### ISSUE THREAD

**Issue by ice1000** [vuejs/vitepress#1673]
### Describe the bug

https://stackblitz.com/edit/vite-j7cesz?file=docs/index.md is the repro. Its `index.md` compiles just fine with some other established markdown compilers -- I tried pandoc and it worked well.

I would like to know what's wrong with my markdown code! It can be that I don't understand the VitePress markdown syntax well enough, or maybe I am lucky to find a bug in the compiler 😉 I would like to provide additional info amap.

### Reproduction

https://stackblitz.com/edit/vite-j7cesz?file=docs/index.md

### Expected behavior

Compiles just fine.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 5.91 GB / 7.61 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.2.0 - /usr/bin/node
    npm: 8.19.3 - /usr/bin/npm
  npmPackages:
    vitepress: 1.0.0-alpha.30 => 1.0.0-alpha.30
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ice1000** [comment]
Hmmmmmmmmmmmmmmm

**Comment by webpon** [comment]
你好，请问你怎么解决这个问题的呢

**Comment by ice1000** [comment]
> 你好，请问你怎么解决这个问题的呢

原理：HTML 中有反斜杠（类似 `<a>\</a>`），浏览器和一般的 markdown 解析器觉得这个反斜杠是文本，vitepress 觉得这个反斜杠是在转义后面的 `<`。

解决方法：使用 HTML entity 转义反斜杠本身即可。
