### ISSUE TITLE
The actionLink missing $withBase

### ISSUE THREAD

**Issue by tolking** [vuejs/vitepress#168]
**Describe the bug**
The `actionLink` in [HomeHero.vue](https://github.com/vuejs/vitepress/blob/master/src/client/theme-default/components/HomeHero.vue#L15) missing $withBase, 

**Expected behavior**
It should configure the base path like other links

**System Info**
- vitepress version: 0.9.0

**Comment by kiaking** [comment]
Good catch! Thanks. We should add it.
