### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by LouisMazel** [vuejs/vitepress#1681]
### Describe the bug

Hey, 

It's not a bug report, just a question.

How to install with a module who's use browser features (document.querySelectorAll) with `ctx.app.use()` on client side ? 

I can't find the way in the documentation. In VuePress, we can use the variable `__VUEPRESS_SSR__`, do you something similar in VitePress ? 

N.B: It's works fine with the dev serve but fail on build time

## In VuePress

`docs/.vuepress/client.ts`

```ts
import { defineClientConfig } from '@vuepress/client'
import { clientModule } from 'lib'

export default defineClientConfig({
  enhance: async ({ app, router }) => {
    if (!__VUEPRESS_SSR__) {
      app.use(clientModule)
    }
  }
})
```

## In VitePress 

`docs/.vitepress/theme/index.ts`

```ts
const theme: typeof DefaultTheme = {
  ...DefaultTheme,
  enhanceApp({ app }) {
    app.use(clientModule) // It's doesn't works 😑
  },
}
```

### Reproduction

-

### Expected behavior

Be able to build the app with client

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 314.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 101.0.1
    Safari: 15.6.1
  npmPackages:
    vitepress: ^1.0.0-alpha.30 => 1.0.0-alpha.30
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Might wanna try: `if (inBrowser)` -- `import { inBrowser } from 'vitepress'`. It is essentially same as checking if `typeof document !== 'undefined'`.

**Comment by LouisMazel** [comment]
Thanks @brc-dd ! 

It's working fine !
