### ISSUE TITLE
Locale Config: Specify the path of the homepage on the logo

### ISSUE THREAD

**Issue by PierW** [vuejs/vitepress#1682]
### Describe the bug

If we have a multilingual project the path inside the href attribute for logo element doesn't change!
For example if I try to change from italian to english I have always: ` href="/"` when I expect to find `href="/en/`
For Vuepress V2 we have the ["home" settings](https://v2.vuepress.vuejs.org/reference/default-theme/config.html#home) .  But for Vitepress?

### Reproduction

1) Create a multilingual project.
2) Click on the logo link

### Expected behavior

Redirect to the respective locale.

### System Info

```shell
Macbook Pro M2, Chrome
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Multilingual projects are not yet supported. Track #631.

**Comment by PierW** [comment]
@brc-dd I think that we can close this issue, from yesterday the Pr was merged! 🚀🎉
 In these days I will check if it's works fine.

**Comment by brc-dd** [comment]
Yeah sure, just create a new one if something appears to be broken. 🙌
