### ISSUE TITLE
How can I change the url of the logo a tag?

### ISSUE THREAD

**Issue by 22289d** [vuejs/vitepress#1683]
I am using VitePress for docs and I want the logo to link to my main site, not back to the docs. There does not appear to be any setting for that in App Configs or Theme Configs. I've tried changing it in index.html but it just gets overwritten when I run build.

How can I accomplish this?

I'd also suggest this as a feature (probably in App Configs). I'm sure others will/would/do want it. For an open source project, going back to the docs makes a lot of sense but for a business, you often want people on your main site and don't want friction getting them there.

**Comment by cijiugechu** [comment]
Maybe you can try [this function](https://vitepress.vuejs.org/config/app-configs#transformhtml) , find and replace the link what you want.
