### ISSUE TITLE
Using vue in markdown on demand

### ISSUE THREAD

**Issue by liuliangsir** [vuejs/vitepress#1684]
### Is your feature request related to a problem? Please describe.

As the title above says, I would like to disable all vue features inside the pure markdown file and compile a markdown file to html file with no error since the compiler might assume some syntaxes are vue-specific syntax and try to compile with vue compiler, which might cause a build error like fenced code blocks with a unknown language.

### Describe the solution you'd like

Vitepress allows user to decide if disable vue compiler with pure markdown file and compile that markdown file with a standard markdown compiler. 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> which might cause a build error like fenced code blocks with a unknown language

This will happen even if we allow a way to disable Vue parsing. The language highlighter ([shiki](https://github.com/shikijs/shiki)) will throw that error.

**Comment by yyx990803** [comment]
The Vue features are not mixed with the Markdown parsing - it's applied **after** the markdown file is already compiled into HTML. It also cannot be avoided because we need to compile page chunks for runtime loading.
