### ISSUE TITLE
404 error when clicking link to public

### ISSUE THREAD

**Issue by samestep** [vuejs/vitepress#1685]
### Describe the bug

When you click a link from a VitePress-generated page to a `public` page on the same site, VitePress gives a 404 error unless the page is reloaded or opened in a new tab.

### Reproduction

Create a VitePress project with these contents.

`index.md`:

```markdown
---
layout: home
hero:
  actions:
    - text: foo
      link: /foo.html
---
```

`public/foo.html`:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    <p>Hello, world!</p>
  </body>
</html>
```

Then run `npx vitepress dev`, open http://localhost:5173/, and click on the green "foo" button that appears. VitePress gives a 404 error page. Reload the page, and the correct HTML page should appear with the contents "Hello, world!"

Go back to http://localhost:5173/, and this time open the green "foo" button's link in a new tab. Observe that the page is loaded correctly with no 404.

### Expected behavior

VitePress should load the page correctly when clicking the link to open it in the current tab.

### System Info

```
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 277.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 90.0
    Safari: 16.1
  npmPackages:
    vitepress: ^1.0.0-alpha.30 => 1.0.0-alpha.30
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I am afraid this won't be possible as the router intercepts all inbound links. You'll need to make that link external (use absolute URL for that).

**Comment by samestep** [comment]
@brc-dd Good to know, thanks! Would you be open to accepting a PR adding support for `pathname://`?

**Comment by samestep** [comment]
I just realized that VitePress has an `mpa` option, which fixes this issue for `build`/`preview`, albeit not for `dev`:

https://github.com/vuejs/vitepress/blob/421e5ce5e60e18c79831203559271ce000e5d4f5/src/node/config.ts#L65-L69
