### ISSUE TITLE
The reactivityTransform attribute of the vue plugin is not supported

### ISSUE THREAD

**Issue by zz541843** [vuejs/vitepress#1688]
### Describe the bug

I wanted to use the vue plugin's reactivityTransform in vitepress, but it was configured to get an error

Error:
[plugin:vite:vue] At least one <template> or <script> is required in a single file component.

### Reproduction

export default defineConfig({
    plugins: [
        vue({
            reactivityTransform: true
        }),] 
})

### Expected behavior

.

### System Info

```shell
"vitepress": "1.0.0-alpha.30",
"vue": "^3.2.45",
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yyx990803** [comment]
Closing as stale. Reactivity Transform is deprecated. But to configure Vue behavior in VitePress, use the `vue` config option instead: https://vitepress.dev/reference/site-config#vue
