### ISSUE TITLE
Build: window is undefined

### ISSUE THREAD

**Issue by haiting** [vuejs/vitepress#1689]
### Describe the bug

- I have a plguin containe a js file `/lib/utils/storageEventHandler.js`
```
const { location } = window;
const systemId = (config) => {
  return `${location.protocol}-${location.hostname}-${location.port}-${config?.name || systemConfig?.name}`;
};

export { systemId }
```
- use the above function in `components/test/index.vue`
- use the component in docs 
- run build that will show error:
```
build error:
ReferenceError: window is not defined
```

### Reproduction

none

### Expected behavior

no error on build

### System Info

```shell
"vitepress": "^1.0.0-alpha.31",
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Yes, because when during the build, the code runs on node so there's no `window` object.

You must import that code inside `onMounted` hook, or wrap the component that uses the code with in `ClientOnly` component 👍
