### ISSUE TITLE
Build: navigator is not defined

### ISSUE THREAD

**Issue by haiting** [vuejs/vitepress#1690]
### Describe the bug

- There is a third-party plugin:  `tinymce` in my component
- In `/node_modules/.pnpm/tinymce@5.10.7/node_modules/tinymce/tinymce.js` has these code:
```
var userAgent = navigator.userAgent;
```
- run build
- it will show error like these:
```
build error:
ReferenceError: navigator is not defined
```

### Reproduction

none

### Expected behavior

no error when use third-party plguin

### System Info

```shell
"tinymce": "^5.4.2",
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by tobidalhof** [comment]
It's not a bug, `navigator` is only available in browser.

Try to use it with the `inBrowser` const provided by `vitepress`:

```ts
import { inBrowser } from 'vitepress'

if (inBrowser) {
  // call tinymce here
}
```
