### ISSUE TITLE
Import Code Snippets Can you provide a relative path

### ISSUE THREAD

**Issue by tomiaa12** [vuejs/vitepress#1692]
### Is your feature request related to a problem? Please describe.

在文件目录过深时用@会不方便

### Describe the solution you'd like

<<< ./demo/index.ts

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sky124380729** [comment]
that what i need also

**Comment by yzqdev** [comment]
Good idea, maybe we could define our own alias like`@src`, `@theme`, `@guide`

**Comment by chgeo** [comment]
Would like to have this feature as well.

**Comment by Handpear** [comment]
any plans for release in future?
