### ISSUE TITLE
Allow customizing root for importing snippets

### ISSUE THREAD

**Issue by ctocode** [vuejs/vitepress#1698]
### Is your feature request related to a problem? Please describe.

use 
`
<<< @/../../ code_project/example/views/xxx/xx.vue
`
Import code snippet，Can customize @ path，

thank you very much indeed

### Describe the solution you'd like

`

import { defineConfig } from 'vitepress';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
const vitepressDir = dirname(fileURLToPath(import.meta.url));
export default defineConfig({
  vite: {
    resolve: {
      // Can it be defined here ??? 
      alias: {
        '@codePath': resolve(vitepressDir, '../../../code_project/example/views/')
      }
    }
  }
});
`
When in use
`
<<< @codePath/xxx/xx.vue
`

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It now supports relative format too. That should be sufficient for most of the cases.
