### ISSUE TITLE
Error when trying to use it with Feathers Client can't find \index

### ISSUE THREAD

**Issue by emersonbottero** [vuejs/vitepress#17]
on npm run dev
Error: EISDIR: illegal operation on a directory, read

Error: ENOENT: no such file or directory, stat 'T:\GitHub\TODO-APP\todo-vue\node_modules\socket.io-client\lib\index'

the file existis 'T:\GitHub\TODO-APP\todo-vue\node_modules\socket.io-client\lib\index.js
'
it doesn't recognize the file without the extensions...

**Comment by yyx990803** [comment]
This is not meant to be used yet.
