### ISSUE TITLE
Provides support for wiki-style internal links (e.g., [[link]]).

### ISSUE THREAD

**Issue by xu4wang** [vuejs/vitepress#1705]
### Is your feature request related to a problem? Please describe.

I am trying to use vitepress as a personal note app.  Need a feature to easily add internal links among all the markdown files.

### Describe the solution you'd like

Support wiki style links.

Links are surrounded by double square brackets, and can contain either an optional "group name" (i.e., subfolder name), or optional link text after a single bar character, or any combination of these. For example:

- [[link]]: A plain link to a note in the current folder with the filename link.md
- [[groupname/link]]: A link to a note in a different folder (called groupname, one level up in the file system hierarchy), with the filename link.md
- [[groupname/link|link text]]: Any of the above two link styles, plus optional link text following the | character

### Describe alternatives you've considered

The alternative is using normal markdown link.  Wiki style links are more concise.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Use some plugin like https://www.npmjs.com/package/markdown-it-wikilinks

https://vitepress.vuejs.org/guide/markdown#advanced-configuration

**Comment by xu4wang** [comment]
> Use some plugin like https://www.npmjs.com/package/markdown-it-wikilinks
> 
> https://vitepress.vuejs.org/guide/markdown#advanced-configuration

thanks. the plugin is tested and it works like a charm.  ;-)
