### ISSUE TITLE
Expose vitepress user config to vite plugins

### ISSUE THREAD

**Issue by emersonbottero** [vuejs/vitepress#1706]
### Describe the bug

[Resolved config](https://github.com/emersonbottero/vitepress-plugin-search/blob/80a33d0e3c34e94abb73f3491233c97d7756f924/src/index.ts#L32) does not have srcExclude in it.

It is needed in my search plugin since I'm adding in the search index documents that should be excluded

### Reproduction

log the resolved config in the plugin mentioned above.

### Expected behavior

I should be able to get this settings in the plugin pipeline.

### System Info

```shell
> playground@1.0.0 serve
  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 9.15 GB / 15.92 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 108.0.5359.125
    Edge: Spartan (44.22621.1037.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-alpha.30 => 1.0.0-alpha.30
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That resolved config is actually Vite's one:

```ts
import { defineConfig } from 'vitepress';

export default defineConfig({
  vite: {
    // @ts-ignore
    foo: 'bar',

    plugins: [
      {
        name: 'test',
        configResolved(config) {
          // @ts-ignore
          console.log(config.foo); // prints bar
        },
      },
    ],
  },
});

```

**Comment by emersonbottero** [comment]
how can I access srcExclude in an vite plugin for vitepress?

**Comment by brc-dd** [comment]
You'll probably need to ask users to put that option in the vite field (or vite.config), or maybe directly accept it as an option to your plugin?
