### ISSUE TITLE
The content of the Badge component's text property is displayed in the outline header

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#1714]
### Describe the bug

![image](https://user-images.githubusercontent.com/25446948/208357493-c8c34e63-1290-461d-afe8-9408feed727d.png)

### Reproduction

N/A

### Expected behavior

N/A

### System Info

```shell
N/A
```

### Additional context

N/A

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I thought this was the expected behavior 😅. Might wanna give an option to disable this.
