### ISSUE TITLE
 No language registration for protobuf

### ISSUE THREAD

**Issue by yordis** [vuejs/vitepress#1717]
### Describe the bug

I can not use `protobuf` as the markdown code block code.

Example:

```md
  
  ```protobuf
    package google.rpc;
  ...

```

### Reproduction

1. Clone https://github.com/straw-hat-team/adr repository
2. Change branch to `univeral-error`
3. Run `yarn docs:dev`
    1. In case I tmp changed it trying to figure it out
    2. Open `adrs/0129349218/README.md` file
    3. Search for `package google.rpc;`
    4. Add `protobuf` as the language mode for the code section
5. Notice the error.

### Expected behavior

One or Many of the following:

- Add official support for `protobuf`
- Add documentation about turning off the issue
- Add documentation about adding support manually if possible

### System Info

```shell
System:
    OS: macOS 12.4
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.asdf/installs/nodejs/18.12.1/bin/node
    Yarn: 3.3.0 - ~/.asdf/installs/nodejs/18.12.1/bin/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.11.28.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 108.1.46.140
    Chrome: 108.0.5359.124
    Edge: 108.0.1462.54
    Firefox: 103.0.2
    Safari: 15.5
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Try using `proto` instead of `protobuf` in the fences.

**Comment by brc-dd** [comment]
Closing as stale.
