### ISSUE TITLE
[sidebar] Offer the possibility to expand a collapsible section if we are navigating to a children page

### ISSUE THREAD

**Issue by camilleterol** [vuejs/vitepress#1718]
When a section of the sidebar is set with collapsed to true, it is sometimes hard to understand that the page you are browsing is in this section when you have followed a link.

Would it be possible to have an option to expand a section if the active page is a children of the section ?
Maybe adding a new setting to collapsed for example `collapsed: unless-active` or something of the sort?

**Comment by brc-dd** [comment]
It's the default behavior if you have `collapsed: true`. There's a bug with it not working for nested children. Should be fixed by #1361.
