### ISSUE TITLE
Add lastUpdatedFS into PageData

### ISSUE THREAD

**Issue by xu4wang** [vuejs/vitepress#1723]
### Is your feature request related to a problem? Please describe.

It's necessary in some scenarios to have the File System timestamp of a specific document returned by the API.  For example to create a "Last Changes" Page, https://github.com/vuejs/vitepress/discussions/1720 .  File system time stamp is more suitable because it reflects the time the file is actually updated.

There is lastUpdated inside PageData which can be access via #1450, however the timestamp is based on git commit timestamp.

### Describe the solution you'd like

Add a field "lastUpdatedFS" in PageData, it will be controlled by the same configuration parameter of lastUpdated.

```ts
export const notFoundPageData: PageData = {
  relativePath: '',
  title: '404',
  description: 'Not Found',
  headers: [],
  frontmatter: { sidebar: false, layout: 'page' },
  lastUpdated: 0,
  lastUpdatedFS: 0
}
```

In markdownToVue.ts

```ts
    if (includeLastUpdatedData) {
      pageData.lastUpdated = await getGitTimestamp(file)
      //update 
      pageData.lastUpdatedFS = ......
    }

```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> File system time stamp is more suitable because it reflects the time the file is actually updated.

It's actually not. It'll be suitable only till you're working on your system. But as soon as you try to build and deploy your site, it won't work as the build pipeline will be cloning your branch which will set the fs timestamp to the time that git clone command is run, yielding same timestamp for every page.

**Comment by xu4wang** [comment]
> > File system time stamp is more suitable because it reflects the time the file is actually updated.
> 
> It's actually not. It'll be suitable only till you're working on your system. But as soon as you try to build and deploy your site, it won't work as the build pipeline will be cloning your branch which will set the fs timestamp to the time that git clone command is run, yielding same timestamp for every page.
> 
> We probably can allow fs as fallback when we cannot retrieve git timestamp (when the user has not committed anything).

If this is the case, shall we just redefine lastUpdated to use File System time.  since it's cheaper to get than git timestamp.
anyway the clone process will make them consistent.

and we get a nice to have by-product, in the developing system when the file is not committed, we can still have time for it.

**Comment by shelley-xl** [comment]
@brc-dd How to solve the problem that each page has the same timestamp？

**Comment by brc-dd** [comment]
> @brc-dd How to solve the problem that each page has the same timestamp？

Depends on how you're building your site. If using github actions you've to specify `depth: 0`, in checkout action, so that it fetches all the commits.
