### ISSUE TITLE
Inconsistency between development and packaging

### ISSUE THREAD

**Issue by sishen654** [vuejs/vitepress#1726]
### Describe the bug

When starting the server normally, the image can be detected and parsed by default
![image](https://user-images.githubusercontent.com/65691266/208959068-88f7cace-6998-4365-b406-9a3040b71401.png)
But, when i building, case like this:
![image](https://user-images.githubusercontent.com/65691266/208959326-d45c7ab5-45c1-4317-8c7b-b28ccb813247.png)
I want to know this case is normally?

### Reproduction

you can clone my repository: https://gitee.com/ma_zipeng/TS-Note.git, and input command:
```
# start server
yarn dev
# build
yarn build
```

### Expected behavior

can build normal like dev environment

### System Info

```shell
windows
node: v16.14.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
There was an issue earlier about this because of the asset URL getting encoded. But IIRC, we fixed it. Can you try using newer versions? (latest is alpha-33, you're on alpha-4).

**Comment by sishen654** [comment]
> There was an issue earlier about this because of the asset URL getting encoded. But IIRC, we fixed it. Can you try using newer versions? (latest is alpha-33, you're on alpha-4).

After updating the version, the problem is solved, thank you very much
