### ISSUE TITLE
Auto-sidebar mode

### ISSUE THREAD

**Issue by KraXen72** [vuejs/vitepress#1737]
### Is your feature request related to a problem? Please describe.

Currently, the sidebar has to be manually kept in-sync with the markdown folders. this offers great control, but is annoying, if i just want the sidebar to always reflect my folders with the files in them

### Describe the solution you'd like

a mode/flag on the sidebar where it would automatically generate depending on all the md files.
example folder structure:  
![image](https://user-images.githubusercontent.com/21956756/209484536-c78739b3-e7d6-4405-abd3-440b5286fc45.png)
example (desired sidebar):  
![image](https://user-images.githubusercontent.com/21956756/209484558-e86f9e2c-a367-4dec-be91-07e7661afaa8.png)
  
 i'd suggest, by default it takes all top level folders => categories and top level .md files in the folders => subheaders.
there could also be an option to specify a map/filter pass, for example to convert filenames separated with - to titles separated with space.  

### Describe alternatives you've considered

currently, i solved this by writing a generator script, but this is a thing many people would expect to be present by default, if the framework/ssg offers a sidebar.

my script: https://github.com/KraXen72/tech-support-wiki/blob/master/sidebar-generator.js

### Additional context

it was a pain trying to figure out for half an hour that vitepress does not indeed support automatic sidebar. 
also, it would be great to make it clearer that the `.vitepress` folder has to be inside of `docs`, struggled with that aswell

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by awbait** [comment]
the .vitepress folder doesn't have to be inside docs, change the startup script to `"dev": "vitepress dev"` and it will run from root directory

**Comment by Jimmylxue** [comment]
this can write an function to realization what you want it:

![example](https://github.com/Jimmylxue/blog/tree/master/docs/.vitepress/config)

```js
// config
const config = {
  // ...
  sidebar:getSliderBar()
  // ...
}
```

getSliderBar function:
```js
const fs = require('fs')
const path = require('path')
const { resolve } = path

export const scanDir = pathName => {
	const path = resolve(__dirname, `../../${pathName}`)
	return getMsg(path)
}

export const getMsg = path => {
	let res = fs.readdirSync(path).filter(item => !(String(item) === '.DS_Store'))
	if (res) {
		let arr = res.map(item => {
			if (String(item).endsWith('.md')) {
				return {
					text: item.split('.')[0],
					link: resolve(path, item),
				}
			} else {
				return {
					text: item.split('.')[0],
					items: getMsg(resolve(path, item)),
					collapsible: true,
				}
			}
		})
		arr = arr.map(item => {
			if (item.link) {
				item.link = translateDir(item.link)
			}
			return item
		})
		return arr
	} else {
		console.warn('无文章')
	}
}

/**
 *
 * @param {string} path
 * @returns
 */
function translateDir(path) {
	return path.replace(/\\/g, '/').split('docs')[1].split('.')[0]
}

// console.log("aaa", getMsg()[0]);
// module.exports = getMsg;

```

**Comment by KraXen72** [comment]
this is not ideal, because it dynamically generates the sidebar on-demain, making the whole site unable to be hosted as static on something like github pages. my script: https://github.com/KraXen72/tech-support-wiki/blob/master/sidebar-generator.js uses user's local node.js install to pre-generate the sidebar before pushing. however, it would be best if vitepress included this out of the box

**Comment by Akryum** [comment]
> because it dynamically generates the sidebar on-demain

That is incorrect, it happens during build time only, so it would be fine on a static hosting.

**Comment by basefas** [comment]
need this feature too

**Comment by brc-dd** [comment]
Duplicate of #1297
