### ISSUE TITLE
Logo theming in CSS

### ISSUE THREAD

**Issue by adinafxv** [vuejs/vitepress#1742]
### Is your feature request related to a problem? Please describe.

Logo theming - two images:
[see here](https://github.com/vuejs/vitepress/blob/257f9e68e947a603f9c3ef0df4be7b2afa79fbe7/types/default-theme.d.ts#L117) 

### Describe the solution you'd like

`<svg>` added directly to html, not within an `<image>` tag

- enables css manipulation of svg 
- for example users can define currentColor in the SVG and direct the theming in CSS

Still can support double-image solution for users who prefer not to change css

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can use the `home-hero-image` to add SVG or any other component there. Docs: https://vitepress.vuejs.org/guide/theme-introduction#layout-slots
