### ISSUE TITLE
打包部署到nginx后，进入某个模块，刷新页面后mackdown空白。或者直接进入某个模块也是空白。

### ISSUE THREAD

**Issue by ufodba** [vuejs/vitepress#1746]
### Describe the bug

由其他位置跳转进入时，显示OK
![image](https://user-images.githubusercontent.com/23053322/210048788-39d28c23-c265-4119-968c-7fa17895a0ff.png)

刷新此链接显示空白
![image](https://user-images.githubusercontent.com/23053322/210048697-a848001c-a5b3-4077-9fa4-29c9485d8241.png)

### Reproduction

1. 打包部署到nginx
2. 进入某个模块
3. 刷新页面后mackdown空白

### Expected behavior

正常显示

### System Info

```shell
"vitepress": "^1.0.0-alpha.33"
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
There are probably hydration issues with your code. We can't help without having a minimal reproducible example.

**Comment by Jimmylxue** [comment]
感觉有可能是代码那块的配置的问题， 你可以把你的代码仓库发出来看看

**Comment by QC2168** [comment]
可能是路径没有对上

**Comment by yyrc** [comment]
一、路径可能没对上。
二、是不是开启了cleanUrls: true

**Comment by yyx990803** [comment]
Closing as stale
