### ISSUE TITLE
Unencoded header links didn't work.

### ISSUE THREAD

**Issue by garmede** [vuejs/vitepress#1749]
### Describe the bug

Unencoded header links (with CJK characters) do not work.

I remember it worked fine in VuePress, but it doesn't work in VitePress.

### Reproduction

```markdown
# Header

This link [한글](#한글-한글) is not work!

This link [한글](#%E1%84%92%E1%85%A1%E1%86%AB%E1%84%80%E1%85%B3%E1%86%AF-%E1%84%92%E1%85%A1%E1%86%AB%E1%84%80%E1%85%B3%E1%86%AF)  is work.

...

## 한글 한글

...
```

### Expected behavior

Creating links with native headers should also work.

### System Info

```shell
System:
  OS: Windows 10 10.0.22621
  CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
  Memory: 46.05 GB / 63.92 GB
Binaries:
  Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
  npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
  Internet Explorer: 11.0.22621.1
npmPackages:
  vitepress: 1.0.0-alpha.34 => 1.0.0-alpha.34
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Probably has something to do with your browser. We don't manually handle the URL fragments. For me, both are working fine on Chrome 108: https://stackblitz.com/edit/vite-kdiy46?file=docs%2Fexample.md

https://user-images.githubusercontent.com/40380293/210208648-de04ebe8-8c07-4f5b-b9a5-e0eebca5fb09.mp4

**Comment by garmede** [comment]
In the html source I built, the address is encoded differently as follows.

```html
<!-- [한글](#한글-한글) to -->
<a href="#%ED%95%9C%EA%B8%80-%ED%95%9C%EA%B8%80">한글</a>

<!-- [한글](#%E1%84%92%E1%85%A1%E1%86%AB%E1%84%80%E1%85%B3%E1%86%AF-%E1%84%92%E1%85%A1%E1%86%AB%E1%84%80%E1%85%B3%E1%86%AF) to -->
<!-- This address was encoded by copy pasting from the browser address bar. -->
<a href="#%E1%84%92%E1%85%A1%E1%86%AB%E1%84%80%E1%85%B3%E1%86%AF-%E1%84%92%E1%85%A1%E1%86%AB%E1%84%80%E1%85%B3%E1%86%AF">한글</a>
```

**Comment by brc-dd** [comment]
I'm not completely sure, but there is an issue with the text in your first link. Copy paste this: `#한글-한글` there. Both are looking same to me after decoding, but JS tells there is a difference. I don't speak Korean, so not sure what's that.

**Comment by garmede** [comment]
Exactly! Both are exactly the same Hangul, but their Unicode is different. Shorter is better.
Unfortunately, VitePress handles Korean characters on the long side.

![image](https://user-images.githubusercontent.com/2133201/210217572-68300a91-e32f-4ec0-9acf-1be35b473abf.png)
