### ISSUE TITLE
Ensure `.html` extension in rendered nav links

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vitepress#175]
Making rendered nav link `href` end with `.html` can make the resulting html work without JS.

Netlify handles `.html`-less URLs so http://vitepress.vuejs.org/ already works without JS, but other static hosting services like Vercel doesn't do that.

**Comment by nico-bachner** [comment]
From what I understand, the browser doesn't show `index.html` files in the url (`https://vitepress.vuejs.org/index.html` is shown as `https://vitepress.vuejs.org`.

In that case, could we solve this issue by enforcing a naming convention that all files without a `.html` extension in the url should be named `index.md` in their respective directory?
