### ISSUE TITLE
The requested module does not provide an export named 'createMarkdownRenderer'

### ISSUE THREAD

**Issue by TotomInc** [vuejs/vitepress#1752]
### Describe the bug

Hi, I am trying to import and use a custom Markdown renderer inside a component but it looks like the `createMarkdownRenderer` function is not exported.

```
Uncaught SyntaxError: The requested module '/@fs/Users/xyz/.github/xyz/node_modules/vitepress/dist/client/index.js?v=61ac765b' does not provide an export named 'createMarkdownRenderer' (at EndpointExample.vue:2:10)
```

However, according to TypeScript types exported from VitePress, `createMarkdownRenderer` should be available for use.

### Reproduction

```vue
<script setup lang="ts">
import { createMarkdownRenderer } from "vitepress";

const props = defineProps<{
  requests: { type: string; content: string; }[];
  response: string;
}>();

// `createMarkdownRenderer` is not exported from vitepress.
const md = await createMarkdownRenderer(".");
const response = md.render(props.response);
</script>
```

### Expected behavior

The function `createMarkdownRenderer` should be exported as it is available from TypeScript types. If it should not, then remove the `createMarkdownRenderer` type export.

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 116.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome: 108.0.5359.124
    Firefox: 103.0.2
    Safari: 16.0
```

### Additional context

Please note that I am trying to create a custom `markdownRenderer` so that I can create a code render from my component props.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It is a server side function. It won't be accessible inside a Vue component.

**Comment by TotomInc** [comment]
Thanks for your answer.

Any ideas on how can I use this server-side API on an SSR component with VitePress?

**Comment by brc-dd** [comment]
You can use static data imports. Basically, create a file ending with `.data.ts`, then inside it you can have content like this: https://github.com/vuejs/vitepress/blob/main/__tests__/e2e/static-data/static.data.ts Then if you import data from it, it will be embedded as JSON during build. (https://github.com/vuejs/vitepress/issues/794#issuecomment-1230986480, https://github.com/vuejs/vitepress/discussions/1291#discussioncomment-3989793)
