### ISSUE TITLE
When using monorepo, can `Import Code Snippets` import files under other package?

### ISSUE THREAD

**Issue by sky124380729** [vuejs/vitepress#1758]
### Is your feature request related to a problem? Please describe.

As introduced on the official website, `Import Code Snippets`:

> The value of @ corresponds to the source root. By default it's the VitePress project root, unless srcDir is configured.

 So if it is a monorepo project, how to import snippets from other projects?

![image](https://user-images.githubusercontent.com/23203328/210530672-6e1c9969-9fb8-4ecf-a4a2-a0e9ecbdcd70.png)

### Describe the solution you'd like

i don't know

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not sure, but have you tried something like: `@/../../vue-next-mini/test.js` ?

**Comment by sky124380729** [comment]
I tried it as you said and it really worked! But will there be a better configuration to support this in the future, it doesn't look very friendly right now

**Comment by sky124380729** [comment]
> Not sure, but have you tried something like: `@/../../vue-next-mini/test.js` ?

I tried it as you said and it really worked! But will there be a better configuration to support this in the future, it doesn't look very friendly right now

**Comment by brc-dd** [comment]
Might wanna track #1698.
