### ISSUE TITLE
Navbar is not sticky in mobile breakpoint

### ISSUE THREAD

**Issue by maxkrieger** [vuejs/vitepress#1764]
### Describe the bug

The responsive mobile layout on `[v1.0.0-alpha.35](https://github.com/vuejs/vitepress/releases/tag/v1.0.0-alpha.35)` (and possibly earlier) does not have a sticky navbar. Only the desktop layout does.

### Reproduction

* Visit any vitepress site on desktop. Right now it occurs on the official one (https://vitepress.vuejs.org/). Scroll down. Observe that the navbar is sticky (stays on top) and the content overflows beneath.
* Resize the window or enter a browser's mobile simulator
* Scroll down again. Notice that the new layout does not have a sticky navbar.

### Expected behavior

The mobile version of the navbar should be sticky. It may need more `overflow:hidden` rules in the parents.

### System Info

```shell
Chrome on MacOS, Safari on iOS
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's a design choice (only secondary nav - menu/return to top is sticky). How's that a bug? Feel free to override CSS if you think sticky navbar will suit your needs best.

**Comment by maxkrieger** [comment]
@brc-dd On the homepage layout, the primary nav is effectively the secondary nav since it wouldn't have a secondary nav otherwise. Note that the [react docs](https://reactjs.org/) have a sticky main nav.
