### ISSUE TITLE
Haven't the markdown.anchor option been supported yet?

### ISSUE THREAD

**Issue by Sunny-117** [vuejs/vitepress#1765]
### Describe the bug

I configure the anchor level of markdown, which does not take effect

### Reproduction

I configure the anchor level of markdown, which does not take effect

### Expected behavior

I configure the anchor level of markdown, which does not take effect
<img width="265" alt="image" src="https://user-images.githubusercontent.com/73089592/210925066-a8c5b645-0e09-4410-a575-a062d4aeff2f.png">

### System Info

```shell
macOS chrome
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to configure outline for that not mardown.anchor. Refer https://vitepress.vuejs.org/config/theme-configs#outline

**Comment by Sunny-117** [comment]
> You need to configure `themeConfig.outline` for that not `mardown.anchor`. Refer https://vitepress.vuejs.org/config/theme-configs#outline

thank you very much

**Comment by webpon** [comment]
666, love you
