### ISSUE TITLE
Cannot find package 'docs' imported from xxx/docs/.vitepress/config.ts.timestamp-1672993082912.mjs

### ISSUE THREAD

**Issue by Plasticine-Yang** [vuejs/vitepress#1768]
### Describe the bug

When I extract paths to a typescript enum in a single file and use it to define sidebar config, it is not work.

### Reproduction

1. define routes in `docs/.vitepress/routes.ts`

```ts
// typescript enum
export enum ROUTES {
  FOO = '/pages/foo/',
}

// or normal object
export const ROUTES = {
  FOO: '/pages/foo/,
}
```

2. define sidebar in `docs/.vitepress/sidebar/index.ts`

```ts
import { DefaultTheme } from 'vitepress'

import { ROUTES } from '../routes'

import { typeChallenges } from './type-challenges'

export const sidebar: DefaultTheme.Config['sidebar'] = {
  [ROUTES.FOO]: [
    {
      text: 'foo',
      items: [
        {
          text: 'foo-item',
          link: `${ROUTES.FOO}easy`,
        },
      ],
    },
  ],
}
```

3. `docs/.vitepress/config.ts`

```ts
import { defineConfig } from 'vitepress'
import { sidebar } from './theme/sidebar'

export default defineConfig({
  themeConfig: {
    sidebar,
  },
})
```

### Expected behavior

I want the dev server to run normally.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 5.15 GB / 7.70 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    vitepress: 1.0.0-alpha.35 => 1.0.0-alpha.35
```

### Additional context

The error info

![image](https://user-images.githubusercontent.com/63829979/210962670-0e682f04-8bec-4b7e-8cf8-a836c80a8207.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`import { ROUTES } from '../routes'`

**Comment by Plasticine-Yang** [comment]
Sorry, I write the demo with a wrong import path, but in my project, it is right path.

It still can not run dev server normally, please reopen the issue.

**Comment by brc-dd** [comment]
What's the actual path? Use relative paths or define base/alias in tsconfig inside docs directory.

**Comment by Plasticine-Yang** [comment]
The actual path:

ROUTES is defined in `docs/.vitepress/routes.ts`, sidebar is defined in `docs/.vitepress/sidebar/index.ts`.

I have changed all paths to relative paths, but it still not work.

**Comment by brc-dd** [comment]
What's the error now? It won't be `docs` package not found unless you have some import like `from 'docs...'`,

**Comment by Plasticine-Yang** [comment]
All right, I missed a place and forgot to change it to a relative path. It's ok now... :(
