### ISSUE TITLE
CloudFlare Deploys Disfunctional

### ISSUE THREAD

**Issue by sosensible** [vuejs/vitepress#1769]
### Describe the bug

We are working on an internal knowledgebase with VitePress, and deploying internally works great. But if we pass the resource as an protected application to CloudFlare Tunnels or if we deploy the app to a CloudFlare pages (web site hosting) the home layout appears twice and the links don't clear content before loading new content.

### Reproduction

Deploy with CloudFlare Tunnel or to CloudFlare Pages.

### Expected behavior

To work like it does when we run it local in dev, like it does when we build and preview, like it does when we use GitHub pages. Works everywhere but CloudFlare.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 4.66 GB / 39.79 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.31 => 1.0.0-alpha.35
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Do you have HTML minification enabled on Cloudflare? If yes, disabling it should work.

**Comment by sosensible** [comment]
Totally awesome, thanks. :)
