### ISSUE TITLE
关于 VitePress 中的 markdown 的脚注、外部链接和任务列表的问题

### ISSUE THREAD

**Issue by vanchKong** [vuejs/vitepress#1775]
### Is your feature request related to a problem? Please describe.

- 对照 markdown 基础语法，发现 VitePress 不支持 脚注 功能
- 另外有个问题，关于 [External Links](https://vitepress.vuejs.org/guide/markdown#external-links)，外部链接不需要尖括号即可直接转换成可跳转链接，如果我想禁用此链接仅作文本展示，只能通过把链接包裹在 ` `` ` 当中，想知道 VitePress 是如何解决这件事的。
- markdown 的任务列表是否有样式优化的计划
:vulcan_salute:

### Describe the solution you'd like

- 是否会支持 markdown 脚注
- 解答 External Links 的问题
- 解答关于 任务列表 的问题
:vulcan_salute:

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [x] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by King-of-Infinite-Space** [comment]
To enable footnotes, I use the following option in `config.js` 
(see https://vitepress.vuejs.org/config/app-configs#markdown for more options)
```js
import mdFootnote from "markdown-it-footnote"

export default {
  markdown: {
    config: (md) => {
      md.use(mdFootnote)
    },
  },
}
```

**Comment by vanchKong** [comment]
> 

wow, it works!
同样可以使用插件[markdown-it-task-lists](https://github.com/revin/markdown-it-task-lists) 来实现 Github-style 的任务列表。
谢谢你的回复！

对此我还有个疑问，vitepress 是自带 markdown-it，而不需要在package.json中单独安装的吧？只需要在用到相关插件的时候使用插件就可以了，是这样吗？

---
剩下的问题
- ~~是否会支持 markdown 脚注~~
- 解答 External Links 的问题
- ~~解答关于 任务列表 的问题~~

**Comment by King-of-Infinite-Space** [comment]
是的，只安装插件即可。（只要插件对应的markdown-it版本与vitepress使用的版本兼容）

**Comment by kiaking** [comment]
Sorry, it's hard for me t understand this issue because of the language barrier 😅 Is this solved...?

**Comment by awxiaoxian2020** [comment]
你的 External Links 的问题没有描述清楚

**Comment by dragon-fish** [comment]
关于你的第二个问题，试试在 config.js 里

```
export default {
  markdown: {
    linkify: false,
  },
}
```

供参考：https://github.com/markdown-it/markdown-it#init-with-presets-and-options
