### ISSUE TITLE
Provide comments integration with giscus

### ISSUE THREAD

**Issue by stafyniaksacha** [vuejs/vitepress#1776]
### Is your feature request related to a problem? Please describe.

This is a common need to have user feedback directly on documentation pages, comments are a good candidate for this.

Knowing that vitepress already integrated third party like algolia search, why not integrating one for this.

Giscus have a pretty nice solution by syncing comments with discussions on a github repository and it integrate well with vue.

- https://github.com/giscus/giscus
- https://github.com/giscus/giscus-component/tree/main/vue

### Describe the solution you'd like

We could integrate it on default theme and enable it if the user has configured it

You can preview it on: https://strapi-community.github.io/strapi-plugin-rest-cache/guide/
> Source: https://github.com/strapi-community/strapi-plugin-rest-cache/blob/main/docs/.vitepress/theme/Layout.vue#L12-L28

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by aiktb** [comment]
There are two bugs in the integration of Giscus and vitepress that have not been fixed, which can also be found on the website you provided:
1. When entering a doc page with a comment area from a home without a comment area, there is a possibility that the comment area cannot be fully displayed, and only a section can be displayed.
2. When jumping from a doc with a comment area to another doc, the comments will not be refreshed, and the document of the previous doc will be displayed.
Both of these issues can be resolved by refreshing the page.
In addition, I did not see these problems on gitalk.

**Comment by aiktb** [comment]
Yesterday I happened to see a vitepress using giscus, and there was no problem, so I found a solution: don't use giscus-vue, please use **_native giscus_**, don't know why, but this will solve the problem.
```vue
<script setup>
import {useData} from 'vitepress';

const {title} = useData()
</script>

<template>
  <div class="comments">
    <component
        :is="'script'"
        :key="title"
        src="https://giscus.app/client.js"
        data-repo=" ...... "
        data-repo-id=" ...... "
        data-category=" ...... "
        data-category-id=" ...... "
        data-mapping="title"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-lang="en"
        data-theme="transparent_dark"
        data-loading="eager"
    />
  </div>
</template>
```

**Comment by brc-dd** [comment]
Should be implemented via third-party plugins. And it's already possible to implement it via custom components. Won't be adding this to default theme for now.
