### ISSUE TITLE
vp-raw cannot isolate style conflicts generated by v-doc classes

### ISSUE THREAD

**Issue by isolcat** [vuejs/vitepress#1777]
### Describe the bug

When I customize a link component and introduce it into vitepress, the `vp-doc` class generates a style override on my custom style, causing my style to not display properly:
![image.png](https://ldbbs.ldmnq.com/bbs/topic/attachment/2023-1/ddd59cc8-70f0-4357-a325-18740cb25373.png)
I've tried `vp-raw` for style isolation, but it still doesn't display my custom styles properly
![image.png](https://ldbbs.ldmnq.com/bbs/topic/attachment/2023-1/a73a4f2a-beb0-485a-bd54-1c7cfe1f423d.png)
I don't know how to solve this style override problem, which has been bothering me for a long time

### Reproduction

This is my custom link component:
```tsx
import { defineComponent, PropType, ref } from "vue";
import "uno.css";

export type IType = 'default' | 'primary' | 'success' | 'warning' | 'danger'| 'info'
export type IColor = 'black' | 'blue' | 'green' | 'yellow'| 'red' | 'gray'
export const props = {
  type: {
    type: String as PropType<IType>,
    default: "default",
  },
  color: {
    type: String as PropType<IColor>,
    default: "black",
  },
  plain: {
    type: Boolean,
    default: true,
  },
  href: {
    type: String,
    required: true,
  },
} as const;

export default defineComponent({
  name: "CLink",
  props,
  setup(props, { slots }) {
        return () => (
      <a
      class={`
        text-${props.plain ? props.color + "-500" : "white"}
        hover:text-${props.color}-400
        cursor-pointer
        text-lg
        hover:text-white
        transition duration-300 ease-in-out transform hover:scale-105
        mx-1
        decoration-none
        `}
      href={props.href}      
    >
      {slots.default ? slots.default() : 'Link'}
    </a>
    );    
  },
});
```

Here's my demo code from the documentation：
```vue
<div class="vp-raw">
       <CLink href="#" class="primary" color="blue">Primary Link</CLink>
       <CLink href="#" type="success" color="green">Success Link</CLink>
       <CLink href="#" type="warning" color="yellow">Warning Link</CLink>
       <CLink href="#" type="danger" color="red">Danger Link</CLink>
       <CLink href="#" type="info" color="gray">Info Link</CLink>
</div>
```

### Expected behavior

I want to be able to display the style of my components properly, in fact I can be sure that the `vp-doc` generated style override, I delete this class by manipulating the DOM and then the style can be displayed normally, but this will make the other functions of vitepress failure, I want to be able to display the style of the component without affecting vitepress

### System Info

```shell
{
    "name": "catisol-ui",
    "version": "0.9.1",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "vitest",
        "build": "vite build",
        "dev": "vite",
        "docs:dev": "vitepress dev docs",
        "docs:build": "vitepress build docs",
        "docs:serve": "vitepress serve docs"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "@iconify-json/ic": "1.1.4",
        "@vitejs/plugin-vue": "3.0.3",
        "@vitejs/plugin-vue-jsx": "2.0.0",
        "@vue/test-utils": "2.0.2",
        "happy-dom": "6.0.4",
        "postcss": "^8.4.21",
        "postcss-prefix-selector": "^1.16.0",
        "unocss": "0.45.6",
        "vite": "3.0.7",
        "vitepress": "v1.0.0-alpha.31",
        "vitest": "0.21.1"
    },
    "maintainers": [
        "isolcat"
    ],
    "dependencies": {
        "@unocss/vite": "^0.45.13",
        "vue": "3.2.37"
    }
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to add postcss config too for `vp-raw` to work: https://vitepress.vuejs.org/guide/markdown#raw

**Comment by isolcat** [comment]
> You need to add postcss config too for `vp-raw` to work: https://vitepress.vuejs.org/guide/markdown#raw
> 
> Based on your first image, it looks like you haven't added it properly.

I actually added the postcss config ：
![image.png](https://ldbbs.ldmnq.com/bbs/topic/attachment/2023-1/1b79cbde-bfff-4033-9f06-f62bc712208d.png)
But it seems that `vp-raw` has no effect, is there a problem somewhere?

**Comment by brc-dd** [comment]
Have you tried rerunning `vitepress dev` after adding that file? If it's possible, can you share a repo/stackblitz link ([vitepress.new](https://vitepress.new)) where we can test that? For some reasons, that postcss config isn't working.

**Comment by isolcat** [comment]
> Have you tried rerunning `vitepress dev` after adding that file? If it's possible, can you share a repo/stackblitz link ([vitepress.new](https://vitepress.new)) where we can test that? For some reasons, that postcss config isn't working.

I'm sorry, I just tried restarting vscode and vitepress once and it worked, thank you very much for your help, the problem is solved
