### ISSUE TITLE
ClientOnly does not work

### ISSUE THREAD

**Issue by wuchaoxin** [vuejs/vitepress#1779]
### Describe the bug

I want to use `vue-cropper@next`, but I find that this component is not very friendly to SSR. I checked the issue and found that I need to modify the vite configuration 'ssr noExternal' and use the 'ClientOnly' component.

When I modified the vite configuration, the Named export 'VueCopper' not found error disappeared.But I found that the `ClientOnly` did not work when I used it, and I got an error `ReferenceError: Blob is not defined`.

### Reproduction

Go to the link below and run `npm run docs:build`
https://stackblitz.com/edit/vite-kr5dqn?file=docs%2Findex.md,docs%2F.vitepress%2Fconfig.ts

### Expected behavior

Can be packaged successfully

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 264.83 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.3
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
This is probably because the cropper is using `Blob` directly so it runs before the VitePress can apply `<ClientOnly>` 🤔  Can you give me the link to the actual libs source code?

**Comment by brc-dd** [comment]
Dynamically import that library on mount and use it. It should work. Also, might wanna try `vue-cropperjs` instead. It seems to have ssr support and is more popular.

**Comment by wuchaoxin** [comment]
Thank you for your reply.

The actual libs source code address is [vue-cropper](https://github.com/xyxiao001/vue-cropper).

As mentioned above, this problem can be solved through dynamic import.

```
import { computed, defineAsyncComponent } from 'vue'
import { inBrowser } from 'vitepress'

const Cropper = computed(() => {
  if (inBrowser) {
    const vueCropper = defineAsyncComponent(() => import('vue-cropper/lib/vue-cropper.vue'))
    return vueCropper
  } else {
    return null
  }
})
```
