### ISSUE TITLE
sidebar: 'auto' doesn't create sidebar

### ISSUE THREAD

**Issue by kdankert** [vuejs/vitepress#178]
**Describe the bug**
Using sidebar auto doesn't produce sidebar at all, even it is considered to be a valid option in https://github.com/vuejs/vitepress/blob/master/src/client/theme-default/config.ts.

**To Reproduce**
1. Create a new project
2. Configure vitepress to use sidebar: 'auto' in .vitepress/config.js
3. Create some pages with headings
4. Start dev server

**Expected behavior**
A sidebar should be auto generated using the headings provided in the markdown files

**System Info**
- vitepress version: v0.9.1
- vite version: v1.0.0-rc.13
- Node version: v15.3.0
- OS version: macOS 10.15.7 (19H2)

**Comment by impys** [comment]
Sidebar object is required.Check out https://github.com/vuejs/vitepress/blob/master/docs/.vitepress/config

**Comment by kiaking** [comment]
Yap this is bug. Sidebar is actually mounted, but it's hidden because at layout component it treats it as hidden.

```js
const showSidebar = computed(() => {
  const { frontmatter } = route.data
  const { themeConfig } = siteRouteData.value
  return (
    !frontmatter.home &&
    frontmatter.sidebar !== false &&
    ((typeof themeConfig.sidebar === 'object' &&
      Object.keys(themeConfig.sidebar).length != 0) ||
      (Array.isArray(themeConfig.sidebar) && themeConfig.sidebar.length != 0))
  )
})
```

So fixing this code, should correctly show the auto sidebar 🔥

**Comment by cloydlau** [comment]
Is this removed? I got a `TypeError: Cannot read properties of undefined (reading 'some')` with the following config:
```ts
sidebar: {
  'XXX': 'auto',
}
```
