### ISSUE TITLE
在内容里使用 {xxx} 就会报错

### ISSUE THREAD

**Issue by mrxu0** [vuejs/vitepress#1781]
### Describe the bug

版本："vitepress": "^1.0.0-alpha.35", 
里面没有多余的东西。就是按照官网https://vitepress.vuejs.org/guide/getting-started 走到了第三步。然后将 index.md 的内容添加了 {1}

![image](https://user-images.githubusercontent.com/28293069/211520935-e0dbe311-986d-4980-8be8-8ed69c5217ab.png)
![image](https://user-images.githubusercontent.com/28293069/211521022-6914acd4-7b57-41eb-b852-539bdec97e41.png)

### Reproduction

按照官网https://vitepress.vuejs.org/guide/getting-started 走到了第三步。然后将 index.md 的内容添加了 {1}

### Expected behavior

正常渲染 {1} 标签的内容

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 1.50 GB / 15.73 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.35 => 1.0.0-alpha.35
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by xu4wang** [comment]
这个原因猜测是markdown-it-attrs 没识别出来 1 是个什么attribute

vitepress有一个markdown-it插件，会把大括号里面的值作为属性给dom配置。 例如：
![image description](https://api.iconify.design/flag:ad-4x3.svg){width="250" height="250"}

如果大括号里面是个不识别的属性，就会报错。

**Comment by mrxu0** [comment]
> 

哦哦，原来是有扩展这个新语法的。那我查一下如何关掉吧，这里想作为普通的字符串来进行处理

**Comment by brc-dd** [comment]
> 哦哦，原来是有扩展这个新语法的。那我查一下如何关掉吧，这里想作为普通的字符串来进行处理

```ts
// .vitepress/config.ts

import { defineConfig } from 'vitepress'

export default defineConfig({
  markdown: { attrs: { disable: true } },
})
```
