### ISSUE TITLE
Internal server error: Element is missing end tag. Plugin: vite:vue

### ISSUE THREAD

**Issue by PuffMeow** [vuejs/vitepress#1784]
### Describe the bug

This is the error:

[vite] Internal server error: Element is missing end tag.    
  Plugin: vite:vue
  File: D:/桌面/学习笔记/doc/docs/rust/Rust基础/4.枚举.md:93:33
  91 |      let girl = Gender::Girl(girl1);
  92 |  
  93 |      boys.run(String::from("男孩们")); // 男孩们 跑得很快
     |                                   ^
  94 |      girl.run(String::from("小女孩")); // 小女孩 跑得很快
  95 |  }

And my code like these: 

```rust
enum Gender {
    Boy(String, String, String),
    Girl(String),
}

impl Gender {
    fn run(&self, gender: String) {
        println!("{} 跑得很快", gender);
    }
}

fn main() {
    let boy1 = String::from("大锤");
    let boy2 = String::from("中风");
    let boy3 = String::from("小明");
    let girl1 = String::from("小红");

    let boys = Gender::Boy(boy1, boy2, boy3);
    let girl = Gender::Girl(girl1);

    boys.run(String::from("男孩们")); // 男孩们 跑得很快
    girl.run(String::from("小女孩")); // 小女孩 跑得很快
}
```

Can somebody tell me how to fix this error? thanks!

### Reproduction

see above error

### Expected behavior

I hope the code could be rendered correctly

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 7.65 GB / 15.79 GB
  Binaries:
    Node: 16.13.0 - D:\nodejs\node.EXE
    Yarn: 1.22.18 - D:\npm\node_global\yarn.CMD
    npm: 8.6.0 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.35 => 1.0.0-alpha.35
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by PuffMeow** [comment]
![image](https://user-images.githubusercontent.com/63894579/211849113-ffe160f0-b55a-4c5c-890f-b7a099df044c.png)

**Comment by brc-dd** [comment]
Can you share your whole markdown file? The error is likely above that code block, probably haven't escaped something properly.

**Comment by PuffMeow** [comment]
@brc-dd  I have solved this problem，there is a statement Option<T> in my MD file, I try to change it to Option\<T\>, this can help.
