### ISSUE TITLE
yarn monorepo setting base config dev&build error

### ISSUE THREAD

**Issue by busyhe** [vuejs/vitepress#1788]
### Describe the bug

when i set config.js base, dev & build error!
example: https://github.com/busyhe/monorepo-template
![Uploading image.png…]()
deploy github page, click logo and click get started button error

### Reproduction

https://busyhe.github.io/monorepo-template/

### Expected behavior

yarn workspace docs dev success preview & deploy github page success preview

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 67.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 3.3.0 - ~/.nvm/versions/node/v18.12.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
the reproduction url seems to be working now?
