### ISSUE TITLE
Codeblocks always show vertical scrollbar

### ISSUE THREAD

**Issue by MarkusKeck** [vuejs/vitepress#1793]
### Describe the bug

Codeblocks always show a vertical scrollbar even when no overflow happens.
There should never be a vertical scrollbar even when an overflow happens.
Only overflow-x should be possible.

### Reproduction

Also appears on the official vitepress page

https://vitepress.vuejs.org/guide/markdown#code-groups

![image](https://user-images.githubusercontent.com/19492739/212391202-d7811fc3-3395-4a6f-8abd-9bf8d691290f.png)

### Expected behavior

No vertical scrollbar should appear ever

### System Info

```shell
System:                                                        
    OS: Windows 10 10.0.19045                                    
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor            
    Memory: 46.67 GB / 63.91 GB                                  
  Binaries:                                                      
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE             
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD               
    npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD                 
  Browsers:                                                      
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)    
    Internet Explorer: 11.0.19041.1566                           
  npmPackages:                                                   
    vitepress: ^1.0.0-alpha.13 => 1.0.0-alpha.36
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
I can't reproduce this. Is anyone on Windows having the same issue? We can add `overflow-y: hidden`, but would like to know why this is heppening 👀

**Comment by kiaking** [comment]
@MarkusKeck Thanks for the check! I think adding `overflow-y: hidden` would make sense 👍  Would you like to create a PR? 😃
