### ISSUE TITLE
Search button shown when non-functional (i.e. without JavaScript)

### ISSUE THREAD

**Issue by paulrobertlloyd** [vuejs/vitepress#1794]
### Describe the bug

If search has been configured, a search button is shown the navigation bar. This opens a dialog which displays Algolia’s search interface.

However, if JavaScript isn’t available/hasn’t loaded, this search button is still shown, labelled as ‘Search’, yet it doesn’t perform any function. This is confusing, perhaps even more so for screen reader users.

### Reproduction

Load a VitePress-powered site with search configured and JavaScript disabled. A search button is shown, but clicking it doesn’t perform any action.

### Expected behavior

Ideally, it would be possible to have this element fallback to an input element and submit button that, when submitted, performs a search on a search engine like DuckDuckGo, with the query scoped to the VitePress’ site URL, for example: <https://duckduckgo.com/?q=site%3Ahttps://vitepress.vuejs.org+my+query>

However, the simpler option might be to only show the search button if JavaScript is available or loaded.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.05 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.11.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 108.0.2
    Safari: 16.2
  npmPackages:
    vitepress: ^1.0.0-alpha.27 => 1.0.0-alpha.36
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Almost all the functionalities of the site will be broken if user has disabled JS. I'm not sure if we are willing to fix them, and most of them couldn't be even worked around.

**Comment by paulrobertlloyd** [comment]
I’ve used VitePress assuming it might use progressive enhancement, but on further investigation, besides enhancements like search and theme switches (which if aren’t available without JavaScript, doesn’t prevent usage of a site) note that on the mobile layout, navigation is inaccessible unless JavaScript has loaded.

Looks like I’ll need to investigate other options.
