### ISSUE TITLE
Next/Previous page not working properly.

### ISSUE THREAD

**Issue by dudo50** [vuejs/vitepress#1795]
### Describe the bug

Previous and Next page are not working correctly.

It only shows main page as next page for strange reason.
<img width="1623" alt="Screenshot 2023-01-14 at 22 31 02" src="https://user-images.githubusercontent.com/55763425/212504656-eecb0f8f-754f-4ed5-b94e-57ed10170570.png">

Where could be an issue?

### Reproduction

Config.js - https://github.com/paraspell/docs/blob/main/docs/.vitepress/config.js
Docs - https://github.com/paraspell/docs
Deployed docs for preview -  https://paraspell.github.io/docs/

### Expected behavior

Should display prev/next pages correctly

### System Info

```shell
Chrome macos
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Use absolute URLs in sidebar. Try this:

```ts
export default {
  title: 'ParaSpell',
  description: 'Make world more connected with XCM.',
  base: '/docs/',
  head: [['link', { rel: 'icon', sizes: '180x180', href: './favicon.png' }]],
  themeConfig: {
    logo: './paraspell.png',

    socialLinks: [
      { icon: 'github', link: 'https://github.com/paraspell' },
      { icon: 'twitter', link: 'https://twitter.com/paraspell' }
    ],

    sidebar: [
      {
        items: [
          { text: 'About ParaSpell✨', link: '/' },
          { text: 'Getting Started', link: '/getting-started' }
        ]
      },
      {
        text: 'Pallets in SDK',
        items: [
          { text: 'Asset Pallet', link: '/sdk/AssetPallet' },
          { text: 'HRMP Pallet', link: '/sdk/HRMP' },
          { text: 'XCM Pallet', link: '/sdk/xcmPallet' },
          { text: 'XYK Pallet', link: '/sdk/XYK' }
        ]
      },
      {
        text: 'Usage of UI',
        items: [
          { text: 'Starting local network', link: '/ui/local' },
          { text: 'Modifying local network', link: '/ui/modify' },
          { text: 'Adding new currency to UI', link: '/ui/currency' }
        ]
      },
      {
        text: 'Interesting links',
        items: [{ text: 'Links', link: '/links' }]
      }
    ]
  }
}
```
