### ISSUE TITLE
Import modules/files from parent folder

### ISSUE THREAD

**Issue by VinceG** [vuejs/vitepress#180]
**Is your feature request related to a problem? Please describe.**

Consider the following directory structure

```
- docs
-- .vitepress
--- theme
---- index.ts <--- import app.css here
-- index.md
- src
-- css
--- app.css <--- import this file
```

**Describe the solution you'd like**

Ability to import files from /src folder in the example above

**Comment by ChrisShank** [comment]
Would adding an [alias](https://github.com/vitejs/vite/blob/master/src/node/config.ts#L114) to the `src` directory in `vite.config.js` solve this?

**Comment by VinceG** [comment]
@ChrisShank no, it won’t import anything from parent folders

**Comment by tolking** [comment]
Add alias is work
example

``` js
// .vitepress -> config.js
const path = require('path')

module.exports = {
  //...
  alias: {
    '/Tese/': path.resolve(__dirname, '../../src'),
  },
}
```
``` js
// .vitepress -> theme -> index.js
import '/Tese/css/app.css'

//...
```

**Comment by kiaking** [comment]
This feature is already supported at latest code! You can directly import modules using relative path such as `import { ... } from '../../../src/app.css'` 👍
