### ISSUE TITLE
Code-group title affect line highlight

### ISSUE THREAD

**Issue by garmede** [vuejs/vitepress#1800]
### Describe the bug

The number in the code-group title affects the line highlight.

### Reproduction

````md
::: code-group
```cpp [[vec3.h] vec3 utility function]
// utility fuction
inline std::ostream& operator<<(std::ostream &out, const vec3 &v) {
    return out << v.e[0] << ' ' << v.e[1] << ' ' << v.e[2];
}
```
:::
````

### Expected behavior

If you use double square brackets for title, the number in the first square bracket is ignored.
However, if followed by any number, it affects the line highlight.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 45.95 GB / 63.92 GB
  Binaries:
    Node: 19.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-alpha.36 => 1.0.0-alpha.36
```

### Additional context

![image](https://user-images.githubusercontent.com/2133201/212638129-18855ee3-59c1-4bb3-9adb-068f75f42e46.png)
![image](https://user-images.githubusercontent.com/2133201/212638181-942f8913-9832-48b9-a0a6-f43e0e98fd7a.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah, I mean it's a regex we do parsing with, obviously some stuff will break 😅.

**Comment by StreakingMan** [comment]
got the same problem，looking foward fix 👀

**Comment by yyx990803** [comment]
Can no longer reproduce the original case. @StreakingMan if you have a difference case that still persists, please open a separate issue.
