### ISSUE TITLE
Changing URL hash causes entire page to reload

### ISSUE THREAD

**Issue by Andrew-web-coder** [vuejs/vitepress#1801]
### Describe the bug

Changing URL hash causes entire page to reload. This causes issues with third part script that uses hash navigation (well, it is Fancybox, but it is not relevant, you can quickly observe that by yourself).

### Reproduction

1) Go to https://vitepress.vuejs.org
2) Resize window so that vertical scrollbar appears, scroll to the bottom
3) Change URL to  https://vitepress.vuejs.org#aa
4) Watch as entire page reloads 

### Expected behavior

The page should not reload

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 6.77 GB / 15.95 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.74
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This depends on how you're changing the url. If you're directly changing the URL from browser, obviously it will reload. If you're changing the route programmatically, then you need to  use the exposed router (`useRouter()`) for SPA navigation. For links (bare anchor tags without target and absolute url specified), it should work fine. Feel free to reopen if the last one is what you're having issues with.

**Comment by Andrew-web-coder** [comment]
The thing is - Docusaurus, for example, works perfectly fine with Fancybox, but Vitepress does not, simply because it reloads on hash change. 

I do not understand your comment - "obviously it will reload". Steps to reproduce on Docusaurus:

1) Go to https://docusaurus.io/ and sroll to the bottom.

2) Change url to https://docusaurus.io/#aaa - observe that nothing reload, everything works fine.

3) Press back button on the browser - URL changes back to https://docusaurus.io/ and nothing reloads as expected.

**Comment by brc-dd** [comment]
Ah, this works on VuePress too 👀 . But VuePress/Docusaurus have probably much more complex router. Our router only intercepts certain kind of stuff, browser does the most of the thing.

**Comment by Andrew-web-coder** [comment]
Yes, you are right, VuePress works the way I want. If Vitpress worked the same way, then anyone using a third part scripts with hash navigation would benefit.

**Comment by Andrew-web-coder** [comment]
FYI, I hacked the VitePress source code for fun and found this problem to be very easy to fix. So, the problem is here:
https://github.com/vuejs/vitepress/blob/main/src/client/app/router.ts#L182

```js
window.addEventListener('popstate', (e) => {
    loadPage(location.href, (e.state && e.state.scrollPosition) || 0)
})
```

As you can see, VitePress loads page every time the user navigates using the browser's back/forward buttons. I added a simple check to avoid reloading current page. I could not find out how to get previous page, so I created a global variable and stored `href` value within `go` and `loadPage` methods. Then I simply compare it with the current location and load page only if different. Now everything is working amazingly well for me.

**Comment by brc-dd** [comment]
There are now router guards that should be sufficient for these cases. Refer #2564
