### ISSUE TITLE
 Error [RollupError]: "default" is not exported by "docs/.vitepress/theme/index.ts"

### ISSUE THREAD

**Issue by wmelton** [vuejs/vitepress#1802]
### Describe the bug

Following instructions found here: https://vitepress.vuejs.org/guide/theme-introduction#customizing-css

If I copy and paste the example code, and create a `custom.css` file in the same folder and then likewise copy and paste the example css in it, it generates the error: ` Error [RollupError]: "default" is not exported by "docs/.vitepress/theme/index.js"` when I run `yarn run docs:build`

### Reproduction

Install fresh install of vitepress. Follow doc guide for custom css. Attempt to build. Fails.

### Expected behavior

Builds and css changes are viewable.

### System Info

```shell
System:
    OS: macOS 12.6.2
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
    Memory: 123.30 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 104.0.1
    Safari: 16.2
  npmPackages:
    vitepress: ^1.0.0-alpha.36 => 1.0.0-alpha.36
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not reproducible: https://stackblitz.com/edit/vite-hbqkxv?file=docs/.vitepress/theme/custom.css,docs/.vitepress/theme/index.ts

**Comment by wmelton** [comment]
@brc-dd StackBlitz is running node v16.14 but the environment config I shared shows running in v18/lts - does Vitepress support node 18? Or are you also unable to produce that error on a node 18 instance also?

**Comment by kiaking** [comment]
@wmelton I haven't checked, but can you confirm that your setup would work on node 16? Then, yeah it must be something to do with node 18 👀

**Comment by wmelton** [comment]
Not sure when I will be able to get back to this - it works in node 16 for sure (that was my work around).

**Comment by brc-dd** [comment]
Closing this if there is no repro. On my local system I'm using Node 19 and everything has been working fine so far.
