### ISSUE TITLE
Links to public/ files are wrong when a base URL is used

### ISSUE THREAD

**Issue by catrope** [vuejs/vitepress#1806]
1. Put a file called `foo.json` in the `public/` directory
2. In an `.md` file somewhere, create a link like `[look at this JSON file](/foo.json)`
3. Build the site. The link works.
4. Change the VitePress config to add `base: '/base/`
5. Build the site again. The link doesn't work: it erroneously points to `/foo.json`, but it should point to `/base/foo.json`

**Comment by brc-dd** [comment]
The problem here is do we know if you're writing /foo.json, it is going to be internal 👀. What if someone wants to have a file at foo.com/bar.json and have vp deployed at foo.com/baz/ and we prefix that link so that it becomes foo.com/baz/bar.json, in this case that link will break, won't it 👀

**Comment by catrope** [comment]
> The problem here is do we know if you're writing /foo.json, it is going to be internal eyes. What if someone wants to have a file at foo.com/bar.json and have vp deployed at foo.com/baz/ and we prefix that link so that it becomes foo.com/baz/bar.json, in this case that link will break, won't it eyes

Sure, and there should be a way to link to something at the domain root if I really want to (perhaps by using a URL like @MarkusKeck) suggests. But the reason I was expecting it to work the way I described in my bug report is because *VitePress's own documentation [says that it should](https://vitepress.vuejs.org/guide/asset-handling#public-files)*:
> Assets placed in `public` will be copied to the root of the dist directory as-is.
>
> Note that you should reference files placed in `public` using root absolute path - for example, `public/icon.png` should always be referenced in source code as `/icon.png`.

There's no caveat here along the lines of "except if you're using a base path, then this doesn't work". At the very least the documentation should be updated so that it correctly describes the actual behavior. But I'd  argue for fixing this bug, or providing some other way of reliably linking to `public` files. The `public` feature is close to useless if there isn't a reliable way to link to those files without having to hard-code the base path all over the place, and without an easy way to refer to the base path for setups (like mine) where the base path is dynamic (we build the same site for different targets, with each target using a different base path).
