### ISSUE TITLE
dev home page doesn't honor base config

### ISSUE THREAD

**Issue by f-w** [vuejs/vitepress#181]
**Describe the bug**
`yarn docs:dev` renders home page on `http://localhost:3000` despite *base* is defined in *config.js*. But asset links honor the base path.

**To Reproduce**
1. follow *getting started* to create new site
2. create file */docs/.vitepress/config.js* with base set to, say `/foo/`
3. run `yarn docs:dev`

**Expected behavior**
Site should be rendered at `http://localhost:3000/foo/`

**System Info**
- vitepress version: 0.9.1
- vite version: 1.0.0-rc.13
- Node version: v14.5.0
- OS version: Windows 10

**Comment by 285851937** [comment]
I have the same problem. It seems not work that specified a ```base``` property in  ```.vitepress/config.js```

**Comment by tolking** [comment]
Check out #105 
Maybe, just use the `base` in build mode, like Vite.

**Comment by f-w** [comment]
As a workaround env var can be used to avoid hard coding.
Still a bug, I believe.

**Comment by 285851937** [comment]
I think it's perfect that to support two modes to use vitepress. 
mode 1: to build to static files and deploy that files on github or as a static resources behind nginx.
mode 2: being a web server revert proxied by nginx.

**Comment by kiaking** [comment]
Yes, `base` is not working on dev mode at the moment. We should make it work.
