### ISSUE TITLE
Favicon not working

### ISSUE THREAD

**Issue by dudo50** [vuejs/vitepress#1815]
### Describe the bug

Favicon is not being loaded up and gives an error - GET https://paraspell.github.io/favicon.ico 404

### Reproduction

https://paraspell.github.io/docs/ ___ Check console
https://github.com/paraspell/docs/blob/main/docs/.vitepress/config.js ___ This is config
https://github.com/paraspell/docs/tree/main/docs/public ___ This is public

### Expected behavior

It should load favicon like it does with yarn docs:dev

(It does not show it on 
```
yarn docs:serve
yarn docs:preview
```
)

### System Info

```shell
Macos
Chrome
Safari
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Add it using head:

```ts
// .vitepress/config.ts

export default {
  head: [
    [
      'link',
      { rel: 'icon', type: 'image/x-icon',  href: '/docs/favicon.ico' }
    ]
  ]
}
```

By default, the browsers look for /favicon.ico, but since you've deployed to ....github.io/docs/ (base: 'docs'), your favicon is at /docs/favicon.ico, so you must specify it explicitly.
