### ISSUE TITLE
Organize slots with good naming convention

### ISSUE THREAD

**Issue by kiaking** [vuejs/vitepress#1819]
One thing I would like to do with slots is to come up with good naming convention that differentiate whether the slot will be displayed when the related component is visible or hidden.

For example, we have a slot named `aside-outline-before`. It's not 100% clear whether this slot will be displayed even when there's no outline on the page. Answer is It does. But `aside-top` will not show if aside is hidden.

And I think there're use cases for both situation. I was thinking it below 😳 

- `aside-outline-before` => Visible regardless of outline visibility
- `aside-outline-top` => Visible only when outline is visible 

So -top -bottom -left -right is only visible when the related component is visible, and -beofre -after will get displayed even when the related component is hidden.

Open to any good idea on this 👀

**Comment by gumingWu** [comment]
So are you willing to merge my PR about a new slot : ) #1807

**Comment by kiaking** [comment]
I've went through all slots, and seems like everything is actually conveying this rule 😳 So, I guess we don't need to do anything 👍
