### ISSUE TITLE
Use PNG files for Team Page Avatar?

### ISSUE THREAD

**Issue by jtgober** [vuejs/vitepress#1826]
### Describe the bug

Hey not sure if bug or not. However when trying to add avatars on a team page while within an enterprise doesnt seem to work

- is there a way to just add a .png file from the public folder to the avatar team url? 

### Reproduction

  {
    avatar: '/mypng.png',
    name: 'Jonathan Gober',
    title: 'QP Consultant',
    links: [
      { icon: 'github', link: 'my github link' }, 
    ]
  },

running docs:dev gives expected result and shows png
running with built file fails

### Expected behavior

Should show png avatar for team page

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 16.31 GB / 31.73 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)   
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.30 => 1.0.0-alpha.30
```

### Additional context

n/a

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
In which directory have you stored that image file? It's working fine for me 👀

**Comment by jtgober** [comment]
I keep it in the public directory

--Maybe i need to update vitepress?  it does work on the docs:dev command but not after build

**Comment by brc-dd** [comment]
Ah, okay let me check once. Also, do you have some base specified in config?

**Comment by jtgober** [comment]
yes sir. everything else seems to load correctly / everything looks fine in pages.

also img of my file structure

![image](https://user-images.githubusercontent.com/57597859/213801291-ece511a7-5ed2-4c4e-bf17-084d4828b840.png)

**Comment by jtgober** [comment]
hmmm regrettably adding the base path doesn't work either. Whenever i can ill try to update to the latest version to see if that fixes anything

**Comment by jtgober** [comment]
Hey @brc-dd. you were once again correct. adding in the basepath to the avatar line was the right solution. Earlier  i didnt realize i had the png file as uppercase, but the actual file was lowercase.

Thanks again for your help on this!

**Comment by brc-dd** [comment]
Yeah cool! BTW if you don't want to hardcode base, just use `withBase` from vitepress.

**Comment by jtgober** [comment]
ill check that out!
