### ISSUE TITLE
Carbon Ads 有计划支持自定义广告图片吗？

### ISSUE THREAD

**Issue by zchengo** [vuejs/vitepress#1828]
### Is your feature request related to a problem? Please describe.

Carbon Ads 有计划支持自定义广告图片吗？有一部分 vitepress 用户，无法使用 Carbon Ads 提供的广告，这些用户想用 Carbon Ads 来展示自定义的广告图片或二维码。

### Describe the solution you'd like

将来 Carbon Ads 会不会支持自定义广告图片？

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can use one of the aside slots to add your own component instead of using carbon ads: https://vitepress.vuejs.org/guide/theme-introduction#layout-slots

**Comment by zchengo** [comment]
ok 👌🏻
