### ISSUE TITLE
Routing breaks with relative base path

### ISSUE THREAD

**Issue by jtuchel** [vuejs/vitepress#1830]
### Describe the bug

Given the following configuration

```ts
import { defineConfig } from 'vitepress'

export default defineConfig({
    base: './',
    outDir: '../dist',
    themeConfig: {
        sidebar: [
            {
                text: 'Configuration',
                collapsible: true,
                items: [
                    {
                        text: 'Foo',
                        link: '/configuration/foo'
                    }
                ]
            },
            {
                text: 'Deployment',
                collapsible: true,
                items: [
                    {
                        text: 'Bar',
                        link: '/deployment/bar'
                    }
                ]
            }
        ]
    }
})
```

with the following folder structure

```
.
└── docs
    ├── .vitepress
    │   └── config.ts
    ├── configuration
    │   └── foo.md
    ├── deployment
    │    └── bar.md
    └── index.md
```

When clicking on the sidebar link **Foo** it works fine, the router navigates to

> http://localhost:5173/configuration/foo.html

but when I now click **Bar** the router navigates to

> http://localhost:5173/configuration/deployment/bar.html

which is wrong. The expected url should be

> http://localhost:5173/deployment/bar.html

### Reproduction

https://stackblitz.com/edit/vite-lem5ux?file=docs%2F.vitepress%2Fconfig.ts

### Expected behavior

When clicking on the sidebar link **Foo** it works fine, the router navigates to

> http://localhost:5173/configuration/foo.html

When navigating to **Foo** and clicking  **Bar** the router should navigate to

> http://localhost:5173/deployment/bar.html

### System Info

```shell
System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 20.66 GB / 31.29 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 19.0.0 - ~/.nvm/versions/node/v19.0.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v19.0.0/bin/npm
  Browsers:
    Firefox: 108.0.2
```

### Additional context

I think the problem is that I'm using a relative base path in my config. I'm using this https://vitejs.dev/config/shared-options.html#base because the requirement is that paths must not be absolute, they must be relative.

When creating Vue apps this is forbidden

> <script type="module" src="/src/main.ts"></script>

Paths should be

> <script type="module" src="./src/main.ts"></script>

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Vite's base is different than VitePress. We don't support the base you've written.

**Comment by jtuchel** [comment]
> Vite's base is different than VitePress. We don't support the base you've written.

@brc-dd based on https://vitepress.vuejs.org/config/app-configs#base would you mind explaining how to generate relative paths instead?

How do I get `./assets/...` instead of `/assets/...` ?

**Comment by brc-dd** [comment]
What's your use case? 

`./assets/...` will resolve differently from each page depending on directory and obviously break stuff. It's a browser feature, we don't control that.
