### ISSUE TITLE
Allow to use configuration file from current working directory

### ISSUE THREAD

**Issue by azat-io** [vuejs/vitepress#1842]
In VuePress v2 you can set configuration in source directory:

```
docs/
├── .vuepress/
│   ├── components/
│   │   ├── avatar.vue
│   │   └── button.vue
│   └── layout/
│       ├── page.vue
│       └── not-found.vue
├── en/
│   ├── page-1/
│   │   └── index.md
│   └── page-2/
│       └── index.md
└── ru/
    ├── page-1/
    │   └── index.md
    ├── page-2/
    │   └── index.md
    ├── config.ts
    └── readme.md
package.json
```

And in current working directory like this:

```
components/
├── avatar.vue
└── button.vue
layout/
├── page.vue
└── not-found.vue
docs/
├── en/
│   ├── page-1/
│   │   └── index.md
│   └── page-2/
│       └── index.md
└── ru/
    ├── page-1/
    │   └── index.md
    ├── page-2/
    │   └── index.md
    ├── config.ts
    └── readme.md
vuepress.config.ts
package.json
```

[VuePress docs](https://v2.vuepress.vuejs.org/guide/configuration.html#client-config-file).

It would be great if VitePress could also use the config from the root.

Not all VitePress sites focus only on content writing. Some sites also focus on creating custom themes. For them, the second structure would be more convenient.

The configuration could be described in the root of the project in files:
* `vitepress.config.ts`
* `vitepress.config.js`
* `vitepress.config.mts`

**Comment by azat-io** [comment]
@brc-dd What do you think about this?

**Comment by brc-dd** [comment]
I don't have any issue, but what's the use case of this? I mean what's the exact problem that people face when using `.vitepress/config.ts`? Also, can you point me to a vuepress issue/discussion that implemented this?

**Comment by azat-io** [comment]
@brc-dd There is not issue/discussion in VuePress next repo.

This improvement allows you to avoid creating unnecessary nesting if the project focuses more on creating a theme than on content

**Comment by azat-io** [comment]
Can we check the opened pull request?

**Comment by azat-io** [comment]
@brc-dd Ping

**Comment by brc-dd** [comment]
I'm not seeing any particular demand for this feature. I think the current behavior is fine enough for almost everyone.

**Comment by azat-io** [comment]
Sad
