### ISSUE TITLE
Fix line break before "external link icon"

### ISSUE THREAD

**Issue by sbleh** [vuejs/vitepress#1864]
### Describe the bug

Since 1.0.0-alpha.41, there is a line break before the external link icon (arrow right up) for links going to other websites. 

### Reproduction

.

### Expected behavior

Having it inline with the title of that link.

### System Info

```shell
.
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sbleh** [comment]
Haven't found anything else. It's not really broken but unexpected formatting.

**Comment by brc-dd** [comment]
/cc @kiaking We currently have

https://github.com/vuejs/vitepress/blob/f9743816a55503c387b9c71793a92eb38817650d/src/client/theme-default/components/VPSidebarItem.vue#L58-L60

I don't think we can move svg inside the text tag. We however can have something like this using flex (external link icons are right aligned):

<img width="248" alt="image" src="https://user-images.githubusercontent.com/40380293/216071220-bc6cd054-9add-40e8-b583-020d22768a9e.png">

Created #1880, have a look. Any better solution where we can have it like it was earlier (just after the text end)?
