### ISSUE TITLE
The value of the class of the pre tag is truncated

### ISSUE THREAD

**Issue by jerrywu001** [vuejs/vitepress#1872]
### Describe the bug

online demo:
https://stackblitz.com/edit/vitejs-vite-79ocfq?file=docs%2Findex.md

1. Register a public component. called `SandBox`.

```js
// docs/components/SandBox.vue
ctx.app.component('SandBox', SandBox);
```
2. Use markdown-it-direcitve-webcomponents plugin.

```js
import { createRequire } from 'module';
import { defineConfig } from 'vitepress';

const require = createRequire(import.meta.url);

export default defineConfig({
  markdown: {
    config(md) {
      md.use(require('markdown-it-directive')).use(
        require('markdown-it-directive-webcomponents'),
        {
          components: [
            {
              present: 'both',
              name: 'sandbox',
              tag: 'sand-box',
              allowedAttrs: ['readonly', 'closabletabs', 'template'],
              parseInner: true,
            },
          ],
        }
      );
    },
  },
});
```

3. So I can use it like this in .md.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/12525415/215923598-a750300a-41b5-4649-97ac-e2e9952b498d.png">

4. The expect effect is as follows

https://vue3-npm-template.netlify.app/get-started/introduction.html#demo

<img width="700" alt="image" src="https://user-images.githubusercontent.com/12525415/215923868-05067303-ee50-453a-a6f2-f8220db4d778.png">

### But actually:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/12525415/215924089-901a2c77-7005-4a3a-8821-0813704e2fb8.png">

Version `1.0.0-alpha.31` does not have this problem.

**This issue starts from `1.0.0-alpha.32`**.

See: https://github.com/vuejs/vitepress/commit/a684b67ec084fdc3b3a300ffbdd21e19fdcf7b1e#diff-caaa5859b69d40532a36e00cd217b000c7653293a148088a1dbc0275e8c56570

**Because The value of the class of the pre-tag is truncated**.

### Reproduction

See: https://stackblitz.com/edit/vitejs-vite-79ocfq?file=docs%2Findex.md

### Expected behavior

Expected to happen:

https://vue3-npm-template.netlify.app/get-started/introduction.html#demo

<img width="700" alt="image" src="https://user-images.githubusercontent.com/12525415/215923868-05067303-ee50-453a-a6f2-f8220db4d778.png">

The issue starts from `1.0.0-alpha.32`.

See: https://github.com/vuejs/vitepress/commit/a684b67ec084fdc3b3a300ffbdd21e19fdcf7b1e#diff-caaa5859b69d40532a36e00cd217b000c7653293a148088a1dbc0275e8c56570

Because The value of the class of the pre-tag is truncated.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vitepress: ^1.0.0-alpha.44 => 1.0.0-alpha.44
```

### Additional context

 Version `1.0.0-alpha.31` does not have this problem.

This issue starts from `1.0.0-alpha.32`.

See: https://github.com/vuejs/vitepress/commit/a684b67ec084fdc3b3a300ffbdd21e19fdcf7b1e#diff-caaa5859b69d40532a36e00cd217b000c7653293a148088a1dbc0275e8c56570

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jerrywu001** [comment]
#1873

**Comment by brc-dd** [comment]
You can write a custom plugin to do some stuff like this: https://github.com/brc-dd/sandpack-vitepress-demo

**Comment by jerrywu001** [comment]
> You can write a custom plugin to do some stuff like this: https://github.com/brc-dd/sandpack-vitepress-demo

thanks

**Comment by jerrywu001** [comment]
I appreciate your help. I have written a plugin for vitepress. So we can use Sandpack as a directive in the markdown file.

Docs: https://vitepress-sandbox.js-bridge.com/get-started/introduction.html

@brc-dd
