### ISSUE TITLE
(shiki v0.14.0): ANSI `ansi` code lang support

### ISSUE THREAD

**Issue by Zhengqbbb** [vuejs/vitepress#1876]
### Is your feature request related to a problem? Please describe.

[shiki v0.14.0](https://github.com/shikijs/shiki/releases) support [ANSI code lang support](https://github.com/shikijs/shiki/pull/386#issuecomment-1404347813).

This is a great improvement over **CLI documentation** like `--help` or `output result` with colorized. Such code display can better distinguish and highlight the key points. Allows users to have more custom highlighting behavior.

### Describe the solution you'd like

```md
```ansi
[90m$[0m [32mczg[0m --help
...
[33mSUBCOMMAND:[0m
    [36mbreak[0m          [31mTurn on appends a ! after the type/scope[0m
    [36memoji[0m          [31mTurn on output message with emoji mode[0m
    [36mcheckbox[0m       [31mTurn on scope checkbox mode[0m
    [36mgpg[0m            [31mTurn on use GPG sign commit message[0m
...
``
```

==>

<img width="800" alt="image" src="https://user-images.githubusercontent.com/40693636/215975574-621fee05-161d-4709-bcf0-7dc6474a68e0.png">

### Describe alternatives you've considered

https://github.com/shikijs/shiki/pull/386#issuecomment-1404347813

```js
const fs = require('fs')
const markdown = require('markdown-it')
const shiki = require('shiki')

shiki.getHighlighter().then(highlighter => {
  const md = markdown({
    highlight: (code, lang) => {
      if (lang === 'ansi') {
        highlighter.ansiToHtml(...)
      }
      return highlighter.codeToHtml(code, { lang })
    }
  })
})
```

### Additional context

I would like to submit a PR if possible

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah PRs are welcome. Shiki is already updated, just need to add the `ansiToHtml` thing 👍
