### ISSUE TITLE
Translate Previous page and Next page (make the text configurable)

### ISSUE THREAD

**Issue by epogrebnyak** [vuejs/vitepress#1883]
### Is your feature request related to a problem? Please describe.

"Previous page" and "Next page" may need translation to other language.

At this point we one can configure "On this page" (with `outlineTitle`), but not yet "Previous page" and "Next page".

Possibly `previousPageTitle` and `nextPageTitle` are needed.

### Describe the solution you'd like

As in https://github.com/vuejs/vitepress/issues/689#issuecomment-1144611412

### Additional context

Issue discussed at https://github.com/vuejs/vitepress/issues/689 with making "On this page" text configurable, but closed without going forward.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.vuejs.org/config/theme-configs#docfooter
