### ISSUE TITLE
如何针对静态导入跳过SSR？

### ISSUE THREAD

**Issue by LZQCN** [vuejs/vitepress#1884]
### Is your feature request related to a problem? Please describe.

许多第三方库会在导入时的顶层代码中访问 `window` 或者 `document`
我不可能在第三库的源码中加上条件判断，这是不切实际的。

假设有一个Vue插件模块名字就叫 "a-vue-plugin"，并且假设它提供了大量有用的Vue组件或者实用功能。
```typescript
window.ABC = 123 // 这个模块在代码顶层就访问里 window

const plugin = {
  // ...
}

export default plugin
```

docs/.vitepress/theme/index.ts
```typescript
// ...
import { plugin } from 'a-vue-plugin''

export default define<Theme>({
  NotFound,
  Layout: VPApp,
  enhanceApp: ({ app }) => {
    // 这样写显然是无济于事的，因为在执行 import { plugin } from 'a-vue-plugin' 时就已经访问到 window 了  
    if (!import.meta.env.SSR) {
      app.use(plugin) // 这里需要使用这个插件
    }
  },
})
```
最终抛出错误
```
⠋ rendering pages...ReferenceError: window is not defined
```

### Describe the solution you'd like

目前缺少完全合理的解决方案，请求官方针对此问题提供标准的解决方案或者规避方案。

### Describe alternatives you've considered

这是一个可能的解决方案，但需要 enhanceApp 支持异步才行。
```typescript
export default define<Theme>({
  NotFound,
  Layout: VPApp,
  enhanceApp: async ({ app }) => {
    if (!import.meta.env.SSR) {
      const plugin = (await import('a-vue-plugin')).default
      app.use(plugin)
    }
  },
})
```

### Additional context

类似的问题 [#](https://github.com/vuejs/vitepress/issues/1727#issue-1507239476)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by zhangbowy** [comment]
我也遇到了

**Comment by XiangZhenHua11** [comment]
+1  希望处理下，业务场景引用三方js情况很多

**Comment by yyx990803** [comment]
https://github.com/vuejs/vitepress/pull/1760 已经加上了 `async enhanceApp` 的支持。
