### ISSUE TITLE
Vitepress locally 

### ISSUE THREAD

**Issue by Makio64** [vuejs/vitepress#1889]
### Is your feature request related to a problem? Please describe.

Made the doc work locally in an old fashion way ( no need of server, you open the index and arrive into the doc )..

A single file ideally.

### Describe the solution you'd like

Add a --singlefile option to made all package in it.

### Describe alternatives you've considered

I checkout vite-plugin-singlefile and a guy made it work with vite & vue but I coudnt find a way to made it work in vitepress 

https://stackoverflow.com/questions/67031295/how-to-open-a-static-website-in-localhost-but-generated-with-vite-and-without-ru#comment118485222_67031295

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not gonna support that officially. It's just too much burden to maintain the hell relative links cause. You can use some base like `path.join(process.cwd(), 'docs/.vitepress/dist/')` on \*nix. But it won't work if you move your generated code around.
