### ISSUE TITLE
Support vite.config.js

### ISSUE THREAD

**Issue by antfu** [vuejs/vitepress#189]
**Describe the solution you'd like**
Able to load `vite.config.js` / `vite.config.ts` under root and merge with Vitepress specified configurations.

**Comment by cloydlau** [comment]
agree, hope it's feasible to use vue2 libraries in vitepress with this and vite-plugin-vue2

**Comment by matias-capeletto** [comment]
In VuePress, the webpack config could also be modified in `.vuepress/config.js` using `configureWebpack`
https://vuepress.vuejs.org/config/#configurewebpack

Maybe both `vite.config.js` under root and a `vite` config option in `.vitepress/config.js` could be supported (following the `markdown` option to configure markdown-it)

**Comment by antfu** [comment]
Waiting for this https://github.com/vitejs/vite/pull/1263 get merged in order to load vite.config.js and merge with Vitepress's custom plugins

**Comment by icehaunter** [comment]
Really needed for component demos using imports which require deep imports

**Comment by antfu** [comment]
Already supported in Vite 2.

**Comment by cloydlau** [comment]
It throws an error below when integrating **vite-plugin-vue2** plugin in vite.config.js

```
runtime-core.esm-bundler.js [Vue warn]: Component is missing template or render function. 
  at <Layout> 
  at <VitePressApp>
```

This plugin works fine in vite, hope it's supported in vitepress as well.

**Comment by antfu** [comment]
@cloydlau Vitepress is built on top of Vue 3 and I am afraid there is no easy way to use Vue 2.
