### ISSUE TITLE
docs build get 'F.useData is not a function'

### ISSUE THREAD

**Issue by jerrywu001** [vuejs/vitepress#1900]
### Describe the bug

I have a plugin called [vitepress-plugin-sandpack](https://github.com/jerrywu001/vitepress-plugin-sandpack)

In this plugin, I used the `useData` API.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/12525415/217128002-d701955c-47e2-4b38-85e9-1b28a64ed829.png">

When build, it get **'F.useData is not a function**

### Reproduction

online code: https://stackblitz.com/edit/vitejs-vite-79ocfq?file=package.json

run `npm run docs:build`

<img width="766" alt="image" src="https://user-images.githubusercontent.com/12525415/217128048-be7ccf3d-c9cc-4b82-aba6-d347ba0ed6ee.png">

But deployment is successful.

### Expected behavior

See Reproduction

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vitepress: latest => 1.0.0-alpha.45
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by godxiaoji** [comment]
Methods that start with use* indicates that it is a [Vue 3 Composition API](https://vuejs.org/guide/introduction.html#composition-api) function that can only be used inside setup() or <script setup>. 
See: https://vitepress.vuejs.org/guide/api

**Comment by jerrywu001** [comment]
> Methods that start with use* indicates that it is a [Vue 3 Composition API](https://vuejs.org/guide/introduction.html#composition-api) function that can only be used inside setup() or <script setup>. See: https://vitepress.vuejs.org/guide/api

yes, you can see, it is used inside setup.
https://user-images.githubusercontent.com/12525415/217128002-d701955c-47e2-4b38-85e9-1b28a64ed829.png

**Comment by godxiaoji** [comment]
The use* indicates is asyntactic sugar in vitepress project. In fact, vitepress does not expose useData.
The external dependence will not get support during the building stages.

You can try to import the original address:
```js
import { useData } from "vitepress/dist/client/index";
```

At the same time, you modify `./dist/esm/index.js` to `./dist/esm/index.ejs` in package.json. Otherwise, it will be considered as CommonJS modules and cannot be used correctly.
```json
{
  "module": "./dist/esm/index.ejs"
}
```

**Comment by jerrywu001** [comment]
> The use* indicates is asyntactic sugar in vitepress project. In fact, vitepress does not expose useData. The external dependence will not get support during the building stages.
> 
> You can try to import the original address:
> 
> ```js
> import { useData } from "vitepress/dist/client/index.js";
> ```

no, no, no, I think it is just an issue from vitepress.

Like [antfu](https://antfu.me/), he has a plugin called [vue-starport](https://github.com/antfu/vue-starport/blob/main/package.json). You can see, the package.json like this:

<img width="405" alt="image" src="https://user-images.githubusercontent.com/12525415/217690953-1e095561-2cd5-4cea-a2c1-e80c6526d990.png">

So I change my plugin to:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/12525415/217691268-e05fb115-e76c-4956-8dcf-c76943d1a860.png">

And in my another vitepress project, change the package.json:

```json
{
  "name": "docs",
  "version": "1.0.0",
  "description": "description for my-custom-vue3-package",
  "type": "module",
  "scripts": {
    "docs:build": "vitepress build docs",
    "docs:dev": "vitepress dev docs",
    "docs:serve": "vitepress serve docs"
  },
  "devDependencies": {
    "vitepress": "1.0.0-alpha.45",
    "vitepress-plugin-sandpack": "latest"
  }
}
```

Then I run `npm run build:docs`, it still has issue:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/12525415/217691833-56751c4e-64bf-41ac-9be3-b18a3b5c2084.png">

--- 

Actually, this has nothing to do with how I define export rules.
@godxiaoji

**Comment by godxiaoji** [comment]
> The use* indicates is asyntactic sugar in vitepress project. In fact, vitepress does not expose useData. The external dependence will not get support during the building stages.
> 
> You can try to import the original address:
> 
> ```js
> import { useData } from "vitepress/dist/client/index.js";
> ```

As mentioned above, The 'vitepress' dose not provide an export named 'useData'. The actual dependence is 'vitepress/dist/client/index.js':

```js
// exports in this file are exposed to themes and md files via 'vitepress'
// so the user can do `import { useRoute, useSiteData } from 'vitepress'`
// composables
export { useData } from './app/data.js';
export { useRouter, useRoute } from './app/router.js';
// utilities
export { inBrowser, withBase } from './app/utils.js';
// components
export { Content } from './app/components/Content.js';
```

**Comment by jerrywu001** [comment]
> > The use* indicates is asyntactic sugar in vitepress project. In fact, vitepress does not expose useData. The external dependence will not get support during the building stages.
> > You can try to import the original address:
> > ```js
> > import { useData } from "vitepress/dist/client/index.js";
> > ```
> 
> As mentioned above, The 'vitepress' dose not provide an export named 'useData'. The actual dependence is 'vitepress/dist/client/index.js':
> 
> ```js
> // exports in this file are exposed to themes and md files via 'vitepress'
> // so the user can do `import { useRoute, useSiteData } from 'vitepress'`
> // composables
> export { useData } from './app/data.js';
> export { useRouter, useRoute } from './app/router.js';
> // utilities
> export { inBrowser, withBase } from './app/utils.js';
> // components
> export { Content } from './app/components/Content.js';
> ```

The same is ESM, why does the docs:dev not report an error???

And `preview:docs` can be run correctly, why??

**Comment by jerrywu001** [comment]
> > The use* indicates is asyntactic sugar in vitepress project. In fact, vitepress does not expose useData. The external dependence will not get support during the building stages.
> > You can try to import the original address:
> > ```js
> > import { useData } from "vitepress/dist/client/index.js";
> > ```
> 
> As mentioned above, The 'vitepress' dose not provide an export named 'useData'. The actual dependence is 'vitepress/dist/client/index.js':
> 
> ```js
> // exports in this file are exposed to themes and md files via 'vitepress'
> // so the user can do `import { useRoute, useSiteData } from 'vitepress'`
> // composables
> export { useData } from './app/data.js';
> export { useRouter, useRoute } from './app/router.js';
> // utilities
> export { inBrowser, withBase } from './app/utils.js';
> // components
> export { Content } from './app/components/Content.js';
> ```

The problem not as you say.

Because when I run `docs:dev`, it's deps still loaded useData from vitepress. why it has no issue????

![](https://user-images.githubusercontent.com/12525415/217730027-c437bd21-9e66-4f24-b511-3369caaba151.png)

But I  changed my plugin to the es module,  it has issue when `docs:build`:

![](https://user-images.githubusercontent.com/12525415/217691833-56751c4e-64bf-41ac-9be3-b18a3b5c2084.png)

**Comment by jerrywu001** [comment]
What exactly is the problem?
@godxiaoji

**Comment by godxiaoji** [comment]
> What exactly is the problem? @godxiaoji

Because the 'vitepress' is specially processed in the development environment. You will not be confused in vitepress project when debugging API Reference. But vitepress is actually a CLI role.

Understand dependencies and devDependencies first.

**Comment by jerrywu001** [comment]
> > What exactly is the problem? @godxiaoji
> 
> Because the 'vitepress' is specially processed in the development environment. You will not be confused in vitepress project when debugging API Reference. But vitepress is actually a CLI role.
> 
> Understand dependencies and devDependencies first.

I can not find the `specially processed ` code in the .vitepress cache folder. 
Actually, It still loaded from 'node_modules', it not like you said.

**Comment by jerrywu001** [comment]
What exactly is the problem?
@godxiaoji

**Comment by godxiaoji** [comment]
In the development environment, the runtime is as shown in the figure:
![image](https://user-images.githubusercontent.com/1532716/217741631-aa040488-d304-44da-ac07-1e2b351c4a95.png)

**Comment by jerrywu001** [comment]
> In the development environment, the runtime is as shown in the figure: ![image](https://user-images.githubusercontent.com/1532716/217741631-aa040488-d304-44da-ac07-1e2b351c4a95.png)

Got it, it was resolved by vite server.

But I run `docs:build`, when`rendering pages`, the `useData` function can be invoked successfully. Only failed once.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/12525415/217743279-daa38c34-a28b-4425-8023-6580eb37dff0.png">

Why??
@godxiaoji
