### ISSUE TITLE
build 报错: SyntaxError: The requested module '@highlightjs/vue-plugin' does not provide an export named 'default'

### ISSUE THREAD

**Issue by SaberA1ter** [vuejs/vitepress#1905]
### Describe the bug

项目中使用了 highlightjs 作为代码预览高亮工具。开发时并未发现异常，但是在构建时提示错误
```text
build error:
 file:///C:/demo-code/vitepress-error/docs/.vitepress/.temp/app.js:7
import hljsVuePlugin from "@highlightjs/vue-plugin";
       ^^^^^^^^^^^^^
SyntaxError: The requested module '@highlightjs/vue-plugin' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async build (file:///C:/demo-code/vitepress-error/node_modules/.pnpm/vitepress@1.0.0-alpha.45/node_modules/vitepress/dist/node/serve-ebe7f464.js:42286:24)
 ELIFECYCLE  Command failed with exit code 1.
```
一开始我怀疑是该库存在问题，但是在常规 vue 应用中使用并构建都是没问题的。

### Reproduction

最小复现
```text
https://github.com/SaberA1ter/vitepress-error-demo
```
组件在 ```docs/.vitepress/theme/index.js``` 中注册，报错也是发生于此

### Expected behavior

开发正常，但是构建报错。

### System Info

```shell
win11

nodejs: v16.15.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by godxiaoji** [comment]
It's already be fixed in https://github.com/highlightjs/vue-plugin/pull/27. Please:
```
pnpm add -S @highlightjs/vue-plugin@next
```
to install v2.1.2.

**Comment by SaberA1ter** [comment]
> 它已经在[highlightjs/vue-plugin#27](https://github.com/highlightjs/vue-plugin/pull/27)中修复。请：
> 
> ```
> pnpm add -S @highlightjs/vue-plugin@next
> ```
> 
> 安装 v2.1.2。

问题解决了，谢谢。
