### ISSUE TITLE
Whether multi-level directories are supported on this page

### ISSUE THREAD

**Issue by Mankvis** [vuejs/vitepress#1907]
May I ask whether the content on this page supports multi-level directories? Currently, only level-2 directories will be displayed

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/49258868/217474699-1f717238-085f-4c79-ae49-2d0ff835a3e1.png">

**Comment by kiaking** [comment]
Yes. See the `outline` option in config doc. https://vitepress.vuejs.org/config/theme-configs#outline

**Comment by Mankvis** [comment]
> Yes. See the `outline` option in config doc. https://vitepress.vuejs.org/config/theme-configs#outline

Hello, I'm sorry that I may misunderstand my meaning. What I mean is not to modify "on this page", but to display multi-level directories below" on this page"

**Comment by kiaking** [comment]
Yes, and you can control the nesting level with `outline` option.

> The levels of header to display in the outline. You can specify a particular level by passing a number, or you can provide a level range by passing a tuple containing the bottom and upper limits. When passing 'deep' which equals [2, 6], all header levels are shown in the outline except h1. Set false to hide outline.

e.g.

```js
{
  themeConfig: {
    outline: [2, 4]
  }
}
```
