### ISSUE TITLE
Use Frontmatter for List of Paths to Images 

### ISSUE THREAD

**Issue by drewalth** [vuejs/vitepress#1909]
### Is your feature request related to a problem? Please describe.

I'm running into a problem with how I'm using frontmatter and Vue components in a markdown file. Before getting into this, I think this issue should be labeled "Question" rather than Feature Request. 

I am using frontmatter to list paths to image files. The list is then passed to an `ImageGallery` component where styling and click events (lightboxes) happen. 

```md
---
title: Section One
items:
    - "./image-01.jpg"
    - "./image-02.jpg"
---

<script setup>
import ImageGallery from "../components/ImageGallery.vue"
</script>

# {{ $frontmatter.title }}

<ImageGallery :items="$frontmatter.items" />
```

This works fine in development, but after running `build`, and `preview`, the image files 404. This makes sense because the image files are not included in the `dist/`. 

So, with the way that vitepress [handles assets](https://vitepress.vuejs.org/guide/asset-handling), is it possible to use images in this way; a list of paths defined in frontmatter. Or do all images have to be defined like a standard markdown image? 

```md
![An image](./image.png)
```

It would be super awesome to create a reusable gallery/lightbox component vs having to list out lots of images in md. 

```md
![An image](./image-01.png)
![An image](./image-02.png)
![An image](./image-03.png)
![An image](./image-04.png)
```

### Describe the solution you'd like

I'm unsure how we could use frontmatter to include paths-to-images in the final dist—maybe checking each list item to see if it is a string and the file extension? 

### Additional context

Here's a link to the example repo: [https://github.com/drewalth/vitepress-image-gallery-frontmatter.git](https://github.com/drewalth/vitepress-image-gallery-frontmatter.git).

I'm sorry if this is a duplicate...

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We currently cannot process assets defined in variables (frontmatter in your case). You can create a `public` directory in your project root (`docs/public` if your run `vitepress dev docs`) and keep those images there.

**Comment by drewalth** [comment]
Thanks!
