### ISSUE TITLE
alpha.43：How to use onBeforeRouteChange and onAfterRouteChanged？

### ISSUE THREAD

**Issue by ChaiMayor** [vuejs/vitepress#1910]
This is my document library address: https://chai-mayor.gitee.io/hview-ui/

Now listen to route address changes in this way, to achieve the progress bar effect.
![image](https://user-images.githubusercontent.com/97388975/217701575-16c81f82-ab7b-4fd0-8f4a-8eff92bcb60e.png)

A false progress bar, can not really monitor the network situation, network congestion leads to the page stuck when jumping links, when the past page will have progress bar effect, this effect is too bad.

How can I use this hook. `onBeforeRouteChange` and `onAfterRouteChanged`
refer: https://github.com/vuejs/vitepress/pull/1264
![image](https://user-images.githubusercontent.com/97388975/217702243-69d1cee7-7ea6-4d0a-bf1d-1e9c1b60eb51.png)

I really need this hook. 😭

**Comment by brc-dd** [comment]
in enhanceApp you will be having `router` too along with app. Do router.onBeforeRouteChange there.

**Comment by ChaiMayor** [comment]
Thank you very much. That was a successful solution. 🤗

**Comment by wisarut-ph** [comment]
.
