### ISSUE TITLE
Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by gengzhaoji** [vuejs/vitepress#1912]
### Describe the bug

Cannot read properties of undefined (reading 'apply')

### Reproduction

Cannot read properties of undefined (reading 'apply')

### Expected behavior

Cannot read properties of undefined (reading 'apply')

### System Info

```shell
Cannot read properties of undefined (reading 'apply')
```

### Additional context

Cannot read properties of undefined (reading 'apply')

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by gengzhaoji** [comment]
打包错误

**Comment by gengzhaoji** [comment]
"vitepress": "1.0.0-alpha.4", 版本

**Comment by brc-dd** [comment]
We need more details than that. Please create a new issue by properly filling out that issue form. Also, make sure you are on the latest version before filing an issue.
