### ISSUE TITLE
support disabling aside in themeConfig

### ISSUE THREAD

**Issue by dominikcz** [vuejs/vitepress#1915]
### Describe the bug

Even when you set theme.outline = false vitepress still adds class has-aside and therefore content is unnecessary constrained to narrow space

### Reproduction

Set theme.outline to false to hide aside. Even thou it's not displayed it still ocupies space and therefore width of .VPDoc container is the same as with theme.outline

### Expected behavior

When aside is hidden it should free up space

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 5.57 GB / 15.80 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
This is intended. Aside contains more than outline.

> therefore content is unnecessary constrained to narrow space

This is also intended to prevent layout shifts on page switches.

**Comment by dominikcz** [comment]
I must admit that I fail to understand logic behind this decision:

- you agree that aside on front page is useless and therefore don't add `has-aside` class there
- you also agree that users, who want two-column layout on specific pages can use `frontmatter.aside = false` and then you respect that decision
- but when a user has hundreds of pages and basically wants a two-column layout everywhere you say it's not possible by design, forcing them to either use artificial frontmatter.aside on hundreds of pages or some tricks with styling to combat that design choice, instead of allowing a single setting like `outline=false`? Not really great DX if you ask me, unless there is some other way to do it that I'm not aware of?
- as for layout shifts between different pages you can prevent that with appropriate styling

If you are, however, worried about some backward compatibility, because someone already relies on that functionality, then maybe additional option would be better, like for example `theme.value.outline === 'remove'`?

**Comment by brc-dd** [comment]
Feel free to create a PR with supporting `theme.value.aside === false`. We should not remove the aside when just outline is disabled.

**Comment by dominikcz** [comment]
Thank you for understanding, will do that.
