### ISSUE TITLE
Exports alias

### ISSUE THREAD

**Issue by antfu** [vuejs/vitepress#192]
As mentioned in https://github.com/vuejs/vitepress/pull/190#issuecomment-750331742

Support exporting alias, for example

```js
import defaultTheme from 'vitepress/default-theme'
```

**Comment by kiaking** [comment]
@antfu Seems like this is [already done at here](https://github.com/vuejs/vitepress/blob/master/theme.d.ts). Could you double check if this is what you intended? 🤝

**Comment by antfu** [comment]
LTGM, thanks, closing
