### ISSUE TITLE
how to make siteConfig to support provide an function

### ISSUE THREAD

**Issue by Jimmylxue** [vuejs/vitepress#1922]
### Describe the bug

maybe it's not a bug, i want to realize an feature which will be in siteConfig to write an function, a demo as follow, but i can't get type of function value. 

i want to know how to resolve it,  i will looking forward to your reply~ thanks~

### Reproduction

a easy demo as follow:

i am define an object, which has attribute name and click:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/65758455/218239883-1dc3db06-c40f-4e7c-a43d-5149a9e8d01d.png">

next, i log site.value.onMounted in VitePressApp
<img width="495" alt="image" src="https://user-images.githubusercontent.com/65758455/218239966-604ab56a-e862-447b-a1d3-46b6eea8c7dc.png">

but in browser, only include attribute of name, click is missing.
<img width="875" alt="image" src="https://user-images.githubusercontent.com/65758455/218240082-e60d04b3-aeb9-4c8e-a1dc-4999770d3d0e.png">

### Expected behavior

i expect function type value of siteConifg can be receive in VitePressApp, which is key step in my feature idea .

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 133.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 15.6
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yyx990803** [comment]
You can put arbitrary value at the root level of the config. But if you put it in `themeConfig`, functions are now supported after #2058.
