### ISSUE TITLE
Focus in Code Blocks

### ISSUE THREAD

**Issue by glysns** [vuejs/vitepress#1926]
### Describe the bug

Focus in Code Blocks not working in my project, is it necessary anymore dependencies ?

### Reproduction

```js
export default {
  data () {
    return {
      msg: 'Focused!' // [!code  focus]
    }
  }
}
```

### Expected behavior

```js
export default {
  data () {
    return {
      msg: 'Focused!' // [!code  focus]
    }
  }
}
```

### System Info

```shell
windows
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You have to keep only space between code focus.
