### ISSUE TITLE
Markdown's anchor is case sensitive

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/vitepress#1927]
### Describe the bug

Hey, not sure if it's a bug or not, but the anchor in markdown seems not working if the case does not match.

In my PhpStorm and Typora, it works. In `GitHub README.md` preview, it works. But in VitePress it doesn't work.

### Reproduction

Hosted: (`.md` files are the same)

VitePress: https://docs.aelita.me/docs/vite-plugin-inject-html.html
~~GitHub: https://github.com/xsjcTony/vite-plugin-inject-html/tree/main/packages/vite-plugin-inject-html~~ (Removed anchors, so longer valid. But it's working on GitHub sites anyway)

Please try to click on either `externalStyleSheets` or `otherTags`, since they are in camelCase, it's not working in VitePress, no idea if it's a bug or expected behaviour. (Click on links in main content at the top, not the side bar)

### Expected behavior

It should jump to anchor, ignoring the case.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 42.08 GB / 63.84 GB
  Binaries:
    Node: 18.14.0 - C:\NodeJS\node.EXE
    Yarn: 1.22.19 - C:\NodeJS\yarn.CMD
    npm: 9.4.2 - C:\NodeJS\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-alpha.45 => 1.0.0-alpha.45
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by xsjcTony** [comment]
Yes I understand each anchor must be unique. Maybe I should rename the question to why VitePress auto converted my anchor to lowercase? In my source markdown it's `externalStyleSheet`, and I link the text to the exact anchor, but VitePress convert it to `externalstylesheet` which breaks my link

**Comment by xsjcTony** [comment]
Yeah I get it, but what's the purpose of forcing lower case? It's jusc forcing me to change every of my links to lower case, which doesn't make sense to me

**Comment by yyx990803** [comment]
1. VitePress just conforms to how HTML hash links work natively, which **is** case sensitive.
2. Different tools have different anchor generation conventions. VitePress lowercases everything by default. You can't expect anchor links to be handled the same way across every tool.

That said you can customize how anchors are generated:

```js
// .vitepress/config.js
export default {
  markdown: {
    anchors: {
      slugify: str => encodeURIComponent(str)
    }
  }
}
```
