### ISSUE TITLE
Referencing the third library has no effect after packaging

### ISSUE THREAD

**Issue by you-hengh** [vuejs/vitepress#1929]
### Describe the bug

I introduced a third-party library into the md document and loaded a vue component, which worked well in the dev environment

```html
<!-- docs/index.md -->
<script setup>
import NotSupportedAvif from './components/NotSupportedAvif.vue'
import bs from 'browser-tool'
// 判断浏览器类型 Determine the type of browser
const isSupportAvif = ()=> bs().browser === 'Edge'? true : false
</script>

<ClientOnly>
  <template v-if="isSupportAvif()">
    <NotSupportedAvif />
  </template>
</ClientOnly>
```
And I feel like `ClientOnly` doesn't seem to work. I'm not sure if it should be used here.

my package.json
```json
{
  "name": "vitepress",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "vitepress dev docs --open",
    "build": "vitepress build docs",
    "serve": "vitepress serve docs"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@algolia/client-search": "^4.14.2",
    "vitepress": "1.0.0-alpha.45"
  },
  "dependencies": {
    "browser-tool": "^1.0.3"
  }
}
```
`browser-tool` can do this:  Browser analysis / browser detection / browser identification / browser judgment / UA parsing-user agent, operating system information

All in all, the reason why I do this is that edge browsers do not support avif image format. I need to judge that if the user's browser is edge, it will remind users to change their browsers to read blogs for a better experience.

### Reproduction

If it's convenient for you, this is my repo:
https://github.com/you-hengh/myblog_vitepress

In short, in the development environment, there will be a notification when opening the homepage with edge browser.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/34816426/218310448-032c69bc-4c3f-44e3-997a-5080761fe69c.png">

But in a production environment, edge visits the home page without this notification, which is not normal.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/34816426/218310530-9b1f1aa7-e189-473d-9afe-0bccc7fc336d.png">

I don't know how to get it back to normal. Please help me.

### Expected behavior

It should be packaged and run as well as in the development environment.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/34816426/218309052-4642bae2-53da-43d6-aa98-50297732db1f.png">

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.39 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Chrome: 109.0.5414.119
    Edge: 109.0.1518.70
    Safari: 16.3
```

### Additional context

Working normally in the development environment:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/34816426/218309052-4642bae2-53da-43d6-aa98-50297732db1f.png">

But after packing, the work is not normal:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/34816426/218309239-ac091181-61c3-4546-96c9-45c67d231369.png">

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by tolking** [comment]
[doc](https://vitepress.vuejs.org/guide/using-vue#browser-api-access-restrictions)

**Comment by you-hengh** [comment]
> Maybe you should import browser-tool like the below
> 
> ```
> <script>
> export default {
>   mounted() {
>     import('./lib-that-access-window-on-import').then((module) => {
>       // use code
>     })
>   }
> }
> </script>
> ```
> 
> [doc](https://vitepress.vuejs.org/guide/using-vue#browser-api-access-restrictions)

I read the document, but I was too stupid to understand the document case. I reintroduced the third-party library according to the document case locally and reported more mistakes.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/34816426/219257543-ecdf65b8-2d39-4aac-b7d8-cad99ffa67fa.png">

I have opened up my repo, can you help me look at it if it is convenient?

**Comment by tolking** [comment]
The isSupportAvif is not defined in data

**Comment by brc-dd** [comment]
Even if you make that thing work, what's even the logic behind doing that? Feature detection should not be done like this (https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent). Use fallback image sources for browsers that don't support modern formats (https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#providing_image_fallbacks).

To make that library work, something like this should suffice:

```html
# Browser Test

{{ browser }}

<script setup>
import { onMounted, ref } from 'vue'

const browser = ref('')

onMounted(() => {
  import('browser-tool').then(mod => {
    browser.value = mod.default().browser
  })
})
</script>

```
