### ISSUE TITLE
resolvePageImports error in win32, missing normalizePath (vite2)

### ISSUE THREAD

**Issue by matias-capeletto** [vuejs/vitepress#193]
In [node/build/render.ts](https://github.com/vuejs/vitepress/blob/600605be09325e4bbe5fa7e9ffc8fef0ad810dc7/src/node/build/render.ts#L91), `resolvePageImports` `srcPath` in win32 is not normalized as is in Vite, so the find fails.

```ts
  const srcPath = path.resolve(config.root, page) // <= missing normalizePath(...)
  const pageChunk = result.output.find(
    (chunk) => chunk.type === 'chunk' && chunk.facadeModuleId === srcPath
  ) as OutputChunk
  return Array.from(new Set([...indexChunk.imports, ...pageChunk.imports]))
```

`facadeModuleId` is normalized in Vite using [`normalizePath` from src/node/utils.ts.](https://github.com/vitejs/vite/blob/0c0bc4a33c99da22be96214af872344f930732d4/packages/vite/src/node/utils.ts#L55)

I think that Vite could export this utility function so there is no need to duplicate it in Vitepress. If it is helpful, I could send PRs to vite/2.0 and vitepress/vite2.

**Comment by bluepower** [comment]
This issue is high priority for windows vitepress/vite2 users...
