### ISSUE TITLE
algolia Search can’t return result

### ISSUE THREAD

**Issue by Richard-Zhang1019** [vuejs/vitepress#1935]
### Describe the bug

Since the "alpha.37" version, the normal algolia search has not returned results, probably because i18n has been supported, there are some changes in the path, and there is a problem with the search request parameters. I tested that there is no problem before the "alpha.36" version. Algolia after application can return search results, ordinary algolia cannot

### Reproduction

pnpm add --save vitepress

### Expected behavior

search should return result

### System Info

```shell
Chrome
```

### Additional context

https://lucky-design.vercel.app/  
This is my url, using the "alpha.45" version

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hey can you try re-running the crawler from Algolia's console? It seems that it has not indexed pages with facetFilters yet.

**Comment by Richard-Zhang1019** [comment]
> 

ok guys wait me to try

**Comment by Richard-Zhang1019** [comment]
> Hey can you try re-running the crawler from Algolia's console? It seems that it has not indexed pages with facetFilters yet.

algolia‘s console is ok. because when I use ”alpha.36“ version to search is ok, but when I use "alpha.45" to search is not return result 
<img width="780" alt="image" src="https://user-images.githubusercontent.com/76982270/218466089-43270baf-4f6f-45f3-8001-37b617cf349c.png">
because when I search request will take the field "lang: en-US"

**Comment by brc-dd** [comment]
But the issue here is it has not indexed your site after alpha.45 upgrade. That language is now there in the generated HTML (`<html lang="en-US">`). So it should be able to pick up.

**Comment by Richard-Zhang1019** [comment]
> I had the same issue. You need to fix your scraper/crawler config (cf. property `"lang"` and `"custom_settings"`).
> 
> Here's mine. Hope it helps.
> 
> ```json
> {
>   "index_name": "*******",
>   "start_urls": ["*******"],
>   "stop_urls": ["*******"],
>   "selectors": {
>     "lvl0": {
>       "selector": "",
>       "default_value": "Documentation"
>     },
>     "lvl1": ".content h1",
>     "lvl2": ".content h2",
>     "lvl3": ".content h3",
>     "lvl4": ".content h4",
>     "lvl5": ".content h5",
>     "text": ".content p, .content li",
>     "lang": {
>       "selector": "/html/@lang",
>       "type": "xpath",
>       "global": true
>     }
>   },
>   "strip_chars": " .,;:#",
>   "selectors_exclude": [".sr-only"],
>   "custom_settings": {
>     "attributesForFaceting": ["lang", "tags"]
>   }
> }
> ```

thanks guys， I just now to test with your code, that's solved my problem，

**Comment by brc-dd** [comment]
Added a crawler config example in docs. That should work for newcomers.
