### ISSUE TITLE
Extending PageData with the transformPageData hook using a new property causes TS to complain

### ISSUE THREAD

**Issue by staghouse** [vuejs/vitepress#1937]
### Is your feature request related to a problem? Please describe.

Consider the following:

**config.js**
```js
const pages = [];

export default {
  transformPageData() {
    return {
      pages: await pages,
    }
  }
}
```

**component.ts**
```ts
<script setup lang="ts">
  import { useData } from 'vitepress';

  const { page } = useData();

  const pages = page.value.pages;
</script>
```

`const pages = page.value.pages;` will fire a TS error that `pages` does not exist on type PageData

### Describe the solution you'd like

Add a field to the interface `PageData` like `customData` that is of type `any` so a user can assign any value to this field without a warning from TS

### Describe alternatives you've considered

Using `const pages = page.value['pages'];` resolves the error.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can use module augmentation for that 👀
