### ISSUE TITLE
split `dist/assets` and file them into appropriate subfolders

### ISSUE THREAD

**Issue by manchan4869** [vuejs/vitepress#1938]
### Is your feature request related to a problem? Please describe.

The `assets` in `dist` is too messy. I want to get an organized `dist`

### Describe the solution you'd like

when i try to use `build.rollupOptions.output.assetFileNames` in `vite.config.js`, it doesn't  take effect

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by yyx990803** [comment]
They are just built files, this is not something we will spend time on.
