### ISSUE TITLE
Latest version of VitePress is not respecting `vite.config.ts`

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/vitepress#1939]
### Describe the bug

The latest version of VitePress is not respecting `vite.config.ts` in my project (a very mini one). It's working in the stackblitz template, but my project structures a little bit differently (the `docs` folder is the root) so I'm not sure if it's a bug or it's intended.

If someone can please clone and have a look, it's really appreciated.

And also, seems documentation of customizing `Vite`'s configuration is missing in the docs

### Reproduction

https://github.com/xsjcTony/docs

I've put `vite.config.ts` in both root and under `.vitepress` but none of them works.
Thanks a lot for the help!

### Expected behavior

It should pick up either `vite.config.ts` (either at the root or in `.vitepress` folder, I think it should pick the one at the root)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 42.69 GB / 63.84 GB
  Binaries:
    Node: 18.14.0 - C:\NodeJS\node.EXE
    Yarn: 1.22.19 - C:\NodeJS\yarn.CMD
    npm: 9.4.2 - C:\NodeJS\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-alpha.46 => 1.0.0-alpha.46
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It should be inside your specified `srcDir`.

**Comment by xsjcTony** [comment]
Thanks for that. It would be really helpful if both of above can be explicitly listed in the docs🥰

**Comment by yyx990803** [comment]
It is now recommended to configure Vite directly via the [`vite` option](https://vitepress.dev/reference/site-config#vite) in your VitePress config, so that they are collocated.
