### ISSUE TITLE
Multi-line HTML table throws `Element is missing end tag`

### ISSUE THREAD

**Issue by bojanrajh** [vuejs/vitepress#1940]
### Describe the bug

HTML table (`td`) with extra newline throws `Error is missing end tag`. Row is transpiled to:

```html
<tr>
    <td>Foo</td>
    <td>Multi
<p>Line</td></p>
  </tr>
```

`</td>` and `</p>` should be reversed.

### Reproduction

See example on [StackBlitz](https://stackblitz.com/edit/vite-js5myp?file=docs/broken.md).

### Expected behavior

It should work as shown on the `Works` example, with single new line.

Broken example:
```html
<table>
  <tr>
    <th>Foo</th>
    <th>Bar</th>
  </tr>
  <tr>
    <td>Single-line</td>
    <td>Multi

Line</td>

  </tr>
  </table>
```

Working example:
```html
<table>
  <tr>
    <th>Foo</th>
    <th>Bar</th>
  </tr>
  <tr>
    <td>Single-line</td>
    <td>Multi
Line</td>

  </tr>
  </table>
```

Markdown rendering:
<table>
  <tr>
    <th>Foo</th>
    <th>Bar</th>
  </tr>
  <tr>
    <td>Single-line</td>
    <td>Multi

Line</td>

  </tr>
  </table>

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vitepress: latest => 1.0.0-alpha.46
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That's expected. You have empty lines separating that `Line</td>` part. It'll be rendered as a separate block as per the commonmark spec.

**Comment by bojanrajh** [comment]
Thanks, you are again correct. :)
For future reference: https://spec.commonmark.org/0.30/#html-blocks

> Start condition: line begins the string < or </ followed by one of the strings (case-insensitive) address, article, aside, base, basefont, blockquote, body, caption, center, col, colgroup, dd, details, dialog, dir, div, dl, dt, fieldset, figcaption, figure, footer, form, frame, frameset, h1, h2, h3, h4, h5, h6, head, header, hr, html, iframe, legend, li, link, main, menu, menuitem, nav, noframes, ol, optgroup, option, p, param, section, source, summary, table, tbody, td, tfoot, th, thead, title, tr, track, ul, followed by a space, a tab, the end of the line, the string >, or the string />.
> **End condition: line is followed by a [blank line](https://spec.commonmark.org/0.30/#blank-line).**
