### ISSUE TITLE
按照官网例子安装项目启动报错

### ISSUE THREAD

**Issue by PLUTO06210331** [vuejs/vitepress#1945]
### Is your feature request related to a problem? Please describe.

按照官网步骤执行：
mkdir vitepress-starter && cd vitepress-starter
npm init
yarn add -D vitepress vue
mkdir docs && echo '# Hello VitePress' > docs/index.md

然后配置
{
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:preview": "vitepress preview docs"
  },
}
执行
npm run docs:dev

报错
![image](https://user-images.githubusercontent.com/33271366/219038792-0bc53123-7085-4be0-a16d-af63ea59c857.png)

### Describe the solution you'd like

我想要正常启动成功

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by PLUTO06210331** [comment]
把版本号换成0.22.4之后就不报错了，但是不知道是不是这个问题

**Comment by awxiaoxian2020** [comment]
你用了两种包管理器，用一种试试

**Comment by kiaking** [comment]
OK, so I guess this is solved...? I'll close this for now but if the issue remains, let us know.
