### ISSUE TITLE
Show external link icons in navbar

### ISSUE THREAD

**Issue by RaniAgus** [vuejs/vitepress#1948]
### Is your feature request related to a problem? Please describe.

I would like to include some external links in a navbar, but they don't look like they are external, so it might be confusing:

![image](https://user-images.githubusercontent.com/39303639/219230074-f79509b5-7588-4739-bb88-0849700909d0.png)

### Describe the solution you'd like

It would be nice to include the external link icon when the link isn't a reference to the page, just like in a sidebar:

![image](https://user-images.githubusercontent.com/39303639/219230014-184c72ee-6ec7-45cc-bb15-ddca1591d54c.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by meedfine** [comment]
pr https://github.com/vuejs/vitepress/pull/1881
