### ISSUE TITLE
Multithreaded rendering

### ISSUE THREAD

**Issue by Pandapip1** [vuejs/vitepress#1952]
### Is your feature request related to a problem? Please describe.

Currently, it takes 80 seconds to build a website with over 500 pages.

### Describe the solution you'd like

I would like it to take less than 80 seconds to build a website with over 500 pages. Considering my computer has pretty good threading, I propose that https://www.npmjs.com/package/thread-puddle be used to significantly reduce rendering time.

### Describe alternatives you've considered

Optimize the render function even more? There's only so much optimization that can be done!

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by yyx990803** [comment]
This would have to be implemented at Vite level, so not really something we can do in VitePress.
In terms of performance, incremental builds would probably provide more significant benefits, and is something we will explore in the future.
