### ISSUE TITLE
KeepAlive does not seem to work

### ISSUE THREAD

**Issue by oscar6echo** [vuejs/vitepress#1958]
### Describe the bug

> First I'm not sure it's a bug, maybe a feature.  

I had expected that vue3 [KeepAlive](https://vuejs.org/guide/built-ins/keep-alive.html) work in vitepress.  
But it does not seem to be the case - off the shelf at least.

Is there a way to make it work ?   
That would make vitepress even better !

### Reproduction

Steps:

+ Have component counter below in one page.
+ Increase counter
+ Navigate to other page, come back
+ Counter is reset to zero as component was re initialized

page:
```md
// mypage.md

# My Title

bla bla

<Counter />

<script setup lang="ts">
import Counter from  '../.vitepress/components/Counter.vue'
</script>
```

counter:
```vue
// Counter.vue

<template>
  <button @click="increment">Count is: {{ count }}</button>
</template>

<script setup lang="ts">
import { ref } from "vue";

const count = ref(0);

const increment = () => {
  count.value++;
};
</script>
```

### Expected behavior

The counter keeps its state as user navigates from one page to another.  
Initialization takes place either upon landing on vitepress site, or better, landing on specific page.

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 23.93 GB / 31.07 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 110.1.48.164
    Chrome: 110.0.5481.100
    Firefox: 110.0
  npmPackages:
    vitepress: 1.0.0-alpha.46 => 1.0.0-alpha.46
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by MarkusKeck** [comment]
@oscar6echo Where in your example do you use `<KeepAlive>`?
I am not sure if `KeepAlive` only works with dynamic components, I have to check that.

```html
<!-- Inactive components will be cached! -->
<KeepAlive>
  <component :is="activeComponent" />
</KeepAlive>
```

**Comment by oscar6echo** [comment]
@MarkusKeck thx for the super fast response - much appreciated !

For now I use `<KeepAlive>` in a vitepress markdown file.   
I will try in the vue component file itself.

To answer your question, I use `<KeepAlive>` in a regular vue app without dynamic components and it does work as expected.

**Comment by oscar6echo** [comment]
I did the test with this modified component:

```vue
// .vitepress/components/Counter.vue

<template>
  <keep-alive>
    <button @click="increment">Count is: {{ count }}</button>
  </keep-alive>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";

const count = ref(0);

const increment = () => {
  count.value++;
  console.log(count.value);
};

onMounted(() => {
  console.log("onMounted");
  console.log(count.value);
});

onUnmounted(() => {
  console.log("onUnmounted");
});
</script>
```

Then I see that `<keep-alive>` has no effect, probably because `onUnmounted()`/`onMounted()` is triggered after each navigation away from / back to the page.

It seems like the default vitepress behavior.   
So then the question would be: how to change that ?

**Comment by MarkusKeck** [comment]
Thanks for clarification, I will try to reproduce it on my end.

**Comment by oscar6echo** [comment]
@MarkusKeck Could you make any progress ?

I tried to manually (by updating file in node_modules) wrap the `theme-default/Layout.vue` [template](https://github.com/vuejs/vitepress/blob/288aa48b92bc1d4dd74d064148a3b03373cdf1c3/src/client/theme-default/Layout.vue#L29) in `<keep-alive>`:

```vue
<template>
<h1>TEST</h1>
<keep-alive>
  <div v-if="frontmatter.layout !== false" class="Layout">
    <slot name="layout-top" />
    <VPSkipLink />
    <VPBackdrop class="backdrop" :show="isSidebarOpen" @click="closeSidebar" />
    .....
    <VPFooter />
    <slot name="layout-bottom" />
  </div>
  <Content v-else />
</keep-alive>
</template>
```
The "TEST" title is visible, which proves this template is used.   
However the `Counter` component keeps being mounted/unmounted upon navigation.  

Moreover I observer that events `activated` and `deactivated` are triggered only if `Counter` is directly wrapped in `<KeepAlive>` (as described above).  

I don't understand as it does not seem to match the [vue3 keepalive documentation](https://vuejs.org/api/built-in-components.html#keepalive):
"When a component is toggled inside <KeepAlive>, its activated and deactivated lifecycle hooks will be invoked accordingly, providing an alternative to mounted and unmounted, which are not called. This applies to the direct child of <KeepAlive> **as well as to all of its descendants**."

What exactly do I miss in the behavior of the keepalive component ? 


---

Generally, irrespective of how it could be done, I think it would be good if vitepress [frontmatter config](https://vitepress.vuejs.org/config/frontmatter-config) had a `keepalive` variable indicating where a page would not unmounted upon navigation away, with default below to keep current behavior unchanged:

```yaml
---
keepAlive: false
---
```

What do you think ?

**Comment by yyx990803** [comment]
`<KeepAlive>` can only work when wrapping a single, direct component child, however the `<Content />` component is another layer that wraps the actual page component, so I don't think there is a way to make it work at the theme level.

I also don't really think this is a good idea, as the page switch is already fast enough, and you will be storing many DOM nodes in memory. If your need is mainly to persist state across pages, using a store is the correct and more efficient solution.

**Comment by oscar6echo** [comment]
@yyx990803 thx for the clarification.  

In the meantime I had used a pinia store and in fact I am satisfied with this way of keeping track of the state as it is more explicit and can be fine tuned to specific cases.
