### ISSUE TITLE
vitepress build fails with pinia

### ISSUE THREAD

**Issue by oscar6echo** [vuejs/vitepress#1959]
### Describe the bug

> It is a bug only if using pinia is considered possible with vitepress - which I hope!

When I `vitepress build` I see that, surprisingly, my pinia store tries to download data from `/public` and naturally the subsequent processing fails.  
Note that it works fine in dev mode.  

How to avoid pinia to download data at build time ?

### Reproduction

Steps:
+ create pinia store:

```ts
// .vitepress/theme/index.ts

import { EnhanceAppContext } from "vitepress";
import DefaultTheme from "vitepress/theme";

import { createPinia } from "pinia";
import "./custom.css";

export default {
  ...DefaultTheme,
  enhanceApp(ctx: EnhanceAppContext) {
    DefaultTheme.enhanceApp(ctx);

    const pinia = createPinia();
    ctx.app.use(pinia);
  },
};
```

+ implement a pinia store:
```ts
// .vitepress/store/mystore.ts

import { defineStore } from "pinia";
import { withBase } from "vitepress";

const useMyStore = defineStore("mystore", {
  state: (): {
    started: boolean;
    data: IData;
  } => ({
    data,
  }),
  getters: {},
  actions: {
    async loadData(): Promise<void> {
      if (this.started) {
        console.log("nothing to do");
        return;
      }
      this.started = true;
      this.data = await loadData();
    },
  },
});

const loadData = async (): Promise<IData> => {
  const dataUrl = withBase(`/data/mydata.json`);
  const result = await fetch(dataUrl);
  const data: IData = await result.json();
  const value = buildValue(data);
  return value;
};

export { useMyStore }
```
+ use store in page:

```md
// mypage.md

# My title

bla bla

<script setup lang="ts">
import { useMyStore } from '../.vitepress/store/mystore.ts'
const store = useMyStore()
store.loadData()
</script>
```

### Expected behavior

It works fine, like in dev.   
The pinia store does not try to download data at build time.  

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 23.93 GB / 31.07 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 110.1.48.164
    Chrome: 110.0.5481.100
    Firefox: 110.0
  npmPackages:
    vitepress: 1.0.0-alpha.46 => 1.0.0-alpha.46
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by oscar6echo** [comment]
@brc-dd  Thx for the swift reply !  
Yes it does work :+1: 

I'll add some extra tips for future readers:

+ to type variable `store`:
```ts
let store: ReturnType<typeof useMyStore>;
```
+ beware to manages the initial case when `store is not defined` with:
```ts
// example:
if (!store) return <an empty object of your choice>;
// example:
const data = store?.data;
```
If you don't it may crash with no error msg, like:
```
  vitepress v1.0.0-alpha.46

✓ building client + server bundles...
⠋ rendering pages...(node:39495) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
root index
✖ rendering pages...
build error:

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by brc-dd** [comment]
> If you don't it may crash with no error msg, like:

Ah, I'll fix this. It's a typo actually when we switched to vite logger.

BTW, there is an alternative too. If you can move that logic to a separate component, then you can directly use `<ClientOnly>`.

**Comment by oscar6echo** [comment]
@brc-dd  Thx for the additional useful info !

I tried and confirms it works in my case too.

I'll add the ref in the doc [ClientOnly](https://vitepress.vuejs.org/guide/api#clientonly) as it also reminds readers of the **default SSR** behavior.
