### ISSUE TITLE
Command line not exiting

### ISSUE THREAD

**Issue by lch3830638** [vuejs/vitepress#1974]
### Describe the bug

After the build is complete, the command line does not exit and cannot proceed to the next command

### Reproduction

version: v1.0.0-alpha.47 pnpm docs:build

### Expected behavior

After the build is complete, continue to execute and write a command

### System Info

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 16.42 GB / 31.83 GB
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Closing as stale.
