### ISSUE TITLE
After logging in with Auth0 on Vitepress, the outline content does not appear

### ISSUE THREAD

**Issue by donnimsifa** [vuejs/vitepress#1979]
### Describe the bug

I implemented Auth0 into Vitepress and after successfully implementing it and logging in, the outline on the side that should appear is not showing up at all.

I apologize for my lack of knowledge in this matter. I am very grateful for your assistance and response to this bug reporting.

### Reproduction

I followed the guide from https://qiita.com/SatoshiGachiFujimoto/items/0aebbf0ea54e955bd87a and the result is:
https://github.com/donnimsifa/auth0tovite
https://auth0tovite.vercel.app/

### Expected behavior

The outline should not appear before logging in, but after logging in, the outline should appear.

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (4) x64 Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
    Memory: 90.53 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 109.0.1
    Safari: 16.3
```

### Additional context

For now, I want to hide the outline section from the page so that my content can be centered and wider, how can I do that?
Also, there's an optional matter regarding the dark mode button on the top right corner. On the website, I'm not using a navbar at all, how can I disable the hamburger and just make it a dark mode button when accessed through mobile?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by donnimsifa** [comment]
[test the auth0 login here](https://auth0tovite.vercel.app/test/)
mail : auth@vite.id
pass : auth@vite

**Comment by donnimsifa** [comment]
[test the auth0 login of my vercel site here](https://auth0tovite.vercel.app/test/)
mail : auth@vite.id
pass : auth@vite

**Comment by yyx990803** [comment]
I think this should work properly now in alpha.54+ since the outline logic has been rewritten.

**Comment by maisterr** [comment]
> I think this should work properly now in alpha.54+ since the outline logic has been rewritten.

Unfortunately, it isn't working on `^1.0.0-alpha.60`. Is there any way to update a page after successful authorization?
