### ISSUE TITLE
[VuePress HMR] Not Support Hot Update Jsx / Tsx code

### ISSUE THREAD

**Issue by NaCoLiu** [vuejs/vitepress#1985]
### Describe the bug
When change code Tsx file and save, hmr not support hot update watch.
![image](https://user-images.githubusercontent.com/42311502/221028484-f28469e6-8d5f-4c86-9c63-d531c84e3c4e.png)

### Reproduction

null

### Expected behavior

Support Jsx / Tsx HMR 

### System Info

```shell
null
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by MarkusKeck** [comment]
duplicate https://github.com/vuejs/vitepress/issues/117

**Comment by NaCoLiu** [comment]
It has been resolved in the new version.
