### ISSUE TITLE
Build Error: Not Support {{}} in ``

### ISSUE THREAD

**Issue by zhengyulong-cn** [vuejs/vitepress#1988]
### Describe the bug

I locate the problematic line by commenting. When `{{ }}` appears, Vitepress parses the code block in the `` line incorrectly.
For example:
```jsx
<div style={{ opacity: 1}}/>
```

### Reproduction

null

### Expected behavior

Support to use `{{}}` in `` inline code blocks.

### System Info

```shell
null
```

### Additional context

![image](https://user-images.githubusercontent.com/50773846/221162312-05548af5-16b9-485c-8f48-7341af8d56e8.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
This is expected. `{{}}` is used for interpolation. You can escape this by doing:

```md
::: v-pre
`<div style={{ opacity: 1 }}/>`
:::
```

Docs -> https://vitepress.vuejs.org/guide/using-vue#escaping
