### ISSUE TITLE
Internal server error: Import error in the demo container.

### ISSUE THREAD

**Issue by Norn3** [vuejs/vitepress#1990]
### Describe the bug

When I want to import, I find that it will report an error.
![image](https://user-images.githubusercontent.com/120736597/221173422-b5b37402-c22f-4a30-aff3-b6dd1adce0a3.png)
I see that the document is imported in this way.
![image](https://user-images.githubusercontent.com/120736597/221173812-e452256f-8816-4f46-8e78-e7406e34b158.png)
Is there anything wrong？Why doesn't it happen when I import from vue？

### Reproduction

After I created the project based on the document, I only installed 'vitepress-theme-demoblock'.
These are my configurations：
![image](https://user-images.githubusercontent.com/120736597/221173005-23a08259-ae37-4776-ae96-96f9d07931f2.png)
![image](https://user-images.githubusercontent.com/120736597/221173060-a20999b4-577d-4175-abfa-133a7f54ee9b.png)
And then it happended.

### Expected behavior

I was about to import some custom objects in the demo, but I found that even useData cannot be imported.

### System Info

```shell
[vitepress] Internal server error: Transform failed with 1 error:
E:/Draculabo/min-vitepress/vitepress-starter/docs/components/test.md:22:7: ERROR: Unexpected "{"
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's an issue with that plugin/theme that you're using. Not vitepress itself.
