### ISSUE TITLE
Uncaught Error: useRouter() is called without provider

### ISSUE THREAD

**Issue by Guebbit** [vuejs/vitepress#1992]
### Describe the bug

```
import { useRouter } from 'vitepress';
const router = useRouter();

```
This code used in ".vitepress\theme\index.js" cause the following error: "Uncaught Error: useRouter() is called without provider". 

### Reproduction

Literally as described

### Expected behavior

To be able to use the router to watch the route change

### System Info

```shell
vitepress 1.0.0-alpha.47
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vuejs.org/guide/reusability/composables.html#usage-restrictions
