### ISSUE TITLE
Development Mode not working

### ISSUE THREAD

**Issue by miili** [vuejs/vitepress#1996]
### Describe the bug

When building a project from scratch following https://vitepress.vuejs.org/guide/getting-started the `development` mode is dysfunctional.

The `vitepress` command comes through but the server is not responsive. The port is not open.

It would be great to have more verbosity, like `--debug` flag.

`vitepress build` and `preview` works like a charm!

### Reproduction

Follow the instructions, start dev.

### Expected behavior

Serve the page with HRM.

### System Info

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 315.41 MB / 7.68 GB
    Container: Yes
    Shell: 3.1.2 - /usr/bin/fish
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Chromium: 104.0.5112.79
    Firefox: 91.13.0esr
  npmPackages:
    vitepress: ^1.0.0-alpha.48 => 1.0.0-alpha.48
```

### Additional context

none

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Please provide reproduction code. I can't reproduce. Maybe your port 5173 is used by other system? Preview uses different port so I kinda guess your 5173 is blocked.
