### ISSUE TITLE
file inclusion escapes details block if included file also has some :::info::: block

### ISSUE THREAD

**Issue by jtgober** [vuejs/vitepress#2000]
### Describe the bug

When using [file inclusion](https://vitepress.vuejs.org/guide/markdown#markdown-file-inclusion) within a details block, if the file that is being included also has a :::block:::, the included file escapes the :::details::: block.
![Details about bug](https://user-images.githubusercontent.com/57597859/221600839-2f5da377-3c73-4783-868d-4a26db15d38c.png)
![bug details 2](https://user-images.githubusercontent.com/57597859/221600854-5eecc0a8-d5a5-4854-bfdd-60ab320763b4.png)

### Reproduction

Create a markdown file (file-a.md) with an :::info::: block
create a new md file (file-b.md). add a details block.
within the details block, use file inclusion to add file-a.md to the details block. 

`:::details

:::`

### Expected behavior

Should stay within the details block, instead escapes.

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 17.32 GB / 31.73 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.48 => 1.0.0-alpha.48
```

### Additional context

n/a

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Hmmm, so this is about nested custom container issue... right? I'm not sure we would want support that 🤔 How would you like it to be displayed?

**Comment by jtgober** [comment]
I just figured they would be contained within the block instead of spilling out. I think got that working with a details container + a code block 😀.

**Comment by kiaking** [comment]
Hah, how would that look like? 👀 Just curious.

**Comment by jtgober** [comment]
Actually I goofed I was thinking something else that had nothing to do with file inclusion. That's on me haha. I have a code block in a details block

https://www.documentation-biome.xyz/days/day8/api-final

**Comment by jtgober** [comment]
The file inclusion thing is still was wonky. But if that is expected I understand

**Comment by kiaking** [comment]
Nice. It's looking great 👍  So, maybe we should add note on "Markdown File Inclusion" section that try not importing external file that contains custom block 👀 

Because, even if we fix the leaking stuff, the design will brake anyway because custom containers are not meant to be nested 😅

**Comment by jtgober** [comment]
That could be fine. It's not a huge deal and I could work around it. 😀. Much appreciated!

**Comment by kiaking** [comment]
👍

**Comment by brc-dd** [comment]
You need to change nesting level for this to work. Example:

Say you're including `bar.md` into `foo.md`, and `bar.md` has maximum `::: block` (3 colons), you need to make the block in `foo.md` have 4 or more colons (2 colon will also work if no two colon block is there in `bar.md`

```md
:::: details

<!-- @include: ./bar.md -->

::::
```

Refer: https://github.com/markdown-it/markdown-it-container/issues/6#issuecomment-213789283
