### ISSUE TITLE
Add the ability to define additional pages for a language

### ISSUE THREAD

**Issue by azat-io** [vuejs/vitepress#2001]
Let's imagine we have a website with the following configuration:

```ts
export default defineConfigWithTheme({
    cleanUrls: true,

    locales: {
      root: {
        lang: 'en',
        link: '/en',
      }
      ru: {
        lang: 'ru',
        link: '/ru',
      }
    }
})
```

There are English and Russian versions.

`site.com` - English page
`site.com/en/some-page` - English
`site.com/ru/some-page` - Russian
`site.com/ru/` - Russian
`site.com/ru` - English 😞 

Is there a way to determine the language for the last page?
This seems like expected behavior.

**Comment by kiaking** [comment]
Just to be clear, you want `site.com/ru` to be English page, right? 👀

**Comment by azat-io** [comment]
@kiaking No, this is the current behavior

**Comment by brc-dd** [comment]
Why exactly is this a requirement?

If you've a file like `/ru/index.md`, opening `/ru` will redirect to `/ru/` automatically.

**Comment by brc-dd** [comment]
Try in production. For dev you need to open `/ru/`. Also, remove links from config or make them `/en/` and `/ru/`. 

https://stackblitz.com/edit/vite-donu8y
