### ISSUE TITLE
Aside/Outline TOC renders headings in nested elements but does not properly trace them

### ISSUE THREAD

**Issue by staghouse** [vuejs/vitepress#2003]
### Describe the bug

When nested a heading inside, say, a blockquote on a markdown page, the Aside Outline will see these headings but not properly scroll them in the Outline as active. Instead only the last item will be highlighted and active

### Reproduction

Create a markdown file with:

```md
> ### test
>
> some blockquote text
```

Adjust the config file themeConfig to have `outline: 3`

### Expected behavior

The Aside Outline should show the heading, which it does, and should mark it as active when it is active.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 73.67 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 110.0
    Safari: 15.2
  npmPackages:
    vitepress: 1.0.0-alpha.48 => 1.0.0-alpha.48
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Can't reproduce. Can you provide the actual reproduction code? Here's how I tested. The outline is active on "Example Heading" which is inside a blockquote.

<img width="1256" alt="Screenshot 2023-02-28 at 10 00 38" src="https://user-images.githubusercontent.com/3753672/221724977-3f367863-ad93-463d-92cb-9e3ef452b0ed.png">

**Comment by staghouse** [comment]
@kiaking Did you also add `outline: 3` to themeConfig as well? There is even some funkiness happening on my end when i mix blockquotes with nested h3's and just regular un-nested h3's all at the same time as a sort of test - it seems like the outline doesnt know what to do with that kind of mixture.

At any rate, here's the project (it's public): https://github.com/mtgjson/mtgjson-website/ and the branch name is `NS/style_vitepress_theme`. There's a few utility scripts that run when you bring up the dev server but you can bypass all that after `npm install` with `npm run dev:bare`.

Here too is a screenshot of the general misbehavior im seeing:

<img width="1127" alt="Screen Shot 2023-02-27 at 11 21 52 PM" src="https://user-images.githubusercontent.com/1939508/221753113-db360020-43a8-4e36-b586-03756a1de5b5.png">

You can see although im near the top of the page with the first blockquote the outline says the last item is active.

**Comment by staghouse** [comment]
@kiaking I found the issue. `position: relative` on blockquote selector was causing the issue - not sure why though.

**Comment by kiaking** [comment]
I still can't reproduce it with `outline: 3`. You can see that `test` is active and seems like it's in correct scrolling position.

Not sure why `position: relative` relates, but it looks like this is affected by your custom theme...? Can you workaround this by overriding `position: relative` at your side?

Would be hard to do anything if we can't reproduce this in default theme 🤔 

<img width="1005" alt="Screenshot 2023-03-01 at 8 11 43" src="https://user-images.githubusercontent.com/3753672/222003742-4358d660-dc24-4d55-ae5b-194661d04931.png">

**Comment by staghouse** [comment]
Yea it's odd that that style would break the behavior but for now I've just set that aside in favor of some other styling (I had an absolute element inside it but I'm just gonna use it differently since the outline is a very nice feature)

**Comment by kiaking** [comment]
Gotcha. Great you found out the workaround 😃 Feel free to open other issues if you find anything 👍
