### ISSUE TITLE
Direct link to page showing duplicated sections in the content

### ISSUE THREAD

**Issue by patak-dev** [vuejs/vitepress#201]
Starting from https://vitepress.vuejs.org, you can navigate to the `Markdown Extensions` section and it properly works:

![image](https://user-images.githubusercontent.com/583075/103703486-e67cbf80-4fa7-11eb-96f7-74a2159490d1.png)

But reloading the page, or directly visiting https://vitepress.vuejs.org/guide/markdown.html is showing duplicated content:

![image](https://user-images.githubusercontent.com/583075/103703407-ccdb7800-4fa7-11eb-9f39-ca3c3dfc6c4c.png)

**Comment by kiaking** [comment]
Oh yeah... hmmm... we must look into this. We're getting `Hydration completed but contains mismatches.` error in the console. I can only find this error in https://vitepress.vuejs.org/guide/markdown.html so markdown example should be the one causing it...? Need to to investigation.

**Comment by sampullman** [comment]
I'm not sure if it's the exact same problem, but I get weird issues using `[[toc]]` where some sections are moved around or removed entirely. Similarly, it only happens when I refresh or visit directly, and only in the final build (not when served from `vitepress dev docs`

**Comment by sampullman** [comment]
You can see this behavior in the Vitepress docs as well: https://vitepress.vuejs.org/guide/markdown.html#table-of-contents

When that page is loaded directly you get the "hydration mismatch" error (and the TOC is missing), but loading another page and navigating to the markdown section works fine.

**Comment by stefandesu** [comment]
I have this problem as well. All pages that contain JavaScript show "Hydration completed but contains mismatches." when loaded directly. For example: https://gbv.github.io/jskos-vue/dev/components/ItemDetails.html

Interestingly, it works when navigating to the page from another site, but not if I simply go back and forth. Only the page that got initially loaded stays broken.

**Comment by JeremyWuuuuu** [comment]
@patak-js Any idea what causes this? Having the same issue of duplicated sections and component lost.

**Comment by seonglae** [comment]
` Hydration completed but contains mismatches.` error occurs when I deployed vitepress to vercel with custom dns

**Comment by blurgyy** [comment]
Building with mpa mode (e.g. `yarn vitepress build --mpa`) seems to solve this issue, as well as mentioned in #388

**Comment by seonglae** [comment]
In my case, mpa mode not working

https://intuiter.seongland.com/

**Comment by vmihailenco** [comment]
`--mpa` helps but it breaks client code that uses JS...
