### ISSUE TITLE
image not display at previewing

### ISSUE THREAD

**Issue by SmallWolf1993** [vuejs/vitepress#2013]
### Describe the bug

image not display at previewing, but replace with base64 string, it is ok ！
![picture](https://user-images.githubusercontent.com/52949537/222028122-083bcbc7-dc5d-4470-814d-e060f205315d.png)

### Reproduction

1. use `layout:home`  in the index page
2. configure the Hero section
3. run `npm run docs:build` then `npm run docs:docs:preview` 
4. to preview the website

### Expected behavior

can display the image by file path

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
    Memory: 8.52 GB / 15.87 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.48 => 1.0.0-alpha.48
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Currently we can't process asset paths from frontmatter. You need to move them to public directory for it to work.

**Comment by SmallWolf1993** [comment]
okay, thank you
