### ISSUE TITLE
Broken links within the official documentation

### ISSUE THREAD

**Issue by orbatschow** [vuejs/vitepress#2016]
### Describe the bug

There are some links within the documentation, that seem to be broken:

- [Default Theme](https://vitepress.vuejs.org/guide/default-theme)
- [Extending the Default Theme](https://vitepress.vuejs.org/guide/customization-extending-default-theme)

### Reproduction

Invoking the links mentioned above will lead to a 404.

### Expected behavior

Invoking the links mentioned above should lead to a functional page.

### System Info

```shell
not needed for this bug
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Where are these links?

**Comment by orbatschow** [comment]
As stated above:

- [Default Theme](https://vitepress.vuejs.org/guide/default-theme)
- [Extending the Default Theme](https://vitepress.vuejs.org/guide/customization-extending-default-theme)

**Comment by brc-dd** [comment]
Yeah but where are those links in our site?

**Comment by brc-dd** [comment]
ah, ok

**Comment by orbatschow** [comment]
Also applies for: https://vitepress.vuejs.org/api/ -> Default Theme/Extending the Default Theme
