### ISSUE TITLE
server-client communication does not work

### ISSUE THREAD

**Issue by emersonbottero** [vuejs/vitepress#2019]
### Describe the bug

server-side only works in dev mode

### Reproduction

clone
https://github.com/emersonbottero/vitepress-demo
npm i
npm run dev => will work

npm run build
npm run serve -> will fail

### Expected behavior

communication should still work in prod

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 7.20 GB / 15.92 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 110.0.5481.104
    Edge: Spartan (44.22621.1325.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.45 => 1.0.0-alpha.45
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
In prod there is no server at all. VitePress is a SSG (Static Site Generator). `vite.configureServer` won't work outside dev because we don't have a vite server at prod. We simply emit html/css/js and assets to dist. Which can then be deployed to any static hosting platform without a dependency on node or vite.

**Comment by emersonbottero** [comment]
what's the use case intend for server-client communication provided in the docs then? debugging purpose?

**Comment by brc-dd** [comment]
IDK maybe some other frameworks are using it probably. But its only for dev as far as I can tell. Vite isn't built for serving sites in prod.
