### ISSUE TITLE
Pass css.modules to vite app

### ISSUE THREAD

**Issue by steventill** [vuejs/vitepress#2026]
### Is your feature request related to a problem? Please describe.

when i have a vue sfc component, and i have 
<template><div class="$style.myStyle"/>
<style module>
.my-style { background: blue;}
</style>

and i am using the component, it does not render the 'blue' background.  if you investigate what $stlye is when you mount the component it has $style={my-style: my-style_fingerprint}

This appears to be because i can not set the css.module options on the vite config.

### Describe the solution you'd like

could you pass through https://vitejs.dev/config/shared-options.html#css-modules to the vite config.  I just need to set the localsConvention to camelcase

### Describe alternatives you've considered

i would have to change my code so that all my references to $style is not camelcase.  I have thousands of references to different css classes, so it would be a real pain to get it to work correctly

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
I think we pass all Vite options to Vite 🤔  How does your config looks like?

**Comment by steventill** [comment]
Ugh, sorry.  I forgot to post my config.

```js
import { defineConfig } from 'vitepress'
const fs = require('fs')

const srcDir = process.cwd() + '/src/components'

const examples = fs.readdirSync(srcDir).filter((file) => /\.md$/.test(file)).filter(file => !/index\.md$/.test(file)).map((example) => {
  const text = example.replace(/\.md$/, '')
  return { text, link: `/${text}`}
})

export default defineConfig({
  title: 'generic-components',
  description: 'Generic components styleguide',
  lang: 'en-US',
  srcDir,
  themeConfig: {
    sidebar: [{
      text: 'Components',
      items: examples
    }]
  },
  css: {
    modules: {
      localsConvention: 'camelCase'
    }
  }
})

```

**Comment by kiaking** [comment]
Can you try nesting `css` option under `vite`?

```ts
export default defineConfig({
  title: 'generic-components',
  description: 'Generic components styleguide',
  lang: 'en-US',
  srcDir,
  themeConfig: {
    sidebar: [{
      text: 'Components',
      items: examples
    }]
  },
  vite: { // <- !!!
    css: {
      modules: {
        localsConvention: 'camelCase'
      }
    }
  }
})
```

**Comment by steventill** [comment]
🤦
any chance you could add that to the documentation, maybe here (https://vitepress.vuejs.org/config/app-config) ??  Also the internet was not the greatest help with that.
