### ISSUE TITLE
[DOC bug]error URL navigation

### ISSUE THREAD

**Issue by bigsnowballhehe** [vuejs/vitepress#2027]
### Describe the bug

![cord](https://user-images.githubusercontent.com/36768323/222621944-7f9d8b34-690f-4403-bf5c-00d9493d2458.gif)

### Reproduction

https://vitepress.vuejs.org/

### Expected behavior

correct positioning

### System Info

```shell
Microsoft Edge
Version 110.0.1587.57 (Official build) (64-bit)
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Confirmed on Chrome too. Interesting. Looks like browser cache issue? If I do `cmd + shift + R` (super reload) then it gets to the correct location 🤔

**Comment by bigsnowballhehe** [comment]
> Confirmed on Chrome too. Interesting. Looks like browser cache issue? If I do `cmd + shift + R` (super reload) then it gets to the correct location 🤔

![Animation](https://user-images.githubusercontent.com/36768323/222644992-ed48b2c6-5a3e-4ef6-aa31-25a791e48e48.gif)
in this case is correct

**Comment by yyx990803** [comment]
When you just hit enter without changing the URL Chrome treats it as a reload and attempts to restore previous scroll position. There is not much we can do IMO.
