### ISSUE TITLE
引入.js后缀文件打包失败[ERR_MODULE_NOT_FOUND]

### ISSUE THREAD

**Issue by zy823957866** [vuejs/vitepress#2028]
### Describe the bug

引入.js文件，由于省略了后缀，导致打包报错。

### Reproduction

![1677813572356](https://user-images.githubusercontent.com/19662251/222623031-c7f838ce-086d-4a57-8b46-477636d15ec6.png)

### Expected behavior

谁知道这个怎么处理呢？

### System Info

```shell
npmPackages
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by CHOYSEN** [comment]
Please provide a reproduction that we can reproduce your issue. There are two ways:

1. [vitepress.new](https://vitepress.new/) can be used as a starter template.
2. Upload your repository and provide a github link.

**Comment by yyx990803** [comment]
Closing as stale. Please provide a valid reproduction if you wish to have this reopened.

**Comment by zy823957866** [comment]
我已经解决了，因为在<code>enhanceApp</code>中用到的第三方包中有<code>localStorage</code>和<code>window</code>，导致打包出错。解决方法如下：
``` js
// 第一步
let localstorage = () => {
    try {
        return window.localStorage
    } catch (error) {
        
    }
}

export default {
    ...DefaultTheme,
    enhanceApp({ app }) {
        if( !localstorage() ) return
        .....
}

// 第二步
在vite.config.ts中配置如下信息：
export default defineConfig({
    ssr: {
        noExternal: [
            '@dt-frames/core',
            '@dt-frames/ui',
            'ant-design-vue',
            'crypto-js',
            '@ant-design/icons-vue',
            '@ant-design/icons-svg',
        ]
    }
    ....
})
```
