### ISSUE TITLE
支持通过文件协议打开

### ISSUE THREAD

**Issue by Dr-Harris** [vuejs/vitepress#2029]
### Is your feature request related to a problem? Please describe.

支持双击dist/index直接打开 现在会报跨域问题

### Describe the solution you'd like

支持双击dist/index直接打开 现在会报跨域问题

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by CHOYSEN** [comment]
You may want `npm run docs:preview`

> https://vitepress.vuejs.org/guide/getting-started#step-3-boot-up-dev-environment
