### ISSUE TITLE
the anchor doesn't work when source anchor is uppercase

### ISSUE THREAD

**Issue by YQisme** [vuejs/vitepress#2034]
### Describe the bug

#1927 Here is the same problem, but it has not been solved yet. So, I gave an example to illustrate the issue. Particularly, all the anchors are in uppercase, and they cannot be jumped successfully, which is surprising.

### Reproduction

https://stackblitz.com/edit/vite-721vib?file=docs/index.md

### Expected behavior

Since destination anchors are automatically converted to lowercase, it is hoped that source anchors can also be automatically converted to lowercase, so that they can match successfully

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.28 GB / 15.87 GB
  Binaries:
    Node: 18.13.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by MarkusKeck** [comment]
I already looked at this issue, but then opted to solve more prominent ones.
My general question is in what occasion would you even habe an uppercase anchor generated?
All the vitepress ones are generated lowercase.

**Comment by yyx990803** [comment]
https://github.com/vuejs/vitepress/issues/1927#issuecomment-1469196660
