### ISSUE TITLE
Latest release caused many 404 errors in the docs

### ISSUE THREAD

**Issue by dilly-sixmo** [vuejs/vitepress#2045]
### Describe the bug

Many doc pages are now inaccessible.

For example:

https://vitepress.vuejs.org/config/theme-config
https://vitepress.vuejs.org/guide/theme-team-page

If you search for "Team", none of the links work.

### Reproduction

Search for team and click a link.

### Expected behavior

Page should exist.

### System Info

```shell
Chrome browser
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by MarkusKeck** [comment]
@brc-dd Same issue as last time the algolia search index has to be recreated.
Maybe it is possible to include this in an automation, every time vitepress gets deployed the search index gets automatically recreated.

**Comment by brc-dd** [comment]
I don't think we can configure docsearch to run the crawler whenever site gets deployed. It currently runs the crawler based on a schedule (weekly).
