### ISSUE TITLE
An error occurred when rendering a markdown file when using vitepress

### ISSUE THREAD

**Issue by newstart0514** [vuejs/vitepress#2046]
### Vue version

3.2.45

### Link to minimal reproduction

https://github.com/newstart0514/vueProblem

### Steps to reproduce

Use vitepress to set the file route normally. The file is routed to the md file (needs to be imported to the local). This error occurs when opening the route

### What is expected?

The md file will be converted to html normally

### What is actually happening?

An error occurred and rendering cannot be performed normally. The error message is: Unhandled error during execution of scheduler flush This is likely a Vue internals bug.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 4800U with Radeon Graphics
    Memory: 4.01 GB / 15.37 GB
  Binaries:
    Node: 18.12.1 - D:\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vue: ^3.2.45 => 3.2.45
```

**Comment by kiaking** [comment]
Could you provide a full reproduction since that repo contains only 1 file and that wouldn't work with VitePress 🤔

**Comment by brc-dd** [comment]
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/40380293/223950907-7ce2bda1-5192-426d-876d-c02e63cdeedc.png">

Unable to reproduce it.

**Comment by newstart0514** [comment]
> Could you provide a full reproduction since that repo contains only 1 file and that wouldn't work with VitePress 🤔

Of course, you can visit my latest uploaded minimal replication environment. Thank you very much! Address: https://github.com/newstart0514/vitepressProblemMinDemo

**Comment by newstart0514** [comment]
> <img alt="image" width="1041" src="https://user-images.githubusercontent.com/40380293/223950907-7ce2bda1-5192-426d-876d-c02e63cdeedc.png">
> 
> Unable to reproduce it.

Thank you very much for trying to reproduce it, but because of my mistake, you can't reproduce it very well. I have uploaded the smallest reproduction environment. You can try it. I'm very sorry. Address: https://github.com/newstart0514/vitepressProblemMinDemo

**Comment by zonemeen** [comment]
https://github.com/newstart0514/vitepressProblemMinDemo/blob/be48e6c9bc79dc9a972fb73bcbf3549dae53497b/docs/language/TypeScript.md?plain=1#L60

The problem is with this line. Because the `markdown-it-attrs` plugin will turn this line into `<td style="text-align:center" A,="" B="">enum/</td>`. This is not allowed in vue's syntax.

You can configure it like this to avoid errors:

```js
markdown: {
     attrs: {
        disable: true
   }
}
```

![image](https://github.com/vuejs/vitepress/assets/44596995/7290de22-7cfd-4fc1-bc81-ec2fa338c215)
