### ISSUE TITLE
Can the sidebar support external links like the navigation bar？

### ISSUE THREAD

**Issue by MaxPeak** [vuejs/vitepress#205]
**Is your feature request related to a problem? Please describe.**
Can the sidebar support external links like the navigation bar？

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/49097525/104460767-798da900-55e9-11eb-9e33-2f2f5e241a0e.png)

**Comment by kiaking** [comment]
Good catch. Yes I think we should support this one 👍

**Comment by deevannaveed** [comment]
Any updates on this feature?
