### ISSUE TITLE
A display error about `vitepress init` template project

### ISSUE THREAD

**Issue by gumingWu** [vuejs/vitepress#2051]
### Describe the bug

Version: vitepress 1.0.0 -alpha.50

After I use `vitepress init` to create template project, and use it, I found that `Site Data` show error

![image](https://user-images.githubusercontent.com/24989299/223748902-4c484540-0860-4de0-bbc9-01f8ce66d1d2.png)

![image](https://user-images.githubusercontent.com/24989299/223748989-44db4c20-7425-4246-aab8-a0cd70b6139b.png)

![image](https://user-images.githubusercontent.com/24989299/223749086-41802dd9-7b4b-4b07-a610-ebbba1dbe46f.png)

I think the display maybe need to fixed

### Reproduction

- vitepress init
- pnpm docs:dev
- click to Examples - Runtime API Examples

### Expected behavior

Maybe need to fixed

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 5.58 GB / 13.87 GB
  Binaries:
    Node: 18.14.2 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - D:\ENVIRONMENT\nodejs\node_global\yarn.CMD
    npm: 9.5.0 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vitepress: 1.0.0-alpha.50 => 1.0.0-alpha.50
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yyx990803** [comment]
This is not really an error - it's because the config contains a string of JavaScript code. It's probably a bit confusing though.
