### ISSUE TITLE
[TOC] Config option to disable Badges in TOC

### ISSUE THREAD

**Issue by staghouse** [vuejs/vitepress#2052]
### Is your feature request related to a problem? Please describe.

Right now if you add a Badge to a header and the TOC applies that header, the TOC will also show the Badge for that header. I would like the option to disable this Badge in the TOC.

### Describe the solution you'd like

Similar to `outlineBadges: boolean` where default is `true` but can be set to `false`, there should be a `tocBadges: boolean` where the default is `true` as well but can be set to `false`.

### Describe alternatives you've considered

Right now we can do something like...

```js
{
  markdown: {
    toc: {
      format: (str) => {
        return str.split('<')[0];
      }
    }
  }
}
```

But this feels like a very dirty solution.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by zonemeen** [comment]
The current version does not seem to have this problem.
