### ISSUE TITLE
【BUG】Failed to load url /guide.md

### ISSUE THREAD

**Issue by Sinosaurus** [vuejs/vitepress#206]
**Describe the bug**

明明有相应的文件，却一直提示文件不存在。关闭 `vscode`，重启终端依旧无效。 没有找到 **缓存*相关的命令。
**System Info**
- vitepress version:  `0.11.3`
- vite version: `2.0.0-beta.30`
- Node version:  `v12.14.1`
- OS version:  `mac 10.14.6`
- 
**Additional context**

具体的错误信息如下

```
[vite] Internal server error: Failed to load url /guide.md (resolved id: /guide.md). Does the file exist?
      at transformRequest (/Desktop/Sinosaurus/vitepress-project/node_modules/vite/dist/node/chunks/dep-3c926c03.js:59215:15)
```

`guide` 目录下有 `index.md` 文件

**Comment by antfu** [comment]
Try visit `/guide/`

**Comment by Sinosaurus** [comment]
@antfu  我本地修改了，问题所在应该是，我开了多个页面，两个页面的地址不一样（因为地址前后不一），导致控制台一直报错，后期我再多注意下，是否是这个问题。

**Comment by yyx990803** [comment]
`guide.md` !== `guide/index.md`
