### ISSUE TITLE
Badge slot breaks `outlineBadges`

### ISSUE THREAD

**Issue by alexbot89** [vuejs/vitepress#2060]
### Describe the bug

When using custom children in the `<badge>` component, it breaks the `outlineBadges: false` option and will display the badge's text in the sidebar outline.

### Reproduction

1. Add a badge to an H2 title (##)
2. Add custom children in the badge slot
3. Set `outlineBadges` option to `false`

https://stackblitz.com/edit/vite-smtupz?file=docs/example.md

### Expected behavior

`outlineBadges` honors badges with custom children/elements when set to false.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 18.43 GB / 31.93 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1344.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.50 => 1.0.0-alpha.50
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That option isn't being used currently (enabling/disabling it won't have any affect).

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/commit/8ab36d05fa4aa8b3707c1f89efc1c820ffaf9669

> default theme config option `outlineBadge` has been removed. Badges in headers are now always excluded when generating outline text.
