### ISSUE TITLE
highlight does not work when the line has nothing

### ISSUE THREAD

**Issue by CHOYSEN** [vuejs/vitepress#2061]
### Describe the bug

highlight does not work when the line has nothing

### Reproduction

https://stackblitz.com/edit/vite-yjqj57?file=docs%2Findex.md

### Expected behavior

null

### System Info

```shell
null
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Was this working earlier? It's probably something CSS related because that line is getting the `highlighted` class there 👀

**Comment by CHOYSEN** [comment]
I think it existed for a long time.I tried add `min-height: calc(var(--vp-code-font-size) * var(--vp-code-line-height))` but its height also different from other lines👀

**Comment by brc-dd** [comment]
Ah, it should be `calc(1em * var(--vp-code-line-height))`

**Comment by brc-dd** [comment]
I remember there used to be a blank character (`&#8203;`) there in empty lines 👀

**Comment by yyx990803** [comment]
9708510
