### ISSUE TITLE
[question]   how can I fully customize a web page under viteprees

### ISSUE THREAD

**Issue by helloQianFan** [vuejs/vitepress#2067]
hello guys, how can I fully customize a web page under viteprees, using only html and css, and then help me route to that page via vitepress, this has been bothering me for a while, thanks

**Comment by brc-dd** [comment]
Put it in public and link it?

**Comment by staghouse** [comment]
Could you not also write a Vue SFC where the HTML goes in the template and CSS in the style tag, register it as a global component and then use it in a MD file?

**Comment by brc-dd** [comment]
Yeah, I mean if it's just a body and style, why even create a component, just paste it in markdown, it'll work. Also even with the component approach, there isn't any need to register it globally. Just import it in a file and use it. The problems will only arise in the cases when there are some scripts.

**Comment by helloQianFan** [comment]
> Put it in public and link it? (https://vitepress.dev/guide/asset-handling#public-files)

thank you sir,!its helping me to solved problem that has benn bothering me for a long time!
