### ISSUE TITLE
feat: allow markdown `config` to return a promise

### ISSUE THREAD

**Issue by tmm** [vuejs/vitepress#2068]
### Is your feature request related to a problem? Please describe.

Trying to port the [`vuepress-plugin-shiki-twoslash`](https://github.com/shikijs/twoslash/blob/main/packages/vuepress-plugin-shiki-twoslash/README.md) plugin over to Vitepress. Shiki Twoslash must be loaded asynchronously and VuePress allows this with the `extendsMarkdown` option:

```ts
const { markdownItShikiTwoslash } = require("markdown-it-shiki-twoslash")
module.exports = settings => ({
  extendsMarkdown: async md => {
    const shiki = await markdownItShikiTwoslash(settings)
    md.use(shiki)
  },
})
```

Meanwhile, VitePress does not support async markdown config so there isn't a way to add these types of plugins (without using [`deasync`](https://www.npmjs.com/package/deasync), etc.).

### Describe the solution you'd like

`MarkdownOptions['config']` allows async configuration.

```ts
interface MarkdownOptions extends MarkdownIt.Options {
  // Configure the Markdown-it instance.
  config?: (md: MarkdownIt) => Promise<void>
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Just return the async config?

**Comment by tmm** [comment]
Works! Didn't see it in the docs.
