### ISSUE TITLE
No outline generated after docs:build (Yes it is there when docs:dev) since alpha52

### ISSUE THREAD

**Issue by arcqiufeng** [vuejs/vitepress#2072]
### Describe the bug

I upgrade to alpha52 then docs:build. Outline in page missing.

I tried docs:dev, it goes well.

Is it a bug?

### Reproduction

I upgrade to alpha52 then docs:build. Outline in page missing.

I tried docs:dev, it is goes well.

Is it a bug?

### Expected behavior

docs:dev and docs:build should be the same.

### System Info

```shell
Windows 11
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by arcqiufeng** [comment]
More:

Then I rollback to v1.0.0-alpha.51:

```
 yarn add -D vitepress@1.0.0-alpha.51
```

It works, outline is back after build.

**Comment by brc-dd** [comment]
Can you share your code? Our site is also using the latest version, but we are able to see the outline:

<img width="190" alt="image" src="https://user-images.githubusercontent.com/40380293/224531105-409d594e-2565-455d-af7d-7d009b4b0076.png">

**Comment by arcqiufeng** [comment]
Maybe it is caused by badge.

I notice there is a break change in alpha52.

It really affected me. I have badges in headlines.

Can you add badges in headlines and tried it again?

My code is in LAN, and size is Large.

**Comment by brc-dd** [comment]
You mean having just the badge in whole heading? Also not asking for the whole code, just a dummy file with 2-3 headers will work.

**Comment by arcqiufeng** [comment]
I will try to reproduce it later.

In the third level of the title, the second level of the title, and there are badges like “to do” and so on.

**Comment by arcqiufeng** [comment]
It works well in dev mode.

**Comment by brc-dd** [comment]
> It works well in dev mode.

Ah, ok. Then we need some code to reproduce the problem at our end. Can't suggest a fix without that 👀

**Comment by arcqiufeng** [comment]
In dev mode, the outline is there. And the badge was perfectly omitted. But it remains in the [[toc]]. Perfect is exactly what I was hoping for.

**Comment by arcqiufeng** [comment]
Now I can reproduce the bug:

Following:

```
W:\work\2023>md test & cd test  

W:\work\2023\test>yarn add -D vitepress

W:\work\2023\test>npx vitepress init

  vitepress v1.0.0-alpha.52

┌   Welcome to VitePress! 
│
◇  Where should VitePress initialize the config?
│  ./docs
│
◇  Site title:
│  My Awesome Project
│
◇  Site description:
│  A VitePress Site
│
◇  Theme:
│  Default Theme
│
◇  Use TypeScript for config and theme files?
│  Yes
│
◇  Add VitePress npm scripts to package.json?
│  Yes
│
└  Done! Now run npm run docs:dev and start writing.
```

Now edit the file "markdown-examples.md" that automatically generated. Just add a badge into the title, as following:

```markdown
## Syntax Highlighting<Badge type="danger" text="caution" />
```

Now we can test the file:

```
W:\work\2023\test>yarn docs:dev
yarn run v1.22.19
warning package.json: No license field
$ vitepress dev docs

  vitepress v1.0.0-alpha.52

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
```
It works fine in http://localhost:5173/markdown-examples.html

Then I try to build it:

```
W:\work\2023\test>yarn docs:build
yarn run v1.22.19
warning package.json: No license field
$ vitepress build docs

  vitepress v1.0.0-alpha.52

✓ building client + server bundles...
✓ rendering pages...
build complete in 19.05s.
Done in 19.83s.
```

I copied all the stuffs into iis root. (C:\inetpub\wwwroot)

Now: http://127.0.0.1/markdown-examples.html
The Page can be displayed but the outline is missing.

**Comment by GVenusLeo** [comment]
I have a similar problem. In v1.0.0-alpha.52, Appearance switch button and custom css work with dev, but fail with preview. #2075

**Comment by yyx990803** [comment]
Looks like alpha.53 didn't fix this, looking into it further...
