### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'W' before initialization

### ISSUE THREAD

**Issue by mancuoj** [vuejs/vitepress#2074]
### Describe the bug

After updating alpha52, local is normal, but after deploying to netlify, the folding of the sidebar and the search button and font setting all invalid.

Uncaught ReferenceError: Cannot access 'W' before initialization

### Reproduction

https://csfive.netlify.app/cs/path

### Expected behavior

like description

### System Info

```shell
see nelify.toml： https://github.com/csfive/docs/blob/main/netlify.toml
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Charles7c** [comment]
#2073 我也遇到了类似的问题，降级到 1.0.0-alpha.51 后问题似乎解决了。

**Comment by mancuoj** [comment]
> #2073 我也遇到了类似的问题，降级到 1.0.0-alpha.51 后问题似乎解决了。

对 回滚到上个版本就能解决

**Comment by zhaoqiu-china** [comment]
一顿操作花了4小时，哈哈，以后先来issues瞅瞅
