### ISSUE TITLE
Add support for custom Prev Next Links in themeConfig

### ISSUE THREAD

**Issue by donggua-nor** [vuejs/vitepress#2079]
### Is your feature request related to a problem? Please describe.

[Prev Next Links](https://vitepress.dev/reference/default-theme-prev-next-links) can only customize using Frontmatter in each markdown file

### Describe the solution you'd like

I think there must be someone else who thinks like me: **I don't want Prev Next Links**

using `custom.css` or customize  in each markdown file is too hack and hope it can be edit in either global config

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by donggua-nor** [comment]
> @donggua-nor I don't know if I understood your request correctly. Do you want that the prev/next links can be disabled globally?
that is what i want.

sry for my poor expression

**Comment by MarkusKeck** [comment]
@donggua-nor I will add a PR for your suggestion this evening.
