### ISSUE TITLE
Refresh global computed $site.customData when a new file is detected in the project.

### ISSUE THREAD

**Issue by jivane-perich** [vuejs/vitepress#208]
**Is your feature request related to a problem? Please describe.**

I'm playing with the vuejs blog template, and I'm frustrated that the customData global properties is not updated on adding a new markdown file.
Creating a new post required a vitepress restart. Vitepress know that a new file exist (we can load it in a new tab), but the global computed content is not updated.

**Describe the solution you'd like**

Adding / removing a file on the site folder (ie not the .vitepress folder) trigger an update of the global computed $site.customData  (so an update of all pages using this global property).

**Additional context**

A basic demo project consists of the vitepress "getting started" project with the following modifications : 

- hello.md : 
```markdown
# Hello VitePress

hello

{{ $site }}
```

- .vitepress/config.js : 

``` javascript
const { getPosts } = require("./getPosts");

module.exports = {
  title: "Hello VitePress",
  description: "Just playing around.",
  customData: {
    posts: getPosts(),
  },
};
```

- .vitepress/getPosts.js : 
``` javascript
const fs = require("fs");
const path = require("path");

exports.getPosts = function getPosts() {
  console.log("calling get posts");
  const postDir = path.resolve(__dirname, "../posts");
  return fs.readdirSync(postDir);
};
```

- a new posts folder in the vitepress project, where we are adding new markdown files.

**Comment by kiaking** [comment]
Well I don't think this is VitePress issue at the moment. You need to tell VitePress that the file has been added.

With your `config.js`, it runs when starting VitePress server, and it calls `getPosts` method. But that's it. You need to recall it update the `config.js` file.

Since `customData` property in config is just a custom field where user can put anything in, VitePress isn't handling anything. VitePress would have no idea how we should update the config when the file is added.

So, there're pretty much nothing we can do at the moment. It's blog theme issue, and not the VitePress's.

**Comment by pgrasland** [comment]
> You need to tell VitePress that the file has been added.
> 
> With your config.js, it runs when starting VitePress server, and it calls getPosts method. But that's it. You need to recall it update the config.js file.

Hi, thanks for the reply.
In this case, how can a theme handle this type of event ? 

Can I listen to the event  `event: 'vitepress:pageData' ` sent on HMR update ?

**Comment by kiaking** [comment]
At first, you need to watch the `posts` folder, then when any new file is added, I think you could just update the config file. Then VitePress will automatically HMR new config to the client.

**Comment by DeFUCC** [comment]
@jivane-perich I think the ability to scan files and have their data available at build time is the last thing, that's delaying the vitepress total success. ✨

**Comment by jivane-perich** [comment]
Finally found some time for this.

The following gist do the job : https://gist.github.com/jivane-perich/1eb2574d0e32afc0aadc0bcb507e12ce

The mechanism used to trigger the reload is a `touch`on the `.vitepresse/config.js` file (this trigger an HMR update).
