### ISSUE TITLE
Add a doc-footer-content-before slot

### ISSUE THREAD

**Issue by hparzych** [vuejs/vitepress#2082]
### Is your feature request related to a problem? Please describe.

Vitepress currently does not have a way to directly add more information to the VPFooter of a VPDoc page. This makes it more difficult to add text or other content inside the document footer.

### Describe the solution you'd like

I've been running a local version of vitepress where I've added the `doc-footer-content-before` slot. This way, I can add more content inside the footer of a VPDoc page.

### Describe alternatives you've considered

I am aware that there exists a `doc-footer-before` slot, but it's outside the footer element. This makes it harder to apply consistent styling, as VPFooter has a margin that affects content inserted with the `doc-footer-before` slot. It's also not the best option in terms of HTML semantics.

### Additional context

Below is a screenshot where two lines of text have been added with the already existing `doc-footer-before`.

![Screenshot2](https://user-images.githubusercontent.com/127784133/224806929-042a3351-e45b-4433-a18d-c60a07b3e926.png)

Below is a screenshot where the proposed `doc-footer-content-before` slot has been used instead.
![Screenshot](https://user-images.githubusercontent.com/127784133/224807730-66233591-193b-4a90-806c-8bf1a734ef94.png)

I'm open to hear your opinion on the issue.

I would be glad to upstream the proposed change.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by yyx990803** [comment]
I think the slot makes more sense to be in the footer, so I moved it in there.
