### ISSUE TITLE
How can I change default config path, like /projectRoot/config/vitepress.config.ts.

### ISSUE THREAD

**Issue by liwuhou** [vuejs/vitepress#2084]
### Is your feature request related to a problem? Please describe.

I want to vitepress cli support this feature to set some path for vitepress configuration. I search the vitepress docs and found nothing about it.
Honestly, path "./vitepress/config.ts" is ugly to me.

### Describe the solution you'd like

Like that: vitepress --config yourConfigPath dev

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by yyx990803** [comment]
Sorry, this is not something that can be changed, and there is no intention to support custom config paths. "Looks ugly" is not enough reason to redesign the whole config resolution.
