### ISSUE TITLE
Can template variables be used in code boxes？

### ISSUE THREAD

**Issue by tolerance-go** [vuejs/vitepress#2087]
### Is your feature request related to a problem? Please describe.

原因看代码就很清楚了，version 是从包的 package.json 取的，这样我就不用每次发布后修改了

```bash
yarn add @to-g-modules/filter-form@{{ version }}
```

### Describe the solution you'd like

```bash
yarn add @to-g-modules/filter-form@{{ version }}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by yyx990803** [comment]
https://vitepress.dev/guide/using-vue#unescape-in-code-blocks
