### ISSUE TITLE
`editLink` should be able to use the link of the route `rewrites` keys.

### ISSUE THREAD

**Issue by ronny1020** [vuejs/vitepress#2088]
### Is your feature request related to a problem? Please describe.

I use `editLink` for my GitHub repo URL. However, I also use the `rewrites` to rewrite my route. The edit link will link to the rewritten link which can't find the edit page.

### Describe the solution you'd like

I think the `:path` in `editLink` should use the original path before rewriting by default or add a boolean key to decide whether to use it or not.

### Describe alternatives you've considered

Or add another mapping object to rewrite the path like the `rewrites` object.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
As a workaround, you can pass a function there: https://vitepress.dev/reference/default-theme-edit-link

**Comment by ronny1020** [comment]
Thanks for your reply. However, I used a dynamic rewrites variable to change the routes. I can't use the function to get my original path since it can't access anything outside its scope.

**Comment by chgeo** [comment]
https://github.com/vuejs/vitepress/pull/2140 should fix this. Please check.
