### ISSUE TITLE
add info about need to commit file for last updated to show

### ISSUE THREAD

**Issue by zchengo** [vuejs/vitepress#2090]
### Describe the bug

The update time of the last content will be displayed in the lower right corner of the page. To enable it, add lastUpdated options to your config.

```js
export default {
  lastUpdated: true
}
```

I add, but lastUpdated not show, why?

### Reproduction

lastUpdated: true

### Expected behavior

lastUpdated: true

### System Info

```shell
lastUpdated: true
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by zchengo** [comment]
.vitepress/config.js , example:

```js
export default {
    title: 'zzz',
    description: 'zzzz.',
    themeConfig: {
        ...
    },
    lastUpdated: true,
    lastUpdatedText: '最后更新：',
}  
```

I added, but no show example "最后更新： 2023/3/12 20:11:01" in the page。how to get lastUpdated and show to the page ?

**Comment by brc-dd** [comment]
You need to commit that file first.

**Comment by MarkusKeck** [comment]
As you suggested, your config file has to look something like this: (either .js or .ts)
```ts
// root/docs/.vitepress/confiig.ts

export default {
    title: 'title',
    description: 'description',
    lastUpdated: true,
    ...
}
```

And as @brc-dd stated, the file you want the date displaayed has to be committed, as vitepress gets the date from git and not from the file itself.
If you take all this into account, were you able to make it work on your end, or is this still an ongoing issue?

**Comment by zchengo** [comment]
Yes, After I submit using git, it can successfully display the date.
