### ISSUE TITLE
Theme default can't toggle dark/light mode or copy code in MPA mode

### ISSUE THREAD

**Issue by xinconan** [vuejs/vitepress#2092]
### Describe the bug

In MPA mode with default theme, can't toggle dark/light mode and can't copy code when click copy button。

### Reproduction

any md file can reproduction

### Expected behavior

In MPA mode, can toggle dark/light mode and copy code.

### System Info

```shell
windows vitepress@1.0.0-alpha.60
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
All JS is stripped in MPA mode, so anything that requires JS (incl. dark/light toggle, copy code, code groups) won't work.
