### ISSUE TITLE
vitepress not support jsx file?

### ISSUE THREAD

**Issue by frontHu** [vuejs/vitepress#2095]
### Describe the bug

I referenced a globally registered component in the markdown document of vitepress. When I used it, the error was reported as follows:
**[vitepress] Internal server error: At least one <template> or <script> is required in a single file component.**

### Reproduction

Create vite.config.js in the vitepress root directory, the content is as follows：

```
import { defineConfig } from "vite";
import vueJsx from "@vitejs/plugin-vue-jsx";
import vue from "@vitejs/plugin-vue"
export default defineConfig({
  plugins: [
    vue(),
    vueJsx(),
  ],
});
```

### Expected behavior

Render component content correctly

### System Info

```shell
node 16
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Reproduction? Appears to be working for me: https://stackblitz.com/edit/vite-vuwsnb?file=docs/index.md
