### ISSUE TITLE
Frontmatter and markdown links don't work

### ISSUE THREAD

**Issue by elis** [vuejs/vitepress#2099]
### Describe the bug

When using a frontmatter data inside a link syntax the resulting HTML is plaintext without link.

### Reproduction

Use the following markdown:

```md

---
homepage: https://vitepress.dev/
---

Vitepress Homepage: [ {{ $frontmatter.homepage }} ]({{ $frontmatter.homepage }}) [Vitpress Homepage]( {{ $frontmatter.homepage }} )
```

Resulting text/html:

```
Vitepress Homepage: [ https://vitepress.dev/ ](https://vitepress.dev/) [Vitpress Homepage]( https://vitepress.dev/ )
```

### Expected behavior

The Frontmatter data should not affect the markdown syntax and links should behave as expected.

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 10.12 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.1
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What's the expected output here? Also your frontmatter is not valid YAML. You need to quote value to escape `:`.

**Comment by elis** [comment]
@brc-dd Yaml parsed fine, never ran into issues with parsing URLs even if in some cases it does makes problems.

Second, tried with and without space - same result. Why would a space inside `[]` would cause any issues? whitespaces aren't an issue in markdown links and never were AFAIK. You're welcome to try it via https://markdownlivepreview.com/ or any other method you find suitable - any kind of setup with whitespaces works well.

Third seems to be the actual issue I'm reporting - it might be a design decision, which is fine if that's the case, I'd cater for the users and the way they use or might find the software useful, but that's for the owner of the software/maintainers to decide upon.

Fourth - thanks for the alternative solution! For now it'll do! :)
