### ISSUE TITLE
Setting outline depth per section

### ISSUE THREAD

**Issue by mishushakov** [vuejs/vitepress#2101]
### Is your feature request related to a problem? Please describe.

I need the outline in my `/docs` to have the default depth of 2, but the outline in my `/api` to have the default depth of [2, 3]. Currently I must specify the outline depth manually

### Describe the solution you'd like

Similar to how I can have multiple sidebars for each section of the docs, I want to be able to have multiple outline settings for each section of my docs

```js
outline: {
  '/docs': 2,
  '/api': [2, 3]
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not seeing any particular demand here (0 upvotes on the issue). Also, now this can be done via transformPageData, so you don't need to specify it on all pages.
