### ISSUE TITLE
Incorrect aside sticky position

### ISSUE THREAD

**Issue by Hfutsora** [vuejs/vitepress#2114]
### Describe the bug

When there is a top banner and no sidebar, the sticky position of the aside is incorrect.

### Reproduction

![image](https://user-images.githubusercontent.com/31959015/226558553-6d252bac-f20f-473f-b733-36293908be10.png)

You can find this bug on [vue doc](https://vuejs.org/about/faq.html).

### Expected behavior

The position of the aside should be correct.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 20.41 GB / 31.87 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Vue docs are using a different theme: https://github.com/vuejs/theme

**Comment by Hfutsora** [comment]
I reproduced this issue in this [repository](https://github.com/Hfutsora/vitepress-aside-issue) using vitepress.

![image](https://user-images.githubusercontent.com/31959015/226565580-65e174e3-6ccb-4884-ae22-5726c4ca7e3c.png)

**Comment by brc-dd** [comment]
Ah, it's only when there is no sidebar present.
