### ISSUE TITLE
Increase contrast for Custom Containers

### ISSUE THREAD

**Issue by RunDevelopment** [vuejs/vitepress#2119]
### Is your feature request related to a problem? Please describe.

Custom Containers have relatively low contrast compared to regular text. This makes the contrast of text very inconsistent across the page, which makes text less pleasant to read. Of course, the lower contrast text itself is also quite hard to read (especially on low-end displays, and displays with filters, such as a blue light filter).

![image](https://user-images.githubusercontent.com/20878432/226621460-2128f5e4-742e-4528-b077-33c68be18f12.png)

### Describe the solution you'd like

As noted in #1824 and #1989, the cause of the problem is that both light and dark mode use the same colors for Custom containers. So the picked color is likely not ideal for both.

Please use different colors for light and dark mode, and choose default colors with higher contrast.

### Additional context

I first came across is here: https://github.com/eslint-community/eslint-utils/pull/84

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Closing this for now regarding #2727 . Let's open another issue if we want further adjustment.

**Comment by Lehoczky** [comment]
But [the comment](https://github.com/vuejs/vitepress/pull/2727#issuecomment-1666590614) regarding the warning container's contrast was ignored in https://github.com/vuejs/vitepress/pull/2727. It still isn't meeting the minimum required contrast for accessibility.

**Comment by brc-dd** [comment]
Ah, Kia probably missed that. We'll fix this issue. Have to pick up some stuff from that a11y PR too.
