### ISSUE TITLE
Link to image does not contain the image-hash

### ISSUE THREAD

**Issue by eigan** [vuejs/vitepress#2124]
### Describe the bug

Link to image (to open image in new tab/fullscreen). The img tag uses the image hash, but not the link itself, resulting in 404. 

#### Markdown
```markdown
[![Lifecycle](../../assets/lifecycle.png)](../../assets/lifecycle.png)
```

#### Result
```html
<a href="../../assets/lifecycle.png"><img src="/assets/lifecycle.61eb5a52.png" alt="Lifecycle">
```

### Expected behavior

```html
<a href="/assets/lifecycle.61eb5a52.png"><img src="/assets/lifecycle.61eb5a52.png" alt="Lifecycle">
```

### System Info

```shell
System:
    OS: Linux 6.2 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 12.28 GB / 31.27 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 19.7.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chromium: 110.0.5481.177
    Firefox: 110.0.1
  npmPackages:
    vitepress: ^1.0.0-alpha.49 => 1.0.0-alpha.61
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Keep it in [the public directory](https://vitepress.dev/guide/asset-handling#the-public-directory) for now.

**Comment by zonemeen** [comment]
The compilation is done by `vite`, which does not compile `<a :href="../../assets/lifecycle.png" >test</a>` to `<a :href="/assets/lifecycle.61eb5a52.png" >test</a>`, and still compiles to `<a :href="../../assets/lifecycle.png" >test</a>`. I'm not sure if this is a bug.

**Comment by brc-dd** [comment]
https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue/README.md#asset-url-handling

https://vitepress.dev/reference/site-config#vue
