### ISSUE TITLE
Is it possible to use Storybook for previewing custom components?

### ISSUE THREAD

**Issue by bojanrajh** [vuejs/vitepress#2127]
### Describe the bug

I'm trying to set up Storybook with Chromatic to test custom VueJS components.

Standard non-vitepress component works okay. As soon as we call the `import {useRoute} from "vitepress";`, there's an error `SyntaxError: Invalid left-hand side in assignment` which happens due to `"production" = "production"`.

Transpiled code:
![image](https://user-images.githubusercontent.com/117360292/227134404-54986640-ab6f-4d50-b14a-ccbf5b440966.png)

[Source code](https://github.com/vuejs/vitepress/blob/da1691d77e371892cbe566ba45ca24f1fa03dc7c/src/node/build/build.ts#L21):
![image](https://user-images.githubusercontent.com/117360292/227134439-ac97a05a-7d71-4b60-ace3-2c762f12e0b4.png)

`renderSelection()`:
![image](https://user-images.githubusercontent.com/117360292/227134784-13a0a0b7-2ee5-40b1-a6cf-788571f6d16f.png)

Trace:
![image](https://user-images.githubusercontent.com/117360292/227134826-55bf1ae2-5faa-44a5-aa49-24a057cc22f1.png)

### Reproduction

See CustomComponent on [Stackblitz](https://stackblitz.com/edit/github-irbs6h?file=src/stories/CustomComponent.stories.ts) (default `storybook-vite` and `vitepress` templates).

### Expected behavior

Due to SSR & SSG, I'm expecting some issues, but not at this level.

### System Info

```shell
/
```

### Additional context

I know I can use [jest-image-snapshot](https://www.npmjs.com/package/jest-image-snapshot) with `vitest`, but that doesn't give us an automated way for reviewing visual regressions.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you try patching vitepress locally to something like this and see if it works?

```ts
if (process.env.NODE_ENV !== 'production') {
  process.env.NODE_ENV = 'production'
}
```

**Comment by brc-dd** [comment]
Ah, you're using `vitepress` inside storybook right? That won't work considering vitepress has it own set of vite plugins, while storybook has other. They are conflicting with each other (process.env/import.meta/defines, etc. are being replaced).

**Comment by bojanrajh** [comment]
Yeah, now I'm not sure why I haven't tried it in a first place, because that was the idea. :selfpunch:

```ts
// .storybook/main.ts
const config: StorybookConfig = {
    viteFinal: async (config, {configType}) => {
        return mergeConfig(
            mergeConfig(config, (await baseConfig()).vite),
            {
                resolve: {
                    alias: {
                        vitepress: '/__mocks__/vitepress',
                    }
                },
            }
        );
    }
}

export default config;
```

For a reference: `storybook-addon-manual-mocks` doesn't work with vite.

Again - thank you!

**Comment by JReinhold** [comment]
Cool!
FYI merging your root Vite config in `viteFinal` shouldn't be necessary in 7.0 anymore, as that happens automatically. So you can just do:

```ts
// .storybook/main.ts
const config: StorybookConfig = {
	viteFinal: async (config) => {
		return mergeConfig(config,
			{
				resolve: {
					alias: {
						vitepress: '/__mocks__/vitepress',
					}
				},
			}
		);
	}
}

export default config;
```

If it's because your `vite.config.js` is not located at CWD, [you can specify the location manually with
](https://github.com/storybookjs/storybook/tree/next/code/lib/builder-vite#customize-vite-config)

```ts
// .storybook/main.ts
const config: StorybookConfig = {
	framework: {
		name: '@storybook/vue3-vite',
		options: {
			builder: {
 				viteConfigPath: '.storybook/customViteConfig.js',
 			},
		},
	},
}

export default config;
```
