### ISSUE TITLE
dev works perfect but build not work

### ISSUE THREAD

**Issue by MelihAltintas** [vuejs/vitepress#2137]
### Describe the bug

I've implemented a vitepress site for a component library used internally. Running npm run docs:dev works as intended and the documentation site is functional. When I attempt to build the docs site, I get an ambiguous error.

Project link: https://github.com/MelihAltintas/vue3-openlayers

```
> vue3-openlayers@0.1.74 docs:build
> vitepress build docs


  vitepress v1.0.0-alpha.50

⠦ building client + server bundles...
(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ building client + server bundles...
build error:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 's' imported from D:\vue3-openlayers\docs\.vitepress\.temp\app.js
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:884:9)
    at moduleResolve (node:internal/modules/esm/resolve:929:18)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

### Reproduction

npm run docs:build

### Expected behavior

work like a npm run docs:dev

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 11.31 GB / 31.88 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 111.0.5563.111
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.51)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.50 => 1.0.0-alpha.50
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by MelihAltintas** [comment]
@brc-dd Help pls :)

**Comment by brc-dd** [comment]
That error is due to `src/components/interaction/ClusterSelectInteraction.vue`. You've a wrong import there `ol-ext//...` remove extra slash.

**Comment by MelihAltintas** [comment]
Thanks @brc-dd But why dev is working. Do we need to do a build test in the meantime, why are they not compatible with each other?

**Comment by brc-dd** [comment]
> But why dev is working.

Not sure, but probably one of our deps / browser is being lenient there.

**Comment by MelihAltintas** [comment]
Thanks @brc-dd Finally, my warning was a very meaningless "s" import error. Direct point shot, how did you find this component? I need it to be able to solve the problem completely :(

**Comment by brc-dd** [comment]
The other errors can be fixed by

- formatting vite config properly
- adding `ssr: { noExternal: ['ol-contextmenu'] }` there (-- that package is not packed properly, needs transpiling)
- `file-saver` is CJS, named imports won't work -- use `import fileSaver from 'file-saver'; /* ... */ fileSaver.saveAs()`

There will be another error `window is not defined`, this is because some of your code / library is accessing browser APIs. Try wrapping them with `<ClientOnly>` or if they have side effects use dynamic imports onMounted.

**Comment by brc-dd** [comment]
> Finally, my warning was a very meaningless "s" import error. Direct point shot, how did you find this component?

Run with `DEBUG=true` (can also set a debug-js compatible specifier) and browse that temp/app.js file

**Comment by brc-dd** [comment]
Some other issues:

- Make ol-ext SSR compatible if you're its maintainer (need to do check if `typeof window !== 'undefined'` before accessing window.
- You've some code like `type: HTMLElement` or `type: [HTMLImageElement, HTMLCanvasElement]`, those interfaces are not available in Node. You either need to make them Object or start using TS.
