### ISSUE TITLE
Custom themes, inconsistent development and production styles

### ISSUE THREAD

**Issue by yaoxfly** [vuejs/vitepress#2143]
![image](https://user-images.githubusercontent.com/44956835/227828385-de09bbdf-fa85-4a37-b56a-46f0e0714ac6.png)
![image](https://user-images.githubusercontent.com/44956835/227830278-b24159b8-c0f2-4947-98f3-687f256a10c4.png)
![image](https://user-images.githubusercontent.com/44956835/227830367-93081324-cd95-4d36-aea6-9ab02714cbac.png)
![image](https://user-images.githubusercontent.com/44956835/227830500-1ac0553f-ec9c-4f7d-a0f5-fb43e10463e9.png)

developmen
![image](https://user-images.githubusercontent.com/44956835/227828547-8e625738-bc09-4770-8a46-1b6c60bce713.png)

production

![image](https://user-images.githubusercontent.com/44956835/227829272-afe79236-0ffe-4405-8bbb-15e2544d2947.png)

After packaging, the iconfont.css style is at the very end
 
Why is this a problem? The old version didn't have this problem

Currently version 1.0.0-alpha.63 is used  ， Old version 1.0.0-alpha.19

**Comment by brc-dd** [comment]
Can you share a simple repo / stackblitz line (https://vitepress.new) instead of screenshots?

**Comment by yaoxfly** [comment]
> 你能分享一个简单的 repo / stackblitz 链接 ( https://vitepress.new ) 而不是屏幕截图吗？

I'm sorry I closed this. I'll fill it out again
