### ISSUE TITLE
Soft link mds in different locales?

### ISSUE THREAD

**Issue by lslzl3000** [vuejs/vitepress#2153]
### Is your feature request related to a problem? Please describe.

My doc site has 1000+ api `.md` generated from source code, they are pure api spec, basically no difference between languages, the only locales I need to covered is a `guide` folder, so I can create different mds for `/guide`, `/zh/guide`, `/fr/guide` ... for different language info, which is a fine way to do that.

But for `api` folder，I have to create/duplicated `/zh/api`, `/ft/api` ...  for all same `.md`,  and there are over 1000 files for each locales. It is too much redundancy and hard to manage.

A work around I used right now is to use the same nav/sidebar settings for different locales, e.g.
```js
locales:{
    root:{
        nav: [{
            text: 'guide',
            items: [{
                text: 'gudie',
                link: '/guide/'
            }]
        },{
            text: 'api',
            items: [{
                text: 'api',
                link: '/api/'
            }]
        }]
        sidebar: {
            '/guide/': [...],
            '/api/': [...]
        }
    },
    zh: {
        nav: [{
            text: 'guide',
            items: [{
                text: 'gudie',
                link: '/zh/guide/'
            }]
        },{
            text: 'api',
            items: [{
                text: 'api',
                link: '/api/'
            }]
        }]
        sidebar: {
            '/zh/guide/': [...],
            '/api/': [...]
        }
    },
    fr: {
        nav: [{
            text: 'guide',
            items: [{
                text: 'gudie',
                link: '/fr/guide/'
            }]
        },{
            text: 'api',
            items: [{
                text: 'api',
                link: '/api/'
            }]
        }]
        sidebar: {
            '/fr/guide/': [...],
            '/api/': [...]
        }
    }
}
```
but this will redirect to the root locale on `/api` paths, which is not a perfect way.

Is there a way to re-use `md` file in different locales, but still keep the route link? e.g. all `/api/`, `/zh/api/`, `/fr/api/` ... they are all point to a same `.md` in `api` folder?

### Describe the solution you'd like

A map config to soft link path with target `md`?
or expose a `md` transform function/hook to locate the source file?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Let's track this at #1496. System symlinks should be fine enough to handle these cases.
