### ISSUE TITLE
Potential bug with scroll to top behavior

### ISSUE THREAD

**Issue by nathanpeck** [vuejs/vitepress#2155]
### Describe the bug

When you click on a link at the bottom of a page, it will navigate to the next page, but then scroll the next page all the way from the bottom of the page to the top of the page. It appears that this happens on each page navigation, but the issue is particularly noticable for longer pages and when clicking a link at the bottom of a page, followed by a long page.

You can see a video of the unexpected behavior here: https://streamable.com/k8kwio

### Reproduction

Scroll to the bottom of a page, click on a link there. The next page should be a long page. Rather than starting out at the top of the page it will take users on a tour of the page all the way from the bottom up to the top.

### Expected behavior

The smooth scrolling behavior should not activate on long pages where the scroll would be longer than the size of the window. I believe that this code is supposed to prevent that super long "tour" of the page, but does not appear to be working: https://github.com/vuejs/vitepress/blob/16064023cfe390eccc1552792b906156e4936382/src/client/app/router.ts#L268-L276

### System Info

```shell
System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
    Memory: 27.43 GB / 30.63 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  npmPackages:
    vitepress: ^1.0.0-alpha.61 => 1.0.0-alpha.61
```

### Additional context

Google Chrome browser

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You probably have some CSS forcing that. Look for any code in your theme that says `scroll-behavior: smooth`
