### ISSUE TITLE
In development mode, markdown under node_modules will be parsed

### ISSUE THREAD

**Issue by aibayanyu20** [vuejs/vitepress#2156]
### Describe the bug

In development mode, markdown under node_modules will be parsed

### Reproduction

Add a markdown file index.md in node_modules under docs and then visit localhost:5173/node_modules/.md file is parsed

### Expected behavior

expect not to be parsed

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz
    Memory: 18.07 GB / 31.87 GB
  Binaries:
    Node: 16.19.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (111.0.1661.51)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vitepress: ^1.0.0-alpha.63 => 1.0.0-alpha.63
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Why are you even opening it?

**Comment by aibayanyu20** [comment]
How can I configure Vitepress to ignore parsing markdown files under node_modules during development? I've attempted to use `srcExclude` to achieve this, but it only seems to work in production mode.

**Comment by brc-dd** [comment]
Hey, my question is still the same, why are you even opening that `http://localhost:5173/node_modules/...` link?

**Comment by aibayanyu20** [comment]
I'm very sorry, maybe I didn't describe it clearly. I didn't open this link. In development mode, it will scan all files with the suffix '.md' under the 'node_modules' directory by itself, which caused my project to not start normally.

**Comment by brc-dd** [comment]
node_modules is automatically excluded by us:

https://github.com/vuejs/vitepress/blob/7dfe9d2d433af878169bce36d82bba9bc93ee68e/src/node/config.ts#L452

Are you using some plugin that might be causing this issue? Can you share the repo where you're getting this?

**Comment by aibayanyu20** [comment]
Thank you very much for your help. I have found the cause of the problem. It was indeed caused by the installation of a certain Vite plugin!
