### ISSUE TITLE
maybe copy button color too dark in code block with light background

### ISSUE THREAD

**Issue by mancuoj** [vuejs/vitepress#2168]
### Describe the bug

![image](https://user-images.githubusercontent.com/45707684/228780139-10122d10-3a61-49e5-b3a7-88d21f8a880c.png)

### Reproduction

As described above

### Expected behavior

As described above

### System Info

```shell
As described above
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It looks like you've overridden styles for your code blocks. If that's the case then override the colors for copy button too.

PS: In default theme the code blocks are dark:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/40380293/228783702-eaf8d03a-c71c-4def-b0ba-6539eb533535.png">
