### ISSUE TITLE
The request to get the content of an html file was intercepted by devserver

### ISSUE THREAD

**Issue by XiaoYang943** [vuejs/vitepress#2174]
### Describe the bug

When I use `axios` or `fetch` get the string of the content of the local HTML file.

But the request was intercepted by devserver.

The request content:
```
"<!DOCTYPE html>
<html>
  <head>
    <script type="module" src="/@vite/client"></script>

    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="">
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/@fs/...\node_modules\vitepress\dist\client\app/index.js"></script>
  </body>
</html>"
```

How should I do ?

Help ! Thanks !

### Reproduction

```
fetch("./test.html")
  .then(function (response) {
    response.text().then(function (data) {
      debugger;
    });
  })
  .catch(function (e) {
    console.log("error: " + e.toString());
  });
```

### Expected behavior

Get local HTML file content correctly

### System Info

```shell
"vitepress": "^1.0.0-alpha.64"
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What's the use-case? Try moving that file to public directory. Or if you just want it's content as string, just import it: https://vitejs.dev/guide/assets.html#importing-asset-as-string

**Comment by XiaoYang943** [comment]
thanks!
