### ISSUE TITLE
UTF-8 not working in dev mode / Safari browser.

### ISSUE THREAD

**Issue by aldrinmartoq** [vuejs/vitepress#218]
**Describe the bug**
Safari does not interpret output files as UTF-8 in dev mode for some reason. There is no problem using Chrome.

**To Reproduce**
Just created a simple project with unicode characters.
1. yarn init
2. yarn add --dev vitepress
3. yarn docs:dev
4. created docs/index.md and docs/.vitepress/config.js with UTF letters: áéíóúñ
5. Output has <meta charset="UTF-8"> but the file is not interpreted as UTF-8 by Safari.

**Expected behavior**
Dev mode should work in Safari as in Chrome.

**System Info**
- vitepress version: 0.11.5
- vite version: 2.0.0-beta.61
- Node version: 12.19.0
- OS version: macOS Big Sur 11.1

**Additional context**
Safari Picture:
<img width="2560" alt="Screen Shot 2021-02-02 at 13 51 57" src="https://user-images.githubusercontent.com/388475/106633795-e5669000-655d-11eb-91b0-0afaebe72bfd.png">

Chrome Picture:
<img width="2560" alt="Screen Shot 2021-02-02 at 13 51 32" src="https://user-images.githubusercontent.com/388475/106633826-ebf50780-655d-11eb-9638-08c61ef4ee57.png">

Sample code:
https://github.com/aldrinmartoq/vitepress-testdrive

Thanks,
Aldrin.

**Comment by ChrisShank** [comment]
I have noticed this same behavior as well

**Comment by kiaking** [comment]
Confirmed. Yeah Safari is using... I don't what it's using but not UTF-8 😓 

We should add charset head meta tag in dev mode as well. Along side with this PR I guess https://github.com/vuejs/vitepress/pull/207.

**Comment by KnowsCount** [comment]
> Confirmed. Yeah Safari is using... I don't what it's using but not UTF-8 😓
> 
> We should add charset head meta tag in dev mode as well. Along side with this PR I guess #207.

Safari is using 'Western (ISO Latin 1)' as a default I guess... but one can always change the default encoding in `Preferences->Advanced`

A screenshot is provided below: 

![](https://knowscount-1304485449.cos.ap-shanghai.myqcloud.com/img/Screenshot%202021-02-18%20at%2010.30.17.png)
