### ISSUE TITLE
Markdown "@include" throw "ERR_INVALID_URL" on "vitepress build docs"

### ISSUE THREAD

**Issue by Guebbit** [vuejs/vitepress#2180]
### Describe the bug

Build blocking error happen on "vitepress build docs".
Works correctly and as intended on "vitepress dev docs --port 8080"

TypeError: Failed to parse URL from [path]
[cause]: TypeError [ERR_INVALID_URL]

### Reproduction

Use the regular Markdown File Inclusion with any file in any .md file, then try to build with "vitepress build docs".

https://vitepress.dev/guide/markdown#markdown-file-inclusion

### Expected behavior

Build concluding with success and no error displayed.

### System Info

```shell
System:                                                    
    OS: Windows 10 10.0.19044                                
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz    
    Memory: 1.94 GB / 7.62 GB                                
  Binaries:                                                  
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE          
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD           
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD             
  Browsers:                                                  
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.19041.1566                       
  npmPackages:                                               
    vitepress: ^1.0.0-alpha.62 => 1.0.0-alpha.62
```

### Additional context

![code](https://user-images.githubusercontent.com/12038511/229305210-5e1734bc-e9e1-4ee3-8b35-0dd97c939581.png)
![error](https://user-images.githubusercontent.com/12038511/229305212-289caf10-bcf4-40aa-a04b-8f73308a1649.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Guebbit** [comment]
Hello, I'm updating the issue. As of 1.0.0-beta.1 the bug is still present.

**Comment by userquin** [comment]
`@include` can be only used to import markdown files: https://vitepress.dev/guide/markdown#markdown-file-inclusion

To include a html page use [Import Code Snippets(`<<<`)](https://vitepress.dev/guide/markdown#import-code-snippets)

**Comment by Guebbit** [comment]
That function is completely different so it is unsuitable for my needs.

The import markdown does work on html, perfectly and as intended, but it fails on build only (dev is fine)

**Comment by userquin** [comment]
@Guebbit check this test (md inclussion at bottom) https://raw.githubusercontent.com/vuejs/vitepress/main/__tests__/e2e/markdown-extensions/index.md

Running the tests works: maybe trying to use `@`  prefix instead relative works...
