### ISSUE TITLE
Configurable 'clean url' in client router

### ISSUE THREAD

**Issue by jalt007** [vuejs/vitepress#219]
**Is your feature request related to a problem? Please describe.**

In production it may be desirable to strip the `.html` extension in urls. Of course this isn't a direct concern of vitepress, and typically static hosts provide a turnkey setting to do this e.g; https://vercel.com/docs/configuration#project/clean-urls

However the client side router will append `.html` to the history push state when navigating:

- https://github.com/vuejs/vitepress/blob/master/src/client/app/router.ts#L47

This will result in an extra server redirects when e.g. sharing urls, doing hard reloads; that ideally could be avoided.

**Describe the solution you'd like**

To be able to configure this `.html` appending behaviour on the client router :)

**Comment by kiaking** [comment]
Thanks for the feedback! Interesting. Sounds nice, but the concern would be it might be misleading for people who are not using advanced hosting such as Vercel. If we have option like `cleanUrl: true`, then people might think VitePress is going to generate clean url directly structure.

```bash
/index.html
/guide/getting-started/index.html
```

I guess we need to be extra careful when designing spec if we were to add this feature 🤔

**Comment by GamearooCodes** [comment]
This would be a nice feature to be able to have it as /about instead of /about.html

**Comment by talawahtech** [comment]
FYI the issue mentioned by @jalt007 happens with Cloudflare Pages, but unlike vercel, there is no way to run it off. It also causes web analytics numbers to be duplicated.

https://developers.cloudflare.com/pages/platform/serving-pages#route-matching
