### ISSUE TITLE
List supported icons

### ISSUE THREAD

**Issue by RSS1102** [vuejs/vitepress#2193]
### Is your feature request related to a problem? Please describe.

Can you list the supported icons?
I would like to know which icons can be used directly
```html
<script setup>
import { VPTeamMembers } from 'vitepress/theme'

const members = [
  {
    avatar: 'https://www.github.com/yyx990803.png',
    name: 'Evan You',
    title: 'Creator',
    links: [
      { icon: 'github', link: 'https://github.com/yyx990803' },
      { icon: 'twitter', link: 'https://twitter.com/youyuxi' }
    ]
  },
  ...
]
</script>
```

### Describe the solution you'd like

Can create an enumeration list in the document

### Describe alternatives you've considered

Alternatively, use typescript for declaration restrictions

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by KishanGupta114** [comment]
_**Hi @RSS1102,**_

**_List of Some Directly Supported Icons_** :

`discord`, `facebook`, `github`, `instagram`, `linkedIn`, `mastodon`, `slack`, `twitter`, `youtube`

**_Also you can use your **_custom svg icons_** like this_** :
```js
 #{
  icon: {
          svg: ' ', //Svg Icon Code
        },
  link: " ", //Paste Your Link
},
```

**Cheers!** ✨

**Comment by RSS1102** [comment]
> youtube

ok, i see it ,thanks.
```ts
  export type SocialLinkIcon =
    | 'discord'
    | 'facebook'
    | 'github'
    | 'instagram'
    | 'linkedin'
    | 'mastodon'
    | 'slack'
    | 'twitter'
    | 'youtube'
    | { svg: string }
```
