### ISSUE TITLE
Team Page Customization

### ISSUE THREAD

**Issue by KishanGupta114** [vuejs/vitepress#2194]
### Discussed in https://github.com/vuejs/vitepress/discussions/2188

<div type='discussions-op-text'>

<sup>Originally posted by **KishanGupta114** April  4, 2023</sup>
## How to customize Team Page?
I want to add more details to Team Card, but unfortunately, I'm unable to do that.
If there is any possible way to do that please help.

</div>

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/issues/2201#issuecomment-1509877240
