### ISSUE TITLE
VitePress does not respect `server.headers` in Vite config

### ISSUE THREAD

**Issue by turbosheep44** [vuejs/vitepress#2195]
### Describe the bug

The `server.headers` field in the Vite config is ignored.

### Reproduction

Define the `vite.server.headers` field in `defineConfig`.

```
export default defineConfig({
  lang: 'en-US',
  title: 'app',

  themeConfig: { ... },

  vite: {
    server: {
      headers: {
        'X-Custom-Header': 'header-value',
      },
    },
  },
})

```

Start the server with `vitepress dev [root]` (or `vitepress build [root] && vitepress preview [root]`).

The header `X-Custom-Header` is not supplied when accessing the site.

### Expected behavior

The header `X-Custom-Header` should be given when accessing the site.

### System Info

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 6.98 GB / 11.70 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    vitepress: ^1.0.0-alpha.64 => 1.0.0-alpha.32
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wudexiong** [comment]
@turbosheep44 
temporary solution:
```js
import { defineConfig } from 'vitepress';
export default defineConfig({
    vite: {
        plugins: [{
            configureServer(server) {
                    server.middlewares.use((_req, res, next) => {
                        res.setHeader("X-Custom-Header", "header-value");
                        next();
                    });
             }
        }]
    }
})
```

**Comment by brc-dd** [comment]
vitepress preview doesn't use vite. those headers will be there only in the dev server
