### ISSUE TITLE
can not handle encoded image URLs in build mode

### ISSUE THREAD

**Issue by foisonocean** [vuejs/vitepress#220]
**Describe the bug**
In the markdown file, When reference a image file with encoded URL, it works in the dev mode, but it would faild to build.

**To Reproduce**
1. a image file named `image (01).png`.
1. a markdown file with content like this: `![](./image%20%2801%29.png)`
1. run `vitepress build`

**Expected behavior**
Should build successfully.

**System Info**
- vitepress version: 0.11.5
- vite version: 2.0.0-beta.62
- Node version: 2.0.0-beta.62
- OS version: Windows 10

**Comment by kiaking** [comment]
Thanks for the report! I think this is the same issue as https://github.com/vuejs/vitepress/issues/217. Closing this issue as a duplication.
