### ISSUE TITLE
docs: make a list of docs powered by vitepress 

### ISSUE THREAD

**Issue by Evavic44** [vuejs/vitepress#2201]
Might be a great idea to curate docs powered by vitepress for inspiration or examples.
A few I can think of besides vite, vue and vitest
- [stackblitz](https://developer.stackblitz.com/)
- [adocs](https://adocs.vercel.app)
- [dicebear](https://www.dicebear.com/)
- [fakerjs](https://fakerjs.dev/)

**Comment by brc-dd** [comment]
https://www.vuetelescope.com/explore?framework.slug=vitepress

**Comment by Evavic44** [comment]
Oh wow. Didn't know this. 👍🏽 Is there a way to add to it?

**Comment by KishanGupta114** [comment]
> https://www.vuetelescope.com/explore?framework.slug=vitepress (you'll connect with GitHub to view all)

It's Amazing
Btw Is there any way to customize the Team Page?

**Comment by brc-dd** [comment]
> Is there a way to add to it?

Not sure, but if you open that extension on your site, it should index that.

**Comment by brc-dd** [comment]
> Btw Is there any way to customize the Team Page?

https://vitepress.dev/reference/default-theme-team-page, or maybe write one yourself instead of using our components?

**Comment by KishanGupta114** [comment]
> > Btw Is there any way to customize the Team Page?
> 
> https://vitepress.dev/reference/default-theme-team-page, or maybe write one yourself instead of using our components?

Okay will try
