### ISSUE TITLE
How to add a global <script> tag

### ISSUE THREAD

**Issue by YangguangZhou** [vuejs/vitepress#2203]
I want to add the <script> tag to all pages to use Umami analysis. What should I do?

[My website](docs.jerryz.com.cn)

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/site-config#head

Example:

https://github.com/vuejs/vitepress/blob/0e5ff773f3b1bd8725c1fc870c884714a0a43e80/docs/.vitepress/config.ts#L17-L25

**Comment by YangguangZhou** [comment]
Thank you
