### ISSUE TITLE
Default `vitepress` project initialized in `vite` + `vue` throws exceptions

### ISSUE THREAD

**Issue by drunkenvalley** [vuejs/vitepress#2220]
### Describe the bug

When running `npx vitepress init` the default path is `./`. This can cause problems.

After finishing installation and running to test the project is working I am greeted with this error.

![Screen Shot 2023-04-15 at 17 27 11](https://user-images.githubusercontent.com/1728144/232234109-90f5914b-36cd-461e-a112-11f94f44a3b1.png)

```bash
[plugin:vite:vue] At least one <template> or <script> is required in a single file component.
```

Resolving it was as simple as remaking the project, and changing the `vitepress` path to `./docs`.

### Reproduction

Reproducing repository: https://github.com/drunkenvalley/vitepress-reprod

1. Create vite project.
```bash
> npm create vite@latest
√ Project name: ... vite-project
√ Select a framework: » Vue
√ Select a variant: » TypeScript

Scaffolding project in path/to/project...

Done. Now run:

  cd vite-project
  npm install
  npm run dev
```
2. From project folder initialize `vitepress`
```bash
> npx vitepress init      

  vitepress v1.0.0-alpha.66

┌   Welcome to VitePress! 
│
◇  Where should VitePress initialize the config?
│  ./
│
◇  Site title:
│  My Awesome Project
│
◇  Site description:
│  A VitePress Site
│
◇  Theme:
│  Default Theme
│
◇  Use TypeScript for config and theme files?
│  Yes
│
◇  Add VitePress npm scripts to package.json?
│  Yes
│
└  Done! Now run npm run docs:dev and start writing.
```
3. Run `npm i -D vitepress` and `npm install`
4. Run `npm run docs:dev`

### Expected behavior

A default Vue project created with vite and the default vitepress settings should preferably be compatible out of the box. Alternatively, the *Getting Started* documentation should be a bit more explicit that an alternate path is not optional, but required, with an "existing" vite project.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 8.52 GB / 15.73 GB
  Binaries:
    Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.46)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.66 => 1.0.0-alpha.66
```

### Additional context

While not really an issue, it is a bit odd to not install `vitepress` when using the `npx vitepress init`.

### Validations

- [x] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Using it directly in other vite project will obviously cause conflicts. You need to have a separate root.
