### ISSUE TITLE
Local search: add `esc to close` entry on search footer

### ISSUE THREAD

**Issue by userquin** [vuejs/vitepress#2231]
### Describe the bug

Add `esc to close` entry on search footer, pressing `esc` close the search dialog

### Reproduction

https://unocss.dev/

### Expected behavior

Just add the entry to the footer.

### System Info

```shell
NA
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
already added it 😅
