### ISSUE TITLE
Incorrect breadcrumbs in local search

### ISSUE THREAD

**Issue by FlorianKoerner** [vuejs/vitepress#2238]
### Describe the bug

I don't even know what exactly is happening here, but the breadcrumbs in the local search are not correct here.

![image](https://user-images.githubusercontent.com/647303/232320421-7b19695e-14a4-4320-bbf3-24c1de7b4738.png)

### Reproduction

Create example page and search for `Foo`.

```
## Foo

Hello world

#### Bar

Hello world

## Baz

Hello world
```

### Expected behavior

Breadcrumbs should only show titles of the own hierarchy.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vitepress: 1.0.0-alpha.69 => 1.0.0-alpha.69
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah, we are aware of this too. Working on fixes.
