### ISSUE TITLE
Using the frontmatter variable with link

### ISSUE THREAD

**Issue by GulomovCreative** [vuejs/vitepress#2240]
### Is your feature request related to a problem? Please describe.

Is it possible to make the frontmatter variables can be used before the rendering of markdown? Like this:

```md
---
someLink: https://some.link
---

[Awesome frontmatter link]({{ $frontmatter.someLink }})
```

### Describe the solution you'd like

Now we're getting this:

```html
<p>[Awesome frontmatter link](https://some.link)</p>
```

I would like to get this:

```html
<a href="https://some.link"></a>
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Refer my third point here: https://github.com/vuejs/vitepress/issues/2099#issuecomment-1481350268
