### ISSUE TITLE
data loader files from package not working in dev

### ISSUE THREAD

**Issue by JohnCampionJr** [vuejs/vitepress#2242]
### Describe the bug

I've built a fairly comprehensive blog theme for my use.  

https://github.com/jcamp-code/vitepress-blog-theme
https://vitepress-blog.netlify.app/blog/

It extends the default theme by using the slots and built in features of VitePress.  As you can see from the demo, it works just fine.  I was hoping to package it up and be able to use it across a few sites so that I could make updates in one place and just update the package of my sites.

However, when I try that, the new site throws 

```
Unknown file extension ".css"
Unknown file extension ".vue"
```

It's not processing these files from the package correctly

### Reproduction

https://github.com/jcamp-code/starter-vitepress-blog

### Expected behavior

Would like VitePress to properly pull in Vue and CSS files from packages

### System Info

```shell
NA
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It should've worked. I'll take a look when I get time. For reference you can see https://github.com/vuejs/theme (being used at https://github.com/vuejs/docs). Basically you just have to ship the components as if you're putting in your .vitepress/theme directory. Only ts part (composables, utils) needs compilation.

**Comment by JohnCampionJr** [comment]
OK, I'll review the vuejs theme and try to pinpoint what I'm missing :)

**Comment by JohnCampionJr** [comment]
OK, I've gotten the .vue / .ts extensions problem fixed by following the vuejs theme.  However, it seems VitePress still doesn't process .data files correctly in packaged themes.

Working on updating repos for a reproduction.

**Comment by brc-dd** [comment]
Yeah, so data files need to be in the final repo. You can probably do something like this:

```ts
// from your theme:

export default {
  load() {
    return {
      data: 'hello'
    }
  }
}
```

ask users to create a `posts.data.ts` file having

```ts
export * from 'your-theme/posts'
```

**Comment by JohnCampionJr** [comment]
In addition to discovering that it works ok in build but not dev, I have finally found the cause.

My theme exports its composables:
```
export { useArchives } from './composables/useArchives'
export { useAuthors } from './composables/useAuthors'
export { usePosts } from './composables/usePosts'
export { useTags } from './composables/useTags'
```

Apparently these are not getting transformed by vite or else its too late in the process.  If I comment out these exports, all works as expected.

**Comment by JohnCampionJr** [comment]
If I set them up allowing them to be directly imported:

package.json
``` 
  "exports": {
    ".": "./src/theme/index.ts",
    "./node": "./dist/node/index.js",
    "./composables/usePost": "./src/theme/composables/usePost.ts"
  },

```

And import them that way, all works as expected too.  There is maybe an upstream bug where the re-exporting is not getting transformed for some reason.

**Comment by JohnCampionJr** [comment]
> If I set them up allowing them to be directly imported:
> 
> package.json
> 
> ```
>   "exports": {
>     ".": "./src/theme/index.ts",
>     "./node": "./dist/node/index.js",
>     "./composables/usePost": "./src/theme/composables/usePost.ts"
>   },
> ```
> 
> And import them that way, all works as expected too. There is maybe an upstream bug where the re-exporting is not getting transformed for some reason.

This was wrong, importing them this way allows the build to work but upon actually using the composable, I'm getting the same data error.   So there is still some sort of issue here.

**Comment by JohnCampionJr** [comment]
I've made it as easy as possible to see here:

https://github.com/jcamp-code/starter-vitepress-blog

If and only if you add the code from PR#2272 and you run this project, you should get error:

```
X [ERROR] No matching export in "node_modules/.pnpm/@jcamp+vitepress-blog-theme@0.1.5_vitepress@1.0.0-alpha.73/node_modules/@jcamp/vitepress-blog-theme/src/theme/composables/posts.data.ts" for import "data"

    node_modules/.pnpm/@jcamp+vitepress-blog-theme@0.1.5_vitepress@1.0.0-alpha.73/node_modules/@jcamp/vitepress-blog-theme/src/theme/composables/usePosts.ts:3:9:
      3 │ import { data as posts } from './posts.data'
        ╵          ~~~~
```

If you uncomment out the lines in `TestLocalComponent.vue` the site will work as expected (if and only if you add the code from PR#2272)

**Comment by brc-dd** [comment]
Resolution:

```ts
    optimizeDeps: {
      exclude: ['@jcamp/vitepress-blog-theme'],
    },
```
