### ISSUE TITLE
showDetailedList not work

### ISSUE THREAD

**Issue by imbyter** [vuejs/vitepress#2244]
### Describe the bug

showDetailedList not work in Local search function。

I am in dev  mode, the error:
```
TypeError: Failed to resolve module specifier '\测试\14.md?t=1681703812524'
    at fetchExcerpt (VPLocalSearchBox.vue:204:53)
    at VPLocalSearchBox.vue:136:52
    at Array.map (<anonymous>)
    at debouncedWatch.debounce (VPLocalSearchBox.vue:136:41)
    at Promise.resolve.filter.fn.fn (index.mjs?v=1aac7394:327:39)
    at index.mjs?v=1aac7394:370:17
```

index.mjs?v=1aac7394:327
```
function createFilterWrapper(filter, fn) {
  function wrapper(...args) {
    return new Promise((resolve, reject) => {
      Promise.resolve(filter(() => fn.apply(this, args), { fn, thisArg: this, args })).then(resolve).catch(reject);
    });
  }
  return wrapper;
}
```
 the error cause on: Promise.resolve(filter(() => fn.apply(this, args), { fn, thisArg: this, args })).then(resolve).catch(reject);

### Reproduction

...

### Expected behavior

...

### System Info

```shell
...
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide a reproducible example and the vitepress version you're running.

**Comment by imbyter** [comment]
详细情况和 https://github.com/vuejs/vitepress/issues/2245 类似，初始化项目后，在最原始的文件结构下，在不选择“Display detailed list”的情况下，一切正常，当选择了“Display detailed list”，不管输入什么搜索关键字，都会报错：
![1](https://user-images.githubusercontent.com/53294133/232402244-8e37aede-f0a2-4386-9b9a-45d095aaa340.png)
![2](https://user-images.githubusercontent.com/53294133/232402262-f088fa4a-9e8a-496b-9a23-19b12e9d8c31.png)
![3](https://user-images.githubusercontent.com/53294133/232402270-da5b8567-9799-44c5-ae36-db7bf8dc15ba.png)

@brc-dd

**Comment by brc-dd** [comment]
Hey that other issue is somewhat different I guess. For you, is it only happening on `vitepress dev` or on `vitepress build` and `vitepress preview` too?

**Comment by LanXiaoChr** [comment]
In #2245 , `vitepress dev` has the same problem.
![222222222](https://user-images.githubusercontent.com/48700158/232413159-1f7f53d6-5143-4a15-b6d7-4f932ca2fc88.png)
@brc-dd

**Comment by brc-dd** [comment]
Oh, ok. IG the issue is here with the different slashes in Windows. Will take a look.
