### ISSUE TITLE
detailed view in local search breaks if fetched excerpt has useData call

### ISSUE THREAD

**Issue by LanXiaoChr** [vuejs/vitepress#2245]
### Describe the bug

When I create a new folder in the root directory and create an md file in the new folder. Then click the 'Display detailed list' button and search. Details are not displayed in the search results. And an error appears in the console.
```
GET http://localhost:4173/assets/guide/test_index.md.undefined.js net::ERR_ABORTED 404 (Not Found)
TypeError: Failed to fetch dynamically imported module: http://localhost:4173/assets/guide/test_index.md.undefined.js
```

### Reproduction

**1. Install (Default configuration)**
```
npm init -y
npm i -D vitepress
npx vitepress init
```
File structure:
```
.
├─ .vitepress
│  └─ config.ts
├─ api-examples.md
├─ markdown-examples.md
├─ index.md
└─ package.json
```

**2. Create folders and files**
File structure:
```
.
├─ guide
│  └─ test.md
├─ .vitepress
│  └─ config.ts
├─ api-examples.md
├─ markdown-examples.md
├─ index.md
└─ package.json
```
guide/test.md
```
# vite
vitepress
```

**3. Turn on local search**
config.ts
```
import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "My Awesome Project",
  description: "A VitePress Site",
  themeConfig: {
    search: {
      provider: 'local'
    },
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Examples', link: '/markdown-examples' }
    ],

    sidebar: [
      {
        text: 'Examples',
        items: [
          { text: 'Markdown Examples', link: '/markdown-examples' },
          { text: 'Runtime API Examples', link: '/api-examples' }
        ]
      }
    ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
    ]
  }
})
```

**4. Build and preview**
```
npm run docs:build
npm run docs:preview
```

**5. Search**
![111111111111](https://user-images.githubusercontent.com/48700158/232397128-a0480633-ac91-4c68-a12f-258e6888c7c4.png)

### Expected behavior

Show the details.

### System Info

```shell
Windows 10 22H2
NodeJS v16.14.0
Edge 112.0.1722.48
Vitepress 1.0.0-alpha.72
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Let's track this at #2244 itself.

**Comment by LanXiaoChr** [comment]
This issue is not resolved in the `1.0.0-alpha.72` (#2244 , #2248) release, and a new bug has occurred in `npm run docs:dev`.
This new error appears after installation with the default configuration:
```
npm init -y
npm i -D vitepress
npx vitepress init
npm run docs:dev
```
![111111111111](https://user-images.githubusercontent.com/48700158/232525680-cafda5a6-d85e-49d2-aa42-81f7015c9e7d.png)


@brc-dd

**Comment by brc-dd** [comment]
My windows device is not in good shape. Someone else will have to debug and fix this. 😓

**Comment by brc-dd** [comment]
Ah this one is not related to OS. Will see what's the issue.

**Comment by LanXiaoChr** [comment]
Now there are **two issues** that need to be addressed in this issue, they have different errors:
One is the problem that just mentioned in `npm run docs:dev`.
Another is a problem that occurs in `npm run docs:build`.

My English is translated using translation software and it may have some grammatical errors.

**Comment by brc-dd** [comment]
For now consider disabling detailed view (`disableDetailedView: true`) if you have pages that use `useData`.

**Comment by zonemeen** [comment]
I'll try to fix this when I have time later.
