### ISSUE TITLE
Cannot fetch from remote data

### ISSUE THREAD

**Issue by mahendra2448** [vuejs/vitepress#2247]
### Describe the bug

Simply, I need to fetch a custom markdown into a page. I follow [this](https://vitepress.dev/guide/routing#rendering-raw-content) instruction but keep getting this error whenever run `docs:dev`
```
failed to start server. error:
ReferenceError: fetch is not defined
```

folder structure:

```
.
├─ docs
│  ├─ .vitepress
│  ├─ components
│  └─ introduction
│  │  └─ [intro].md
│  │  └─ [intro].paths.js
```

[intro].md
```md
<!-- @content -->
```

[intro].paths.js
```js
export default {
  paths() {
    async paths() {
      const posts = await (await fetch('http://some-url/api/intro/overview')).json()

      return posts.map((post) => {
        return {
          params: { intro: post.menu },   // should return 'overview' menu
          content: post.markdown          // raw Markdown from fetch
        }
      })
    }
  }
}
```

Please anyone help me resolve this. Thank you.

### Reproduction

if the code like this:
[intro].paths.js
```js
export default {
  paths() {
    async paths() {
      const posts = await (await fetch('http://some-url/api/intro/overview')).json()

      return posts.map((post) => {
        return {
          params: { intro: post.menu },   // should return 'overview' menu
          content: post.markdown          // raw Markdown from fetch
        }
      })
    }
  }
}
```

the error would look like this:
```shell
✘ [ERROR] Expected "=>" but found "("

    docs/introduction/[intro].paths.js:14:15:
      14 │     async paths() {
         │                ^
         ╵                =>
Invalid paths file export in .../docs/introduction/[intro].paths.js. Expects default export of an object with a "paths" property.
```

BUT, if I remove the *paths()* code like this:
[intro].paths.js
```js
export default {
    async paths() {
      const posts = await (await fetch('http://some-url/api/intro/overview')).json()

      return posts.map((post) => {
        return {
          params: { intro: post.menu },   // should return 'overview' menu
          content: post.markdown          // raw Markdown from fetch
        }
      })
    }
}
```

the error would look like this:
```shell
failed to start server. error:
ReferenceError: fetch is not defined
```

### Expected behavior

The code inside `*.paths.js` successfully fetch data from my API and render the custom raw markdown text to `content`. what should I do?

### System Info

```shell
vitepress v1.0.0-alpha.71
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You're probably some old Node.js version. Either upgrade it, or use something like node-fetch/axios/got.

**Comment by mahendra2448** [comment]
I have tried use `node-fetch` but have no idea where to import the 'node-fetch' and use it on my `[intro].paths.js`
Now I'm trying to upgrade my nodejs since mine is on `16.x`

**Comment by mahendra2448** [comment]
Updating the nodejs version. It worked for me. Thank you.
