### ISSUE TITLE
redirect web-page to specify directory with language in b

### ISSUE THREAD

**Issue by sunflower-knight** [vuejs/vitepress#2251]
### Is your feature request related to a problem? Please describe.

I delopy my vitepress website in github page and there are many langauge locales directory . I want readers can redirect to their  default homepage depend on their web browser language .

### Describe the solution you'd like

```js
var lang = null;
function language() {
    var language = null;
    if (navigator.appName == 'Netscape') {
        language = navigator.language;
    } else {
        language = navigator.browserLanguage;
    }
    if (language.indexOf('zh') > -1) {
        lang = "zh"
        window.location.href = "/yalantinglibs/zh/index.html";
    } else {
        window.location.href = "/yalantinglibs/en/index.html";
    }
}

language()
```

I use this way in a opensource code  

[click here to see html](https://github.com/alibaba/yalantinglibs/blob/ec37ed2a2d4467a33743a11221be2af8fe0a1e4a/website/docs/public/index.html)

[click here too to see js ](https://github.com/alibaba/yalantinglibs/blob/ec37ed2a2d4467a33743a11221be2af8fe0a1e4a/website/docs/public/index.js)

But I want to use this feature in vitepress rather than write this code myself.

### Describe alternatives you've considered

I just want a redirect depend on readers's webserver language config.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by azat-io** [comment]
I created `root` view in my own project for this:
https://github.com/azat-io/azat-io/blob/main/content/.vitepress/theme/pages/root.vue

**Comment by brc-dd** [comment]
Having to write 2-3 lines of code is not a big deal. Your code can probably be simplified to:

```ts
const lang = window.navigator.language || ''
window.location.href = `/yalantinglibs/${/zh/.test(lang) ? 'zh' : 'en' }/index.html`
```
