### ISSUE TITLE
Local Search has performance issues when detailed list is enabled

### ISSUE THREAD

**Issue by RaniAgus** [vuejs/vitepress#2262]
### Describe the bug

If I edit the search terms with detailed list enabled, the whole page gets frozen until the search is complete.

### Reproduction

1. Click on search
2. Enable detailed list
3. Slowly enter a search term, letter by letter

### Expected behavior

The query shouldn't freeze the whole page until it's completed. Also, if the query isn't complete, I should be able to click somewhere else to cancel it and close the search dialog.

Also, it would be nice to have a spinner when the query is not complete.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 16.21 GB / 19.44 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - /mnt/c/Program Files/nodejs/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.14.0/bin/npm
  npmPackages:
    vitepress: 1.0.0-alpha.73 => 1.0.0-alpha.73
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by arcqiufeng** [comment]
The page freezes when I enter text in the search box. I have the same problem when detail is enabled.

**Comment by brc-dd** [comment]
For now consider disabling the detailed view - `search.options.disableDetailedView: true`
