### ISSUE TITLE
vitepress contaminated element-plus css

### ISSUE THREAD

**Issue by zhoufanglu** [vuejs/vitepress#2266]
### Describe the bug

* demo 
![image](https://user-images.githubusercontent.com/24451091/233577880-b8f84ab4-dfa1-4cb8-a48b-15ab45e0d17f.png)

* demo in vitepress
contaminated element-plus css
![image](https://user-images.githubusercontent.com/24451091/233577986-c7621b92-2872-4d6a-ac5a-72e312fae89f.png)

### Reproduction

vitepress contaminated element-plus css

### Expected behavior

keep the original style

### System Info

```shell
--
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/guide/markdown#raw
