### ISSUE TITLE
Bugs caused by image suffix capitalization

### ISSUE THREAD

**Issue by imbyter** [vuejs/vitepress#2277]
### Describe the bug

when I use a .png in xx.md file, it is OK,  when i use a .PNG, get error.
![2](https://user-images.githubusercontent.com/53294133/233841251-d18168d1-fead-4270-a905-ab6ee861a680.png)

This issue only occurs when using the `docs:build` command, it is fine in `docs:dev`

### Reproduction

  vitepress v1.0.0-alpha.73

Windows 11

### Expected behavior

.

### System Info

```shell
.
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Refer https://github.com/vuejs/vitepress/issues/1968#issuecomment-1438770596

```ts
// .vitepress/config.ts
import { defineConfig } from 'vitepress'

export default defineConfig({
    vite: {
        assetsInclude: ['**/*.PNG']
    }
})
```
