### ISSUE TITLE
🐞 Dead link warning even if we resolve it via a tag as per suggestion

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/vitepress#2281]
### Describe the bug

If we add link like below:
```
Visit <a href="http://localhost:5173" target="_blank" rel="noreferrer">http://localhost:5173</a>
```

And run the server, we get error like below:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/47495003/233909541-25e26fbe-c466-4299-a53c-efeabd266974.png">

### Reproduction

https://stackblitz.com/edit/vite-fiz6gv?file=docs/example.md

### Expected behavior

As we have updated the code from md link syntax `()[]` to a tag as per suggestion it shouldn't show this warning.

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 82.20 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0
    Safari: 16.3
  npmPackages:
    vitepress: 1.0.0-alpha.73 => 1.0.0-alpha.73
```

### Additional context

None

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
Hi @jd-solanki 
You can configure it like this in siteConfig to avoid warning.
```ts
export default defineConfig({
  ignoreDeadLinks: true
})
```
or
```ts
export default defineConfig({
  ignoreDeadLinks: [
    // ignore all localhost links
    /^https?:\/\/localhost/
  ]
})
```

**Comment by jd-solanki** [comment]
We do have seperate config for ignoring localhost link but point I'm trying to make is suggested solution in console doesn't work

**Comment by zRains** [comment]
MarkdownIt will collect plain text links. This means that the link(#) between `a` tag will be treated as `[](#)`. You can rewrite it as:

```html
<a href="http://localhost:5173/" target="_blank" rel="noreferrer" v-text="'http://localhost:5173/'"></a>
```

The suggestions given by the console can be:

```typescript
;(siteConfig?.logger ?? console).warn(
  c.yellow(
    `\n(!) Found dead link ${c.cyan(url)} in file ${c.white(
      c.dim(file)
    )}\nIf it is intended, you can use:\n    ${c.cyan(
      `<a href="${url}" target="_blank" rel="noreferrer" v-text="'${url}'"></a>`
    )}`
  )
)
```

**Comment by brc-dd** [comment]
Feel free to create a PR remove that suggestion entirely. Just recommend users to visit the docs. There is no need of workarounds now, one can explicitly mark links to ignore from being checked in the config.

**Comment by jd-solanki** [comment]
Sorry I didn't get what you mean by:

> _Just recommend users to visit the docs_

---

> _one can explicitly mark links to ignore from being checked in the config_

How?

**Comment by brc-dd** [comment]
> How?

`ignoreDeadLinks` now accepts an array (of strings/regex/functions). So you basically can have any functionality there:

https://vitepress.dev/reference/site-config#ignoredeadlinks
