### ISSUE TITLE
Use custom component with slot, When preview the build files, Got an error "Hydration completed but contains mismatches."

### ISSUE THREAD

**Issue by cnscoo** [vuejs/vitepress#2284]
### Describe the bug

Use custom component with slot, When preview the build files, Got an error "Hydration completed but contains mismatches." and the page content is distorted.

### Reproduction

Demo: [https://stackblitz.com/edit/vite-7ctcqz?file=docs/.vitepress/theme/index.js](https://stackblitz.com/edit/vite-7ctcqz?file=docs/.vitepress/theme/index.js)

**Steps**

- Build project
- Run `npm run docs:preview`
- Visit the page and click "Get Start" button redirect to the example page.
- Refresh the example page

Now I got an error "Hydration completed but contains mismatches." and the page content is distorted.

### Expected behavior

No errors.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 13.25 GB / 31.73 GB
  Binaries:
    Node: 18.16.0 - D:\Program\NodeJs\node.EXE
    npm: 9.6.5 - D:\Program\NodeJs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.58)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.73 => 1.0.0-alpha.73
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
Issue similar to https://github.com/vuejs/vitepress/issues/2441

Since the `a` tag is nested inside the `a` tag.

Server-rendered HTML: `<a><a></a></a>`

Browser-rendered HTML: `<a></a><a></a>`

If you want to use it this way and not get an error, you can rewrite the `Site` component like this:

```vue
<template>
  <ClientOnly>
    <a
      :href="href"
      target="_blank"
      class="site-item"
      style="text-decoration: none"
    >
      <div class="site-item-head">
        <div v-if="icon" class="site-item-icon">
          <img :src="icon" :title="title" shape="square" />
        </div>
        <div class="site-item-title">{{ title }}</div>
      </div>
      <div v-if="description" class="site-item-body">{{ description }}</div>
      <div class="site-item-actions">
        <slot></slot>
      </div>
    </a>
  </ClientOnly>
</template>
```

Demo: https://stackblitz.com/edit/vite-mgtacj
