### ISSUE TITLE
貌似从7.3开始本地搜索报错

### ISSUE THREAD

**Issue by lxmfcc** [vuejs/vitepress#2287]
### Describe the bug

只是开启本地搜索未做任何更改

![捕获](https://user-images.githubusercontent.com/68628878/234206500-63f2b122-9d4e-4ccf-a81b-122e2dba587c.PNG)

### Reproduction

![捕获](https://user-images.githubusercontent.com/68628878/234206500-63f2b122-9d4e-4ccf-a81b-122e2dba587c.PNG)

### Expected behavior

![捕获](https://user-images.githubusercontent.com/68628878/234206500-63f2b122-9d4e-4ccf-a81b-122e2dba587c.PNG)

### System Info

```shell
![捕获](https://user-images.githubusercontent.com/68628878/234206500-63f2b122-9d4e-4ccf-a81b-122e2dba587c.PNG)
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by LanXiaoChr** [comment]
是的，本地搜索存在问题，可以看这个 #2245 。（在靠近底部的回复中的内容）
现在只能禁用详细内容。
`search.options.disableDetailedView: true`

**Comment by arcqiufeng** [comment]
我也有同样的问题。不知与是否与中文有关。
I have the same problem. I have the same problem. I don't know if it's CJK related.

**Comment by zonemeen** [comment]
有复现的demo吗

**Comment by LanXiaoChr** [comment]
```
npm init -y
npm i -D vitepress
npx vitepress init
npm run docs:dev
```
默认安装后，启用本地搜索，然后点击 `Display detailed list` ，随便搜索已有内容，例如 `a` ，都可以复现。
@zonemeen

**Comment by zonemeen** [comment]
我的windows10电脑复现不了，很奇怪，安装的最新vitepress版本
![image](https://user-images.githubusercontent.com/44596995/234528487-4d5a994f-7035-4a6c-9e9a-14ac2c8be484.png)

**Comment by LanXiaoChr** [comment]
我上传了一个 `Stackblitz` ，但我之前没有使用过它，不知道是否是直接分享链接即可。
在这里我仍然能复现该问题，我尝试了切换浏览器但仍然没有解决。
```
npm run docs:dev
```
https://stackblitz.com/edit/node-ezqew6

![QQ截图20230426172247](https://user-images.githubusercontent.com/48700158/234533082-78da1b03-2cf6-4428-be3a-51c214f04bc3.png)

**Comment by LanXiaoChr** [comment]
我也不清楚具体的原因，该问题好像并不只出现在Windows系统中，详见 #2253 的倒数第二个回复。

**Comment by zonemeen** [comment]
我复现出来了，是有些问题，我有空的时候尝试去修复一下

**Comment by lxmfcc** [comment]
貌似因为我执行了pnpm add vue -D 单独安装了VUE就会出现这个错误，具体原因不知道。

**Comment by zRains** [comment]
在启动本地搜索详细内容选项时，`VPLocalSearchBox`组件会通过新建一个Vue app实例重新挂载结果页面，以获取渲染的结果内容：

https://github.com/vuejs/vitepress/blob/f7443643a4510a6c650f1a1bda977c1d55fddf64/src/client/theme-default/components/VPLocalSearchBox.vue#L153-L157

但好巧不巧的是在`api-examples.md`示例文件里存在：
```typescript
<script setup>  
import { useData } from 'vitepress'

const { site, theme, page, frontmatter } = useData()
</script>
```
这部分代码中的`useData()`会在新环境中执行，但`dataSymbol`所对应的数据不存在会导致获取到`undefined`导致报错。
