### ISSUE TITLE
The drop-down menu of the top navigation appears infinitely triggering the drop-down to collapse.

### ISSUE THREAD

**Issue by Ruler1020730** [vuejs/vitepress#2288]
### Describe the bug

In the official Vue.js document, the drop-down menu of the top navigation has an exception of infinitely triggering the drop-down to collapse.

### Reproduction

https://user-images.githubusercontent.com/47056082/234228099-37dad552-eeb4-4507-baf1-2b6cbab5a3fc.mov

### Expected behavior

Normal Trigger PulldownCollapse.

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 500.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.2/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Ruler1020730** [comment]
After triggering the drop-down menu, moving from the inside to another menu (from the bottom), the bug must be triggered

**Comment by Ruler1020730** [comment]
https://user-images.githubusercontent.com/47056082/234230124-cd6ccb7e-ecef-4d87-9088-f817c2387a33.mov

**Comment by brc-dd** [comment]
Create an issue at https://github.com/vuejs/theme instead. Official site doesn't use the default theme. Some padding needs to be adjusted probably.
