### ISSUE TITLE
How to dynamically introduce svg into VPTeamMembers's icon?

### ISSUE THREAD

**Issue by you-hengh** [vuejs/vitepress#2290]
### Describe the bug

I have loaded svg according to the method described in the document, and it works normally, but the code fragment of this svg is too long, which affects the later code maintenance very much. I hope that this icon can support dynamic introduction, so that the code can be easily maintained.

### Reproduction

<img width="958" alt="image" src="https://user-images.githubusercontent.com/34816426/234260488-4b99a70b-39a2-4d4d-a32a-7d5391420f0e.png">

As shown in the figure, the code of this svg is very long!

### Expected behavior

<img width="815" alt="image" src="https://user-images.githubusercontent.com/34816426/234261175-de8db98e-41bb-4661-a318-104560c18140.png">

I hope that the loading of svg can support import () or url () to introduce icon, so that the code will look much more comfortable

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.48 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: 109.0.1518.70
    Safari: 16.4
  npmPackages:
    vitepress: 1.0.0-alpha.72 => 1.0.0-alpha.72
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
```ts
import icon from 'path/to/file.svg?raw'

// ...

{ icon: icon, link: '...' }
```

**Comment by you-hengh** [comment]
> ```ts
> import icon from 'path/to/file.svg?raw'
> 
> // ...
> 
> { icon: icon, link: '...' }
> ```

Thank you for your reply. I tried according to the method you provided, but the svg icon is not displayed on the web page.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/34816426/234273992-89831f72-d53f-4455-baa6-0ff74e1695b5.png">

**Comment by brc-dd** [comment]
You forgot the `?raw` in import.

**Comment by you-hengh** [comment]
> You forgot the `?raw` in import.

No, it didn't work. I wrote 'raw` before.

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/34816426/234277913-12acb8dd-8a92-4a6b-8628-0026fef3175f.png">

I make sure there is nothing wrong with my svg file
```css
<svg t="1682419655204" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3786" width="24" height="24" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M972.8 742.4c25.6 0 44.8 19.2 44.8 44.8s-19.2 44.8-44.8 44.8-44.8-19.2-44.8-44.8 25.6-44.8 44.8-44.8z m-147.2 0c25.6 0 44.8 19.2 44.8 44.8s-19.2 44.8-44.8 44.8-44.8-19.2-44.8-44.8 19.2-44.8 44.8-44.8z m-153.6 0c25.6 0 44.8 19.2 44.8 44.8s-19.2 44.8-44.8 44.8c-25.6 0-44.8-19.2-44.8-44.8s19.2-44.8 44.8-44.8zM467.2 601.6c25.6 0 44.8 19.2 44.8 44.8 0 25.6-19.2 44.8-44.8 44.8H236.8c-25.6 0-44.8-19.2-44.8-44.8 0-25.6 19.2-44.8 44.8-44.8h230.4z m166.4-198.4c25.6 0 44.8 19.2 44.8 44.8s-19.2 44.8-44.8 44.8H236.8c-19.2-6.4-38.4-25.6-38.4-44.8s19.2-44.8 44.8-44.8h390.4z m0-198.4c25.6 0 44.8 19.2 44.8 44.8 0 25.6-19.2 44.8-44.8 44.8H236.8c-25.6 0-44.8-19.2-44.8-44.8 0-25.6 19.2-44.8 44.8-44.8h396.8zM601.6 1024H140.8C64 1024 0 960 0 876.8V147.2C0 64 64 0 140.8 0h588.8c76.8 0 140.8 64 140.8 147.2V576c0 25.6-19.2 44.8-44.8 44.8s-44.8-19.2-44.8-44.8V147.2c0-32-25.6-57.6-57.6-57.6H140.8c-32 0-57.6 25.6-57.6 57.6v736c0 32 25.6 57.6 57.6 57.6h460.8c25.6 0 44.8 19.2 44.8 44.8 0 19.2-19.2 38.4-44.8 38.4z" fill="#0061D5" p-id="3787"></path></svg>
```

**Comment by brc-dd** [comment]
ah sorry, it should be `{ icon: {svg: blog}, link: '...'`

**Comment by aiktb** [comment]
`import ... from '....svg?raw'`can't be used in config.js, so it can also be like this:
```javascript
      {
        icon: {
          svg: `<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                     <title>Email</title>
                     <use xlink:href="/email.svg#email"/>
                </svg>`
        },
        link: ' ... '
      }
```
The viewBox needs to be consistent with the svg file in the public folder to scale correctly, and the xlink:href needs to be consistent with the id in the svg file.

**Comment by brc-dd** [comment]
@aiktb It's not config file. The OP is using it in a Vue component / MD file with Team Member component. Your method should work with `socialLinks`. SVG sprites should also work, or in the config file one can also just do fs.readFile or directly use the simple-icons package.

**Comment by you-hengh** [comment]
> `import ... from '....svg?raw'`can't be used in config.js, so it can also be like this:
> 
> ```js
>       {
>         icon: {
>           svg: `<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
>                      <title>Email</title>
>                      <use xlink:href="/email.svg#email"/>
>                 </svg>`
>         },
>         link: ' ... '
>       }
> ```
> 
> The viewBox needs to be consistent with the svg file in the public folder to scale correctly, and the xlink:href needs to be consistent with the id in the svg file.

Thank you for your reply, but even so, I still feel that the svg code is too long and looks messy. I have used the syntax of `{icon: {svg: blog}, link:''}`
