### ISSUE TITLE
m1 mac feel stuck when i use itab plugin in microsoft-edge

### ISSUE THREAD

**Issue by RrowR** [vuejs/vitepress#2294]
### Describe the bug

https://user-images.githubusercontent.com/26684446/234516220-63b4ac62-a6d1-4cad-9dbc-030477cea8b3.mp4

when i press key to input something ,it Stuck and stopped very obviously

### Reproduction

use macbook pro m1 and use microsoft-edge also install itab plugin ,type input for chinese,it becomes stuck,google chrome not has this problem

### Expected behavior

use macbook pro m1 and use microsoft-edge also install itab plugin ,type input for chinese,it becomes stuck,google chrome not has this problem

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What has it to do with VitePress?
