### ISSUE TITLE
Support react？

### ISSUE THREAD

**Issue by gaogaoinvincible** [vuejs/vitepress#2295]
### Is your feature request related to a problem? Please describe.

Vitepress is so good，but I want use react，so...

### Describe the solution you'd like

like @vite/vitepress-plugin-react

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sagargurtu** [comment]
+1

I asked this in one of the discussions https://github.com/vuejs/vitepress/discussions/548?sort=new#discussioncomment-5057695.

**Comment by baiwusanyu-c** [comment]
cc：https://islandjs.dev/en/guide/getting-started

**Comment by brc-dd** [comment]
React components can be used like this: https://github.com/vuejs/vitepress/discussions/2183 but SSR won't work there.

Regarding that feature request on #548 for a framework-agnostic SSG, it won't be exactly feasible for us to implement that here. Currently, the functionality of VitePress is very closely coupled with Vue. React has totally different APIs for SSR, totally different router, markdown-it plugins too don't support JSX, we would need something like MDX + rehype for that to work. There'd be barely anything shared between the react and vue versions except Vite. It'd be like maintaining two separate tools. I'm not sure if we (the vue team members) are ready for that kind of commitment. Moreover, there are already many performant React SSGs like Nextra there in wild. vite-plugin-ssr (vike) too at one point might have nice support for cross framework SSG. But this is currently out of scope for VitePress.
