### ISSUE TITLE
Quasar and Vitepress: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Salimify** [vuejs/vitepress#2298]
### Describe the bug

While trying to run document some components built on top of Quasar components, I was unable to run `vitepress build docs` for my project and throwing error

> ✓ building client + server bundles...
✖ rendering pages...
build error:
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at installQuasar (......dist\quasar.cjs.prod.js:6:15454)
    at Object.install (......\quasar\dist\quasar.cjs.prod.js:6:491344)
    at Object.use (......\dist\runtime-core.cjs.prod.js:3350:28)
    at Object.enhanceApp (....../docs/.vitepress/.temp/app.js:5580:9)
    at createApp (....../docs/.vitepress/.temp/app.js:5881:17)
    at render (....../docs/.vitepress/.temp/app.js:5921:33)
    at renderPage (....../vitepress/dist/node/serve-c489c02c.js:41209:25)
    at ....../node_modules/vitepress/dist/node/serve-c489c02c.js:41742:21
    at Array.map (<anonymous>)

### Reproduction

**config.ts**

```typescript
import { defineConfig } from 'vitepress'
import vueJsx from '@vitejs/plugin-vue-jsx'
import * as path from "path";

export default defineConfig(
    {
      lang: 'en-US',
      title: 'MyLib',
      lastUpdated: true,
      titleTemplate: false,
      themeConfig: {
        siteTitle: 'MyLib',
        docFooter: {
          prev: 'Prev',
          next: 'Next'
        },
      },
      vite: {
        plugins: [
          vueJsx(),
        ],
        resolve: {
            alias: [
                {find: "@", replacement: path.resolve(__dirname, '../../src') },
                {find: "components", replacement: path.resolve(__dirname, '../components') }
            ],
            dedupe: ['vue', 'quasar', 'Quasar', 'pubsub-js'],
        },
        build: {
            rollupOptions: {
                external: ['vue', /quasar\/.+/]
            }
        },
      }
    }
)
````

**index.ts**

```typescript
import DefaultTheme from 'vitepress/theme'
import { App, onMounted } from 'vue'
import { dispatchEventStorage } from '../utils/tools'
import MyLib from 'my-lib '

import Container from "../components/Container.vue";
import {Quasar } from "quasar";
import {quasarConfig} from "@";

export default {
  ...DefaultTheme,
  enhanceApp ({ app }: { app: App }) {
    app.use(Quasar, {
      components: {
        ...quasarConfig.components,
      },
      directives: {
        ...quasarConfig.directives,
      },
      plugins: {
        ...quasarConfig.plugins,
      },
    });
    app.use(MyLib);
    app.component('Container', Container)
  },

  setup () {
    onMounted(() => {
      dispatchEventStorage()
    })
  }
}
```

### Expected behavior

As `vitepress dev docs` works fine and serving the documentation with the required component example, running 'vitepress build docs' is not running fine in rendering pages step.

### System Info

```shell
windows: 11,
node: v16.19.1
npm: 8.19.3
quasar: 2.10.2
vue: 3.2.47
vite: 4.3.1
vitepress: 1.0.0-alpha.73
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Might need to add Quasar related things in `vite.optimizeDeps.exclude` or `vite.ssr.noExternal`. Can you share the code using https://vitepress.new, it'll be easier for us to quickly test things there.

**Comment by Salimify** [comment]
> Might need to add Quasar related things in `vite.optimizeDeps.exclude` or `vite.ssr.noExternal`. Can you share the code using https://vitepress.new, it'll be easier for us to quickly test things there.

Issue reproduced on [stackblitz](https://stackblitz.com/edit/vite-vyfx9s) , everything seems to be working fine when running `vitepress dev docs`, but it still breaks when running `vitepress build docs`.
Both `vite.optimizeDeps.exclude` and `vite.ssr.noExternal` did not help.

**Comment by brc-dd** [comment]
Hey, tbh I have never used Quasar. So, is there some docs where they mention their vue plugin? My guess is it should have some special handling for SSR.

**Comment by brc-dd** [comment]
Okay, so I searched other issues on Quasar and found someone using it with VitePress. Here is what they are doing:

```ts
    app.use(Quasar, {}, { req: { headers: {} } });
```

https://stackblitz.com/edit/vite-acj5cz

It needs a third parameter called `ssrContext`. I can find it being referenced in their source code but I don't understand it fully.
