### ISSUE TITLE
[设计相关问题]当侧边栏存在多级时，是否有些缺乏美感？(上下之间的空隙太大)

### ISSUE THREAD

**Issue by yjrguxing** [vuejs/vitepress#2300]

**Comment by yjrguxing** [comment]
[Design-related issue] Does the sidebar look aesthetically pleasing when there are multiple levels? (There seems to be too much empty space between top and bottom)

**Comment by yjrguxing** [comment]
我尝试汇总不同的文档，所以在侧边栏存在多级分类，代码如下:
I am trying to consolidate different documents, so I have implemented the following code to have multiple levels of categorization in the sidebar:
```
                sidebar: [
                    {
                        text: 'Examples',
                        items: [
                            { text: 'Markdown Examples', link: '/en/markdown-examples' },
                            { text: 'Runtime API Examples', link: '/en/api-examples' }
                        ]
                    },
                    {
                        text: 'OpenAI',
                        items: [
                            {
                                text: 'Documentation',
                                items: [
                                    { text: 'GET STARTED'},
                                    { text: 'introduction', link: '/en/openai/api-reference/introduction' },
                                ]
                            },
                            {
                                text: 'API reference',
                                items: [
                                ]
                            }
                        ]
                    }
                ],
```

**Comment by yjrguxing** [comment]
但是实际出现的效果有些不符合预期，我想知道这在设计上是刻意为之嘛？(如下图所示)
However, the actual outcome is not what I expected. I am wondering if this design was intentional or not. (As shown in the image below)
![image](https://user-images.githubusercontent.com/38355410/234788158-3d02b727-46de-4e84-8274-b7823c4f5ac8.png)

**Comment by brc-dd** [comment]
Can you share a reproduction using https://vitepress.new? Something seems off in your screenshot. You can see our docs site: https://vitepress.dev/guide/what-is-vitepress, it does not has that much space:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/40380293/234789757-b27fa389-ee0d-4fc3-97b2-1ff01f174857.png"> <img width="238" alt="image" src="https://user-images.githubusercontent.com/40380293/234789687-83938f51-8862-4c2e-92d5-79a122e8e796.png">

**Comment by yjrguxing** [comment]
I apologize for the inconvenience. I have identified the root cause of the issue, and it turns out that I caused it myself. I imported openai's CSS on this page, which affected the sidebar and caused this problem. Thank you very much for your help, and I'm glad to inform you that the issue has been resolved.
Can we close this issue now since the problem has been resolved?
