### ISSUE TITLE
Search bar won't appear in header

### ISSUE THREAD

**Issue by SoCuul** [vuejs/vitepress#2305]
### Describe the bug

I've added the search property to my `config.js` file, but no search bar is appearing in the header of the page.
I'm having the same problem with local search and with algolia.

### Reproduction

```js
import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
// https://vitepress.dev/reference/default-theme-config

export default defineConfig({
    lang: 'en-CA',
    title: 'Pepsi Spire Wiki',
    description: 'A wiki about the mixture-focused soda fountain by PepsiCo.',

    base: '/',
    cleanUrls: true,
    lastUpdated: true,

    head: [
        [ 'meta', { name: 'theme-color', content: '#2e7ec9' } ],
    ],

    themeConfig: {
        i18nRouting: true,
        search: {
            provider: 'local'
        }
    }
})

```

### Expected behavior

The search bar should appear in the header of the webpage.

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 334.04 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.6.3 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0
    Safari: 16.4
    Safari Technology Preview: 16.4
  npmPackages:
    vitepress: ^1.0.0-alpha.65 => 1.0.0-alpha.65
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We will need more info than that. Can you share a reproducible example via https://vitepress.new or as a GitHub repo. Are the other properties specified in that file working?

**Comment by SoCuul** [comment]
The update actually fixed it! Thanks 😄
