### ISSUE TITLE
`base` option not generating correct multi sidebar

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vitepress#231]
**Describe the bug**
Yesterday's PR (https://github.com/vuejs/vitepress/pull/223) introduced the ability to have a base option work with dev mode. However this change breaks sidebar implementations and they no longer show up.

This happens in both dev and prod builds.

**To Reproduce**
The following config works without the base option set, but not with it:
```js
module.exports = {
  lang: 'en-US',
  title: 'Chalk UI 🐼',
  description: 'Vue Component Library',

  // base: '/test/',

  themeConfig: {
    docsDir: 'docs',

    nav: [
      { text: 'Components', link: '/components/' },
      { text: 'Style Guide', link: '/style-guide/' },
    ],

    sidebar: {
      '/components/': getComponentsSidebar(),
      '/style-guide/': getStyleGuideSidebar(),
    },
  }
}

function getComponentsSidebar () {
  return [{
    text: 'Components',
    children: [
      { text: 'Button', link: '/components/button' },
    ],
  }]
}

function getStyleGuideSidebar () {
  return [{
    text: 'Style Guide',
    children: [
      { text: 'Components', link: '/style-guide/components' },
      { text: 'State Machines', link: '/style-guide/state-machines' },
      {
        text: 'Tests',
        link: '/style-guide/tests',
        children: [
          { text: 'Components', link: '/style-guide/tests/components' },
          { text: 'State Machines', link: '/style-guide/tests/state-machines' },
        ],
      },
    ],
  }]
}
```

**Expected behavior**
The sidebars to appear (I think it might not resolve the files correctly anymore)

**System Info**
- vitepress version: 0.12
- vite version: 2.0.0-beta.50
- Node version: 12.19
- OS version: MacOS 11.2

**Comment by TheDutchCoder** [comment]
It also appears that `sidebar: 'auto'` no longer works (even though there was a PR merged for it not too long ago: https://github.com/vuejs/vitepress/pull/224)

**Comment by kiaking** [comment]
Confirmed. Sidebar not correctly showing with multi sidebar. Must be forgetting to take in `base` option in account when generating the sidebar in the theme.

@TheDutchCoder I can't confirm `auto` not working. It's working for me. What happens for you?

**Comment by TheDutchCoder** [comment]
@kiaking same result as specifying the sidebar manually, it's hidden in the CSS (and missing all children).
I'll upgrade all dependencies and see if that yields a different result.

**Comment by kiaking** [comment]
@TheDutchCoder I made a fix at #234. This should fix multi sidebar issue, but not sure about `auto`. Do you still see issue when you set sidebar to `auto`?

**Comment by TheDutchCoder** [comment]
Let me quickly check!

**Comment by TheDutchCoder** [comment]
@kiaking in 0.12.0 I still have that issue yes, Let me add some screenshots, maybe it helps

**Comment by kiaking** [comment]
Oh OK that's expected. You don't have heading to show on the sidebar. Try adding Level 2 headers to the markdown. Not sure if we should completely hide Sidebar when there're no headings in the markdown though 🤔  But that's some other issues to be discussed 👍

**Comment by ejimenez123** [comment]
Everything works fine for me with `vitepress dev docs` and with "vitepress serve docs" but when I use it on github it uploads it to me but the header and the menu sidebar don't appear. Help me please...
