### ISSUE TITLE
【Bug】localSearchPlugin breaks up other markdown plugin

### ISSUE THREAD

**Issue by theniceangel** [vuejs/vitepress#2313]
### Describe the bug

When i bump to `1.0.0-alpha.74` and configure the `search` field，start a server will get a error.
The reason is that my markdown plugin which depends on `env` parameters that contains `path` info in `markdownToVue.ts`
<img width="422" alt="image" src="https://user-images.githubusercontent.com/25956811/235289997-3cec0b29-928e-48b5-9fd6-f08ccf9843a9.png">

But when I configure the `search` field in `config.ts`, in `localSearchPlugin.ts` which use `md.render(await fs.readFile(file, 'utf-8'))`, It lacks `path` info in `env` object as belows:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/25956811/235290138-db1936d5-3b2d-420d-b983-bbd8db406d62.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/25956811/235290161-34ab41ce-896d-4fc0-9686-0623a42067b3.png">

My plugin is a normal markdown plugin which relies `env.path`.
```typescript
export const loadContainerPlugin = (md: MarkdownIt) => {
  md.use(markdownItContainer, 'demo', {
    validate(params) {
      return !!params.trim().match(/^demo/)
    },

    render(tokens: Token[], idx, _, env) {
      // It will breaks when working with localSearchPlugin.ts
      console.log(env.path)
    }
  })
}
```

### Reproduction

none

### Expected behavior

`localSearchPlugin` should keep the same logic as `markdownToVue` when use `md.render()`

### System Info

```sh
none
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Feel free to create a PR.

**Comment by theniceangel** [comment]
> Feel free to create a PR.

See this [PR](https://github.com/vuejs/vitepress/pull/2322)
