### ISSUE TITLE
Syntax highlighting not working for Vue interpolated code blocks

### ISSUE THREAD

**Issue by ericfennis** [vuejs/vitepress#2315]
### Describe the bug

We wrote a markdown code group to dynamically generate code for each framework. Unfortunately, the syntax highlighting is not working when using Vue interpolated code blocks, which is known and mentioned in the [docs](https://vitepress.dev/guide/using-vue#unescape-in-code-blocks).

### Reproduction

Create an array or object with code examples to fill each code block

The markdown: 
``````md
<script setup>
const codeExample = {..}
</script>

::: code-group

```html-vue [HTML]
{{codeExample.html.code}}
```

```jsx-vue [React]
{{codeExample.react.code}}
```

```vue-vue [Vue]
{{codeExample.vue.code}}
```

```svelte-vue [Svelte]
{{codeExample.svelte.code}}
```

```jsx-vue [Preact]
{{codeExample.preact.code}}
```

```jsx-vue [Solid]
{{codeExample.solid.code}}
```

```tsx-vue [Angular]
{{codeExample.angular.code}}
```

```html-vue [Font]
{{codeExample.font.code}}
```

```html-vue [Flutter]
{{codeExample.flutter.code}}
```
:::
``````

Visual Result
<img width="891" alt="image" src="https://user-images.githubusercontent.com/11825403/235295993-01f1f136-8e17-4971-a616-da41bd38b860.png">

### Expected behavior

Expected result:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/11825403/235296568-f15c0e82-ad10-41d4-9215-68ce2e514423.png">

### System Info

```sh
System:
    OS: macOS 13.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 784.03 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.4
  npmPackages:
    vitepress: 1.0.0-alpha.73 => 1.0.0-alpha.73
```

### Additional context

In the documentation, this is mentioned: "Note that this might prevent certain tokens from being syntax highlighted properly."
Source: https://vitepress.dev/guide/using-vue#unescape-in-code-blocks
But none of the code blocks are syntax highlighted.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What's the issue here? Syntax highlighting won't work with interpolated code. It's mentioned in the docs.

**Comment by ericfennis** [comment]
@brc-dd yeah I know. But doesn't mean it's not expected behavior

**Comment by ericfennis** [comment]
I see you labeled the issue as unfixed. But can you maybe explain why it's not possible. Are there technical limitations why syntax highlighting is broken when using Vue interpolation? Or did you only labeled it as unfixed because it is written in de docs that it is not working?

**Comment by LinusBorg** [comment]
1. Reporting a bug for a known and documented beahvior will result in the report being closed, because there is no bug. If anything, this should have been a feature request.
2. It's not going to be fixed because markdown conversion to HTML (and code-blocks as part of that) happens before the result is being evaluated as a Vue component template (at which point interpolation would happen). So syntax highlighting happens before interpolation, and that is kind of an architectural foundation that we cannot re-work easily.

**Comment by ericfennis** [comment]
@LinusBorg yeah maybe it should be feature request then. Sorry for that.

Thanks for the explanation. I understand now what the problem is. 

Do you maybe know a workaround? How I can dynamically render code-snippets with syntax highlighting.

**Comment by brc-dd** [comment]
You can try creating a component that takes the code as text and highlights + renders it as code block 👀

**Comment by ericfennis** [comment]
@brc-dd hmm that maybe will work. But will increase bundle size ofc. Will think of this. Thanks!

**Comment by brc-dd** [comment]
Yeah it will add around 100-200kB to the bundle size. How are you getting that `codeExample` object? If that has no client-side dependency, you can use [data loading](https://vitepress.dev/guide/data-loading) to render the code directly in the server and pass it as string to the md file and use it with `v-html`.

**Comment by ericfennis** [comment]
Yeah we using the dat loading feature with Parma as well. Using v-html also good option. Maybe I can use the internal code highlighter from vitepress to do this. Do you think it will be hard to get the tabs/codegroups working as well?

**Comment by brc-dd** [comment]
You just need to generate the same html as we generate, rest is handled automatically. (No need of custom css or scripts for interactivity.)
