### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Hollelihanqi** [vuejs/vitepress#2337]
### Describe the bug

run vitepress build error:
> docs@1.0.0 docs:build E:\yto-engine\docs
> vitepress build

  vitepress v1.0.0-alpha.74

⠴ building client + server bundles...
(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ building client + server bundles...
build error:
TypeError: Cannot assign to read only property '__esModule' of object '#<Object>'
    at file:///E:/yto-engine/docs/.vitepress/.temp/plugin-vue_export-helper.b00f2ce5.js:7100:20
    at Array.forEach (<anonymous>)
    at file:///E:/yto-engine/docs/.vitepress/.temp/plugin-vue_export-helper.b00f2ce5.js:7098:29
    at requireVue_cjs_prod (file:///E:/yto-engine/docs/.vitepress/.temp/plugin-vue_export-helper.b00f2ce5.js:7102:5)
    at file:///E:/yto-engine/docs/.vitepress/.temp/plugin-vue_export-helper.b00f2ce5.js:7179:22
    at file:///E:/yto-engine/docs/.vitepress/.temp/plugin-vue_export-helper.b00f2ce5.js:7183:3
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async build (file:///E:/yto-engine/node_modules/.pnpm/vitepress@1.0.0-alpha.74/node_modules/vitepress/dist/node/serve-c662a607.js:41704:24)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

git-clone：https://github.com/Hollelihanqi/ui.git
step1:
pnpm install
step2:
pnpm docs:build

### Expected behavior

virepress build success

### System Info

```sh
nodejs 16.15.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yangzongliu** [comment]
这不是已经告诉你怎么做了吗
