### ISSUE TITLE
http / ws codeblocks

### ISSUE THREAD

**Issue by JK-Effects** [vuejs/vitepress#2338]
### Is your feature request related to a problem? Please describe.

I am currently writing an API documentation and miss a function to specify http(s) requests and websocket/socket.io connections with all their parameters and responses.

### Describe the solution you'd like

Document API with following features:
a) http(s) requests
Display the request method and the request URL. (GET, POST, DELETE... and other methods.) It should also be possible to specify the header and body of the request with a description and the types of the parameters. Furthermore, a display for possible returns should be included which displays the response status and the send json/text/number... .
(In short: specification of the request method to an API URL with the necessary parameters and the return).

b) websocket / socket.io
A specification of websockets contains namespaces with connection options and events. The individual events should be listed separately. These are listed with the parameters their types and descriptions. In addition, expected return events or no return are specified. Events that the server can send at any time should also be listed separately.
(In short: specification of the connection url with accessable namespaces with their connect-options and a list with all events which the client and the server can send).

For both extensions, it is best to have a kind of container that directly specifies the function (GET,POST, WS...) and the URL in the header and displays the parameters and the responses when expanded.
It should also be possible to copy the URL directly by clicking on it.
It would also be great to extend the copy functionality in such a way that the parameters can be copied formatted in the programming language used (JS, C, Rust...). If the programmer wishes, he can also specify an implementation of the entire function (also in different languages).

Optionally, an integration for a direct test request via the documentation can also be built in. This would also require input fields for an API key or Auth token and the required parameters.

### Describe alternatives you've considered

So far I have used containers to specify the URL in the head and the content in the expandable body.
I have also used the code blocks without format.

### Additional context

All links below show possible designs and functions as described above.

https://petstore.swagger.io/#/pet/
https://redocly.github.io/redoc/#tag/pet
https://developers.write.as/docs/api/#introduction
https://apidocjs.com/example/
https://stoplight.io/demo
https://readme.com/

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This can easily be accomplished by a custom component. ([Can be registered globally too.](https://vitepress.dev/guide/extending-default-theme#registering-global-components))

The team won't be working on this, but feel free to open a PR if you come up with a good design.

**Comment by alexandrehtrb** [comment]
I was thinking about this too.
There is a very good plug-in for Docusaurus ([Docusaurus OpenApi Docs](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs)) that generates documentation from a Swagger file.

We could make a similar plug-in, but for Vitepress... I think it is not too difficult.
Is there a plug-in tutorial for Vitepress? (I am not a JavaScript developer)
