### ISSUE TITLE
Config 'base' option works on dev, but doesn't quite work on build

### ISSUE THREAD

**Issue by VividLemon** [vuejs/vitepress#2339]
### Describe the bug

If you configure the base config property, it somewhat works on dev. The way it appears to work is that it navigates to the requested page, but proceeds to redirect you to the true page directly after. 

If this is how it works on dev, it isn't really a foolproof solution. 

The issue mainly is that on a built copy, this method doesn't work at all. Even if you have a base config property, it doesn't redirect you. 

Keep in mind that I'm using these links in _layout.vue_ which may be different in an md file. 

### Reproduction

Create an app, 
configure the base
Go to layout
Create some links, say, to /about
Try to navigate on dev, seemingly goes to /about then redirects to /${base}/about
- works
Build the project
Preview
Try to navigate to /about
- does not work -> goes directly to /about and not /`${base}/about

### Expected behavior

It would be nice if Vitepress was smart enough to compile all the links with the base property. Like I've said, it seems that the method is redirection, but perhaps I'm confused. 

### System Info

```sh
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 7.46 GB / 15.53 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - /run/user/1000/fnm_multishells/11424_1683296095333/bin/node
    npm: 9.5.1 - /run/user/1000/fnm_multishells/11424_1683296095333/bin/npm
  Browsers:
    Firefox: 112.0.2
  npmPackages:
    vitepress: 1.0.0-alpha.75 => 1.0.0-alpha.75
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We don't parse links in vue files. In markdown files it should've worked fine IMO. In vue code, you need to do something like this manually:

```vue
<script setup>
import { withBase } from 'vitepress'
</script>

<template>
  <a :href="withBase('/about')">About</a>
</template>
```

**Comment by brc-dd** [comment]
> Is this utility located anywhere in the docs besides the api reference?

Nope, just here: https://vitepress.dev/reference/runtime-api#withbase

**Comment by VividLemon** [comment]
Actually that place has a link to https://vitepress.dev/guide/asset-handling#base-url which has the information. My b

**Comment by mtermoul** [comment]
If you want the `base` path to work on your build, change the build command on your `package.json` to 

```
"scripts": {
   "build": "vitepress build --base=/bar/"
}
```

it is documented here https://vitepress.dev/reference/cli#vitepress-build

**Comment by VividLemon** [comment]
Sorry, this issue has already been addressed. `withBase` fixed the issue.
