### ISSUE TITLE
Footer copyright, message in build not support element like div and p

### ISSUE THREAD

**Issue by engvuchen** [vuejs/vitepress#2340]
### Is your feature request related to a problem? Please describe.

Footer copyright, message in build not support element like div and p

### Describe the solution you'd like

Add such information to the documentation (docs/reference/default-theme-footer.md) :

```
::: warning
Only inline elements can be used in message, copyright, because their rendering results are P elements.
:::
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's already supported. How are you using it?

**Comment by brc-dd** [comment]
> Footer copyright, message in build not support element like div and p

You can use [`layout-bottom`](https://vitepress.dev/guide/extending-default-theme#layout-slots) slot if you want more customization.

**Comment by engvuchen** [comment]
use this config:
```
footer: {
      copyright: [ `<div>Copyright ©2023-present MyName</div>`, ],
}
```

1. `vitepress dev docs`, it is ok
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/31369318/236473381-5896bf04-f00a-4c22-9135-70e1941187a6.png">

2. `vitepress preview docs `, an error has occurred, and copyright disappear
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/31369318/236473838-0b0c71c3-3694-48f8-af71-f13bb9ca1959.png">

**Comment by brc-dd** [comment]
Yeah I had misread that. Already removed that label.

**Comment by engvuchen** [comment]
> 

Only want to be able to simple settings, at the bottom of the page to add record information.
Filing information is a special setting on a Chinese web page.
like https://github.com/vuejs/vitepress/issues/815

**Comment by engvuchen** [comment]
> Yeah I had misread that. Already removed that label.

The footer's behavior is inconsistent in the Dev, Product environment. Will changes be considered?
