### ISSUE TITLE
url become case sensitive after build

### ISSUE THREAD

**Issue by gyhyfj** [vuejs/vitepress#2343]
### Describe the bug

url become case sensitive after build, the wrong case will lead to 404

### Reproduction

Just create a md file like `Hello.md`, and set path as `path/to/hello` in `.vitepress/config.ts`，
then I can access this page by `path/to/hello` when run `docs:dev`
but after build, this url is 404 page, even if I try `path/to/Hello`.
Only if I modify `path/to/hello` to `path/to/Hello` in `.vitepress/config.ts`, this url can work again after build

### Expected behavior

Expect case unsensitive after build

### System Info

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 9.27 GB / 15.92 GB
  Binaries:
    Node: 18.16.0 - D:\Program Files\NodeJS\node.EXE
    npm: 9.6.4 - D:\Program Files\NodeJS\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: latest => 1.0.0-alpha.75
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This actually depends on how you're serving your site. Like if you open https://vitepress.dev/GUIDE/GETTING-STARTED, it would work fine too -- Netlify handles the redirection. Similarly if you locally use `npx serve docs/.vitepress/dist/`, it would work fine. Polka/Sirv seems to have some issues though, but it shouldn't interfere with how you're deploying your site.
