### ISSUE TITLE
Question: Exclude from Local Search and display Frontmatter data

### ISSUE THREAD

**Issue by mitchellknight** [vuejs/vitepress#2344]
The new Local Search is great! I just have a few questions:

1. How do I exclude results from Local Search? For example, let's say I had a `/secret/` folder that I would like to exclude all subpages from search results, how would I do that?
2. How do I get Local Search to use [frontmatter data](https://vitepress.dev/guide/frontmatter#accessing-frontmatter-data) (see screenshot)?

![Frontmatter](https://user-images.githubusercontent.com/1848796/236547876-610465f3-3624-4887-938e-f8779086d058.png)

**Comment by jeremyriverain** [comment]
Hi,

I am currently migrating a doc website from Vuepress to Vitepress. I would like to exclude certain content from the search results but I can't find a way to do it with Vitepress. This ticket seems to indicate that it could be an improvement to Vitepress. Is this a possible development?

I have time to work on this subject. I can contribute.

Is there a particular direction you would like to take on this subject? Which API expose?

I imagine 2 ways to exclude content from search results.

1. from the `.vitepress/config.ts` file, by adding a new parameter, like `isSearchable`:

```typescript
// .vitepress/config
export default defineConfig({
  themeConfig: {
    search: {
      provider: 'local',
      options: {
        isSearchable (pageData) {
          return !pageData.startsWith('/excluded-folder')
        },
      },
    },
})
```

2. at the level of each page, by taking into account a new frontmatter property:

```markdown
---
search: false
---

<!-- excluded-folder/index.md -->
# my content excluded from search results
```


What do you think ?

**Comment by brc-dd** [comment]
Yeah contributions are welcome. Make the API something like this instead:

```ts
interface LocalSearchOptions {
  ignore: string[] | RegExp | (pageData: PageData) => boolean
}
```
