### ISSUE TITLE
热更新

### ISSUE THREAD

**Issue by peiyanlu** [vuejs/vitepress#2349]
### Describe the bug

指定端口号后热更新失效，恢复默认之后热更新依旧不生效

### Reproduction

vitepress dev docs --host --port 9999

### Expected behavior

热更新生效

### System Info

```sh
System:                                                       
    OS: Windows 10 10.0.19044                                   
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 44.27 GB / 63.71 GB                                 
  Binaries:                                                     
    Node: 14.18.2 - C:\Program Files\nodejs\node.EXE            
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD    
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD              
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-alpha.75 => 1.0.0-alpha.75
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
你好，有复现的仓库吗

**Comment by peiyanlu** [comment]
你好，我又重新验证了一下，我清除缓存之后重新安装vitepress没有复现这个问题，如果后续再复现这个问题我再提供

**Comment by zonemeen** [comment]
好嘞，麻烦您把issue关一下，后边还有问题的话可以重开下issue，谢谢啦😀

**Comment by peiyanlu** [comment]
未复现
