### ISSUE TITLE
Extending the vitepress theme

### ISSUE THREAD

**Issue by ghost** [vuejs/vitepress#235]
I'd like to only have a custom NavLinks component while keeping the default vitepress theme.  Next I looked at the NavBar although also my version doesn't override.  Any help in the right direction would be great.

docs/.vitepress/config.js

```
import Theme from 'vitepress/theme'
import '../../assets/vars.css'
import NavBar from './Mynav.vue'

const MyTheme = {...Theme, Layout: {...Theme.Layout, NavBar}}

export default {
    ...MyTheme,
    NotFound: () => 'custom 404',
    enhanceApp({app, router, siteData}) {

    },
}
```

**Comment by agritheory** [comment]
Maybe this will help?
https://github.com/vuejs/vitepress/issues/157

**Comment by ahawkclint** [comment]
The default theme is brilliant however I don't want to clone the entire theme into my working dir.  I'm not sure how to extend simply the menu as I'd like to keep upstream changes without effort.  

I moved on to creating my own theme however would love information on how to extend the default.

**Comment by sadeghbarati** [comment]
I follow the documentation for customizing the `default theme` Vue components but it's **_not working_**

.
├─ docs
│  ├─ .vitepress
│  │  ├─ theme
│  │  │  └─ index.js
│  │  └─ config.js
│  └─ index.md
└─ package.json

for example, I want to customize default `LastUpdated.vue`

so in the `theme` directory create another directory called `components` just like `vitepress/dist/client/theme-default/`


```js
import DefaultTheme from 'vitepress/theme'
import LastUpdated from './components/LastUpdated.vue'

export default {
    ...DefaultTheme,
    LastUpdated,
    NotFound: () => 'custom 404',
    enhanceApp({ app, router, siteData }) {
        // app is the Vue 3 app instance from `createApp()`. router is VitePress'
        // custom router. `siteData`` is a `ref`` of current site-level metadata.
    }
}
```

**Comment by soulsam480** [comment]
Hii, @sadeghbarati I think it'll work if you register the component properly
```js
import DefaultTheme from 'vitepress/theme'
import LastUpdated from './components/LastUpdated.vue'

export default {
    ...DefaultTheme,
    NotFound: () => 'custom 404',
    enhanceApp({ app, router, siteData }) {
    app.component('last-updated',LastUpdated)
        // app is the Vue 3 app instance from `createApp()`. router is VitePress'
        // custom router. `siteData`` is a `ref`` of current site-level metadata.
    }
}
```

**Comment by titouanmathis** [comment]
Registering the component globally did not work for me, but defining aliases in `vite.config.js` did: 

```js
const { defineConfig } = require('vite');
const path = require('path');

module.exports = defineConfig({
  resolve: {
    alias: {
      // Use my custom `NavBarTitle` component
      './NavBarTitle.vue': path.resolve(__dirname, '.vitepress/theme/components/NavBarTitle.vue'),
    },
  },
});
```

**Comment by emersonbottero** [comment]
This should be added to the interface of vitepress config so we can replace each default theme component.. 
this  way we can replace a specific component and an plugin that adds darktheme can replace only the navbars component and a search  plugin could change only the algolia component and so on..
multiple themes could be added chained and it would work as intended.

**Comment by userquin** [comment]
@brc-dd vía vite plugin
https://github.com/antfu/vite-plugin-pwa/blob/main/docs/plugins/navbar.ts

**Comment by brc-dd** [comment]
Let's just document the alias method. I don't think there is any other way to properly replace the theme components. Just a pro tip here, use regex in the aliases, it will make the alias work regardless of how the component is internally imported.
