### ISSUE TITLE
After build, the src of img tag as 'file://home/user/xxx/.vitepress/.temp/xxx.png'

### ISSUE THREAD

**Issue by lk101** [vuejs/vitepress#2357]
### Describe the bug

I use some image in vue component, by using
```js
new URL('@theme/public/my-image.jpg', import.meta.url).href
```
it works while `dev`, but not work while `preview` (after `build`), in the html file, it looks like this, 
```html
<img src="file://home/user/project/.vitepress/.temp/public/my-image.jpg" />
```
rather than
```html
<img src="/assets/my-image.47d9f72.jpg" />
```

Is there some configurations or processing to resolve this problem?

### Reproduction

none.

### Expected behavior

build successfully

### System Info

```sh
OS: Windows 10/Ubuntu 20.04
VitePress: 1.0.0-alpha75
Vue: 3.2.47
element-plus: 2.3.4
pnpm: 8.5.0
nodejs: 18.16.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by lk101** [comment]
my repo: https://gitee.com/liu-kai-101/lincoler.git

boundless gratitude

**Comment by brc-dd** [comment]
That repository link is not accessible. Also, why are you doing this? Why not simply import it or keep it in `project/public`?

**Comment by lk101** [comment]
> That repository link is not accessible. Also, why are you doing this? Why not simply import it or keep it in `project/public`?

Sorry, the repo is private, I will fix it later.

Because I use the `carousel` and `card` component in `element-plus` to show those images, and I want to reuse my vue component, so I use the href as props for my vue component.
Maybe you are right, I'll try your suggesstions.

Thanks.
