### ISSUE TITLE
When the page is refreshed, the scroll bar cannot retain the scroll position according to the hash

### ISSUE THREAD

**Issue by trry-github** [vuejs/vitepress#2361]
### Describe the bug

vitepress: 1.0.0-alpha.75
使用了默认主题，自己修改了样式，页面滚动时，url中没有hash,刷新页面时也不能保留滚动位置，求解决

### Reproduction

使用了默认主题，自己修改了样式，页面滚动时，url中没有hash,刷新页面时也不能保留滚动位置，求解决

### Expected behavior

使用了默认主题，自己修改了样式，页面滚动时，url中没有hash,刷新页面时也不能保留滚动位置，求解决

### System Info

```sh
System:
    OS: Windows 10 10.0.25346
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12450H
    Memory: 1.55 GB / 15.71 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.25346.1001.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.25346.1001
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
Could you provide a full reproduction☺️

**Comment by trry-github** [comment]
> Could you provide a full reproduction☺️

https://github.com/trry-github/trry-github

**Comment by zonemeen** [comment]
https://github.com/trry-github/trry-github/blob/e053be96652f4125d2b7a35cc99ba2cacba184e4/.vitepress/theme/index.ts#L24-L36

It seems to be a problem here, you try to switch to a synchronous way to register global components.

```ts
enhanceApp({ app }: { app: App }) {

    app.use(ElementPlus)

    // 自动导入 components 下的所有组件
    const modules = import.meta.glob('./components/*.vue')

    for (let key of Object.keys(modules)) {
      const name = key.split('/').pop()?.split('.')[0] as string
      const componentModule = modules[key]() as { default: Component }
      app.component(name, componentModule.default || componentModule)
    }
}
```
