### ISSUE TITLE
navbar cannot cover content when visit directly on a built site which url is with hash

### ISSUE THREAD

**Issue by jellyfishgh** [vuejs/vitepress#2364]
### Describe the bug

1. open url with hash (eg: https://vitejs.dev/plugins/#community-plugins ) in browser;
2. navbar is transparent so we can see content behind the navbar;
![image](https://github.com/vuejs/vitepress/assets/3036042/638d0c6e-c292-4e5d-b4c3-95850260fbce)

### Reproduction

open https://vitejs.dev/plugins/#community-plugins in browser

### Expected behavior

navbar can cover content and we can not see content behind the navbar.

### System Info

```sh
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 255.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Safari: 16.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
It seems to happen only when there is no sidebar. Similar to the problem of https://github.com/vuejs/vitepress/issues/2442
