### ISSUE TITLE
Local assets included into Audio html element are not built

### ISSUE THREAD

**Issue by alkaitagi** [vuejs/vitepress#2372]
### Describe the bug

Placing raw HTML element `<audio control src="./sound.m4a"></audio>` does not carry the audio file into the build (but it works in `npm run dev`).

I've read @kiaking's reasoning in #607 about how we can't be sure if a string is a URL or some plain text, but I don't think I applies here. 

### Reproduction

1. Create a `.md` page with `<audio control src="./sound.m4a"></audio>` content.
2. Place an audio file names `sound.m4a` in the same directory.
3. Run `npm run dev`, confirm that the sound plays.
4. Run `npm run build && npm run preview`, the audio element can't find the file (there's no in `dist`).

### Expected behavior

The audio file should be included into the build, and the `src` attribute of the HTML element should point to it. 

### System Info

```sh
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 5.70 GB / 15.89 GB
  Binaries:
    Node: 18.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.74 => 1.0.0-alpha.75
```

### Additional context

I was writing a custom _markdown-it_ rendering function that does this conversion:
`![image](./audio.m4a)` → `<MyPlayer src="./cig.m4a"/>`
E.g. simply replaces any image with URL leading to an audio file with my VUE component. I've immediately run into the problem of the specified file being absent from the build (while it works in `npm run dev`).

Then I've found #607 and understood why this happens, but also I agree that storing all assets in `public` is rather inconvenient. So I've tried mitigating that with at least including the audio files via native html tags, which didn't work too.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
m4a is not in the default list of known asset extensions. Use this:

```ts
// .vitepress/config.ts

export defineConfig({
  vite: {
    assetsInclude: ['**/*.m4a']
  }
})
```

**Comment by brc-dd** [comment]
Use it like this for now:

```html
<audio controls>
  <source src="./sound.m4a" type="audio/mp4">
</audio>
```

You'll also need to add something like this in your config:

```ts
// .vitpress/config.ts
import { defineConfig } from 'vitepress'

export default defineConfig({
  vite: {
    assetsInclude: ['**/*.m4a']
  }
})
```
