### ISSUE TITLE
Vitepress build Problem

### ISSUE THREAD

**Issue by chenweigh** [vuejs/vitepress#2385]
### dependencies

`pnpm add @chenwei02/qy-element`
> `@chenwei02/qy-element` has svg-icon component. svg files builded by vite-plugin-svg-icons.

### docs
`vitepress dev docs`  is ok
`vitepress build docs`  then deploy to gh-pages,  *.svg icon was blank.

### Problem
vitepress build docs . something is wrong.

### Help
I need help

### Reproduction

pnpm add @chenwei02/qy-element

*.md
<qy-icon name="close">

vitepress build docs.

### Expected behavior

every thing is ok.

### System Info

```sh
vitepress : 1.0.0-alpha.64
@chenwei02/qy-element: 1.0.2-p1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you share some demo code using https://vitepress.new? Does running `vitepress build docs && vitepress preview docs` work fine locally?
