### ISSUE TITLE
callback of theme change ?

### ISSUE THREAD

**Issue by sufuwang** [vuejs/vitepress#2387]
### Is your feature request related to a problem? Please describe.

i am using component library in VitePress project,  i want to change dark mode of component library when mode of VitePress have changed

### Describe the solution you'd like

Can you provide a `onChange` callback of mode button

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
isDark is exposed through useData, you can register a watcher for it. Something like this should do the job:

```ts
import { useData } from 'vitepress'
import { watchEffect } from 'vue'

const { isDark } = useData()

watchEffect(() => {
  console.log(isDark.value)
})
```

**Comment by sufuwang** [comment]
@brc-dd thank your answer, but `useData` only use in `setup` , i want to use it in entry of project, when web page is open

**Comment by brc-dd** [comment]
> i want to use it in entry of project, when web page is open

I don't think I completely understand this. You can have the`<script setup>` block in your custom theme, it will be executed when someone opens your page. How were you expecting to consume the `onChange` event outside script blocks?

> Do VitePress have life cycle function callback

This too I don't understand properly. We have build hooks, vite plugin hooks, and vue lifecycle hooks if that's what you meant.

**Comment by sufuwang** [comment]
>  i want to use it in entry of project, when web page is open

if every page use component,  and `useData` must use in `setup`, it mean that i must listener `isDark` in erery `markdown` file, i want to listener once only

**Comment by brc-dd** [comment]
> do VitePress have a file like App.vue of Vue Project, i can listener isDark in the file

Yeah you can create one. That's what I meant when I wrote "You can have the `<script setup>` block in your custom theme".

Create a file like this:

```ts
// .vitepress/theme/index.js
import DefaultTheme from 'vitepress/theme'
import Layout from './Layout.vue'

export default {
  ...DefaultTheme,
  Layout
}
```

```vue
<!--.vitepress/theme/Layout.vue-->
<script setup>
import DefaultTheme from 'vitepress/theme'

// put your code here ....
</script>

<template>
  <DefaultTheme.Layout />
</template>
```

**Comment by sufuwang** [comment]
@brc-dd  

thank you, It is perfect
