### ISSUE TITLE
Whether to remove redundant dependencies

### ISSUE THREAD

**Issue by zonemeen** [vuejs/vitepress#2397]
I scanned the repository and there are two dependencies that are redundant, can they be removed?

1. enquirer
2. supports-color

**Comment by brc-dd** [comment]
`supports-color` is needed by [`debug`](https://github.com/debug-js/debug#nodejs)

`enquirer` is being used by `lint-staged > listr2`. Probably can be removed (it was being used in the release scripts earlier IG).
