### ISSUE TITLE
Having a link and second header in index.md breaks `vitepress build`

### ISSUE THREAD

**Issue by larionov** [vuejs/vitepress#24]
**Describe the bug**

Hello, Evan! I'm very excited about this project, was playing around with it, trying to see if our existing vuepress content will work here. Discovered, that having this in `index.md` breaks static build:
```md
# Vitepress build bug

 test: [VuePress](https://vuepress.vuejs.org/)

## Second header
```

`vitepress build` result does not display rendered page and shows hydration error in console:

![2020-06-11_18-46](https://user-images.githubusercontent.com/174250/84381991-1a5f5480-ac14-11ea-950d-c95afd611249.png)

Removing the link or the second header makes build working again

Also displays warnings while building:

**To Reproduce**
1. Build https://github.com/larionov/vitepress-build-bug
```sh
git clone git@github.com:larionov/vitepress-build-bug.git
cd vitepress-build-bug/
npm install
npm run build
npx serve .vitepress/dist
```
2. Open http://localhost:5000/ in browser.

**Expected behavior**
I expect to see the contents of index.md on the main page, and no errors in console

**System Info**
- vitepress version :v0.3.1
- vite version: v0.20.7
- Node version: v12.16.1
- OS version: Linux 5.6.15-arch1-1

**Comment by marina-mosti** [comment]
Interestingly this seems like a package issue, it works for me with node 12.18 when using `yarn`, but not when using `npm`

**Comment by larionov** [comment]
Just tried on the vitepress from master branch and the error doesn't happen there. No warning, no hydrarion failures. I guess it's either fixed there already or npm link makes some difference.

**Comment by larionov** [comment]
Doesn't reproduce in v0.4.0, now I see #28
