### ISSUE TITLE
pnpm not working when running 

### ISSUE THREAD

**Issue by ooomi** [vuejs/vitepress#2401]
### Describe the bug

fail when initializinfg: ```pnpm exec vitepress dev docs``` pnpm exec vitepress dev docs

### Reproduction

run ```pnpm exec vitepress dev docs``` on Apple M1.

### Expected behavior

Docs are added.

### System Info

```sh
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 80.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.13.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 110.0
    Safari: 16.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Please provide reproduction code please 😳

**Comment by dragos199993** [comment]
Can confirm that on M1 using pnpm I had the same issue. Ended up using npx.
On my side I get
```
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: vitepress init
spawn vitepress ENOENT
```

I checked and pnpm is installed correctly (being using it for a while)

**Comment by brc-dd** [comment]
@dragos199993 Based on those logs it appears you haven't installed VitePress?

1. Run `pnpm add -D vitepress`
2. Run `pnpm vitepress init`

Alternatively, directly run `pnpm dlx vitepress init`

**Comment by brc-dd** [comment]
Not seeing anyone else experiencing these issues. Also, what's the error that you get? And installing vitepress globally is not a good idea. It might cause conflicts later.
