### ISSUE TITLE
Configuring vitepress from vite, not the other way around

### ISSUE THREAD

**Issue by hybridherbst** [vuejs/vitepress#2405]
### Is your feature request related to a problem? Please describe.

The docs are a bit lacking in that regard: if I want to add vitepress to an existing project to leverage the templating/routing capabilities, can I do that? 

[This note](https://vitepress.dev/reference/site-config#vite-vue-markdown-config) isn't very helpful to see if the other way around is possible too: 
> You can configure the underlying Vite instance using the [vite](https://vitepress.dev/reference/site-config#vite) option in your VitePress config. No need to create a separate Vite config file.

From what I currently understand, given an existing vite+vue project with multiple routes that I want to use SSG with, I need to 
- delete the existing vite config
- move everything from there into the vitepress config
- use my existing page as a custom theme
- start implementing actual vitepress stuff

Is that correct? Am I missing something?

### Describe the solution you'd like

Improved docs covering the migration case of "I want to move my vue+vite project to vitepress so I can leverage SSG".

### Additional context

The Vue.js docs mention in multiple places that Vitepress would be the right place to look at for SSG, however the migration path isn't clear.
Example: https://vuejs.org/guide/extras/ways-of-using-vue.html#jamstack-ssg

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Regarding second point:

```ts
export default async () => defineConfig({
  // ...
})
```

**Comment by brc-dd** [comment]
> Improved docs covering the migration case of "I want to move my vue+vite project to vitepress so I can leverage SSG".

Don't. Use some vite plugin like https://github.com/antfu/vite-ssg Although vitepress has many other features too, but I don't think just for SSG you need to switch to another framework.

Currently, we are not planning to go the other way around. Implementing vitepress as a vite plugin would be nice, but isn't that easy.

**Comment by hybridherbst** [comment]
> I don't think just for SSG you need to switch to another framework
Vue + vite doesn't have that out of the box as far as I'm aware, so I do think I'd switch anyways (to vuepress or vitepress), right? That's why I think migration steps would be nice to have somewhere.

**Comment by brc-dd** [comment]
> Vue + vite doesn't have that out of the box as far as I'm aware

vite doesn't have, but vite-ssg is just a wrapper over vite, you just need 2-3 line changes to generate static vue site from that. migrating a vue app to vitepress isn't straightforward enough to be documented.
