### ISSUE TITLE
链接点不了了，新版

### ISSUE THREAD

**Issue by adoin** [vuejs/vitepress#2408]
### Describe the bug

点了没反应

### Reproduction

？

### Expected behavior

跳转啊

### System Info

```sh
win10
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by adoin** [comment]
三个li 元素，第一个是链接，被后面的俩遮挡了，设置z-index或者隐藏那俩即可

**Comment by HaifeiGeng** [comment]
我也遇到这个问题了  能详细说下应该怎么设置吗

**Comment by adoin** [comment]
我是用css临时修复的，浏览器有设置全局css，在文件上定位链接，父容器同级的俩li隐藏就能用了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月24日(周三) 晚上9:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vuejs/vitepress] 链接点不了了，新版 (Issue #2408)

**Comment by adoin** [comment]
> 你好，能提供一下复现的stackblitz链接或者是github仓库吗

浏览器插件的。。。而且插件报错了，貌似说修复了
