### ISSUE TITLE
Charts & Diagrams

### ISSUE THREAD

**Issue by titouandk** [vuejs/vitepress#2409]
### Is your feature request related to a problem? Please describe.

It would be nice to be able to generate charts & diagrams using markdown code blocks.

Maybe something like this (for a [Mermaid](https://mermaid.live/) sequence diagram):

````markdown
```mermaidSequenceDiagram format:svg theme:auto
sequenceDiagram
    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!
```
````

Render (would render 2 images, dark and light, and display one or the other depending on the theme) :

![mermaid-diagram-2023-05-25-001842](https://github.com/vuejs/vitepress/assets/5413308/f52e6510-8bbe-427b-84cd-0291c3d19f53)

### Describe the solution you'd like

Maybe a system of plugins of some sort to be able to handle chart & diagrams source codes.

**Sequence Diagram**

````markdown
```mermaidSequenceDiagram format:svg theme:auto
sequenceDiagram
    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!
```
````

**Gant Diagram**

````markdown
```mermaidGanttDiagram format:png theme:dark
gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 20d
    section Another
    Task in sec      :2014-01-12  , 12d
    another task      : 24d
```
````

**Etc...**

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by alexandrehtrb** [comment]
There is a Vitepress Mermaid Plug-in:

https://github.com/emersonbottero/vitepress-plugin-mermaid

**Comment by titouandk** [comment]
Thanks @alexandrehtrb, I am going to test this 👍
