### ISSUE TITLE
setting base path will make the sidebar blank

### ISSUE THREAD

**Issue by Assone** [vuejs/vitepress#242]
**Describe the bug**
setting base path will make the sidebar blank.

**To Reproduce**
in .vitepress/config.js:
add base path setting

**Expected behavior**
normal display

**System Info**
- vitepress version: 0.12.0
- vite version: 2.0.0-beta.50
- Node version: v15.2.1
- OS version: macOS 11.2

**Additional context**
you can see there: https://assone.github.io/Note/programing/

**Comment by TheDutchCoder** [comment]
This was fixed in 0.12.2
