### ISSUE TITLE
Different behaviour between `vite build` and `vitepress build` in same project

### ISSUE THREAD

**Issue by hybridherbst** [vuejs/vitepress#2421]
### Describe the bug

It's unclear to me how these two differ, my understanding was that vitepress also calls vite build under the hood.

However, I have a scenario where running `npm run docs:build` (`"docs:build": "vitepress build`) results in

```
✓ building client + server bundles...
build error:
file:///D:/git/some/path/docs/.vitepress/.temp/app.js:10
import { v5 } from "uuid";
         ^^
SyntaxError: Named export 'v5' not found. The requested module 'uuid' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'uuid';
const { v5 } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

while running `npm run build` (`"build": "vite build"`) works perfectly fine.

These both use the same vite config (once in `vite.config.js` and once in the `vite:` property in vitepress' `config.js`, the latter with the `vite.config.js` deleted).

The module uuid (9.0.0) is not a CommonJS module, and building without vitepress works fine, so it looks like however `vitepress build` starts the build detects that incorrectly?
package.json of the uuid package: https://github.com/uuidjs/uuid/blob/4de23a6030e65ac72b3b015680f08e7e292681ed/package.json#L25

To be honest I'm not sure if this is a vitepress bug or even lower-level, at this point I'm mostly looking for guidance as to what vitepress build does different to vite build that could result in such differences.

Thanks!

### Reproduction

https://stackblitz.com/edit/vite-qpoze8?file=package.json

Run `npm run docs:build` if it doesn't run automatically.

package.json of the `postprocessing` package used for repro purposes here:
https://github.com/pmndrs/postprocessing/blob/3e6ea9d8fddd2ca2d269e2182752f8199b8248af/package.json#L11

### Expected behavior

Either
- Builds both work
or
- can understand the difference between the two better from the docs so I can resolve the issue myself

### System Info

```sh
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 31.89 GB / 63.85 GB
  Binaries:
    Node: 18.13.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.2 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 113.0.5672.127
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-beta.1 => 1.0.0-beta.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by hybridherbst** [comment]
After digging a bit deeper it looks like vitepress doesn't respect this type of info in package.json:
```js
	"main": "dist/bundler.cjs",
	"module": "dist/bundler.mjs",
```
while vite does (using the correct code, CommonJS or ES6 module, depending on environment).

Changing the above in all affected package.jsons inside `node_modules` to
```js
	"exports": {
		".": {
		  "require": "./dist/bundler.cjs",
		  "import": "./dist/bundler.mjs"
		}
	},
```
"fixes" the issue, but I can't really do that to external dependencies.

Would be great if this could be fixed!

**Comment by Cat1007** [comment]
same issue

**Comment by brc-dd** [comment]
Force it's transpilation:

```ts
 vite: {
    ssr: {
      noExternal: ['postprocessing'],
    },
  },
```
