### ISSUE TITLE
No inclusion of assets in frontmatter of markdown file and js config

### ISSUE THREAD

**Issue by EthanAndreas** [vuejs/vitepress#2422]
### Describe the bug

When you define a link to an image in frontmatter or in config.js, the file is note copy in the dist folder, whereas for a link in the markdown file directly it works, also when you define a public folder with your pictures it copy the content of the folder directly in dist folder and not in a public folder in dist folder.  

### Reproduction

at this in a makdown file that represents the home page :
features:
  - icon: 
      src: /public/compiler.png
create a public folder in docs with the image

and build the project

### Expected behavior

it will be preferable if the content of public folder will be copy in a dist/public folder, because here you can just enter :
features:
  - icon: 
      src: compiler.png

but it is not very clear

### System Info

```sh
npm run docs:build
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by dotob** [comment]
same here...

**Comment by hybridherbst** [comment]
Related
- #2419

**Comment by brc-dd** [comment]
> also when you define a public folder with your pictures it copy the content of the folder directly in dist folder and not in a public folder in dist folder.

this is expected - https://vitejs.dev/guide/assets.html#the-public-directory

and content in frontmatter is considered string, that doesn't go through rollup. hence relative paths won't work there.
