### ISSUE TITLE
I try to render React component from library with @vitejs/plugin-vue-jsx and failed. But i render simple div works :(

### ISSUE THREAD

**Issue by francmarin98** [vuejs/vitepress#2427]
### Describe the bug

Step 1

```vue
<script lang="jsx">
import { CustomLink } from 'my-lib/dist/customLink';
import { defineComponent } from "vue";
export default defineComponent({
  render() {
    return (
    <CustomLink />
    );
  },
});

</script>
```

Step 2

Page md
```
<Test />
<script setup>
  import Test from '../components/Test.vue'
</script>

````

Result
![image](https://github.com/vuejs/vitepress/assets/50973629/135367df-1b46-4822-86a8-9a099f9318a1)

But

I change for example

```vue

<script lang="jsx">
import { defineComponent } from "vue";
export default defineComponent({
  render() {
    return (
      <div>
        Hello World :defineConfig
        </div>
    );
  },
});

</script>

```

works
![image](https://github.com/vuejs/vitepress/assets/50973629/0af06542-32f4-4958-80f4-06884cf61147)

HELP PLEASE

### Reproduction

no

### Expected behavior

I would expect the component to be seen

### System Info

```sh
$ npx envinfo --system --npmPackages vitepress --binaries --browsers
npx: installed 1 in 2.22s

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   
    Memory: 5.52 GB / 15.82 GB
  Binaries:
    Node: 14.19.0 - D:\nodejs\node.EXE
    Yarn: 1.22.17 - D:\nodejs\yarn.CMD
    npm: 6.14.16 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-beta.1 => 1.0.0-beta.1
```

### Additional context

I want to document my component library in react with vitepress; It might sound crazy but I had a leap of faith says Toretto hehe

Vite config
```ts
import { defineConfig } from "vite";
import vueJsx from "@vitejs/plugin-vue-jsx";
export default defineConfig({
  plugins: [
    vueJsx(),
  ],
});

```

@antfu do you know jeje?

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need `@vitejs/plugin-react` for this not `@vitejs/plugin-vue-jsx`

Refer this: https://github.com/vuejs/vitepress/discussions/2183#discussioncomment-5531222

**Comment by francmarin98** [comment]
@brc-dd Sorry for the next question but in case I wanted to encapsulate the css of the external lib without it "fighting" with the base theme of vitepress where could I configure that? I'm currently documenting a component lib but when I import the base styles from it they overwrite the ones from vitepress :(.

I want to insert a playground type so that it can see the component and not affect the rest, but I can't find any. I mean, I could add stackbliz or codesanbox but this component lib is private.

**Comment by brc-dd** [comment]
add `vp-raw` class to your wrapper and use the postcss configuration mentioned here: https://vitepress.dev/guide/markdown#raw

**Comment by francmarin98** [comment]
![chrome_hM8BoJKcPw](https://github.com/vuejs/vitepress/assets/50973629/0788274a-10c5-425f-881a-72faea215bdc)

In short, it will be time to use storybook :(. I tried that but I had results, I don't know if I'm the problem hehe or vitepress but I already gave up. I also tried using https://whyframe.dev/docs/integrations/ vitepress but despite the fact that it creates the iframe it does not give me that encapsulation that I am looking for.

**Comment by francmarin98** [comment]
https://github.com/bluwy/whyframe/issues/23 any ideas?
