### ISSUE TITLE
Local Search Error

### ISSUE THREAD

**Issue by francmarin98** [vuejs/vitepress#2435]
### Describe the bug

when configuring the search engine as the documentation mentions https://vitepress.dev/reference/default-theme-search#local-search, the app breaks:

![image](https://github.com/vuejs/vitepress/assets/50973629/4d3a5289-1ba6-4a07-a3d4-8e2449983676)

![image](https://github.com/vuejs/vitepress/assets/50973629/c66da1d2-f0be-4955-829f-07c3b47f705d)

### Reproduction

:)

### Expected behavior

![image](https://github.com/vuejs/vitepress/assets/50973629/e13140ca-275a-4539-a2e4-b2f4d2ec8aec)

### System Info

```sh
$ npx envinfo --system --npmPackages vitepress --binaries --browsers
npx: installed 1 in 2.16s

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 4.40 GB / 15.82 GB
  Binaries:
    Node: 14.19.0 - D:\nodejs\node.EXE
    Yarn: 1.22.17 - D:\nodejs\yarn.CMD
    npm: 6.14.16 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: latest => 1.0.0-beta.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Update your node version?

**Comment by francmarin98** [comment]
16?

i use 14

![image](https://github.com/vuejs/vitepress/assets/50973629/cbd986b2-5441-4e56-953c-7e606457dd77)

**Comment by brc-dd** [comment]
14 is EOL

**Comment by francmarin98** [comment]
Works fine, thank you much
