### ISSUE TITLE
打包报错Unexpected token '.' 问题

### ISSUE THREAD

**Issue by 21236774** [vuejs/vitepress#2439]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/58690897/9f2c8fc4-6084-404f-9f62-a2eaf0517460)

打包报错css问题，css没有任何问题，theme里全局引入组件库的，版本"vitepress": "1.0.0-beta.1"

### Reproduction

v "vitepress": "1.0.0-beta.1"

### Expected behavior

正常打包

### System Info

```sh
npm run build
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by 21236774** [comment]
打包命令写错了，正常npm run docs:build 报错那个问题

**Comment by zonemeen** [comment]
你好，我试了一下是没问题的，你的电脑操作系统以及node版本是什么呢？

**Comment by 21236774** [comment]
![image](https://github.com/vuejs/vitepress/assets/58690897/25b8e968-00e8-489b-9f61-fd4b7dcd50e3)
我创建了一个新项目，vitepress版本最新版，全局引入这个包，打包还是报这个错误，麻烦帮忙看下，node版本v16.17.0 Windows系统

**Comment by 21236774** [comment]
是的，xdd-ui那个，我又新建了一个初始项目，全局引入这个组件库，打包还是报错一样的问题。这个UI库我在后台管理系统引入不会打包不会报错的

**Comment by zonemeen** [comment]
复现不出来😅你重新装个最新稳定版的node再试试看吧

**Comment by 21236774** [comment]
我重新装了一个node和在同事那边试了build也是报错的，帮看看这个最基础的项目，您那边是否正常https://github.com/21236774/vitepress-starter/tree/master   我这边这个项目打包是报错的，一样只引入了一个UI库

**Comment by zonemeen** [comment]
你的 `theme/index.js` 应该要这么写，不然会引起ssr的问题的：

```js
import DefaultTheme from 'vitepress/theme'
export default {
  ...DefaultTheme,
  async enhanceApp ({ app }) {
    if (!import.meta.env.SSR) {
      const plugin = await import('easyest')
      app.use(plugin.default)
    }
  },
}
```

具体为什么要这样配置，你可以看看文档里的链接：https://vitepress.dev/guide/ssr-compat

还有你的示例markdown里的写法要改成这样：

```md
<ClientOnly>
    <xdd-button>默认按钮</xdd-button>
    <xdd-button type="success">怎么说</xdd-button>
</ClientOnly>
```

不然渲染出来的顺序会乱的，具体原因可以看看vue关于ssr的说明：https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch

**Comment by zonemeen** [comment]
好嘞，我建议第一手资料尽量看英文的，还能学学英语😉
