### ISSUE TITLE
vitepress doesn't work with node_modules as symlink

### ISSUE THREAD

**Issue by DrakoPOD** [vuejs/vitepress#2443]
### Describe the bug

I have a my node_modules as symlink, for save space and prevent synch with the cloud storage. Vite has some problemens resolving path with symlink, because they actually outside of the root folder, so they aren't in the allow list. This can be solved with `server.fs.strict= false`. But in vitepress, doesn't exist `vite.config.js`, I already tried to put in `./vitepress/config.js` but still got the same error.

### Reproduction

1. create a "node_module" as symlink, the original folder must be outside of the root.
2. install the dependencies
3. run dev

### Expected behavior

dev should run normally.

### System Info

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
    Memory: 451.46 MB / 3.88 GB
  Binaries:
    Node: 18.12.1 - C:\ProgramData\Anaconda3\node.EXE
    npm: 9.2.0 - C:\ProgramData\Anaconda3\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-beta.1 => 1.0.0-beta.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
Could you provide a full reproduction since that I'm not quite sure what your intention is 🤔

**Comment by DrakoPOD** [comment]
I have my project folder in a GDrive folder, to prevent that `node_module` get sync, I create a symlink with power shell:

```powershell
New-Item -ItemType SymbolicLink -Path $(Join-Path "path/to/my/project" "/node_modules") -Target $(Join-Path "path/outside/of/GDrive" "/node_modules")
```

Vite prevents scripts that are outside the root directory to execute, so I got an error when run vite.

This can be solved with `server.fs.allow = false` in the `vite.config.js`. But in Vitepress this doesn't work.

**Comment by brc-dd** [comment]
>  I already tried to put in `./vitepress/config.js` but still got the same error.

How did you put that? Something like this should've worked:

```ts
import { defineConfig } from 'vitepress'

export default defineConfig({
  vite: {
    server: {
      fs: {
        strict: false
      }
    }
  },
}
```

Also, can you share what error are you getting? along with the stack trace?
