### ISSUE TITLE
plugin with syntax like $(1,3-5), will conflict with highlightLinePlugin

### ISSUE THREAD

**Issue by itcatplayit** [vuejs/vitepress#2450]
### Describe the bug

I write a plugin ([vitepress-markdown-it-repl](https://www.npmjs.com/package/vitepress-markdown-it-repl)) with syntax like `$(1,3-5)`, it will conflict with highlightLinePlugin.

### Reproduction

when markdown is:

    ```js{1-2,4} $(1,3-5)
    console.log("111")
    console.log("222")
    console.log("333")
    console.log("444")
    console.log("555")
    ```

highlightLinePlugin will use `1,3-5`, not `1-2,4`.

### Expected behavior

highlightLinePlugin use `1-2,4`, and other plugin like [vitepress-markdown-it-repl](https://www.npmjs.com/package/vitepress-markdown-it-repl) use `1,3-5`.

They both exist together.

### System Info

```sh
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 7.36 GB / 15.89 GB
  Binaries:
    Node: 16.15.1 - F:\nodejs\16.15.1\node.EXE
    Yarn: 1.22.19 - F:\nodejs\16.15.1\node_global_modules\yarn.CMD
    npm: 8.13.2 - F:\nodejs\16.15.1\node_global_modules\npm.CMD
  Browsers:
    Chrome: 113.0.5672.127
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This should be fixed at your plugin level. Make it extract the things according to your syntax and then modify token.info so that it contains stuff in vitepress recognizable format. For example in this case, token.info after your plugin has done processing should be `js{1-2,4}`. You basically need to create a fence rule that does that and then calls the original fence rule with new token data.
