### ISSUE TITLE
`createContentLoader` resolves urls from project root

### ISSUE THREAD

**Issue by shadow-light** [vuejs/vitepress#2462]
### Describe the bug

`createContentLoader` resolves urls from project root rather than source directory. This results in invalid urls that are relative to the project root, but should be relative to the source directory.

### Reproduction

https://stackblitz.com/edit/vite-vhsxi3?file=docs%2Fsrc%2Findex.md

### Expected behavior

Urls should be relative to the source directory.

### System Info

```sh
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vitepress: latest => 1.0.0-beta.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
I think it cannot be defined as a bug. You can configure it like this:

```js
import { createContentLoader } from 'vitepress';

export default createContentLoader('src/*.md', {
  transform(raw) {
    return raw.map(({ url }) => ({
      url: url.replace('/src/', ''),
    }));
  },
});
```
