### ISSUE TITLE
unable to bind a variable url to background-image

### ISSUE THREAD

**Issue by alephpi** [vuejs/vitepress#2472]
### Discussed in https://github.com/vuejs/vitepress/discussions/2471

<div type='discussions-op-text'>

<sup>Originally posted by **alephpi** June  3, 2023</sup>
I have a assets of images
```
.vitepress
|-theme
   |-assets
      |-wallpaper
         |-default.png
   |-components
      |-Home.vue
```
And in Home.vue, I want to bind a variable `bgImgUrl` to the `background-image`
where const bgImgUrl = \`url('../assets/wallpaper/${title}.png')\`
I tried `background-image: v-bind(bgImgUrl)`, but the image is not rendered.
However If I just use `background-image: url('../assets/wallpaper/default.png')`, this works, but it will not be variable.

I am really confused, by the way the inline binding doesn't work either.
**I think the problem lies the entanglement of three things: url(), v-bind() and the url resolution specificity of vitepress, and I really don't know how to deal with them.** </div>

**Comment by userquin** [comment]
have you tried to import the asset `import bgImgUrl from '../assets/wallpaper/default.png?url`? https://vitejs.dev/guide/assets.html#explicit-url-imports

**Comment by alephpi** [comment]
> have you tried to import the asset `import bgImgUrl from '../assets/wallpaper/default.png?url`? https://vitejs.dev/guide/assets.html#explicit-url-imports

No, but what I want is let `bgImgUrl` be a reactive variable (which can be modified), so that we can change the background image among multiple images in the wallpaper folder.

**Comment by alephpi** [comment]
direct assignment:
![image](https://github.com/vuejs/vitepress/assets/61275421/21853444-ff23-49b8-9844-e0caf93d90fd)

binding:
![image](https://github.com/vuejs/vitepress/assets/61275421/881da460-83fa-4713-8353-f1e54c966377)

seems that when binding it just cannot resolve the relative path

**Comment by alephpi** [comment]
current workaround: create static css rules for background-image, bind the css class to `title`. Seems the problem is the relative url resolution.

**Comment by brc-dd** [comment]
Dynamic variables won't work with imports/urls. Rollup needs to be able analyze them statically at build level to emit assets. It'd work if assets are in public directory.
