### ISSUE TITLE
[Feature] - Allow local styling of components

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vitepress#248]
**Is your feature request related to a problem? Please describe.**
Currently, importing Vue components (whether they are VitePress components, or components from a library for example) are influenced by VitePress's somewhat sub-optimal styles.

For example, all headings are styled, so as soon as a component uses an `h1`/`h2`/etc, it will inherit those styles, making VitePress virtually unusable for component libraries that ship their own CSS.

The only I can think of mitigating this, is to use a web component as a base for Vue components to be mounted in, as styles are local to web components if I remember correctly.

**Describe the solution you'd like**
Some way to render components with their own styles, and not inherit styles from the docs.

**Describe alternatives you've considered**
I tries unsetting all styles `* { all: unset; }` inside our demo component (the wrapper for all other components), but that also removes some of the Tailwind related styling unfortunately.

I couldn't get web components to work, as the vue plugin seems to be for Vue 2 (https://github.com/vuejs/vue-web-component-wrapper).

**Comment by kiaking** [comment]
Closing due to duplicate https://github.com/vuejs/vitepress/issues/199
