### ISSUE TITLE
Build fails with `Error: ENOTEMPTY: directory not empty, rmdir docs\.vitepress\.temp`

### ISSUE THREAD

**Issue by hybridherbst** [vuejs/vitepress#2482]
### Describe the bug

Related or identical to this locked issue:
- https://github.com/vuejs/vitepress/issues/1004

When running `npm run docs:build`, the build fails with the following error message:

```
✓ building client + server bundles...
build error:
Error: ENOTEMPTY: directory not empty, rmdir '\\?\D:\path\to\project\docs\.vitepress\.temp'
    at Object.rmdirSync (node:fs:1226:10)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmSync (node:fs:1275:10)
    at build (file:///D:/path/to/project/node_modules/vitepress/dist/node/serve-d5608de4.js:41814:12)
```

The directory is empty afterwards, and does not exist before running `npm run docs:build`.

### Reproduction

Happens consistently (100%) for some projects and never (0%) for other projects. Have not found a pattern or trivial reproduction yet.

### Expected behavior

Can either build or get an actionable error message

### System Info

```sh
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 40.60 GB / 63.85 GB
  Binaries:
    Node: 18.13.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.2 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.110
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-beta.1 => 1.0.0-beta.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by hybridherbst** [comment]
Looking at the code, it seems that the error comes from here:
![image](https://github.com/vuejs/vitepress/assets/2693840/2c96364c-1a0c-49a3-b3b4-21dd0c5b8ab6)

My understanding is that `{ recursive: true, force: true }` should ensure this _always_ works, but seems that is not the case.

**Comment by brc-dd** [comment]
Are you using a NAS?

**Comment by userquin** [comment]
@brc-dd me too, I have also done some tests in Vite repo

**Comment by hybridherbst** [comment]
No, this is just a regular SSD drive (NTFS).

**Comment by brc-dd** [comment]
Yeah, I had seen this with NAS earlier too. With normal SSD it looks like some permission issue to me. @hybridherbst Can you try moving the project to some other drive?

**Comment by hybridherbst** [comment]
I work regularly on this drive with nodejs and vue/vite projects, vitepress is the only tool making trouble there right now. This also happens consistently across several Windows machines.

Looking forward to the fix being rolled out! When is the next release planned?
