### ISSUE TITLE
Nav ahref with target="_self" breaks the url when the link points to the same website, but to a directory other than VitePress's

### ISSUE THREAD

**Issue by cedivad** [vuejs/vitepress#2487]
### Describe the bug

I have VitePress installed at /docs/ and I would like to have a clickable item pointing to /other-dir/ from the navigation menu (config.js -> themeConfig -> nav []). However, when setting `target: '_self'`, the a href stop working. I believe that the function catching those clicks is triggering but confused that:

- The url is on the same website
- It is outside of the urls VitePress knows about, so it thinks those don't exist

When changing the target url from website.com/other-dir/ to another-website.com, `target: '_self'` works just fine.

### Reproduction

Install VitePress in a subdirectory and try to reach outside of the install directory, but on the same domain, without using `_blank`.

### Expected behavior

`_self` shouldn't crash a href.

### System Info

```sh
Latest
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
As a workaround, consider adding `class="vp-raw"` to that link. That will bypass that click handler.

**Comment by Red-Asuka** [comment]
@brc-dd I tried using `class="vp-raw"`, which can indeed bypass click handler. However, in the production environment, this will load some non-existent JavaScript files. Is there any solution to this?

<img width="1321" alt="image" src="https://github.com/vuejs/vitepress/assets/38158783/9c694901-b256-4734-a1fd-7562e37bb895">
