### ISSUE TITLE
Allow Third-party Themes To Use Local Search

### ISSUE THREAD

**Issue by davidhemphill** [vuejs/vitepress#2490]
### Is your feature request related to a problem? Please describe.

I'm developing an open-source documentation theme and wish to support searching locally, similar to the default theme. After searching the Vitepress source, it seems like third-party themes cannot use this built-in functionality, and we would need to reimplement the feature. 

I could be wrong, and there may be a straightforward way to use it, but if so, there's no documentation for third-party themes, and I wasn't able to find any third-party themes implementing it.

### Describe the solution you'd like

I want to be able to utilize the built-in search functionality.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Ah, there isn't a straightforward way to do that. The [vite plugin](https://github.com/vuejs/vitepress/blob/main/src/node/plugins/localSearchPlugin.ts) is already there, so you won't need to rewrite that, but you'll need to write the component similar to this: https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPLocalSearchBox.vue

To be able to reuse the vite plugin, you must have `themeConfig.search.provider === 'local'`. (i.e. in your theme too, you'll need to have same [config interface for search](https://github.com/vuejs/vitepress/blob/main/types/default-theme.d.ts#L344-L388)).

That component might look big to you, but if you don't want that much features, it's pretty straightforward. What it does is import `@localSearchIndex` and passes that to `MiniSearch.loadJSON` to get the search index. Then getting the search results from index is as simple as `index.search(textToSearch)`. How you render those results is totally up to you. Complexity of your component will increase as you add more features and work on optimizing performance.

**Comment by davidhemphill** [comment]
@brc-dd Yeah, I was able to adapt the local search component to my theme. Thanks :-)
