### ISSUE TITLE
How to use the plug-in like vuepress?

### ISSUE THREAD

**Issue by shelley-xl** [vuejs/vitepress#2491]

**Comment by chgeo** [comment]
@shelley-xl please add a description that elaborates your question.

**Comment by taozuhong** [comment]
How to upgrade the VuePress v1 site to VitePress? it contains many plug-ins, these plug-ins could work continuously?

**Comment by xxholly32** [comment]
vitepress uses themes instead of plug-in mode. If you still want to use plug-ins, try [vuepress-next](https://github.com/vuepress/vuepress-next)

**Comment by brc-dd** [comment]
VuePress-like plugin system won't be supported. You can use vite plugins + theme-level enhancements.
