### ISSUE TITLE
Not able to use Badge Component

### ISSUE THREAD

**Issue by emanuelenardi** [vuejs/vitepress#2493]
### Discussed in https://github.com/vuejs/vitepress/discussions/2062

<div type='discussions-op-text'>

<sup>Originally posted by **PrajjwalArora08** March  9, 2023</sup>
Is there any specific configuration that required to use badge?
I just created a fresh project and was trying badge component but it showing error in console.

```
runtime-core.esm-bundler.js:40 [Vue warn]: Failed to resolve component: Badge
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
at <TextBadge.md>
at <VitePressContent class="vp-doc _text-badge" >
at <VPDoc key=3 >
at <VPContent>
at <Layout> 
at <Layout> 
at <VitePressApp>
```

**Comment by emanuelenardi** [comment]
I have the same exact problem, the `Badge` component is not rendered on the page.

**Comment by brc-dd** [comment]
Please share a minimal reproducible example.

**Comment by emanuelenardi** [comment]
To replicate the problem, you can follow the following procedure in a newly created folder.

```
npm i -D vitepress
npm i -D vue
npx vitepress init
```
![image](https://github.com/vuejs/vitepress/assets/15109661/b90f85f1-30b2-4838-a2d2-cee42747c406)
```
Use TypeScript for config and theme files? Yes
Add VitePress npm scripts to package.json? Yes 
```
Then paste inside a markdown file the example provided [on the reference](https://vitepress.dev/reference/default-theme-badge).
```
### Title <Badge type="info" text="default" />
### Title <Badge type="tip" text="^1.9.0" />
### Title <Badge type="warning" text="beta" />
### Title <Badge type="danger" text="caution" />
```
Now run
```
npm run docs:dev
```
Now you should see that the badge component it's not rendered, and inspecting the html I notice that:

![image](https://github.com/vuejs/vitepress/assets/15109661/7bd8ec80-a5d5-400d-80b8-f389cff6cdd5)

> Please note that if you delete the folder `docs\.vitepress\theme` everything works fine.
---

Meanwhile, if you follow the same procedure, but instead of "_Default Theme + Customization_", you choose "_Default Theme (Out of the box, good-looking docs)_" everything works as expected.

![image](https://github.com/vuejs/vitepress/assets/15109661/a6aeb29d-0d98-41b2-acc6-4f01794124b4)

![image](https://github.com/vuejs/vitepress/assets/15109661/343e8aa1-bdeb-415a-ab2a-83cec600cb03)
