### ISSUE TITLE
--vp-layout-max-width bigger than 1440px breaks layout

### ISSUE THREAD

**Issue by deenns** [vuejs/vitepress#2505]
### Describe the bug

By default, `--vp-layout-max-width` is equal to 1440px. The same value is used in the media queries. If the `--vp-layout-max-width` is bigger than 1440px, then the layout breaks when the window width is less than the new `--vp-layout-max-width`, but bigger than 1440px. 

### Reproduction

To reproduce from scratch:

1. Create a new vitepress project. Choose the "Default Theme + Customization" option.
2. Add
    ```css
    :root {
      --vp-layout-max-width: 1800px;
    }
    ```
    to the `style.css` file.   
3. Run in dev, open the `markdown-examples.html` page and make the window width equal to 1550px.

Alternatively, you can clone this repo https://github.com/deenns/vitepress-bugs, run the dev script, open `markdown-examples.html` page and make the window width equal to 1550px. You will see the following: 

![image](https://github.com/vuejs/vitepress/assets/96049300/4510c87e-7ae6-4ccf-8676-6cafea24e8b3)

The sidebar width is less than needed.

### Expected behavior

The sidebar width should not be less than required. 

### System Info

```sh
"vitepress": "^1.0.0-beta.2"
```
```


### Additional context

_No response_

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Actually `min-width: 1440px` related `@media` rules need to be updated for this to work and CSS doesn't allow using variables there. You can write a postcss or vite plugin to transform this:

```ts
// .vitepress/config.ts

export default defineConfig({
  vite: {
    plugins: [
      {
        name: 'increase-width',
        transform(code, id) {
          if (/\.css($|\?)/.test(id)) {
            return code.replace(/1440px/g, '1800px')
          }
        }
      }
    ]
  }
})
```
