### ISSUE TITLE
Markdown after custom element with codepen script is duplicated in production

### ISSUE THREAD

**Issue by deenns** [vuejs/vitepress#2506]
### Describe the bug

If I insert a codepen demo into a markdown page, everything works as expected during development. But in prod (or in preview) all the content after a custom Vue element (that adds a script tag to the page) is duplicated. 

### Reproduction

All the changes that are needed to reproduce the bug in a new project are in this commit:
https://github.com/deenns/vitepress-bugs/commit/687c84c424b7159271a82a856af3ddd24b3e9e63

1. Clone the repo https://github.com/deenns/vitepress-bugs
2. Run 
    ```
    npm i
    npm run docs:build
    npm run docs:preview
    ```
3. Open the `/markdown-examples.html` page. There is a codepen demo, and everything is ok.
4. Click on the "Runtime API Examples" in the sidebar, and then click on the "Markdown Examples" to return back.
5. Now all the content after the codepen demo is rendered twice. 

A workaround: 

If you move the `<ScriptElement />` to the end of the markdown file, the problem will disappear. 

### Expected behavior

It must not duplicate the content after the script element. It works correctly in dev. 

### System Info

```sh
"vitepress": "^1.0.0-beta.2"
```
```


### Additional context

_No response_

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
Hi @deenns , your custom component should be written like this:

```vue
<template>
  <ClientOnly>
    <div ref="container">
      Here is a custom element with a script
    </div>
  </ClientOnly>
</template>
```

or 

```ts
enhanceApp({ app, router, siteData }) {
    if (!import.meta.env.SSR) {
      app.component('ScriptElement', ScriptElement)
    }
}
```

The reasons for this are similar to those described in this link https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch

The solution is mentioned in this link https://vitepress.dev/guide/ssr-compat#clientonly
