### ISSUE TITLE
I want to add a icon to the sidebar,like this picuture,how should I do ?

### ISSUE THREAD

**Issue by imbyter** [vuejs/vitepress#2511]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/vuejs/vitepress/assets/53294133/37e99106-9a8f-4774-a347-7d2b741ad26b)

### Describe the solution you'd like

1

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Just add that svg in your sitebar config. It accepts html.
