### ISSUE TITLE
Searchbox blinking on firtst usage

### ISSUE THREAD

**Issue by Elringus** [vuejs/vitepress#2513]
### Describe the bug

When clicking the searchbox (or pressing ctrl+k) for the first time after the page loaded, it disappears for about 500ms.

https://github.com/vuejs/vitepress/assets/2056864/a3bfc3de-219e-4329-824d-965d7cfa3bf1

### Reproduction

1. Open https://vitepress.dev
2. Click the searchbox or press ctrl+k
3. Notice the box is hidden for about 500ms before the search overlay is loaded

### Expected behavior

The searchbox doesn't disappear.

### System Info

```sh
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz
    Memory: 49.17 GB / 63.92 GB
  Binaries:
    Node: 18.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.134
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.43)
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Elringus** [comment]
@brc-dd Hey, Do I get it right that you don't qualify this as a bug? If not, why?

![img](https://github.com/vuejs/vitepress/assets/2056864/7e27adff-34f1-42f0-9026-2c34ad3ddaa8)

**Comment by brc-dd** [comment]
It is sort of expected behavior because that Algolia chunk is loaded dynamically on demand to reduce the initial load times. That element is then swapped by the docsearch not us. That swap is appearing as the blink to you. But the blink is usually in sub seconds, and is very fast (~10ms) once that chunk is cached by the browser. We can try to figure out some way to avoid the element removal till the new one is mounted, but that might be bit of overengineering.

**Comment by Elringus** [comment]
Well, that doesn't happen on other sites, that use algolia, so it should be something vite or vitepress-specific. Users of my docs clearly identify this is a bug/glitch and I agree with them. Is there a way to make vite/vitepress preload the chunk, so that at least it doesn't disappear for that long on the initial load?

**Comment by Elringus** [comment]
Thank you!
