### ISSUE TITLE
Separate directory for each locale without server tweaks

### ISSUE THREAD

**Issue by CanadianBeaver** [vuejs/vitepress#2514]
### Is your feature request related to a problem? Please describe.

Can you please implement it, f.e. for github, gitlab, etc...
https://vitepress.dev/guide/i18n#separate-directory-for-each-locale

### Describe the solution you'd like

> However, VitePress **will** redirect `/` to `/en/` by default.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Redirects need to be handled at the server level. It will vary from server to server. Refer your hosting provider's documentation on how to configure redirects.
