### ISSUE TITLE
Calling a sidebar function within the json array of another one

### ISSUE THREAD

**Issue by pberto** [vuejs/vitepress#2518]
### Describe the bug

I am trying to call a sidebar function from within another sidebar:

```
function sidebarA() {
  return [
    {
      text: 'A',
      collapsed: false,
      items: [
        { text: '1', link: '/1' },
        { text: '2', link: '/2' },
        { text: '3', link: '/3' },
       ]
     }
  ]
}
```  

```
function sidebarB() {
  return [
    {
      text: 'B',
      collapsed: false,
      items: [
        sidebarA(),
        { text: '4, link: '/4' },
        { text: '5', link: '/5' },
        { text: '6', link: '/6' },
       ]
     }
  ]
}
```

But I cannot see the links 1 2 3 in the sidebar B when rendering (and there is no error).

What's odd is that if I copy and paste the returned content of sidebarA in place of the function call it works (as it should because is just text with no function calls).

Is this supposed to work at all?

### Reproduction

See description.

### Expected behavior

I would expect the function call to return but maybe this is not possible within the json array.

### System Info

```sh
Mac, beta2.
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It should be `...sidebarA(),`

**Comment by brc-dd** [comment]
It should be `...sidebarA(),`
