### ISSUE TITLE
Base paths (and links) not generating correctly for nested pages.

### ISSUE THREAD

**Issue by songololo** [vuejs/vitepress#252]
**Describe the bug**

See https://github.com/songololo/vitepress-debug for reproduction of this issue:

Run a dev server: `yarn docs:dev`.

Note that the base-path `/my-base-path/` is set in the config at `.vitepress/config.js`.

The base path works for root files, i.e. `index.md` is served from `/my-base-path/`.

However, the base path is missing for nested files, i.e. `content/index.md` is served from `/content/` and `content/hello.md` is served from `/content/hello.html`.

This doesn't break things in development mode because the links are also missing the base path.

However, it breaks things in production because the links are missing the base path.

**System Info**
- vitepress 0.12.2
- vite/2.0.4
- darwin-x64
- node-v15.8.0

This happens for both my local system and for a github actions build.

**Comment by songololo** [comment]
PS - this may be a links issue, for example:
- When following the link `/content/` path from the home page, it will send to (and serve from) `/content/`
- But if you try to go to `/content/` manually, then it will give a warning: `The server is configured with a public base URL of /my-base-path/ - did you mean to visit /my-base-path/content/ instead?`
- Manually inserting `/my-base-path/` into the link works as intended, for example a link to `/my-base-path/content/` will send to (and serve from) `/my-base-path/content/`.

I'm assuming that the intended behaviour is that links described without `/my-base-path/` should automatically include the base path when resolving?

For now I'm inserting the base path into all links as a workaround.

**Comment by Alsmile** [comment]
+1

The server is configured with a public base URL：/my-base-path/
Markdown link: [a](/a) 
I want to visit [hostname]/my-base-path/a, not [hostname]/a

**Comment by Alsmile** [comment]
> +1
> 
> The server is configured with a public base URL：/my-base-path/ Markdown link: `[a](/a) ` I want to visit [hostname]/my-base-path/a, not [hostname]/a

It can be solved as follow:
[bar - three](../bar/three)
