### ISSUE TITLE
Navbar active highlighting

### ISSUE THREAD

**Issue by JK-Effects** [vuejs/vitepress#2520]
### Describe the bug

The navbar of vitepress highlights multiple links when parts of the active match are the same.
See highlighted part below in the reproduction code.

![image](https://github.com/vuejs/vitepress/assets/79076586/f1628c6f-3e9e-4343-b3ba-070e97b1c0bb)

### Reproduction

nav: [
  { text: "Contest Manager", link: "/Contest_Manager/", activeMatch: "**/Contest_Manager/**" },
  { text: "Modules", link: "/Modules/", activeMatch: "/Modules/" },
  { text: "Plugins", link: "/Plugins/", activeMatch: "/Plugins/" },
  { text: "Changelog", link: "**/changelog/Contest_Manager/**", activeMatch: "/changelog/" },
]

Parts of the highlighted link and activeMatch strings are the same, which causes the highlighting of multiple links in the navbar.

### Expected behavior

The highlighting in the Navbar should not highlight multiple tabs if parts of the activeMatch are the same.

### System Info

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 5.57 GB / 15.68 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.1 - ~\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.51)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-beta.2 => 1.0.0-beta.2
```

### Additional context

If the activeMatch checks the current link from the beginning and not if it is in the link, this would solve the problem.
For those who want to highlight a deeper nested link by writing only parts of it to activeMatch, they would have to write the whole link to activeMatch.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> If the activeMatch checks the current link from the beginning and not if it is in the link, this would solve the problem.

It's regex string. Use `'^/Contest_Manager/'` and `'^/changelog/'` as the activeMatch for that behavior.

**Comment by JK-Effects** [comment]
Thanks for the feedback.
I didn't know that activeMatch uses a regex.
That's settled then.
