### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by PShiYou** [vuejs/vitepress#2521]
### Is your feature request related to a problem? Please describe.

Hello, I have a suggestion,
Add a column in the countdown to the end of the day to show the monthly salary,
Is it one day off or two days off on the weekend.
![Snipaste_2023-06-19_10-31-54](https://github.com/vuejs/vitepress/assets/118948488/2dc81108-c791-4a8b-91d0-7d004ce98496)

### Describe the solution you'd like

suggestion

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What does it has to do with VitePress?

**Comment by PShiYou** [comment]
Sorry, I can't find a place to give advice.
