### ISSUE TITLE
`Public folder` outside of `.vitepress` or `docs`

### ISSUE THREAD

**Issue by CanadianBeaver** [vuejs/vitepress#2526]
### Is your feature request related to a problem? Please describe.

Please add on option where the public folder can be specified in build settings: https://vitepress.dev/reference/site-config#build
The public folder can be outside of `.vitepress` or `docs`

### Describe the solution you'd like

Also, please add an option, that public folder can be specified in one, two or more instances and the output has to be combined in result. F.e.: project can have different folders: /imagesfromJohn, /simpleimages, /mybestimages/forsite

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Adding support for multiple public directories won't be possible as vite doesn't support that. You'll need to write a custom vite plugin to handle that.
