### ISSUE TITLE
defineModel is not defined

### ISSUE THREAD

**Issue by Tyh2001** [vuejs/vitepress#2531]
### Describe the bug

vue3 use `defineModel` err

```ts
const modelValue = defineModel<string | number>({ required: true, default: '' })
```

### Reproduction

https://github.com/FightingDesign/fighting-design

```shell
pnpm i

pnpm dev:docs
```

### Expected behavior

Can be used normally

### System Info

```sh
windows11

"vue": "^3.3.4"
"vitepress": "1.0.0-beta.3"
"vite": "^4.3.9"
"vitest": "^0.32.2"
"vue-tsc": "^1.8.0"
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It is opt-in. Add this to your .vitepress/config:

```ts
import { defineConfig } from 'vitepress';

export default defineConfig({
  vue: {
    script: {
      defineModel: true,
    },
  },
});
```
