### ISSUE TITLE
Page redirection

### ISSUE THREAD

**Issue by f33r0** [vuejs/vitepress#2534]
### Is your feature request related to a problem? Please describe.

I need to move the user from the page sitename.com/foo/bar to sitename.com/bar, while there can be several pages in foo and I would not like to declare each one manually

### Describe the solution you'd like

Transparent and understandable settings for redirecting from page to page. And the documentation for it.

### Additional context

P.S. I looked at the documentation, but did not see what I need, if it is already there, please point it out to me.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
These need to be done at the server level. Refer your hosting provider's documentation to do that.
