### ISSUE TITLE
Remove index.html in content loader generated urls

### ISSUE THREAD

**Issue by SimonBerens** [vuejs/vitepress#2541]
### Is your feature request related to a problem? Please describe.

When clicking links to `index.md` files [generated](https://github.com/vuejs/vitepress/blob/c4909e4298ec706cf1762cb36af03e5fd3637ccc/src/node/contentLoader.ts#L116-L121) by the `createContentLoader` function, the url will flash because the link generated includes the `/index.html`, but then vue removes it on pageload.

### Describe the solution you'd like

The url created by `createContentLoader` should have `/index.html` suffixes removed from it.

### Describe alternatives you've considered

You can manually remove the `index.html` using the `transform` function provided by `createContentLoader`

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by huluobotx** [comment]
I use it like this: 
export default createContentLoader(relativePath + '/!(index).md', {
  excerpt: true,  
  transform(rawData) {
    return rawData.sort((a, b) => {
      return a.frontmatter.sort - b.frontmatter.sort
    })
  }
})

**Comment by huluobotx** [comment]
I use it like this:
`export default createContentLoader(relativePath + '/!(index).md', {
  excerpt: true,  
  transform(rawData) {
    return rawData.sort((a, b) => {
      return a.frontmatter.sort - b.frontmatter.sort
    })
  }
})`

**Comment by SimonBerens** [comment]
> I use it like this: `export default createContentLoader(relativePath + '/!(index).md', {`

In my case I want the content loader to include `index.md` files but generate non index.html routes.

My directory looks something like this
```
blog/
-- post1/
---- index.md
-- post2/
---- index.md
```
