### ISSUE TITLE
Support nested includes

### ISSUE THREAD

**Issue by Jeff-Tian** [vuejs/vitepress#2544]
### Is your feature request related to a problem? Please describe.

Is nested includes supported?

For example, in the following file structure:

```
| main.md
|-- Chapter1
|----|
|----|-- index.md
|----|-- section1.md 
```

- In `main.md`, included `Chapter1/index.md`.
- In `Chapter1/index.md`, included `section1.md`.

The rendered `Chapter1/index` looks fine and included the `section` content.

However, in the `main`, the `section1`'s content are loss.

By looking the code here: https://github.com/vuejs/vitepress/blob/b2a129f49b8c83e528f594af977b1e901a57313e/src/node/markdownToVue.ts#L99C62-L99C62 , the raw content of `Chapter1/index` are read into `main`.

### Describe the solution you'd like

What do you think if it's a good idea to read the cache during the `replace` function to get the replaced content instead of the raw content?

So that the `main` would also include the `section1`'s content.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Jeff-Tian** [comment]
I saw it mentioned the release notes of v1.0.0-beta.4, but I tried the nested inclusion is not working.

But I released the forked one and saw it's working. How is the release done? Need to check if there are some issues there.

---

To double check I released a `@jeff-tian/vitepress` and made sure the nested inclusion is working:

https://stackblitz.com/edit/vite-e7v8d1?file=docs%2Findex.md,docs%2Fmiddle.md,docs%2Fnested.md
<img width="1222" alt="image" src="https://github.com/vuejs/vitepress/assets/3367820/2bebd6cd-5a1a-48be-b995-2d591f7cf893">


But with latest `vitepress`, the nested inclusion is not working:

https://stackblitz.com/edit/vite-upxxuh?file=docs%2Fnested.md

<img width="1469" alt="image" src="https://github.com/vuejs/vitepress/assets/3367820/7b82f673-33ad-4b57-adca-9e4efcd53049">

**Comment by brc-dd** [comment]
Update the lockfile.

**Comment by Jeff-Tian** [comment]
Worked, 😂
