### ISSUE TITLE
Provide a way for extending themes to add layouts

### ISSUE THREAD

**Issue by aentwist** [vuejs/vitepress#2547]
### Is your feature request related to a problem? Please describe.

For my theme which extends the default theme, I want to have a contact page with a custom layout.

###### Users

```markdown
---
layout: contact
---

# Contact

content
```

###### Devs

Effectively add custom blocks here

https://github.com/vuejs/vitepress/blob/c30e758585ef512eef68b33918832d4413839e9c/src/client/theme-default/components/VPContent.vue#L29-L52

For example

```vue
<MyContact v-if="frontmatter.layout === 'contact'">
  <!-- define slots for this layout, if any -->
</MyContact>
```

---

This needs a lot of consideration, but I might propose something like

```typescript
import Contact from "./components/MyContact.vue";

export default <Theme>{
  // ...
  customLayouts: {
    contact: Contact,
  },
};
```

Then in VPContent,

```vue
<component v-else-if="customLayouts[frontmatter.layout]" :is="customLayouts[frontmatter.layout]"></component>
```

### Describe alternatives you've considered

- Override the VPContent component - very fragile coupling
- Use the page layout with a custom frontmatter key under which additional layouts can be specified - cannot control `Content`, workaround hack

###### Users

```markdown
---
layout: page
type: contact
---

# Contact

content
```

###### Devs

*MyLayout.vue*

```vue
<template>
  <Layout>
    <template v-if="frontmatter.type === 'about'" #page-top>
      about page top
    </template>
    <template v-if="frontmatter.type === 'about'" #page-bottom>
      about page bottom
    </template>

    <template v-if="frontmatter.type === 'contact'" #page-top>
      contact page top
    </template>
    <template v-if="frontmatter.type === 'contact'" #page-bottom>
      contact page bottom
    </template>
  </Layout>
</template>
```

```
An element cannot have multiple '<template>' elements which are distributed to the same slot.eslint[vue/valid-v-slot](https://eslint.vuejs.org/rules/valid-v-slot.html)
```

OR

```vue
<template>
  <Layout>
    <template #page-top>
      <template v-if="frontmatter.type === 'about'">
        about page top
      </template>
      <template v-if="frontmatter.type === 'contact'">
        contact page top
      </template>
    </template>

    <template #page-bottom>
      <template v-if="frontmatter.type === 'about'">
        about page bottom
      </template>
      <template v-if="frontmatter.type === 'contact'">
        contact page bottom
      </template>
    </template>
  </Layout>
</template>
```

(Terrible maintainability)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by bojanrajh** [comment]
@brc-dd Could something like this work?

https://github.com/vuejs/vitepress/blob/c30e758585ef512eef68b33918832d4413839e9c/src/client/theme-default/components/VPContent.vue#L37

Change `<VPDoc v-else>` into `<component :is="frontmatter.layout || 'VPDoc'">`.
