### ISSUE TITLE
Override a component in the default theme / use a dup theme

### ISSUE THREAD

**Issue by pberto** [vuejs/vitepress#2548]
### Describe the bug

This is half an issue and half a question:

I am trying to override a due component in the default theme, say `VPTeamMembersItem.vue`, since I cant manage I am trying also to use a dup of the default_theme.

### Reproduction

- First I verified my edits in the same file inside node_modules and of course I get the expected results.
- Then I looked how I could override this, from the docs it appear I can use Vite aliases: https://vitepress.dev/guide/extending-default-theme#overriding-internal-components 
  - To do so I duplicate `VPTeamMembersItem.vue` and apply my changes and store a copy in `.vitepress/theme/components` and edit the config:
  
```  
  export default defineConfig({
  vite: {
    resolve: {
      alias: [
        {
          find: /^.*\/VPTeamMembersItem\.vue$/,
          replacement: fileURLToPath(
            new URL('./components/VPTeamMembersItem.vue', import.meta.url)
          )
        }
      ]
    },
```

- However as soon as I try the above I can see all the dependencies of `VPTeamMembersItem.vue` are not found, such as `VPLink` and recursively a lot of other files inside theme-default.

I expect them to be found just as they are found with the default theme but they are not so I believe I am doing something wrong. 

So I decided I should instead make a duplicate of the default theme by copy of the whole `node_modules/vitepress/dist/client/theme-default` in my project but I am unsure how I should import it.

Any pointer will help.

### Expected behavior

I would expect to be able to override a component without worrying of all its recursive imports falling back on default theme imports. 

I would like to know how I can duplicate entirely the default theme and use it in my project.

### System Info

```sh
macOS, beta 2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Liberty-liu** [comment]
I use it like this, don't know if it will work for you
```typescript
<script setup lang="ts">
import type { DefaultTheme } from 'vitepress/theme'
import VPLink from 'vitepress/dist/client/theme-default/components/VPLink.vue'
import VPSocialLinks from 'vitepress/dist/client/theme-default/components/VPSocialLinks.vue'
defineProps<{
  size?: 'small' | 'medium'
  member: DefaultTheme.TeamMember
}>()
</script>
```

**Comment by pberto** [comment]
@Liberty-liu thanks, using the full path works as expected!
