### ISSUE TITLE
MPA mode BUGS

### ISSUE THREAD

**Issue by imbyter** [vuejs/vitepress#2550]
### Describe the bug

when I use MPA mode, I can't switch the menu in release version

![image](https://github.com/vuejs/vitepress/assets/53294133/c1e1df19-d745-4ca7-b83f-4220c97c437f)

![bug](https://github.com/vuejs/vitepress/assets/53294133/d54d6af6-cae3-4769-a247-649fdc45ead4)

### Reproduction

Windows 10 
node -v      v18.16.1
npm -v      9.5.1

vitepress version : 1.0.0 beta.3

### Expected behavior

Windows 10 
node -v      v18.16.1
npm -v      9.5.1

vitepress version : 1.0.0 beta.3

### System Info

```sh
Windows 10 
node -v      v18.16.1
npm -v      9.5.1

vitepress version : 1.0.0 beta.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That's expected because there is no JS in MPA mode. The default theme won't work. Feel free to write a theme that does not require any JS.
