### ISSUE TITLE
自己定义的vue组件总是受到外层.vp-doc样式影响

### ISSUE THREAD

**Issue by coderhaoo** [vuejs/vitepress#2551]
### Is your feature request related to a problem? Please describe.

你好，我在md文件引入了自己的vue组件，但外层有一个.vp-doc元素自带的一堆样式总是会影响到自己开发的组件样式，这种情况该如果解决？

### Describe the solution you'd like

比如ezlist 引入了tabel，那就会受到.vp-doc的这行影响，从而改变布局
.vp-doc table {
    display: block;
    border-collapse: collapse;
    margin: 20px 0;
    overflow-x: auto;
}

# list.md 文件
<EzList></Ezlist>

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
add `vp-raw` class to your component (or its wrapper) and use the postcss setup given here in "Details": https://vitepress.dev/guide/markdown#raw
