### ISSUE TITLE
MPA MODE BUGS

### ISSUE THREAD

**Issue by imbyter** [vuejs/vitepress#2552]
### Describe the bug

1. When in MPA mode, Normal in development mode, no outline in production environment:

Local use: pnpm exec vitepress dev dist --mpa
![01](https://github.com/vuejs/vitepress/assets/53294133/1a26b43a-56ba-4072-99cd-3e00cac87808)

on linux server use : pnpm exec vitepress build dist --mpa
![2](https://github.com/vuejs/vitepress/assets/53294133/d2632247-0b01-4d8b-bbf0-06e53dbbc40f)

### Reproduction

windows 10

C:\Users\test\Desktop\tmp>node -v
v18.16.1

C:\Users\test\Desktop\tmp>npm -v
9.5.1

vitepress version: 1.0.0 beta.3

### Expected behavior

windows 10

C:\Users\test\Desktop\tmp>node -v
v18.16.1

C:\Users\test\Desktop\tmp>npm -v
9.5.1

vitepress version: 1.0.0 beta.3

### System Info

```sh
windows 10

C:\Users\test\Desktop\tmp>node -v
v18.16.1

C:\Users\test\Desktop\tmp>npm -v
9.5.1

vitepress version: 1.0.0 beta.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
same reason as #2550  that outline feature needs js
