### ISSUE TITLE
your site config lastupdated unuseful   -- cause .md document lastupdated time dont show

### ISSUE THREAD

**Issue by 123456-droid** [vuejs/vitepress#2553]
### Describe the bug

your site config lastupdated unuseful  

### Reproduction

 -- cause .md document lastupdated time dont show

### Expected behavior

lastupdated time should show normal

### System Info

```sh
vitepress window64 chrome92
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Commit your file.
