### ISSUE TITLE
页面与首页重合

### ISSUE THREAD

**Issue by Lxx-c** [vuejs/vitepress#2556]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/42939639/f8b6a389-2797-4a13-a73b-3d5945550a12)
复现方式，在服务器部署后，访问具体的某一个子菜单后，鼠标选中浏览器地址，按下enter键。就会导致如图效果，首页会和选中页面重合

### Reproduction

在服务器部署后，访问具体的某一个子菜单后，鼠标选中浏览器地址，按下enter键
例如 ：
我已经定位到这个具体的菜单  ： http://127.0.0.1:80/demo/specify01

当我在浏览器地址栏使用鼠标选中地址栏并且按下enter键的时候，就会出现上面的情况

### Expected behavior

我希望我在定位到具体的菜单后，在浏览器快速访问时，会帮我定位到具体的菜单，而不是和首页重合

### System Info

```sh
1.0.0-beta.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wforguo** [comment]
去掉config当中的cleanUrls: true,试试

```
cleanUrls: true,
```

**Comment by wforguo** [comment]
> 去掉config当中的cleanUrls: true,试试
> 
> ```
> cleanUrls: true,
> ```

https://vitepress.dev/reference/site-config#cleanurls

**Comment by Lxx-c** [comment]
> > 去掉config当中的cleanUrls: true,试试
> > ```
> > cleanUrls: true,
> > ```
> 
> https://vitepress.dev/reference/site-config#cleanurls

**Comment by wforguo** [comment]
> > > 去掉config当中的cleanUrls: true,试试
> > > ```
> > > cleanUrls: true,
> > > ```
> > 
> > 
> > https://vitepress.dev/reference/site-config#cleanurls
> 
> 有没有在保留cleanUrls的情况下，解决这个问题的方法呢

nginx配置try_files试试，应该就是刷新404的问题
