### ISSUE TITLE
Can't build vitepress when I use npm package

### ISSUE THREAD

**Issue by luthfimasruri** [vuejs/vitepress#257]
**Describe the bug**
I try to use npm package QuillJS in .vitepress/theme/index.js
```js
import Quill from "quill";
let quill = new Quill("#container")
```
when I run `npm run dev` it works just fine
but when I run `npm run build` it failed
and shows an error message: 

> build error:
>  ReferenceError: document is not defined
>     at Object.\<anonymous\> (D:\vueup-quill\node_modules\quill\dist\quill.js:7661:12)
>     at __webpack_require__ (D:\vueup-quill\node_modules\quill\dist\quill.js:36:30)

**Expected behavior**
It should work in dev and build mode.

**System Info**
- vitepress version: v0.12.2
- vite version: v2.0.5
- Node version: v14.15.4
- OS version: Windows 10

**Comment by MageeLin** [comment]
The same issue, has you fixed it?

**Comment by uoau** [comment]
+1

**Comment by LiuJinYang9527** [comment]
I think there should be a configuration item to turn off SSR

**Comment by haohao809** [comment]
+1

**Comment by kiaking** [comment]
Please open another issue with the reproduction code guys! Otherwise, it's very hard to help 😅
