### ISSUE TITLE
The menu button click is abnormal, only the overlay appears, and there is no menu items.

### ISSUE THREAD

**Issue by mingyuLi97** [vuejs/vitepress#2577]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/44830818/e9db9a7c-2f1c-48cd-a053-cc3544b38e7c)

Error:Attempting to define property on object that is not extensible.

<img width="1073" alt="image" src="https://github.com/vuejs/vitepress/assets/44830818/cfe2bb18-d737-4eb4-8b38-62a06be8644f">

### Reproduction

1. access [website](https://vitepress.dev/guide/what-is-vitepress) using an iOS 17 device
2. click menu button.
3. sometimes this issue may occur.

### Expected behavior

normal function.

### System Info

```sh
iphone 12
ios 17.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Ah, I don't have an iOS 17 device at hand. Someone else has to debug it. Can't reproduce it on iPhone 14 + iOS 16.5

**Comment by mingyuLi97** [comment]
I updated to the latest iOS system, and this issue resolved.
