### ISSUE TITLE
Allow ability to change in-page navigation to top right of page instead of inline with page name

### ISSUE THREAD

**Issue by xyeLz** [vuejs/vitepress#258]
**Describe the solution you'd like**
GitBook implements this really well. For example, on https://ccsp.alukos.com, you will see by clicking on a page that the in-page navigation appears on the _right side_ of the page as opposed to inline with the title of that page. I believe this is referred to as "sidebar depth" in VuePress. What I would like to see implemented natively is the ability to simply adjust a command and have the sidebar for in-page navigation on the right side of the page as opposed to underneath other navigation on the left side of the page.

**Comment by kiaking** [comment]
This is implemented in `theme-next` 👍

**Comment by xyeLz** [comment]
Can you please elaborate more on where this is implemented? I am unaware of any inline ToC.

**Comment by kiaking** [comment]
Checkout `next-theme` 🚀
