### ISSUE TITLE
how to link to image (png), instead of (.png.html)

### ISSUE THREAD

**Issue by fjun99** [vuejs/vitepress#2583]
### Describe the bug

when link to a image, such as 'abc.png', it turns to be a link to 'abc.png.html'

### Reproduction

for example, in markdown (subdir/sample.md) I write:

`[link to big image](./images/abc.png)`

It turns out to be a link to:

`/subdir/images/abc.png.html`

change to <a>:

`<a href='/subdir/images/abc.png'>link to big image</a>`

same.

Important NOTE: If I link to an image in public folder, it is ok.

---

dev vs build

in dev mode, it is ok.

in build mode, it is wrong. 

### Expected behavior

`[link to big image](./images/abc.png)`

link to:

`/subdir/images/abc.png`

### System Info

```sh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.6.2 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 107.1.45.123
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    vitepress: ^1.0.0-beta.5 => 1.0.0-beta.5
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
>  If I link to an image in public folder, it is ok.

Relative paths won't work anyway. They are not copied to dist. Even with the correct link, you'll get 404.

**Comment by fjun99** [comment]
> > If I link to an image in public folder, it is ok.
> 
> Relative paths won't work anyway. Assets marked by links aren't recognised. Even with the correct link, you'll get 404.

ok, already choose to use public for now.

the dev behavior fools me:)

**Comment by brc-dd** [comment]
If you want to keep images aside markdown files, you'll need to import them instead:

```html
# Hello

<a :href="abc">link to big image</a>

<script setup>
import abc from './images/abc.png'
</script>
```

**Comment by fjun99** [comment]
> If you want to keep images aside markdown files, you'll need to import them instead:
> 
> ```
> # Hello
> 
> <a :href="abc">link to big image</a>
> 
> <script setup>
> import abc from './images/abc.png'
> </script>
> ```

try this before, it will break build.

build error:
SyntaxError: Error parsing JavaScript expression: Invalid regular expression flag. (1:11)
    at createCompilerError (/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:17:17)
    at processExpression (/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:3128:7)
    at Array.transformExpression (/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:3025:21)
    at traverseNode (/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1958:38)
    at traverseChildren (/node_modules/@vue/compiler-core/dist/compiler-core.cjs.p

**Comment by brc-dd** [comment]
Can you share the exact code what you wrote? It is working fine for me 👀  Looking at that error it seems you missed a quote somewhere.

**Comment by fjun99** [comment]
thanks, i already get your trick.

import 

& 

:href="abc"

My error is caused by give the image to  :href directly.
