### ISSUE TITLE
The F5 page does not appear after being refreshed

### ISSUE THREAD

**Issue by xing403** [vuejs/vitepress#2590]
### Describe the bug

The F5 page does not appear after being refreshed.
The development mode is normal, but the problem occurs in the production mode

### Reproduction

When I enter other pages through the sidebar display on the home page, the page is normally displayed, but when I use F5 to refresh the page after entering, the content of the home page appears, and then switch to other pages, it is still like this

### Expected behavior

Want to use F5 page layout does not change (normal display content)

### System Info

```sh
Winows 10
node 16
pnpm 8.6.2
```

### Additional context

Error displayed by the console: Hydration completed but contains mismatches.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by xing403** [comment]
The page returned to normal when I created a folder for each `.md` file and changed the name of the md to `index.md`

**Comment by brc-dd** [comment]
Can you share your site+repository if it's public? Most probably, you have either not enabled cleanUrls or not your server is not returning the correct file.

**Comment by xing403** [comment]
webSite: [http://blog.ilstudy.vip/](http://blog.ilstudy.vip/)
repository: [https://github.com/xing403/blog](https://github.com/xing403/blog)

**Comment by zhongjingjogy** [comment]
I try to reproduce the issue using the repository provided by @xing403 , but everything seems normal, as the pages are displayed correctly.
I have a similar problem in another website built with vitepress using the same nginx conf. I wonder if any improvement has been made to the [xing's repository](https://github.com/xing403/blog).
I would like to list the nginx access log record here for further discussion.

# Step to reproduce

## Build

1. Build after cloning
```
pnpm install
npm run docs:build
```

2. Serve the `dist` folder at `test.mesospire.site` by nginx
```
server {
    server_name test.mesospire.site;
    index index.html;
    root /home/user/websites/testvitepress ;
    location / {
            alias /home/user/websites/testvitepress/;
            index index.html
            try_files $uri $uri/ ;
            access_log /tmp/access.log ;
    }
}
```

## Test

1. go to `http://test.mesospire.site` directly by pasting the url in the browser
The backend says:
``` log
122.207.96.72 - - [27/Jul/2023:09:03:56 +0800] "GET / HTTP/1.1" 200 4451 "-" 
122.207.96.72 - - [27/Jul/2023:09:03:56 +0800] "GET /assets/chunks/theme.ff379861.js HTTP/1.1" 200 75601 "http://test.mesospire.site/" 
122.207.96.72 - - [27/Jul/2023:09:03:56 +0800] "GET /assets/inter-roman-latin.2ed14f66.woff2 HTTP/1.1" 200 42464 "http://test.mesospire.site/" 
122.207.96.72 - - [27/Jul/2023:09:03:56 +0800] "GET /assets/index.md.b1f6cc6e.lean.js HTTP/1.1" 200 1481 "http://test.mesospire.site/" 
122.207.96.72 - - [27/Jul/2023:09:03:56 +0800] "GET /assets/chunks/framework.04718b2c.js HTTP/1.1" 200 82686 "http://test.mesospire.site/" 
122.207.96.72 - - [27/Jul/2023:09:03:56 +0800] "GET /assets/style.17e3b7f0.css HTTP/1.1" 200 426377 "http://test.mesospire.site/" 
122.207.96.72 - - [27/Jul/2023:09:03:56 +0800] "GET /assets/app.7058f765.js HTTP/1.1" 200 777001 "http://test.mesospire.site/" 
122.207.96.72 - - [27/Jul/2023:09:03:56 +0800] "GET /images/logo.png HTTP/1.1" 200 14708 "http://test.mesospire.site/" 
122.207.96.72 - - [27/Jul/2023:09:03:57 +0800] "GET /assets/home_index.md.548fdd49.js HTTP/1.1" 200 5461 "http://test.mesospire.site/" 
122.207.96.72 - - [27/Jul/2023:09:03:57 +0800] "GET /images/avatar.jpg HTTP/1.1" 200 17596 "http://test.mesospire.site/" 
```

2. go to `http://test.mesospire.site/home` by click the link in the page
The backend says
``` log
122.207.96.72 - - [27/Jul/2023:09:05:31 +0800] "GET /assets/avatar.b524a73a.jpg HTTP/1.1" 200 17596 "http://test.mesospire.site/home/" 
122.207.96.72 - - [27/Jul/2023:09:05:31 +0800] "GET /assets/blogs_event_index.md.153dc89c.js HTTP/1.1" 200 27052 "http://test.mesospire.site/home/" 
122.207.96.72 - - [27/Jul/2023:09:05:31 +0800] "GET /assets/blogs_resource_index.md.fd45107e.js HTTP/1.1" 200 4053 "http://test.mesospire.site/home/" 
```

3. go to `http://test.mesospire.site/blogs/event/` by click the link in the page
The backend says nothing.
``` log
```

4. Refresh the page `http://test.mesospire.site/blogs/event/`
The backend says
``` log
122.207.96.72 - - [27/Jul/2023:09:07:02 +0800] "GET /blogs/event/ HTTP/1.1" 200 6630 "-" 
122.207.96.72 - - [27/Jul/2023:09:07:02 +0800] "GET /assets/style.17e3b7f0.css HTTP/1.1" 304 0 "http://test.mesospire.site/blogs/event/" 
122.207.96.72 - - [27/Jul/2023:09:07:02 +0800] "GET /assets/blogs_event_index.md.153dc89c.lean.js HTTP/1.1" 200 494 "http://test.mesospire.site/blogs/event/" 
122.207.96.72 - - [27/Jul/2023:09:07:02 +0800] "GET /assets/app.7058f765.js HTTP/1.1" 304 0 "http://test.mesospire.site/blogs/event/" 
122.207.96.72 - - [27/Jul/2023:09:07:02 +0800] "GET /assets/inter-roman-latin.2ed14f66.woff2 HTTP/1.1" 304 0 "http://test.mesospire.site/blogs/event/" 
122.207.96.72 - - [27/Jul/2023:09:07:02 +0800] "GET /assets/chunks/framework.04718b2c.js HTTP/1.1" 304 0 "http://test.mesospire.site/blogs/event/" 
122.207.96.72 - - [27/Jul/2023:09:07:02 +0800] "GET /assets/chunks/theme.ff379861.js HTTP/1.1" 304 0 "http://test.mesospire.site/blogs/event/" 
122.207.96.72 - - [27/Jul/2023:09:07:03 +0800] "GET /assets/index.md.b1f6cc6e.js HTTP/1.1" 200 1481 "http://test.mesospire.site/blogs/event/" 
122.207.96.72 - - [27/Jul/2023:09:07:03 +0800] "GET /assets/home_index.md.548fdd49.js HTTP/1.1" 304 0 "http://test.mesospire.site/blogs/event/" 
```

**Comment by xing403** [comment]
My solution is to create a folder for each `.md` file, rename this `.md` to `index.md`, and then configure the sidebar.

**Comment by zhongjingjogy** [comment]
It seems that works as a solution, though the code becomes slightly clumsy. According to @xing403 's information, I add two pages for comparison, the folder layout is
```
- blog
    - not_folder.md
    - folder/index.md
```
The link for `not_folder.md` is `http://test.mesospire.site/blogs/not_folder`, and the other is `http://test.mesospire.site/blogs/folder/`.

The page status after refresh are
- `http://test.mesospire.site/blogs/folder/`: As it is before being refreshed.
- `http://test.mesospire.site/blogs/not_folder`: 404 Not Found

**I wonder whether a potential solution is available to resolve this problem by means of not struggling with the Nginx configuration.**

**Comment by zhongjingjogy** [comment]
Could another solution be using `rewrites`. For example,
```
import { defineConfig } from 'vitepress'

export default defineConfig({
  ...
  cleanUrls: true,
  lastUpdated: true,
  rewrites: {
    "blogs/not_folder.md": "blogs/not_folder/index.md",
  },
...
```
Such a solution works without bothering creating a folder structure on our own. It is tested and works like a charm.

**Comment by zhongjingjogy** [comment]
I try to use this strategy to solve the problem of my wesites, and it seems everything is fine. It might turns out that problem resists when neither vitepress repo folder structure nor nginx conf is properly set up. 

The available solution from mine is that, .i,e, Nginx conf,
```
server {
    server_name xxx.xxx.com;
    index index.html;
    root  /path/to/dist;
    location / {
            alias /path/to/dist/;
            try_files $uri $uri/ /index.html;
    }
}
```

For vitepress, as suggested by @xing403, markdown should be layouted in a separated folder with index.md inside. The official website indicates that `rewrites` can be used to dynamically achieve this goal.

**Comment by brc-dd** [comment]
The issue is probably with the nginx config. With `cleanUrls: true`, putting things in `folder/index.md` format should not be required. I'm not an expert with nginx, but the general logic for cleanUrls to work flawlessly is if `/foo` is requested, then check for `dist/foo`, `dist/foo.html`, `dist/foo/index.html`, return whatever is found, else 404.
