### ISSUE TITLE
Try to update the version to the newest, but error arise.

### ISSUE THREAD

**Issue by ryankert01** [vuejs/vitepress#2591]
### Describe the bug

I tried to update my version for new features, but it just cannot do so...

```
✖ building client + server bundles...
build error:
Error: ENOENT: no such file or directory, open '/home/runner/work/AlgoKert/AlgoKert/node_modules/shiki/themes/material-palenight.json'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

### Reproduction

look at this action.
https://github.com/ryankert01/AlgoKert/actions/runs/5483665555/jobs/9990251033?pr=11

and the PR accordingly.
https://github.com/ryankert01/AlgoKert/pull/11

### Expected behavior

raise an error on github action.

### System Info

```sh
I first get the error message on Github action, but I got the same error message on my Mac too.
So, I provide my Mac's system info.
  System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 137.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5
  npmPackages:
    vitepress: ^1.0.0-beta.5 => 1.0.0-beta.5
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Remove this line from your config: https://github.com/ryankert01/AlgoKert/blob/main/docs/.vitepress/config.js#L47
