### ISSUE TITLE
Copying the configuration of vuepress to vitepress, the sidebar is not displayed as a result.

### ISSUE THREAD

**Issue by misitebao** [vuejs/vitepress#260]
**Describe the bug**
Copying the configuration of vuepress to vitepress, the sidebar is not displayed as a result.

**To Reproduce**
Clone Repo: [https://github.com/misitebao/template-vitepress.git](https://github.com/misitebao/template-vitepress.git)
Run: npm i && npm run dosc:dev

**Expected behavior**
Display the sidebar normally

**System Info**
- vitepress version: v0.12.2
- vite version: 
- Node version: v14.8.0
- OS version: Win10

**Additional context**
I want to implement a template template as the basis for subsequent vitepress projects

**Comment by kiaking** [comment]
Yes, the config is a little different from VuePress. You need to use `{ text: '...' }` instead of `{ title: '...' }`. And yeah we're missing the documentation for it 😅  Though, for now, please take a look at the [VitePress doc config as an example](https://github.com/vuejs/vitepress/blob/master/docs/.vitepress/config.js).

**Comment by rickalex21** [comment]
@kiaking I'm also having problems with the sidebar as well but according to the issues template.
>Please do not open issue about default theme missing features or something doesn't work like VuePress.

Just thought I would mention here for future reference. I'm not sure how I'm going to go about getting the sidebar the
way I would like by only using ```{text:'...'}``` in vitepress but this does not work in vitepress, it only works in vuepress:

```javascript
module.exports = {
    themeConfig:{
        sidebar: {
            '/code/': [
              {
                title: 'Guide',
                collapsable: false,
                children: [
                  '',
                  'git',
                ]
              }
            ],
          },
    }
}
```

It gives me the following errors:

```javascript
Loading module from “http://localhost:3000/code.md?import&t=1621087628773” was blocked because of a disallowed MIME type (“”).
code.html
Loading failed for the module with source “http://localhost:3000/code.md?import&t=1621087628773”. code.html:9:1
TypeError: error loading dynamically imported module router.js:67:25
[Vue warn]: Unhandled error during execution of render function 
  at <Layout> 
  at <VitePressApp> runtime-core.esm-bundler.js:38:17
Uncaught (in promise) TypeError: route.data is null
    showNavbar Layout.vue:119
    reactiveEffect reactivity.esm-bundler.js:42
    get value reactivity.esm-bundler.js:861
    pageClasses Layout.vue:162
    reactiveEffect reactivity.esm-bundler.js:42
    get value reactivity.esm-bundler.js:861
    unref reactivity.esm-bundler.js:775
    get reactivity.esm-bundler.js:778
    _sfc_render Layout.vue:76
    renderComponentRoot runtime-core.esm-bundler.js:846
    componentEffect runtime-core.esm-bundler.js:4280
    reactiveEffect reactivity.esm-bundler.js:42
    effect reactivity.esm-bundler.js:17
    setupRenderEffect runtime-core.esm-bundler.js:4263
    mountComponent runtime-core.esm-bundler.js:4222
    processComponent runtime-core.esm-bundler.js:4182
    patch runtime-core.esm-bundler.js:3791
    componentEffect runtime-core.esm-bundler.js:4298
    reactiveEffect reactivity.esm-bundler.js:42
    effect reactivity.esm-bundler.js:17
    setupRenderEffect runtime-core.esm-bundler.js:4263
    mountComponent runtime-core.esm-bundler.js:4222
    processComponent runtime-core.esm-bundler.js:4182
    patch runtime-core.esm-bundler.js:3791
    render runtime-core.esm-bundler.js:4883
    mount runtime-core.esm-bundler.js:3077
    mount runtime-dom.esm-bundler.js:1259
    <anonymous> index.js:101
```
