### ISSUE TITLE
render my .md string

### ISSUE THREAD

**Issue by 572031690** [vuejs/vitepress#2603]
### Is your feature request related to a problem? Please describe.

I recently needed to obtain an MD file from the remote end and obtain its internal string during development. I think I can directly use the capabilities of vitepress to parse this string, including the Vue component that I registered globally that can also be rendered within this string. I hope vitepress can provide a method where I can pass in a custom MD string that can parse my string into HTML, The relevant code including Vue can also be parsed and rendered within the MD string。

### Describe the solution you'd like

like :
```
<renderFilter src="http:test.ver.com/assets/test.md"></renderFilter>
```
or 
```
<renderFilter src="./test.md"></renderFilter>
```
or 
```
<renderFilter src="this is a `test` dec !"></renderFilter>
```

and if test.md has vue it can be render like :
// test.md
```
# this is title 

<myGlobalComponents></myGlobalComponents>

{{ title }}

<srcipt setup>
import { ref } from 'vue'
const title = ref('test')
</script>
```

### Describe alternatives you've considered

If this feature is implemented, it would be too cool!!!

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/guide/routing#rendering-raw-content ?
