### ISSUE TITLE
features(theme):  Link configuration supporting features in the home page

### ISSUE THREAD

**Issue by jiazengp** [vuejs/vitepress#2604]
### Is your feature request related to a problem? Please describe.

Based on my analysis of user behavior in a project, I have found that a large number of users tend to attempt clicking on features on the home page to learn more about them. However, it is frustrating that this functionality is currently not supported.

### Describe the solution you'd like

Support jump link configuration.
For example:
```markdown
layout: home

features:
  - title: xxx
    icon: 🦾
    details: xxxx
    link: https://xxx.xx
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by jiazengp** [comment]
If possible, I would like to contribute a PR for this

**Comment by brc-dd** [comment]
It's already supported. What issues are you having?

**Comment by jiazengp** [comment]
I'm sorry, I thought I haven't received any support. Thank you
