### ISSUE TITLE
Hydration completed but contains mismatches

### ISSUE THREAD

**Issue by lmylinux** [vuejs/vitepress#2608]
### Describe the bug

I use nginx to deploy vitepress
When I visit atopno.cn and click one by one to enter the article, there is no problem
But when I directly access the complete link of a certain article, there will be an 'Hydration completed but contains mismatches' error and misalignment behavior

### Reproduction

npm run docs:build = vitepress build docs

### Expected behavior

I hope there is no problem when I directly access a certain article
The article link is as follows
https://www.atopno.cn/mileage/Linux/Jenkins/automake

### System Info

```sh
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 4.23 GB / 15.91 GB
  Binaries:
    Node: 16.15.0 - E:\node\node.EXE
    npm: 8.5.5 - E:\node\npm.CMD
  Browsers:
    Chrome: 114.0.5735.199
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.79)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-beta.2 => 1.0.0-beta.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We are working on providing better error messages (track #422). However, this is not a bug in vitepress, but in your code itself. It can happen because of many things: https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch
