### ISSUE TITLE
simple css overriding ain't happening

### ISSUE THREAD

**Issue by omarcostahamido** [vuejs/vitepress#2612]
### Describe the bug

I was trying to follow these instructions [here](https://vitepress.dev/guide/extending-default-theme#customizing-css) just to change the color of the Title on the home page.
According [this section](https://vitepress.dev/guide/custom-theme#theme-resolving), just by creating the `.vitepress/theme/index.js` and `.vitepress/theme/custom.css` files that the [Customizing CSS](https://vitepress.dev/guide/extending-default-theme#customizing-css) suggests should be enough to have it being read.
But no. That alone does not work.

I had to add `import './theme/custom.css'` to the `config.ts` file first to force it to read the custom css.

**edit:**
more recently I tried renaming the `.vitepress/theme/index.js` to `.ts` and then it woke up! now it is aware of that file...
Looks like a bug, no?

### Reproduction

I was trying to follow these instructions [here](https://vitepress.dev/guide/extending-default-theme#customizing-css) just to change the color of the Title on the home page.
According [this section](https://vitepress.dev/guide/custom-theme#theme-resolving), just by creating the `.vitepress/theme/index.js` and `.vitepress/theme/custom.css` files that the [Customizing CSS](https://vitepress.dev/guide/extending-default-theme#customizing-css) suggests should be enough to have it being read.
But no. That alone does not work.

I had to add `import './theme/custom.css'` to the `config.ts` file first to force it to read the custom css.

**edit:**
more recently I tried renaming the `.vitepress/theme/index.js` to `.ts` and then it woke up! now it is aware of that file...
Looks like a bug, no?

### Expected behavior

be able to follow along the initial instructions on custom css

### System Info

```sh
mac os catalina latest vitepress nodejs 16 npm 6.9
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by xsjcTony** [comment]
Please make sure you import the custom CSS file after importing `DefaultTheme` from `'vitepress/theme`.
Import order matters.

```ts
// This will work
import DefaultTheme from 'vitepress/theme';
import './custom.css';

// This won't work
import './custom.css';
import DefaultTheme from 'vitepress/theme';
```

**Comment by omarcostahamido** [comment]
I had followed the instructions exactly as they are on the links provided.
Did not invert that order.

**Comment by xsjcTony** [comment]
@omarcostahamido Reproduction link then? Go to something like https://stackblitz.com/ to write a minimal repo, otherwise I'm not able to help.

**Comment by omarcostahamido** [comment]
Ok, let me study how to work with that and I will get back to you. Thank you.

**Comment by brc-dd** [comment]
you need to restart vitepress after creating `.vitepress/theme/` to pick those files up.

**Comment by omarcostahamido** [comment]
@brc-dd that makes more sense now but it is not explained anywhere near in the documentation.
I would like to reopen the issue just for that and suggest a PR myself.
Thank you.
