### ISSUE TITLE
Docs site displays docs for main branch, not latest release version

### ISSUE THREAD

**Issue by marccoup** [vuejs/vitepress#2624]
The docs site uses the main branch. This leads to having documentation for features that don't work in the latest release as they've yet to be merged. I think it's more confusing since the docs show the version in the top right, but in fact that's not the version the docs are for.

I'd expect the site to show either the correct version of the docs for the version displayed in the header, or a prominent notice somewhere on the site explaining the discrepancy.

If this is mentioned somewhere in the docs I apologise I must have missed it.

## An Example
This section of the docs asserts that you can configure minisearch, but you can't in the latest release (v1.0.0-beta.5 at time of writing).
![image](https://github.com/vuejs/vitepress/assets/48916612/5c8bedd2-ded4-46be-b014-6102c471c984)

This caught me off guard at first when my `config.ts` file complained that `miniSearch` did not exist in `LocalSearchOptions`. It took me a while to figure out what was happening and why it didn't work.

**Comment by brc-dd** [comment]
The docs are currently in state of flux. But we will have proper badges specifying version range for any new features once v1 is out. Thanks.
