### ISSUE TITLE
How should I trace build error?

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/vitepress#2627]
### Describe the bug

I'm getting some errors when running `pnpm build`, I guess it's because I should somehow wrap this component causing the error in `<ClientOnly />`, but how should I find the exact cause from the error log? It does not provide any useful details (see below screenshot)

---

Another question, as I guess my error is because of this:
Should I wrap `watch()` inside `onMounted()`? or in another word, can I do it? I didn't find any corresponding example in Vue documentation... 
Sorry if this is a dumb question, as I'm a react guy :(
```vue
<script setup lang="ts">
import { useLocalStorage } from '@vueuse/core';
import { watch } from 'vue';

const nfcapiEnvRef = useLocalStorage('vp-nfcapi-env', 'staging', {
  deep: false,
  listenToStorageChanges: true,
  writeDefaults: true
});

watch(nfcapiEnvRef, (value, oldValue) => {
  const htmlDataSet = document.documentElement.dataset;
  oldValue && (htmlDataSet.nfcapiEnv = oldValue.toLowerCase());
  htmlDataSet.nfcapiEnv = value.toLowerCase();
}, { immediate: true });
</script>
```

---

Screenshot of the error:

![Snipaste_2023-07-17_01-34-01](https://github.com/vuejs/vitepress/assets/45784210/688a3697-2cab-4ad0-82a9-eb5389c68f21)

### Reproduction

This is not a bug, but a question

### Expected behavior

N/A

### System Info

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 30.87 GB / 63.84 GB
  Binaries:
    Node: 18.16.0 - C:\NodeJS\node.EXE
    Yarn: 1.22.19 - C:\NodeJS\yarn.CMD
    npm: 9.8.0 - C:\NodeJS\npm.CMD
    pnpm: 8.6.7 - C:\NodeJS\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-beta.5 => 1.0.0-beta.5
```

### Additional context

N/A

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> Should I wrap watch() inside onMounted()? or in another word, can I do it

Do something like this instead:

```ts
import { inBrowser } from 'vitepress'

watch(nfcapiEnvRef, (value, oldValue) => {
  if (!inBrowser) return;

  const htmlDataSet = document.documentElement.dataset;
  oldValue && (htmlDataSet.nfcapiEnv = oldValue.toLowerCase());
  htmlDataSet.nfcapiEnv = value.toLowerCase();
}, { immediate: true });
```

You can set `DEBUG` environment variable to true or any [debug](https://www.npmjs.com/package/debug) compliant specifier. It will preserve the `.temp` directory, so you can see the code that's causing the error. It won't give better errors though. (`DEBUG=*`, `vite:*` or `vitepress:*` might show the file that's causing the error, not sure.) But it might be easier to search where in your project you've the code that generates that line in `.temp/app.js`

**Comment by xsjcTony** [comment]
@brc-dd Thanks, that makes sense.
To be said, `inBrowser` seems a good way in vitepress, but I just want to know, in vue general, is it a good practice to put side-effects (e.g. watchers) that access DOM into `onMounted` hook?

**Comment by xsjcTony** [comment]
Also @brc-dd , seems `pnpm build` is not performing type check? I tried to make some intentionally TS error, but the build still passes.
I can't find any corresponding details in the doc and I don't think it worth to open another issue, so I just asked here. Thanks

**Comment by brc-dd** [comment]
> but I just want to know, in vue general, is it a good practice to put side-effects (e.g. watchers) that access DOM into onMounted hook?

It will work, but you'll need to manually stop it. Otherwise there will be memory leaks: https://vuejs.org/guide/essentials/watchers.html#stopping-a-watcher

> pnpm build is not performing type check?

You'll need to add a separate `tsc`/`vue-tsc` step for that to work.
