### ISSUE TITLE
TypeError: section.titles.at is not a function

### ISSUE THREAD

**Issue by fieemiracle** [vuejs/vitepress#2630]
### Describe the bug

when I use 'npm run dev',it occurs the error of 'failed to start server. error:TypeError: section.titles.at is not a function',but the error is in 'node_moduls/vitepress/dist/node/serve-d0f912b9.js:36893:35',and the codes are the following:
` async function indexAllFiles(files) {
    const documentsByLocale = /* @__PURE__ */ new Map();
    await Promise.all(
      files.filter((file) => fs$a.existsSync(file)).map(async (file) => {
        const fileId = getDocId(file);
        const sections = splitPageIntoSections(
          md.render(await fs$a.readFile(file, "utf-8"), createMarkdownEnv(file))
        );
        const locale = getLocaleForPath(file);
        let documents = documentsByLocale.get(locale);
        if (!documents) {
          documents = [];
          documentsByLocale.set(locale, documents);
        }
        documents.push(
          ...sections.map((section) => ({
            id: `${fileId}#${section.anchor}`,
            text: section.text,
            title: section.titles.at(-1),
            titles: section.titles.slice(0, -1)
          }))
        );
      })
    );
    for (const [locale, documents] of documentsByLocale) {
      const index = getIndexByLocale(locale);
      index.removeAll();
      await index.addAllAsync(documents);
    }
    debug$2(`\u{1F50D}\uFE0F Indexed ${files.length} files`);
  }`

### Reproduction

i try to delete 'node_moduls' and 'package.lock.json',and then use 'npm install' and 'npm run dev',but it is fail.

### Expected behavior

start sucessfully

### System Info

```sh
'package.json' :
` "dependencies": {
    "vitepress": "^1.0.0-beta.5",
    "vue": "^3.2.45",
    "vuepress-theme-vdoing": "^1.9.4"
  }`
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Update your node version to v16 or above.
