### ISSUE TITLE
表格内容换行后页面就报错

### ISSUE THREAD

**Issue by sxdPanda** [vuejs/vitepress#2634]
### Describe the bug

| 属性        |      默认值      |  说明 |  对应组件 |
| ------------- | :-----------: | ----: | ----: |
| col 3 is      | right-aligneright-alignedright-alignedright-alignedright-alignedright-alignedright-alignedright-alignedright-alignedright-alignedright-alignedright-alignedright-alignedright-alignedd | $1600 | $1600 |

### Reproduction

内容换行后就报错：componentStyles.md?import&t=1689578052281:23  DOMException: Failed to execute 'setAttribute' on 'Element': '6' is not a valid attribute name.

### Expected behavior

内容换行后就报错：componentStyles.md?import&t=1689578052281:23  DOMException: Failed to execute 'setAttribute' on 'Element': '6' is not a valid attribute name.

### System Info

```sh
win11 edge浏览器
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
你好，能方便提供一下复现的仓库或者在线地址吗

**Comment by CosmoLau** [comment]
> 

用反斜杠转义一下能临时解决
```txt
|test|test|
|:-|-|
|{test}|\{test\}|
```
大括号里的内容应该是被 vue 当成了文本差值吧

**Comment by zonemeen** [comment]
解决方案在这个issue里边有了，原因里边也说明了 https://github.com/vuejs/vitepress/issues/2046
