### ISSUE TITLE
After fetch(file) response.text(), the import path of the file content is incorrect

### ISSUE THREAD

**Issue by laterdayi** [vuejs/vitepress#2636]
### Describe the bug

After fetch(file) response.text(), the import path of the file content is incorrect

```
import {
  MeshBasicMaterial,
  Vector2
} from "three";
```

Be converted to

```
import {
  MeshBasicMaterial,
  Vector2
} from "/.vitepress/cache/deps/three.js?v=90219ecf";
```

### Reproduction

*

### Expected behavior

After fetch(file) response.text(), the import path of the file content is incorrect

After fetch(file) response.text() After that, keep the original import "*"

### System Info

```sh
windows
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please share a minimal reproducible example.

**Comment by laterdayi** [comment]
##  machine-room.ts
```
import {
  MeshBasicMaterial,
  MeshStandardMaterial,
  Mesh,
  PerspectiveCamera,
  Raycaster,
  Scene,
  Texture,
  TextureLoader,
  WebGLRenderer,
  Vector2,
  Color
} from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
```

## index.vue
```
  fetch("./machine-room.ts")
    .then(response => {
      response.text().then(e => {
        console.log(e);
      });
    })
```

What I got instead

```
import {
  MeshBasicMaterial,
  PerspectiveCamera,
  Raycaster,
  Scene,
  TextureLoader,
  WebGLRenderer,
  Vector2
} from "/.vitepress/cache/deps/three.js?v=90219ecf";
import { OrbitControls } from "/.vitepress/cache/deps/three_examples_jsm_controls_OrbitControls__js.js?v=90219ecf";
import { GLTFLoader } from "/.vitepress/cache/deps/three_examples_jsm_loaders_GLTFLoader__js.js?v=90219ecf";
```

**Comment by laterdayi** [comment]
How can I prevent import "path" from being converted when fetch reads the contents of a file

Thank you for your help             @brc-dd

**Comment by brc-dd** [comment]
It's getting compiled by vite. Move that file to public directory?

**Comment by brc-dd** [comment]
You can also do this:

```ts
import machineRoomCode from './machine-room.ts?raw'

console.log(machineRoomCode)
```

**Comment by laterdayi** [comment]
My scenario is that I put the ts vue file in docs, fetch the file content, and then hand it over to stackblitz to dynamically generate the project, but response.text() will convert the path of import to the path in the.vitepres cache. There is no address that can be configured to prevent paths from being escaped

**Comment by laterdayi** [comment]
I want to import "three" module in the fetch response.text file instead of import ".vitepress cache".

**Comment by laterdayi** [comment]
![图片](https://github.com/vuejs/vitepress/assets/122137647/d4d23aac-6a1a-40db-975e-f159a2c774cb)
Thank you very much for your help. Is there a vite or vitepress configuration that can prevent file import path from being converted

**Comment by brc-dd** [comment]
@laterdayi Do something like this: https://stackblitz.com/edit/vite-vuzman?file=docs/index.md

**Comment by laterdayi** [comment]
Pass? raw is OK, but I want to loop all files through import.meta-.glob,

 how can I dynamically import form "*? raw " 

```
const files = import.meta.glob(".. /machine-room/**/*");
```

**Comment by brc-dd** [comment]
https://vitejs.dev/guide/features.html#glob-import-as

```ts
import.meta.glob('../machine-room/**/*', { as: 'raw' })
```

**Comment by laterdayi** [comment]
![图片](https://github.com/vuejs/vitepress/assets/122137647/2a1efdf8-1c5a-41cf-9134-7fbc781b7ef7)
I made it. Thank you so much for your help

**Comment by laterdayi** [comment]
@brc-dd     I use const files = import.meta-. glob("../machine-room/**/*", { as: "raw" }); , but it does not contain this file, is there a way to solve it?

**Comment by brc-dd** [comment]
Which file?
