### ISSUE TITLE
Add personal website social icon

### ISSUE THREAD

**Issue by azat-io** [vuejs/vitepress#2638]
### Is your feature request related to a problem? Please describe.

In default VitePress there is `VPSocialLink` component which allows to add social icons.

Could you please add one more icon for personal website here?
https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/support/socialIcons.ts

### Describe the solution you'd like

...

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can past custom icons as svg: https://vitepress.dev/reference/default-theme-config#sociallinks (Refer the example.)
