### ISSUE TITLE
Last updated detection doesn't like dynamic routing

### ISSUE THREAD

**Issue by Pandapip1** [vuejs/vitepress#2646]
### Describe the bug

Using both dynamic routing and `lastUpdated: true` causes the build to crash.

### Reproduction

I have the following structure:

```
.vitepress
    config.js
src
    [test]
        index.md
        index.paths.js
```

In `.vitepress/config.js`, `lastUpdated` was set to `true`. The following error occured:

```
[vitepress] spawn git ENOENT
file: C:/Users/<me>/source/repos/<repo>/src/1234/index.md
✖ building client + server bundles...
build error:
Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I have determined that the root cause is that: https://github.com/vuejs/vitepress/blob/main/src/node/markdownToVue.ts#L210 doesn't check if the file actually exists, causing https://github.com/vuejs/vitepress/blob/a07f959d472f1976d26c675066204eca9bc7c651/src/node/utils/getGitTimestamp.ts#L4 to spawn a process to get the git log of a nonexistent file, which fails with ENOENT because the file doesn't exist.

### Expected behavior

Last updated detection is disabled for dynamic routes.

### System Info

```sh
Probably irrelevant, but:


  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 763.48 MB / 9.85 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-beta.5 => 1.0.0-beta.5
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
fixed in 7778187
