### ISSUE TITLE
Adding link to (non-html) files from md

### ISSUE THREAD

**Issue by davay42** [vuejs/vitepress#265]
Vitepress keeps adding `.html` extension to any link referencing a pdf file relative to the page. Seems like it's hard-coded here

https://github.com/vuejs/vitepress/blob/cee0b400d95b610fa47ea79007e03221a140084f/src/node/markdownToVue.ts#L52

May be it's the right way and any non-routed link should be put as `<a>` tag? Just wanted to share this observation.

**Comment by jarrodu** [comment]
I just ran into the same issue. I am also trying to link to a pdf file.

**Comment by kiaking** [comment]
Ah good point. Wasn't thinking about this use case. Hmmm should we have whitelist to filter out major extensions?

**Comment by DeFUCC** [comment]
@kiaking Yeah, that could be a nice solution. The actual extensions may differ for different sites significantly – some may share books, others provide 3d models and so on.  So there may be an option in config.js file with some default state with the list of most used file extensions.

**Comment by jarrodu** [comment]
That would be a great solution. Thanks for thinking about it.

**Comment by davay42** [comment]
@kiaking  @jarrodu I'm deep into vitepress now and have many ideas on improving it, but can't figure out where to discuss them. Vue discord has a vitepress channel, but it's quite silent. I think vitepress may become a great tool for users to create and publish their digital gardens (which are quite a hype now!). I have my little snippets running for the purpose and I'll be glad to share these ideas and collaborate on implementing them.

**Comment by davay42** [comment]
Any updates on this issue? @kiaking @jarrodu ?

**Comment by jarrodu** [comment]
I have not worked on this issue. Since I am using vitepress for a personal project this issue is not urgent.

Are you thinking of picking up the issue?

**Comment by davay42** [comment]
It's ok. ) I have a couple of workarounds for this issue with custom components just for the cases. Vitepress is so flexible, so any problem is solvable with a nice SFC ))))

**Comment by brc-dd** [comment]
Changing `EXTERNAL_URL_RE` to `/^https?:|\.(?!html|md)\w+$/i` might fix this.
