### ISSUE TITLE
Build issue 

### ISSUE THREAD

**Issue by arunkaruppasamy** [vuejs/vitepress#2653]
### Describe the bug

Actuall I am using one pakage in vue component and I am importing my vue component in vitepress then when I am trying to build I am getting this error

(!) Some chunks are larger than 500 kBs after minification. Consider:

Using dynamic import() to code-split the application
Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ building client + server bundles...
⠙ rendering pages...ReferenceError: document is not defined
at enableDismissTrigger (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:826:21)
at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:908:3
at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:7:83
at Object. (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:10:3)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at ModuleWrap. (node:internal/modules/esm/translators:190:29)
at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
✖ rendering pages...
build error:
ReferenceError: document is not defined
at enableDismissTrigger (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:826:21)
at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:908:3
at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:7:83
at Object. (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:10:3)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at ModuleWrap. (node:internal/modules/esm/translators:190:29)
at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
PS C:\ArunSk\aswin>
if I comment that package and try to build it's building fine and I have added config.ts also

import { UserConfig } from 'vite';

const config: UserConfig = {
// Other Vite configuration options...
build: {
rollupOptions: {
external: /^bootstrap($|/)/,
},
ssr: false,
},
};

export default config;

my package.json

{
"scripts": {
"docs:dev": "vitepress dev docs",
"docs:build": "vitepress build docs",
"docs:preview": "vitepress preview docs"
},
"peerDependencies": {
"markdown-it-container": "^3.0.0",
"vitepress": "",
"vue": "^3.2.0"
},
"devDependencies": {
"@types/markdown-it": "^12.2.3",
"@types/markdown-it-container": "^2.0.5",
"@types/node": "^18.16.3",
"lint-staged": "^13.2.2",
"vue": "^3.2.38"
},
"dependencies": {
"bootstrap": "^5.2.0",
"fire-stars": "^0.0.1",
"markdown-it": "^13.0.1",
"markdown-it-container": "^3.0.0",
"sass": "^1.63.6",
"vitepress": "",
"vue": "^3.2.0"
}
}

### Reproduction

So is it possible to sort out that issue with vite config ts 

// vite.config.ts
import { defineConfig } from 'vite';
import { UserConfig } from 'vite';

const config: UserConfig = {
build: {
rollupOptions: {
external: ['fire-stars'], // Add external module
output: {
globals: {
'fire-stars': 'fireStars', // Provide global variable name for the external module
},
},
},
},
};

export default defineConfig(config);

so is it posiible with vite config ts file ?

### Expected behavior

Build susseful 

And this is my old question same issue But now I want in diff approch

https://github.com/vuejs/vitepress/issues/2633

### System Info

```sh
{
  "devDependencies": {
    "vitepress": "^1.0.0-beta.5"
  },
  "scripts": {
    "docs:dev": "vitepress dev vitepress",
    "docs:build": "vitepress build vitepress",
    "docs:preview": "vitepress preview vitepress"
  },
  "dependencies": {
    "fire-stars": "^0.0.1",
    "sass": "^1.63.6"
  }
}
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by arunkaruppasamy** [comment]
So Actually I am using vue component inside vitepress while running app it's running fine I am able to see my vue component and that component is using bootstrap package

when we are going for building i am getting that error because vitepress is while building it will go for ssr right

**Comment by arunkaruppasamy** [comment]
This is my config file 

`// vite.config.ts
import { defineConfig } from 'vite';
import { UserConfig } from 'vite';

const config: UserConfig = {
build: {
rollupOptions: {
external: ['fire-stars'], // Add external module
output: {
globals: {
'fire-stars': 'fireStars', // Provide global variable name for the external module
},
},
},
},
};`

and my package code is 
`{
  "devDependencies": {
    "vitepress": "^1.0.0-beta.5"
  },
  "scripts": {
    "docs:dev": "vitepress dev vitepress",
    "docs:build": "vitepress build vitepress",
    "docs:preview": "vitepress preview vitepress"
  },
  "dependencies": {
    "fire-stars": "^0.0.1",
    "sass": "^1.63.6"
  }
}`

**Comment by brc-dd** [comment]
I still don't understand what's the issue here? To escape the SSR use the resolutions mentioned at #2633.

**Comment by arunkaruppasamy** [comment]
Yup, Actuall my application is like kind of vuetify application will show one package how to use in their project so like in vite press we are doing the documentation part likw we will show copy, edit and show code in that to show that package componenet we are using vue code inside vitepress and when we are using this fix

https://github.com/vuejs/vitepress/issues/2633

it's not showing component while ruuning and the same code will show in view code also in view code 
kind od we are using the same like this 
https://github.com/flingyp/vitepress-demo-preview

so if that resolve in code it not gonna help me, so I thought of we can resolve from vite.config.ts

so that's my doubt

**Comment by brc-dd** [comment]
No, it's not possible to do that from vite.config file. Disabling SSR globally is not supported.

If I understand correctly, you basically want to show your components right? Use something like [Histoire](https://histoire.dev/) for that. Or if you're using that demo-preview plugin, have you tried doing something like this?

```html
<ClientOnly>
  <preview path="./xxx/xx.vue" />
</ClientOnly>
```

**Comment by arunkaruppasamy** [comment]
Thanks @brc-dd 😃 ,
I will follow the old one only.
