### ISSUE TITLE
TOC won't parse imported markdown files

### ISSUE THREAD

**Issue by gawlk** [vuejs/vitepress#266]
**Describe the bug**
When doing something like this:

`index.md`:
```
[[toc]]

<A />
<B />

<script setup>
    import A from './sections/a.md'
    import B from './sections/b.md'
</script>
```

`a.md`:
```
## Title

test
```

`b.md`:
```
## Title2

test2
```

`[[toc]]` won't show anything because it doesn't parse the sub .md files

**To Reproduce**
Steps to reproduce the behavior: Just use the code that I pasted

**Expected behavior**
I expect `[[toc]]` to take into account the markdown that is imported so that we can organise our text into different files

**System Info**
- vitepress version: latest
- vite version: latest
- Node version: latest
- OS version: Mac OS M1 latest

**Additional context**

**Comment by kiaking** [comment]
Can you try importing MD files with this syntax and how it goes?

```
<!--@include:./sections/a.md-->
```
