### ISSUE TITLE
after rewrite, import error

### ISSUE THREAD

**Issue by tang-tag** [vuejs/vitepress#2662]
### Describe the bug

Failed to import the file from the relative path after rewriting。

![image](https://github.com/vuejs/vitepress/assets/22408105/43f8d840-d18b-4a2d-b678-5a9bd4edd57c)

### Reproduction

https://stackblitz.com/edit/vite-9syvzp?file=docs%2F.vitepress%2Fconfig.ts

### Expected behavior

I want to import the file successfully using a relative path

### System Info

```sh
"vitepress": "1.0.0-beta.5"
"node": "18.16.0"
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's relative to the final path. Use `<<< ./Demo/demo.ts` for that to work.

**Comment by tang-tag** [comment]
> 
I'am sorry, my description is not accurate enough

i want rewrite rule like this:
   `':path*/src/:component/README.md': ':path*/:component.md'`

I want to remove `src` from the path
But the introduced ts cannot be rewritten

**Comment by brc-dd** [comment]
The process is same. That snippet injection is relative to the final path -- ./src/Demo/Demo.ts
