### ISSUE TITLE
🐞Bug: `aside`'s outline marker is flicking when navigating towards above

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/vitepress#2665]
### Describe the bug

The aside's outline marker will have an annoying flick when navigating towards above. All `vitepress` sites seems have this problem.

The video should be enough to demo the issue. (Sorry for the bad quality)

### Reproduction

https://github.com/vuejs/vitepress/assets/45784210/d21095b6-a769-45c5-9119-0fc88f041c3f

### Expected behavior

No flick

### System Info

```sh
Chrome 114
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This was supposed to look cool 😅 It's hard to explain in words but this was kind of expected. It creates a sense of animation like https://easings.net/#easeOutBack (hover over the graph)
