### ISSUE TITLE
[❗Bug]: `pnpm` will resolve `v1.0.0-beta.6` to `v1.0.0-draft.1`

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/vitepress#2670]
### Describe the bug

This only happens to `pnpm`. `npm` is fine.
I've no idea about this, can you please have a look?
***Note: it always resolve to `v1.0.0-draft.1` with or without `lockfile`***

### Reproduction
![Snipaste_2023-07-23_02-48-18](https://github.com/vuejs/vitepress/assets/45784210/f169d655-c1db-47b3-8126-fe278361dfee)

![Snipaste_2023-07-23_02-42-28](https://github.com/vuejs/vitepress/assets/45784210/359e2085-97fb-4444-b651-9ea4d993bf35)

### Expected behavior

Resolve to `v1.0.0-beta.6`

### System Info

```sh
N/A
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/pnpm/pnpm/issues/6463

**Comment by xsjcTony** [comment]
![Snipaste_2023-07-23_02-51-45](https://github.com/vuejs/vitepress/assets/45784210/c01599ec-6559-4d5b-a1cb-3605ff550ef1)
It suddenly works now.🤯

**Comment by xsjcTony** [comment]
@brc-dd sorry for pinging, as this is a `pnpm` issue, I've read through the issue, however, I'm not a fan of removing `^` or using `@latest`. Generally I use `npm-check-updates` regularly to update packages.

From my limited understanding to that issue, I can't really figure out why the same `^1.0.0-beta.6` is not working at first but suddenly can be resolved to the correct version minutes later.... It would be really helpful to me if you can give a brief explanation on this.. but yeah, if it's way too complex, please just ignore me. Thanks❤

**Comment by brc-dd** [comment]
Just create a `.npmrc` file in your project root with this:

```
resolution-mode=highest
```

Then it will use the highest matching version consistently. 

---

> I can't really figure out why the same `^1.0.0-beta.6` is not working at first but suddenly can be resolved to the correct version minutes later.

Not sure, but maybe try updating your pnpm version. During clean installations it should work fine (IG that was fixed in some pnpm version).
