### ISSUE TITLE
 Cannot read properties of undefined (reading '_s')

### ISSUE THREAD

**Issue by niefz** [vuejs/vitepress#2672]
### Describe the bug

When I run "vitepress preview" after executing "vitepress build" for packaging, the error message "Cannot read properties of undefined (reading '_s')" is prompted：
![image](https://github.com/vuejs/vitepress/assets/17262357/2e952e3a-028f-4439-8417-fd8dfc8ea6a0)
After debugging, i is a reference to Pinia, but it is undefined here.

### Reproduction

vitepress config:

```js
// https://vitepress.dev/guide/custom-theme
import { h } from 'vue';
import Theme from 'vitepress/theme';
import { createPinia } from 'pinia';
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';

import './style.css';

export default {
  ...Theme,
  Layout: () => {
    return h(Theme.Layout, null, {
      // https://vitepress.dev/guide/extending-default-theme#layout-slots
    });
  },
  enhanceApp({ app, router, siteData }) {
    const store = createPinia().use(piniaPluginPersistedstate);

    app.use(store);
  },
};
```

### Expected behavior

it can operate normally in the production environment.

### System Info

```sh
dependencies

"pinia": "~2.1.4",
"pinia-plugin-persistedstate": "~3.1.0",

devDependencies

"vitepress": "~1.0.0-beta.5"
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Refer this example: https://stackblitz.com/edit/vite-a3mv97?file=docs/.vitepress/theme/index.ts,docs/counterStore.ts,docs/index.md,docs/ssrStorage.ts
