### ISSUE TITLE
where is the Internationalization demo

### ISSUE THREAD

**Issue by 52javascript** [vuejs/vitepress#2675]
### Describe the bug

the website document about Internationalization  is too simple, could you provide a demo

### Reproduction

the website document about Internationalization  is too simple, could you provide a demo

### Expected behavior

the website document about Internationalization  is too simple, could you provide a demo

### System Info

```sh
the website document about Internationalization  is too simple, could you provide a demo
```

### Additional context

the website document about Internationalization  is too simple, could you provide a demo

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jiazengp** [comment]
@52javascript你可以参考一下我这个仓库~ <http://github.com/kongying-tavern/docs>
