### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by Richard-08** [vuejs/vitepress#2678]
### Describe the bug

Content is duplicated.
Console error: Hydration completed but contains mismatches. framework.f2e19bd8.js:1:36420

HTML auto minify disabled. 
My config:
`export default defineConfig(async ({ mode }) => {
  return {
    plugins: [MarkdownTransform()],
    build: {
      minify: false,
    },
    resolve: {
      alias: {
        "@": fileURLToPath(new URL("../src", import.meta.url)),
      },
    },
  };
});`

### Reproduction

![Снимок экрана от 2023-07-25 16-44-17](https://github.com/vuejs/vitepress/assets/56265698/441e221e-5fd0-4b71-9a02-9d38cc3a525b)

### Expected behavior

Locally in preview mode works fine

### System Info

```sh
Dependencies:

"vue": "^3.2.45",
"vite": "^4.0.0",
"vitepress": "^1.0.0-beta.6",
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please share a minimal reproducible example. If locally `vitepress preview` is working fine. The issue is probably with your hosting setup.

**Comment by Big-Cake-jpg** [comment]
Same issue, this is the repository.
https://github.com/GlobeMC/crashmc.com
