### ISSUE TITLE
NavBar is transparent

### ISSUE THREAD

**Issue by leeoocca** [vuejs/vitepress#268]
**Describe the bug**
The NavBar is transparent and page content makes it difficult to read when scrolling.

**To Reproduce**

- Scroll the page on https://vitepress.vuejs.org/ and look at the NavBar.

**Expected behavior**
The NavBar should have an opaque background to make it easy to read even when scrolling the page.

**System Info**
- https://vitepress.vuejs.org/ instance

**Additional context**
Perhaps changing the `background-color` to a theme variable could do the trick.
https://github.com/vuejs/vitepress/blob/cee0b400d95b610fa47ea79007e03221a140084f/src/client/theme-default/components/NavBar.vue#L39

**Comment by ydcjeff** [comment]
Fixed in #264
