### ISSUE TITLE
Hide JS-dependent features when JS disabled

### ISSUE THREAD

**Issue by Pandapip1** [vuejs/vitepress#2680]
### Is your feature request related to a problem? Please describe.

Many visual bugs appear when JS is turned off. The search and the three-bar navigation menu toggle don't work. These should be hidden if JS is turned off.

### Describe the solution you'd like

The following code (must be in <body> tag) can be used to create a CSS style for objects that require JavaScript:

```
<noscript>
    <style>
        .yesscript {
            display: none !important;
        }
    </style>
</noscript>
```

It should then be added to the search menu, and the three bar navigation open menu.

Ideally, the three-bar navigation menu should also not require JS.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Default theme is not meant to support MPA mode or browsers with JS disabled. Only the following are supported by VitePress: 

Chrome >= 88
Edge >= 88
Safari >= 14
Firefox >= 78
Opera >= 74

**Comment by Pandapip1** [comment]
> Default theme is not meant to support MPA mode or browsers with JS disabled. Only the following are supported by VitePress:

If I opened a PR, would you accept it?

**Comment by brc-dd** [comment]
> If I opened a PR, would you accept it?

Having that no script thing doesn't make much sense to me. Most of the features of the default theme will be hidden if that's enabled, e.g. navbar/sidebar, return to top, outline, last updated, appearance toggle, ...

**Comment by Pandapip1** [comment]
> Having that no script thing doesn't make much sense to me. Most of the features of the default theme will be hidden if that's enabled, e.g. navbar/sidebar, return to top, outline, last updated, appearance toggle, ...

Yes, that would be the case. I believe it makes more sense for them to be hidden than non-functional.
