### ISSUE TITLE
默认主题添加组件使用 bootstrap 样式没有预期

### ISSUE THREAD

**Issue by ygqygq2** [vuejs/vitepress#2683]
### Describe the bug

1. 组件中 style scoped 使用了 bootstrap，某些 class 样式出不来，比如下面  `rounded`；
![image](https://github.com/vuejs/vitepress/assets/17672440/881a7fe7-00e0-48d2-9aa7-45ae493c816e)

2. 如果在 vue 组件的 script 导入 bootstrap，则会影响默认主题的样式，比如下面标题
![image](https://github.com/vuejs/vitepress/assets/17672440/f38d6770-e62b-48b1-a836-f7a6580c9bb3)

3. 不管是使用 slots 还是使用全局注册组件，都是一样的问题；

### Reproduction

默认主题结合 bootstrap 很容易重现。

### Expected behavior

我希望在 vitepress 的组件中使用 bootstrap 快速开发。

### System Info

```sh
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 4.30 GB / 7.72 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.5.0 - ~/.nvm/versions/node/v19.5.0/bin/node
    npm: 9.6.4 - ~/.nvm/versions/node/v19.5.0/bin/npm
    pnpm: 8.6.9 - ~/.local/share/pnpm/pnpm
  npmPackages:
    vitepress: 1.0.0-beta.6 => 1.0.0-beta.6
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This is not technically a bug. Bootstrap has its own set of styles that will conflict with ours.
