### ISSUE TITLE
✨Feature: Re-generate aside content when visbility of anchor headings change

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/vitepress#2686]
### Is your feature request related to a problem? Please describe.

Imagine the use case:

There are some settings on the left side (just like `vuejs.org`'s API style switch), but I want it to show/hide some `h2` or `h3`, or say, those heading elements which will be in the aside.

By wrapping entire `h2` or `h3` parts by a `<div>` and using classes on the root element to control their visibility based on the value of settings. However, currently, the aside content won't update in this case.

---

If you don't want this to be part of the default theme, please inform me and close this issue, Thanks.

### Describe the solution you'd like

I'm here to gather whether you want this to be a feature in the default theme, as I already implemented it by overriding internal files (that's a bit frustrating honestly) and it's working well for me, so I can raise the MR if you would like to accept this feature as part of the default theme.

My implementation in high-level:
1. In those aside components (i.e. `VPDocAsideOutline.vue`, `VPDocOutlineDropdown.vue` and `VPLocalNav.vue`
2. Using `IntersectionObserver` to observe the visibility against root (`<html>`)
3. Once change is detected, regenerate the headers and cleanup + apply step 2 again.

Please feel free to advise if you have a better approach.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by xsjcTony** [comment]
As I can see, https://vuejs.org is doing the same thing when switching between composition-api and option-api, any idea how it's achieved?

**Comment by brc-dd** [comment]
Using IntersectionObserver is considerably performance heavy operation. How are you controlling the visibility of your elements? Using some prop + `v-if` should trigger the header regeneration 👀

**Comment by xsjcTony** [comment]
@brc-dd Ah yeah, using `v-if` will cause the VNode of content to change hence triggering `onContentUpdated` to update the header, however, I'm using `display: none` to hide content, by wrapping the entire block into a `div`, based on class name on the root element. The reason is that way I can control hide/show based on normal HTML syntax instead of `vue` specified (e.g. `v-if`), since my team are all React developer and I'm making things easier for them. So yeah you are right, as I don't think that's needed in the core, since `v-if` can absolutely do the thing

**Comment by xsjcTony** [comment]
@brc-dd I've tried to use `v-if` for my case, however it seems not working for me because my `v-if` condition requires reading `document.documentElement.dataset`. Any suggestions?

**Comment by brc-dd** [comment]
You seem to be directly writing stuff in template. Can you share relevant code?

**Comment by xsjcTony** [comment]
Nah I'm dumb. Vue's conditional rendering works a little bit differently from React. I need to define something in setup first.

**Comment by xsjcTony** [comment]
@brc-dd Sorry if this is a dumb question, but I just want to get it working with `v-if` so I can close this one. How can I watch for an attribute change? e.g. watch change for `document.documentElement.dataset` in my case.

Using `watch()` with a `getter` seems has no effect. Do I have to use `MutationObserver` to achieve that?

**Comment by brc-dd** [comment]
Yeah. `document.documentElement.dataset` isn't reactive, create a ref and a mutation observer. update that ref's value in mutation observer, use that ref in v-if

**Comment by brc-dd** [comment]
Why do you need reading data from data-* attributes though? If you're just doing some settings toggle thing, then you should be able to directly store a ref there and use provide/inject or global properties 👀

**Comment by xsjcTony** [comment]
Because the derived boolean result is not straight forward and not the same for each page, and still some place needs that to control hidden styles. I worked it out, so I'm happy to close this ticket if you want. Thanks a lot for the help.
