### ISSUE TITLE
[search] add option to enable detailed view by default

### ISSUE THREAD

**Issue by jcstein** [vuejs/vitepress#2690]
### Is your feature request related to a problem? Please describe.

This would add support for [FlexSearch](https://github.com/nextapps-de/flexsearch), which is what is used by default in [Nextra.js](https://nextra.site). I am currently choosing between either VitePress or Nextra, with a preference toward VitePress. However, the details from the search that show up on Nextra are preferable as opposed to just the title of a page.

With minisearch:
<img width="817" alt="Screenshot 2023-07-27 at 11 31 49" src="https://github.com/vuejs/vitepress/assets/46639943/92a5e2aa-bc0f-409d-9e73-1e899b43440f">

With FlexSearch:
<img width="820" alt="Screenshot 2023-07-27 at 11 32 04" src="https://github.com/vuejs/vitepress/assets/46639943/62ed14ba-ef4d-4943-b010-75fbf6e8abeb">

### Describe the solution you'd like

Add support for FlexSearch

### Describe alternatives you've considered

Using Nextra, but I would like to use VitePress

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
toggle that button on top right

**Comment by jcstein** [comment]
omg thank you @brc-dd 😄

**Comment by jcstein** [comment]
any idea if there is a setting to toggle on this by default?

<img width="1822" alt="Screenshot 2023-07-27 at 11 42 26" src="https://github.com/vuejs/vitepress/assets/46639943/6d686d17-416a-4ea5-bd7a-7dbd561c8ede">

**Comment by brc-dd** [comment]
Ah, not yet. PRs are welcome.
