### ISSUE TITLE
Feature groups

### ISSUE THREAD

**Issue by ThePlenkov** [vuejs/vitepress#2699]
### Is your feature request related to a problem? Please describe.

In case if we want to build kind of a portal on top of vitepress - we may have quite many top-level features.

### Describe the solution you'd like

It would be great if we could introduce some Groups/Sections for features that's how they can be rendered in kind of a dashboard way. Here is just an example from the tool I work with. OF course we're not going to bild business portal with apps  = but it's more about approximate outlook of the home page with sections
![image](https://github.com/vuejs/vitepress/assets/6381507/3f66ebec-f829-4718-a4a3-aa03a8ce34b8)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This might be quite specific to your use case. Can't you simply write a component for this? The default theme is oriented towards docs-like sites and I don't think many people need something like this on their home page.

**Comment by ThePlenkov** [comment]
Indeed, you're right. Going for an own component is the case - but in this case the others will not benefit of it. For a dedicate library/component indeed having few features is enough - but for enterprise or large products/teams having more than 10 blocks may make the page not readable/not enough structured.  
Again - may be my image is confusing - because it has some charts on it - but I was mostly thinking of having multiple blocks grouped somehow into sections.

Let's try to find more examles:
- [Github Pages](https://docs.github.com/en)
- [Microsoft Docs](https://learn.microsoft.com/en-us/java/)
we may see here some blocks with list of links inside:
![image](https://github.com/vuejs/vitepress/assets/6381507/ab394702-096e-42f2-9eeb-44bac9666a5c)
but from the other side we also see sections which help to segregate those blocks semantically and not to mix them together

**Comment by brc-dd** [comment]
Ah, that's the index page feature (x-ref: #794). Example can be some page like https://vuejs.org/api/ having a bunch of links to different stuff.

**Comment by ThePlenkov** [comment]
So having something like
```
sections:
 - title: Getting started
   features:
     - ...
- title: Advanced scenarios:
     features: 
       - ...
 ```
could be already enough to break features into sections and each section may have it's own anchor too

**Comment by ThePlenkov** [comment]
yes - that will also work!
