### ISSUE TITLE
Moving VitePress' Node API as ESM only

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#2703]
Vite might be removing/deprecating it's CJS API is near future (https://github.com/vitejs/vite/discussions/13928) which will impact VitePress' CJS API as well.

**Edit: Let's wait on discussion at Vite's side to conclude and we will try to follow their footsteps. But, it is recommended to use ESM APIs for anything new you might be building.**

~~Most of the projects already appear to be using the import syntax. A quick [GitHub code search](https://github.com/search?q=/require%5C%28%5Cs*%5B%22'%5Dvitepress%5B%22'%5D/+NOT+is:fork&type=code) shows about 20 public projects doing `require('vitepress')`. Exploring more, over half of them appear to be on `vitepress@0.x` branch. Leaving less than 10 projects that might need minor refactoring.~~

`import` syntax in `config.js` file when `"type": "module"` is not specified in nearest package.json also uses the CJS build. Might be difficult to estimate the impact. But for most of the cases where people are using import without type module or mjs/mts extension the migration should be straight forward -- either change the file extension or project level type.

Migration:

```ts
// use .mjs/.mts file extension if can't use `"type": "module"`

// change
const { defineConfig } = require('vitepress')

module.exports = {/*...*/}

// to
import { defineConfig } from 'vitepress'

export default {/*...*/}

// or since it's just a type helper simply do something like this

/** @type {ReturnType<typeof import('vitepress').defineConfig>} */
module.exports = {/*...*/}

// change
const { createMarkdownRenderer } = require('vitepress')
      // ^ or any async API like createServer, build, resolveConfig, resolveSiteData

async fn() {
  const md = await createMarkdownRenderer(/*...*/)
}

// to
async fn() {
  const { createMarkdownRenderer } = await import('vitepress')
  const md = await createMarkdownRenderer(/*...*/)
}
```

---

~~For maintainers, we will need to use [jiti](https://github.com/unjs/jiti) for the CLI and remove CJS stuff from rollup config.~~

CLI won't need any changes, it's already CJS compatible and uses ESM output. Only rollup related changes need to be done.

Rollout plan:

Let's log a warning for now if someone `require`'s the package. We can drop the CJS API by RC.

/cc @kiaking @zonemeen

**Comment by zonemeen** [comment]
I think this kind of plan works.

**Comment by benmccann** [comment]
An update from https://github.com/vitejs/vite/discussions/13928 - we have PRs out now to migrate all projects to ESM except for Vitepress and Storybook
