### ISSUE TITLE
Unable to build the docs project when importing a module from node_modules

### ISSUE THREAD

**Issue by shibisuriya** [vuejs/vitepress#2709]
### Describe the bug

I have a npm package called @declarative-gridstacks/react, it exports a bunch of react components (compiled with babel-loader obviously), I import these modules use them in vitepress it words good in dev mode... But when I actually try to build the vitepress project, it doesn't build.

### Reproduction

```jsx
import {
  GridstackContainer,
} from "@declarative-gridstack/react"; // This is in node_modules.

const Component = () => {
return <GridstackContainer />
}

export default Component;
```

// Import this code in 
```vue
<div ref="el" />

<script setup>
import { createElement } from 'react'
import { createRoot } from 'react-dom/client'
import { ref, onMounted } from 'vue'
import Simple from '../components/simple/Simple.jsx'

const el = ref()
onMounted(() => {
  const root = createRoot(el.value)
  root.render(createElement(Simple, {}, null))
})
</script>
```

### Expected behavior

The project should build... It works fine in dev mode...

### System Info

```sh
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.16 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.1/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 15.6
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by shibisuriya** [comment]
$ vitepress build
  vitepress v1.0.0-beta.7
- building client + server bundles...
"GridstackContainer" is not exported by "../react/dist/main.js", imported by "frameworks/react/components/simple/Simple.jsx".
file: /Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/packages/docs/frameworks/react/components/simple/Simple.jsx:3:2
1: import React, { useState } from "react";
2: import {
3:   GridstackContainer,
     ^
4:   GridstackItem,
5: } from "@declarative-gridstack/react";
✖ building client + server bundles...
build error:
RollupError: "GridstackContainer" is not exported by "../react/dist/main.js", imported by "frameworks/react/components/simple/Simple.jsx".
    at error (file:///Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at Module.error (file:///Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/node_modules/rollup/dist/es/shared/node-entry.js:13604:16)
    at Module.traceVariable (file:///Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/node_modules/rollup/dist/es/shared/node-entry.js:14029:29)
    at ModuleScope.findVariable (file:///Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/node_modules/rollup/dist/es/shared/node-entry.js:12547:39)
    at FunctionScope.findVariable (file:///Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at ChildScope.findVariable (file:///Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at Identifier.bind (file:///Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/node_modules/rollup/dist/es/shared/node-entry.js:8267:40)
    at CallExpression.bind (file:///Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
    at CallExpression.bind (file:///Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/node_modules/rollup/dist/es/shared/node-entry.js:9833:15)
    at CallExpression.bind (file:///Users/shibisuriya/Desktop/personal-projects/declarative-gridstack/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Ran target build for project @declarative-gridstack/docs (2s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

This is the error that it generates. When I use this lib outside vitepress it works fine.

**Comment by brc-dd** [comment]
That package doesn't seem to have any ESM export. Try adding something like this in your `.vitepress/config`:

```ts
  vite: {
    ssr: {
      noExternal: ['@declarative-gridstack/react']
    }
  }
```

**Comment by shibisuriya** [comment]
Doesn't work... It is build as an umd module btw...

**Comment by shibisuriya** [comment]
import { defineConfig } from "vitepress";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  base: "/declarative-gridstack/",
  title: "declarative-gridstack",
  description: "Use gridstack.js with ease.",
  vite: {
    ssr: {
      noExternal: ["@declarative-gridstack/react"],
    },
  },
  I have added like this...

**Comment by brc-dd** [comment]
Ah, can you share this via StackBlitz https://vitepress.new ? It'll be easier for me to debug there.

**Comment by shibisuriya** [comment]
https://stackblitz.com/edit/vite-ci2uus?file=docs%2Findex.md I have added the code... But the vitepress says there is no file like that in the project :(

**Comment by brc-dd** [comment]
Ah those files are in wrong directory:

<img width="201" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/a8a59a41-7500-4089-8084-55adf883f338">

**Comment by shibisuriya** [comment]
Oh sorry... Can you add a dot... The project is working fine in dev mode... 
build the project it is not building for somereason...

**Comment by brc-dd** [comment]
Setting that `vite.ssr.noExternal` technically fixes the issue you had originally. But the build won't succeed because that package is using `self` with UMD output which is undefined on Node environments. Setting `output.globalObject` to `this` in your webpack config for that module should fix that issue (https://github.com/webpack/webpack/issues/6784, https://github.com/webpack/webpack/issues/6522). But even then the output generated by webpack is not SSR compatible and will throw errors like `document is not defined` due to some code like `(r.b = document.baseURI || self.location.href),`.  I'm not sure if we can anything at vitepress level. Since you're the author of that package, I'd recommend refactoring your build setup to generate proper ESM code, or use rollup/tsup instead of webpack which will correctly generate the bundles.
