### ISSUE TITLE
outDir logic is too confusing now

### ISSUE THREAD

**Issue by ThePlenkov** [vuejs/vitepress#2716]
### Describe the bug

I'm trying to build a site in a custom folder and noticed several issues.

My site is located in the folder `sites/mysite.com`.

When I run following command in the root of my project:
```
npx vitepress build  sites/mysite.com --outDir public
```

Instead of writing to ${workplaceFolder}/public it actually still resolves outDir relatively to sites/mySite.com so to make it working I need to use currently `../../public` or `$(pwd)/public` which are both too confusing because from CLI call it looks like i write to something above.

My suggestion is that relative path needs to be resolved relatively to cwd, not a docs folder.

But even like that what I find even more strange - this setting only impacts assets, while actual html pages are still located in the .vitepress/dist folder. Do you know how to fix that too? THanks!

### Reproduction

Just create a nested project like sites/test.site and try to build it to a public/test.site folder in your root.

### Expected behavior

- command like `vitepress build  path/to/my/site --outDir public` resolves to a public folder in your root - not in the package.
- html pages should be also built respectively to outDir parameter

### System Info

```sh
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 11.75 GB / 15.34 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.3.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    pnpm: 8.6.6 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    vitepress: ^1.0.0-beta.6 => 1.0.0-beta.6
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Specifying `outDir` from command line is not supported. The way you're invoking, it passes that as vite server options not vitepress config.

**Comment by ThePlenkov** [comment]
Well, in this case documentation may be confusing too, because I just follow: https://vitepress.dev/reference/cli#vitepress-build

![image](https://github.com/vuejs/vitepress/assets/6381507/a1c32780-03ff-4558-be99-e6b95bf0109e)
 So do you want to say that it must not be used at all? Thanks!

**Comment by brc-dd** [comment]
Ah, the support was added in 22047f3 . The second one is a bug then. Everything should be generated inside `outDir`. Regarding resolution from cwd vs project root, it's consistent across all the config: https://vitepress.dev/reference/site-config#outdir
