### ISSUE TITLE
Invalid search for topic Settings ！！！

### ISSUE THREAD

**Issue by bhabgs** [vuejs/vitepress#272]
**Describe the bug**
The theme is set as follows

``` js
{
  ...,
  title: 'Vite vui',
  base: '/vite-vui-docs/',
  themeConfig: {
    repo: 'bhabgs/vite-vui',
    search: true, // here
    sidebar: {
      '/': [
        {
          text: 'vui',
          children: [
            { text: '介绍', link: '/' },
            { text: '日志', link: '/components/log' },
            { text: 'Button', link: '/components/button/' },
            { text: 'Layout', link: '/components/layout/' },
            { text: 'contextmenu', link: '/components/contextmenu/' },
          ],
        },
        {
          text: 'vuu',
          children: [
            { text: '介绍', link: '/vuu/' },
            { text: '日志', link: '/vuu/log' },
            { text: '某个功能', link: '/vuu/any' },
          ],
        },
      ],
    },
    author: 'bhabgs',
    nav: [
      { text: '首页', link: '/' },
      { text: '分类', link: '/tags' },
    ],
  },
  dest: 'public',
}
```

**To Reproduce**
[to view](https://github.com/bhabgs/vite-vui/tree/master/docs)
![image](https://user-images.githubusercontent.com/19221378/112778357-f374f080-9076-11eb-8d1b-6d00493084a6.png)

**Expected behavior**
show search box.
![image](https://user-images.githubusercontent.com/19221378/112778251-adb82800-9076-11eb-9aaf-31a61e42aec7.png)

**System Info**
- vitepress version: 0。12.2
- vite version: 2.0.3
- Node version: 14*
- OS version: 11.2.2

**Comment by hafdon** [comment]
I also have this problem. System info:
"vitepress": "^0.20.10"
vite/2.7.9 darwin-x64 node-v16.1.0
ProductName:	macOS
ProductVersion:	12.1

**Comment by kiaking** [comment]
We don't have `search: true` option.
