### ISSUE TITLE
how to make the title show just "Title" on home instead of "Title | Title"

### ISSUE THREAD

**Issue by jcstein** [vuejs/vitepress#2729]
### Describe the bug

not a bug, but not sure how to do this! thanks

### Reproduction

the title shows as "Title | Title" on home

### Expected behavior

just show "Title"

### System Info

```sh
npx envinfo --system --npmPackages vitepress --binaries --browsers


Need to install the following packages:
  envinfo@7.10.0
Ok to proceed? (y) y

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
    Memory: 111.17 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.7.2 - /opt/homebrew/bin/npm
    pnpm: 8.6.5 - ~/.nvm/versions/node/v16.15.1/bin/pnpm
  Browsers:
    Brave Browser: 114.1.52.130
    Safari: 16.5.2
  npmPackages:
    vitepress: 1.0.0-beta.7 => 1.0.0-beta.7
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`titleTemplate: ':title'`
