### ISSUE TITLE
nav items are being shown awkwardly within my sidebar

### ISSUE THREAD

**Issue by CodyBontecou** [vuejs/vitepress#273]
**Describe the bug**
Building and serving my site displays my `nav` awkwardly within my sidebar.

**To Reproduce**
1. Clone https://github.com/CodyBontecou/blog
2. run `yarn build && yarn serve`
3. View Home and Contact within the sidebar as well as top nav

You can also view this behavior at https://cody-bontecou.netlify.app/

**Expected behavior**
I should only see Home and Contact navigation elements within the top nav.

**System Info**
- vitepress version: ^0.12.2
- vite version:
- Node version:
- OS version:

**Additional context**

You can see my config.js [here](https://github.com/CodyBontecou/blog/blob/main/blog/.vitepress/config.js). The navigation elements should never be in my sidebar in the first place. Making the duplication odd.

The sidebar + top nav look fine while running the site in dev mode.

**Comment by shockw4ver** [comment]
meet this, too...

**Comment by CodyBontecou** [comment]
> met this, too...

@shockw4ver Can you share your codebase?

**Comment by shockw4ver** [comment]
@CodyBontecou Sorry it's private, but I found the reason and created a issue #275...

**Comment by ishaqzain** [comment]
@CodyBontecou try updating the vite version to `2.1.5`, by reinstalling Vitepress packages.
![image](https://user-images.githubusercontent.com/4214621/114142067-a2011700-993c-11eb-90c4-76618b161fb2.png)

**Comment by CodyBontecou** [comment]
> @CodyBontecou try updating the vite version to `2.1.5`, by reinstalling Vitepress packages.
> ![image](https://user-images.githubusercontent.com/4214621/114142067-a2011700-993c-11eb-90c4-76618b161fb2.png)

This fixed it, thank you for the suggestions.
