### ISSUE TITLE
Bug: default theme search button background blends in with icon on mobile

### ISSUE THREAD

**Issue by import-brain** [vuejs/vitepress#2735]
### Describe the bug

The default docs theme search button background blends in with the search icon on mobile.

![IMG_2579](https://github.com/vuejs/vitepress/assets/68196762/75dd17ed-13e8-46da-86e8-28b45e0aa0d9)

### Reproduction

Go to vitepress.dev or fakerjs.dev on a mobile site

### Expected behavior

The icon itself to seem more prominent so that users can more easily tell it’s a search button on first glance- maybe no background at all?

### System Info

```sh
Apple iPhone 11
Google Chrome
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Which Chrome version are you on?

**Comment by import-brain** [comment]
I'm on the iOS 17 beta, that might be why the issue is happening on my phone

![IMG_2581](https://github.com/vuejs/vitepress/assets/68196762/564f0e52-a710-4adf-a76c-65a90bdaebc5)
![IMG_2580](https://github.com/vuejs/vitepress/assets/68196762/50ccaf7e-5090-4f60-8a04-9be61bc55f5b)

**Comment by brc-dd** [comment]
Ah, yeah. That might be the cause. Can you check internally with Faker team once if this is happening on stable iOS version for anyone?

**Comment by import-brain** [comment]
> Ah, yeah. That might be the cause. Can you check internally with Faker team once if this is happening on stable iOS version for anyone?

Sure, I'll ping them right now

**Comment by import-brain** [comment]
Hi @brc-dd ,

I checked internally with Faker team and none of them were able to replicate it on Android, iOS stable, and using multiple different browsers.

I just tried again and I can't replicate it either now 👀

I'll keep testing to see if I can get it to pop up again.

**Comment by brc-dd** [comment]
It might be a glitch actually. We already have this code to make it transparent:

https://github.com/vuejs/vitepress/blob/063b0e520a0b34db934371f56ddba212ceb3ba4c/src/client/theme-default/components/VPNavBarSearchButton.vue#L67

I also overrode the css var in 063b0e5 just to be double sure.
