### ISSUE TITLE
请教个问题，如果用vitepress写组件库文档，但是我的组件库是vue2.*的，那么还能从vuepress换成vitepress吗？因为vuepress太慢了

### ISSUE THREAD

**Issue by cyt68** [vuejs/vitepress#274]
请教个问题，如果用vitepress写组件库文档，但是我的组件库是vue2.*的，那么还能从vuepress换成vitepress吗？因为vuepress太慢了

**Comment by cyt68** [comment]
md文件里是会引入组件库组件的

**Comment by yyx990803** [comment]
vitepress 只支持引入 Vue 3 组件。
引入 Vue 2 组件的话，除非你用 Vue 2 的 global build 然后用 Vue 3 包一层再引入。
