### ISSUE TITLE
configFile parameter to specify vite.config.ts path like in Vuepress-next

### ISSUE THREAD

**Issue by TechAkayy** [vuejs/vitepress#2743]
### Is your feature request related to a problem? Please describe.

Instead of the ability to re-use the vite config of existing project when we want to leverage Vitepress, we currently have to move the vite config under the `vite` parameter of config.ts. 

This is an inconvenience and ability to retain our current Vite config file would be provide a great DX. 

### Describe the solution you'd like

Introduce a `configFile` similar to what's done in Vuepress-next, where we are able to specify the path of an existing vite config file. For Vuepress-next, please check here - https://github.com/vuepress/vuepress-next/blob/main/packages/bundler-vite/src/resolveViteConfig.ts#L25 

Vitepress previously did merge config from existing vite config file, for eg, check Pinia's docs site here - https://github.com/vuejs/pinia/tree/v2/packages/docs

That said, this request is to not bring back merging by default, and it's totally understandable why we want to extend vite config via the standard vitepress config file. 

Rather, this request is to opt-in to specify a configFile, when we want to. This will be very helpful for those who want to add vitepress to existing vite-powered Vue apps.

### Describe alternatives you've considered

Vuepress-next

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> Vitepress previously did merge config from existing vite config file, for eg, check Pinia's docs site here

VitePress does this currently too. You need to keep `.vitepress/config.ts` and `vite.config.ts` side by side (in same root) to make that work.

From the next version, you'll be able to override which vite config file to load: #2750

**Comment by TechAkayy** [comment]
Thanks bunch 👏🏾
