### ISSUE TITLE
assects img for logo dev works,build result does't work

### ISSUE THREAD

**Issue by zouyaowen** [vuejs/vitepress#2745]
### Describe the bug

the log setting dev works ,but build does't work

the code as

```
base: "./",
    head: [['link', {rel: 'icon', href: '/assets/img/logo.png'}]],
    vite: {
        assetsInclude: ['assets']
    },
    title: "FollowYourHeart",
    description: "LearningNote",
    themeConfig: {
        logo: '/assets/img/logo.png',
```

### Reproduction

the code repo :
https://github.com/zouyaowen/freewheeling

deploy address: https://freewheeling.top/

### Expected behavior

<img width="608" alt="image" src="https://github.com/vuejs/vitepress/assets/20028367/9706d233-a7ef-458a-a904-84799f25e2bd">

### System Info

```sh
System:
    OS: Linux 4.18 CentOS Linux 8 (Core)
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-26xx v4
    Memory: 1.88 GB / 3.65 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 18.16.0 - /usr/local/node-v18.16.0-linux-x64/bin/node
    npm: 9.5.1 - /usr/local/node-v18.16.0-linux-x64/bin/npm
  npmPackages:
    vitepress: ^1.0.0-beta.7 => 1.0.0-beta.7
```

### Additional context

no

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Move that assets folder to public directory.
