### ISSUE TITLE
Build hook buildEnd rendering $frontmatter in generated template.

### ISSUE THREAD

**Issue by CodyBontecou** [vuejs/vitepress#2748]
### Describe the bug

HTML rendered within the `buildEnd` hook contain `{{ $frontmatter.title }}` rather than the actual title contained with the frontmatted metadata. 

### Reproduction

Here is my implementation:
https://github.com/CodyBontecou/blog/commit/cd40a9d79f9954bf7f64fd329b0ee74b06c2dadc#diff-a2c09d222e870efa333dc7e96fbe9b10bc9b289553da72641eb52f7605a2ed51

### Expected behavior

I expect the `buildEnd` hook to have the template `$frontmatter` variables to be the value of what it's calling, not of `{{ $frontmatter.title }}`.

### System Info

```sh
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 128.91 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 9.6.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.2
  npmPackages:
    vitepress: ^1.0.0-alpha.44 => 1.0.0-beta.7
```

### Additional context

You can see the generated file at https://codybontecou.com/feed.rss.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by CodyBontecou** [comment]
I ended up hacking together this implementation: https://github.com/CodyBontecou/blog/commit/83b5721b377ec3228d072fa76528dae7607c1609.

**Comment by brc-dd** [comment]
createContentLoader does not render Vue. It only renders markdown. `{{  ... }}` is vue syntax. That html is not the final html. For final html you'll need to something like store the data in array in transformHTML and then call feed generator in buildEnd.
