### ISSUE TITLE
Add `displaySidebarNav` prop to themeConfig.

### ISSUE THREAD

**Issue by shockw4ver** [vuejs/vitepress#275]
**Is your feature request related to a problem? Please describe.**
Under `build` command.

If I defined nav in themeConfig, the NavLinks component would show both on NavBar and Sidebar.
And I found the NavLinks's been put into Sidebar just on purpose, but looks ugly...

However, everything are just fine in dev mode.

I don't if this a bug or the design is so...

**Describe the solution you'd like**
But if the design is so and the style is WIP, maybe add a themeConfig prop to control this?
Like:
```js
module.exports = {
  themeConfig: {
    displaySidebarNav: false
  }
}
```

**Comment by kiaking** [comment]
This is not relevant anymore in VitePress Next theme. Nav items are excluded from sidebar and has its own hamburger menu.
