### ISSUE TITLE
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module ***  needs an import assertion of type "json"

### ISSUE THREAD

**Issue by brolnickij** [vuejs/vitepress#2756]
### Describe the bug

I am encountering an error when trying to load the vitepress config. The error message specifically points to a missing import assertion for a JSON module:

```
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///Users/brolnickij/Desktop/@vm/ui/node_modules/@vm/icons/dist/icons.json" needs an import assertion of type "json"
```

I have already attempted to import the JSON file with the proper assertion as shown in my code:

```
import * as unpluginVmIconPack from '@vm/icons' assert { type: 'json' }
```

However, the error persists. I have verified the path and ensured that the referred file is indeed a JSON file, and im using the supported Node.js version for the import assertions.

### Reproduction

```ts
// index.mts
import * as unpluginVmIconPack from '@vm/icons' assert { type: 'json' } // or external package with icons in json
import { defineConfig } from 'vitepress'
import unpluginIcons from 'unplugin-icons/vite'


export default defineConfig({  
  vite: {
    plugins: [
      unpluginIcons({
        customCollections: unpluginVmIconPack
      })
    ]
  }
})
```

### Expected behavior

I expect the configuration to load without any errors, and the JSON import assertion to work as intended.

### System Info

```sh
System:
  OS: macOS 13.5
  CPU: (8) arm64 Apple M1 Pro
  Memory: 367.27 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v20.3.1/bin/yarn
  npm: 9.8.1 - ~/.nvm/versions/node/v20.3.1/bin/npm
  pnpm: 8.2.0 - ~/.nvm/versions/node/v20.3.1/bin/pnpm
Browsers:
  Chrome: 115.0.5790.170
  Safari: 16.6
npmPackages:
  vitepress: 1.0.0-rc.3 => 1.0.0-rc.3
```

### Additional context

Everything worked before `.rc` version

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I'm able to import json files without import assertion too. Also, you probably don't need to do `import *` -- `import unpluginVmIconPack from '...'` should work. Can you share some public package if this happens with them?

**Comment by brolnickij** [comment]
@brc-dd 

I have created a zip archive containing the dump of the `@vm/icons` library from my `node_modules` directory, which seems to be causing the problem.

You can download the [icons.zip](https://github.com/vuejs/vitepress/files/12293991/icons.zip) file to further inspect the issue.

P.S. Please let me know if you need any additional information or if there's anything else I can do to help.

**Comment by brc-dd** [comment]
I'm not sure what is the root cause. Use `require` syntax for now:

```ts
import { createRequire } from 'node:module'
import unpluginIcons from 'unplugin-icons/vite'
import { defineConfig } from 'vitepress'

const require = createRequire(import.meta.url)
const unpluginVmIconPack = require('@vm/icons')

export default defineConfig({
  vite: {
    plugins: [
      unpluginIcons({
        customCollections: unpluginVmIconPack
      })
    ]
  }
})
```

Seems to work fine:

<img width="780" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/65ea790b-3bf4-4092-838f-1a0bb66c4695">

**Comment by brc-dd** [comment]
Sorry, had to revert back to Vite 4. So this issue will still be there for some time. Keep using the createRequire workaround for now. It's fixed in Vite and will automatically be fixed here once we start using Vite 5.
