### ISSUE TITLE
Unable to assign local Component to Layout Slot 

### ISSUE THREAD

**Issue by PrimalOutshoot** [vuejs/vitepress#2757]
My issues.
1. I am unable to locally assign my registered components within markdown files into Slots *without* creating a Custom Layout.
2. I have registered my Component in Vitepress, and created Custom Layouts, and it is not  loading in my markdowns YAML as layout: CustomLayout. It loads fine when I utilize it in index.js/config.js
3. I am unable to get my Local $frontmatter to be read by my Global components - for that page only - without mental gymnastics related to JS/Vue, as a work around to 2, as a work around to 1.

What I would like to do to is append my Infobox Component to the "Aside" box, but it has been challenging for me due to limited documentation and resources.

I would like to understand each of the methods
**For Method 1** - In `markdown.md` I am able to use my registered  `<component />`  and even pass frontmatter to it or props to it, but I am unable to take that component and say - ok - I want you to appear in the Aside slot. Using the methods described in the documentation do not work when it is instantiated within markdown.md. What I am trying to do here is set up `Local Layout Slots` - that are only for that specific page or categories of pages. Using `layout: LayoutSlot` does not work as a workaround.

**For Method 2** -  I would also like to actually know how to create Custom Layouts with more detail, for example adding `<content />`  to a template, disabled the sidebar and navigation information, and I have not figured out how to add the <sidebar /> or navigation, or other built-in theme components -  back in the same way I was able to do `<content />` . I don't understand how to style the CSS in the content section only of my local markdown.md files*(fully)  or why when following the same structure as the documentation by `layout: CustomLayout` in Yaml Markdown will not activate the same way it does when I register it globally - even when nothing has changed about the code itself. I understand there is documentation for these things, but the documentation is not clear enough or makes some basic assumptions about knowledge that extend beyond what the documentation explains.

**For Method 3** - Lets say I have a `markdown.md` and I have set up some `$frontmatter`.  I have also set up a `Layout Slot`, that appends Globally (even though my goal is Local application only) - I am unable to get the Global Components to read the `$frontmatter` from the local markdown pages, and workarounds to pass the `$frontmatter` as props to the global component do not work - it only ever passes to local instances of the component. Is what I want to do possible (I know it is because of `outline.js` but upon inspection of outline.js the code it uses is awfully complicated for my brain - and with $frontmatter so easy, I would think why wouldn't  it be able to pass to the global component for that page). I am sure there is something I am missing, but when reading documentation on how to access frontmatter, it didn't cover this topic.

I have no idea if these are bugs or user errors, or a combination. But I do know 4-5 days in now and I need some help. Thank you.

**Comment by brc-dd** [comment]
Honestly, too much text! You're getting confused between `layout` frontmatter property and `Layout` in theme. You probably wanna do something like this: https://stackblitz.com/edit/vite-bqcchj

**Comment by PrimalOutshoot** [comment]
Thank you for the information provided, it was indeed helpful. While it is helpful, I'm still encountering some ambiguities about the unique terminology and component workflow in Vitepress and Vue. It's a different way compared to what most platforms like Jekyll, Wordpress, and other widely used SSGs offer in terms of accessible resources and examples. While I appreciate Vitepresses simplicity - working out of the box - as is - , it appears to be quite opinionated when it comes to customization, where there is a strict adherence to the conventions and workflows set up by Vitepress.

What could assist users like myself, especially those new to Vitepress, is a comprehensive starter theme that provides examples or scaffolds similar to what Underscores (WP), Bones(WP) offer, and a more comprehensive documentation. A detailed guide or documentation with a working example of customized template creation workflow would be particularly useful - and would absolutely absolve much of the confusion new users facing similar challenges in navigating the Vitepress ecosystem, have. Again, thank you for your time and I appreciate any useful resources or advice that could help resolve this issue. I am happy to devour more links, resources, and examples such as the one you gave, that would add more clarity for me.
