### ISSUE TITLE
vitepress@1.0.0-rc.4

### ISSUE THREAD

**Issue by z040707** [vuejs/vitepress#2759]
### Describe the bug

"vitepress" resolved to an ESM file. ESM file cannot be loaded by `require`.

### Reproduction

无

### Expected behavior

up

### System Info

```sh
node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:27:  
      1373 │         let result = await callback({

  The plugin "externalize-deps" was triggered by this import

    docs/.vitepress/config.js:1:332:
      1 │ ...docs/.vitepress/config.js";import { defineConfig } from "vitepress";
```

### Additional context

无

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jerrywu001** [comment]
same issue

**Comment by z040707** [comment]
vitepress@1.0.0-beta.7 ok

**Comment by allen0234** [comment]
I thin the note info in user guide will help: https://vitepress.dev/guide/getting-started#installation
>VitePress is an ESM-only package. Don't use require() to import it, and make sure your nearest package.json contains "type": "module", or change the file extension of your relevant files like .vitepress/config.js to .mjs/.mts. Refer Vite's troubleshooting guide for more details. Also, inside async CJS contexts, you can use await import('vitepress') instead.

**Comment by z040707** [comment]
ok
