### ISSUE TITLE
升级最新版本运行后报错：VPImage.vue:10 Uncaught (in promise) ReferenceError: defineOptions is not defined     at setup (VPImage.vue:10:1)

### ISSUE THREAD

**Issue by gaojianghua** [vuejs/vitepress#2761]
### Describe the bug

VPImage.vue:10 Uncaught (in promise) ReferenceError: defineOptions is not defined
    at setup (VPImage.vue:10:1)

问题出现在logo属性，不使用logo属性则不报这个错误，使用就会有这个报错，请问怎么解决

### Reproduction

从以前的旧版本升级到rc4后运行就会这样

### Expected behavior

如何解决这个问题

### System Info

```sh
mac studio  google浏览器
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You probably are on older version of vue. Can you upgrade it to v3.3+ if you've manually installed vue.
