### ISSUE TITLE
vitepress运行报错PM [vitepress] Internal server error: Invalid end tag.

### ISSUE THREAD

**Issue by gaojianghua** [vuejs/vitepress#2762]
### Describe the bug

但是实际我找不到这个原因在哪
![image](https://github.com/vuejs/vitepress/assets/61684763/3669c92c-b680-4f2d-b6f1-096c6b771110)
![image](https://github.com/vuejs/vitepress/assets/61684763/d0348f8e-ea70-4c29-8171-d3e64779462f)
报错指出的位置不准确。调试很久，一直未找到出错点。

### Reproduction

运行就出错

### Expected behavior

期望解决这个问题

### System Info

```sh
mac studio  google浏览器
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah, the location is not accurate. I'm not sure if we can fix that at vitepress level though. It's likely an issue vue plugin / vite. Can't help without whole file. Maybe try running prettier on it or enabling `"vue.server.vitePress.supportMdFile": true` if using volar. That should highlight the issue.

**Comment by gaojianghua** [comment]
![image](https://github.com/vuejs/vitepress/assets/61684763/15d8bdb3-5608-4033-b8a2-e511edab5f3a)
![image](https://github.com/vuejs/vitepress/assets/61684763/68164fe7-c871-43c6-baba-57cd1cf3f4fd)
找了好久是这个`{{`的原因，vitepress对这个的解析是不是有问题？

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/discussions/480#discussioncomment-2225141

**Comment by gaojianghua** [comment]
ok,这玩意折磨我好久
