### ISSUE TITLE
Element is missing end tag

### ISSUE THREAD

**Issue by busyhe** [vuejs/vitepress#2764]
### Describe the bug

ts Symbol error:

Partial<T>

### Reproduction

Partial<T>

### Expected behavior

Partial<T> is OK

### System Info

```sh
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 334.34 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.5.0 - ~/.nvm/versions/node/v19.5.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.1 - ~/.nvm/versions/node/v19.5.0/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v19.5.0/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 17.0
  npmPackages:
    vitepress: 1.0.0-beta.7 => 1.0.0-beta.7
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Escape that using backticks:

```
`Partial<T>`
```

**Comment by busyhe** [comment]
> 

I use Partial\<T\> also OK, But this is an unfriendly solution

**Comment by busyhe** [comment]
> 使用反引号转义：
> 
> ```
> `Partial<T>`
> ```

I use Partial<T> also OK, But this is an unfriendly solution

**Comment by busyhe** [comment]
> 使用反引号转义：
> 
> ```
> `Partial<T>`
> ```

I use Partial also OK, But this is an unfriendly solution

```ts
Partial\<T\>
```
