### ISSUE TITLE
引入 echarts 编译时报错

### ISSUE THREAD

**Issue by holynewbie** [vuejs/vitepress#2769]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/8347286/f26c7798-8355-4d4a-8236-056f5b3d2ac5)

### Reproduction

https://stackblitz.com/edit/vite-pzpqo8?file=docs%2F.vitepress%2Ftheme%2Fx.ts

在 `theme/x.ts` 中引入了 `echarts` ，开发时是可以的，页面正常显示。构建时报错。

![image](https://github.com/vuejs/vitepress/assets/8347286/a9816458-b726-4519-b5ca-996815280fe6)

**如果是一个纯 vite 项目，构建不错误**

### Expected behavior

正常编译不出错

### System Info

```sh
System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 48.46 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/Library/Caches/fnm_multishells/19014_1691646234602/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/19014_1691646234602/bin/npm
    pnpm: 8.6.8 - ~/Library/pnpm/pnpm
  npmPackages:
    vitepress: 1.0.0-rc.4 => 1.0.0-rc.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
add this to your config:

```ts
  vite: {
    ssr: {
      noExternal: ['vue-echarts', 'echarts', 'zrender', 'resize-detector'],
    }
  }
```

https://stackblitz.com/edit/vite-zwfd6j?file=docs%2Fexample.md,docs%2F.vitepress%2Fconfig.ts
