### ISSUE TITLE
【自定义主题】使用useDate().page.headers获取得标题是空得

### ISSUE THREAD

**Issue by killer-wu** [vuejs/vitepress#2771]
### Describe the bug

export const useToc = () => {
  const { page  } = useData()

 console.log(page.value.headers)  // 为空
}

md文件：
## Character
- Custom component collections

## Toll
- Install built-in plugins

### Reproduction

![image](https://github.com/vuejs/vitepress/assets/61451803/831b5470-e108-4bcb-943e-4ebb0c4d5c0e)

### Expected behavior

能够正常访问md文件中得标题

### System Info

```sh
"devDependencies": {
    "vitepress": "1.0.0-rc.4"
},
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to enable that:

```ts
import { defineConfig } from 'vitepress';

export default defineConfig({
  markdown: {
    headers: {
      level: [1, 6],
    },
  },
});
```

**Comment by killer-wu** [comment]
> You need to enable that:
> 
> ```ts
> import { defineConfig } from 'vitepress';
> 
> export default defineConfig({
>   markdown: {
>     headers: {
>       level: [1, 6],
>     },
>   },
> });
> ```

Thank you for your answer. I should have looked at the markdown-it file more often
