### ISSUE TITLE
Escape character for ] inside ::code-group filename

### ISSUE THREAD

**Issue by louwers** [vuejs/vitepress#2775]
### Describe the bug

From the documentation it is not clear how to escape `]` inside a `::code-group`.

### Reproduction

````
::code-group
```ts "[server/api/trpc/[trpc].ts]"
// some code
```
````

Filename gets cut off:

<img width="215" alt="image" src="https://github.com/vuejs/vitepress/assets/649392/09407eb8-df3a-4489-ba43-522162c00ab7">

### Expected behavior

I expect to be able to escape `]` with `\]`.

Or maybe only end the file name parsing when `]` is the last character of the line.

### System Info

```sh
N/A
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Seems to work fine: https://stackblitz.com/edit/vite-hz83rb?file=docs/index.md

**Comment by brc-dd** [comment]
And that site uses Docus not VitePress

**Comment by louwers** [comment]
@brc-dd Whoops. Sorry.
