### ISSUE TITLE
The ol label is not aligned

### ISSUE THREAD

**Issue by Plumbiu** [vuejs/vitepress#2777]
### Describe the bug

![](https://plumbiu.github.io/blogImg/Snipaste_2023-08-11_23-12-00.png)

### Reproduction

[bug](https://stackblitz.com/edit/vite-tsynfq?file=docs%2Fexample.md)

### Expected behavior

![](https://plumbiu.github.io/blogImg/image-20230811231540808.png)

### System Info

```sh
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 17.60 GB / 31.73 GB
Binaries:
    Node: 18.16.0 - D:\env\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - D:\env\nodejs\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Roaming\npm\pnpm.CMD
Browsers:
    Edge: Spartan (44.22621.1194.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Lists are expected to be indented. For example, github, shadcn/ui also do this:

<img width="180" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/132cd4ee-eb9b-4e90-bc96-4a3733415c0c"> <img width="341" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/3d4b2c83-fcf4-4c9f-840c-28764c06db5d">

It might be your personal preference to align them though. You can directly customize styles via CSS: https://vitepress.dev/guide/extending-default-theme#customizing-css
