### ISSUE TITLE
build errors in rendering pages: TypeError: Cannot read properties of undefined (reading 'imports')

### ISSUE THREAD

**Issue by eriktorsner** [vuejs/vitepress#2779]
### Describe the bug

This is pretty much a duplicate of #2351 

When using symlinks to include a folder in my /docs, I get the following error:

```
TypeError: Cannot read properties of undefined (reading 'imports')
    at resolvePageImports (file:///Users/erik.torsner/src/wundermatics/static-site/node_modules/vitepress/dist/node/serve-3dd2c315.js:52780:18)
    at renderPage (file:///Users/erik.torsner/src/wundermatics/static-site/node_modules/vitepress/dist/node/serve-3dd2c315.js:52676:10)
    at async Promise.all (index 11)
    at async file:///Users/erik.torsner/src/wundermatics/static-site/node_modules/vitepress/dist/node/serve-3dd2c315.js:52881:7
    at async task (file:///Users/erik.torsner/src/wundermatics/static-site/node_modules/vitepress/dist/node/serve-3dd2c315.js:48634:5)
    at async build (file:///Users/erik.torsner/src/wundermatics/static-site/node_modules/vitepress/dist/node/serve-3dd2c315.js:52849:5
```

The docs folder: 

```
docs
├── api-examples.md
├── index.md
├── markdown-examples.md
└── myproduct -> /Users/erik.torsner/src/org/my-product-docs
```

So, whenever I upgrade vitepress, I do the following manual patch to fix it:

```
➜  static-site git:(main) ✗ diff node_modules/vitepress/dist/node/serve-orig-3dd2c315.js node_modules/vitepress/dist/node/serve-3dd2c315.js
52770c52770,52772
<     srcPath = fs$a.realpathSync(srcPath);
---
>     if (!config.vite.resolve.preserveSymlinks) {
>       srcPath = fs$a.realpathSync(srcPath);
>     }
```

...and I'm off to the races. Both `npm run docs:build` and `npm run docs:dev` works just fine and I can go back to building my docs site. 

If it's possible to fix this in the source, I'd be grateful.

### Reproduction

Set up a docs folder where one of the folders is a symlink to another location.

### Expected behavior

`npm run docs:build` works without having to manually patching `resolvePageImports()`

### System Info

```sh
MacOS: 13.5 (22G74)
Node: v18.15.0
npm: 9.5.0
vitepress: 1.0.0-rc.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Symlinks aren't completely supported yet (#1496). I'll test out your solution with other factors. If it works well for all cases, then will add that. Thanks for the sharing your findings.
