### ISSUE TITLE
Documentation on how to use `enhanceApp` 

### ISSUE THREAD

**Issue by jivane-perich** [vuejs/vitepress#278]
**Is your feature request related to a problem? Please describe.**

The current documentation is unclear on how to use `enhanceApp` in a custom theme `.vitepress/theme/config.js`

I'm trying to add a new custom route redirecting all pages with url like `/tags/*` to `/tag/`

**Describe the solution you'd like**

A documentation with an example on how to declare a new custom route in `Theme.enhanceApp`  in config.js.
Ideally, the newly declared route can have the following format `/tags/:id`, where `:id` is extracted by the router and added to route.data.parameter

**Describe alternatives you've considered**

A method to surcharge the Router, or the possibility to surcharge the `loadPageModule` parameter of `createRouter`
Any other solution allowing me to have parameter in my url (without ? )

**Comment by soulsam480** [comment]
Currently Vitepress desn't have support for URL params i think. But a workaround can be achieved by using URL hash.

Let's say you want to go `tags#vue` where `vue` is the hash. You can add a `watchEffect` hook inside a custom component that only gets rendered for the `tags` route. Then you can wrap the component inside `<ClientOnly></ClientOnly/>` and use the hash like a URL param. e.g. [see](https://github.com/soulsam480/rengoku/blob/theme/content/.vitepress/theme/components/Tags.vue)
```vue
<script setup lang="ts">
import { useSiteData } from 'vitepress';
import { ref, toRef, watchEffect } from 'vue';
import type { Post } from '../types';
import PostCards from './PostCards.vue';
const siteData = useSiteData();
const posts = toRef(siteData.value.customData as { posts: Post[] }, 'posts');
const showPosts = ref<Post[]>([]);
const hash = ref<string | null>(null);
watchEffect(() => {
  if (window.location.hash) {
    hash.value = window.location.hash.replace('#', '');
    showPosts.value = posts.value
      .slice()
      .filter((el) => el.tags?.includes(window.location.hash.replace('#', '')));
  }
});
</script>
<template>
  <div>
    <div v-if="showPosts.length > 0">
      <h2>
        Showing articles for <span class="rengoku-alt">{{ hash }}</span>
      </h2>
      <PostCards :posts="showPosts" />
    </div>
    <p v-else>
      Nothing found for tag <span class="rengoku-alt">{{ hash }}</span>
    </p>
  </div>
</template>
```
This component will be rendered for the `tags` route and filter the posts accordingly. As this is inside `ClientOnly`, this won't be server renderd.

**Comment by prashantnirgun** [comment]
Help required I am new to vitepress please help
Can't access siteData its giving errror 
router.js:76 SyntaxError: The requested module '/@fs/home/prashant/www/vitepress/node_modules/vitepress/dist/client/index.js' does not provide an export named 'default'
code is as bellow 
```
# Test

<script>
import { defineComponent } from "vue";
import useSiteData from "vitepress";
export default defineComponent({
  setup() {
    const siteData = useSiteData();
    console.log("context", siteData);
  },
});
</script>
```
is it because my theme/index.js contain following code
```import "./tailwind.postcss";
import DefaultTheme from "vitepress/dist/client/theme-default";
export default { ...DefaultTheme };
```

**Comment by shadow-light** [comment]
I've been trying to work out how to add global vars that are accessible in all pages. Was thinking along the lines of global $frontmatter but ended up with:

```
enhanceApp({app}){
    app.config.globalProperties.$something = 'something'
},
```
Is that the best way or was there something more proper?

---

Re @prashantnirgun I'm sure you've moved on but just for fun: you are missing the brackets on your import `{useSiteData}`

**Comment by kiaking** [comment]
We have much more details docs about this 👍
