### ISSUE TITLE
Open Markdown plugin mechanism

### ISSUE THREAD

**Issue by deyihu** [vuejs/vitepress#2789]
### Is your feature request related to a problem? Please describe.

Users can customize the set of plugins for markdown

### Describe the solution you'd like

Markdown provides plugin configuration options or plugin installation hook functions
```js
markdown:{
     ....
  
  plugins:[
    [plugin1,options],
    ....
  ]

}

```

or

```js

markdown:{
     ....
  
  pluginHook(md){
      md .use(plugin1)
   }

}



```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's already supported. Use markdown.config option : https://vitepress.dev/guide/markdown#advanced-configuration

**Comment by steverowling** [comment]
How do you use this now that Vitepress is an ESM-only package? Using `require()` as per the link to extend the markdown config results in an error: `Dynamic require of "file:///var/www/html/node_modules/markdown-it-deflist/index.js" is not supported`

**Comment by brc-dd** [comment]
import them instead of requiring

**Comment by steverowling** [comment]
What does that look like? Shouldn't the docs show the correct method for doing that? Sorry, but I'm more of a PHP dev than JS and not completely familiar with the syntax for import.

**Comment by brc-dd** [comment]
updated the docs

**Comment by steverowling** [comment]
Thanks!
