### ISSUE TITLE
vitepress support tsx ?

### ISSUE THREAD

**Issue by yeojongki** [vuejs/vitepress#279]
I want to importing a tsx component in markdown like this

```md
# Docs

This is a .md using a custom component

<CustomComponent />

## More docs

...

<script setup>
import CustomComponent from '../components/CustomComponent.tsx'
</script>
```

but found error:
```bash
Layout.vue:114 Uncaught (in promise) TypeError: Cannot destructure property 'frontmatter' of 'route.data' as it is null.
```

**Comment by kiaking** [comment]
Hmmm... @yeojongki Do you know if the same code works with Vite...?

**Comment by yeojongki** [comment]
@kiaking  yes, but it needs a vite plugin: [@vitejs/plugin-vue-jsx](https://www.npmjs.com/package/@vitejs/plugin-vue-jsx)

**Comment by imjeen** [comment]
Here's my config in root directory.  

`/vite.config.js`: 
```ts
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import vueJsx from "@vitejs/plugin-vue-jsx";

export default defineConfig({
  esbuild: {
    jsxFactory: "h",
    jsxFragment: "Fragment",
  },
  plugins: [
    vue({
      include: [/\.vue$/, /\.md$/],
    }),
    vueJsx({
      // options are passed on to @vue/babel-plugin-jsx
    }),
  ],
});
```


But it's not working  for  `/docs` directory  to import a tsx component in markdown with `vitepress`. 

`/docs/test.md`: 
```md
# Docs

This is a .md using a custom component

<CustomComponent />

## More docs

...

<script setup>
import CustomComponent from '../components/CustomComponent.tsx'
</script>
```

 I'm a beginner about `vitepress`.  Anyone know where to config it ?

**Comment by YogaZong** [comment]
你成功了吗？好像只支持 `.vue`

**Comment by antfu** [comment]
VitePress support `vite.config.ts`, maybe try to install the plugin there?

**Comment by YogaZong** [comment]
> VitePress supports `vite.config.ts`, maybe try to install the plugin there?

I have a success case:
I tried to import the default function `createPlugin` from `@vitejs/plugin-vue-jsx` , and added it to the result array of function  `createVitePressPlugin()` in `src/node/plugin.ts`, then I successfully used Jsx component in md.

Failure case:
But the plugin `@vitejs/plugin-vue-jsx` that was installed in `vite.config.ts` didn't  seem to be excuted correctly when vitepress running. VitePress still throwing an Error like `TypeError: destructrue property 'frontmatter' of 'route.data' as it is null` or `React is undefined`(jsx was not be compiled by render function of Vue) during execution of render function.

Versions:
Vue: 3.0.5
Vite: 2.2.4
VitePress: 0.14.0

plugin.ts of VitePress:
```
import createVuePlugin from '@vitejs/plugin-vue'
import createJsxPlugin from '@vitejs/plugin-vue-jsx'

export function createVitePressPlugin(...args) {

...

  const vuePlugin = createVuePlugin({
    include: [/\.vue$/, /\.md$/],
    ...vueOptions
  })

  const vueJsxPlugin = createJsxPlugin()

...

  return [vitePressPlugin, vuePlugin, vueJsxPlugin]
}
```

vite.config.ts of my project:
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
export default defineConfig({
  plugins: [
    vue(),
    vueJsx()
  ]
)}
```

I am writing a little component library with Vue 3 and tsx, I meet this question when using VitePress in my project for building a documentation site.
VitePress is a nice minimalist production, wish it be better!

**Comment by YogaZong** [comment]
> VitePress supports `vite.config.ts`, maybe try to install the plugin there?

Do you mean that add `vue.config.ts` to root path like `docs/` ?
```
 .
├─ docs
│  ├─ .vitepress
│  │  └─ config.js
│  └─ index.md
│  └─vue.config.ts
└─ package.json
```

**Comment by antfu** [comment]
Yes, like 

```ts
// vite.config.ts

import { defineConfig } from 'vite'
import vueJsx from '@vitejs/plugin-vue-jsx'
export default defineConfig({
  plugins: [
    vueJsx()
  ]
)}
```

**Comment by YogaZong** [comment]
> Yes, like
> 
> ```ts
> // vite.config.ts
> 
> import { defineConfig } from 'vite'
> import vueJsx from '@vitejs/plugin-vue-jsx'
> export default defineConfig({
>   plugins: [
>     vueJsx()
>   ]
> )}
> ```

I solved this problem, Thanks a lot!!

**Comment by bowencool** [comment]
> Yes, like
> 
> ```ts
> // vite.config.ts
> 
> import { defineConfig } from 'vite'
> import vueJsx from '@vitejs/plugin-vue-jsx'
> export default defineConfig({
>   plugins: [
>     vueJsx()
>   ]
> )}
> ```

It works for me **without** `vue()`.

**Comment by luocong2016** [comment]
## 总结
1. 安装依赖
```
pnpm i -D @vitejs/plugin-vue-jsx
```

2. 创建 `vite.config.ts` 文件
```
| - .vitepress
    |_ vite.config.ts
```

3. 修改文件`vite.config.ts` 
```ts
import { defineConfig } from "vite";
import vueJsx from "@vitejs/plugin-vue-jsx";

export default defineConfig({
  plugins: [
    vueJsx(),
  ],
});
```

**Comment by ice1000** [comment]
This is very helpful!! Thanks very much!!
