### ISSUE TITLE
Change `import 'uno.css';` to `import 'unocss';`.

### ISSUE THREAD

**Issue by heyingjiee** [vuejs/vitepress#2792]
Change `import 'uno.css';` to `import 'unocss';`.

_Originally posted by @kiaking in https://github.com/vuejs/vitepress/issues/1917#issuecomment-1425090440_

unocss does not take effect even after it is introduced
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/39174971/260728813-28ffc44b-f297-4a06-b8b5-187ad048bdd8.png">

**Comment by brc-dd** [comment]
Refer the example link in #2424
