### ISSUE TITLE
How can I force an <a> to NOT be handled by the SPA router?

### ISSUE THREAD

**Issue by jcbhmr** [vuejs/vitepress#2798]
Right now I have this `<a href="/my-other-project/">` that I want to link to and NOT have it magically SPA-ed. Why? Because I'm hosting `me.github.io` and then `me.github.io/my-other-project/` is a separate website controlled by the me/my-other-project repository.

Is there some kind of attribute that I can add to get the `<a>` to magically bypass the SPA router?

actual code: https://github.com/devcontainers2/devcontainers2.github.io/blob/02020ea28b897267067f0774aa8ccad46092ec3b/index.md?plain=1#L23

so far I've resorted to using `mpa: true` which works, but id really like to `mpa: false` and still have an escape-hatch to avoid SPA behaviour here.

i also don't know if this problem is specific to the `features:` `<a>` hack that I'm using or if it applies to generic `[project 2](/my-other-project)` markdown normal links

i also don't know if this is a bug worthy of an issue or if it should be a discussion. feel free to move this around wherever

**Comment by brc-dd** [comment]
specify `target="_self"` on that link. For markdown, you can do: `[project 2](/my-other-project){target="_self"}`
