### ISSUE TITLE
Sidebar Navbar break on 0.4.0

### ISSUE THREAD

**Issue by marina-mosti** [vuejs/vitepress#28]
**Describe the bug**
The SideBar.js and NavBar.js components still reference `__DEV__` and should be replaced with `import.meta.env.DEV` to work with 0.4.0

**To Reproduce**
Use the default theme with 0.4.0

**Expected behavior**
NavBar and SideBar should not throw __DEV__ not defined errors

**System Info**
- vitepress version: 0.4.0
- vite version: v1.0.0-beta.2
- Node version:
- OS version:

**Additional context**

**Comment by yyx990803** [comment]
Can't reproduce... 0.4.0 doesn't contain any references to `__DEV__`. Maybe a npm caching issue?
