### ISSUE TITLE
At least one <template> or <script> is required in a single file component.

### ISSUE THREAD

**Issue by xanggang** [vuejs/vitepress#2801]
### Describe the bug

When the project first starts: `At least one <template> or <script> is required in a single file component.`，

### Reproduction

https://stackblitz.com/edit/vite-nnfopi?file=docs%2Findex.md

### Expected behavior

Normal

### System Info

```sh
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: latest => 1.0.0-rc.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by changweihua** [comment]
The same error was found under github workflow

**Comment by changweihua** [comment]
![image](https://github.com/vuejs/vitepress/assets/2877201/3d7c5b19-ef7a-4eeb-a3a0-bd5d20ef407b)

**Comment by changweihua** [comment]
I tried to fix it by using

"overrides": {
    "@vitejs/plugin-vue": "4.2.3"
  },

It seems works fine.

**Comment by zyf540860996** [comment]
![image](https://github.com/vuejs/vitepress/assets/10524382/11a86933-694d-40c0-a978-12467fac8f1e)

"dependencies": {
    "vue": "^3.3.4"
  },
  "devDependencies": {
    "typescript": "^5.0.2",
    "vite": "^4.4.5",
    "vue-tsc": "^1.8.5",
    "@vitejs/plugin-vue": "4.2.3",
    "vitepress": "1.0.0-alpha.76"
  }

**Comment by brc-dd** [comment]
use `@vitejs/plugin-vue@4.3.1`, no need manually override it, just regenerate your lockfiles.
