### ISSUE TITLE
Routing access failure after server Nginx deployment

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#2802]
### Describe the bug

Recently, I deployed a document site on my server through Nginx and found that if I directly access the specified route, it will be forwarded to the homepage, but the routing address is the one that was accessed. At this point, clicking on other navigation options on the page would be confusing. And I have deployed a site on GitHub without experiencing this issue. I suspect it is a Nginx configuration issue. Can you help me take a look at the problem?

### Reproduction

1.pnpm build
2.upload the content from dist to Nginx server
3.accessing Sites
![新标签页 - Google Chrome 2023-08-17 16-08-40](https://github.com/vuejs/vitepress/assets/25446948/87186df7-5d8d-4585-a8e0-f38caf354d37)

### Expected behavior

Expect normal routing access.

### System Info

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 21.30 GB / 31.75 GB
  Binaries:
    Node: 18.16.0 - D:\Develop\nodejs\node.EXE
    npm: 9.5.1 - D:\Develop\nodejs\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.19041.1566
```

### Additional context

N/A

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Please use [Discord](https://discord.com/invite/HBherRA) or [GitHub Discussions](https://github.com/vuejs/vitepress/discussions) for a question 👍 

And when you do, don't forget to paste your Nginx config so that people can see what's wrong with it 👀
