### ISSUE TITLE
srcDir not working

### ISSUE THREAD

**Issue by TechAkayy** [vuejs/vitepress#2806]
### Describe the bug

I'm currently having one markdown file (`index.md`) within the project root itself (`docs` folder) and uses only one Vue SFC called `SampleCard.vue`. I'm using a custom theme. This works fine. 

But I want to move my markdown file into `docs/content` folder, so I copied my md files into that folder. 

I then tried setting `srcDir` to `content` following the docs - https://vitepress.dev/guide/routing#source-directory. This doesn't work and the error message I get seems to indicate that my vite aliases gets broken when I use srcDir. 

Thanks for looking into this. 

### Reproduction

Here is my minimal github repo (one `index.md` page using one `SampleCard.vue`) - https://github.com/TechAkayy/my-vitepress-tailwindcss-app

Please clone, install, `npm run dev`, works fine. 

Then uncomment the `srcDir` settings in `config.ts`, and save. It gets broken. I tried paths relative to both project root, as well as relative to the `docs` folder. 

<img width="1106" alt="image" src="https://github.com/vuejs/vitepress/assets/73772701/30fa51cb-8ca4-4720-bd37-624eae000b76">

Error when using `srcDir`:
![image](https://github.com/vuejs/vitepress/assets/73772701/d3221060-8941-496a-955f-07b5d61c5b7e)

### Expected behavior

srcDir should work when moving the md files into a folder. But it didn't. 

### System Info

```sh
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.31 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Chrome Canary: 118.0.5953.0
    Safari: 15.6.1
  npmPackages:
    vitepress: ^1.0.0-rc.31 => 1.0.0-rc.31
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by TechAkayy** [comment]
I have updated the above with a minimal repo, one `index.md` page using one `SampleCard.vue`.

**Comment by TechAkayy** [comment]
Just checking if anyone figured out a workaround until this srcDir issue gets fixed? Thanks in advance.

**Comment by TechAkayy** [comment]
Hello, would be great not to miss this issue, before going major version, as `srcDir` is an important one. Thank you!

**Comment by brc-dd** [comment]
vite.config.ts should be inside srcDir

**Comment by TechAkayy** [comment]
Thank you 🙏🏾
