### ISSUE TITLE
[Feature Request] Allow user to set system as appearance

### ISSUE THREAD

**Issue by jcstein** [vuejs/vitepress#2808]
### Is your feature request related to a problem? Please describe.

Allow user to set color mode based on their system preferences:

```ts
  appearance: 'system',
```

### Describe the solution you'd like

This would allow the user's system preferences to set the mode of the site.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Unless the user manually toggles the appearance, it's inferred based on system preferences only.

**Comment by jcstein** [comment]
thanks! this is the way
