### ISSUE TITLE
使用行内代码时无法识别django template模板语法

### ISSUE THREAD

**Issue by yulinvo** [vuejs/vitepress#2810]
### Describe the bug

在行内代码中，使用django template语法时，build编译时会报错

### Reproduction

1.  xx.md文档中内容：
这是django temolate的笔记：`{{ articleList.a }}`

2. yarn docs:build 时会报错：TypeError: Cannot read properties of undefined (reading 'a')

测试环境是：v1.0.0-rc.4

### Expected behavior

yarn docs:build 能够编译通过

### System Info

```sh
yarn docs:build
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/discussions/480#discussioncomment-2225141
