### ISSUE TITLE
process includes before creating search index

### ISSUE THREAD

**Issue by g-dx** [vuejs/vitepress#2812]
### Describe the bug

If you include one or more Markdown files in another page, the local search index "sees them all" as separate pages - i.e. not as 1 single page which can be navigated to via the local search box. 

### Reproduction

1. Add the following Markdown files to a Vitepress project

    **part_1.md**
    ```
    Hello
    ```
    
    **part_2.md**
    ```
    World
    ```
    
    **index.md**
    ```
    <!--@include: ./part_1.md-->
    
    <!--@include: ./part_2.md-->
    ```
    
2. Configure local search and search for the word "Hello".

### Expected behavior

Given the example above, I would expect:

1. It is not possible to navigate to `part_1.md` or `part_2.md` pages at all.
2. Searching for the word "Hello" will show `index.md` as the only result.

### System Info

```sh
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 55.33 GB / 62.54 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    npm: 9.6.7 - /usr/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Chromium: 116.0.5845.96
  npmPackages:
    vitepress: ^1.0.0-rc.4 => 1.0.0-rc.4 
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Your part files are inside the source directory, so they will be considered as pages and will be indexed. You should move them out or add them to `srcExclude` to prevent generating corresponding html pages.

**Comment by g-dx** [comment]
Hey, thanks for the quick response!

If I do this:

```typescript
export default defineConfig({
  srcExclude: [
    '/part_1.md',
    '/part_2.md'
  ]
}
```
This *does* remove them from the search results as individual pages. However, I cannot find any of the _included_ content ("Hello" or "World") in `index.md` via the local search box anymore.

It appears the search index is being built _before_ Markdown inclusions are processed?

**Comment by brc-dd** [comment]
ah yeah, includes aren't currently processed as part of markdown renderer. should be an easy fix. 

also dynamic content is not supported in local search (fixing this might be quite tricky).

**Comment by g-dx** [comment]
Ah, glad to hear that processing includes as part of the Markdown renderer should be a straightforward fix as this will address my current issue (no need for dynamic content)

Thanks again for an amazing open source project! :trophy:
