### ISSUE TITLE
Export `VPImage` as global component

### ISSUE THREAD

**Issue by kleisauke** [vuejs/vitepress#2813]
### Is your feature request related to a problem? Please describe.

Exporting `VPImage` as a global component, just like `VPBadge`, would be really helpful. This approach would allow a different image to be chosen depending on whether dark or light mode is used.

For example:
```vue
<Image alt="Logo" :image="{ light: '/logo.svg', dark: '/logo-dark.svg' }" />
````

### Describe the solution you'd like

Export `VPImage` as global `Image` component, see e.g. commit https://github.com/kleisauke/vitepress/commit/f1b6a57409f7752fc2142545340afc589cf091ff.

### Describe alternatives you've considered

I considered to use this:
```html
<picture>
  <source srcset="/logo-dark.svg" media="(prefers-color-scheme: dark)" />
  <img src="/logo.svg" alt="Logo" />
</picture>
```

However, this approach wouldn't work if a user manually switches to dark mode.

### Additional context

I could open a PR for commit https://github.com/kleisauke/vitepress/commit/f1b6a57409f7752fc2142545340afc589cf091ff, if appropriate.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Contributions are welcome, but don't add that globally. Export it like this: #2767

People who want it to be global, can just import and register in their enhanceApp.

**Comment by kleisauke** [comment]
Ah, that makes sense. I just opened PR #2814 for this.
