### ISSUE TITLE
Vitepress build error

### ISSUE THREAD

**Issue by soulaimaneyahya** [vuejs/vitepress#2817]
### Describe the bug

Execute command npm run docs:build and throw an exception: build error:
TypeError: Intl.Segmenter is not a constructor

### Reproduction

.vitepress config.ts
```
import { defineConfig } from 'vitepress'

export default defineConfig({
  lang: 'en-US',
  lastUpdated: true,
  cleanUrls: true,

  themeConfig: {

    nav: nav(),

    sidebar: {
      '/rest-api/': sidebarRestApi(),
    }
  }
})
```

package.json
```
"scripts": {
    "dev:docs": "npx vitepress dev docs",
    "build:docs": "npx vitepress build docs",
    "serve:docs": "npx vitepress serve docs"
  },
  "dependencies": {
    "vue": "^3.3.4"
  },
  "devDependencies": {
    "vitepress": "^1.0.0-rc.4"
  }
```

### Expected behavior

npm run build:docs

### System Info

```sh
npx vitepress build docs

vitepress v1.0.0-rc.4

build error:
TypeError: Intl.Segmenter is not a constructor
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide a minimal "complete" verifiable example, preferably using https://vitepress.new

The information you've provided is not sufficient enough to reproduce the issue at our end. Although, most likely seems to be an issue with your node version.

**Comment by soulaimaneyahya** [comment]
the same issue;

https://stackblitz.com/edit/vite-p57qkk?file=package.json

Works for dev but not for build

**Comment by brc-dd** [comment]
<img width="873" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/8daf0ead-6b98-4a8f-881c-b4986b34ff77">

**Comment by soulaimaneyahya** [comment]
build issue

![Screenshot from 2023-08-18 23-16-36](https://github.com/vuejs/vitepress/assets/75973907/7955ea4b-2b51-4410-bee9-e2bfa6d63cdc)

**Comment by brc-dd** [comment]
Which browser are you on? StackBlitz doesn't work properly in firefox.

**Comment by soulaimaneyahya** [comment]
latest vitpress v support node-v > 16.2.0

**Comment by brc-dd** [comment]
The recommended version is node 18 or higher. It might however work on node 16 as well. But webcontainers (stackblitz) polyfill most of the code but not the Intl.Segmenter API which is available in node 16+ but is not there in firefox. It wasn't being used anywhere in the client code, but since technically node in webcontainers is running in the browser itself, so it was being executed. I have now downgraded that dependency in 877f643. It should work fine on firefox webcontainers from next release.

**Comment by soulaimaneyahya** [comment]
Thank you for the update! It's great to hear that the compatibility issue with Firefox and Node.js versions has been addressed by downgrading the dependency. I really appreciate your quick response and effort in making sure Vitepress works smoothly across different environments. Looking forward to the next release! :+1:
