### ISSUE TITLE
vitepress not support element-plus? 

### ISSUE THREAD

**Issue by zhaowenlin** [vuejs/vitepress#282]
**Describe the bug**
when i was included element-plus as official document , but there was error about vue3 proxy
 index.esm.js: 1 Uncaught (in promise) TypeError: Cannot read property 'proxy' of null

**To Reproduce**
1.git clone from https://github.com/zhaowenlin/demo
2.yarn install
3.npm run dev
4.访问http://localhost:3000/
5.点击快速上手

**Expected behavior**
render normally

**System Info**
- vitepress version: 0.12.2
- vite version:2.1.5
- Node version: 14.15.5
- OS version: 10.14.6

**Additional context**

**Comment by Zimomo333** [comment]
same problem with me.I can't use my own UI components too.

**Comment by YogaZong** [comment]
You may set config in `docs/vite.config.ts` like this:
```
import { defineConfig } from 'vite'
import styleImport from 'vite-plugin-style-import'

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      vue: 'vue/dist/vue.esm-bundler.js',
    },
  },
  plugins: [
    vueJsx(),
    styleImport({
      libs: [
         {
               libraryName: 'element-plus',
               resolveStyle: (name) => {
                 return `element-plus/lib/theme-chalk/${name}.css`;
               },
               resolveComponent: (name) => {
                   return `element-plus/lib/${name}`;
               },
          },
        },
      ],
    }),
  ],
})
```

**Comment by kiaking** [comment]
I guess that is the solution here 👍

**Comment by Zimomo333** [comment]
> You may set config in `docs/vite.config.ts` like this:
> 
> ```
> import { defineConfig } from 'vite'
> import styleImport from 'vite-plugin-style-import'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   resolve: {
>     alias: {
>       vue: 'vue/dist/vue.esm-bundler.js',
>     },
>   },
>   plugins: [
>     styleImport({
>       libs: [
>          {
>                libraryName: 'element-plus',
>                resolveStyle: (name) => {
>                  return `element-plus/lib/theme-chalk/${name}.css`;
>                },
>                resolveComponent: (name) => {
>                    return `element-plus/lib/${name}`;
>                },
>           },
>         },
>       ],
>     }),
>   ],
> })
> ```

thanks, it works well for me.

**Comment by Zimomo333** [comment]
thanks @YogaZong solution, it works well for me.
