### ISSUE TITLE
"vitepress" resolved to an ESM file. ESM file cannot be loaded by `require`.

### ISSUE THREAD

**Issue by journey0726** [vuejs/vitepress#2820]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/73887142/b0af9512-e7f6-4a8a-b79d-fe739eeb0e72)
![image](https://github.com/vuejs/vitepress/assets/73887142/a1ccf8ca-11ed-498d-9087-faed77e5b06a)

![image](https://github.com/vuejs/vitepress/assets/73887142/63ffa878-6c3e-4b27-a8fc-badc2168b88e)
![image](https://github.com/vuejs/vitepress/assets/73887142/8c80e814-11d1-44ad-b0b1-29ec957f116d)
![image](https://github.com/vuejs/vitepress/assets/73887142/0cc4532a-2fef-46e5-ba49-745dd49d2f73)

### Reproduction

It was able to run normally before,but I didn't make any changes to the configuration

### Expected behavior

normal operation

### System Info

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 AMD FX-9830P RADEON R7, 12 COMPUTE CORES 4C+8G 
    Memory: 2.17 GB / 6.95 GB
  Binaries:
    Node: 14.18.0 - F:\test\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - F:\test\npm.CMD
  Browsers:
    Chrome: 115.0.5790.173
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.203)  
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-rc.4 => 1.0.0-rc.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
#2703

**Comment by journey0726** [comment]
> #2703

Is it changing the `config.ts`'s suffix to `mts`？ but it throw an error
![image](https://github.com/vuejs/vitepress/assets/73887142/54d02302-e67a-46e7-80a2-04be4ab04451)

**Comment by zonemeen** [comment]
You can change the suffix of `config.ts` to `mts`, or add `"type": "module"` to `package.json`.

**Comment by journey0726** [comment]
> You can change the suffix of `config.ts` to `mts`, or add `"type": "module"` to `package.json`.
I change the suffix of `config.ts` to `mts`, but it also throw an error
![image](https://github.com/vuejs/vitepress/assets/73887142/f7573159-fef9-4183-af58-4f84eeea4afa)

**Comment by brc-dd** [comment]
Update your node version to v18 or above. both mts/type module would work fine.

**Comment by journey0726** [comment]
thanks
