### ISSUE TITLE
Unable to add Pinia with enhanceApp

### ISSUE THREAD

**Issue by TechAkayy** [vuejs/vitepress#2827]
### Describe the bug

When trying to use pinia uisng `enhanceApp` (https://vitepress.dev/guide/custom-theme#theme-interface), I'm getting the below error. 

![image](https://github.com/vuejs/vitepress/assets/73772701/ac9c1ae9-f8ec-4875-a932-f30e3b409c23)

### Reproduction

Github: [pinegrow/pg-vitepress-tailwindcss-custom](https://github.com/pinegrow/pg-vitepress-tailwindcss-custom)

Equivalent stackblitz links:
[stackblitz.com/github/pinegrow/pg-vitepress-tailwindcss-custom](https://stackblitz.com/github/pinegrow/pg-vitepress-tailwindcss-custom)

In app.ts, uncomment `app.use(pinia)`, like below.

![image](https://github.com/vuejs/vitepress/assets/73772701/473dc6fc-7bda-4db8-b1ae-c72062a81ea9)

### Expected behavior

Should be able to register pinia store to app via enhanceApp. 

### System Info

```sh
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.31 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Chrome Canary: 118.0.5953.0
    Safari: 15.6.1
  npmPackages:
    vitepress: ^1.0.0-rc.4 => 1.0.0-rc.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Seems an issue with your dependencies. I updated them and it works fine on dev:

<img width="699" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/2b208a0c-d193-423f-b939-1d1256a4c167">

On build, there are hydration issues because of some other components.

**Comment by TechAkayy** [comment]
Thanks 👍🏽

**Comment by TechAkayy** [comment]
Upgrading vue to latest seems to fix it for me. For anyone's reference.
