### ISSUE TITLE
How to toggle dark theme in custom theme?

### ISSUE THREAD

**Issue by zhou-tao** [vuejs/vitepress#2830]
### Describe the bug

When i use `isDark` and try to toggle it’s value, theme color of the page is not be changed.

```html
<script setup lang="ts">
  import { useData } from 'vitepress'

  const { isDark } = useData()
</script>

<template>
  <header class="header">
    <a href="#">LOGO</a>
    <nav class="nav">
      <a href="#">
        <!-- custom theme toggle -->
        <div :class="isDark ? 'i-ri-sun-line' : 'i-ri-moon-line'" @click="isDark = !isDark" />
      </a>
    </nav>
  </header>
</template>
```

### Reproduction

https://github.com/vuejs/vitepress/assets/36221207/cb78fbb6-8ae3-482e-8c37-063fcc7e441d

### Expected behavior

A way to switch themes in a custom theme:

The theme color of the page switches automatically when the isDark value is changed.

Or provide a method to actively modify.

Thanks❤️

### System Info

```sh
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 45.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.1.2 - /usr/local/bin/npm
    pnpm: 8.6.12 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
will be fixed in next release

**Comment by zhou-tao** [comment]
> will be fixed in next release

thanks
