### ISSUE TITLE
Monaco-editor + Vitepress not found on 1.0.0-rc.4 when building?

### ISSUE THREAD

**Issue by valgaze** [vuejs/vitepress#2832]
### Describe the bug

Using Monaco Editor (applying **[this trick](https://github.com/vuejs/vitepress/issues/1508)**) works with `npm run docs:dev` but is failing with `npm run docs:build`

In other words, Monaco Editor works in dev but fails in build. The is **not** related to imports ([ex1](https://github.com/vuejs/vitepress/issues/1508), [ex2](https://github.com/vitejs/vite/discussions/1791#discussioncomment-321046, [ex3](https://twitter.com/youyuxi/status/1355316139144970240?s=20))

The error when building reads is about module_not_found (the package is definitely installed & path exists):

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/home/projects/nbwixzanm.github/node_modules/monaco-editor/' imported from /home/projects/nbwixzanm.github/.vitepress/.temp/....
```

Stackblitz:
<img width="1040" alt="image" src="https://github.com/vuejs/vitepress/assets/1396559/1ce6110a-4d0e-4160-a1df-9148f778ebe3">

### Reproduction

https://github.com/valgaze/vitepress-monaco#setup

https://stackblitz.com/github/valgaze/vitepress-monaco # npm run docs:build

### Expected behavior

Monaco Editor should be able to build/bundle and find its folder that exists

### System Info

```sh
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 139.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
  Browsers:
    Brave Browser: 114.1.52.122
    Chrome: 116.0.5845.96
    Firefox: 105.0.3
    Safari: 15.2
  npmPackages:
    vitepress: ^1.0.0-rc.4 => 1.0.0-rc.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Add this to your config:

```ts
  vite: {
    ssr: {
      noExternal: ['monaco-editor']
    }
  }
```

Also, that component should be imported only on client. Because `monaco-editor` uses browser only APIs, and will throw errors on SSR:

```vue
<MonacoEditor />

<script setup>
import { defineAsyncComponent } from 'vue';
import { inBrowser } from 'vitepress';

const MonacoEditor = inBrowser
  ? defineAsyncComponent(() => import('./components/monaco.vue'))
  : () => null;
</script>
```

https://stackblitz.com/edit/github-ud4nff?file=index.md,.vitepress/config.mts
