### ISSUE TITLE
starter template is crashing.

### ISSUE THREAD

**Issue by PriyansuMaurya** [vuejs/vitepress#2838]
### Describe the bug

This is not working as intended.

![image](https://github.com/vuejs/vitepress/assets/101447544/f4738b05-3bc6-455a-8d80-5a535e0d7c8d)

[StackBlitz](https://vitepress.new/)

When you click, it will take you here, and the side terminal will show "installing dependencies."

![image](https://github.com/vuejs/vitepress/assets/101447544/c7997fcd-a862-43c0-bd23-fbca35b8b880)

But after a few seconds, it crashes.

![image](https://github.com/vuejs/vitepress/assets/101447544/76bbaa76-38bb-4acb-a716-7ac931c208c8)

I checked it with other browsers as well, but the same thing is happening.

### Reproduction

Simply go to this link [StackBlitz](https://vitepress.new/).

And wait for few seconds.

 

### Expected behavior

It should not crash.

### System Info

```sh
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Which browser version are you on? It seems to be working fine for me on Chromium 116, Safari 17, Firefox 117.

**Comment by PriyansuMaurya** [comment]
![image](https://github.com/vuejs/vitepress/assets/101447544/ae424ed6-eefa-4096-8337-017474a02e9d)

Yesterday, it was same with Chrome but now it is fine but it still persist in edge.

**Chrome**

![image](https://github.com/vuejs/vitepress/assets/101447544/affbff31-c240-4238-a830-4129efb4fc29)

**Edge**

![image](https://github.com/vuejs/vitepress/assets/101447544/26c8ceaf-e6f4-445a-bb39-f372e4b33755)

**Comment by brc-dd** [comment]
Seems like a bug with StackBlitz. Can you create an issue there: https://github.com/stackblitz/webcontainer-core/issues/new?template=bug_report.yml

Also, once check if enhanced security is disabled for stackblitz: https://developer.stackblitz.com/platform/webcontainers/browser-config#edge-webassembly
