### ISSUE TITLE
Miss page headers using useDate

### ISSUE THREAD

**Issue by JiuRanYa** [vuejs/vitepress#2840]
This way not work for me. I got the same problem.

```ts
import { defineConfig } from 'vitepress';

export default defineConfig({
  markdown: {
    headers: {
      level: [1, 6],
    },
  },
});
```

_Originally posted by @brc-dd in https://github.com/vuejs/vitepress/issues/2771#issuecomment-1672749363_

Repo link: https://stackblitz.com/edit/vite-ernqnb?file=docs%2Fexample.md

**Comment by brc-dd** [comment]
Please provide a reproducible example using https://vitepress.new

**Comment by JiuRanYa** [comment]
> Please provide a reproducible example using https://vitepress.new

markdown type even not include headers field, I'll provide a repo later. Thanks!

**Comment by JiuRanYa** [comment]
> Reference in new

It seems vitepress v1.0.0-alpha.73 version problem, I switch to 0.22 version. Code works.

**Comment by JiuRanYa** [comment]
https://stackblitz.com/edit/vite-ernqnb?file=docs%2Fexample.md

> Please provide a reproducible example using https://vitepress.new

Here is the repo. Log headers is empty.

**Comment by brc-dd** [comment]
It's working fine:

<img width="457" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/4021e33b-cc0b-4071-9734-91b259c81d9e">

You need to specify all the levels you need in headers:

<img width="415" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/43c84802-3685-4b05-b3ca-2f38a7c556c5">

**Comment by JiuRanYa** [comment]
> It's working fine:
> 
> <img alt="image" width="457" src="https://user-images.githubusercontent.com/40380293/262877566-4021e33b-cc0b-4071-9734-91b259c81d9e.png">
> You need to specify all the levels you need in headers:
> 
> <img alt="image" width="415" src="https://user-images.githubusercontent.com/40380293/262877722-43c84802-3685-4b05-b3ca-2f38a7c556c5.png">

Thanks, I find the latest version has markdown header option. But 1.0.0.alpha.73
