### ISSUE TITLE
How to build with csr 

### ISSUE THREAD

**Issue by 52javascript** [vuejs/vitepress#2841]
### Describe the bug

I do not want use ssr method build document. by the way, Whether the current version supports building a single page？

### Reproduction

I do not want use ssr method build document. by the way, Whether the current version supports building a single page？

### Expected behavior

I do not want use ssr method build document. by the way, Whether the current version supports building a single page？

### System Info

```sh
I do not want use ssr method build document. by the way, Whether the current version supports building a single page？
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
No.
