### ISSUE TITLE
Cannot use external theme with UnoCSS

### ISSUE THREAD

**Issue by VVsxmja** [vuejs/vitepress#2845]
### Describe the bug

I wrote a custom VitePress theme with UnoCSS, and I tried to import the theme from another project.

But after imported, the dev server failed to render the page and reported 

```
[plugin:vite:import-analysis] Failed to resolve import "virtual:uno.css" from "../theme/.vitepress/theme/index.js". Does the file exist?
/home/projects/stackblitz-starters-9izmbf/theme/.vitepress/theme/index.js:3:9
1  |  // https://vitepress.dev/guide/custom-theme
2  |  import Layout from './Layout.vue';
3  |  import 'virtual:uno.css';
   |          ^
4  |  
5  |  export default {
```

I'm not sure which part of it is wrong. I don't even know if this is a VitePress bug. Please check the Stackblitz repro below.

### Reproduction

This StackBlitz project reproduces the bug. BTW, the start script might execute very slowly.

https://stackblitz.com/edit/stackblitz-starters-9izmbf?file=readme.md

### Expected behavior

The test project in the above StackBlitz repro with external theme to work normally without additional configuration.

### System Info

```sh
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> External theme to work normally without additional configuration.

This is not possible. Your theme user will need to have the same set of vite plugins and configuration for this to work. Export a base config from your theme and ask your users to put that in `extends` field in `defineConfig`. (move stuff inside vite.config to .vitepress/config inside `vite` option). Alternatively you can directly export a `defineConfig` from your theme's node entry too.

For a theme to work without any necessary configuration, you'll need to ship pre-built components. You can use vite's library mode for that.
