### ISSUE TITLE
Overriding root level CSS has no effect

### ISSUE THREAD

**Issue by atoumbre** [vuejs/vitepress#2846]
### Describe the bug

Overriding root level CSS variables has no effect on the theme.

### Reproduction

I strict followed exemple from the official Guide

### Expected behavior

I would like to customize the primary color

### System Info

```sh
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 161.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    npm: 9.7.2 - /usr/local/bin/npm
    pnpm: 8.6.12 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 116.1.57.53
    Chrome: 116.0.5845.96
    Edge: 116.0.1938.54
    Safari: 16.5.2
  npmPackages:
    vitepress: 1.0.0-rc.4 => 1.0.0-rc.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
The docs are for latest (unpublished) version. Refer these variables for rc.4: https://github.com/vuejs/vitepress/blob/v1.0.0-rc.4/src/client/theme-default/styles/vars.css
