### ISSUE TITLE
Imports from vitepress in markdown files lead to reexport warning

### ISSUE THREAD

**Issue by stone-zeng** [vuejs/vitepress#2856]
### Describe the bug

When I import something from vitepress in markdown files with a custom theme and then run `pnpm build`, I get the following warning:

<samp>
Export "Content" of module "node_modules/.pnpm/vitepress@1.0.0-rc.4_search-insights@2.7.0/node_modules/vitepress/dist/client/app/components/Content.js" was reexported through module "node_modules/.pnpm/vitepress@1.0.0-rc.4_search-insights@2.7.0/node_modules/vitepress/dist/client/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in ".vitepress/theme/Layout.vue" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
</samp>

### Reproduction

The file structure is the following:

- `.vitepress/config.js`:

```js
import { defineConfig } from 'vitepress'
export default defineConfig({
  lang: 'en-US',
  title: 'VitePress',
  cleanUrls: true,
})
```

- `.vitepress/theme/index.js`:

```js
import Layout from './Layout.vue'
export default { Layout }
```

- `.vitepress/theme/Layout.vue`:

```vue
<script setup>
import { Content } from 'vitepress'
</script>

<template>
  <Content />
</template>

```

- `index.md`:

```md
---
layout: home
---

<script setup>
import { useData } from 'vitepress'
</script>

{{ useData() }}
```

See <https://stackblitz.com/edit/vite-x3jrgk>.

### Expected behavior

There should be no such warning.

### System Info

```sh
System:
    OS: macOS 13.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 224.85 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /usr/local/bin/node
    npm: 9.8.0 - /usr/local/bin/npm
    pnpm: 8.6.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.110
    Edge: 115.0.1901.188
    Safari: 16.6
  npmPackages:
    vitepress: 1.0.0-rc.4 => 1.0.0-rc.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`import { Content } from 'vitepress'` should not be there. It's a global component.

**Comment by stone-zeng** [comment]
But the editor (e.g. vscode+volar) will not recognize it as a component:

<img width="703" alt="Screenshot 2023-08-26 at 16 33 33" src="https://github.com/vuejs/vitepress/assets/18233088/0638df6b-67fa-4d75-a2b6-0dcbd23c734b">

Is there any way to highlight it?

**Comment by brc-dd** [comment]
You can add something like this to a .d.ts file and include it in your tsconfig:

```ts
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('vitepress').Content
  }
}
```
