### ISSUE TITLE
`postcssIsolateStyles` mess up original styles

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/vitepress#2868]
### Describe the bug

Hover state on link in `.vp-doc` is always matched, seems `:hover` is being truncated.
![Snipaste_2023-08-29_00-58-54](https://github.com/vuejs/vitepress/assets/45784210/4812c127-1c7b-4f47-8afe-28f4a84fb2f8)

Copy button in code block is also messed up.
![Snipaste_2023-08-29_01-02-12](https://github.com/vuejs/vitepress/assets/45784210/2bcea36d-cd14-4bfe-b8ad-e7e421fec79f)
![Snipaste_2023-08-29_01-01-27](https://github.com/vuejs/vitepress/assets/45784210/782deb5a-3180-4a9c-99e9-b993aff3ba52)

Table style messed up as well.

I guess there's a lot more...

### Reproduction

In `config.ts`:
```ts
export default defineConfig({
  vite: {
    css: {
      postcss: {
        plugins: [
          postcssIsolateStyles({
            includeFiles: [/vp-doc\.css/]
          }),
        ],
      },
    }
})
```

I would write one if required, but since my above example is pretty easy to reproduce, I'll leave it blank here.

### Expected behavior

Style not messed up

 (NOTE: it's working properly if I use `postcss-prefix-selector` straight away instead of using the one from vitepress package)

### System Info

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 38.35 GB / 63.84 GB
  Binaries:
    Node: 18.16.0 - C:\NodeJS\node.EXE
    Yarn: 1.22.19 - C:\NodeJS\yarn.CMD
    npm: 9.8.1 - C:\NodeJS\npm.CMD
    pnpm: 8.7.0 - C:\NodeJS\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-rc.9 => 1.0.0-rc.9
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hey, can you paste your `postcss-prefix-selector` config? It should've worked fine 👀  We are just bundling it.

**Comment by xsjcTony** [comment]
> Hey, can you paste your `postcss-prefix-selector` config? It should've worked fine 👀  We are just bundling it.

Sorry I'm afk now, but my plugin config is copied from the previous version of vitepress doc (for that section), so you can refer to there.
