### ISSUE TITLE
Error 404 on refresh

### ISSUE THREAD

**Issue by atoumbre** [vuejs/vitepress#2869]
### Describe the bug

I'geting a 404 error when I refresh a page deeper than the home ( '/' ) WHEN it is deployed. local test works fine. I have seen some closed issue describing the same issue but no clear workaround that I can follow was shown.
![Screenshot](https://github.com/vuejs/vitepress/assets/10261533/7db343a6-89aa-47e0-b1c1-7e0d70abf502)

### Reproduction

- deploy a vite press app 
- Navigate to any link but the home page
- refresh the page

### Expected behavior

Refresh should not get 404 error

### System Info

```sh
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 77.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    npm: 9.7.2 - /usr/local/bin/npm
    pnpm: 8.6.12 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 116.1.57.53
    Chrome: 116.0.5845.110
    Edge: 116.0.1938.62
    Safari: 16.5.2
```

### Additional context

here is my config file :
import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config  
// https://vitepress.dev/reference/default-theme-config

export default defineConfig({
  title: "Weft Finance",
  description: "Lend and Borrow on Radix",

  lastUpdated: true,
  cleanUrls: true,

  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/favicons/favicon.svg' }],
    ['link', { rel: 'icon', type: 'image/png', href: '/favicons/favicon.png' }],
  ],

  themeConfig: {

    logo: '/weft-logo.png',

    editLink: {
      pattern: 'https://github.com/WeftFinance/weft_docs/tree/main/content/:path',
      text: 'Edit this page on GitHub'
    },

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © 2023-present Weft Finance'
    },

    nav: [
      { text: 'Home', link: '/' },
      { text: 'Overview', link: '/overview' },
    ],

    sidebar: [
      {
        text: 'Weft Overview',
        link: '/overview',
        items: [
          {
            text: 'Description and core concepts',
            link: '/description'
          },
          {
            text: 'On-ledger components',
            link: '/components'
          },
          {
            text: 'Lending and Borrowing Operations',
            link: '/operations'
          },
        ]
      },
      {
        text: 'The WEFT Token',
        link: '/token',
      },
      {
        text: 'Revenue and Insurance module',
        link: '/revenue',
      },
      {
        text: 'Roadmap',
        link: '/roadmap',
      }

    ],

    socialLinks: [
      { icon: 'twitter', link: 'https://twitter.com/Weft_Finance' },
      { icon: 'github', link: 'https://github.com/WeftFinance' }
    ]
  }
})

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
cleanUrls is enabled, but looks like you haven't configured your hosting provider to return `foo.html` when `foo` is requested.

**Comment by atoumbre** [comment]
Thanks for the feedback. I added cleanUrls:true to Firebase Hosting config file and it works fine.
