### ISSUE TITLE
Rewrites error when the path or filename includes '+'

### ISSUE THREAD

**Issue by izhichao** [vuejs/vitepress#2872]
### Describe the bug

If the path or filename includes '+', it will have a type error
![1](https://github.com/vuejs/vitepress/assets/60996631/c6a7d136-3614-4415-a7be-dc588c1b1347)
![2](https://github.com/vuejs/vitepress/assets/60996631/3b2d3d95-b550-4a82-90ac-f2e83ea7f7ae)

### Reproduction

just rename the path or filename to include '+'

### Expected behavior

No error

### System Info

```sh
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 6.72 GB / 15.89 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.7 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.10 => 1.0.0-rc.10
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Plus is a special character in regexes. Try escaping it: `1\\+.md`

**Comment by izhichao** [comment]
> Plus is a special character in regexes. Try escaping it: `1\\+.md`

It works. Thanks.
