### ISSUE TITLE
feat: build dry run or verify option

### ISSUE THREAD

**Issue by OrbisK** [vuejs/vitepress#2878]
### Is your feature request related to a problem? Please describe.

When you put build and deployment into the CI it happens from time to time that "dead links" exist.

### Describe the solution you'd like

I would like to have a way to manually run the dead links search step (and other steps if needed). This would allow me to run a light test script on the feature branches to know how the deploy will be before the merge into the deploy branch. 

### Describe alternatives you've considered

Of course, I could also run the build on the feature branch. But this seems to me (especially for larger projects) rather more cumbersome and resource-intensive.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Might be tricky to just expose running dead links checks. They are currently run as part of the vite pipeline (bundling step). If there are some dead links then the very first task would fail. How resource intensive is that?

Moreover, the dead link warnings are logged to terminal during dev as well. That should work for most folks. How frequently are you missing those warnings?

**Comment by OrbisK** [comment]
> How resource intensive is that?
It is not, but only if it fails. On most feature branches dead links are not a problem. Which would lead to the building running unnecessarily in most cases.

But sometimes it happens that the docs on a feature branch are not updated properly, which is only noticeable when the build process on a develop or staging branch is triggered. Which feels a bit late for me. But maybe that's just me.

**Comment by OrbisK** [comment]
> We can allow skipping the rendering step if you want 👀 But separating the dead link checks might not be feasible at the moment.

Yeah, thats what I mean by Dry-run
