### ISSUE TITLE
Reporting "Dead Links" in build when referring to the full path of the .md file

### ISSUE THREAD

**Issue by SharePointing** [vuejs/vitepress#2882]
### Describe the bug

In previous builds, I could use the intellisense in VSCode to build the link (ie ./folder/Index.md) and it would convert properly to /folder/index.html

I recently upgraded to rc10 and now the build reports those as dead links and I have to remove the .md to make it work. 

### Reproduction

In VSCode, add a link using the VSCode Intellisense (which produces a full path to the md file) 

example: 
* [Link Text](./Folder/Index.md)

When I build the site locally using the npm run docs:dev it seems to be OK, but when it's built in my azure devops pipline, it errors out with "dead links" and the build fails. 

(!) Found dead link ./PK-Community-4.0/index in file PK/Index.md

[vitepress] 1 dead link(s) found.
✖ building client + server bundles...
build error:
Error: 1 dead link(s) found.
    at Object.renderStart (file:///working_dir/node_modules/vitepress/dist/node/serve-df7895a1.js:37223:15)
    at file:///working_dir/node_modules/rollup/dist/es/shared/node-entry.js:25461:40
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///working_dir/node_modules/rollup/dist/es/shared/node-entry.js:25389:9)
    at async Bundle.generate (file:///working_dir/node_modules/rollup/dist/es/shared/node-entry.js:17827:13)
    at async file:///working_dir/node_modules/rollup/dist/es/shared/node-entry.js:26694:27
    at async catchUnfinishedHookActions (file:///working_dir/node_modules/rollup/dist/es/shared/node-entry.js:25827:16)

### Expected behavior

Referencing the .md file directly should convert without having to remove the .md extension (which is the workaround I have right now)

It's not optimal obviously to train content authors to remove the .md extension to avoid the build failure. 

### System Info

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 6.77 GB / 15.72 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-beta.7 => 1.0.0-rc.10
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide a reproducible example. It's working fine for me:

<img width="670" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/8f408ec0-d466-445a-8afe-fe6c17ef7cf0">
