### ISSUE TITLE
Request to Translate VitePress Documentation into Simplified Chinese

### ISSUE THREAD

**Issue by Coder-XiaoYi** [vuejs/vitepress#2883]
### Is your feature request related to a problem? Please describe.

My request is related to the problem of limited access to VitePress documentation for Chinese developers.

### Describe the solution you'd like

Dear VitePress team,

I am writing to express my interest in translating your excellent documentation from English into Simplified Chinese. As an avid user of VitePress, I believe having Chinese documentation would greatly benefit the Chinese developer community, who may not be proficient in English.

VitePress has quickly become one of the most popular static site generators thanks to its focus on speed and flexibility. However, currently all the official resources are only available in English. This creates a barrier to adoption for millions of developers in China who could greatly benefit from VitePress.

As a native Chinese speaker proficient in English, I would be honored to volunteer my time to translate the VitePress docs and site into Simplified Chinese. This would involve translating the documentation, guides, API references, and anything else on the site.

I am part of the Chinese open source community and am committed to helping projects expand their reach. I would handle all the translation work, while making sure to maintain the original meaning and technical accuracy. I am also happy to coordinate with your team and demonstrate proficiency if required.

Please consider this request to translate VitePress into Chinese. I believe it will significantly lower the barrier to entry for Chinese developers and enable faster adoption in China. If you have any other questions or need clarification, please let me know. I am excited at the possibility of contributing to this great project!

Thank you for your consideration.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi, we already have two PRs ready for Chinese translations. They will be merged as soon as the docs stabilize (i.e. vitepress reaches v1). You can view the preview at https://deploy-preview-1593--vitepress-docs.netlify.app/ or https://deploy-preview-2249--vitepress-docs.netlify.app/. Some translations might be incomplete currently.
