### ISSUE TITLE
Curly Quotes Not Working

### ISSUE THREAD

**Issue by SimonBerens** [vuejs/vitepress#2894]
### Describe the bug

Straight quotes are not converted into curly quotes by `markdown-it`.

### Reproduction

Create a new `vitepress` project using stackblitz, add `"hello world"` to the `index.md`, and it will be rendered with straight quotes.

### Expected behavior

According to the settings of `markdown-it` (see [demo](https://markdown-it.github.io/)) they should be replaced with smart quotes

### System Info

```sh
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: latest => 1.0.0-rc.10
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`typographer` isn't enabled likely due to conflicts with Vue syntax.
