### ISSUE TITLE
Dynamic sidebar values

### ISSUE THREAD

**Issue by quantix-dev** [vuejs/vitepress#2898]
### Is your feature request related to a problem? Please describe.

Currently I am unable to dynamically set the value of  the sidebar config at runtime. I had attempted to workaround this issue by overriding the built-in Sidebar component but the VPSidebarItem and other component were innaccessible due to them not being exported from `vitepress/theme`.

### Describe the solution you'd like

Potentially some way of updating the sidebar value either from the useData() or useSidebar composable.

Or for all components to be exported so that we can properly reimplement the internal components.

### Describe alternatives you've considered

I had attempted to edit the value returned from `useData()` but noted that was read-only so that had failed to work.
I also attempted to override the internal VPSidebar component with my own but was met with troubles when other dependent components (VPSidebarItem) were innaccessible from the `vitepress/theme` import.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> I also attempted to override the internal VPSidebar component with my own but was met with troubles when other dependent components (VPSidebarItem) were innaccessible from the vitepress/theme import.

Import them from `vitepress/dist/client/theme-default/...`

**Comment by brc-dd** [comment]
Track #2595 for types. Other than that, things are accessible from dist.
