### ISSUE TITLE
Local search has wrong colour on highlighted text

### ISSUE THREAD

**Issue by maggie44** [vuejs/vitepress#2902]
### Describe the bug

When using the local search (`search: { provider: "local" },`), the highlighted text is green instead of the brand colour:

<img width="1121" alt="Screenshot 2023-09-03 at 19 05 58" src="https://github.com/vuejs/vitepress/assets/64841595/b19fef35-9fd4-4fd9-a784-da3b48617fbc">

### Reproduction

`npx vitepress init`.

Add `search: { provider: "local" },` to themconfig. 

Search for the string `api`. 

Note: It's not reproducible on the Vitepress example site (`http://vitepress.dev`) as it doesn't use the local provider.

### Expected behavior

Should be a colour matching the brand colours

### System Info

```sh
`"vitepress": "^1.0.0-rc.10"`
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by userquin** [comment]
fixed in rc11 via https://github.com/vuejs/vitepress/pull/2887
