### ISSUE TITLE
Has the code highlight color changed?

### ISSUE THREAD

**Issue by Lazydd** [vuejs/vitepress#2903]
This is for rc.4
![image](https://github.com/vuejs/vitepress/assets/71319962/2c19e924-de92-4fe8-bca6-4146771603a4)

Then I upgraded to rc.10
![image](https://github.com/vuejs/vitepress/assets/71319962/efe84f71-2282-4c34-b430-6237f003048e)

**Comment by ajiho** [comment]
Yes, I don't know how to restore it yet. I don't feel like it looks as good as before

**Comment by brc-dd** [comment]
You can override `--vp-code-line-highlight-color` -- https://vitepress.dev/guide/extending-default-theme#customizing-css

**Comment by Lazydd** [comment]
> 

How to use old highlighted parts of the code. 
If covered, it would be very troublesome `--vp-code-line-highlight-color`

**Comment by brc-dd** [comment]
Are you referring to the syntax highlighting theme or that line highlight background color? That line highlight bg color can be overridden via that CSS variable. If you want to override syntax highlighting theme, you can set this in your config (refer the changelog, it's mentioned there):

```ts
export default defineConfig({
  markdown: {
    theme: 'material-theme-palenight'
  }
})
```
