### ISSUE TITLE
How to prevent iframe's src from automatically redirecting to page 404 when it cannot find the correct path

### ISSUE THREAD

**Issue by ajiho** [vuejs/vitepress#2905]
# code
```
## demo

<iframe src="/5.html"></iframe>
<iframe src="/6.html"></iframe>
```
# img
![image](https://github.com/vuejs/vitepress/assets/107699138/c7ea2936-a49c-4302-9cb0-2fcc1b111aea)
![image](https://github.com/vuejs/vitepress/assets/107699138/25064416-e163-4b81-9389-c0c32a30b3c2)

***
6. HTML does not exist. I would like to cancel its automatic redirection behavior. How can I maintain the default loading and timeout behavior of iframes? What should I do?

**Comment by brc-dd** [comment]
What's the expected behavior here? `/6.html` does not exist so 404 is shown. It's not redirecting your page.

**Comment by ajiho** [comment]
> What's the expected behavior here? `/6.html` does not exist so 404 is shown. It's not redirecting your page.

Ha, your speed is as fast as Superman, just like the default effect of iframe loading a non-existent HTML page in a regular page

see

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        iframe{
            border:1px solid red;
        }
    </style>
</head>
<body>

<iframe src="6.html" ></iframe>

</body>
</html>

```
![image](https://github.com/vuejs/vitepress/assets/107699138/fe1b60be-8f38-4768-8322-83ffed1e3d54)
I don't want any content on page 404 of vitepress to appear on it

**Comment by brc-dd** [comment]
You can override the 404 page like this:

```vue
<!--.vitepress/theme/Layout.vue-->
<script setup lang="ts">
import DefaultTheme from 'vitepress/theme'
import { useData } from 'vitepress'

const { page } = useData()
</script>

<template>
  <div v-if="page.isNotFound">404</div>
  <DefaultTheme.Layout v-else />
</template>
```

```ts
// .vitepress/theme/index.ts
import DefaultTheme from 'vitepress/theme'
import Layout from './Layout.vue'

export default {
  extends: DefaultTheme,
  Layout
}
```

<img width="394" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/6e7d3248-221c-43dd-9120-2c4ebbae68ca">

If you want to override it only for iframe, you can do something like this:

```vue
<script setup lang="ts">
import DefaultTheme from 'vitepress/theme'
import { inBrowser, useData } from 'vitepress'

const { page } = useData()

const inIframe = inBrowser && window.self !== window.top
</script>

<template>
  <div v-if="page.isNotFound && inIframe">404</div>
  <DefaultTheme.Layout v-else />
</template>
```
