### ISSUE TITLE
为什么部署完我的博客域名重定向到 一个新的地址

### ISSUE THREAD

**Issue by qisi007** [vuejs/vitepress#2910]
### Is your feature request related to a problem? Please describe.

我的域名是www.liuguisheng.vip，但是部署完成后重定向到了http://www.liuguisheng.vip/qisi007.github.io/，之前用vuepress搭建的没出现这个问题

### Describe the solution you'd like

我想要我的主页地址是www.liuguisheng.vip

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Remove `base` from here:

https://github.com/qisi007/qisi007.github.io/blob/main/package.json#L9C1-L10C1

It should simply be `vitepress build docs`
