### ISSUE TITLE
How to configure multiple languages for Copied?

### ISSUE THREAD

**Issue by ajiho** [vuejs/vitepress#2914]
## Translation issues regarding copying code prompt information

![image](https://github.com/vuejs/vitepress/assets/107699138/167f4d52-903e-416c-a661-f750cfb9ee5b)

How should I configure my own language?

I hope there is an option, like the one below

```
copyLabel: '已复制',
```

In order not to cause you any trouble, I have carefully read the official documents, but I have not found any relevant information

Does the feature configuration already exist and I have not found it, or is it not yet implemented in the current version?

**Comment by brc-dd** [comment]
#2833
