### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /Users/pengfeiren/Desktop/ld/ledu-design-vue/node_modules/.pnpm/element-plus@2.3.12/node_modules/element-plus/theme-chalk/base.css

### ISSUE THREAD

**Issue by pengfeir** [vuejs/vitepress#2915]
### Describe the bug

我的组件库是基于element ui 二次封装 正常打包 且在项目内可以使用 在使用vitepress 开发文档时 运行无任何问题，能正常显示组件 可是打包一堆css报错。并且配置了 ssr
<img width="940" alt="image" src="https://github.com/vuejs/vitepress/assets/22837913/c8dd579b-3721-4905-a92d-fdca342cabcd">

### Reproduction

预期打包成功

### Expected behavior

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /Users/pengfeiren/Desktop/ld/ledu-design-vue/node_modules/.pnpm/element-plus@2.3.12/node_modules/element-plus/theme-chalk/base.css
    at new NodeError (node:internal/errors:393:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)

### System Info

```sh
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
    Memory: 88.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/Library/Caches/fnm_multishells/842_1694067466336/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/842_1694067466336/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.5.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
can you share this using https://vitepress.new ? It used to work fine IIRC. Can probably be a regression.

**Comment by pengfeir** [comment]
> 

https://stackblitz.com/edit/vite-cpd5am?file=vite.config.js

**Comment by pengfeir** [comment]
> Can you share this using https://vitepress.new ? It used to work fine IIRC. Can probably be a regression.



> 
Running npm run docs:dev allows you to preview, while running npm run docs:build reproduces the bug.

**Comment by MichaelGitArt** [comment]
Same. Using Vuetify

**Comment by brc-dd** [comment]
@pengfeir That vite.config.ts should be inside docs, or alternatively you can have `vite` option inside `docs/.vitepress/config.ts`. Also, since you're using `element-plus` through `test-design-vue`, you'll need to transpile `test-design-vue` as well. Here is an updated working example -- https://stackblitz.com/edit/vite-gjz9zf?file=docs%2F.vitepress%2Fconfig.ts

**Comment by pengfeir** [comment]
> @pengfeir That vite.config.ts should be inside docs, or alternatively you can have `vite` option inside `docs/.vitepress/config.ts`. Also, since you're using `element-plus` through `test-design-vue`, you'll need to transpile `test-design-vue` as well. Here is an updated working example -- https://stackblitz.com/edit/vite-gjz9zf?file=docs%2F.vitepress%2Fconfig.ts

I tried it and it works, thank you very much
