### ISSUE TITLE
How to add CSS animation to html element?

### ISSUE THREAD

**Issue by 1245906843** [vuejs/vitepress#2916]
### Describe the bug

我的项目是一个组件库，其中有一些CSS动画(比如[animation](animation: rotate 2s linear infinite;))。
在使用vitepress书写文档时，发现很多动画都没有显示。

我自己排查了下，发现是`src/client/theme-default/styles/base.css` 这个文件中使用!important声明了禁止动画的样式。导致我的CSS动画属性失效了。
```
@media (prefers-reduced-motion: reduce) {
  *,
  ::before,
  ::after {
    animation-delay: -1ms !important;
    animation-duration: 1ms !important;
    animation-iteration-count: 1 !important;
    background-attachment: initial !important;
    scroll-behavior: auto !important;
    transition-duration: 0s !important;
    transition-delay: 0s !important;
  }
}
````

目前的一个解决办法为：给元素声明animation时，使用!important提高优先级
animation: rotate 2s linear infinite !important;

### Reproduction

为html元素添加css动画，必现。
比如`animation: rotate 2s linear infinite;`

### Expected behavior

需要部分Vue组件或Html元素支持CSS动画。
有一个Vue组件的说明，需要有CSS动画以说明使用方法。如果可以的话，希望其他组件的动画也能正常展示。

### System Info

```sh
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 6.69 GB / 31.84 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-rc.10 => 1.0.0-rc.10
```

### Additional context

.vitepress\config.js
```
import { defineConfig } from 'vitepress';

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: 'QMWebUI',
  description: '...',
  head: [['link', { rel: 'icon', href: '...' }]],
  // https://vitepress.dev/reference/default-theme-config
  themeConfig: {
    logo: '...',
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Examples', link: '/markdown-examples' }
    ],

    outline: {
      label: '本页内容',
      level: [2, 3]
    },
    sidebar: [...],
    socialLinks: [
      {
        icon: {
          svg: 'xxx'
        },
        link: 'xxx'
      }
    ]
  }
});

```
.vitepress\theme\index.js
```
import DefaultTheme from 'vitepress/theme'
import '@tencent/qm-webui/lib/style.css';

export default DefaultTheme
```
### Validations

- [x] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Animations should be displayed normally unless the site user is emulating or have configured their browser or operating system that they want reduced motion. If you want to show the animation even then (not recommended), you can either add `!important` to your styles too, or add `vp-raw` class to your component or their parents and add the postcss config mentioned at https://vitepress.dev/guide/markdown#raw (toggle _details_).

**Comment by 1245906843** [comment]
> Animations should work fine unless the site user is emulating or have configured their browser or operating system that they want reduced motion. If you want to show the animation even then (not recommended), you can either add `!important` to your styles too, or add `vp-raw` class to your component or their parents and add the postcss config mentioned at https://vitepress.dev/guide/markdown#raw (toggle _details_).

我google了下这个偏好设置，发现MDN给出了win10系统下的设置方式：https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-reduced-motion；
我的电脑设置中的【在Windows中显示动画】这个开关已经被打开了。关闭这个按钮然后再重新打开，发现动画又能正常显示了。
行吧，估计是win10或者是Chrome的bug
