### ISSUE TITLE
Route Alias or Redirect

### ISSUE THREAD

**Issue by AgustinBanchio** [vuejs/vitepress#2922]
### Is your feature request related to a problem? Please describe.

Let's say we got a folder structure like this:

└─ foo
   ├─ 1.0.0.md
   ├─ 2.0.0.md
   └─ 3.0.0.md

Right now we would have routes like:
 `/foo/1.0.0.html`
 `/foo/2.0.0.html`
 `/foo/3.0.0.html`

I'd like to also have a route or alias like the following: `/foo/latest` which will point to the latest version (this can all be determined on build time by looking at the file, I already have a function that gives me the latest "route", in this case `/foo/3.0.0.html`.

How can I make this `/foo/latest` route exist and be an alias to the one I wanted?

### Describe the solution you'd like

Allow us to define route aliases or redirects

### Describe alternatives you've considered

I've tried with rewrites but that allowed me to make the latest version redirected to /latest instead. I want the reverse.

### Additional context

If this is not something you think vitepress should have because it's not SSG friendly (there is no latest.html file) then I understand.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This should be configured at your hosting-level. Where are you hosting your site?

**Comment by AgustinBanchio** [comment]
Yeah, I can add a vercel redirect.
Will I have to update the json each time a new version is out? Or is there a way to make it automatic on build?

**Comment by brc-dd** [comment]
You can automate it via some js script to find and replace version string. It can probably be a part of your release script where you bump your package version.

For example, if someone is using release-it, they can have this there:

```yaml
hooks:
  'after:bump':
    sed -i '' -e 's/${latestVersion}/${version}/g' vercel.json
```

But yeah, this is currently out-of-scope here. The best we can support is client-side redirects, but even for that we'll need to create double output for that latest version so that the server doesn't send 404.
