### ISSUE TITLE
add button on navbar

### ISSUE THREAD

**Issue by xiaoyunwu** [vuejs/vitepress#2925]
### Is your feature request related to a problem? Please describe.

How do I add a button on navbar?

### Describe the solution you'd like

some formatter for button on navbar. 

### Describe alternatives you've considered

n/a

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Use one of the `nav-` slots: https://vitepress.dev/guide/extending-default-theme#layout-slots
