### ISSUE TITLE
世界时钟小组件

### ISSUE THREAD

**Issue by CMEPCBHG** [vuejs/vitepress#2929]
### Is your feature request related to a problem? Please describe.

世界时钟显示数量太少了。

### Describe the solution you'd like

1.增加世界时钟可以显示的时钟数量。
2.增加一个时钟样式，例如2*4的样式中也可以显示数字时钟，而非表盘时钟，这样看时间会更加直观。

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What does this has to do with VitePress?
