### ISSUE TITLE
Last updated date formatter doesn't use the site `lang` from `config.ts`

### ISSUE THREAD

**Issue by alessandrojean** [vuejs/vitepress#2934]
### Describe the bug

The `Intl.DateTimeFormat` instance on the `<VPDocFooterLastUpdated>` component doesn't use the site `lang` attribute set in the settings. This leads to the date to be formatted using the navigator language even when the site might be written in other language.

https://github.com/vuejs/vitepress/blob/a1e1267549e198b35455d055536cd0c6d1ad79ce/src/client/theme-default/components/VPDocFooterLastUpdated.vue#L17-L23

### Reproduction

`.vitepress/config.ts`:

```typescript
import { defineConfig } from "vitepress"

export default defineConfig({
  // ... other attributes
  lang: 'en-US',
  lastUpdated: true,
  themeConfig: {
    text: 'Last updated',
    formatOptions: {
      dateStyle: 'long',
      timeStyle: 'short',
    },
  },
})
```

Then open the site in a browser with another language that's not `en-US`.

### Expected behavior

The date should follow the `lang` set in the `config.ts` file.

If this is by design, the `lastUpdated` attribute of the `themeConfig` property could allow setting a specific language to be used in the formatter instance instead.

### System Info

```Text
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 1.37 GB / 7.69 GB
    Container: Yes
    Shell: 3.6.0 - /usr/bin/fish
  Binaries:
    Node: 19.9.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 9.6.3 - /usr/bin/npm
    pnpm: 8.5.1 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.140
  npmPackages:
    vitepress: 1.0.0-rc.12 => 1.0.0-rc.12
```

### Additional context

The following image is the result of a site with `lang: 'en-US'` viewed in a browser with `pt-BR` language.

![image](https://github.com/vuejs/vitepress/assets/14254807/e21006f2-be64-4c58-a16d-6b18dd45a112)

Same issue as #1967 which was already fixed back in #2118.

Regressed by [`24abc7c`](https://github.com/vuejs/vitepress/commit/24abc7c6bda66df6e7ed543531f52c87f52f52df).

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This was intentional as the time should be in whatever format the users prefer, not the developer. Currently it respects the user's browser's time format. Why does a user having the browser in Portuguese is using the site in English?

**Comment by alessandrojean** [comment]
> Why does a user having the browser in Portuguese is using the site in English?

The site in question only has the English language available and doesn't have the intention to have other languages.

At our documentation, it doesn't make sense to use the user language from the browser to only format the date as everything else is in English. It's mixed language content we would want to avoid.

> This was intentional

If it's the case, can an option in the `lastUpdated` object be made for this as suggested?

**Comment by Soitora** [comment]
When a site is forcing UTC dates and is only written in a single language, it does indeed feel weird if timezones specifically were written localized
