### ISSUE TITLE
Enter key no longer selects result in local search

### ISSUE THREAD

**Issue by g-dx** [vuejs/vitepress#2935]
### Describe the bug

Commit e544b411d91eba54154243b0af4cea3226c192c4 was merged into `main` and released as part of RC12. 

[The PR](https://github.com/vuejs/vitepress/pull/2933) states that the search dialogue shouldn't be closed under a number of circumstances one of which is when the user presses enter. 

No justification is given for this or any description of what the intended behaviour should be. This is made even more confusing given the current UI explicitly states that Enter will select the item:

![image](https://github.com/vuejs/vitepress/assets/4189306/3f3cf0b2-f28a-4dad-842f-4a39b41bb7b0)

### Reproduction

Add the following Markdown files to a Vitepress site:

```markdown
# Overview

Some text ...
```

* Hit `Ctrl + K` and type "Overview".
* Hit enter.

### Expected behavior

When a user hits Enter the search dialogue should be dismissed and Vitepress should navigate to the selected entry.

### System Info

```Text
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 56.57 GB / 62.54 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    npm: 9.6.7 - /usr/bin/npm
    pnpm: 8.6.12 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Chromium: 116.0.5845.179
  npmPackages:
    vitepress: ^1.0.0-rc.12 => 1.0.0-rc.12
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by userquin** [comment]
Uhmm, ok, we must also check if there is no selected index...
