### ISSUE TITLE
能否提供页面颜色定制支持？

### ISSUE THREAD

**Issue by taozuhong** [vuejs/vitepress#2938]
### Is your feature request related to a problem? Please describe.

比如汶川大地震纪念日，页面都需要变成灰色来祭奠英灵，能否提供这样一种机制来支持这样的情况？

### Describe the solution you'd like

提供一种插件或者配置接口，提供两个参数：
1. 重要日子列表
2. 日期对应的页面颜色

当进入这个日期时，自动切换为该日期的颜色。一般需要提前准备，所以预配置会更好一些，然后机器自动判断。

### Describe alternatives you've considered

提供一种插件或者配置接口，提供两个参数：
1. 重要日子列表
2. 日期对应的页面颜色

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by re-ovo** [comment]
你可以自定义theme: https://vitepress.dev/guide/extending-default-theme#customizing-css

```js
// ./vitepress/theme/index.js
import DefaultTheme from 'vitepress/theme'
import './custom.css'

export default DefaultTheme
```
```css
html {
    filter: grayscale(100%);
    -webkit-filter: grayscale(100%);
}
```

没必要为这种小功能单独添加选项，太臃肿

**Comment by brc-dd** [comment]
This might be a too specific feature, which I don't think many users will use. It might be better to refer the docs on customizing CSS and override them yourself and deploy the site near those days manually. Alternatively, extend the default theme and add code in your script setup to check the date and inject corresponding css into head.
