### ISSUE TITLE
Vite alias overwrite component. The origin component css save in bundler assert.

### ISSUE THREAD

**Issue by Zhengqbbb** [vuejs/vitepress#2945]
### Describe the bug

I am trying to use vite [alias overwrite component](https://vitepress.dev/guide/extending-default-theme#overriding-internal-components). Such as `VPNavbar`. Works fine in the page display

But after building I found that the `dist/assets/style.css` file still retains the styles in the component that origin component style.

### Reproduction

https://stackblitz.com/edit/vite-vfhomn?file=docs%2F.vitepress%2Fconfig.ts

`npm run build` and check style file `dist/assets/style.css`

<img width="1624" alt="image" src="https://github.com/vuejs/vitepress/assets/40693636/85469507-fa9b-4e8f-b76a-a2ee2fc86bbb">

### Expected behavior

Remove origin component's style

### System Info

```Text
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 115.05 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.5.2
```

### Additional context

I'm not sure if this is a bug or the vite alias design, but it's look like not a perfect overwrite. I want to get a css asset as small as possible.

If there is a configuration that can be removed, welcome share with me. 🙌

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Zhengqbbb** [comment]
Using postcss + rule match have removed

**Comment by brc-dd** [comment]
Still seems like a bug to me. I'll take a closer look once I've got some time. Reopening this for now.

**Comment by brc-dd** [comment]
Ah, not a bug. VPNavScreen is not inside VPNavBar:

https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPNav.vue#L26-L37

You'll need to alias VPNav.vue if you want VPNavScreen styles to not leak 👀
