### ISSUE TITLE
SIdebar is not clickable on refresh.

### ISSUE THREAD

**Issue by AnilSonix** [vuejs/vitepress#2949]
### Describe the bug

The sidebar is not clickable on refresh.

### Reproduction

1. Visit  https://vitepress.dev/
2. Click on "Get Started".
3. The sidebar is clickable and it works.
4. Do a refresh
5. Now it doesn't work

Again if we go to the home page by clicking on the top left home link.
and then click on "Get Started".
The SIdebar works.
Again if refreshed, it's not clickable.

### Expected behavior

The sidebar should be clickable.

### System Info

```Text
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
    Memory: 1.57 GB / 7.93 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 116.0.5845.180
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
```

### Additional context

Looks similar to #2936

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by vanhiupun** [comment]
Looks like I'm having the same problem

**Comment by tmosmant** [comment]
This is happening in prod for me, but not on my local environment.

**Comment by vijay0726** [comment]
me too.The page can't be clicked on the table of contents in siderbar, but I found that when the window size changes and I switch to the mobile layout, I can click

**Comment by vanhiupun** [comment]
Updating to `v1.0.0-rc.13` should solve the problem
