### ISSUE TITLE
How to force dark mode on

### ISSUE THREAD

**Issue by vanhiupun** [vuejs/vitepress#2960]

**Comment by brc-dd** [comment]
Set `appearance: 'dark'` in your `.vitepress/config.ts`?

**Comment by vanhiupun** [comment]
This works, but at the same time I want to hide the toggle button and lock dark mode

**Comment by brc-dd** [comment]
Something like this might work:

```ts
  appearance: false,
  head: [['script', {}, `document.documentElement.classList.add('dark')`]],
```

**Comment by vanhiupun** [comment]
Thank you for answering my questions and good luck
