### ISSUE TITLE
Error in Previous page and Next page

### ISSUE THREAD

**Issue by javinba** [vuejs/vitepress#2961]
### Describe the bug

When I go to my FAQ tab, for example, I have a series of articles in my sidebar. 
For each of them the link to the next page is always the link to the first article.

### Reproduction

My configuration is something like this
```
"/en/faq/": [
            {
              text: 'FAQ',
              items: [
                { text: 'foo text', link: './foo-link' },
                { text: 'bar text', link: './bar-link' },
```
If I modify it to :

```
"/en/faq/": [
            {
              text: 'FAQ',
              items: [
                { text: 'foo text', link: '/en/faq/foo-link' },
                { text: 'bar text', link: '/en/faq/bar-link' },
```
It works correctly but I think it's a bit of a pain to have to add the prefix to all links.

### Expected behavior

I would expect it to work correctly with:
```
"/en/faq/": [
            {
              text: 'FAQ',
              items: [
                { text: 'foo text', link: './foo-link' },
                { text: 'bar text', link: './bar-link' },
```

### System Info

```Text
System:
    OS: Linux 6.4 Fedora Linux 38 (Container Image)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 8.57 GB / 15.25 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.1/bin/npm
  npmPackages:
    vitepress: ^1.0.0-rc.10 => 1.0.0-rc.13 
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Relative links are resolved relative to the current page. They aren't recommended as then the sidebar will have different links depending on where the user is at moment. You can do something like this instead:

```ts
 '/en/faq/': { base: '/en/faq/', items: [ { text: 'foo text', link: 'foo-link' }, ...
```

**Comment by javinba** [comment]
Perfect, thank you for your time and advice :blush: .

Best regards!
