### ISSUE TITLE
head 引入脚本提示未定义

### ISSUE THREAD

**Issue by y-pp** [vuejs/vitepress#2966]
### Describe the bug

当我按顺序引入js脚本的时候，后面的脚本依赖于前面的，问题入下图

### Reproduction

https://stackblitz.com/edit/vite-yl3bnx

### Expected behavior

预期是不会产生 is not defined. 这个错误

### System Info

```Text
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 147.43 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 20.0.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 117.0.5938.62
    Safari: 15.4
  npmPackages:
    vitepress: ^1.0.0-rc.13 => 1.0.0-rc.13
```

### Additional context

<img width="521" alt="image" src="https://github.com/vuejs/vitepress/assets/17758990/61b1827b-79f7-4b89-8db4-29061ba08a02">
<img width="649" alt="image" src="https://github.com/vuejs/vitepress/assets/17758990/4757b2c1-35b6-4336-bd4a-f9731418dc82">

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That `lib` directory should be inside `docs/public` directory. Then on build the code will work fine. There is still a bug in dev though.

**Comment by y-pp** [comment]
> That `lib` directory should be inside `docs/public` directory. Then on build the code will work fine. There is still a bug in dev though.

好的，谢谢！
