### ISSUE TITLE
I keep getting [vite] Internal server error: The request url "/path" is outside of vite dev server root "/path".  when using vitepress

### ISSUE THREAD

**Issue by romain130492** [vuejs/vitepress#297]
**Describe the bug**
* I keep getting `I keep getting [vite] Internal server error: The request url "/path" is outside of vite dev server root "/path". ` when doing `vitepress dev docs`, 
* i dont get that error on build and serve

**To Reproduce**
* In order to reproduce that bug you can simply use that [repository](https://github.com/gwenf/vue3-vitepress-demo)

**Expected behavior**

**System Info**
- vitepress version: 0.10.7 and "^0.13.2"
- vite version:
- Node version:
- OS version:

**Additional context**

<img width="487" alt="Screen Shot 2021-05-11 at 7 32 04 PM" src="https://user-images.githubusercontent.com/57079606/117808548-98e2cd00-b28f-11eb-96ca-1c36502e4c8d.png">

**Comment by romain130492** [comment]
oh man, thanks!

**Comment by cfife-btig** [comment]
I think the answer above is a little OOD

If you are trying to access a file that's outside the root (.i.e. one level above), I was able to get it to work using 

```
export default defineConfig({
  server: {
    fs: {
      allow: ['..']
    }
  }
})
```
