### ISSUE TITLE
Easier Overriding of Internal Components

### ISSUE THREAD

**Issue by phill2mj** [vuejs/vitepress#2976]
### Is your feature request related to a problem? Please describe.

Right now (unless I'm not understanding the correct method) it seems difficult to override core theme componentry. Say I want to edit the NavBar template; I have to either write a completely new implementation from scratch (sacrificing a lot of features built in to the framework like the hamburger menu, and the configurable data expressed to navbar links, logo image, site title, etc. This seems to be because those components are part of the core library and not exported anywhere to be reused, so there's a big block of reused components like
```
<VPNavBarSearch class="search" />
<VPNavBarMenu class="menu" />
<VPNavBarTranslations class="translations" />
<VPNavBarAppearance class="appearance" />
<VPNavBarSocialLinks class="social-links" />
<VPNavBarExtra class="extra" />
<slot name="nav-bar-content-after" />
<VPNavBarHamburger class="hamburger" :active="isScreenOpen" @click="$emit('toggle-screen')" />
```
and those would either have to be copied and/or reimplemented inside my project if all I wanted to do, for example, was put the site title/logo in the middle of the navbar instead of the left side.

### Describe the solution you'd like

I'm still learning Vue, but it seems like if these core theme components could be exported from the vitepress library, they could be imported instead of reimplemented if all I wanted to do was copy the NavBar template and edit it a bit.

### Describe alternatives you've considered

The alternative right now seems to be either copying all these theme files into my project, reimplementing them, or not using them and sacrificing their utility.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can import them like `import VPNavBarSearch from 'vitepress/dist/client/theme-default/components/VPNavBarSearch.vue'`

The types aren't exported yet. Track #2595 for that.

**Comment by phill2mj** [comment]
Ok, that's very helpful! Thanks! Looking forward to typing and import help. Having fun with with this library so far.
