### ISSUE TITLE
Cannot jump to the directory when clicking on it

### ISSUE THREAD

**Issue by vanhiupun** [vuejs/vitepress#2979]
Recently I found that my website cannot redirect when clicking on the directory.
I'm not sure what's wrong with my settings,
Set `outline: deep` in each article
Or setting `cleanUrls` to `false` or `true` cannot correct the error.

**Comment by brc-dd** [comment]
Please provide a reproducible example.

**Comment by vanhiupun** [comment]
I found the problem,
When I configure the `markdown` option the code is as follows：
```ts
  // markdown
  markdown: {
    theme: "material-theme-palenight",
    lineNumbers: true,
    anchor: {
      slugify(str) {
        return encodeURIComponent(str);
      },
    },
  },
  },
```

So I deleted the last paragraph and everything was normal.：
```ts
  markdown: {
    theme: "material-theme-palenight",
    lineNumbers: true,
  },
```

**Comment by brc-dd** [comment]
Handling all those cases would be quite tricky. I'd remove the mention of that `encodeURIComponent` slugify from our docs. As a user, you should make sure the returned value from slugify has no percent-encoded characters.
