### ISSUE TITLE
Setting base path doesn't set logo path

### ISSUE THREAD

**Issue by akshaybabloo** [vuejs/vitepress#2981]
### Describe the bug

Setting the base path on GitHub pages does not update the path for logo

### Reproduction

1. Create a new app
2. Set the `base` path to something eg: `/hello/`
3. Set your logo to `/logo.<ext>`

Here is what I have - https://github.com/akshaybabloo/dotfiles/tree/main/docs

### Expected behavior

The path after generation should be `<ulr>/hello/logo.<ext>` but it generates `<url>/logo.<ext>`

### System Info

```Text
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 18.87 GB / 31.07 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
  Browsers:
    Brave Browser: 117.1.58.127
    Chrome: 117.0.5938.88
  npmPackages:
    vitepress: ^1.0.0-rc.12 => 1.0.0-rc.14
```

### Additional context

I am using Bun as my package manager.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not reproducible.
