### ISSUE TITLE
Support fast-glob options in createContentLoader

### ISSUE THREAD

**Issue by huluobotx** [vuejs/vitepress#2985]
### Is your feature request related to a problem? Please describe.

I want to ignore some files and folders, especially in the srcExclude configuration, but I cannot pass fast global options.

### Describe the solution you'd like

The parameters of createContentLoader only support strings and arrays. hope it support objects to pass fast global options

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
As I mentioned on your PR won't this work? https://github.com/vuejs/vitepress/pull/2963#issuecomment-1722182648

**Comment by huluobotx** [comment]
> As I mentioned on your PR won't this work? [#2963 (comment)](https://github.com/vuejs/vitepress/pull/2963#issuecomment-1722182648)

I have tried using negative patterns, and in some cases it works and in others it doesn't, especially when using './' as the starting path and excluding both files and folders.
Use fast-glob options is easy to implement my require.
```
const excludeDirs = exclude_dir && exclude_dir.length > 0 ? ('/**/!(' + exclude_dir.join('|') + ')/') : '/'
const excludeDirs2 = exclude_dir && exclude_dir.length > 0 ? ('/!(' + exclude_dir.join('|') + ')/') : '/'
const excludeFiles = exclude_file && exclude_file.length > 0 ? ('!(' + exclude_file.join('|') + ')') : '*'
const glob = [`./${srcDir}${excludeDirs}**/${excludeFiles}.md`, `./${srcDir}${excludeDirs2}**/${excludeFiles}.md`, `./${srcDir}/${excludeFiles}.md`]
// console.log(srcDir, exclude_file, exclude_dir, glob)
export default createContentLoader(glob, {
```

**Comment by brc-dd** [comment]
It will be there in the next version. `createContentLoader(..., { globOptions: {...} })`
