### ISSUE TITLE
How to break line in blockquote?

### ISSUE THREAD

**Issue by you-hengh** [vuejs/vitepress#2986]
### Describe the bug

I cannot line break when using `blockquote` in vitepress, like this:

<img width="959" alt="image" src="https://github.com/vuejs/vitepress/assets/34816426/92c4c5e7-898b-4112-a0e6-f48ce94ec737">

### Reproduction

In vscode:

<img width="859" alt="image" src="https://github.com/vuejs/vitepress/assets/34816426/51edd8cf-ffd2-4151-85c0-d93963a1e1e7">

In the development page of Vitepress:

<img width="1074" alt="image" src="https://github.com/vuejs/vitepress/assets/34816426/2587c0d5-20c4-4691-a751-c227980f8e25">

They are on the same line now, what method should I use to keep them on separate lines? This is not the result I want.

<img width="1077" alt="image" src="https://github.com/vuejs/vitepress/assets/34816426/57f8a8fb-ffba-47bb-a808-6940e1ac4ae6">

### Expected behavior

I hope it is like this.

<img width="959" alt="image" src="https://github.com/vuejs/vitepress/assets/34816426/92c4c5e7-898b-4112-a0e6-f48ce94ec737">

### System Info

```Text
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 564.50 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.1 - ~/Library/pnpm/node
    npm: 9.8.1 - ~/Library/pnpm/npm
    pnpm: 8.6.3 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 117.0.5938.62
    Safari: 16.6
  npmPackages:
    vitepress: 1.0.0-rc.13 => 1.0.0-rc.13
```

### Additional context

null

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
```md
> foo
>
> bar
```
