### ISSUE TITLE
Build & Dev behaves differently: Build does not update reactive class name on the first page render

### ISSUE THREAD

**Issue by bastiW** [vuejs/vitepress#2995]
### Describe the bug

I am checking for the active route.

When I run the build I notice the following when loading the page the first time:

- The text part `{{isActiveRoute(href)? 'active': 'inactive'}}` is updated ✔️
- The `:class="{'link--active': isActiveRoute(href)}"` is not updated on first render. ❌
- When navigating to another router and back the `:class` is updated ✔️

The HTML output on build on first render is:

```html
<ul>
   <li><a href="/" class="">active: Home</a></li>
   <li><a href="/markdown-examples.html" class="">inactive: Markdown Examples</a></li>
   <li><a href="/api-examples.html" class="">inactive: API Examples</a></li>
</ul>
```

![image](https://github.com/vuejs/vitepress/assets/7667003/9472c0ab-b716-4a0e-ba47-41b9097b5bf2)

### Reproduction

[Reproduction Repository](https://github.com/bastiW/vitepress-reproduce-reactive-class)

The code:

```vue

<script setup lang="ts">
import { useData, useRoute } from 'vitepress'

// https://vitepress.dev/reference/runtime-api#usedata
const { site, frontmatter } = useData()

const route = useRoute()

type NavItem = {
  href: string,
  name: string
}

const navItems: NavItem[] = [
  {
    href:'/',
    name: 'Home'
  },
  {
    href:'/markdown-examples.html',
    name: 'Markdown Examples'
  },
  {
    href: '/api-examples.html',
    name: 'API Examples'
  }
]

const isActiveRoute = (url: string) => {
  return route.path === url
}


</script>

<template>
    <ul v-for='({ href, name  }) of navItems'>
      <li>
        <a :href="href" :class="{'link--active': isActiveRoute(href)}">{{isActiveRoute(href)? 'active': 'inactive'}}: {{name}}</a>
      </li>
    </ul>
    <Content />
</template>

<style>
  .link--active {
    font-weight: bold;
  }
</style>

```

### Expected behavior

Should be the same as in dev mode: When loading the page the first time:

- The text part `{{isActiveRoute(href)? 'active': 'inactive'}}` is updated ✔️
- The `:class="{'link--active': isActiveRoute(href)}"` is updated on first render. ✔️

The HTML output on build on first render should be same as in dev mode:

```html
<ul>
   <li><a href="/" class="link--active">active: Home</a></li>
   <li><a href="/markdown-examples.html" class="">inactive: Markdown Examples</a></li>
   <li><a href="/api-examples.html" class="">inactive: API Examples</a></li>
</ul>
```
![image](https://github.com/vuejs/vitepress/assets/7667003/703fe3ab-98ce-4f39-8b9d-f9f80ebf9f19)

### System Info

```Text
Error can also be reproduced on vercel.

Local install

System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
    Memory: 1.28 GB / 7.92 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.3.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 116.0.5845.188
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.31)
  npmPackages:
    vitepress: ^1.0.0-rc.14 => 1.0.0-rc.14
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That repository is not public.

**Comment by bastiW** [comment]
Seems to be that the issue also only happens on `/` page. Not on the other pages.

**Comment by brc-dd** [comment]
Try something like this instead:

```vue
<script setup lang="ts">
import { useData } from 'vitepress';

const { site, frontmatter, page } = useData();

type NavItem = {
  href: string;
  name: string;
};

const navItems: NavItem[] = [
  {
    href: '/',
    name: 'Home',
  },
  {
    href: '/markdown-examples.html',
    name: 'Markdown Examples',
  },
  {
    href: '/api-examples.html',
    name: 'API Examples',
  },
];

const isActiveRoute = (url: string) => {
  return (
    page.value.relativePath
      .replace(/\.md$/, '.html')
      .replace(/\bindex\.html$/, '') === url.slice(1)
  );
};
</script>

<template>
  <ul v-for="{ href, name } of navItems">
    <li>
      <a :href="href" :class="{ 'link--active': isActiveRoute(href) }">
        {{ isActiveRoute(href) ? 'active' : 'inactive' }}: {{ name }}
      </a>
    </li>
  </ul>
  <Content />
</template>

<style>
.link--active {
  font-weight: bold;
}
</style>
```

Seems like a but with vue itself rather than vitepress. Feel free to create an issue at https://github.com/vuejs/core, although it doesn't seem to be reproducible on the SFC playground. But since the hydration is working properly for text but not for the classes, I'm not sure.

**Comment by brc-dd** [comment]
It appears that during SSR, `route.path` is `/index.html` instead of `/`. That's why different result for that path.

**Comment by bastiW** [comment]
Thanks a lot for your help
