### ISSUE TITLE
Cannot find package 'vue' 

### ISSUE THREAD

**Issue by changbb** [vuejs/vitepress#2998]
### Describe the bug
执行pnpm run docs:build
打包的时候报错！
![image](https://github.com/vuejs/vitepress/assets/23628509/3a0fb304-02a9-4912-bb58-47992f35b706)

### Reproduction

当进行打包的时候会出现
node版本：18.18.0
pnpm版本：8.7.6
windows系统

### Expected behavior

可以正常打包不报错

### System Info

```Text
Cannot find package 'vue' imported from C:\Users\changbb\node_modules\vue-demi\lib\index.mjs
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Which vitepress version are you on?

**Comment by changbb** [comment]
> Which vitepress version are you on and please share your index.md as well.

1.0.0-rc.14

**Comment by brc-dd** [comment]
Doesn't seem to be reproducible at my end. Can you retry `pnpm install`?

/cc @zonemeen hey, do you have a windows device at hand? can you confirm if this is happening with a new project? 👀

**Comment by changbb** [comment]
> Doesn't seem to be reproducible at my end. Can you retry `pnpm install`?
> 
> /cc @zonemeen hey, do you have a windows device at hand? can you confirm if this is happening with a new project? 👀

我尝试删除node_modules并重新pnpm install多次，pnpm run docs:dev 是正常的，但是pnpm run docs:build依然报错

**Comment by zonemeen** [comment]
@brc-dd It's fine when running a new project on my Windows device.
