### ISSUE TITLE
build --watch failed since vite@2.2.0

### ISSUE THREAD

**Issue by linbudu599** [vuejs/vitepress#300]
**Describe the bug**

I'm facing the error just like #110 , that one issue was closed because problem fixed in 0.7.1, but now it just appears again because vite is updating so quickly...

The reason of this problem:

- vitepress use `vite build` to handle `vitepress build`.
- since [vite@2.2.0](https://github.com/vitejs/vite/blob/v2.2.0/packages/vite/src/node/build.ts#L440), watching-build is enabled, when using `build --watch`, or pass `watch: true` to `build` method, **it returns `rollup-watcher` instead of `rollup-output`**.
- vitepress depends on rollup-output to generate chunks, related code: [bundle](https://github.com/vuejs/vitepress/blob/master/src/node/build/bundle.ts#L82) ,[build](https://github.com/vuejs/vitepress/blob/master/src/node/build/build.ts#L15-L27)(clientResult is a intance of rollup [WatchEmitter](https://github.com/rollup/rollup/blob/dba6f13132a1d7dac507d5056399d8af0eed6375/src/watch/watch-proxy.ts#L8), so we got error `Cannot read property 'find' of undefined`), so if user is using **Vite version >= 2.2.0**, `vitepress build docs --watch` will failed.
- A tmp solution is lock vite version under 2.2.0, but as vite develops so quick, this is not indeed a soluation.

**To Reproduce**

Using `vite >= 2.2.0`, and run `vitepress build docs --watch`

**Expected behavior**

**System Info**
- vitepress version: 0.13.2
- vite version: 2.3.0
- Node version: 15.1.0
- OS version: Windows 10

**Additional context**

**Comment by kiaking** [comment]
Can anyone confirm this still happening on `next-theme` branch?

**Comment by brc-dd** [comment]
Closing this as stale.
