### ISSUE TITLE
Support to show page contributors

### ISSUE THREAD

**Issue by KeroZhai** [vuejs/vitepress#3001]
### Is your feature request related to a problem? Please describe.

Nope.

### Describe the solution you'd like

Provide a config option, like `lastUpdated`.

### Additional context

Not very familiar with Node and Vite. I tried to do it on my own, but failed with 'process is not defined'. Any help?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Do something like this:

```ts
// .vitepress/config.ts
import Git from 'simple-git'

const git = Git({
  maxConcurrentProcesses: 200
})

// taken from vueuse
async function getContributorsAt(path: string) {
  try {
    const list = (
      await git.raw(['log', '--pretty=format:"%an|%ae"', '--', path])
    )
      .split('\n')
      .map((i) => i.slice(1, -1).split('|') as [string, string])
    const map: Record<string, { name: string; count: number }> = {}

    list
      .filter((i) => i[1])
      .forEach((i) => {
        if (!map[i[1]]) {
          map[i[1]] = {
            name: i[0],
            count: 0
          }
        }
        map[i[1]].count++
      })

    return Object.values(map)
      .sort((a, b) => b.count - a.count)
      .map((i) => i.name)
  } catch (e) {
    console.error(e)
    return []
  }
}

export default defineConfig({
  // ...,
  async transformPageData({ relativePath }) {
    return { contributors: await getContributorsAt(relativePath) }
  }
})
```

Then in your theme or docs, you can use this by doing something like this:

```vue
<script setup>
import { useData } from 'vitepress'
import { computed } from 'vue'

const { page } = useData()
const contributors = computed(() => page.value.contributors)
</script>
```
