### ISSUE TITLE
Push the website to Github Pages

### ISSUE THREAD

**Issue by theadanielskocher** [vuejs/vitepress#3002]
I have finished my website and I want to push my website to Github pages by hand, but nothing works. How can I address this issue?

![image](https://github.com/vuejs/vitepress/assets/88028913/0448a283-d089-486a-aa1f-48acdd7240ae)

Thank you for your answer!

**Comment by brc-dd** [comment]
Please follow the deploy guide - https://vitepress.dev/guide/deploy#github-pages and if any issue arises, create one with proper debugging information including a minimal reproducible example and the steps you followed.
