### ISSUE TITLE
reference style links not working on custom container title

### ISSUE THREAD

**Issue by rin-w** [vuejs/vitepress#3004]
### Describe the bug

reference style link not rendering on container title

![image](https://github.com/vuejs/vitepress/assets/36298836/b2237dda-6497-42db-aa20-7922efc88a79)

### Reproduction

```md
::: info Software ([latest][link-latest], [stable][link-stable])

Software stable is cool, but Software latest is cooler.

:::

[link-latest]: <https://download/link-latest>
[link-stable]: <https://download/link-stable>
```

### Expected behavior

![image](https://github.com/vuejs/vitepress/assets/36298836/1f3c9a1e-d932-4640-bffe-171b3d60335c)

```md
::: info Software ([latest](https://download/link-latest), [stable](https://download/link-stable))

Software stable is cool, but Software latest is cooler.

:::
```

### System Info

```Text
System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 3.70 GB / 7.95 GB
  Binaries:
    Node: 18.12.0 - C:\laragon-portable\bin\nodejs\node-v18\node.EXE
    npm: 9.6.6 - C:\laragon-portable\bin\nodejs\node-v18\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.1
  npmPackages:
    vitepress: ^1.0.0-rc.10 => 1.0.0-rc.15
```

### Additional context

idk why it says IE11. i use a chrome/firefox browser

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That title is rendered inline. I don't think if we can support link references there.
