### ISSUE TITLE
Supporting Shikiji Instead of Shiki

### ISSUE THREAD

**Issue by shellscape** [vuejs/vitepress#3006]
### Is your feature request related to a problem? Please describe.

[Shikiji](https://github.com/antfu/shikiji) is the next iteration of Shiki by the same author.

>  An ESM-focused rewrite of [shiki](https://github.com/shikijs/shiki), a beautiful syntax highlighter based on TextMate grammars. And [a little bit more](https://github.com/antfu/shikiji#additional-features).

Here are the notable changes between the two: https://github.com/antfu/shikiji#changes

This is the most compelling difference imho https://github.com/antfu/shikiji#fine-grained-bundle which results in an even _smaller_ bundle, which means an even _faster_ load. For a static site generator, this would be a nice improvement.

### Describe the solution you'd like

Perhaps a configuration option to swap in Shikiji.

Perhaps a lively discussion about replacing Shiki with Shikiji

### Describe alternatives you've considered

Tried hacking around Shiki but there's not much there that can be accomplished. 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah we are tracking this internally.

**Comment by davidglezz** [comment]
https://github.com/shikijs/shiki/issues/424#issuecomment-1701273142

**Comment by brc-dd** [comment]
#3237
