### ISSUE TITLE
bottom page navigation link always directs to first page when using base URLs for sidebar

### ISSUE THREAD

**Issue by rin-w** [vuejs/vitepress#3010]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/36298836/befed400-c0c5-4493-8014-4568069af914)

same happens when there's another `base: '/section2/',` in sidebar

### Reproduction

config:
```ts
export default defineConfig({

...

    sidebar: [
      {
        base: '/section/',
        items: [
          { text: 'First', link: '/first' },
          { text: 'Second', link: '/second' },
          { text: 'Third', link: '/third' },
        ]
      },
    ],

...
```

folder structure:

![image](https://github.com/vuejs/vitepress/assets/36298836/d56ab009-8655-4d1c-8a1f-e75aee7f77ad)

### Expected behavior

![image](https://github.com/vuejs/vitepress/assets/36298836/29bfca7f-02c5-404d-8ab6-30e7b2cecbe9)

(like without the base link and md files stored in parent folder)

### System Info

```Text
rc20, windows
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You probably meant to use `base: '/section',` or `link: 'first'`, `link: 'second'`... (base is simply concatenated, double slash are not removed.
