### ISSUE TITLE
Add support for images in different languages

### ISSUE THREAD

**Issue by javinba** [vuejs/vitepress#3012]
### Is your feature request related to a problem? Please describe.

I have a project with the following structure:
```
docs/
├─ en/
│ ├─ foo.md
├─ fr/
│ ├─ foo.md
├─ index.md
```

I would like to be able to easily manage images for different languages by being able to select a default language for cases where there is no translation for that image.

### Describe the solution you'd like

I would like to have a folder with images for each language and that for example if a file located in `es/` contains `![](/foo.png)` it would look first in the folder inside public for images `public/es/` for the image `foo.png` and if it is not found there it would look in `public/en/`.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This seems be too specific to your needs and I don't think many people will benefit from this. You can easily implement this using a markdown-it plugin.

Closing this for now. If there is significant demand, we might consider this later.
