### ISSUE TITLE
Head styles reload on each page navigation

### ISSUE THREAD

**Issue by davestewart** [vuejs/vitepress#3013]
### Describe the bug

VitePress completely reloads head stylesheets on each page navigation.

This causes the page to de-style then re-style.

### Reproduction

https://stackblitz.com/edit/vite-jkgh1y?file=docs%2Findex.md

### Expected behavior

Once styles are loaded in, no reload on navigation

### System Info

```Text
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 64.77 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.3.1 - ~/.npm-packages/bin/pnpm
    Watchman: 2023.09.18.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 117.1.58.127
    Chrome: 116.0.5845.187
    Chrome Canary: 119.0.6028.0
    Edge: 117.0.2045.40
    Safari: 16.0
  npmPackages:
    vitepress: ^1.0.0-rc.20 => 1.0.0-rc.20
```

### Additional context

Have only tried in dev, but still, it shouldn't happen.

Tried on two local projects, also went back to rc-10, it still does it there

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I can implement a check, but it will need you to specify `id` on your element (`['link', { id: '...', ... }]`), without that the implementation will have to rely on isEqualNode + nested loops -- that'd be quite slow.

**Comment by davestewart** [comment]
Hey Divyansh.

I updated the repo and added an `id` as suggested, but the files still load in each time.

The import (locally!) fixed it.

What would i do if I wanted the files from a CDN?

**Comment by davestewart** [comment]
Oh - wow, world's quickest fix! 🙏

**Comment by brc-dd** [comment]
In next version it should work fine from head too (without any need to specify id).
