### ISSUE TITLE
hi sir, the bug of custom theme

### ISSUE THREAD

**Issue by amin2312** [vuejs/vitepress#3015]
### Describe the bug

When I create a project using a custom theme, it display empty code style in markdown file

### Reproduction

When I create a project using a custom theme, it display empty code style in markdown file

### Expected behavior

right code style

### System Info

```Text
last versoin
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That's expected. You need to write your own styles if you're choosing the "Custom Theme" option in the init wizard. Choose "Default Theme + Customization" if you want to extend the default theme.
