### ISSUE TITLE
Hook on route change (for analytics)

### ISSUE THREAD

**Issue by IlyaSemenov** [vuejs/vitepress#302]
**Is your feature request related to a problem? Please describe.**
It's not currently possibly to easily add external analytics module, such as Google Analytics or Yandex Metrika, because there's no documented way to hook on page change event.

**Describe the solution you'd like**
I'd like the router to have `router.afterEach((route) => { /* emit analytics event here */ })` similar to how I can achieve the same with vue-router.

**Describe alternatives you've considered**
I'm using this at the moment:
```ts
import { watch } from "vue"
import default_theme from "vitepress/dist/client/theme-default"

const theme: Theme = {
	...default_theme,
	enhanceApp({ router }) {
		watch(
			() => router.route.path,
			(path) => {
				// track page change
			}
		)
	})
}

export default theme
```

However I'm not confident it's an ideal solution. In particular, it relies on the undocumented fact that `route` is a reactive object.

**Comment by posva** [comment]
You can `watch` the route safely as we rely on it being reactive to render the content

**Comment by MartinMalinda** [comment]
In case anyone's wondering, this has worked for me in the Layout component:

```ts
import { useRouter } from 'vitepress';
const router = useRouter();

// Only run this on the client. Not during build.
if (typeof window !== 'undefined' && window.ga) {
  watch(() => router.route.data.relativePath, (path) => {
      console.log(path);
      ga('send', 'pageview', path);
  }, { immediate: true });
}
```
