### ISSUE TITLE
Hi sir, how to remove the code block of dark mode

### ISSUE THREAD

**Issue by amin2312** [vuejs/vitepress#3022]
### Describe the bug

I found that the markdown file generated two code blocks, one for light mode, one for dark
I can't find any ban sign from the official website to turn it off

### Reproduction

as describe

### Expected behavior

as describe

### System Info

```Text
as describe
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
```ts
// .vitepress/config.ts
import { defineConfig } from 'vitepress';

export default defineConfig({
  appearance: false,
  markdown: {
    theme: 'github-light',
  },
});
```

**Comment by amin2312** [comment]
thanks for your help
