### ISSUE TITLE
can't get anything defined by `defineExpose`  from component ref

### ISSUE THREAD

**Issue by ishowman** [vuejs/vitepress#3023]
### Describe the bug

If a component is using `defineClientComponent`, everything exposed by `defineExpose` is missing via component's ref value.

### Reproduction

# Example

create `Editor.vue`
```vue
<script setup lang="ts">
// ...
defineExpose({
  getHtml,
  setHtml,
});
</script>
```

using `Editor.vue` in `Page.vue`
```vue
<template>
  <Editor ref="editor" />
<button @click="clear">clear all</button>
</template>

<script setup lang="ts">
// ...
  import { ref } from 'vue';
  const editor = ref();

  const clear = () => {
    console.log(`editor.value`, editor.value);
    editor.value.setHtml();
  }

</script>
```

# When using `defineClientComponent` it can't not found `setHtml`
- `docs\.vitepress\theme\index.js`  config:
```
export default {
  ...DefaultTheme,
  async enhanceApp(ctx) {
    const app = ctx.app;
    // ...
   if (!import.meta.env.SSR) {
      const Editor = defineClientComponent(() => {
        return import('../../../src/components/Editor.vue');
      })
      app.component('editor', Editor);
   }
  }
}
```
- click `clear all` button
- the result is :
  -:devtool tell me:editor.value.setHtml is not a function
  - `editor.value` object missing `setHtml` 

# When not using `defineClientComponent` it work normally
- `docs\.vitepress\theme\index.js`  config:
```
import Editor from '../../../src/components/Editor.vue'
export default {
  ...DefaultTheme,
  async enhanceApp(ctx) {
    const app = ctx.app;
    // ...
   if (!import.meta.env.SSR) {
      app.component('editor', Editor);
   }
  }
}
```
- click `clear all` button
- the result is :
  - editor.value.setHtml is called
  - console tab `editor.value` object has `setHtml` 

### Expected behavior

defineExpose works in defineClientComponent component

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.18 GB / 7.86 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.43)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-rc.20 => 1.0.0-rc.20
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You'll need to pass ref to defineClientComponent itself:

```ts
const editor = ref()

const Editor = defineClientComponent(
  () => import('/path/to/editor',
  [{ ref: editor }]
)

...


<Editor />
```

**Comment by brc-dd** [comment]
This is already documented at https://vitepress.dev/guide/ssr-compat#defineclientcomponent, and I don't think Vue allows forwarding refs (i.e. syntax like `<Editor ref="editor" />` such that the child can inherit that ref.)
