### ISSUE TITLE
Tags (keywords) taxonomy

### ISSUE THREAD

**Issue by noraj** [vuejs/vitepress#3029]
### Is your feature request related to a problem? Please describe.

Rather the lack of ability to do something.

### Describe the solution you'd like

Having a default tag taxonomy with tags displayed on each page and pointing to the corresponding tag index.

Extensive explanation of the tag support idea: https://github.com/intuit/Ignite/issues/126 (tags display on pages, tags index, tags list, etc.)

## Examples

Examples in other staticgen:

- Retype (documentation) https://retype.com/configuration/page/#tags
- Hexo (blog) https://hexo.io/docs/front-matter

Screenshot on retype:

Tags button embedded on a page: ![image](https://github.com/Doctave/doctave/assets/16578570/83802686-81ff-47e0-9cb7-a58f006fa64e)

A tag index (https://retype.com/tags/config/): ![image](https://github.com/Doctave/doctave/assets/16578570/f71e43af-a094-40ea-9db5-f47c966f565c)

The index of all tags (https://retype.com/tags/): ![image](https://github.com/Doctave/doctave/assets/16578570/82641ed5-28c9-4c13-a73e-d7e6b44f5762)

Examples on my Hexo blog:

Tags on an article: ![image](https://github.com/Doctave/doctave/assets/16578570/2a9b2249-c5a7-442d-9a73-408ef60ffc8b)

A tag index (https://blog.raw.pm/tags/eop/): ![image](https://github.com/Doctave/doctave/assets/16578570/4f9da590-ae0b-4aaa-a868-8abef7de4afa)

The list of all tags (https://blog.raw.pm/tags/): ![image](https://github.com/Doctave/doctave/assets/16578570/83429c47-68db-4343-9dd9-1d42fd65e367)

A tag cloud widget: ![image](https://github.com/Doctave/doctave/assets/16578570/b7e2c191-f82e-4f73-8508-aaa5aa917623)

### Additional context

Front-matter (https://vitepress.dev/guide/frontmatter) are already supported

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by shailen-naidoo** [comment]
I created another ticket to provide more context in regard to my use case, you are welcome to close if you feel that it is necessary to have https://github.com/vuejs/vitepress/issues/3254 but I do believe that this feature is very important, especially in the case of a documentation tool where there may be multiple related pages.

**Comment by Karlstens** [comment]
Great write up! I too would love to use such a tag feature set in my vitepress projects.

**Comment by brc-dd** [comment]
Let's track this at #3254 itself (although that one is newer but it has more upvotes)
