### ISSUE TITLE
Custom title for 'home: true' pages

### ISSUE THREAD

**Issue by IlyaSemenov** [vuejs/vitepress#303]
**Is your feature request related to a problem? Please describe.**
I'm unable to set custom page title for the home page (denoted with `home: true`). It's hardcoded as 'Home':

https://github.com/vuejs/vitepress/blob/3d1642094048f6301d30d1da16965ea7ee6da2f7/src/node/markdownToVue.ts#L129-L132

**Describe the solution you'd like**
I'd like to be able to override page title via `index.md`:

```md
---
home: true
title: Custom Title
---
```

(This will be useful not only for home: true pages).

**Comment by lhsazevedo** [comment]
Doesn't fulfill your request but maybe it's enough for you: #263

**Comment by kiaking** [comment]
This is now possible in VitePress Next 👍
