### ISSUE TITLE
By default the  github "editLinks" are using the "master" branch instead of the "main" branch ? how do we change the branch ? 

### ISSUE THREAD

**Issue by romain130492** [vuejs/vitepress#304]
**Describe the bug**
Hey By default when using the  github "editLinks" are using the "master" branch instead of the "main" branch ? how do we change the branch used by vitepress github link ? 
Since the "master" has now be replaced by the "main" branch.
My purpose is to be able to use `Edit this page on GitHub` 
my config 
```
  themeConfig: {
    docsDir: 'rsi-api-documentation/docs/',
    lastUpdated: 'Last Updated',
    repo: 'https://github.com/repo
    editLinks: true,
    editLinkText: 'Help us improve this page!',
```

**To Reproduce**

**Expected behavior**

**System Info**
- vitepress version:
- vite version:
- Node version:
- OS version:

**Additional context**

**Comment by ydcjeff** [comment]
See https://github.com/vitejs/vite/blob/496e26e995e18e7dab9fbea03885952f792e15ce/docs/.vitepress/config.js#L11-L16
