### ISSUE TITLE
[Bug] VitePress won't build

### ISSUE THREAD

**Issue by Ahwxorg** [vuejs/vitepress#3040]
### Describe the bug

VitePress builds, and instantly removes the dist folder again.

### Reproduction

Clone my [GitHub repository](https://github.com/Ahwxorg/Linkbase/), run yarn to install the dependencies and run `yarn vitepress build`.

### Expected behavior

VitePress successfully builds the dist/ folder.

### System Info

```Text
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M2 Pro
    Memory: 125.69 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 16.6
```

Although I use GitHub Actions as well (see [the failed run here](https://github.com/Ahwxorg/Linkbase/actions/runs/6273423931/job/17036870482))

### Additional context

Build log is the following:

```sh
vitepress v1.0.0-rc.20

✓ building client + server bundles...
✓ rendering pages...
build complete in 1.89s.
✨  Done in 2.06s.
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to change this path to `.vitepress/dist`:

https://github.com/Ahwxorg/Linkbase/blob/e08cf99bd6f8cb488dd3b79621eb7930e5773576/.github/workflows/deploy.yml#L53
