### ISSUE TITLE
[Q] - vitepress/style.styl in the docs; is it used? 

### ISSUE THREAD

**Issue by khalwat** [vuejs/vitepress#305]
The [docs state](https://vitepress.vuejs.org/guide/differences-from-vuepress.html#general):

[styling](https://vuepress.vuejs.org/config/#styling) `.vitepress/styles/index.styl` and `.vitepress/styles/palette.styl` is `.vitepress/style.styl`

...which implies that the `.vitepress/style.styl` is looked at for Stylus variables but searching the codebase, I couldn't see any reference to it.

Is this documentation vestigial, or am I misreading it somehow, or...?

**Comment by soulsam480** [comment]
Hii @khalwat , Currently Vitepress doesn't have support for `.vitepress/styles/index.styl` and `.vitepress/styles/palette.styl`. See [here](https://vitepress.vuejs.org/guide/differences-from-vuepress.html#general).  You can customize the default `CSS Vars` instead. see [here](https://github.com/vuejs/vitepress/blob/master/src/client/theme-default/styles/vars.css) and [here](https://vitepress.vuejs.org/guide/theming.html#customizing-css)

**Comment by khalwat** [comment]
Right, I was mostly pointing out the vestigial documentation, but I assume the project isn't looking for feedback on that at the. moment, so will close it up!
