### ISSUE TITLE
No loader is configured for ".scss" ".vue"

### ISSUE THREAD

**Issue by ChenKaiKe** [vuejs/vitepress#3050]
### Describe the bug

I want to extend Default theme by custom .scss and .vue files，but when I run 'yarn docs:dev', it output a error "No loader is configured for ".scss"

### Reproduction

1. new file index.scss 
2. import index.scss
3. yarn docs:dev

### Expected behavior

normal operation by import .scss and .vue files

### System Info

```Text
mac chrome
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Run `npm add sass`

**Comment by ChenKaiKe** [comment]
你好，你的来件我已经收到，谢谢，打扰啦。

**Comment by ChenKaiKe** [comment]
my codes:
![image](https://github.com/vuejs/vitepress/assets/24711778/c0151f70-69ff-4d8b-a3a8-2b73e35e08b1)
![image](https://github.com/vuejs/vitepress/assets/24711778/2538856a-bf9e-4862-83fd-83bc817b14d4)
![image](https://github.com/vuejs/vitepress/assets/24711778/f3c3f5ca-848f-467f-a5ab-51cf7be3db2b)
![image](https://github.com/vuejs/vitepress/assets/24711778/c42fdef3-1291-4766-8545-d3c7d1be4d12)

**Comment by ChenKaiKe** [comment]
I just want to extend default theme，so I import my custom sass file and vue file

**Comment by brc-dd** [comment]
Don't import theme in your config file and remove that `extends: blogTheme`. `extends:` in config file is for extending config not theme. Theme is automatically loaded from `.vitepress/theme/index`.
