### ISSUE TITLE
Using createContentLoader in xxx.data.mts causes an error

### ISSUE THREAD

**Issue by wangxiaocuo** [vuejs/vitepress#3051]
### Describe the bug

When I refer to official documents and Vue Blog to expand the default theme, an error occurred. 

When I use `createContentLoader` in `xxx.data.mts`, the console will output a syntax error.

### Reproduction

It can be reproduced in the following Repository: [xiaocuo.wang](https://github.com/wangxiaocuo/xiaocuo.wang).

### Expected behavior

Expect normal operation without errors.

### System Info

```Text
System:
  OS: macOS 13.5.2
  CPU: (8) arm64 Apple M1
  Memory: 95.55 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
  npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  pnpm: 8.7.5 - ~/.nvm/versions/node/v16.17.1/bin/pnpm
Browsers:
  Chrome: 117.0.5938.149
  Safari: 16.6
npmPackages:
  vitepress: ^1.0.0-rc.20 => 1.0.0-rc.20
```

### Additional context

<img width="704" alt="image" src="https://github.com/vuejs/vitepress/assets/16472134/0526601d-b2ae-45e9-bc3c-a6cea9770941">

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Fancy11111** [comment]
Hi, I currently face the same issue, did you solve this? @wangxiaocuo

**Comment by wangxiaocuo** [comment]
Nope😭 @Fancy11111

**Comment by brc-dd** [comment]
Use `.js` or `.ts` for now. You'll need to put `"type": "module"` in your nearest package.json

**Comment by wangxiaocuo** [comment]
It worked. Thank you. @brc-dd
