### ISSUE TITLE
header and footer of 404 page are not localized

### ISSUE THREAD

**Issue by neicore** [vuejs/vitepress#3056]
### Describe the bug

I added a custom notFound and footer content in the themeConfig and it works as expected, but when I passed custom in themeConfig of a locale, the values didn't appear

### Reproduction

In any vitepress project that has locale go to themeConfig of that locale and add custom notFound or footer values and they wont show up when you are in that locale

### Expected behavior

When you add custom values of notFound or footer in themeConfig or a locale, they should show up if you are in that locale

### System Info

```Text
System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 5.70 GB / 15.31 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.5.0 - ~/.nvm/versions/node/v20.5.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.0/bin/npm
  npmPackages:
    vitepress: ^1.0.0-rc.20 => 1.0.0-rc.20
```

### Additional context

you can find my config here:
https://github.com/NuruProgramming/nyaraka/blob/main/docs/.vitepress/config.mts

currently it only has notFound property in locale

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by dragomano** [comment]
Tooltip for the "Copy Code" button is hardcoded too.

**Comment by NozomuIkuta** [comment]
@brc-dd 

I faced at this issue with the latest VitePress.

As far as I investigated, what's happening is like below:

- `notFoundPageData.relativePath` is always an empty string regardless of actual page path the user is navigated to
- Then, inside [`resolveSiteDataByRoute()`](https://github.com/vuejs/vitepress/blob/00487872062fbf538657654e03afcc53b53ca7ef/src/shared/shared.ts#L78C17-L78C39), [`isActive()`](https://github.com/vuejs/vitepress/blob/00487872062fbf538657654e03afcc53b53ca7ef/src/shared/shared.ts#L37) always returns `false` and `localeIndex` is fallen back to `"root"`
- Then, `siteData` is made up by merging 2 root configs

Updating `notFoundPageData.relativePath` based on the current route would resolve this issue, but I'm not sure might be missing a reason why you set an empty string to it, and can't be so confident to submit a PR. 🙏

**Comment by brc-dd** [comment]
`notFoundPageData.relativePath` needs to be kept as empty because only one 404.html page is generated and I don't think any popular host support localized error pages. We can however fix this problem similar to how we are determining the root link inside onMounted hook.

**Comment by NozomuIkuta** [comment]
@brc-dd 

Thank you for the quick fix!
But, unfortunately #3833 resolved the issue only partially. 🙌 

`themeConfig` for NotFound page is made up on mounted hook of `NotFound.vue`, which corresponds to main contents of the page. As a result, other components such as layout components (e.g `VPFooter`) is still not localized.

**Comment by brc-dd** [comment]
I don't think there is any way to fix that except to render 404 completely on client 👀

**Comment by brc-dd** [comment]
You can customize those but cannot override based on locale. Track https://github.com/vuejs/vitepress/issues/3141#issuecomment-1784021955 for that. The current workaround is to always specify titles on blocks.
