### ISSUE TITLE
After I added the relevant internationalization configuration, the icons in the public directory cannot be loaded on pages in certain languages.

### ISSUE THREAD

**Issue by NasaRocket** [vuejs/vitepress#3059]
### Describe the bug

Here is my website:
github: https://github.com/Lark-Base-Team/js-sdk-docs
Accessing https://lark-base-team.github.io/js-sdk-docs/zh/start
does not display the icons.
![image](https://github.com/vuejs/vitepress/assets/38005687/edcaa283-4d04-459c-81d3-681fc9297836

But accessing: https://lark-base-team.github.io/js-sdk-docs/
displays the icons.
![image](https://github.com/vuejs/vitepress/assets/38005687/4996b72f-1749-4b75-9a46-45f82603cd1c)
Below is my configuration file:
```
export default defineConfig({
  lastUpdated: true,
  cleanUrls: true,
  base: '/js-sdk-docs/',
  themeConfig: {
    logo: 'logo.svg',
    search: {
      provider: 'local'
    },
    nav: [
      { text: 'API', link: '/zh/api/guide', activeMatch: 'zh/api' },
    ],
  },
  head: [
    ['link', { rel: 'icon', href: 'logo.svg' }],
  ],
  title: 'Base JS SDK',
  description: 'Base JS SDK Docs',
  // sitemap: {
    // hostname: 'https://basejsapi.com',
  // },
  lang: 'zh',
  locales: {
    zh: {
      label: '中文',
      lang: 'zh',
      dir: '/zh',
      title: 'Base JS SDK',
      description: 'Base JS SDK Docs',
      themeConfig: {
        search: {
          provider: 'local'
        },
        nav: [
          { text: 'API', link: '/zh/api/guide', activeMatch: 'zh/api' },
        ],
        sidebar: getZhSideBar(),
      },
    },
    en: {
      label: 'English',
      lang: 'en',
      dir: '/en',
      title: 'Base JS SDK',
      description: 'Base JS SDK Docs',
      themeConfig: {
        search: {
          provider: 'local'
        },
        nav: [
          { text: 'API', link: '/en/api/guide.md' },
        ],
        sidebar: getEnSideBar(),
      },
    }
  },
})

```

### Reproduction

vitepress: 1.0.0-rc.10

### Expected behavior

show icon like this
![image](https://github.com/vuejs/vitepress/assets/38005687/362c67ba-1367-4a1d-b411-4fffb0c8eb79)

### System Info

```Text
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 210.73 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    pnpm: 8.7.4 - ~/.nvm/versions/node/v18.14.2/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.6
  npmPackages:
    vitepress: 1.0.0-rc.10 => 1.0.0-rc.10
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You probably meant to write `logo: '/logo.svg'` there.
