### ISSUE TITLE
Use Iconify icons in inline markdown

### ISSUE THREAD

**Issue by pberto** [vuejs/vitepress#3068]
### Is your feature request related to a problem? Please describe.

Feature and/or problem (in the latter case is just a lacking documentation).

### Describe the solution you'd like

Since VP already uses Iconify, I'd like to be able to use inline iconify icons in markdown, is it possible somehow maybe like dropping a tag like if it was template? Eg:

```
## Sample text
Here's an inline icon: <Icon icon="mdi-light:home" />
```
I think this is pretty reasonable to have.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by userquin** [comment]
Try adding to your md file this section under frontmatter (if present):
```ts
<script setup>
import { Icon } from '@iconify/vue'
</script>
```

Or use the Iconify web component: 
- dependency: https://github.com/iconify/website/blob/main/package.json#L25-L27
- registration (global): https://github.com/iconify/website/blob/main/.vitepress/theme/index.ts#L4C9-L4C22
- vue configuration (tell vue `<iconify-icon>` is a web component): https://github.com/iconify/website/blob/main/.vitepress/config.ts#L24-L30
- usage (same as vue component): https://github.com/iconify/website/blob/d88ba0e810f94244b4c523edc203340193f567bc/sponsors/index.md?plain=1#L19
- docs: https://iconify.design/docs/iconify-icon/#iconify-icon-web-component

**Comment by userquin** [comment]
@pberto any Iconify icon won't bundle the svg icon in the html, will load the icons on the client, you can use [unplugin-icons](https://github.com/unplugin/unplugin-icons) (vue component, svg in the html) or [UnoCSS Preset Icons](https://unocss.dev/presets/icons) (svg in your css)

**Comment by pberto** [comment]
Thanks, will look into this and report if there is any problem.

**Comment by pberto** [comment]
@userquin thank you, excellent explanation. Both works, and I winter for the global approach which also works inline, while in the first case (local import on page) I would have had to do some css changes due to `display: block`.

Awesome feedback and nice work on the iconify website, I am snooping for more things in there now. Keep it up!
