### ISSUE TITLE
[Query] How image url inside markdown transform to right url ?

### ISSUE THREAD

**Issue by HelloYu** [vuejs/vitepress#3072]
I want to make a post list with excerption, now I am using `createContentLoader` , and it can get rendered html excerpt, but the image url not append the right prefix. 
```ts
export default createContentLoader(POST_FILES, {
	excerpt: (file) => {
		const index = file.content.indexOf(EXCERPT_MARK)

		file.excerpt = file.content.substring(
			0,
			index == -1 ? EXCERPT_LENGTH : index
		)
	},
	transform(raw): Post[] {
		return raw
			.map(({ url, frontmatter, excerpt }) => {
				return {
					title: frontmatter.title,
					categories: frontmatter?.categories ?? [],
					description: excerpt,
					tags: frontmatter.tags ?? [],
					url: url,
					excerpt,
					date: formatDate(frontmatter.date),
				}
			})
			.sort((a, b) => b.date.time - a.date.time)
	},
})
```
for example, i use relative path syntax inside markdown file:
```
![](images/xxx.png)
```
it show up in excerption was: 
```
<img src="./images/xxx.png" />
```
and in post or page that process by vitepress is correct url:
```
<img src="/blog/xxxx/images/xxx.png" />
```
how can I make the right process by ourself ?

**Comment by brc-dd** [comment]
That image will be hashed. The only way to prevent this to use public directory and reference your images by leading slash - `/images/foo.png` -- If you still want to use relative format, then you'd need to manually generate the final path. (that hash is sha256 digest of the image -- https://github.com/vuejs/vitepress/issues/2999#issuecomment-1730071744)

**Comment by HelloYu** [comment]
> That image will be hashed. The only way to prevent this to use public directory and reference your images by leading slash - `/images/foo.png` -- If you still want to use relative format, then you'd need to manually generate the final path. (that hash is sha256 digest of the image -- [#2999 (comment)](https://github.com/vuejs/vitepress/issues/2999#issuecomment-1730071744))

Thanks
