### ISSUE TITLE
Support aliases to highlighting not-so-popular-languages in markdown/shiki

### ISSUE THREAD

**Issue by pberto** [vuejs/vitepress#3073]
### Is your feature request related to a problem? Please describe.

Feature

### Describe the solution you'd like

I am writing documentation with code snippets of not widely known languages with C-like syntax.

I'd like to somehow declare that `myLang` syntax should be highlighted as if it was `C` syntax, and in the code block on the top-left I'd like to see `myLang` and not `c`. Any hint?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Try this:

```ts
// .vitepress/config.ts
import { BUNDLED_LANGUAGES } from 'shiki'

BUNDLED_LANGUAGES
  .find(lang => lang.id === 'c').aliases.push('myLang');
```

**Comment by pberto** [comment]
Trying to understand why aliases is undefined... totally new at this typescript hehe

**Comment by brc-dd** [comment]
Ah right, change that to this:

```ts
BUNDLED_LANGUAGES.find(lang => lang.id === 'c').aliases = ['myLang']
```

**Comment by pberto** [comment]
Thanks it works plus it's now I understood ;)
