### ISSUE TITLE
页内锚点滚动滑动效果

### ISSUE THREAD

**Issue by anyaoqi** [vuejs/vitepress#3074]
### Is your feature request related to a problem? Please describe.

There is no sliding effect when the anchor point scrolls in the web page. I am not sure whether this function is available. I hope to increase the animation effect of the anchor point scrolling and sliding in the web page.

If there is this function, please tell me how to use it

当前在网页内锚点滚动时没有滑动效果，我不确定是否有这个功能，希望可以增加网页内锚点滚动滑动的动画效果
如果有这个功能，请告诉我如何使用

### Describe the solution you'd like

Add a sliding effect when scrolling by clicking on the anchor point in the page

### Additional context

I found that in VuePress you can slide when clicking on the anchor point

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Add this CSS:

```css
html:focus-within {
  scroll-behavior: smooth;
}
```

https://vitepress.dev/guide/extending-default-theme#customizing-css
