### ISSUE TITLE
vitepress不支持.awebp格式文件

### ISSUE THREAD

**Issue by wushuang5112** [vuejs/vitepress#3076]
### Describe the bug

⠇ building client + server bundles...[vite:build-import-analysis] Parse error @:2:129
file: /data/www.wushuang5112.wang/docs/01FE/nodejs/resources/stream.awebp:2:128
WEBPVP8X
2: vRALPH����!���I�I����Njb;gn��3c�bۨضQ���m��<;�=����q�HRi��v�Y�L�/��S�����?�l.rwM�앇/ݫ_��/l.R�4������\�2�\�3}���ys�ґ...
                                                                                                                                   ^
3: ��)B
       �������v%��)�*2�XF�z�Q�mT�&�Y6j�
4: *$c�J���h�X/q���K��}��o2��u.y�8�|���
✖ building client + server bundles...
xterm-256colorbuild error:
Error: Parse error @:2:129
    at parse$e (file://node_modules/.pnpm/vite@4.4.11/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:16497:355)
    at Object.transform (file://node_modules/.pnpm/vite@4.4.11/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:46642:27)
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

```js
{
  "type": "module",
  "name": "website",
  "version": "1.0.0",
  "description": "self website",
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:serve": "vitepress serve docs"
  },
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "vitepress": "^1.0.0-alpha.48",
    "vue": "^3.2.47"
  }
}
```
从报错上来看是因为解析不了*.awebp文件，缺少Loader支持

### Expected behavior

通过项目编译时出现了如下报错，可能是不支持*.awebp文件；

pnpm run docs:build

### System Info

```Text
window & ubuntu 22.04
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
Upgrade vitepress to the latest version and you shouldn't have this problem.

**Comment by brc-dd** [comment]
`awebp` is not there in vite's known assets. add this to your config:

```ts
// .vitepress/config.ts
import { defineConfig } from 'vitepress'

export default defineConfig({
  vite: {
    assetsInclude: ['**/*.awebp']
  }
})
```

If you want, feel free to create a PR at vite. You'll need to update this part - https://github.com/vitejs/vite/blob/main/packages/vite/src/node/constants.ts#L97
