### ISSUE TITLE
unexpected css style

### ISSUE THREAD

**Issue by Sorryhx** [vuejs/vitepress#3077]
### Describe the bug

It occur unexpected css style when I use doc theme，just CSS pollution cause the label selector `.vp-doc table`.

### Reproduction

```txt
---
layout: doc
---

<script setup>

import {ElTable} from 'element-plus'
<script>

<el-table></el-table>

```
`el-table` style is unexpected because `.vp-doc table` `.vp-doc td` `.vp-doc tr` selectors.

### Expected behavior

`el-table` or other html tags have browser's default style in doc theme.

### System Info

```Text
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 1.49 GB / 15.73 GB
  Binaries:
    Node: 18.15.0 - D:\Program Files (x86)\node\18\node.EXE
    Yarn: 1.22.19 - D:\Program Files (x86)\node\18\yarn.CMD
    npm: 9.5.0 - D:\Program Files (x86)\node\18\npm.CMD
    pnpm: 8.6.8 - D:\Program Files (x86)\node\18\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.13 => 1.0.0-rc.13
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You'll need to enable style isolation - read the details section https://vitepress.dev/guide/markdown#raw

**Comment by Sorryhx** [comment]
> You'll need to enable style isolation - read the details section https://vitepress.dev/guide/markdown#raw and add `vp-raw` class to that table.

Thank you for your reply! I just code a post-css plugin to solve the issue by myself before I found your reply, so sad😂, hah hah.
