### ISSUE TITLE
multi-level base path problem

### ISSUE THREAD

**Issue by RSS1102** [vuejs/vitepress#3080]
### Describe the bug

When I perform multi-level routing on the base path of an item, it only takes effect on one。

### Reproduction

https://github.com/RSS1102/vitepress-SidebarItem-base

### Expected behavior

Should the base path of the sidebar and the base of the SidebarItem be combined to splice the paths together。
```diff
export default defineConfig({
  ignoreDeadLinks: true,
  themeConfig: {
    nav: nav(),
    sidebar: {
++    '/A/': { base: '/A/', items: sideA() },
      '/B/': { base: '/B/', items: sideB() },
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/RSS1102/vitepress-SidebarItem-base' }
    ]
  }
})

function nav(): DefaultTheme.NavItem[] {
  return [
    {
      text: 'A',
      link: '/A/a/index1',
      activeMatch: '/A/'
    },
    {
      text: 'B',
      link: 'B/b/index1',
      activeMatch: '/B/'
    },
  ]
}

function sideA(): DefaultTheme.SidebarItem[] {
  return [
    {
      text: 'a',
++     base: '/a/',
      items: [
++       { text: 'index1', link: 'index1' },
        { text: 'index2', link: 'index2' },
      ]
    },
    {
      text: 'b',
      base: '/b/',
      items: [
        { text: 'index1', link: 'index1' },
        { text: 'index2', link: 'index2' },
      ]
    },
  ]
}
```
I want to obtain a path for the above diff: `/A/a/index1.html`,
Actually, `/a/index1.html`,

### System Info

```Text
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 3.11 GB / 13.86 GB
  Binaries:
    Node: 18.12.1 - E:\node\node.EXE
    Yarn: 1.22.19 - E:\node\yarn.CMD
    npm: 9.8.0 - E:\node\npm.CMD
    pnpm: 8.7.6 - E:\node\pnpm.CMD
  Browsers:
    Edge: Chromium (117.0.2045.60)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.21 => 1.0.0-rc.21
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's expected behavior. If we join the bases then there will be no way to opt-out of that.
