### ISSUE TITLE
When running the browser in the directory pnpm docs:dev vitepress, it reports 404

### ISSUE THREAD

**Issue by Jevin0** [vuejs/vitepress#3082]
### Describe the bug

When running the browser in the directory pnpm docs:dev vitepress, it reports 404

### Reproduction

This is the address of the demo https://github.com/Jevin0/vite-vue3-ui

### Expected behavior

-

### System Info

```Text
-
```

### Additional context

![image](https://github.com/vuejs/vitepress/assets/69580637/0d7f28c1-16f5-4cf3-9900-4b7a3e020d4d)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Jevin0** [comment]
Sorry, my English is not good, I can only explain my question through Google Translate

**Comment by brc-dd** [comment]
Change this https://github.com/Jevin0/vite-vue3-ui/blob/master/docs/package.json#L3 to `"dev": "vitepress dev"` and delete this folder https://github.com/Jevin0/vite-vue3-ui/tree/master/docs/docs/.vitepress/cache/deps

**Comment by Jevin0** [comment]
The problem has been solved, thank you
