### ISSUE TITLE
[Query]Which hooks can I use to modifiy HTML or Vue before render process

### ISSUE THREAD

**Issue by HelloYu** [vuejs/vitepress#3084]
I have a requirement should append post meta tag and custom H1 tag into vp-doc container, and I used BOM to manipulate this, like below:
```vue
<template>
  <div ref="$h1Custom">
    <h1 :id="page.title" tabindex="-1">
      {{ page.title }}
    </h1>
    <Metadata :categories="frontmatter.categories" :tags="frontmatter.tags" :published-at="frontmatter.date" />
  </div>
</template>
<script setup lang="ts">
import { useData } from 'vitepress';
import Metadata from './HYPostMetadata.vue'
import { nextTick, onMounted, ref, watch } from 'vue';
const $h1Custom = ref()
const { page, frontmatter } = useData()

watch(page, (value, oldValue) => {
  nextTick(() => {
    processH1Element()
  })
})

onMounted(() => {
  processH1Element()
})

function processH1Element() {
  const docDomContainer = window.document.querySelector('#VPContent')
  if (!docDomContainer) return
  const vpDoc = docDomContainer.querySelector('main .vp-doc div')
  vpDoc?.insertAdjacentElement('afterbegin', $h1Custom.value)
}

</script>
```
but the h1 tag not add anchor because this not render by VitePress default process, how can I inject my template into the process? or which solution should I use ? I search [Build Hooks](https://vitepress.dev/reference/site-config#build-hooks), but seems not meet my need.

**Comment by brc-dd** [comment]
You probably need to add this in `doc-before` slot - https://vitepress.dev/guide/extending-default-theme#layout-slots

**Comment by HelloYu** [comment]
> You probably need to add this in `doc-before` slot - https://vitepress.dev/guide/extending-default-theme#layout-slots

Yes, I used this slot, but no anchor show up.
![image](https://github.com/vuejs/vitepress/assets/6134340/52cb1b50-76a6-402b-adbb-79c1f3019f7a)

**Comment by brc-dd** [comment]
by anchor, do you mean the `#` symbol on left?

**Comment by HelloYu** [comment]
> by anchor, do you mean the `#` symbol on left?

yes, and a tag with it.

**Comment by brc-dd** [comment]
try something like this:

```html
  <h1 :id="id" tabindex="-1">
    {{ page.title }}
    <a class="header-anchor" :href="'#' + id" :aria-label="`Permalink to "${page.title}"`">&#8203;</a>
  </h1>


<script setup lang="ts">
import slugify from '@sindresorhus/slugify' // install this or some other library to create id from title
import { computed } from 'vue'

const id = computed(() => slugify(page.title))
</script>
```

**Comment by HelloYu** [comment]
> try something like this:
> 
> ```
>   <h1 :id="id" tabindex="-1">
>     {{ page.title }}
>     <a class="header-anchor" :href="`#${id}`" :aria-label="`Permalink to "${page.title}"`">&#8203;</a>
>   </h1>
> 
> 
> <script setup lang="ts">
> import slugify from '@sindresorhus/slugify' // install this or some other library to create id from title
> import { computed } from 'vue'
> 
> const id = computed(() => slugify(page.title))
> </script>
> ```

Divyansh, Many thansk.
