### ISSUE TITLE
[style] Navbar was overlap outline menu in mobile Chrome browser ?

### ISSUE THREAD

**Issue by HelloYu** [vuejs/vitepress#3087]
### Describe the bug

I used Chrome to review my blog and saw the Navbar overlaped:
![623975fbab78abbab5a5a2e42ba27d8](https://github.com/vuejs/vitepress/assets/6134340/05a01730-88a5-47df-8c30-322353caaf23)
my Chrome version:
![45ddaf8afb602047f8b0029d31bcbb6](https://github.com/vuejs/vitepress/assets/6134340/d5773da5-c255-492b-9b19-e1118ec0d04b)
it work on my native browser:
![76bc99e9d1c73bbd5c0574aed0e7d87](https://github.com/vuejs/vitepress/assets/6134340/4e415038-efbb-4359-bc3d-af1ba1353eb0)
and it also work at my PC Chrome in response  mode.
my blog: https://helloyu.github.io/

### Reproduction

as describe 

### Expected behavior

Same behavior all cross the platforms

### System Info

```Text
no relevant
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Unfortunately Chrome 68 is not supported - https://vitejs.dev/guide/build.html#browser-compatibility

**Comment by HelloYu** [comment]
> Unfortunately Chrome 78 is not supported - https://vitejs.dev/guide/build.html#browser-compatibility

Oh, okay, thank you.
