### ISSUE TITLE
How to display results for more than 5 items using Algolia search?

### ISSUE THREAD

**Issue by simply-none** [vuejs/vitepress#3088]
### Is your feature request related to a problem? Please describe.

emmmm, now on the official website of vitepress.dev, after clicking search and entering some keywords, no more than 5 results are always returned. Now I need to view more results, such as 20 or 50, what should I do? Hope to get a reply, thank you
![image](https://github.com/vuejs/vitepress/assets/44159358/f95a8816-da3e-4acc-a988-92064be62572)

### Describe the solution you'd like

Now I need to view more results, such as 20 or 50, what should I do?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
already replied on https://github.com/vuejs/vitepress/issues/2983#issuecomment-1762703269
