### ISSUE TITLE
Strip `frontmatter` when a Markdown file inserted into another

### ISSUE THREAD

**Issue by dacodekid** [vuejs/vitepress#3091]
### Is your feature request related to a problem? Please describe.

Currently markdown file insertion also includes (renders) the `frontmatter` data.

### Describe the solution you'd like

Adding an option to strip the `frontmatter` would help when we reuse the same markdown files.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you explain a bit more?

**Comment by dacodekid** [comment]
@brc-dd I think that was an oversight on my part. I just noticed that the file includes the source file also had the same `frontmatter`, hence it was rendered while including.  Closing this issue it is working as expected.
