### ISSUE TITLE
Frontmatter is not accessible in markdown

### ISSUE THREAD

**Issue by bencodezen** [vuejs/vitepress#31]
**Describe the bug**

1. Add frontmatter to index.md

```
---
title: My Docs Site
---

# {{ $frontmatter.title }}
```

This does not render as expected.

**To Reproduce**

**Expected behavior**

**System Info**
- vitepress version: v0.4.0
- vite version: v1.0.0-beta.1
- Node version: v12.16.1
- OS version: macOS 10.15.5

**Additional context**

**Comment by SigureMo** [comment]
Unlike VuePress, the VitePress `frontmatter` variable under the `$page`, you can try to access it by using `$page.frontmatter`.

``` md
---
title: My Docs Site
---

# {{ $page.frontmatter.title }}
```

However, FrontMatter doesn't seem to support HMR yet.

**Comment by yyx990803** [comment]
HMR used to work but was broken due to changes in Vite, will be fixed soon.

VitePress will try to keep minimal global injections, so it's recommended to access it via `$page.frontmatter`.
