### ISSUE TITLE
Can you generate all routing lists for slidebar by default?

### ISSUE THREAD

**Issue by kongyijilafumi** [vuejs/vitepress#310]
The routing list parsed from the MD file expects to be rendered directly in the slidebar, rather than dynamically rendering the currently selected slidebar based on `useRoute()`.

>As in this case, the first page renders the routing list below it, but the subrouting list below the other headings needs to be selected to render.

![image](https://user-images.githubusercontent.com/56569970/120969197-7663a700-c79c-11eb-8613-98661db9f9a0.png)

**and like this.**
![image](https://user-images.githubusercontent.com/56569970/120969609-effb9500-c79c-11eb-890b-4db79dc8fe56.png)

**These big title paths are all MD files, but the titles in MD are hierarchical, and I hope they can be rendered. And it can be folded.**

- The slidebar I want is a list like this and can be folded to display.

![image](https://user-images.githubusercontent.com/56569970/120971254-00147400-c79f-11eb-8b09-1290551d0093.png)

**Comment by kiaking** [comment]
Not relevant anymore in `next-theme` since sidebar don't show headings anymore 👍
