### ISSUE TITLE
i want to use Router.onBeforeRouteChange

### ISSUE THREAD

**Issue by fanchen4139** [vuejs/vitepress#3100]
### Is your feature request related to a problem? Please describe.

My company has many development documentation sites, and because each of these documents is a separate site, it is difficult to link them together. My current idea is to link them together in a micro-application way. VitePress framework is a very good document, so we are developing document site is it, unable to use the router. OnBeforeRouteChange, lead to cannot be quick and easy to realize the communication between father and son application function.
 

### Describe the solution you'd like

I hope we can add the function of route guard to the router or useRouter hook of enhanceApp, which can solve many problems.
 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by fanchen4139** [comment]
<img width="1526" alt="image" src="https://github.com/vuejs/vitepress/assets/96282978/103fe141-e062-411e-8841-442f5c5ceba9">

**Comment by brc-dd** [comment]
The syntax is different from vue-router. Use it like this:

```ts
  enhanceApp: ({ router }) => {
    router.onBeforeRouteChange = (to) => {
        // ...
    }
  }
```
