### ISSUE TITLE
将 .md 文件后缀改为 .mdx 报错页面不存在

### ISSUE THREAD

**Issue by zhengxinonly** [vuejs/vitepress#3101]
在编写文档的时候，有部分的 markdown 文件使用了大量的 mdx 语法，所以试着将 .md 文件后缀修改为 .mdx ，刷新报 404 页面不存在。请问是否考虑支持 .mdx 的 markdown 文件后缀 ？

**Comment by brc-dd** [comment]
MDX is quite different from the syntax we support. Allowing .mdx extension for something that isn't MDX would be a weird behavior.
