### ISSUE TITLE
Can you identify the H tag in the outline display using vue file in md?

### ISSUE THREAD

**Issue by tomiaa12** [vuejs/vitepress#3103]
### Is your feature request related to a problem? Please describe.

H2, H3 headings currently written in vue cannot be shown in outline,

### Describe the solution you'd like

or can we get a useData add header provided

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
They need to be in specific format to be recognized: https://github.com/vuejs/vitepress/issues/3084#issuecomment-1761583124

You can abstract that to a component and use it instead of plane h2/h3.
