### ISSUE TITLE
How can the trailing slash at the end of the homepage URL be removed?

### ISSUE THREAD

**Issue by Alano-i** [vuejs/vitepress#3104]
### Is your feature request related to a problem? Please describe.

When the deployment is located at the path "/www/doc" and accessed via "http://domin.com/doc", 

an issue arises where a trailing slash is always automatically added at the end (resulting in "http://domin.com/doc/"). 

Could you please advise how to prevent the trailing slash from being displayed?

### Describe the solution you'd like

How can the trailing slash at the end be concealed in the browser's address bar?
```js
  base: '/doc/',
  rewrites: {
    'note/index.md': 'note.md',
    'note/:category/:page/index.md': 'note/:page.md',
  },
```

I have implemented the aforementioned rewrites, and URLs such as "http://domin.com/doc/note" and "http://domin.com/doc/note/nas" no longer display the trailing slash when accessed.

However, the browser's address bar still shows "http://domin.com/doc/" when accessing "http://domin.com/doc".

Thanks.

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to configure this at your hosting level. VitePress has no control over this.

**Comment by Alano-i** [comment]
> You need to configure this at your hosting level. VitePress has no control over this.

I have configured the Nginx rules on my server as follows, but the problem still persists. 

Could you please help me take a look and see if I have made any configuration mistakes?
``` console
server {
    listen 80;
    server_name domin.com www.domin.com;

    location / {
        root /www;
        try_files $uri $uri.html $uri/index.html =404;
    }
    location ~* /(.+)/$ {
        rewrite ^(/.+)(/)$ $1 permanent;
    }
}
```

**Comment by brc-dd** [comment]
Sorry, I'm not much familiar with nginx config. But someone earlier had mentioned this (https://github.com/vuejs/vitepress/discussions/2837):

```nginx
    location / {
        root /www;
        index index.html index.htm;
        try_files $uri $uri.html $uri/ /index.html =404;
    }
```

You might need to set `cleanUrls: true` in your vitepress config.

**Comment by Alano-i** [comment]
Thanks!

 Other solutions can work, but there is a problem with this root!    
 the browser's address bar still shows "http://domin.com/doc/" when accessing "http://domin.com/doc".

**Comment by brc-dd** [comment]
Okay now I remembered. This won't work. Trailing slash on /index.md kind of pages is enforced by VitePress. Otherwise all relative urls for links / assets will break.
