### ISSUE TITLE
Assets that are used with HTML block in Markdown don't move to assets folder

### ISSUE THREAD

**Issue by tevfik6** [vuejs/vitepress#3108]
I'm not sure this is a feature, bug or something else that is not documented. I have a Markdown that has `<img>` tag in it with some custom styling in it. 

As a config, I use additionally from any regular setup:
```js
srcDir: "./src",
```

and the html in markdown looks like this

```markdown

## Title 

<div class="float-right pl-[0.5rem] pt-[1rem]"> 
    <img src="./images/logo.png" alt="Logo" class="max-h-[60px]">
</div>

Some text here
```

When I run on `dev` mode it works perfectly fine however on a build the assets are not being moved, therefore the images are not really shown/broken. 

Is this expected behaviour? (Based on this issue I will file either Enhancement/Bug)

**Comment by brc-dd** [comment]
Can you share this in form of some repo? This should work fine with static strings.

**Comment by tevfik6** [comment]
@brc-dd Thanks for quick response. I need to extract it from the project. I will update here as soon as possible.

**Comment by brc-dd** [comment]
closing as stale.
