### ISSUE TITLE
When the user configures build hooks, the theme's build hooks are overwritten

### ISSUE THREAD

**Issue by MaLuns** [vuejs/vitepress#3109]
### Is your feature request related to a problem? Please describe.

When the user configures build hooks, the theme's build hooks are overwritten.

当用户配置 build hooks 时, 会覆盖掉主题的 build hooks.

### Describe the solution you'd like

For example, when there is a `transformHead` in the theme, the user adds a `transformHead` in their configuration to override the processing of the theme and has to handle it as follows: Is it possible to place this processing inside `vitepress`?

以为 `transformHead` 为例, 当主题里存在  `transformHead` , 用户在自己配置里添加 `transformHead` 会覆盖掉主题的处理, 不得不像下面那样处理, 能否将这种处理放置在 `vitepress` 内部处理呢?

``` ts
// user config
import Config from 'vitepress-theme-xxx';

{
  async transformHead(content) {
    const { transformHead } = await Config()
    if (transformHead) {
	    transformHead(content)
    }
    // do something
  }
}
```
---

It seems that useRouter's `onBeforeRouteChange` will also exist in `vitepress`, and overrides will also exist when multiple internal components declare onBeforeRouteChange

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [ ] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
The theme should export defineConfig and extendConfig helpers that merge those properly.

**Comment by MaLuns** [comment]
> The theme should export defineConfig and extendTheme helpers that merge those properly.

👌
