### ISSUE TITLE
Data Loader Error :  ... does not provide an export named ...

### ISSUE THREAD

**Issue by ezzle** [vuejs/vitepress#3113]
### Describe the bug

SyntaxError: The requested module '/component/util/allsuperclassframes.data.js?t=1697876520202' does not provide an export named 'allSuperclassFrames' (at application_provider.md:11:10)`

**Data Loader** 

```js
export default {
  watch: ['../../**/class/*.json'],
  async load(watchedFiles) {
    // watchedFiles will be an array of absolute paths of the matched files.
    // generate an array of blog post metadata that can be used to render
    // a list in the theme layout
    console.log('watchedFiles.length :::: ', watchedFiles.length)
    let allSuperclassFrames/*:FrameDbDataModel[]*/ = []
    let superclasses =  watchedFiles.map((file) => {
      return JSON.parse(fs.readFileSync(file, 'utf-8')).filter
    })
    superclasses.forEach(s => {
        if(! allSuperclassFrames.find(r => r.frame === s.frame && r.short_value === s.short_value)){
            allSuperclassFrames.push(s)
        }
    })
    console.log('result.length :::: ', allSuperclassFrames.length)
    return {allSuperclassFrames}
  }
}
```

**Import data loader**

```vue
<script setup>
import { allSuperclassFrames } from '../../../component/util/allSuperclassFrames.data'
...
```

**package.json**

```json
...
"type": "module",
...
```

### Reproduction

ts or js data loader for local files.

**Related ?**

https://github.com/vuejs/vitepress/pull/3058

https://github.com/vuejs/vitepress/issues/3051

### Expected behavior

Load data as documented 

https://vitepress.dev/guide/data-loading#basic-usage

### System Info

```
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 5.61 GB / 15.88 GB
  Binaries:
    Node: 18.15.0 - D:\Tools\Nodejs\18.15.0\node.EXE
    npm: 9.8.1 - D:\Tools\Nodejs\18.15.0\npm.CMD
    pnpm: 8.6.3 - D:\Tools\Nodejs\18.15.0\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (118.0.2088.57)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vitepress: v1.0.0-rc.22 => 1.0.0-rc.22
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you tell me what's the name of your data loader file?

**Comment by ezzle** [comment]
> Can you tell me what's the name (extension) of your data loader file? Or share the reproduction using https://vitepress.new

allsuperclassframes.data.js
allsuperclassframes.data.ts
allSuperclassFrames.data.js
allSuperclassFrames.data.ts

produce the same error

**Comment by brc-dd** [comment]
It doesn't seem to be reproducible at my side. Can you share a simple version using https://vitepress.new ?

**Comment by ezzle** [comment]
> It doesn't seem to be reproducible at my side. Can you share a simple version using https://vitepress.new ?
> 
> And those related issues you've mentioned are not exactly related. Those were fixed and we have e2e tests for those now.

You are right.
I missed a detail (required) : the import must be exactly 

`import  {data}  from '.....'`.

So 

`
import { allSuperclassFrames } from '../../../component/util/allsuperclassframes.data'

was not correct. Right ?

Thank you for your help.

Best regards

`

**Comment by brc-dd** [comment]
Ah right. 

You'll need to do something like this:

```ts
import  { data }  from '../../../component/util/allsuperclassframes.data.js'

const { allSuperclassFrames } = data
```

**Comment by brc-dd** [comment]
Our example is bit confusing as we have `data` there as a key too.

**Comment by ezzle** [comment]
> Our example is bit confusing as we have `data` there as a key too.

It is what happened for me. Please, adapt the doc .

Thank you for your support.

Best regards,

Tshitshi

**Comment by brc-dd** [comment]
Yeah updated the docs. It should be clearer in the basic example there now:

<img width="751" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/76b7c32d-9577-44a1-b27a-a4601af0bbc6">

**Comment by ezzle** [comment]
> Yeah updated the docs. It should be clearer in the basic example there now:
> 
> <img alt="image" width="751" src="https://user-images.githubusercontent.com/40380293/277160163-76b7c32d-9577-44a1-b27a-a4601af0bbc6.png">

Perfect! Thank you
