### ISSUE TITLE
no autocomplete on enhanceApp() or other things in theme/index.ts export default

### ISSUE THREAD

**Issue by jcbhmr** [vuejs/vitepress#3116]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/61068799/55cb7db1-503e-4747-8252-6c770c19b8d7)

no Ctrl+Space autocomplete on anything in the `export default { ... }` block in `theme/index.ts`

```ts
// https://vitepress.dev/guide/custom-theme
import { h } from 'vue'
import Theme from 'vitepress/theme'
import './style.css'

export default {
  extends: Theme,
  Layout: () => {
    return h(Theme.Layout, null, {
      // https://vitepress.dev/guide/extending-default-theme#layout-slots
    })
  },
  enhanceApp({ app, router, siteData }) {
    // ...
    app.
     // ^ NO autocomplete here 😢
  }
}
```

### Reproduction

https://stackblitz.com/edit/vite-bjyf4o?file=.vitepress%2Ftheme%2Findex.ts

### Expected behavior

![image](https://github.com/vuejs/vitepress/assets/61068799/4dd783a4-400e-4df8-ad2e-aef79e6d4c56)

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (2) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.9.2 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: ^1.0.0-rc.22 => 1.0.0-rc.22
```

### Additional context

i think the solution is to add a `satisfies import('vitepress').Theme` or similar in the docs examples and in the `vitepress init` wizard

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
add the type like this:

```ts
import type { Theme } from 'vitepress'
import DefaultTheme from 'vitepress/theme'

export default {
  extends: DefaultTheme,
  enhanceApp({ app }) {
    // ...
  }
} satisfies Theme
```

**Comment by brc-dd** [comment]
> i think the solution is to add a satisfies import('vitepress').Theme or similar in the docs examples and in the vitepress init wizard

ah you already figured that out 😅

**Comment by jcbhmr** [comment]
i found this https://github.com/vuejs/vitepress/blob/main/template/.vitepress/theme/index.js but is there a typescript version that i can also add the `satisfies` thing to as well for a pr? idk where the `vitepress init` wizard clones from 😵

**Comment by brc-dd** [comment]
init doesn't clone anything. That file uses interpolate delimiters. `useTs` will be available in the context when that file is compiled.
