### ISSUE TITLE
Non-code-groups Tabs : HowTo ?  + Tabs inside custom container: how to ?

### ISSUE THREAD

**Issue by ezzle** [vuejs/vitepress#3120]
### Is your feature request related to a problem? Please describe.

Is there a md syntax for 

1. tabs group for non code content  ? How to ?
2. Tabs inside custom containers ? How to ?

### Describe the solution you'd like

Tabs group like https://vitepress.dev/guide/markdown#code-groups
Inside custom containers like https://vitepress.dev/guide/markdown#custom-containers
And vice-versa ?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
first is not fully supported. see #3107

second:

````md

:::: details Click me to view the code

::: code-group

```js [config.js]
...
```

```ts [config.ts]
...
```

:::

::::

````

**Comment by ezzle** [comment]
Thank you for the response.
Unfortunately not a solution.
My issue is how to for reproduce the same result with tabs without code content ..

`
:::: details Click me to view the **tabs**

::: **content**-group (tabs)

::Tab 1
<h1>tab 1 </h1>
tab 1 content
::

:: Tab 2
<h1>tab 2 </h1>
tab 2 content
::

:::

::::
`

**Comment by brc-dd** [comment]
like I said that isn't supported at moment. track #3107 for that.

**Comment by ezzle** [comment]
> like I said that isn't supported at moment. track #3107 for that.

Could be of interest

https://github.com/sapphi-red/vitepress-plugins/discussions/42

**Comment by ezzle** [comment]
> > like I said that isn't supported at moment. track #3107 for that.
> 
> Could be of interest
> 
> [sapphi-red/vitepress-plugins#42](https://github.com/sapphi-red/vitepress-plugins/discussions/42)

@brc-dd  could you help improve the solution. Style not applied as expected . Thanks in adance for your help

https://stackblitz.com/edit/vite-8nyd7s?file=docs%2Findex.md

Best regards,

Tshitshi
