### ISSUE TITLE
"If this is a native custom element " import @vitejs/plugin-vue error

### ISSUE THREAD

**Issue by duoduoObama** [vuejs/vitepress#3127]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/30836806/1fb6c94a-d194-4f19-8c95-28d8ec1b1b35)
1. Browser console prompts warning when using custom elements
2. And add relevant plug-ins"@vitejs/plugin-vue"
3. Add this plug-in "@vitejs/plugin-vue" and report an error immediately

```
const plugins = [
  vue({ 
    template: {
      compilerOptions: {
        isCustomElement: (tag) => tag.startsWith("XXX-"),
      },
    },
  }),
];
```
At least one <template> or <script> is required in a single file component.
At least one <template> or <script> is required in a single file component. (x2)
At least one <template> or <script> is required in a single file component. (x3)
At least one <template> or <script> is required in a single file component. (x4)
At least one <template> or <script> is required in a single file component. (x5)
At least one <template> or <script> is required in a single file component. (x6)
At least one <template> or <script> is required in a single file component. (x7)
At least one <template> or <script> is required in a single file component. (x8)
At least one <template> or <script> is required in a single file component. (x9)
At least one <template> or <script> is required in a single file component. (x10)
At least one <template> or <script> is required in a single file component. (x11)
At least one <template> or <script> is required in a single file component. (x12)
At least one <template> or <script> is required in a single file component. (x13)
14:22:09 [vitepress] Internal server error: At least one <template> or <script> is required in a single file component.
  Plugin: vite:vue
  File: D:/work/webcomponent/webcomponent-project/vpdemo/node_modules/.pnpm/vitepress@1.0.0-rc.23_@algolia+client-search@4.20.0_search-insights@2.9.0/node_modules/vitepress/dist/client/theme-default/components/VPBadge.vue
      at Object.parse$2 [as parse] (D:\work\webcomponent\webcomponent-project\vpdemo\node_modules\.pnpm\@vue+compiler-sfc@3.3.6\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1905:7)
      at createDescriptor (file:///D:/work/webcomponent/webcomponent-project/vpdemo/node_modules/.pnpm/vitepress@1.0.0-rc.23_@algolia+client-search@4.20.0_search-insights@2.9.0/node_modules/vitepress/dist/node/serve-ZHDKzFm5.js:74:43)
      at transformMain (file:///D:/work/webcomponent/webcomponent-project/vpdemo/node_modules/.pnpm/vitepress@1.0.0-rc.23_@algolia+client-search@4.20.0_search-insights@2.9.0/node_modules/vitepress/dist/node/serve-ZHDKzFm5.js:2286:34)
      at TransformContext.transform (file:///D:/work/webcomponent/webcomponent-project/vpdemo/node_modules/.pnpm/vitepress@1.0.0-rc.23_@algolia+client-search@4.20.0_search-insights@2.9.0/node_modules/vitepress/dist/node/serve-ZHDKzFm5.js:2818:16)
      at Object.transform (file:///D:/work/webcomponent/webcomponent-project/vpdemo/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44352:62)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async loadAndTransform (file:///D:/work/webcomponent/webcomponent-project/vpdemo/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55026:29)    
14:22:09 [vitepress] Internal server error: At least one <template> or <script> is required in a single file component.

### Reproduction

https://stackblitz.com/edit/vite-xafvgm?file=vite.config.ts,docs%2Fexample2.md,docs%2Fexample.md
1. Add “@vitejs/plugin-vue” to stackblitz. This plugin still prompts a warning.
2. in local computer error：
3. 
![image](https://github.com/vuejs/vitepress/assets/30836806/4a6fad77-ea59-4668-87f3-da97feb6ad79)

### Expected behavior

After using the custom element and introducing the vitejs plugin vue plug-in, the console will not prompt a warning, and the vscode console will not report an error.

### System Info

```Text
Need to install the following packages:
  envinfo@7.10.0

  System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13500
    Memory: 2.90 GB / 15.69 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (118.0.2088.57)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-rc.22 => 1.0.0-rc.22
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Don't add the plugin. VitePress already includes it. Configure it using vitepress config: https://vitepress.dev/reference/site-config#vue

**Comment by Zhengqbbb** [comment]
```js
// .vitepress/config/index.js
export default {
  vue: {
    template: {
      compilerOptions: {
        isCustomElement: tag => tag.includes('XXX-'),
      },
    },
  },
}
```

**Comment by brc-dd** [comment]
Please reopen if it's still happening.
