### ISSUE TITLE
links with trailing slash do not load

### ISSUE THREAD

**Issue by jcstein** [vuejs/vitepress#3134]
### Describe the bug

These two links should both load the same page, but the one with trailing slash returns 404.

https://docs.celestia.org/developers/blobstream/
https://docs.celestia.org/developers/blobstream

### Reproduction

https://docs.celestia.org/developers/blobstream/
https://docs.celestia.org/developers/blobstream

### Expected behavior

Both pages load https://docs.celestia.org/developers/blobstream

### System Info

```Text
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 80.42 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
    pnpm: 7.13.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 117.1.58.135
    Chrome: 118.0.5993.88
    Safari: 17.0
  npmPackages:
    vitepress: 1.0.0-rc.24 => 1.0.0-rc.24
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You'll need to set this at your hosting level. How/where are you hosting your site?

**Comment by jcstein** [comment]
On GitHub pages, do you know if this needs to be set for every page or just at the top level?

**Comment by jcstein** [comment]
And for visibility, [this workflow is for main deployments](https://github.com/celestiaorg/docs/blob/main/.github/workflows/deploy.yml) and [this is for PR previews](https://github.com/celestiaorg/docs/blob/main/.github/workflows/preview.yml)

**Comment by brc-dd** [comment]
Ah, I don't think GitHub pages allows configuring this. But you seem to be using CloudFlare. So you can probably configure some rewrite rule like `https://docs.celestia.org.com/*/` to `https://docs.celestia.org.com/$1` there.

**Comment by jcstein** [comment]
thank you for digging into this. i'll go ahead and try that and hopefully that should resolve it 🙌

**Comment by userquin** [comment]
https://github.com/slorber/trailing-slash-guide

**Comment by jcstein** [comment]
thank you again @brc-dd - resolved with your suggestion for cloudflare. also, thanks for the link @userquin !
