### ISSUE TITLE
configure `locals > themeConfig.search` , it can't work

### ISSUE THREAD

**Issue by vanchKong** [vuejs/vitepress#3141]
### Describe the bug

https://github.com/vanchKong/vitepress/tree/doc-zh

temporary modify `docs/locals/en.ts` & `docs/locals/zh.ts` > `themeConfig.search` to
```ts
search: {
  provider: 'local'
},
```
run `vitepress dev docs`, `search` can't work successfully

### Reproduction

https://github.com/vanchKong/vitepress/tree/doc-zh

### Expected behavior

- configure `locals  > themeConfig.search` , and it could work
- In addition, `markdown.container` should be supported in multi-language configurations

### System Info

```Text
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 485.97 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.2.0 - /usr/local/bin/pnpm
  Browsers:
    Safari: 16.6
  vitepress: 1.0.0-rc.24
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
你好，现有版本关于搜索的配置你应该在 `themeConfig` 里边设置，别设在 `locales` 里，不然搜索框整体都会被隐藏的

**Comment by vanchKong** [comment]
> 你好，现有版本关于搜索的配置你应该在 `themeConfig` 里边设置，别设在 `locales` 里，不然搜索框整体都会被隐藏的

了解了。所以是这样：配置了多语言的情况下，使用 `themeConfig.search.options._render ` 来做到区分语言搜索吗？未来会有进一步的分别配置的支持吗？
另外，`markdown.container` 在多语言的配置中应该得到支持

**Comment by zonemeen** [comment]
> 了解了。所以是这样：配置了多语言的情况下，使用 `themeConfig.search.options._render ` 来做到区分语言搜索吗？未来会有进一步的分别配置的支持吗？ 另外，`markdown.container` 在多语言的配置中应该得到支持

`local` 搜索是在这里进行区分的：https://github.com/vuejs/vitepress/blob/c343d938fccd878134c8b9dbf2b12dce226a1c19/src/client/theme-default/components/VPLocalSearchBox.vue#L73

然后 `algolia` 是在这里：https://github.com/vuejs/vitepress/blob/c343d938fccd878134c8b9dbf2b12dce226a1c19/src/client/theme-default/components/VPAlgoliaSearchBox.vue#L25

进一步的分别配置在正式版1.0出来之前应该都不太会支持，当然可以期待一下另外一个 [issue](https://github.com/vuejs/vitepress/issues/3047) 提到的i18n解决方案

你指的 `markdown.container` 是指的[这个](https://vitepress.dev/guide/markdown#custom-containers)吗？

**Comment by vanchKong** [comment]
> 你指的 markdown.container 是指的[这个](https://vitepress.dev/guide/markdown#custom-containers)吗？

是的，就是这个

**Comment by awxiaoxian2020** [comment]
@vanchKong I think we should post it in English to engage with others.

**Comment by brc-dd** [comment]
`markdown.container` support can be a bit tricky as we'll have to somehow get the current locale in the markdown renderer. I'll see what we can do.

Regarding search I believe the recommended approach is https://vitepress.dev/reference/default-theme-search#local-search-i18n (it should be in top-level config, same for algolia too). Regarding `_render` function, we probably can pass the locale as env.locale (this logic would probably be shared between that container titles thing and this _render function).

In the meantime you can do something like:

```ts
_render(src, env, md) {
  if (env.relativePath.startsWith('/zh/') {
    ...
  }
}
```
