### ISSUE TITLE
The root node will be missing index.html

### ISSUE THREAD

**Issue by wChenonly** [vuejs/vitepress#3142]
### Describe the bug

1. At the beginning, the home page suffix has index.html, and it is no problem to refresh or click the title of utils.

2. Click the function label, switch to the function page, and then click the title of utils, and find that the home page suffix is missing index.html.
3. My base is  /xx/xxxUtils/
4. The final url is https:www.xxx.net/xx/xxxUtils/index.html

### Reproduction

1. At the beginning, the home page suffix has index.html, and it is no problem to refresh or click the title of utils.

2. Click the function label, switch to the function page, and then click the title of utils, and find that the home page suffix is missing index.html.

https://github.com/vuejs/vitepress/assets/37658262/3db2466f-6fca-463d-91b5-8bc898cfcc0c

### Expected behavior

It can still display xxxx/index.html normally.

### System Info

```Text
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 153.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 10.2.1 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.7.1 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wChenonly** [comment]
https://github.com/vuejs/vitepress/blob/main/src/client/app/router.ts#L340


Is there a problem here? I tried it and it doesn't seem to work.

**Comment by zonemeen** [comment]
@wChenonly Hi there, are you using the latest version of vitepress?

**Comment by wChenonly** [comment]
> zonemeen

yes,  1.0.0-rc.24

**Comment by zonemeen** [comment]
Can you share your project repository? Or reproduce it on [StackBlitz](https://vitepress.new/).

**Comment by zonemeen** [comment]
I reproduced the code implementation of your project locally. The suffix `index.html` will never appear in the homepage url.
My guess is that the some URL redirection rules in your deployment server cause the `index.html` suffix to be added to the home page at the beginning.
The homepage URL without the `index.html` suffix is ​​the behavior expected by vitepress.
