### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" 

### ISSUE THREAD

**Issue by myGitHubHuLin** [vuejs/vitepress#3145]
使用element-plus作二次封装组件库，npm run docs:build的时候还是会报错
https://stackblitz.com/edit/vite-laeh9e?file=docs%2F.vitepress%2Ftheme%2Findex.js,docs%2F.vitepress%2Fconfig.ts,package.json,docs%2Fexample.md

**Comment by kaikaibenkai** [comment]
老哥，用英语，按 issue 模板填，不然没人理你

**Comment by wChenonly** [comment]
config.ts中 {
    ssr: {
      noExternal: ['@huyuchen/visual', 'test-design-vue', 'element-plus'],
    }
  }

**Comment by YaminZheng** [comment]
> `vite: { ssr: { noExternal: ['@huyuchen/visual', 'test-design-vue', 'element-plus'], }, },`

感谢，这个对我来说有用，不过这个参数是什么意思？有没有副作用？

**Comment by wChenonly** [comment]
> > `vite: { ssr: { noExternal: ['@huyuchen/visual', 'test-design-vue', 'element-plus'], }, },`
> 
> 感谢，这个对我来说有用，不过这个参数是什么意思？有没有副作用？

https://vitejs.dev/config/ssr-options.html#ssr-noexternal
