### ISSUE TITLE
Use vitepress in an existing vue app

### ISSUE THREAD

**Issue by countryst** [vuejs/vitepress#315]
I'm new to vue and vitepress so I'm a little confused.

I'm looking into adding markdown to my existing vue app. The way I imagined it would be some markdown element which would take the markdown text and render it. I'm also interested in embedding vue components inside the markdown. Something like
```
<Markdown>
## abc
efg
### hij
Hi {{name}},
</Markdown>
```
I was hoping vitepress would do it, but it seems like vitepress sets everything up as a standalone app. I can't simply add vitepress to my package.json and start using it's elements.

Any examples of using vitepress in an existing vue as a library? Or any alternative?

**Comment by antfu** [comment]
I would think this is out-of-scope of vitepress. Wrapping https://github.com/markdown-it/markdown-it into a component would do I think.
