### ISSUE TITLE
Bad route to # anchor when using 3rd controls

### ISSUE THREAD

**Issue by DSYZayn** [vuejs/vitepress#3152]
### Describe the bug

I try to use leaflet map component in my docs, and the map has many controls with anchor "#",which may help the control's behavior.When I click these controls,the web page automatically jumped to the position #(but actually there's no content at xx.html/#).That troubles me
<img width="1280" alt="Snipaste_2023-10-28_21-04-37" src="https://github.com/vuejs/vitepress/assets/98650340/db01ab21-607e-46c1-8d47-5531530da3e5">

https://github.com/vuejs/vitepress/assets/98650340/e46e9987-8295-4fc6-aaf2-81acf8521ca8

### Reproduction

using leaflet in docs,and just click the zoom in/out control,the page will jump to xx.html/#.

### Expected behavior

Do not jump at this situation.

### System Info

```Text
win11, dev
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
consider adding `vp-raw` class to your component wrapper. You can also do something like:

```md
:::raw

<your-map-component />

:::raw

```

**Comment by DSYZayn** [comment]
@brc-dd That works. I noticed it suggests to use whyframe for completely isolation, if I use it,can I just wrap it with <iframe data-why> tag,or I must import js and css for every whyframe component? I don't know it causes extra cost or not.

**Comment by brc-dd** [comment]
I don't think that you'll need whyframe for this. That's mainly for documenting component libraries. Also, it won't be as simple as adding thing inside iframe. You'll need extra setup for that.
