### ISSUE TITLE
Build error while using relative image path in md files

### ISSUE THREAD

**Issue by DSYZayn** [vuejs/vitepress#3156]
### Describe the bug

My images are in the public folder,and I have a custom base url configuration in config.mts.  
I try to use relative path in md files like this:
```md
![testImage](../../imgs/super/intro/01.png)
```
But this cause error when build project,because it tries to find `../../imgs/super/intro/01.png`,but the path just adapt to runtime.
why not use `../../public/imgs/super/intro/01.png` or simply as '/imgs/super/intro/01.png'? Yes that works well in dev, but won't work when I deploy on gh-pages beacuse the custom base url.
#3139 

### Reproduction

put an image in `public/imgs/`, use it in a md file at path `docs/xx/xx/xx.md`

### Expected behavior

ignore the path when build or resolve it correctly.

### System Info

```Text
win11
```

### Additional context

![Snipaste_2023-10-30_12-28-26](https://github.com/vuejs/vitepress/assets/98650340/35677923-34b8-46bc-80d2-eb6d9af14b0a)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you share a reproducible example? It seems to be working fine for me, although it isn't recommended as that file will be duplicated in build:

<img width="400" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/b6d124b8-a362-4844-9650-7dbacf6a40f5">

**Comment by brc-dd** [comment]
In markdown if you use `/imgs/super/intro/01.png`, base will automatically be added. #3139 was different because frontmatter is basically string and nothing gets parsed there.

**Comment by DSYZayn** [comment]
![Snipaste_2023-10-31_22-36-49](https://github.com/vuejs/vitepress/assets/98650340/427293e8-44c2-44ff-a720-01b796247cb1)
I use ../../imgs/xxx/xxx.png like #3139.I tried to use /imgs/super/intro/01.png,but in dev browser it is localhost:5173/imgs/xxx, but I already use a custom base option, so it can  automatically be added while building?

> In markdown if you use `/imgs/super/intro/01.png`, base will automatically be added. #3139 was different because frontmatter is basically string and nothing gets parsed there.

**Comment by brc-dd** [comment]
Try this repo as example - https://github.com/brc-dd/vitepress-image-demo

hosted at https://brc-dd.github.io/vitepress-image-demo/bar/baz.html

In bar/baz.md, I have:

```md
# Test

![Alt text](/imgs/image.png)

![Alt text](./image.png)
```

imgs/image.png is stored inside public, and ./image.png is stored relative to that file. Both don't need you to do anything. You just need to specify base, and the build output will have proper paths.

**Comment by DSYZayn** [comment]
@brc-dd Thanks a lot
