### ISSUE TITLE
feature request: allow "On this page" menu to show more than h2 headings, like a tree

### ISSUE THREAD

**Issue by jcstein** [vuejs/vitepress#3158]
### Is your feature request related to a problem? Please describe.

I'd like to be able to show more headings on the "On this page" menu, as it is not very useful now.

![image](https://github.com/vuejs/vitepress/assets/46639943/052453e7-985a-4053-af2d-0c1c688bdfc1)

### Describe the solution you'd like

display headings as a tree, similar to this:
![scrot 2023-10-30 at 1 56 20 PM](https://github.com/vuejs/vitepress/assets/46639943/80be7737-2409-4ad9-93ab-7d38d9d43ce1)

### Describe alternatives you've considered

custom css, seems like it would be more useful as a feature though..

### Additional context

i looked in vitepress docs and couldn't find this as an option

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/default-theme-config#outline

**Comment by jcstein** [comment]
thank you as always 🫡 @brc-dd

**Comment by jcstein** [comment]
is there a way to config this globally?

**Comment by brc-dd** [comment]
If you add it to .vitepress/config, it's global. If you want you can override the global value via frontmatter.

```
// .vitepress/config.ts

export default {
  themeConfig: {
    outline: {
      level: 'deep'
    }
  }
}
```

**Comment by jcstein** [comment]
ahh i just had `outline: deep`

thank you again!

**Comment by jcstein** [comment]
hrm, doesn't seem to be working? https://github.com/celestiaorg/docs/commit/8db9c26097c0b94f3f7a099e87d468cf25274b9e

**Comment by brc-dd** [comment]
it's inside themeConfig
