### ISSUE TITLE
Full width layout for larger screens like desktop

### ISSUE THREAD

**Issue by Ephenodrom** [vuejs/vitepress#3160]
### Is your feature request related to a problem? Please describe.

The home page looks quite good on a larger display. Once you switch to a documentation page, the conent feels a bit squeezed together. This is mostly due to paddings from the left and right sidebar and the content. Each "padding" considered alone is not very large. However, when added together, I think a lot of space is wasted here.

### Describe the solution you'd like

Add a "full width" mode for desktop view, configureable via the theme settings (true/false). This should reduce the paddings and maximize the content width.

Now :
<img width="1624" alt="Screenshot1" src="https://github.com/vuejs/vitepress/assets/30625794/941774fd-b73f-4b03-8095-f1eda053f247">

Expected :
<img width="1624" alt="Screenshot2" src="https://github.com/vuejs/vitepress/assets/30625794/62a77e31-80a6-4f54-b894-28f58d3460af">

I think this will result in some better readability when you have a documentation with some screenshots or larger code parts.

### Describe alternatives you've considered

Maybe you can try to write some hacky CSS overrides, but this is not a good solution.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
I don't think this is a good idea. Current doc page are designed in a way that the content width and others in mind.

Now of course this is subjective matter. Some people prefer wider content area. I say it should be created as a different theme 👍

**Comment by brc-dd** [comment]
Also, longer lines are hard to read -- https://ux.stackexchange.com/a/108803
