### ISSUE TITLE
VitePress does not honor `vite.build.ssr = false`

### ISSUE THREAD

**Issue by Swivelgames** [vuejs/vitepress#3162]
### Describe the bug

Trying to build with `vite.build.ssr = false`, but it appears that VitePress continues to bundle everything as if preparing it to be served with a backend.

### Reproduction

Build VitePress with `vite.build.ssr = false`

### Expected behavior

Paths will become absolute and referenced modules will be bundled with the dist, unless excluded with `rollupOptions.external`.

### System Info

```Text
System:
    OS: macOS 13.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 487.25 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.7.6 - /usr/local/bin/pnpm
  Browsers:
    Safari: 16.6
    Firefox: 118.0.2
    Chrome: 118.0.5993.117
  npmPackages:
    vitepress: 1.0.0-rc.14 => 1.0.0-rc.14
```

### Additional context

VitePress should respect disabling `SSR` to allow for hosting via CDN.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I think you're confused between what SSR in this context means. VitePress performs SSR to generate static HTML/JS/CSS. You can host that wherever you want. You don't need a backend to serve that. Regarding paths, you probably need https://github.com/vuejs/vitepress/pull/2467
