### ISSUE TITLE
Disable or modify usePrefetch behavior (rel="prefetch" on links)

### ISSUE THREAD

**Issue by marce1994** [vuejs/vitepress#3163]
### Is your feature request related to a problem? Please describe.

I have a large amount of links (78 links) on my index webpage, and I'm mounting it in AWS Cloudfront. I'm getting 503 errors since I'm doing a kind of DOS attack prefetching all 78 links...

I think this issue is related to usePrefetch() that enables "intersectionObserver based pre-fetch", and since all my links are above the webpage they are all prefetched at once...

### Describe the solution you'd like

I want to add an easy way of disabling this feature or find a way to only fetch them when links are visible/unfolded (they are dropdowns).

![image](https://github.com/vuejs/vitepress/assets/358126/f41c1816-dbdd-4aa5-8478-092c0a7108c8)

![image](https://github.com/vuejs/vitepress/assets/358126/a2ab4e2f-8ac0-46fe-a896-03bdea48b4d1)

### Describe alternatives you've considered

I didn't try another way. Maybe someone with more experience can do this easily.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by marce1994** [comment]
my "workaround" was to just comment the line in the source code:
![image](https://github.com/vuejs/vitepress/assets/358126/7fd32e9d-6e6f-45aa-91d5-3adf0549ef6d)

**Comment by brc-dd** [comment]
Contributions are welcome, simple `prefetch: false` in config should be sufficient. Although I'm not sure if this should cause 503. I can't find any such issue on https://github.com/GoogleChromeLabs/quicklink

**Comment by marce1994** [comment]
> Contributions are welcome, simple `prefetch: false` in config should be sufficient. Although I'm not sure if this should cause 503. I can't find any such issue on https://github.com/GoogleChromeLabs/quicklink

the 503 is more related to my hosting server, it has a "max hit ratio" per IP :)

**Comment by marce1994** [comment]
Now I'm trying to finish something urgent, but if I have some time and I find a way of adding that config (thought it was simple), I'll take a look and make a PR. 😄

**Comment by bonyuta0204** [comment]
@brc-dd @marce1994
Apologies if @marce1994 has already begun addressing this issue, but I have created a pull request related to it. 
Could you please take a moment to review it?
https://github.com/vuejs/vitepress/pull/3220

**Comment by brc-dd** [comment]
Thanks for the PR. Will be supported in the next version as:

```ts
// .vitepress/config.ts
export default {
  router: {
    prefetchLinks: false
  }
}
```

**Comment by marce1994** [comment]
> @brc-dd @marce1994
> Apologies if @marce1994 has already begun addressing this issue, but I have created a pull request related to it. 
> Could you please take a moment to review it?
> https://github.com/vuejs/vitepress/pull/3220

Nvm I did start to investigate but never continued. Thank you for the PR :)
