### ISSUE TITLE
When running vitepress, how to point the vite attribute in defineConfig to the viete.config.js file

### ISSUE THREAD

**Issue by Jevin0** [vuejs/vitepress#3164]
### Is your feature request related to a problem? Please describe.

-

### Describe the solution you'd like

-

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please explain what are you trying to do? You can keep your vite config in your `vite.config.js`. You don't need any extra config, but some stuff might not work.

**Comment by Jevin0** [comment]
@brc-dd Sorry, I didn't express the question clearly yesterday.
https://github.com/Jevin0/vite-vue3-ui/tree/master/docs
This is a demo address
When I want to start vitepree. The vite.config.js configuration under the docs folder will be enabled. And print out the 123 content inside. what should I do

**Comment by brc-dd** [comment]
Yeah, that's because vitepress will load vite.config.js too. You can disable that by setting `vite: { configFile: false }` in your vitepress config. Still not sure why you need that.

PS: feel free to your native language if conveying the ideas in English is difficult for you.

**Comment by Jevin0** [comment]
可是在上面的我发的demo中。运行vitepress，vie.config.js
![image](https://github.com/vuejs/vitepress/assets/69580637/8b1cbf00-59b5-4afd-afdd-5d662ce433e6)
中的这个123并不会打印。

**Comment by Jevin0** [comment]
OK, thanks, I know what the problem is
