### ISSUE TITLE
easily override a style on a single page scope

### ISSUE THREAD

**Issue by pberto** [vuejs/vitepress#3172]
### Describe the bug

this is more a question that could lead to a feature request. See the repro below.

### Reproduction

I'd like to override a css style on one page only.

On a default vitepress site, duplicate the `index.md` page, to `index2.md`. Then in index add at the bottom:

```
<style>
  .item.grid-6, .item.grid-4, .item.grid-3, .item.grid-2{
    width: calc(100% / 1) !important;
  }
</style>
```
This will make the vpfeatures span across the whole page at any screen size.

This works fine on a quick sight, but, when I browse back to `index.md`, also on this page they are page spanned. If I reload the page however there are again 3 features per page span.

I'd like the style override to be scoped only on page index2. Of course I could duplicate the component, rename it, and change the component style but it sounds like a overkill. I was wondering there must be a more straight forward way to do a page-scoped css override.

### Expected behavior

Style to be page scoped.

### System Info

```Text
Any.
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/frontmatter-config#pageclass (instead of `.vitepress/theme/custom.css`, you can have the styles in your markdown file, it'll work just the same).

**Comment by pberto** [comment]
Wow, sorry I really did not see this one.
