### ISSUE TITLE
[FR] Add before/after router hooks

### ISSUE THREAD

**Issue by khalwat** [vuejs/vitepress#318]
Add before/after router hooks so that can be added via `enhanceApp()`, to allow for code to be executed when new pages are routed to

My specific use-case is to be able to fire Google Analytics tracking events after a new page is routed to, but there could be any number of cases where it might be useful to have these basic before/after router hooks, e.g.:

```js
    enhanceApp: (ctx) => {
        ctx.router.hooks.after = (route) => { console.log("after!")};
    }
```

Implemented via pull request: https://github.com/vuejs/vitepress/pull/317

**Comment by posva** [comment]
You can just `watch` the route location to have an `afterEach()`
Having a before route hook without being able to control the navigation isn't really useful.

**Comment by mashpie** [comment]
for those (like me) looking for an example:

```js
// /.vitepress/theme/index.js

import { watch } from 'vue'

// [...]

export default {
  // [...]
  enhanceApp({ app, router, siteData }) {
    watch(router.route, () => {
      console.log('route changed', router.route.path)
    })
  }
}

```
