### ISSUE TITLE
Symptom When the npm package is used, Build-Time Data Loading is abnormal

### ISSUE THREAD

**Issue by MaLuns** [vuejs/vitepress#3185]
### Describe the bug

我在使用自定义主题中, 给主题添加一个 i18n 功能, 是通过构建时数据加载方式进行加载的, 然后再 enhanceApp 中挂在一个全局的 `$t` 方法以便于在组件中方便设置 i18n 配置. 当然自定义主题文件放置在 `theme` 下时, 执行 dev 或者 build 时一切正常, 但是我将之定义主题发布到 npm 后, 通过 npm 安装引入后, 执行 dev 就会出现 ` No matching export in "node_modules/vitepress-theme-async/composables/languages.data.ts" for import "data"` 的错误 ,但是执行 build 是正常的.

### Reproduction

可以通过 `npm create async-theme@latest my-first-blog` 命令, 快速初始化一个可复现 demo 

### Expected behavior

通过 npm 发布的主题包和将文件放置在 `theme` 下行为一致

### System Info

```Text
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 7.37 GB / 15.88 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.1 - C:\Program Files\nodejs\pnpm.CMD
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
yeah, known issue - https://github.com/vuejs/vitepress/issues/2179
