### ISSUE TITLE
Property 'glob' does not exist on type 'ImportMeta'

### ISSUE THREAD

**Issue by tomiaa12** [vuejs/vitepress#3186]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/34568691/6a07bc6f-9978-451c-be70-676a52daa40d)

### Reproduction

import.meta.glob is undefind

### Expected behavior

import.meta.glob([xxxx/xxx.ts])

### System Info

```Text
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 2.21 GB / 15.64 GB
  Binaries:
    Node: 20.8.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.44)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-rc.25 => 1.0.0-rc.25
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's not there in config files. It not there in vite config files either.
