### ISSUE TITLE
missed 'base' path when run 'vitepress dev docs' behind nginx

### ISSUE THREAD

**Issue by 285851937** [vuejs/vitepress#319]
**Describe the bug**
To set 'base' property in '.vitepress/config.js', and run 'vitepress dev docs' behind nginx. When access it, the 'index.js' can't be loaded. Because it's path missed 'base' path.  
Server response like this:
``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/@fs//xxxxxxxxx/doc-index/node_modules/vitepress/dist/client/app/index.js"></script>
  </body>
</html>
```
I set the base is '/docs/'. So, the path of 'index.js' shuld be: 
``` html 
/docs/@fs//xxxxxxxxx/doc-index/node_modules/vitepress/dist/client/app/index.js
```

By the way, line number 131 of 'vitepress/src/node/plugin.js' shuld be: 
``` html
<script type="module" src="${siteData.base}@fs/${APP_PATH}/index.js"></script>
```

**System Info**
- vitepress version: 0.14.1
- vite version: 2.3.7
- Node version: v12.8.1
- OS version: Windows 10 pro 21H1 19043.1055

**Comment by skyroam** [comment]
@285851937 Hi, have you solved that? I want to run it with nginx reverse proxy, but I don't know how.

**Comment by 285851937** [comment]
I chose a **Informal way** to solve that. In my case:  
step1: to install 'vitepress' with a fixed version. eg:vitepress@0.20.0.  
step2: go to the directory of vitepress. eg: ```node_modules/vitepress/dist/node``` and find 'serve-xxx.js'.  
step3: Modify 'serve-xxx.js'. To open the file and find keyword 'viewport'. You can see this line ```<script type="module" src="/@fs/${APP_PATH}/index.js"><\/script>```, just add '${siteData.base}' before '@fs/${APP_PATH}...'，like ```<script type="module" src="${siteData.base}@fs/${APP_PATH}/index.js"><\/script>```.  

Note That:If you want to re-install vitepress each time with the project be deployed, you should backup the 'serve-xxx.js', and to replace the new one that after vitepress was be installed, in order to keep the request path is correct.

**Comment by kiaking** [comment]
Not sure if this still happens in latest version, but we should check it before 1.0.0.

**Comment by kiaking** [comment]
Can anybody check if this is still an issue with the latest version?

**Comment by schirrel** [comment]
I have this problem when build and deploy to a custom page, i am deploying to `https://schirrel.dev/vue-cruder/` but the assests and stuff keep getting point to `https://schirrel.dev/` because the path is missing
