### ISSUE TITLE
Markdown files with several dots `.` in name are not routed

### ISSUE THREAD

**Issue by Ianis** [vuejs/vitepress#3191]
### Describe the bug

A markdown file with several dots `.` such as `software-1.2.3.md`  is not properly routed and leads to a 404 error.
I guess that the router assumes that there is a file named `/software-1.2.3` with the `.3` extension when using cleanUrls.

### Reproduction

1. Create a new VitePress project
2. Create a new markdown file named `software-1.2.3.md` with some content.
3. Create links the `/software-1.2.3` page in the `index.md` file. 
```md
[/software-1.2.3](/software-1.2.3)
[/software-1.2.3.md](/software-1.2.3.md)
``` 
5. Enable `cleanUrls`.
6. Click the links on the index page.

### Expected behavior

The router should load the page `/software-1.2.3` when  cleanUrls are active.

### System Info

```Text
System:
    OS: macOS 11.7.10
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 85.34 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.9.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.6.1
  npmPackages:
    vitepress: ^1.0.0-rc.25 => 1.0.0-rc.25
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kaikaibenkai** [comment]
> I guess that the router assumes that there is a file named /software-1.2.3 with the .3 extension when using cleanUrls.

it's like a feature (?) try `/software-1.2.3.html`
