### ISSUE TITLE
The logo disappears after it is built

### ISSUE THREAD

**Issue by xincheng-1999** [vuejs/vitepress#3197]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/67899096/9793e3f1-f337-4d04-89ab-a58b76e4e684)
I configured the logo as shown above and I can see my logo in dev mode，but after the build, the logo is gone，I can't find the logo.webp in the dist folder 

### Reproduction

see Describe the bug

### Expected behavior

Expect the logo file to be in the dist directory after build

### System Info

```Text
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 89.69 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
    pnpm: 8.7.4 - ~/.nvm/versions/node/v18.12.0/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.105
    Safari: 17.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
that should be inside the public directory -- src/public/icon.webp

**Comment by xincheng-1999** [comment]
> that should be inside the public directory -- src/public/icon.webp

Thanks for the answer
