### ISSUE TITLE
Multiple root nodes custom Vue element will fail to render in vitepress

### ISSUE THREAD

**Issue by HerringtonDarkholme** [vuejs/vitepress#3199]
### Describe the bug

Thanks for building vitepress!

I have a vitepress website and I found that a custom vue component with [multiple root nodes](https://v3-migration.vuejs.org/new/fragments.html) will fail to render in production mode.

### Reproduction

https://github.com/ast-grep/ast-grep.github.io/tree/repro-vite

```
git clone --branch repro-vite git@github.com:ast-grep/ast-grep.github.io.git
pnpm install
pnpm build
pnpm serve
```

Then visit localhost:4173

### Expected behavior

The `Supported Languages` section, of which the [code is here](https://github.com/ast-grep/ast-grep.github.io/blob/repro-vite/website/src/homepage/Languages.vue),  should render.

<img width="1115" alt="image" src="https://github.com/vuejs/vitepress/assets/2883231/2faa0688-df54-47a6-9e47-cc3e5f8f85ac">

### System Info

```Text
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 81.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/Library/Caches/fnm_multishells/62761_1699555887568/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/62761_1699555887568/bin/npm
    pnpm: 8.6.3 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 15.6.1
```

### Additional context

The languages.vue has two root elements in the template.

Source
<img width="405" alt="image" src="https://github.com/vuejs/vitepress/assets/2883231/e92eb6f2-1d61-4b3a-b65d-fa71502a675c">

Actual rendering include zero language images: 
<img width="753" alt="image" src="https://github.com/vuejs/vitepress/assets/2883231/8f7b4a16-06da-4587-83aa-5ded94ad0ab6">
With HTML:
<img width="424" alt="image" src="https://github.com/vuejs/vitepress/assets/2883231/7a4fe317-db1b-429e-a1d1-4be2fa63f6bf">

----

However, it looks like the static HTML built on server side is correct.

Rendering if JS is disabled
<img width="876" alt="image" src="https://github.com/vuejs/vitepress/assets/2883231/ab2ffe30-d9bd-4e0d-b2bb-d82e36540297">
Actual HTML without JS
<img width="391" alt="image" src="https://github.com/vuejs/vitepress/assets/2883231/1af71121-dbae-4115-882e-ef348b931ca9">

---
Also, if I [avoid the multiple root nodes](https://github.com/ast-grep/ast-grep.github.io/blob/main/website/src/homepage/Languages.vue#L2), the [page looks like fine](https://ast-grep.github.io/).

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Something else appears to be an issue here. If there are not more than two elements in the languages it works fine. For example:

<img width="313" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/cb64ddb3-ea80-4ac6-8aff-89ddba3b80a7"> <img width="393" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/bc234742-71a6-4318-8b2d-f25c12fb91b6">

**Comment by brc-dd** [comment]
Please remove `vite.build.ssr` from your vitepress.config

**Comment by HerringtonDarkholme** [comment]
I believe the ssr: false is required for docs indexing for search. It used to need ssr:false to enable build search using external search plugin. Back then there is no builtin search in vitepress.

I believe there are plenty of options to work around the issue.
My point is why ssr option will impact the rendering behavior here?

**Comment by brc-dd** [comment]
> It used to need ssr:false to enable build search using external search plugin.

Ah this was fixed there IG.

> My point is why ssr option will impact the rendering behavior here?

Not exactly sure. I can try finding why different server rendered HTML is being generated. I'm not even sure how user's `build.ssr` is leaking. We aren't respecting it anywhere. Specifying shouldn't have even mattered.

Also, there wasn't any issue with multiple root nodes. If you remove stuff inside div.languages it'd work fine too. Even if you keep two images inside that it'll work fine. Adding more than two elements breaks that. I'm guessing there is some sort of inconsistency between the ssr value here. Some part of maybe vue or vite-plugin-vue is respecting the user's ssr option while other is not.
