### ISSUE TITLE
How to add favicon?

### ISSUE THREAD

**Issue by carveybunt** [vuejs/vitepress#320]
I don't saw any description for custom favicon in documents. Somebody could help me? I was to try the file `favicon.ico` to move to `.vitepress/public`, but it not working.

**Comment by stafyniaksacha** [comment]
Hello,

You have to add a link to your favicon too in your `.vitepress/config.js`
Images should be in the `public/` folder (not in  `.vitepress/public/`)

```js
module.export = {
  // ...
  head: [
    ['link', { rel: 'icon', type: 'image/x-icon', href: '/path/to/favicon.ico' }],
    // ['link', { rel: 'icon', type: 'image/svg+xml', href: '/path/to/icon.svg' }], for svg
  ],
  // ...
}
```

Hope this help!

**Comment by carveybunt** [comment]
@stafyniaksacha Thanks, I will be to try that late.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
