### ISSUE TITLE
i18n and multiple sidebars problem

### ISSUE THREAD

**Issue by altrusl** [vuejs/vitepress#3202]
### Is your feature request related to a problem? Please describe.

Multiple sidebars do not work with multiple locales

Multiple sidebars work only for the root locale

```js
import sidebar_es from "./sidebar.es";
import sidebar_en from "./sidebar.en";
import sidebar_subdir_es from "./sidebar.subdir.es";
import sidebar_subdir_en from "./sidebar.subdir.en";

export default defineConfig({
  locales: {
    root: {
      lang: "sp",
      label: "Spanish",
      themeConfig: {
        nav: nav_es,
        sidebar: {
          "/": sidebar_es,
          "/subdir/": sidebar_subdir_es,
        },
      },
    },
    en: {
      lang: "en",
      label: "English",
      themeConfig: {
        nav: nav_en,
        sidebar: {
          "/": sidebar_en,
          "/subdir/": sidebar_subdir_en,
        },
      },
```

In this example `/en/subdir/` path shows default `sidebar_en` sidebar

### Describe the solution you'd like

Multiple sidebars should work for secondary locales

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`"/en/subdir/": sidebar_subdir_en,`

**Comment by altrusl** [comment]
> `"/en/subdir/": sidebar_subdir_en,`

Thank a lot
I was confused by the fact that `/` for the `en` locale is working properly...

**Comment by brc-dd** [comment]
`"/en/": sidebar_en,` would also work fine. `/` is working in your case because that matches everything and your Spanish config is ignored when you're in /en/something.

PS: `lang: "sp"` should be `lang: "es"`
