### ISSUE TITLE
publicDir configuration option

### ISSUE THREAD

**Issue by uncenter** [vuejs/vitepress#3203]
### Is your feature request related to a problem? Please describe.

Currently the `public/` directory has to be inside the `srcDir`. I'd like to have a structure like this, where `srcDir` is `src`:

```
public/
└── a.jpg
└── b.png
src/
└── index.md
```

### Describe the solution you'd like

I think a `publicDir` option would be nice. It might make sense to be `public/` by default and resolve inside `src/`, so for my situation I would set it as `../public`.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Have you tried setting `vite: { publicDir: 'your-value' }` in your config?

**Comment by uncenter** [comment]
Ah sorry I didn't realize that was an option. That does the trick, thank you! It might be worth mentioning that [in the public directory section of the docs](https://vitepress.dev/guide/asset-handling#the-public-directory).
