### ISSUE TITLE
code-group 支持统一切换

### ISSUE THREAD

**Issue by Suomm** [vuejs/vitepress#3205]
### Is your feature request related to a problem? Please describe.

当我点击第一个 `code-group` 中的 `模式二` 之后，第二个 `code-group` 中并未切换到 `模式二`。

![image](https://github.com/vuejs/vitepress/assets/27558987/e98bcc0d-275d-4ad5-ba4a-bff64a02b971)

### Describe the solution you'd like

当我点击第一个 `code-group` 中的 `模式二` 之后，第二个 `code-group` 中也会切换到 `模式二`。

![image](https://github.com/vuejs/vitepress/assets/27558987/1b28c928-7490-4017-9a2f-8f0ded30a249)

### Describe alternatives you've considered

Like this：https://docs.livekit.io/realtime/server/generating-tokens/

![vitepress_code_group](https://github.com/vuejs/vitepress/assets/27558987/78ec2430-514b-44aa-bf54-6146a5853af5)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
use https://vitepress-plugins.sapphi.red/tabs/

**Comment by Suomm** [comment]
> use https://vitepress-plugins.sapphi.red/tabs/

OK！
