### ISSUE TITLE
"On this page sidebar" only render ## H2, H3/H4 can't be resolved.

### ISSUE THREAD

**Issue by xunhui** [vuejs/vitepress#3210]
### Describe the bug

"On this page sidebar" only render the ## H2, H3/H4 can't be resolved.

### Reproduction

ThemeConfig:
![image](https://github.com/vuejs/vitepress/assets/12594325/d0fb565d-9456-46eb-a188-c492d51f5816)

My markdown content:
![image](https://github.com/vuejs/vitepress/assets/12594325/3848205d-aa7a-42d0-aead-e4ada1164ac5)

Page Render Result:
![image](https://github.com/vuejs/vitepress/assets/12594325/212bd998-c18b-4842-8690-c896b8eef445)

### Expected behavior

H3/H4 will be resolved correctly at "On the page" sidebar.

### System Info

```Text
System:
    OS: macOS 13.3
    CPU: (12) x64 Apple M2 Pro
    Memory: 25.97 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.8.0 - ~/.nvm/versions/node/v18.12.1/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.123
    Chrome Canary: 121.0.6130.0
    Edge: 119.0.2151.58
    Safari: 16.4
  npmPackages:
    vitepress: 1.0.0-rc.25 => 1.0.0-rc.25
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Set `outline: 'deep'` in your themeConfig

**Comment by xunhui** [comment]
Thanks, I missed this config. Maybe you can add some details in Sidebar chapter.

**Comment by brc-dd** [comment]
Sidebar is the left one. Right one is called aside/outline. It's mentioned in the overview: https://vitepress.dev/reference/default-theme-config#outline
