### ISSUE TITLE
Locales Dropdown isn't displayed in navBar

### ISSUE THREAD

**Issue by m4dz** [vuejs/vitepress#322]
**Describe the bug**
Following #50 and #91, `locales` and `theme.locales` stay empty, whatever has been defined in `config.js`. 

**To Reproduce**

1. add to config.js
   ```
   module.exports = {
     ...
     locales: {
       '/': { lang: 'en-US' },
       '/fr/': { lang: ' fr-FR' },
     },
     ...
     themeConfig: {
       ...
       locales: {
         '/': { label: 'English' },
         '/fr/' : { label: 'Français' },
       },
     },
   };
   ```

**Expected behavior**
Dropdown lang selected should be displayed.

**System Info**
- vitepress version: 0.15.4
- vite version: 2.3.7
- Node version: v16.3.0
- OS version: macOS 11.4

**Comment by MartinMalinda** [comment]
This seems to be fixed by @m4dz and it could be closed? I encountered this issue but then I updated to a later version of vitepress and it's gone.

**Comment by kiaking** [comment]
Seems like this is fixed 👍
