### ISSUE TITLE
Unneeded scrollbar in sidebar

### ISSUE THREAD

**Issue by patak-dev** [vuejs/vitepress#3228]
### Describe the bug

A scrollbar appears in the sidebar when it isn't required:
<img width="1727" alt="image" src="https://github.com/vuejs/vitepress/assets/583075/777b43ef-7bf4-4794-9b6a-2e598411b386">

I saw the same in https://vitepress.dev

### Reproduction

Run the vitepress dev docs.

### Expected behavior

The sidebar shouldn't be there until there are enough items in the sidebar.

### System Info

```Text
n/a
```

### Additional context

There is a `padding-bottom: 128px` [here](https://github.com/vuejs/vitepress/blob/85bd7e845ab37862d68d2506f0b693dafc236a7a/src/client/theme-default/components/VPSidebar.vue#L92) that may be part of the issue. It seems the height of the sidebar should also be reviewed.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by dy-xiaodong2022** [comment]
It seems like a style problem caused by padding.

**Comment by patak-dev** [comment]
@brc-dd thanks for the fix! I checked removing that line before and it only seems to work for the vite docs. I think there is some extra spacing still around that makes the vitepress docs show the sidebar when it could be avoided

**Comment by brc-dd** [comment]
Ah yeah. We still have 64px extra padding at bottom. I guess that was intentional to avoid having to move mouse/finger at the bottom to click something. @kiaking might know better.
