### ISSUE TITLE
Does the hero configuration not support image?

### ISSUE THREAD

**Issue by dodu2014** [vuejs/vitepress#3232]
### Describe the bug

hreo:
  image:
    src: /logo.png
    alt: logo

After configuring image, an error was reported during compilation, as follows:

![image](https://github.com/vuejs/vitepress/assets/15245544/a6a49a1a-419c-4030-a762-033f42819cdb)

### Reproduction

add image configuration under hreo

### Expected behavior

continue to support image config

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
    Memory: 16.45 GB / 31.87 GB
  Binaries:
    Node: 18.16.0 - d:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.4 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 7.33.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.72)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-rc.29 => 1.0.0-rc.29
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please share a reproducible example in the form of a GitHub repo or StackBlitz link (https://vitepress.new)
