### ISSUE TITLE
文章目录不显示一级标题

### ISSUE THREAD

**Issue by cruvie** [vuejs/vitepress#3234]
### Describe the bug

文章目录不显示一级标题

### Reproduction

```mts
import {withMermaid} from "vitepress-plugin-mermaid";
// https://emersonbottero.github.io/vitepress-plugin-mermaid/guide/getting-started.html
// https://vitepress.dev/reference/site-config
import {generateSidebar} from 'vitepress-sidebar';

export default withMermaid({
    title: "DMP-Docs",
    description: "DMP-Docs",
    themeConfig: {
        // https://vitepress.dev/reference/default-theme-config
        nav: [
            {text: 'Home', link: '/'},
        ],

        search: {
            provider: 'local'
        },
        sidebar: generateSidebar({
            documentRootPath: '/docs',
        }),
        socialLinks: [
            {icon: 'github', link: 'http://10.186.18.21/dmp-dev-newbie/caomingkang/DMP-DOC'}
        ],

        outline: 'deep'
    },
    // optionally, you can pass MermaidConfig
    mermaid: {
        // refer https://mermaid.js.org/config/setup/modules/mermaidAPI.html#mermaidapi-configuration-defaults for options
    },
    // optionally set additional config for plugin itself with MermaidPluginConfig
    mermaidPlugin: {
        class: "mermaid my-class", // set additional css classes for parent container
    },

})






```

### Expected behavior

显示一级目录导航

### System Info

```Text
macos 13
 "vitepress": "^1.0.0-rc.29",
```

### Additional context

<img width="1159" alt="Xnip2023-11-22_18-52-26" src="https://github.com/vuejs/vitepress/assets/55651847/e1924277-32d5-45bb-a609-763b0e672075">

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by dy-xiaodong2022** [comment]
Hi, this is not a bug, if you want to make some changes to the thing you’re saying, please reopen a **feature** issue.
This issue can be closed now.

**Comment by brc-dd** [comment]
Use `outline: [1, 6]` instead of `outline: 'deep'`
