### ISSUE TITLE
add nginx config example 

### ISSUE THREAD

**Issue by Alexufo** [vuejs/vitepress#3235]
### Is your feature request related to a problem? Please describe.

Hard to understand how netllify example should be rewritten for nginx
```
/*  /es/:splat  302  Language=es
/*  /fr/:splat  302  Language=fr
/*  /en/:splat  302
```

### Describe the solution you'd like

nginx config wll be nice to present in doc

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Try the solutions mentioned in this threads - https://stackoverflow.com/a/9983986/11613622 -- you can also search online for similar solutions (make a web search on something like "nginx redirect based on language header"). Please let us know whichever solution works for you. We will add that to docs.

**Comment by Alexufo** [comment]
Switch language button set nf_lang cookie  and add language prefix in current url. I see text in new language but all links in menu still opend without prefix. They are not load any content from server and nginx config cant do anything with this behaivor (redirect).

Nginx config working if I manually call adress from adress bar.
I think something wrong with saving lang in browser and vitepress.

**Comment by pclokcer** [comment]
```
root /viteproject/.vitepress/dist;

location / {
    try_files $uri $uri/ $uri.html =404;
}
```    
I used this nginx settings. it is worked

**Comment by TerryYoung518** [comment]
I use the following code snippet, and it works well:
```
map $http_accept_language $lang {
    default "";
    ~*^zh zh;
}


server {
    ...
    location = / {
        rewrite (.*) $1/$lang;
        root    html/my-docs;
        index   index.html;
    }
    location / {
        root    html/my-docs;
        index   index.html;
    }
}
```
