### ISSUE TITLE
Compilation error [commonjs--resolver] Expected '(', got 'string literal (object, 'object')'

### ISSUE THREAD

**Issue by tomiaa12** [vuejs/vitepress#3238]
### Describe the bug

npm run build

> vitepress@0.0.0 build
> vitepress build src

  vitepress v1.0.0-rc.29

[commonjs--resolver] Expected '(', got 'string literal (object, 'object')'
file: F:/github/blog/node_modules/.pnpm/lerc@3.0.0/node_modules/lerc/LercDecode.js:2314:10
2312:     define([], function() { return Lerc; });/* jshint ignore:line */
2313:   }
2314:   else if (typeof module !== "undefined" && module.exports) {/* jshint ignore:line */
                ^
2315:     //commonJS module 1.0/1.1/1.1.1 systems, such as nodeJS
2316:     //http://wiki.commonjs.org/wiki/Modules
✖ building client + server bundles...
build error:
RollupError: Expected '(', got 'string literal (object, 'object')'
    at error (file:///F:/github/blog/node_modules/.pnpm/rollup@4.5.1/node_modules/rollup/dist/es/shared/parseAst.js:337:30)        
    at nodeConverters (file:///F:/github/blog/node_modules/.pnpm/rollup@4.5.1/node_modules/rollup/dist/es/shared/parseAst.js:2090:9)
    at convertNode (file:///F:/github/blog/node_modules/.pnpm/rollup@4.5.1/node_modules/rollup/dist/es/shared/parseAst.js:975:12)  
    at convertProgram (file:///F:/github/blog/node_modules/.pnpm/rollup@4.5.1/node_modules/rollup/dist/es/shared/parseAst.js:966:48)
    at parseAstAsync (file:///F:/github/blog/node_modules/.pnpm/rollup@4.5.1/node_modules/rollup/dist/es/shared/parseAst.js:2156:20)
    at async Module.tryParseAsync (file:///F:/github/blog/node_modules/.pnpm/rollup@4.5.1/node_modules/rollup/dist/es/shared/node-entry.js:13499:21)
    at async Module.setSource (file:///F:/github/blog/node_modules/.pnpm/rollup@4.5.1/node_modules/rollup/dist/es/shared/node-entry.js:13080:35)
    at async ModuleLoader.addModuleSource (file:///F:/github/blog/node_modules/.pnpm/rollup@4.5.1/node_modules/rollup/dist/es/shared/node-entry.js:17722:13)

### Reproduction

https://github.com/tomiaa12/blog

pnpm update 
pnpm update vitepress@latest

pnpm build

### Expected behavior

Compilation successful

### System Info

```Text
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 3.21 GB / 15.64 GB
  Binaries:
    Node: 21.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.72)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-rc.29 => 1.0.0-rc.29
```

### Validations

- [x] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by tomiaa12** [comment]
Normal in rc.29, error in rc.26+

**Comment by brc-dd** [comment]
Ah, something to do with vite 5 / rollup 4 bump. I'll take a look.

**Comment by wxzgis** [comment]
> Ah, something to do with vite 5 / rollup 4 bump. I'll take a look.

Is there a solution for this situation at the moment

**Comment by tomiaa12** [comment]
谁有什么好的办法解决吗，目前一直不能更新vitepress

**Comment by brc-dd** [comment]
Hi, I just updated the related dependencies and everything seems to work fine on your repo. Can you check again if the problem is reproducible?

<img width="453" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/597ab7ce-a20f-477e-9578-4b897425aa44">
<img width="285" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/46d21b4e-18d5-454f-a8c7-dfd9d1effc82">

**Comment by tomiaa12** [comment]
Upgraded to vitepress v1.0.0-rc.40 resolved the issue

**Comment by tomiaa12** [comment]
Upgraded to vitepress v1.0.0-rc.40 resolved the issue

> Hi, I just updated the related dependencies and everything seems to work fine on your repo. Can you check again if the problem is reproducible?
> 
> <img alt="image" width="453" src="https://private-user-images.githubusercontent.com/40380293/298374527-597ab7ce-a20f-477e-9578-4b897425aa44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDk4ODksIm5iZiI6MTcwNjE0OTU4OSwicGF0aCI6Ii80MDM4MDI5My8yOTgzNzQ1MjctNTk3YWI3Y2UtYTIwZi00NzdlLTk1NzgtNGI4OTc0MjVhYTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAyMjYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NzYxN2ExMzk5NmMxMmI1Yzc3ZDI0NzdmZWMyMGJiZDRiMmRmMDY4MmQyZmZjMGZmNmRhZjU1MzQ2ZTYzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MS_ZyKxzWEKghSdZUQDWfqYuWT2SyN_3sE2_woSZ9QA"> <img alt="image" width="285" src="https://private-user-images.githubusercontent.com/40380293/298374538-46d21b4e-18d5-454f-a8c7-dfd9d1effc82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDk4ODksIm5iZiI6MTcwNjE0OTU4OSwicGF0aCI6Ii80MDM4MDI5My8yOTgzNzQ1MzgtNDZkMjFiNGUtMThkNS00NTRmLWE4YzctZGZkOWQxZWZmYzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAyMjYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZjQyZjVlMmQ1YmI1OWZkMTMyMjI4ODNiNTFkMjZjOTdkNGVhZjNkNzgxOGUyMTFjMGQ0MDdmMTIxNWIyOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IpSiUmiQDemnPiHZmksGNOHEZFSnidiqndavuudLhcI">
