### ISSUE TITLE
文章目录不显示一级标题

### ISSUE THREAD

**Issue by cruvie** [vuejs/vitepress#3242]
### Is your feature request related to a problem? Please describe.

文章目录不显示一级标题

### Describe the solution you'd like

文章目录显示一级标题

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Refer solution at #3234
