### ISSUE TITLE
Missing `/` in sidebar link prevents prev/next to be generated correctly

### ISSUE THREAD

**Issue by koebi** [vuejs/vitepress#3243]
### Describe the bug

Although the documentation mentions that 
> Each link should specify the path to the actual file starting with `/`.
the sidebar works without the starting `/` - but prev/next links don't.

### Reproduction

Add two pages (`Foo.md`, `Bar.md`) to `vitepress.new`.
Add them to the sidebar, as in the docs:
```
sidebar: [
      {
        // text: 'Guide',
        items: [
          { text: 'Example', link: '/example' },
          { text: 'Foo', link: '/Foo'},
          { text: 'Bar', link: '/Bar'}
        ],
      },
    ]
 ```
 This works as intended.
 
 Removing the `/` before `example`, `Foo` and `Bar` makes the sidebar generation work, but doesn't generate prev/next correctly.

### Expected behavior

I'd expect the sidebar to fail or the prev/next links to be generated correctly.

### System Info

```Text
vitepress.new
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by mathiash98** [comment]
For me the issue was using the same sidebar style as the vitepress docs:

https://github.com/vuejs/vitepress/blob/47a7203258b8b04ad3f32aaa5cbf39b05b529067/docs/.vitepress/config.ts#L51C1-L51-54C1

```Json
    sidebar: {
      '/guide/': { base: '/guide/', items: sidebarGuide() },
      '/reference/': { base: '/reference/', items: sidebarReference() }
    },
```

replaced `base` and `/guide/` with just the list of items and moved the baseUrl into each link  and prev/next links worked.
Vitepress `1.0.0-rc.31`

**Comment by soerenmartius** [comment]
+1, experiencing the same issue

**Comment by brc-dd** [comment]
This is not a bug rather a configuration issue. We can't validate every edge case. Put in correct data, it will work fine.
