### ISSUE TITLE
Support ignoring the specified path generation

### ISSUE THREAD

**Issue by HerbertHe** [vuejs/vitepress#3255]
### Is your feature request related to a problem? Please describe.

I tried to use VitePress to build my blog, but I notice that `frontmatter.draft` is not supported.I don't think add support for `frontmatter.draft` is a good solution, because we can't directly know the post is draft or not.

I defined `$draft <post-title>.md` as my post file name, and noticed that I can overwrite the path generation but can't ignore the path generation for the specified file.

### Describe the solution you'd like

add `ignore` option for `config.ts` file, like:

```ts
{
  ignore: (path: string) => path === "<path-to-be-ignored>"
}
```

```ts
{
  ignore: (path: string) => /^\$draft */.test(path.split("/").at(-1))
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Use something like fast-glob + srcExclude property

**Comment by HerbertHe** [comment]
```ts
{
  srcExclude: ["posts/**/$draft*.md"]
}
```

**Comment by brc-dd** [comment]
Ah yeah, I forgot globs are supported with srcExclude too 😅

**Comment by HerbertHe** [comment]
Haha, I prefer RegExp~😂
