### ISSUE TITLE
The language is not loaded in syntax highlighting

### ISSUE THREAD

**Issue by pabloalmunia** [vuejs/vitepress#3259]
### Describe the bug

From version 1.0.0.0-rc.30 (includes 1.0.0.0-rc.31) custom language syntax highlighting aliases do not work.

### Reproduction

Into the config.js add:

```js
import { BUNDLED_LANGUAGES } from 'shiki';
const graphaneLanguageGrammar = JSON.parse(readFileSync("./src/.vitepress/shiki/graphane.tmLanguage.json"))
const html     = BUNDLED_LANGUAGES.find(lang => lang.id === 'html')
html.scopeName = 'source.graphane';
html.grammar   = graphaneLanguageGrammar;
html.aliases   = html.aliases || [];
html.aliases.push('svg');
```

### Expected behavior

Highlight the SVG as HTML and it is now displayed as TXT, and this warning is thrown in the console:

```txt
The language 'svg' is not loaded, falling back to 'txt' for syntax highlighting. 
```

### System Info

```Text
System:
    OS: Windows 11 10.0.22635
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 10.91 GB / 31.75 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.27.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.22)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.31 => 1.0.0-rc.31
```

### Additional context

Works perfectly on Vitepress 1.0.0-rc.29 and earlier.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We are no longer using shiki. With shikiji, you can configure aliases like this - https://github.com/vuejs/vitepress/pull/3237#issuecomment-1824818242
