### ISSUE TITLE
Why is there less underline in the side navigation bar

### ISSUE THREAD

**Issue by mxpup** [vuejs/vitepress#327]
**Describe the bug**
The title has multiple underlines, but the generated navigation bar has fewer underlines

**System Info**
- vitepress version: 0.14.0

**Comment by posva** [comment]
What does this even mean? Do you have a screenshot or something? 
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by mxpup** [comment]
![git](https://user-images.githubusercontent.com/25654465/123920832-f2769680-d9b8-11eb-9d87-66a7af9c7200.png)

**Comment by posva** [comment]
I can't understand... please use the forum or chat and come back with more information if this really is a bug
