### ISSUE TITLE
Support GitHub-style Alert?

### ISSUE THREAD

**Issue by antfu** [vuejs/vitepress#3278]
### Is your feature request related to a problem? Please describe.

GitHub introduced a syntax to have alerts: https://github.com/orgs/community/discussions/16925

Basically, it's:

```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
```

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.

### Describe the solution you'd like

I think it would be nice for VitePress to support that built-in. So markdown files authored that way can have a closer experience when reading on GitHub.

I wrote a markdown-it plugin for that: https://github.com/antfu/markdown-it-github-alerts that VitePress might be able to use directly. (and also a short intro and preview on my site: https://antfu.me/posts/github-alerts)

I guess we don't need to align exactly the same as GitHub's styling. We could just render our existing alerts.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Sounds good. I think we can add "Important" type on VP's Custom Container type, and use it. So this GitHub syntax would be like an alias for that.

Since I don't think GitHub style supports having custom title text, in the docs, perhaps this should be documented as alternative way of writing the custom container, and guide user to use the VP syntax when they want to customize the title 👀 `::: Tip Custom Title`

**Comment by kecrily** [comment]
Although I hate this syntax, I think it's a good idea. It allows md files using alert to be readable even when opened in GitHub without VitePress.
