### ISSUE TITLE
Custom Containers  Default Title details 可以默认展开吗

### ISSUE THREAD

**Issue by xuguojing-xgj** [vuejs/vitepress#3286]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/vuejs/vitepress/assets/79581129/60071e5c-d0a6-4d52-8522-53d83f3531c1)

### Describe the solution you'd like

我想打开页面的时候, details 内容默认展开,这个可以配置吗
![image](https://github.com/vuejs/vitepress/assets/79581129/0069f596-6ce2-4e1d-a5cf-014b329165f5)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
```md
:::details {open}

您的内容在这里

:::
```

**Comment by xuguojing-xgj** [comment]
谢谢, 我明白了
