### ISSUE TITLE
Markdown filenames ending in numbers don't seem to link correctly

### ISSUE THREAD

**Issue by arcqiufeng** [vuejs/vitepress#3289]
### Describe the bug

I have the markdown file name as: 02.2023_04_GB55030.md

I have the config like this:
```
        sidebar: {
            /////////////////////////////////////////////////////////////////////////////////////////
            '/Resource/': [
                {
                    text: '新规提示', collapsed: false,
                    items: [
                        { text: '日常提醒', link: '/Resource/000.新规提示/00.日常提醒' },
                        { text: '2023_03_GB55新规', link: '/Resource/000.新规提示/01.2023_03_GB55新规' },
                        { text: '2023_04_GB55030', link: '/Resource/000.新规提示/02.2023_04_GB55030' },
                        { text: '2023_06_GB55037', link: '/Resource/000.新规提示/03.2023_06_GB55037' },
                    ],
...

```
Works fine in dev mode.
However, the "02.2023_04_GB55030" link does not work in build mode. The link should end with `.html`, but it is missing and shows as 404.

If I change the code from
```
{ text: '2023_04_GB55030', link: '/Resource/000.新规提示/02.2023_04_GB55030' },
```
To
```
{ text: '2023_04_GB55030新规', link: '/Resource/000.新规提示/02.2023_04_GB55030新规' },
```
and rename the file `02.2023_04_GB55030.md` to `02.2023_04_GB55030新规.md`

Then the link will work fine, in both dev mode and build mode.

### Reproduction

as mentioned earlier

### Expected behavior

it should work in build mode.

### System Info

```Text
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 48.30 GB / 63.73 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.97), ChromiumDev (121.0.2248.1)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.51 => 1.0.0-rc.31
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
Can you share your project repository? Or minimally reproduce it on [StackBlitz](https://vitepress.new/).

**Comment by brc-dd** [comment]
Not reproducible - https://stackblitz.com/edit/vite-4getay
