### ISSUE TITLE
video 标签引入的资源无法播放

### ISSUE THREAD

**Issue by jaycethanks** [vuejs/vitepress#3296]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/44388103/7eb38136-e51b-4db8-a520-4ed9caf74da3)

看着就像是张图片一样， 无法点击播放

### Reproduction

-

### Expected behavior

能正常播放

### System Info

```Text
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 13.57 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.7.1 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: 1.0.0-rc.31 => 1.0.0-rc.31
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wChenonly** [comment]
Can you provide a minimum repo?

**Comment by Theo-messi** [comment]
```md
<video src="/video.mp4" controls="controls"></video>
```

Try adding `controls="controls"`

**Comment by jaycethanks** [comment]
> ```
> <video src="/video.mp4" controls="controls"></video>
> ```
> 
> Try adding `controls="controls"`

it works as expected, thanks a lot. : )
