### ISSUE TITLE
How to set auto-warp column in code blocks like docusaurus?

### ISSUE THREAD

**Issue by hxhac** [vuejs/vitepress#3307]
### Is your feature request related to a problem? Please describe.

Without auto-wrap, I have to drag horizontally to view the text in the code block, which is a pain in the ass!

### Describe the solution you'd like

...

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by you-hengh** [comment]
I have encountered the same problem. I hope that in code blocks, the code can automatically wrap lines instead of horizontal scrollbars. Is there any progress?

@brc-dd

**Comment by brc-dd** [comment]
Duplicate of #2660
