### ISSUE TITLE
Add loading="lazy" to <img> tag to support native lazy load feature of browser.

### ISSUE THREAD

**Issue by lemonicy** [vuejs/vitepress#3316]
### Is your feature request related to a problem? Please describe.

I can't find any solution to lazy load images. If I use markdown, vitepress will render the code to:
``` HTML
<img src="" alt="">
```
I think it's better to add loading="lazy" to <img> tag. This solution doesn't need any plugin.

### Describe the solution you'd like

Already said above.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by elringus** [comment]
Take into account lazy loading above-the-fold content is considered bad practice and will degrade performance: https://web.dev/articles/lcp-lazy-loading Some browsers will even log warnings when they detect such cases. If you're considering auto-applying lazy load on the md images, please add a way to opt out for specific images.

**Comment by zonemeen** [comment]
I add a custom configuration to achieve this feature in this [pr](https://github.com/vuejs/vitepress/pull/3346), in general, if a page has a lot of images, the img tag with loading="lazy" will bring a considerable performance improvement IMO.

**Comment by elringus** [comment]
It will, but also it will regress performance on pages where there is just one above the fold image. And it will also make browsers log warnings. The solution here would be either adding a way to mark each image as lazy or vice-versa (make all images lazy by default and add a way to mark an image as eager).
