### ISSUE TITLE
VitePress site not working with Github pages

### ISSUE THREAD

**Issue by GameboyTheDev** [vuejs/vitepress#3317]
### Describe the bug

Apparently when I published my site to github pages it appeared like this. I'm not sure what I did wrong. I followed the documentation with the deploy.yml etc.

![image](https://github.com/vuejs/vitepress/assets/110689336/041f609f-4f99-4671-82bc-a92a67a84959)

### Reproduction

I am not sure how you would reproduce this.

### Expected behavior

This is what my site is supposed to look like:

![image](https://github.com/vuejs/vitepress/assets/110689336/0153d15f-9ef3-4502-938e-98237c91b3f6)

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 5.87 GB / 15.73 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.31 => 1.0.0-rc.31
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wChenonly** [comment]
Can you provide a minimum repo? use [stackblitz.com/edit/vite-7vr5lz?file=docs%2Findex.md](https://stackblitz.com/edit/vite-7vr5lz?file=docs%2Findex.md)

**Comment by GameboyTheDev** [comment]
Sure, https://stackblitz.com/edit/vite-pi4por

**Comment by wChenonly** [comment]
> Sure, [stackblitz.com/edit/vite-pi4por](https://stackblitz.com/edit/vite-pi4por)

<img width="736" alt="image" src="https://github.com/vuejs/vitepress/assets/37658262/b292615e-aed1-49b1-b65f-f2770ba3b566">

Are you deployed under the subpath?

**Comment by GameboyTheDev** [comment]
Yes, this works tysm! Maybe I didn't understand the docs in the first place.

I have one more question, I'm trying to figure out which css property changes the color of these buttons when you hover over them with your mouse.
![image](https://github.com/vuejs/vitepress/assets/110689336/4141262b-da18-4f39-ba6f-905343cd3522)

Similar question, don't know which css property changes the color for these as well.
![image](https://github.com/vuejs/vitepress/assets/110689336/88571651-e803-4718-ad83-00c91fa65aef)
![image](https://github.com/vuejs/vitepress/assets/110689336/079d0361-2e05-4cd1-8cf5-af8aba5a3108)
![image](https://github.com/vuejs/vitepress/assets/110689336/505fac5f-4327-48ff-88ee-0a294885384a)

**Comment by wChenonly** [comment]
> Yes, this works tysm! Maybe I didn't understand the docs in the first place.
> 
> I have one more question, I'm trying to figure out which css property changes the color of these buttons when you hover over them with your mouse. ![image](https://private-user-images.githubusercontent.com/110689336/290005849-4141262b-da18-4f39-ba6f-905343cd3522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzIzNTksIm5iZiI6MTcwMjQzMjA1OSwicGF0aCI6Ii8xMTA2ODkzMzYvMjkwMDA1ODQ5LTQxNDEyNjJiLWRhMTgtNGYzOS1iYTZmLTkwNTM0M2NkMzUyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMTQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDFiOGNkMzQ2MWM1MzRkYTQwMzVlZjBlZTk5YWYxMjA4Y2Y4ZDRiYTUwYmUxMmRlOWY5Y2IzYWYyZjgxMDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A4RPRqmvj7iOWgfYffE35NUUl-jaGsQ9hTtHtijJidY)
> 
> Similar question, don't know which css property changes the color for these as well. ![image](https://private-user-images.githubusercontent.com/110689336/290006086-88571651-e803-4718-ad83-00c91fa65aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzIzNTksIm5iZiI6MTcwMjQzMjA1OSwicGF0aCI6Ii8xMTA2ODkzMzYvMjkwMDA2MDg2LTg4NTcxNjUxLWU4MDMtNDcxOC1hZDgzLTAwYzkxZmE2NWFlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMTQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTIzNGY5YzIwN2JhZmE3OTgzYjAxMTZkZmUxNWU1NWU0OGIzOGQzN2MxMTc4NzI4ODg2NmU1MDQxMWZlYzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qPfnpWoaRh1all0jjvSNbilNRLfBCUHs10NutPVHHhY) ![image](https://private-user-images.githubusercontent.com/110689336/290006247-079d0361-2e05-4cd1-8cf5-af8aba5a3108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzIzNTksIm5iZiI6MTcwMjQzMjA1OSwicGF0aCI6Ii8xMTA2ODkzMzYvMjkwMDA2MjQ3LTA3OWQwMzYxLTJlMDUtNGNkMS04Y2Y1LWFmOGFiYTVhMzEwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMTQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmNmN2M0MzQxOGEzZDcyMzdlYTIxMmQxMGJmMzE4ZTRkMmEzY2M4NmI0OTBhMGE1ZDNiMDdjNTQ3NDViYTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NSj2Y0dlgT8Y4DUkvjqJH-ZawkyzrcXgxWVgDzfQrKo) ![image](https://private-user-images.githubusercontent.com/110689336/290006286-505fac5f-4327-48ff-88ee-0a294885384a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzIzNTksIm5iZiI6MTcwMjQzMjA1OSwicGF0aCI6Ii8xMTA2ODkzMzYvMjkwMDA2Mjg2LTUwNWZhYzVmLTQzMjctNDhmZi04OGVlLTBhMjk0ODg1Mzg0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMTQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGZhY2VkNzFlMzIwYzNkODFiMmRhODczOGMzZDk0N2QxNjdkZTUwNDFhN2RiZjllNjQyYmJmOTNmZTRkMTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nkn7K08MG-8inXDkFFJnAdAtAo1Zq63LYVkKKXaTDgg)

<img width="403" alt="image" src="https://github.com/vuejs/vitepress/assets/37658262/069659d3-2050-4f87-bc3a-9ba0bf04de89">


This is the top VPNavBarMenu.

<img width="692" alt="image" src="https://github.com/vuejs/vitepress/assets/37658262/e88efa39-84b4-47fe-8163-353a16f0932f">


This is the side VPSidebarItem.

<img width="380" alt="image" src="https://github.com/vuejs/vitepress/assets/37658262/fb13c2cc-f898-432d-95e8-343c319ef735">


This is the bottom VPDocFooter

All colors are       --vp-c-brand-1: #3451b2

**Comment by GameboyTheDev** [comment]
This worked tysm! (Sorry about the late reply)
