### ISSUE TITLE
iframe source in public not being adjusted for base URL

### ISSUE THREAD

**Issue by hamishwillee** [vuejs/vitepress#3318]
### Describe the bug

According to https://vitepress.dev/guide/asset-handling#base-url , if files are in public you should not have to adjust for the base URL. However I have an iframe in public that only works if the base url is not set.

```html
<iframe src="/config/failsafe/index.html" frameborder="0" height="1400px" style="text-align: center; margin-left: -230px; margin-right: -230px;" width="1200"></iframe>
```

If the base url is set then I get an error asking me whether I meant the file in the base URL.

### Reproduction

I can create a cut down starter if needed. 

### Expected behavior

`/config/failsafe/index.html` above should be found irrespective of the base URL.

### System Info

```Text
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 17.59 GB / 31.83 GB
  Binaries:
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.25 => 1.0.0-rc.25
```

### Additional context

I tried adding this using an inline script. That "works" but the script appears to be reordered before the rest of the markdown, so I can't choose where to insert the element other than body, because any elements I add to markdown do not exist when this is run.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
```html
<iframe :src="withBase('/config/failsafe/index.html')" ... />

<script setup>
import { withBase } from 'vitepress'
</script>
```

**Comment by hamishwillee** [comment]
Thank you @brc-dd that works, and is much appreciated. It _may_ be that the docs need to be updated. I interpreted this documentation to mean that I would not have to update code to find the base. 

> All your static asset paths are automatically processed to adjust for different base config values. For example, if you have an absolute reference to an asset under public in your markdown:
>
> ```md
>  ![An image](/image-inside-public.png)
> ```
>
> You do not need to update it when you change the base config value in this case.

I didn't think this counted as "authoring a theme component that links to assets dynamically" since this was just markdown inclusion inside a page. So did not think the remaining instructions applied.
I also did not understand the `:` syntax, but I see it is vue magic.
