### ISSUE TITLE
Refresh some pages with error "Hydration completed but contains mismatches." when deployed on Aliyun OSS.

### ISSUE THREAD

**Issue by jaggerwang** [vuejs/vitepress#3322]
### Describe the bug

For example the page  https://blog.jaggerwang.net/basicai-annotation-specification/  cannot access directly, but it's ok when add `index.html` suffix, and other pages did not have this problem, such as https://blog.jaggerwang.net/basicai-technical-architecture/ . So it seems related to the content of page?

<img width="1512" alt="image" src="https://github.com/vuejs/vitepress/assets/1255011/3a69f282-d002-4194-b7ca-3b3075616883">

It's ok when running in local dev and preview mode, and there is no error showing in the  browser console or terminal console.

<img width="1512" alt="image" src="https://github.com/vuejs/vitepress/assets/1255011/82b87b50-f21a-430e-bb4e-893eb3bf9c52">

### Reproduction

Project structure:

<img width="1624" alt="image" src="https://github.com/vuejs/vitepress/assets/1255011/d3f2d9e0-5dc8-4344-9674-61433c5a8322">

Aliyun OSS config:

<img width="1306" alt="image" src="https://github.com/vuejs/vitepress/assets/1255011/d30acd18-d20c-44f2-a872-61bd981d0bcb">

Buid with GitHub actions, but the html is same with local build.

<img width="1624" alt="image" src="https://github.com/vuejs/vitepress/assets/1255011/f57bef3c-2d76-47c4-b18a-4b4a7b696771">

### Expected behavior

No error.

### System Info

```Text
Aliyun OSS
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jaggerwang** [comment]
And there is another problem, the return to top button always not show in mobile.

**Comment by zonemeen** [comment]
All the pages seem to work fine now.

**Comment by jaggerwang** [comment]
It seems related to browser cache, after disabled cache, the page became ok.

![image](https://github.com/vuejs/vitepress/assets/1255011/23b00dcd-760c-480e-bfd9-2fe3eef04057)
