### ISSUE TITLE
HMR seems to be a bit of an anomaly

### ISSUE THREAD

**Issue by popring** [vuejs/vitepress#333]
### Describe the bug

Start the service (npm run docs:dev),  modify Markdown, and view the results in real time, but there seems to be a problem after rendering, as shown in the video.

[video](https://youtu.be/3DDyb4uh3j0)

### Reproduction

1. npm run docs:dev
2. modify markdown
3. view results
4. HMR reload html
5. **The content is rendered repeatedly**

### Expected behavior

HMR updates the content normally

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 91.06 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.22.2 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/opt/node@12/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.1.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
@popring Thanks for the report. I can't reproduce this with the latest version. Can you create a repro project for this?

**Comment by popring** [comment]
> @popring Thanks for the report. I can't reproduce this with the latest version. Can you create a repro project for this?

repo is here: https://github.com/popring/vitepress-bugreport

**Comment by popring** [comment]
The new version seems to be woring fine. (v0.20.1). The question will be closed.
