### ISSUE TITLE
Dark mode display issue after setting the accent color

### ISSUE THREAD

**Issue by xincheng-1999** [vuejs/vitepress#3341]
### Describe the bug

I only configured the theme color configuration of normal mode as follows, but when I switched to dark mode, the theme color was still overwritten by the custom color. 
![image](https://github.com/vuejs/vitepress/assets/67899096/3a5c1620-f621-400d-9896-0dfa6df3ad0f)
![image](https://github.com/vuejs/vitepress/assets/67899096/5bcc6a61-152c-49e5-a91e-1d909c59be37)

### Reproduction

see Describe the bug

### Expected behavior

Isn't the color of dark mode undefined and shouldn't be used by default with vitepress

### System Info

```Text
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1
    Memory: 89.67 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.6.0 - ~/Library/pnpm/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.109
    Edge: 119.0.2151.46
    Safari: 17.2
  npmPackages:
    vitepress: 1.0.0-rc.31 => 1.0.0-rc.31
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by xincheng-1999** [comment]
> You may have to specify separated style for `.dark`, `:root` is for both light and dark unless you override the property for `.dark`
> 
> * https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/styles/vars.css

I tried adding these colors for `.dark`,but it's still not working. 
![image](https://github.com/vuejs/vitepress/assets/67899096/04f244f2-7d27-4bad-afad-89b832cdcaaf)

**Comment by brc-dd** [comment]
Why do you have a .module.css file?

**Comment by xincheng-1999** [comment]
> Why are you using a .module.css file? Try with normal .css and make sure you import it after vitepress/theme in theme entrypoint

My bad, just used normal CSS， Thanks very much
