### ISSUE TITLE
404 page navbar should follow language settings

### ISSUE THREAD

**Issue by quadratz** [vuejs/vitepress#3350]
### Is your feature request related to a problem? Please describe.

When a page is not found (404 error), the navbar content doesn't dynamically adapt to the selected language/locale despite the i18n setup.

Steps to Reproduce:
1. Set up VitePress with multiple languages.
2. Navigate to a non-existent page to trigger a 404 error.
3. Observe that the navbar content remains in English and doesn’t adjust based on the selected language/locale.

### Describe the solution you'd like

Ideally, the navbar content should follow the i18n configuration and display the appropriate language-specific content when encountering a 404 error.

### Expected:
![Expected](https://github.com/vuejs/vitepress/assets/74030149/017fca6c-5c78-4e71-8419-f0ee4c7eec70)

### Actual:
![Actual](https://github.com/vuejs/vitepress/assets/74030149/d16c80c9-f2ce-4763-aa33-1e0644ef3ade)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Aganivi** [comment]
You can load different configurations depending on the language.

**Comment by quadratz** [comment]
I assume you're referring to this config at https://vitepress.dev/guide/i18n? I've set up the configuration, but it only seems to work on regular pages, not on the 404 page.

**Comment by brc-dd** [comment]
How can one infer locale in a 404 page? Suppose user visits /foo, how to tell if the user wants the Chinese version there not the root version?

**Comment by quadratz** [comment]
> For /zh/not-existent we can probably do that, but for other routes where 404 will be served

It's quite similar to what Vitepress already does with the main content on the 404 page. The only thing is, we need to extend this functionality to cover not just the page content but also the navbar. For instance, if the URL reads /zh/not-exist, it should utilize the 'zh' config. Otherwise, it should fallback to the 'root' config or the primary language.

**Comment by NozomuIkuta** [comment]
This issue would be able to be tracked as a part of #3056.
