### ISSUE TITLE
loadEnv is not exported

### ISSUE THREAD

**Issue by bhogan-mitre** [vuejs/vitepress#3358]
### Describe the bug

The CMS example references a `loadEnv` method which does not seem to be exported properly.
https://vitepress.dev/guide/cms

```
// posts/[id].paths.js
import { loadEnv } from 'vitepress'

const env = loadEnv('', process.cwd())
```

<img width="787" alt="Screenshot 2023-12-19 at 9 45 30 AM" src="https://github.com/vuejs/vitepress/assets/32336739/61d5aeef-502c-4c3c-a01f-6453bdf8f123">

### Reproduction

`npm install --global vitepress`
`npx vitepress init`

Modify script in `api-examples.md` to use `loadEnv` and add to template.

```
<script setup>
import { useData, loadEnv } from 'vitepress'

const env = loadEnv('', process.cwd())

const { site, theme, page, frontmatter } = useData()
</script>

## Results

### Env Data
<pre>{{ env }}</pre>

### Theme Data
<pre>{{ theme }}</pre>
```

Launch dev site `npm run docs:dev`
Get build error:

<img width="787" alt="Screenshot 2023-12-19 at 9 45 30 AM" src="https://github.com/vuejs/vitepress/assets/32336739/61d5aeef-502c-4c3c-a01f-6453bdf8f123">

### Expected behavior

Environment variables populate `env` and display similar to `theme`.

### System Info

```Text
System:
    OS: macOS 13.6.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.26 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Brave Browser: 120.1.61.104
    Chrome: 120.0.6099.109
    Edge: 120.0.2210.77
    Safari: 17.2
```
```


### Additional context

I'm looking for the best way to do this type of environment handling in Vitepress and it's not obvious from the documentation.  
https://vitejs.dev/guide/env-and-mode

Thanks in advance for any help you could provide.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`loadEnv` can only be used in config or data / path loader files. You're trying to use that in client code where obviously browser can't read your local env.

**Comment by bhogan-mitre** [comment]
Okay, thank you.  Could you provide a basic example of how to do this?   How would step 2 in the CMS example get the result of `env` to use in preparing headers?  Does something get passed through from `config.ts`?  `enhanceApp`?  Thanks.

**Comment by brc-dd** [comment]
If you have set `VITE_APP_FOO=bar` in your .env file, you can use `import.meta.env.VITE_APP_FOO` in your client code. No additional config is needed for that.

**Comment by bhogan-mitre** [comment]
Great, thank you very much!  I appreciate the help.
