### ISSUE TITLE
Why does the html obtained in buildEnd contain &ZeroWidthSpace;

### ISSUE THREAD

**Issue by rxliuli** [vuejs/vitepress#3364]
### Describe the bug

I am trying to generate rss for the website added by vitepress, but I found that the html obtained by getting `ContentData['html']` in `buildEnd` contains `&ZeroWidthSpace;`. I want to confirm that this is a mistake or it can be designed. .

<img width="1724" alt="image" src="https://github.com/vuejs/vitepress/assets/24560368/df04b6d1-72b2-4404-977b-26e42fe0d8e6">

### Reproduction

https://stackblitz.com/edit/vitepress-rss-generate?file=docs%2F.vitepress%2Fconfig.ts&file=docs%2F.vitepress%2Fdist%2Findex.html

### Expected behavior

The html obtained in buildEnd does not contain &ZeroWidthSpace; the same as the final output html.

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: latest => 1.0.0-rc.32
```

### Additional context

I also confirmed that the RSS of vue’s official blog has this problem when displayed on inoreader and feedly.

<img width="742" alt="image" src="https://github.com/vuejs/vitepress/assets/24560368/3e512deb-8b08-4454-bdce-0eb564c7bd99">

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That's an HTML entity. Use some parser library to convert that to unicode sequences.

**Comment by rxliuli** [comment]
Of course I could have deleted them anyway, just wanted to make sure it was something viteprees expected or if it was a bug.

**Comment by brc-dd** [comment]
It's expected behavior. We need something there to pass a11y tests.

**Comment by rxliuli** [comment]
@brc-dd By the way, when generating rss, if it contains pictures, I also noticed that the links to the pictures in the html given by it at this stage are not finally rendered. Is there any solution?

**Comment by brc-dd** [comment]
Can you elaborate?

**Comment by rxliuli** [comment]
> Can you elaborate?

updated ⬆️

**Comment by brc-dd** [comment]
Ah weird. This should be the final link in buildEnd. I'll take a look.

**Comment by brc-dd** [comment]
Ah no, you're using createContentLoader. It doesn't return rendered HTML. You need to create a list and store data from transformHtml and save that list in buildEnd.

**Comment by rxliuli** [comment]
> Ah no, you're using createContentLoader. It doesn't return SSR'd HTML. You need to create a list and store data from transformHtml and generate the feed from that in buildEnd. It should be something like this - [#520 (comment)](https://github.com/vuejs/vitepress/issues/520#issuecomment-1566062351) (first argument of `transformHtml` 是渲染的 HTML）

Thank you, I solved it. In the end, I divided the html into those with pictures and without pictures. If there were pictures, I used node-html-parser to re-parse. Otherwise, I used the html in ContentData directly. (most do not come with pictures)

**Comment by brc-dd** [comment]
Yeah that could work too. Or if you can, try to store images in the public directory. That way their path won't change.

**Comment by rxliuli** [comment]
> Yeah that could work too. Or if you can, try to store images in the public directory. That way their path won't change.

Yes, I noticed that the vue official blog does this. But for my scenario, I need to execute multiple processes from local markdown source files, vitepress is just one of them (building the website), and I need the markdown file to be just a normal file reference.

**Comment by brc-dd** [comment]
Ah I don’t have access to the blog repo. Someone else will get back to you on that.
