### ISSUE TITLE
 Browser compatibility

### ISSUE THREAD

**Issue by huang-yf3160** [vuejs/vitepress#3369]
### Describe the bug

The page does not run properly on Chrome 75 version

### Reproduction

https://vitepress.dev/guide/getting-started

### Expected behavior

The page run properly on Chrome 75 version

### System Info

```Text
chrome 75
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Sorry, it's not supported - https://vitejs.dev/guide/build#browser-compatibility

**Comment by huang-yf3160** [comment]
> Sorry, it's not supported - https://vitejs.dev/guide/build#browser-compatibility

Is there a way to support it?

for example @vitejs/plugin-legacy

**Comment by brc-dd** [comment]
Plugin legacy doesn't work with vitepress. You can add polyfill.io via [head](https://vitepress.dev/reference/site-config#head), but it still won't work with Chrome < 61.
