### ISSUE TITLE
Supporting showing graphs and charts by Echarts or d3.js?

### ISSUE THREAD

**Issue by betterRunner** [vuejs/vitepress#337]
### Is your feature request related to a problem? Please describe.

I don't know how to place my Echarts code to vitepress.

### Describe the solution you'd like

It would be nice if vitepress could support showing charts and graphs from Echarts or d3.js. The tutorial seems not providing the guide to do so. Thank you!

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
This should exist as a plugin. 
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
