### ISSUE TITLE
assets Inline doesn't work?

### ISSUE THREAD

**Issue by Jeff-Tian** [vuejs/vitepress#3370]
### Describe the bug

Image wasn't inlined, see https://stackblitz.com/edit/vite-upxxuh?file=package.json,vite.config.ts:

<img width="1919" alt="image" src="https://github.com/vuejs/vitepress/assets/3367820/7ab7ef71-c29e-4a24-9f96-36d06441e7b9">

### Reproduction

see https://stackblitz.com/edit/vite-upxxuh?file=package.json,vite.config.ts:

<img width="1919" alt="image" src="https://github.com/vuejs/vitepress/assets/3367820/7ab7ef71-c29e-4a24-9f96-36d06441e7b9">

### Expected behavior

the image should be base64 inlined according to https://vitepress.dev/guide/asset-handling#referencing-static-assets

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: v1.0.0-beta.7 => 1.0.0-beta.7
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can keep it at `docs/vite.config.ts` too.

**Comment by brc-dd** [comment]
I don't think that's supported by vite, mainly because to keep dev HMR fast.
