### ISSUE TITLE
README.md as default folder page together with index.md

### ISSUE THREAD

**Issue by CanadianBeaver** [vuejs/vitepress#3371]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

It will be great if this feature be implemented, like it was implemented in old `vuepress` from the box. it is related to Github integration.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Specify this in your .vitepress/config.ts:

```ts
  rewrites: {
    '(.*)/README.md': '(.*)/index.md'
  },
```

**Comment by CanadianBeaver** [comment]
It does not work in root folder, not sure if this solution is good:

```
  rewrites: {
    'README.md': 'index.md',
    '(.*)/README.md': '(.*)/index.md'
  },
```

**Comment by brc-dd** [comment]
Ah yeah your version should work.
