### ISSUE TITLE
Temporary JS file randomly left un-deleted in .vitepress when user hit CTRL-C upon server start

### ISSUE THREAD

**Issue by zhangyx1998** [vuejs/vitepress#3382]
### Describe the bug

<img width="535" alt="image" src="https://github.com/vuejs/vitepress/assets/37485759/972f244c-66e1-467c-ac05-fe863590d0e2">

### Reproduction

This happened several times when I startup the dev server and hit CTRL-C very quickly. Most of the time I just notice the extra file and manually delete it.
But there was one time that I did not notice the tmp file, and mistakenly committed it.

### Expected behavior

Maybe consider using `cache/` to store bundled user config?

### System Info

```Text
Not relevant.
```

### Additional context

This seemed to be caused by [`loadConfigFromFile()`](https://github.com/vuejs/vitepress/blob/9568fea8fc50e625c8ef27c588eca3dbe5a44e81/src/node/config.ts#L175-L179). 

Since this is a Vite API, it seems like we should ask them to add an extra option to specify the output location of temporary config file.

([code to blame](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/config.ts#L1172-L1184))

Let me know if you would like to implement this change. If so, I can open a feature request to Vite.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I guess, for now, you can simply have `*.timestamp-*.mjs` there in `.gitignore`. I'm not sure if they will be accepting a change there as the module resolution might get messed up depending on the cache directory.

**Comment by zhangyx1998** [comment]
> I guess, for now, you can simply have `*.timestamp-*.mjs` there in `.gitignore`. I'm not sure if they will be accepting a change there as the module resolution might get messed up depending on the cache directory.

Nice catch. I'll investigate further before opening an issue on Vite repo.

**Comment by zhangyx1998** [comment]
Closing this issue because upstream is already tracking it at vitejs/vite#13267.
