### ISSUE TITLE
Uncaught (in promise) Error: vitepress data not properly injected in app

### ISSUE THREAD

**Issue by fxzer** [vuejs/vitepress#3389]
### Describe the bug

![CleanShot 2023-12-30 at 22 03 41@2x](https://github.com/vuejs/vitepress/assets/68853957/220db8d5-ea69-4a6a-adb7-18591efdbe96)

### Reproduction

   https://fxzer.gitee.io/shikiji/guide/load-lang

### Expected behavior

console no error

### System Info

```Text
Mac OS 14.2.0
@antfu/ni  v0.21.8
node       v18.18.2
agent      no lock file
npm -g     v9.8.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's fixed, will be there in next release.
