### ISSUE TITLE
Js is Invalid

### ISSUE THREAD

**Issue by xiaoshuaiyo** [vuejs/vitepress#3394]
### Describe the bug

After executing the packaging command, the index.html in the running dist folder found that all the js in the web page were invalid.
And there's a lot of errors on the page

### Reproduction

`npm run docs:build`

### Expected behavior

I hope it works correctly

### System Info

```Text
windows11 chrome
```

### Additional context

![90d2511219e2cb841faf92cf8f76148a](https://github.com/vuejs/vitepress/assets/139530289/cedfc913-30a0-4e00-8b32-c1eb23427218)

https://github.com/vuejs/vitepress/assets/139530289/d008c5da-ead0-4017-816f-5eea9d449026

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide a reproducible example in the form of a git repository or maybe using https://vitepress.new

**Comment by userquin** [comment]
You cannot open the html page in the browser directly, you need to serve the app via some static server, you can try running `npm run preview` (check if the script present in your package.json or add it):
```json
"scripts": {
  "preview": "vitepress preview"
}
```
