### ISSUE TITLE
small images are not integrated into the text 

### ISSUE THREAD

**Issue by CanadianBeaver** [vuejs/vitepress#3397]
### Describe the bug

The typical behaviour on GitHub or in vuepress is:

![image](https://github.com/vuejs/vitepress/assets/20358069/026c7c54-d303-4690-b75d-14aba1302271)

The behaviour in vitepress is different:

![image](https://github.com/vuejs/vitepress/assets/20358069/8de7609a-5df5-489e-8210-54b85f71a0b3)

### Reproduction

The source markdown:

```
Производство энергии на начальном этапе игры заключаются в строительстве достаточного количества бойлеров *![Boiler](../icons/boiler.png)* `Boiler`, паровых двигателей *![Steam engine](../icons/steam-engine.png)* `Steam engine` и снабжение их углём *![Coal](../icons/coal.png)* `Coal`, не забывая при этом про насосы *![Offshore pump](../icons/offshore-pump.png)* `Offshore pump` подающие воду *![Water](../icons/water.png)* `Water` в бойлеры из ближайших луж. По мере возможностей и без особого спеха производим солнечные панели *![Solar panel](../icons/solar-panel.png)* `Solar panel` и устанавливаем их в пустых участках разрастающейся базы. На аккумуляторы ![Accumulator](../icons/accumulator.png) `Accumulator` можно забить до поры до времени, когда ресурсов будет хватать на большее.
```

### Expected behavior

somethere, vitepress marked all images with css style like

```
display: block;
```

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 8.34 GB / 15.92 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    vitepress: ^1.0.0-rc.32 => 1.0.0-rc.34
```

### Additional context

Also, I found out that vitepress does not integrate small images as `<img src="data:image/png;base64,...`

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Feel free to adjust it using CSS - https://vitepress.dev/guide/extending-default-theme#customizing-css

> I found out that vitepress does not integrate small images as `<img src="data:image/png;base64,...`

It depends on your image size. But if they are less than 4kB they will be inlined in build.
