### ISSUE TITLE
目前更新到RC.35，文件后缀链接默认增加了.html后缀

### ISSUE THREAD

**Issue by jackloves111** [vuejs/vitepress#3408]
### Describe the bug

目前更新到RC.35，文件后缀链接默认增加了.html后缀

### 我在md文件中写：
```
[nginx.conf配置文件下载](/nginx/nginx.conf)
```
### `public`文件夹中也有这个文件
![7a8b15fc-8277-4441-81e2-ad03cda57cef](https://github.com/vuejs/vitepress/assets/89971817/f505f548-b500-4b16-8295-eb7f721998b1)
### 但当我点开链接，RC.34版本会下载这个文件，但是RC.35则是自动在链接后面增加了html后缀，导致无法正常下载文件。
![a90932a2-4b88-46a2-97f2-c09a318685dc](https://github.com/vuejs/vitepress/assets/89971817/e2a18003-fa08-4957-a473-14f1192a45be)

### Expected behavior

如上所述

### System Info

```Text
如上所述
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zhangyx1998** [comment]
You might find this helpful: [generating clean url](https://vitepress.dev/guide/routing#generating-clean-url). You can turn it off as instructed there.

In your case, maybe consider placing those `conf` files under `public` directory? [reference](https://vitepress.dev/guide/asset-handling#the-public-directory)

**Comment by jackloves111** [comment]
Thanks
