### ISSUE TITLE
Yeah, it's a bit of a pain in the butt to have to re-apply all the styles, especially since the styles are scoped. Causes a lot of duplication of code and makes it a very frustrating experience just to try and provide a consistent experience.

### ISSUE THREAD

**Issue by myzf** [vuejs/vitepress#3410]
Yeah, it's a bit of a pain in the butt to have to re-apply all the styles, especially since the styles are scoped. Causes a lot of duplication of code and makes it a very frustrating experience just to try and provide a consistent experience.

If someone wants to provide overrides for specific styles on the homepage, it might be a better idea to provide a class of some sort that they can use to override styles specifically on the homepage (like `.homepage` or something`).

But, ultimately, there's an enormous amount of work that has to go in to add anything other than the hero and features section to the homepage.

At minimum, there should at least be an option _added_ to enable the default styles to the lower half of the page.

Ultimately, the path forward should be:
- Added option to enable default styling to the homepage
- Add class `.homepage` for simple overrides

_Originally posted by @Swivelgames in https://github.com/vuejs/vitepress/issues/800#issuecomment-1780511582_
            

I use this way，but it is not work

**Comment by brc-dd** [comment]
Please comment on #800 itself instead of creating separate issues. I believe ATQQ already suggested some solution there.
