### ISSUE TITLE
exiting dev server with CTRL-C should not give exit code 1

### ISSUE THREAD

**Issue by zhangyx1998** [vuejs/vitepress#3418]
### Describe the bug

<img width="516" alt="image" src="https://github.com/vuejs/vitepress/assets/37485759/99f6e28a-ab8a-4edf-a074-87147dd31f9f">

Although provided a command `q` for exiting, there should be many users (including me) that are used to CTRL-C.

### Reproduction

Press CTRL-C under dev-server

### Expected behavior

Should exit normally, user command is not an error.

### System Info

```Text
N/A
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Press `q` to quit. CTRL + C should technically exit with status code 130 (SIGINT)

**Comment by zhangyx1998** [comment]
Closing as not planned
