### ISSUE TITLE
侧边栏配置

### ISSUE THREAD

**Issue by AZCodingAccount** [vuejs/vitepress#3422]
Hello VitePress Team,

I am encountering two issues with my VitePress project and seeking guidance.

1. **Sidebar Title Formatting Not Effective**: 
   I have been trying to customize the sidebar title formatting in my VitePress site, but it seems not to be working as expected. Despite using the recommended plugins, including `toc`, the sidebar either doesn't reflect the specified title formats or disappears completely. Attached is a screenshot of my current interface for reference:
   ![Interface Screenshot](https://github.com/vuejs/vitepress/assets/145426558/ea1ada20-4241-493e-983f-2c52b81294c9)

   Here is the code snippet I am using (I've ensured all necessary libraries are installed):
   ![Code Screenshot](https://github.com/vuejs/vitepress/assets/145426558/a95846b7-b203-40ca-bd63-fcc33fc532f9)

   Could you please clarify if there's anything I am missing or doing incorrectly? Any guidance on how to properly format the sidebar titles would be greatly appreciated.

2. **Navigation Placement on the Left**:
   I am trying to achieve a layout similar to VuePress where the navigation is on the left side. Although I have disabled the sidebar and set `aside: "left"`, the final layout seems to have excessive white space on the left. How should I configure it to get the desired layout? Here is a screenshot showing the current layout:
   ![Layout Screenshot](https://github.com/vuejs/vitepress/assets/145426558/78bed034-3a86-4a97-915c-36116a906fa7)

Thank you for your assistance. Looking forward to your suggestions and solutions.

**Comment by brc-dd** [comment]
`markdown.toc` is for `[[ toc ]]`. You need to set `themeConfig.outline` - https://vitepress.dev/reference/default-theme-config#outline

**Comment by AZCodingAccount** [comment]
Thank you. I've resolved the first issue. Regarding the second question, do you have any suggestions for displaying two columns instead of three?

**Comment by brc-dd** [comment]
It's actually perfectly centered:

<img width="1912" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/c4e3d00c-de26-45b5-9a7c-57af1c8c99e8">

If you want it to be left aligned, you can [add some css](https://vitepress.dev/guide/extending-default-theme#customizing-css) like this:

```css
.VPDoc .container {
  margin: 0;
}
```

Result:

<img width="1912" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/ef6f9410-a8bf-4d2b-a2c0-2d79e37d5b20">

**Comment by AZCodingAccount** [comment]
Ok，Thank you very much foy your answer。
