### ISSUE TITLE
Error in console with two locales and local search

### ISSUE THREAD

**Issue by altrusl** [vuejs/vitepress#3423]
### Describe the bug

An error appears in the browser console under the following conditions:

- The site contains two or more locales 
- `Search provier: local` is enabled
- There are pages that are present in one locale and absent from another

If `search provier: local` is disabled, there are no errors (and no search functionality of course)
The error sometimes (in dev mode) makes it impossible to further switch locales on the site.
Search works only in the `en` locale

Error text in production build:

```txt
framework.kynelX4h.js:1 Error: vitepress data not properly injected in app
    at Mc (framework.kynelX4h.js:1:83939)
    at Ta (theme._g5Wezsv.js:1:47657)
```

In dev mode: 

```js
runtime-core.esm-bundler.js:39 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core .
...
data.js?v=4f487e31:50 Uncaught (in promise) Error: vitepress data not properly injected in app
    at useData (data.js?v=4f487e31:50:15)
    at createTranslate (translation.js?v=4f487e31:6:29)

//  translations.js file   
import {useData} from "/@fs/S:/src/vue-faq/node_modules/.pnpm/vitepress@1.0.0-rc.32_@algolia+client-search@4.22.0_sass@1.69.7_search-insights@2.13.0_typescript@5.3.3/node_modules/vitepress/dist/client/theme-default/composables/data.js?v=4f487e31";
/**
 * @param themeObject Can be an object with `translations` and `locales` properties
 */
export function createTranslate(themeObject, defaultTranslations) {
    const {localeIndex} = useData();    // this line
```    

### Reproduction

The error can be seen on this website - https://vue-faq.org/en/misc/introduction.html
Just try to change the language

This is the source code of the website - https://github.com/vuesence/vue-faq/blob/search-error/docs/.vitepress/config/index.ts

### Expected behavior

Browser console should not contain any errors

### System Info

```Text
Chrome, vitepress 1.0.0-rc.32, Vite 3.4.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Use rc 34 or above.

**Comment by altrusl** [comment]
> Use rc 34 or above.

Thanks, it helped
