### ISSUE TITLE
Export `Badge` component for custom Theme

### ISSUE THREAD

**Issue by peterroe** [vuejs/vitepress#3430]
### Is your feature request related to a problem? Please describe.

I want to use `Badge` component in my custom theme. And the `Badge` component not exportd by `vitepress/theme`

So I can do this only:
```ts
import Theme from 'vitepress/theme'

export default {
	...Theme,
	enhanceApp(ctx) {
	 	Theme.enhanceApp(ctx)
		// Custom content
	}
}
```

### Describe the solution you'd like

So I' d like to import `Badge` from `vitepress/theme` directly

```ts
import { Badge } from 'vitepress/theme'

export default {
	...Theme,
	enhanceApp(ctx) {
	 	ctx.app.component('Badge', VPBadge);
		// Custom content
	}
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
PR is welcome. This needs to be edited - https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/without-fonts.ts
