### ISSUE TITLE
Dracula Theme is not visible properly

### ISSUE THREAD

**Issue by yagnikvamja** [vuejs/vitepress#3435]
### Describe the bug

The dracula theme is not visible properly while doing Syntax Highlighting.
![image](https://github.com/vuejs/vitepress/assets/118651250/436b42b0-d53c-4359-83cb-81963e3cf81a)

### Reproduction

https://stackblitz.com/edit/vite-vnywhq?file=docs%2F.vitepress%2Fconfig.ts,docs%2Findex.md,docs%2Fexample.md

### Expected behavior

Code snippet in example page should be in dracula (dark) theme.

### System Info

```Text
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 80.41 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.12.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.199
    Safari: 17.2.1
  npmPackages:
    vitepress: 1.0.0-rc.36 => 1.0.0-rc.36
```

### Additional context

N/A

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Zhengqbbb** [comment]
The `dracula` theme has only dark themes, so that:
1. Change to another theme in light mode
2. Set your site to dark only

<img width="759" alt="image" src="https://github.com/vuejs/vitepress/assets/40693636/868f952e-cfbc-4eb3-a1c2-94b89ba73c1a">

**Comment by yagnikvamja** [comment]
In my documention i want both the themes light and dark . And i want to set the theme `dracula` in both the modes.

**Comment by brc-dd** [comment]
> In my documention i want both the themes light and dark . And i want to set the theme dracula in both the modes.

You'll need to write a dracula light theme yourself then.

**Comment by jd-solanki** [comment]
@brc-dd He is trying to force dark theme in snippets even when light theme is activated in VitePress like Anu:
![image](https://github.com/vuejs/vitepress/assets/47495003/2bc1d6fd-09b2-4849-860d-5e38945b840e)

I guess this should be feature request instead of bug report.

**Comment by brc-dd** [comment]
Use this CSS - https://github.com/vuejs/vitepress/issues/3154#issuecomment-1784612839

**Comment by yagnikvamja** [comment]
Thanks for the comment @brc-dd .
It's working.

**Comment by jd-solanki** [comment]
It looks like according to everyone, VitePress should have option for forcing certain theme like previously we were doing.

Do you think we should consider this for feature req because everyone who want dark code snippet (even in light theme) they have to write custom CSS which was previously not the case?
