### ISSUE TITLE
If i use backticks (`) within a table in Markdown, it can cause issues with the rendering of the table.

### ISSUE THREAD

**Issue by Aurorxa** [vuejs/vitepress#3438]
### Describe the bug

If i use backticks (`) within a table in Markdown, it can cause issues with the rendering of the table.

![image](https://github.com/vuejs/vitepress/assets/25677587/aa3a5a14-c555-4b0a-9815-6d0374afcdd3)

My Real markdown is 

![image](https://github.com/vuejs/vitepress/assets/25677587/7411e9a3-bb49-4f8e-9053-66fb6fd9d446)

### Reproduction

[1.0.0-rc.36](https://github.com/vuejs/vitepress/compare/v1.0.0-rc.35...v1.0.0-rc.36) (2024-1-8)

### Expected behavior

Hopefully this issue will be resolved soon

### System Info

```Text
❯ npx envinfo --system --npmPackages vitepress --binaries --browsers
Need to install the following packages:
envinfo@7.11.0
Ok to proceed? (y)

  System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 60.85 GB / 95.92 GB
  Binaries:
    Node: 20.9.0 - ~\AppData\Local\Volta\tools\image\node\20.9.0\node.EXE
    npm: 10.2.5 - ~\AppData\Local\Volta\tools\image\npm\10.2.5\bin\npm.CMD
    pnpm: 8.10.5 - C:\Program Files\Volta\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.36 => 1.0.0-rc.36
```

### Additional context

no

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
You should write it like this:  \`\\|\\|`

**Comment by brc-dd** [comment]
Ah right. OP is using pipe. It needs to be escaped to work - https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables (see last point)

<img width="668" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/a20063a5-74ed-4d35-8dd6-080d5816407c">

**Comment by Aurorxa** [comment]
thanks
