### ISSUE TITLE
How to use markdown-it-regex plugin?

### ISSUE THREAD

**Issue by Peque** [vuejs/vitepress#3443]
### Is your feature request related to a problem? Please describe.

I'd like to be able to use https://github.com/tylingsoft/markdown-it-regex inside my Vitepress project. The goal is to add a regexp to replace MDI icons inside text.

### Describe the solution you'd like

I'd like to be able to use this plugin (or a solution to implement some kind of custom regexp replacement) by changing `.vitepress/config.ts`. However, I have been unable to do it.

Is there any way to work around this?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
1. That plugin is written for old versions of markdown it. You can call it like this:

```ts
import { defineConfig } from 'vitepress'
import markdownItRegex from 'markdown-it-regex'

export default defineConfig({
  markdown: {
    config(md) {
      markdownItRegex.default(md, {
        name: 'emoji',
        regex: /(:(?:heart|panda_face|car):)/,
        replace: (match) => {
          return `<i class="e1a-${match.slice(1, -1)}"></i>`
        }
      })
    }
  }
})
```

2. But this will conflict with the [markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji) plugin. You can get similar functionality by doing:

```ts
import { defineConfig } from 'vitepress'

export default defineConfig({
  markdown: {
    config(md) {
      md.renderer.rules.emoji = function (token, idx) {
        return `<i class="e1a-${token[idx].markup}"></i>`
      }
    }
  }
})
```

You might also need to adjust `markdown.emoji.defs` to include any additional icons which are not added by default - https://github.com/markdown-it/markdown-it-emoji/blob/master/lib/data/full.mjs

**Comment by Peque** [comment]
@brc-dd Thanks, that worked perfectly. :blush:
