### ISSUE TITLE
Crazy request Vpxxxx, setting the subject / index is invalid

### ISSUE THREAD

**Issue by 2439340964** [vuejs/vitepress#3448]
### Describe the bug

Set up the theme / index, and then delete, and then restore the theme / index, will be crazy request VPxxx, affect the project loading

### Reproduction

Set up the theme / index, and then delete, and then restore the theme / index, will be crazy request VPxxx, affect the project loading

### Expected behavior

Set up the theme / index, and then delete, and then restore the theme / index, will be crazy request VPxxx, affect the project loading

### System Info

```Text
System:
    OS: macOS 13.6.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 973.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.9.1 - ~/.nvm/versions/node/v18.9.1/bin/node
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.1/bin/npm
  Browsers:
    Chrome: 120.0.6099.216
    Edge: 120.0.2210.133
    Safari: 17.1
```

### Additional context

vitepress v31

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This is the expected behavior. Vite is just performing HMR. That's why all those components are being loaded. The HMR should not be slow. There might be some other factors affecting perf for you. Let's continue the discussion at #3447 itself.
