### ISSUE TITLE
Can we provide an option to completely op-out the vue related processing stuff?

### ISSUE THREAD

**Issue by wxsms** [vuejs/vitepress#3452]
### Is your feature request related to a problem? Please describe.

I have a lot of md files (10K+) that want to serve with vitepress, which contains something made vitepress unhappy (e.g. un closed tags, or `{{ xxx }}`), all I want to do is simply serve them as html pages, without any vue-parsing stuff, but vitepress keep complain about the those things while building. There're too many files for me to fix them one by one, it's nearly impossible.

### Describe the solution you'd like

provide an option to completely op-out the vue related processing stuff, just parse and display markdowns

### Describe alternatives you've considered

other alternatives are also welcome as long as it solved this kind of problem.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/brc-dd/vitepress-disable-vue/blob/main/.vitepress/config.ts

**Comment by wxsms** [comment]
Thank you, it works for `{{ }}` syntax, but `<xxx>`  are still reporting `un closed tags`, I have to also set `markdown.html` to `false` to avoid this.
