### ISSUE TITLE
Rename file that match parent folder name

### ISSUE THREAD

**Issue by satche** [vuejs/vitepress#3453]
### Is your feature request related to a problem? Please describe.

I don't know if there's an already existing solution, but I try to rename a file according to the parent's folder

### Describe the solution you'd like

Here is an example:
`/foo/bar/bar.md -> /foo/bar/index.md`

### Describe alternatives you've considered

I tried to create rewrite rules, something like that:
`":dir/:dir.md": ":dir/index.md"`

But it's not working

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
If you've `/foo/bar/bar.md` then do you want to serve it at `/foo/bar/` ? Or is it opposite? `/foo/bar/index.md` at `/foo/bar/bar` ?

**Comment by brc-dd** [comment]
You'll need some rewrite like this:

```ts
  rewrites: {
    '^(?<dir>.+?)\\/\\1\\.md': ':dir/index.md'
  }
```

I know it's ugly 😅

**Comment by satche** [comment]
That's exactly what I was looking for! As long it's working, I'm fine. Thank you very much 😄

**Comment by satche** [comment]
That's exactly what I was looking for! As long it's working, I'm fine. Thank you very much 😄

**Comment by brc-dd** [comment]
Bit more ugly, but this will work with nested folder too:

```ts
    '^(?<rest>.*(?=\\/))?\\/?(?<dir>.+?)\\/\\2\\.md$': ':rest*/:dir/index.md'
```

**Comment by satche** [comment]
Nice, thank you! It's working well in nested folder, but it somehow mess with next/prev nav links. Next page refers sometimes as the previous one. Any idea why ?
