### ISSUE TITLE
After initializing the project, an error occurs when opening the page

### ISSUE THREAD

**Issue by xxf5530** [vuejs/vitepress#3457]
### Describe the bug

I followed the documentation to start initializing the project, but the startup failed.

1. using `npx vitepress init`, and select `Default Theme (Out of the box, good-looking docs)`,
2. when I run `npm run docs:dev`, and goto `localhost:5173`, I got a vitepress error.

- [related docs: #setup-wizard](https://vitepress.dev/guide/getting-started#setup-wizard)

### Reproduction

[https://stackblitz.com/edit/vite-5hqysu?file=package.json](https://stackblitz.com/edit/vite-5hqysu?file=package.json)

### Expected behavior

Can start normally

### System Info

```Text
*
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
use rc.38
