### ISSUE TITLE
Site auto loads 404.html after deployed to Vercel

### ISSUE THREAD

**Issue by dinhhoangbaochan** [vuejs/vitepress#3460]
### Describe the bug

I installed Vitepress, built then ran it locally following the documentation of Vercel and everything seemed fine. But when I deployed it to my personal Vercel, my site keeps loading the 404.html. When I visit the Output of Vercel, I couldn't find any index.html and only 404.html. 

Here is currently [the blog of mine](https://vitepress-doc-kappa.vercel.app/) that I deployed to Vercel.

This is my current source on Vercel:
![image](https://github.com/vuejs/vitepress/assets/42535510/692cb237-e112-4424-9b26-b877a719ba13)

This is my current output on Vercel:
![image](https://github.com/vuejs/vitepress/assets/42535510/67b96827-9b46-45c8-967d-47d35d86c6eb)

### Reproduction

Not sure if this is the correct way to reproduce, but I'll list down the commands that I ran, from install command to deploy:

```bash
npm add -D vitepress
npx vitepress init ./
npm run docs:build
npm run docs:preview
vercel --prod
```

### Expected behavior

Page should load index.html when visiting `/`.

### System Info

```Text
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
    Memory: 2.27 GB / 7.96 GB
  Binaries:
    Node: 20.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (120.0.2210.133)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-rc.39 => 1.0.0-rc.39
```

### Additional context

I use a fresh setup of Vitepress and deploy to a Vercel setting using Node v20.x (which as mentioned on Vercel that is still in Beta). However I did try Node v18.x on Vercel and the error is the same. 

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Adjust the settings. You initialized vitepress at cwd instead of docs. You need to adjust vercel output directory and build commands accordingly:

```sh
? In which directory is your code located? ./
Local settings detected in vercel.json:
Auto-detected Project Settings (VitePress):
- Build Command: vitepress build docs
- Development Command: vitepress dev docs --port $PORT
- Install Command: `yarn install`, `pnpm install`, `npm install`, or `bun install`
- Output Directory: docs/.vitepress/dist
? Want to modify these settings? [y/N] y
? Which settings would you like to overwrite (select multiple)? Build Command, Development Command, Output Directory
? What's your Build Command? npm run docs:build
? What's your Development Command? npm run docs:dev --port $PORT
? What's your Output Directory? .vitepress/dist
```
