### ISSUE TITLE
Page with 600+ lines and lots of images doesn't load

### ISSUE THREAD

**Issue by Heus-Sueh** [vuejs/vitepress#3465]
### Describe the bug

page with 600+ lines and lots of images doesn't load. 
![image](https://github.com/vuejs/vitepress/assets/98482469/45637ee9-19b4-45f7-a96d-4531da4dad6c)

### Reproduction

acess the link: "Guia do Streaming Doméstico Automatizado - Sonarr, Radarr e Plex"

![image](https://github.com/vuejs/vitepress/assets/98482469/d8a5c7ba-c001-48a6-87b6-cf1ece1546d0)

through this link
https://pirataria.digital/pages/guias

### Expected behavior

the page loads normally

### System Info

```Text
System:
    OS: Linux 6.6 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 10.23 GB / 15.54 GB
    Container: Yes
    Shell: 5.9 - /usr/sbin/zsh
  Binaries:
    Node: 21.5.0 - /usr/sbin/node
    npm: 10.3.0 - /usr/sbin/npm
    pnpm: 8.14.1 - /usr/sbin/pnpm
```

### Additional context

you can temporarily solve the problem by pressing CTRL + F5, but if you go back to the previous page and try to access it again, it doesn't load the page

this is the .md file of the page
https://github.com/c-pirataria/megathread/blob/main/docs/pages/guias/sonarr-radarr-plex.md

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It has content like `{...}` outside the code elements. You'll need to disable markdown-it-attrs to render those properly:

```ts
// .vitepress/config.ts

export default defineConfig({
  markdown: {
    attrs: false
  }
})
```

**Comment by Heus-Sueh** [comment]
> It has content like `{...}` outside the code elements. You'll need to disable markdown-it-attrs to render those properly:
> 
> ```ts
> // .vitepress/config.ts
> 
> export default defineConfig({
>   markdown: {
>     attrs: false
>   }
> })
> ```

apparently it didn't solve it, I had to put it in code block to solve it

**Comment by brc-dd** [comment]
> apparently it didn't solve it, I had to put it in code block to solve it

You probably also have syntax like `{{...}}` then. Vue is likely trying to compile that. You might try the solution mentioned on #3452

**Comment by Heus-Sueh** [comment]
> > apparently it didn't solve it, I had to put it in code block to solve it
> 
> You probably also have syntax like `{{...}}` then. Vue is likely trying to compile that. You might try the solution mentioned on #3452 if you don't want to manually add stuff inside backticks.

Thanks for the help, I'll test this again when I have time
