### ISSUE TITLE
Customize target and rel attributes for `home` layout

### ISSUE THREAD

**Issue by wodeni** [vuejs/vitepress#3472]
### Is your feature request related to a problem? Please describe.

Now that `pathname` protocol has been removed (5836fac), the `home` layout cannot emulate the behavior by specifying target and rel attributes of actions. In my case, I had been using `pathname` to link to an SPA hosted together with the main site, and was able to use `target: "_blank"` for the nav bar, but not the home page action (PR: https://github.com/penrose/penrose/pull/1704). 

### Describe the solution you'd like

Just like the nav bar in `config.ts`, the `actions` of `home` layout exposes `target` and `rel`. 

### Describe alternatives you've considered

* Not using the default theme `home` layout but I'd love to keep using the default theme!
* Bring back `pathname`, which is unlikely
* Turn off `cleanUrl`, but this will impact the entire site, which is not desirable.

### Additional context

Related issue on sidebar links:  https://github.com/vuejs/vitepress/issues/2851

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by liana-p** [comment]
Implementing this, will open a PR for it soon
