### ISSUE TITLE
Shorter variable name $frontmatter

### ISSUE THREAD

**Issue by Alexufo** [vuejs/vitepress#3476]
### Is your feature request related to a problem? Please describe.

$frontmatter is not long for use inside text strings

Name is: {{$frontmatter.prefix}}_mode

### Describe the solution you'd like

$frontmatter can become as $f

Name is: {{$f.prefix}}_mode

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
```ts
// .vitepress/theme/index.ts

import { Theme } from 'vitepress'
import DefaultTheme from 'vitepress/theme'

export default {
  extends: DefaultTheme,
  enhanceApp({ app, router }) {
    Object.defineProperty(app.config.globalProperties, '$f', {
      get() {
        return router.route.data.frontmatter
      }
    })
  }
} satisfies Theme
```
