### ISSUE TITLE
希望能在添加弹窗增加一个截图当前网站作为图标的功能

### ISSUE THREAD

**Issue by haitaibanfan** [vuejs/vitepress#3477]
### Is your feature request related to a problem? Please describe.

很多网站没有自己的图标，只用文字图标辨识度又比较低

### Describe the solution you'd like

在添加页面的时候能选择截图当前的网站直接作为图标背景，在大图标的模式下就能很直观的知道当前的网站是什么样子

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by haitaibanfan** [comment]
可以参考Speed dial 2 新标签这个扩展的实现效果，不过这个扩展的功能性比itab要差很多

**Comment by brc-dd** [comment]
Wrong repo.
