### ISSUE TITLE
Using vue to report errors in markdown

### ISSUE THREAD

**Issue by you-hengh** [vuejs/vitepress#3485]
### Describe the bug

I want to use the vue component in vitepress. I have read the documentation on the official website, but when I do it, I encounter an error like this.
```bash
[plugin:vite:vue] Tags with side effect (<script> and <style>) are ignored in client component templates.
```

I don't understand what I'm encountering, I just want to achieve the effect here in this vue document

> https://cn.vuejs.org/guide/reusability/composables.html#vs-react-hooks

![PixPin_2024-01-21_16-20-49](https://github.com/vuejs/vitepress/assets/34816426/9cfc1f56-491a-4182-9eb5-177da0565de1)

### Reproduction

https://stackblitz.com/edit/vite-dn63jg?file=docs%2Fhooks%2FuseMouse.js,docs%2Fexample.md

### Expected behavior

The documentation on the official website makes me understand the difficulty or the need for a better demo?

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) CoreT i7-13800H
    Memory: 17.07 GB / 31.74 GB
  Binaries:
    Node: 20.11.0 - ~\AppData\Local\pnpm\node.EXE
    npm: 10.2.4 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.14.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-rc.39 => 1.0.0-rc.39
```

### Additional context

Please tell me the correct way to write it, thank you

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Your import is wrong. See this example - https://stackblitz.com/edit/vite-b6ybfn?file=docs%2Fhooks%2FuseMouse.js,docs%2Fexample.md

**Comment by you-hengh** [comment]
> Your import is wrong. See this example - https://stackblitz.com/edit/vite-b6ybfn?file=docs%2Fhooks%2FuseMouse.js,docs%2Fexample.md
https://stackblitz.com/edit/vite-b6yb​​fn?file=docs%2Fhooks%2FuseMouse.js,docs%2Fexample.md

The online documentation is just a simple demo, and actually the article I'm importing is so far down the file hierarchy that I need to write something like that.
```js
import xxx from "../../../../hooks/useMouse.js"
```

I want to use the @ symbol instead as in the vue project.
```js
import xxx from "@/hooks/useMouse.js"
```
I tried to configure vite in `.vitepress / config.ts`, but it didn't seem to work.
```js
import { fileURLToPath, URL } from 'node:url'

export default defineConfig({
  lang: 'en-US',
  title: 'VitePress',
  description: 'Vite & Vue powered static site generator.',
  vite: {
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./docs', import.meta.url)),
      },
    },
  }
})
```

I tried to use @ / hooks/useMouse.js in the file, but the error was as follows:
```bash

[plugin:vite:import-analysis] Failed to resolve import "@/hooks/useMouse.js" from "docs\article\note\vue\vue3\路由.md". Does the file exist?
D:/Coding/web/myblog_vitepress/docs/article/note/vue/vue3/路由.md:5:27
1  |  import { useMouse } from '@/hooks/useMouse.js'
   |               
```

May I ask how to configure @ to take effect? Hooks is a subfolder of docs

**Comment by brc-dd** [comment]
Your alias appears to be wrong. If your files are like this:

```
- docs/
    - .vitepress/config.ts
    - hooks/useMouse.js
```

the alias should be `fileURLToPath(new URL('../', import.meta.url))`

**Comment by you-hengh** [comment]
> Your alias appears to be wrong. If your files are like this:您的别名似乎有误。如果你的文件是这样的：
> 
> ```
> - docs/
>     - .vitepress/
>         - config.ts
>     - hooks/
>         - useMouse.js
> ```
> 
> the alias should be `fileURLToPath(new URL('..', import.meta.url))`别名应该是 `fileURLToPath(new URL('..', import.meta.url))`

Oh my God, you are my God!!!
