### ISSUE TITLE
1.0.0-rc.39 dev报错Uncaught SyntaxError: The requested module '/@fs/Users/.../node_modules/vitepress/dist/client/index.js?v=8517777d' does not provide an export named 'getScrollOffset' (at outline.js?v=8517777d:1:10)

### ISSUE THREAD

**Issue by shiheme** [vuejs/vitepress#3486]
### Describe the bug

1.0.0-rc.39 dev报错Uncaught SyntaxError: The requested module '/@fs/Users/.../node_modules/vitepress/dist/client/index.js?v=8517777d' does not provide an export named 'getScrollOffset' (at outline.js?v=8517777d:1:10)

1.0.0-rc.36没问题，1.0.0-rc.39 dev时会出现这个错误
<img width="1507" alt="image" src="https://github.com/vuejs/vitepress/assets/5304020/75126808-f96b-4568-b9f0-091cd1a28b89">

### Reproduction

不清楚是什么问题。升级1.0.0-rc.39后vitepress dev docs 就报错，还原到1.0.0-rc.36 就没问题了

### Expected behavior

解决这个报错。正确的页面 应该是这样的
<img width="1511" alt="image" src="https://github.com/vuejs/vitepress/assets/5304020/cd194c50-abce-4a40-9882-bb08c6c1d0dc">

### System Info

```Text
mac/google chrome 

https://github.com/shiheme/appbeebee
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Try removing your node_modules and lock file and re running `yarn install`

**Comment by shiheme** [comment]
> Try removing your node_modules and lock file and re running `yarn install`

可以了，谢谢

**Comment by brc-dd** [comment]
Closing this. Comment here if issue persist. I tried locally, it seems to work fine.
