### ISSUE TITLE
vitepress build x6 error

### ISSUE THREAD

**Issue by bhabgs** [vuejs/vitepress#349]
### Describe the bug

在 vitepress 文档环境中 引用x6 组件，会提示navigate不存在。

### Reproduction

``` bash
yarn build:docs
```

### Expected behavior

希望能够正常引入 x6, 或者提供一个 使用x6的最佳实践

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 891.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1.1
module
     "vite": "^2.4.4",
    "vitepress": "^0.15.6",
```

### Additional context

![image](https://user-images.githubusercontent.com/19221378/128308123-3b5a9649-2288-49a8-9f55-87c745277e2c.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
the error comes from @antv/x6 not from vitepress

**Comment by bhabgs** [comment]
这个问题是X6 内部文件报告的，但是我想问下vitepress 有没有相关问题的处理方式？
