### ISSUE TITLE
exclude folders from building and from local search

### ISSUE THREAD

**Issue by pberto** [vuejs/vitepress#3495]
### Is your feature request related to a problem? Please describe.

I'd like to be able to exclude entire folders via srcExclude, so far I can only exclude files.

Likewise I'd like to exclude folders from local search (mini search).

### Describe the solution you'd like

I tried using srcExclude but only supports blob for file names.
I read mini search docs and seems also you can exclude from search only files.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`foo/**/*` is a valid glob that matches all files in the directory `foo`

**Comment by pberto** [comment]
Ok thanks, I think the docs should be more clear that also folders can be excluded as the impression is that you have to pass a filename:

https://vitepress.dev/reference/site-config#srcexclude

**Comment by pberto** [comment]
BTW it is strange because when I do a `npm run docs:build` for the excluded folders I received all the messages of broken links in this pages. Trying to track the reason.
