### ISSUE TITLE
Dockerfile snippet not highlighted

### ISSUE THREAD

**Issue by OrbisK** [vuejs/vitepress#3499]
### Describe the bug

Including a Dockerfile snippet into md does not apply highlighting

### Reproduction

https://stackblitz.com/edit/vite-jrvx6i?file=docs%2FDockerfile,docs%2Fexample.md

### Expected behavior

snippet dockerfile should render propperly

### System Info

```Text
System:
    OS: Linux 5.10 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 29.01 GB / 31.25 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v17.4.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
    pnpm: 8.7.6 - ~/.local/share/pnpm/pnpm
    bun: 1.0.2 - ~/.local/share/pnpm/bun
  npmPackages:
    vitepress: 1.0.0-rc.40 => 1.0.0-rc.40
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I'm not sure though why it's adding extra lines though. I'll fix that.
