### ISSUE TITLE
本地搜索对中文不是很友好

### ISSUE THREAD

**Issue by shiheme** [vuejs/vitepress#3507]
### Describe the bug

使用本地搜索，搜索段落中间的中文无法显示结果，如果是英文没有这个问题。如果搜索的中文是段落前面几个字或者挨着标点符号的中文才显示结果
<img width="851" alt="image" src="https://github.com/vuejs/vitepress/assets/5304020/d0173cac-b32f-40e8-99f8-546d7d24a21a">
<img width="1041" alt="image" src="https://github.com/vuejs/vitepress/assets/5304020/cd28bd06-5531-4eed-97f0-a851093c9391">

### Reproduction

可以在我的博客https://www.appbeebee.com/尝试搜索段落中间的中文和段落前的中文进行比较

### Expected behavior

希望本地搜索能进行全文中文搜索，而不是仅仅搜索段落前的中文

### System Info

```Text
mac google chrome
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Those things appear to being added dynamically. Local search can only index your markdown content. Use something like vitepress-plugin-pagefind instead. (PS: that too might not work because your SSR seems to be completely broken.)
