### ISSUE TITLE
Bug: GitHub-flavored alerts cannot be nested (with errors)

### ISSUE THREAD

**Issue by shigma** [vuejs/vitepress#3512]
### Describe the bug

- Blockquotes can be nested.
- Custom blocks can be nested.
- But GitHub-flavored alerts cannot (with errors).

```md
> case 1
>
> > nested content

:::: tip
case 2

::: warning
nest content
:::
::::

> [!TIP]
> case 3
>
> > [!WARNING]
> > case 3
```

![image](https://github.com/vuejs/vitepress/assets/33423008/df0e6ed4-1ce3-4920-87e7-5b79e3578d6f)

![image](https://github.com/vuejs/vitepress/assets/33423008/81cb6243-d168-42d4-bb15-cddabfb89107)

### Reproduction

https://stackblitz.com/edit/vite-alzhrt?file=docs%2Fexample.md

### Expected behavior

Render without errors.

### System Info

```Text
N/A
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This isn't supported on GitHub either. We can avoid throwing error and just render blockquote though.

**Comment by shigma** [comment]
I'm willing to have a try if you can accept this feature.

**Comment by meduzen** [comment]
FYI, and as GitHub doesn’t do it autimatically, I’ve referenced this issue in discussion #3540.
