### ISSUE TITLE
Next / Prev links with internationalization

### ISSUE THREAD

**Issue by raul-izquierdo** [vuejs/vitepress#3527]
### Describe the bug

Next / Prev links are not generated

### Reproduction

1. Open [this stackblitz link](https://stackblitz.com/edit/vite-ek6zn1?file=docs%2F.vitepress%2Fconfig.ts).
2. Press "Get Started" button in the preview panel to go to Page A.
3. The "Next Page" link is pointing to the same page. Instead, it should be a link to page b. 
4. Go to page b using the side bar. There should be a link to page A as "Previous page" (not "Next Page").

The problem also happens in the spanish version of the site.

### Expected behavior

- On "Page A", there should be a link to "Next -> Page B"
- On "Page B", there should be a link to "Previous -> Page A"

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
    Memory: 1.28 GB / 7.96 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 121.0.6167.86
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.19041.3636
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Your URLs are wrong. Make them:

```ts
              { text: 'English page A', link: '/en/page_a' },
              { text: 'English page B', link: '/en/page_b' },

...

              { text: 'Spanish page A', link: '/es/page_a' },
              { text: 'Spanish page B', link: '/es/page_b' },
```

**Comment by raul-izquierdo** [comment]
Thank you so much. It works now.
