### ISSUE TITLE
Translate path in language selector, e.g. navigate from welcome.html to de/willkommen.html

### ISSUE THREAD

**Issue by polenter** [vuejs/vitepress#3532]
### Is your feature request related to a problem? Please describe.

**SEO**
Fot better SEO, it would be nice to provide a translated target path in the language selector, i.e. from `welcome.html` to `de/willkommen.html`.

**404 Not found**
Is there no translated version of a page, e.g. no `de/welcome.html`, a 404 not found is returned.

### Describe the solution you'd like

**Define target page in frontmatter**
Additional section in frontmatter of each page, providing the target page, e.g.:
```
---
title: Welcome
locales: {
    de: {
        link: "/de/willkommen/"
    },
    fr: {
        link: "/fr/bienvenue/"
    }
}
---
```

**Fallback against 404 errors**
Is a page not defined, language selector should target the root of a particular language.

There was already a [discussion](https://github.com/vuejs/vitepress/discussions/2857) concerning this problem.
I've implemented this feature locally, and I could provide a PR.
It would bring better SEO and UX. 
What do you think about it?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I believe fixing #3530 would fix this. Users can then supply their own functions via themeConfig.
