### ISSUE TITLE
Dead link check for hash url

### ISSUE THREAD

**Issue by ydcjeff** [vuejs/vitepress#354]
### Is your feature request related to a problem? Please describe.

VitePress has the ability to check dead links (without hash) like `./frontmatter.html`.

Since the dead hash url can still go to the existing page but not to the hash location, it would be great if VitePress can also check the hash url like `./frontmatter.html#head`.

### Describe the solution you'd like

I am not familiar with the code base, so no solution I can think of.

### Describe alternatives you've considered

Maybe a VitePress plugin like [`vuepress-plugin-check-md`](https://github.com/ulivz/vuepress-plugin-check-md)?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Let's track it at #646. Thanks.
