### ISSUE TITLE
[vitepress] 1 dead link(s) found.

### ISSUE THREAD

**Issue by afl-lxw** [vuejs/vitepress#3541]
### Describe the bug

vitepress v1.0.0-rc.41
--
18:10:03.153 |  
18:10:03.204 | - building client + server bundles...
18:10:04.206 |  
18:10:04.206 | The language 'git' is not loaded, falling back to 'txt' for syntax highlighting.
18:10:04.207 |  
18:10:04.207 | The language 'git' is not loaded, falling back to 'txt' for syntax highlighting.
18:10:20.793 |  
18:10:20.794 |  
18:10:20.794 | (!) Found dead link ./assets/Vue.js-devtools_v3.1.6.crx in file web/vue/vue-router/3-devTools.md
18:10:20.794 |  
18:10:20.794 | If this is expected, you can disable this check via config. Refer: https://vitepress.dev/reference/site-config#ignoredeadlinks
18:10:20.794 |  
18:10:20.795 | [vitepress] 1 dead link(s) found.
18:10:20.795 | ✖ building client + server bundles...
18:10:20.803 | build error:
18:10:20.804 | Error: 1 dead link(s) found.

<img width="1341" alt="image" src="https://github.com/vuejs/vitepress/assets/56349292/19734b5b-3ede-426d-a62e-c06967ed9f03">

### Reproduction

There is no problem with packaging in the local environment

Production environment packaging prompt error

node -  20.10.0
vitepress": "^1.0.0-rc.41"

### Expected behavior

build success

### System Info

```Text
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1
    Memory: 52.17 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
crx is not recognized. add this line to top of your config file:

```ts
process.env.VITE_EXTRA_EXTENSIONS = 'crx'
```

**Comment by afl-lxw** [comment]
> crx is not recognized. add this line to top of your config file:
> 
> ```ts
> process.env.VITE_EXTRA_EXTENSIONS = 'crx'
> ```

Thank you for being my angel
