### ISSUE TITLE
"<! -- @ content -->" is not available in the Rendering Raw Content

### ISSUE THREAD

**Issue by tomiaa12** [vuejs/vitepress#3543]
### Describe the bug

```js
export default {
    paths() {
      return [
        {
          params: {
            title: "test1",
            content: `tttt
            yyyy
            qqq`,

          },
        },
      ]
    },
  }
```

```md
# {{ $params.title }}

11111  content ↓↓↓

<!-- @content -->


2222 content ↑↑↑

```

### Reproduction

https://stackblitz.com/~/edit/vite-sqe6dh?file=docs%2Findex.md

### Expected behavior

Content displayed normally

### System Info

```Text
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 7.25 GB / 15.64 GB
  Binaries:
    Node: 21.6.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.98)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-rc.41 => 1.0.0-rc.41
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
content should be outside params:

```ts
params: {
  title: '...'
},
content: '...'
```
