### ISSUE TITLE
import not found: defineEmit

### ISSUE THREAD

**Issue by ebxn** [vuejs/vitepress#355]
### Describe the bug

Upon following the starter instructions in the [docs](https://vitepress.vuejs.org/guide/getting-started.html), running `yarn docs:dev` yields a blank webpage at `localhost:3000` with the error shown below in the console.

![image](https://user-images.githubusercontent.com/32674127/128770771-122737b5-b4f3-4489-9a12-72fb36d48c28.png)

### Reproduction

Following the instructions outlined on the Getting Started page on [vitepress.vuejs.org](https://vitepress.vuejs.org/guide/getting-started.html).

### Expected behavior

"Hello Vitepress" should be rendered to the screen with no error messages in the console.

### System Info

```shell
System:
    OS: Linux 5.13 Fedora 34 (Workstation Edition) 34 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 2.30 GB / 15.28 GB
    Container: Yes
    Shell: 5.1.0 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.20.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ebxn** [comment]
Hahaha I think you literally fixed this issue as I was typing it and hitting submit. What are the chances??

**Comment by posva** [comment]
Yeah, this has already been fixed. For the moment use Vue 3.1 with Vite

**Comment by bhabgs** [comment]
vue 最新版本为 3.2.1， 提示没有默认导出 defineEmit， 预计vitepress什么时间能过支持

**Comment by bhabgs** [comment]
我是在 .vite 里这么改的，反正再是能用了。。 为啥改名字了，现在应该是vite修改么？
``` js
const defineEmit = defineEmits;
export {
  defineEmit,
  defineEmits,
  ...
}
```

![image](https://user-images.githubusercontent.com/19221378/128804454-8f54c5c0-873f-42f2-996c-1fd5d8327cf7.png)

**Comment by airene** [comment]
我也遇到了这个问题！
解决办法显示指定 vue和相关的文件版本先回到3.1.x 
`npm i -D vue@3.1.5 @vue/compiler-sfc@3.1.5 @vue/server-renderer@3.1.5` 
应该是等vitepress有新的release有可以了吧

@bhabgs 不改源码等升级是不是优雅一点

**Comment by bhabgs** [comment]
降级到3.1.5 好像没有解决我的问题，.
![image](https://user-images.githubusercontent.com/19221378/128813203-ea9d2184-e28d-4d73-8c14-9c4c43f78c58.png)
![image](https://user-images.githubusercontent.com/19221378/128813237-7b7ddb0b-e1b3-4194-9e29-c9aedc24e2da.png)

**Comment by QiYoe** [comment]
Modifying the local source code does solve the problem of local startup, but online deployment does not

**Comment by airene** [comment]
@QiYoe @bhabgs 删除node_modules 强制安装指定版本, 不要带^ 而且确保 yarn 或者npm lock 文件中的版本是3.1.5 再上travis就没问题了，我也有travis编译，就是这样整的。 最好的办法就是等发一个vitepress 0.15.7就啥问题都没有了

**Comment by fz6m** [comment]
强指定

`vue@3.1.5 @vue/compiler-sfc@3.1.5 @vue/server-renderer@3.1.5` 会有 `_ctx.$withBase` 问题。 

改为强指定 vitepress 解决了，

```json
  "vitepress": "0.14.1"
```

这个版本的 vitepress 依赖了 3.1.5 系列的 vue
