### ISSUE TITLE
SyntaxError: The requested module 'shiki' does not provide an export named 'isPlaintext'

### ISSUE THREAD

**Issue by lemonfog** [vuejs/vitepress#3551]
### Describe the bug

.

### Reproduction

.

### Expected behavior

.

### System Info

```Text
.
```

### Additional context

![Snipaste_2024-02-06_20-33-00](https://github.com/vuejs/vitepress/assets/54741465/6f5c2430-03da-4398-9c43-5e49f2c09d2f)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
fixed by #3550
