### ISSUE TITLE
SyntaxError: The requested module 'shiki' does not provide an export named 'isPlaintext'

### ISSUE THREAD

**Issue by shoebham** [vuejs/vitepress#3552]
### Describe the bug

Getting 
SyntaxError: The requested module 'shiki' does not provide an export named 'isPlaintext'
when running npx vitepress init 
    
<img width="730" alt="image" src="https://github.com/vuejs/vitepress/assets/25881429/1ece1ea3-815d-45f1-8ce3-c4f57f3f7ec8">

### Reproduction

Follow the steps mentioned here: https://vitepress.dev/guide/getting-started

install vitepress
1. npm add -D vitepress
Start the wizard
2. npx vitepress init

### Expected behavior

Succesful init of vitepress

### System Info

```Text
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 79.88 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.6.1 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.2.1
  npmPackages:
    vitepress: ^1.0.0-rc.41 => 1.0.0-rc.41
```

### Additional context

I saw that it was fixed here https://github.com/vuejs/vitepress/pull/3550 some hours ago, but still i am getting this error

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> but still i am getting this error

because it's not released. wait for next version

**Comment by brc-dd** [comment]
released
