### ISSUE TITLE
`DocFooter` doesn't work well with dynamic `Sidebar` array.

### ISSUE THREAD

**Issue by penyoofficial** [vuejs/vitepress#3554]
### Describe the bug

I created a large documentation set using VitePress, so the directory is quite long. Initially, I separated the directory array (also known as the Sidebar array) into a separate TS file, which worked fine. However, **when I expressed it in YAML format, the DocFooter stopped working properly**; it always makes the 'next' link point to the first markdown or simply doesn't show anything.

![yaml file](https://github.com/vuejs/vitepress/assets/93194508/2cd6da60-9ae8-48ce-b5dd-7c7fa514c6ff)

![catalog adapter](https://github.com/vuejs/vitepress/assets/93194508/60cf9ba6-29ba-484d-882c-a5cf8be6718c)

![connector](https://github.com/vuejs/vitepress/assets/93194508/76f62066-8687-4f52-851c-202dd57b25cd)

### Reproduction

As described above.

### Expected behavior

Regardless of whether the directory is hardcoded or dynamically read, it should behave the same as when hardcoded.

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 17.87 GB / 31.80 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.10 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.98)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.42 => 1.0.0-rc.42
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
First, this isn’t really dynamic - config is evaluated beforehand and how you insert data in your config doesn’t matter. Second, the issue in your case is your YAML is not same as what you had in your TS file. Try logging the value of catalog in both cases and compare them. Also we need a minimal reproducible example to help you further (the reproduction section in issue template is meant to be filled with a link to some project created with https://vitepress.new or a repo containing trimmed down code that others can easily run on their systems to reproduce your issue)

**Comment by brc-dd** [comment]
Like I said, leading slash is missing in your sidebar entries. Do something like this:

```ts
        link: [obj.id, o.id].join('/').replace(/^\/?/, '/'),
```

**Comment by penyoofficial** [comment]
Sorry, I missed a crucial point. **The problem still happens when a file called 'index.md'...** @brc-dd Whether I do this or not, it doesn't affect how it happens

**Comment by brc-dd** [comment]
`[obj.id, o.id].join('/').replace(/^\/?/, '/').replace(/\/index$/, '/')`
