### ISSUE TITLE
Redirect homepage route

### ISSUE THREAD

**Issue by dj835638078** [vuejs/vitepress#3555]
### Describe the bug

when i set srcDir: '../' in config.ts，All routes become '/docs/', but When I start the project,The link that opens is '/', it is 404,
The routing in the upper left corner of the page is also / 
how can i Revise the Default homepage route   '/'  to '/docs'
![404](https://github.com/vuejs/vitepress/assets/25895889/7110233d-ae88-4048-b996-cbacc2d4f560)
![OK](https://github.com/vuejs/vitepress/assets/25895889/2f10cd24-591b-47d3-bd6c-da43f48cd098)

### Reproduction

in describe

### Expected behavior

/  to /docs

### System Info

```Text
windows
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can set `logoLink: '/docs/` in themeConfig. It won't redirect your page to `/docs/` by default though. Why do you need to set srcDir?

**Comment by dj835638078** [comment]
> You can set `logoLink: '/docs/` in themeConfig. It won't redirect your page to `/docs/` by default though. Why do you need to set srcDir?

I want to put the md file of the document in the directory of the component

**Comment by brc-dd** [comment]
Are those components also being served under `/docs/`? Can you show your directory tree and at which route you want to serve which file?

**Comment by brc-dd** [comment]
Closing as stale/
