### ISSUE TITLE
More slots in the default theme to replace components completely

### ISSUE THREAD

**Issue by stenreijers** [vuejs/vitepress#3558]
### Is your feature request related to a problem? Please describe.

I would like to replace sections in the default theme with my own components and sections for the home page. For example I want to replace the `VPHomeFeatures` with my own features component and not rely on the vitepress `VPHomeFeatures` component. The slots `vp-home-feature-before` and `vp-home-feature-after` are not sufficient, because I want to replace the actual component itself.

Section from from `src/client/theme-default/components/VPHome.vue` where the feature component is defined in the theme:
```
    <slot name="home-features-before" />
    <VPHomeFeatures />
    <slot name="home-features-after" />
```

### Describe the solution you'd like

A simple solution is to introduce more slots in the default theme such that a developer can replace components on the home page with his own custom components.

I think we should introduce at least two new slots:
- `home-features`
- `home-hero`

The improved section from `src/client/theme-default/components/VPHome.vue` would simply be:
```
    <slot name="home-features-before" />
    <slot name="home-features" />
        <VPHomeFeatures />
    </slot>
    <slot name="home-features-after" />
```

### Describe alternatives you've considered

The alternative is to tell vite to replace the `VPHome.vue` component (or Features component for that matter) with a custom `VPHome.vue` component using aliases in the configuration, e.g.:

```
vite: {
    resolve: {
      alias: [
        {
          find: /^.*\/VPHome\.vue$/,
          replacement: fileURLToPath(
            new URL('./theme/components/VPHome.vue', import.meta.url),
          ),
        },
      ],
    },
  },
```

### Additional context

If this is something the maintainers want to consider, I can prepare a quick MR for this feature asap after approval.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by stenreijers** [comment]
Unfortunately due to limitations of nested forwarding capabilities in Vue3 regarding slots and templates the proposed solution will not work for the `home-hero` component because there are nested slots in that component.

**Comment by brc-dd** [comment]
Why do you need slot for that? Just remove features from frontmatter (or prefix them with something if you're using them in your component) and register the component in one of the other slots 👀  (if frontmatter is not there, I don't think VPHomeFeatures will show up)

**Comment by stenreijers** [comment]
I see, im thinking too difficult. Thanks for this obvious answer @brc-dd.
