### ISSUE TITLE
Add PWA Support via `vite-plugin-pwa`

### ISSUE THREAD

**Issue by userquin** [vuejs/vitepress#356]
### Is your feature request related to a problem? Please describe.

PWA Support

### Describe the solution you'd like

I would like to include `vite-plugin-pwa` on `vitepress`: 
- `vite-plugin-pwa` exposes a virtual module to interact with the service worker from the client ui: this virtual module will register the service worker and when new content available will notify the client via `ref` on the ui.
- since `vitepress` is build on top of `Vite`, we can use the `rollup plugin intercomunication api` exposed also by the plugin to regenerate the service worker once the `cli` finish rendering the pages.
- on the `Layout` component, `vitepress` will include the `ReloadPrompt.vue` component, this component will import the virtual module for vue.

This way, you from `vitepress`, won't need to add the support for PWA, just use a vite plugin  for it.

I'm a collaborator of `vite-plugin-pwa` repo.

### Describe alternatives you've considered

I'm using `vitepress` with `vite-plugin-pwa` to create the docs site for `vite-plugin-pwa`, I regerenerate the service worker after `vitepress cli` finish: since the plugin will execute before `vitepress` rendering page starts, the html files won't be on the service worker precache, and so I need to process it again.

You can see [the node script](https://github.com/antfu/vite-plugin-pwa/blob/main/docs/package.json#L7) and [the pwa module](https://github.com/antfu/vite-plugin-pwa/blob/main/docs/scripts/build.ts) on `vite-plugin-pwa` repo. 

### Additional context

I have a working example on my fork on local, if you think it would be a good idea, I can push to my fork a working example.

I can also make a PR for it.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by userquin** [comment]
You can view the integration here: https://github.com/userquin/vitepress/tree/feat/pwa-support

I have added these dependencies: `fast-glob`, `vite-plugin-pwa` and `https-localhost`.

I have included the `vuepress` icon to create the icons for the PWA, I hope you don't mind. 

Just clone to local and run from root folder: 
```shell
yarn && yarn build && cd examples/minimal && yarn build && yarn serve
```
Open `https://localhost`, see the SW is installed.

Stop the server, change `examples/minimal/index.md` content and `yarn build && yarn serve` from `examples/minimal` directory.

Press F5 on browser and  the app should prompt for update: before clicking Reload button, you can open `dev tools` and on `Application > Service Workers` the new SW should be in skip waiting state. Once Refresh button clicked, then the SW should be activated and the page reloaded.

**Comment by userquin** [comment]
I have update my branch, here a summary of included changes:
- fix a11y on permalinks: since the anchors have `aria-hidden: 'true'`, included also `tabindex: '-1'`
- make show/hide button (hamburger icon) keyboard aware: the button can be activated/deactivated with enter key and with mouse (the svg becomes non focusable and the button accesible via role button and tabindex 0)
- added hook for `transformPage` before writting it to disk on build process: for example, this will be useful when adding dark/light mode to inject some script on head or body page
- add pwa support via `vite-plugin-pwa`: this will allow simplify `vitepress` logic since pwa support must be included from user land including the pwa plugin
- allow configure behavior of pwa prompt: by default no Cancel/Close button will be shown
- added i18n entries on `site` data to localize pwa prompt entries (the defaults can be changes, I included)

You can see `.vitepress/config.js` module on `examples/minimal` directory for `pwa` behavior and `transformPage` hook.

**Comment by yyx990803** [comment]
This should be done via custom config. (either `vite.config.js` or via `vite` option in `.vitepress/config.js`).

PWA doesn't add much to documentation sites by default, especially with proper HTTP caching.
