### ISSUE TITLE
The link in css file is not correct after setting base to '.' in config.mjs

### ISSUE THREAD

**Issue by m3ng9i** [vuejs/vitepress#3563]
### Describe the bug

I want to use VitePress to generate some static HTML pages, and I hope these HTML files can be opened directly with a browser by double-clicking, without the need for a web server. But after run `npm run docs:build`, and open the HTML file in Chrome, there came an error in Network panel, `Name: inter-roman-latin.bvIUbFQP.woff2`, `Status: (failed)net::ERR_FILE_NOT_FOUND`.
![](https://github.com/vuejs/vitepress/assets/8485214/80a19499-0bba-4700-b52b-4c66ca50cd86)

In `.vitepress/dist/assets/style.SZl3QJfs.css`, you can see the url of file `inter-roman-latin.bvIUbFQP.woff2` is `/assets/inter-roman-latin.bvIUbFQP.woff2` but not `./assets/inter-roman-latin.bvIUbFQP.woff2`. This might be the cause of the error.
![](https://github.com/vuejs/vitepress/assets/8485214/9f5d9ddd-a272-4f61-9a33-819ef90666c0)

### Reproduction

Run the command:

```
npm install --save-dev vitepress

npx vitepress init

    Where should VitePress initialize the config?
    ./

    Site title:
    My Awesome Project

    Site description:
    A VitePress Site

    Theme:
    Default Theme (Out of the box, good-looking docs)

    Use TypeScript for config and theme files?
    No

    Add VitePress npm scripts to package.json?
    Yes
```

Edit `.vitepress/config.mjs`, add `base : '.'` and `mpa : true`:

```
import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "My Awesome Project",
  description: "A VitePress Site",
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Examples', link: '/markdown-examples' }
    ],

    sidebar: [
      {
        text: 'Examples',
        items: [
          { text: 'Markdown Examples', link: '/markdown-examples' },
          { text: 'Runtime API Examples', link: '/api-examples' }
        ]
      }
    ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
    ]
  },
  base : '.',
  mpa : true
})
```

And build the docs:

```
npm run docs:build
```

Open the file `.vitepress/dist/api-examples.html` in Chrome by double-clicking, and then open the Network panel of Chrome's DevTools to see the error.

### Expected behavior

After set  `base : '.'` in `config.mjs`, the url of assets should start with `./assets/`, but not `/assets/`.

### System Info

```Text
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 10.44 GB / 15.52 GB
    Container: Yes
    Shell: 3.6.0 - /usr/bin/fish
  Binaries:
    Node: 18.17.1 - ~/dev/nodejs/nodejs/bin/node
    npm: 10.4.0 - ~/dev/nodejs/nodejs/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
  npmPackages:
    vitepress: ^1.0.0-rc.42 => 1.0.0-rc.42
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Relative base is not supported. Many other things won't work too. And we don't plan to support that in near future. Use some other tool if you want to serve generated html directly from filesystem.
