### ISSUE TITLE
Support img srcset

### ISSUE THREAD

**Issue by erik-beus** [vuejs/vitepress#3566]
### Is your feature request related to a problem? Please describe.

To allow sites to serve images in the most relevant size/format, it would be nice if the [image plugin](https://github.com/vuejs/vitepress/blob/main/src/node/markdown/plugins/image.ts) supported setting the [srcset attribute](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset)

I'm happy to add a proposal for the implementation if anyone else finds this useful.

### Describe the solution you'd like

Being able to link to multiple image sizes/formats to allow the browser to pick the most relevant image.
The current `src` attribute should still work as it currently does.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you explain more what feature are you requesting? That plugin only normalizes the src and is not needed at all if your src/srcset is correct.

**Comment by erik-beus** [comment]
> Can you explain more what feature are you requesting? That plugin only normalizes the src and is not needed at all if your src/srcset is correct.

Sorry, I'm new to this project and did not fully understand its capabilities.
`srcset` does work as intended as you mentioned 👍 

Do you know if it's possible to render a [picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) element as well? Or would that require a separate plugin?

Thank you for your feedback 🙌

**Comment by brc-dd** [comment]
You don’t need plugins. You can simply add the picture element and it will work fine.

**Comment by erik-beus** [comment]
Got it, thank you. I guess I got confused when trying to use a `picture` on a page with the ["home" layout](https://vitepress.dev/reference/default-theme-home-page) instead of its `image` property. But it seems that would require a custom "page" layout 👍
