### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'K' before initialization

### ISSUE THREAD

**Issue by liulyxandy-codemao** [vuejs/vitepress#3569]
### Describe the bug

I was using 1.0.0-rc.40 before, and everything worked correctly in local. After building in the CI system and deploying to my own server, the search button and the theme button (switching to dark/light theme) didn't work correctly. The sidebar worked, but it didn't highlight the current page. I thought it was because of the version is low, so I updated to 1.0.0-rc.42, but the problem still happens.
I found that this problem is similar to [#2074 ](https://github.com/vuejs/vitepress/issues/2074), but that issue is already closed and locked as resolved.

### Reproduction

https://bot.cocotais.cn/

### Expected behavior

See the description

### System Info

```Text
[15:08:53]   System:
[15:08:53]     OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
[15:08:53]     CPU: (16) x64 Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
[15:08:53]     Memory: 26.13 GB / 30.09 GB
[15:08:53]     Container: Yes
[15:08:53]     Shell: 5.0.17 - /bin/bash
[15:08:53]   Binaries:
[15:08:53]     Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
[15:08:53]     Yarn: 1.15.2 - /usr/local/bin/yarn
[15:08:53]     npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
[15:08:53]     pnpm: 7.33.5 - ~/.nvm/versions/node/v18.12.1/bin/pnpm
[15:08:53]   npmPackages:
[15:08:53]     vitepress: ^1.0.0-rc.42 => 1.0.0-rc.42
```

### Additional context

![image](https://github.com/vuejs/vitepress/assets/65491750/058f63d8-964a-4edc-a662-f35133904442)
![image](https://github.com/vuejs/vitepress/assets/65491750/5efc858b-6973-4f4e-9869-844648c5c402)
position: assets/chunks/framework.BYmzT8Bu.js

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide the minimal code required to reproduce this issue in form of a repo or using https://vitepress.new

**Comment by liulyxandy-codemao** [comment]
> Please provide the minimal code required to reproduce this issue in form of a repo or using https://vitepress.new

https://github.com/liulyxandy-codemao/bot-doc

**Comment by brc-dd** [comment]
Locally `npm run docs:build && npm run docs:preview` is working fine. How are you deploying your page?

**Comment by liulyxandy-codemao** [comment]
run script
```shell
npm install
npm run docs:build
```
then upload artifacts inside .vitepress/dist to /path/to/my_site
then set nginx rewrite:
```
location / {
	if (!-e $request_filename){
		rewrite  ^(.*)$  $1.html  last;   break;
	}
}
```

**Comment by brc-dd** [comment]
I'm still not sure what is going wrong. The code looks fine and it works fine locally. Which CI are you using? Can you try changing the build command to `DEBUG='*' npm run docs:build` and share the logs here?

**Comment by liulyxandy-codemao** [comment]
The CI system is https://flow.aliyun.com/. I use it to build and deploy a few of my projects, and it usually works correctly. 
Here is the complete log: 
[logs-build.txt](https://github.com/vuejs/vitepress/files/14236382/logs-build.txt)
and this is the artifact:
[Artifacts_2911466.tar.gz](https://github.com/vuejs/vitepress/files/14236392/Artifacts_2911466.tar.gz)

**Comment by liulyxandy-codemao** [comment]
Very weird, I found that the error message changed:
![image](https://github.com/vuejs/vitepress/assets/65491750/344baeb7-ae1f-454a-ae58-ba0c6bc71826)

**Comment by brc-dd** [comment]
> Very weird, I found that the error message changed after re-run the CI build:

It's the same error, but the code is now not minified because you set `DEBUG`.

Looking at the artifact there indeed is a circular reference (theme -> framework -> theme chunk), but for some reason it's not happening  while building locally. I'll look into it.

**Comment by liulyxandy-codemao** [comment]
I've found that the *优先使用缓存*(means *Prefer using local cache* in English) option in the CI system is open by default.

> It caches the build dependencies in the cache directories of different task workspaces separately. The cache can be quickly downloaded the next time the task is executed to improve the overall build speed.
> ------ From the official document of the CI system

So I tried to disable it in the settings, and then it built successfully, the site works properly too.
@brc-dd Thank you very much for helping me to resolve the problem. ❤️
