### ISSUE TITLE
Project not working

### ISSUE THREAD

**Issue by QiYoe** [vuejs/vitepress#357]
### Describe the bug

vitepress dependency error

### Reproduction

Errors reported during project startup and packaging

### Expected behavior

project can start and package normally

### System Info

```shell
Error: 'defineEmit' is not exported by node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js, imported by node_modules/vitepress/dist/client/theme-default/components/NavBar.vue?vue&type=script&setup=true&lang.ts
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
Duplicate of #355
