### ISSUE TITLE
Content missing when being deployed to Vercel

### ISSUE THREAD

**Issue by CoolPlayLin** [vuejs/vitepress#3570]
### Describe the bug

When I deployed my website to Vercel, I tried to access the website via specific url like https://rule.xfisxf.top/policy/charter.html to check out an article. But the content missed in less 1s and it threw `framework.gkMttBBc.js:2  Hydration completed but contains mismatches.` error in console.

![image](https://github.com/vuejs/vitepress/assets/96709586/cecf937b-2622-414e-acf0-36ed60375432)

### Reproduction

Deploy website to Vercel

### Expected behavior

Checked out complete content in browser

![image](https://github.com/vuejs/vitepress/assets/96709586/4d46c2b0-02fc-4471-8b56-c0d560f7e667)

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Intel(R) Pentium(R) CPU GOLD 6500Y @ 1.10GHz
    Memory: 1.46 GB / 7.92 GB
  Binaries:
    Node: 18.19.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.21 - ~\scoop\apps\nvm\current\nodejs\nodejs\yarn.CMD
    npm: 10.2.5 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 8.15.1 - ~\scoop\shims\pnpm.EXE
  Browsers:
    Edge: Chromium (121.0.2277.112), ChromiumDev (123.0.2380.1)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-rc.42 => 1.0.0-rc.42
```

### Additional context

The error only appears in production env.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by liulyxandy-codemao** [comment]
Might be a duplicate.
https://github.com/vuejs/vitepress/issues/1143#issuecomment-1212374302
Take a look at this. Do you enable options like *Auto Minify*?

**Comment by CoolPlayLin** [comment]
I have found the reason which caused this issue: Cloudflare opened Auto Minify by default

Thanks for @liulyxandy-codemao 's point!
