### ISSUE TITLE
Please  assign  the  ref  attribute  to  the  key  label  element.

### ISSUE THREAD

**Issue by you-hengh** [vuejs/vitepress#3574]
### Is your feature request related to a problem? Please describe.

I  currently  have  a  practical  requirement  to  change  the  background  image  of  the  homepage  based  on  the  button  state  with  the  class  "VPSwitch  VPSwitchAppearance".

However,  this  button  does  not  have  an  id  attribute  or  a  ref  attribute,  which  forces  me  to  use  the  `document.querySelector()`  method  to  get  this  element.

This  is  quite  uncomfortable  in  the  Vue3  environment.

### Describe the solution you'd like

Give ref tags to all key elements

### Describe alternatives you've considered

null

### Additional context

![image](https://github.com/vuejs/vitepress/assets/34816426/9b9d7f23-1a00-4ca8-b197-00d203c4ef0a)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by you-hengh** [comment]
> For checking light/dark mode you can directly do this:
> 
> ```ts
> import { useData } from 'vitepress'
> 
> const { isDark } = useData()
> ```
> 
> Also not sure what ref will do here. Exposing ref of each element is not feasible.

However, when I want to set the background image, I still seem to be able to get the binding element through'document.querySelector () ', and then set the'background-image'.

So, can you provide some elegant ways?

**Comment by brc-dd** [comment]
> So, can you provide some elegant ways?

Just [add some css](https://vitepress.dev/guide/extending-default-theme#customizing-css) like this:

```css
.foo {
  background: url(...);
  background-size: cover;
}

.dark .foo {
  background: url(...);
}
```

Inside your home page (index.md) add:

```md
---
pageClass: foo
---
```

PS: If you are targeting modern browsers only you can directly use `.Layout:has(.vp-home)` in CSS too
