### ISSUE TITLE
Allow custom title link (or side bar item with image)

### ISSUE THREAD

**Issue by eschirtz** [vuejs/vitepress#3577]
### Is your feature request related to a problem? Please describe.

I'm finding it very difficult to override the location of the title <a> tag. I have a docs site for my web app and users are getting confused because they click our company logo at the top right (the title link) but are being navigated "/", the root of the docs (vite press) site. I'd like to direct users to our other domain. 

### Describe the solution you'd like

Either a `link` field in the `logo` themeConfig. (that would probably need to extend the Themeable image, which might be gross). 

Or even just a place where I can write some custom js to select the title and change the anchor tag's href. 

### Describe alternatives you've considered

I checked out this issue: https://github.com/vuejs/vitepress/issues/717

But the proposed solution doesn't seem to work in my case. Unless I'm missing something, I can't add an image to the side bar items. And even if I could, I don't think it would persist the nice "sticky" behavior the title has out of the box. 

### Additional context

Totally down to hack something in place here, does not need to be built into the core API. But I do think other users may want this when building consumer applications with documentation sites built with vite press. 

For reference: 

https://docs.samply.app
and https://samply.app

Thanks!

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
themeConfig.logoLink
