### ISSUE TITLE
vitepress@1.0.0-rc.40+ breaks vitepress dev

### ISSUE THREAD

**Issue by lukastaegert** [vuejs/vitepress#3579]
### Describe the bug

After updating to vitepress@1.0.0-rc.40 (and still confirmed in vitepress@1.0.0-rc.42), we can no longer use vitepress's development mode via `vitepress dev`.
While the CLI app runs without visible errors, the browser only shows an empty screen. In the browser console, the following warnings and error are shown:
<img width="662" alt="vitepress-error" src="https://github.com/vuejs/vitepress/assets/12949268/f6b73163-1a5f-4890-8c28-0c5744000ef3">
As this does not seem to originate from our own code, we are not sure we can do anything about it. At the moment, we avoid the issue by pinning vitepress to vitepress@1.0.0-rc.39.

### Reproduction

```shell
git clone git@github.com:rollup/rollup.git
cd rollup
npm install --ignore-scripts
npm install vitepress@latest
npm run dev
```

### Expected behavior

Opening http://localhost:5173/ in the browser shows the Rollup website.

### System Info

```Text
System:
    OS: macOS 14.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 14.80 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - ~/.asdf/installs/nodejs/20.5.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.14.1 - ~/.asdf/installs/nodejs/20.5.1/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.3.1
  npmPackages:
    vitepress: ^1.0.0-rc.42 => 1.0.0-rc.42
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Adjusted the condition. Will be there in next release (1-2 days). But it was due to this - https://github.com/rollup/rollup/blob/c9b3655ec25d08f5182feb3d118cc676940f1549/build-plugins/replace-browser-modules.ts#L46 -- you're forcing process to be defined in browser.

**Comment by lukastaegert** [comment]
Oh I see, thank you so much! I did not consider this. Let's see if I still need this hack.
