### ISSUE TITLE
can not start server successful 

### ISSUE THREAD

**Issue by WangYuLue** [vuejs/vitepress#358]
### Describe the bug

I created a new project based on the [Getting Started](https://vitepress.vuejs.org/guide/getting-started.html) tutorial, but get error

### Reproduction

steps reference [Getting Started](https://vitepress.vuejs.org/guide/getting-started.html) tutorial

### Expected behavior

![屏幕快照 2021-08-10 下午6 53 59](https://user-images.githubusercontent.com/19245919/128854914-cde09c97-c406-48fd-abca-ce0fe981f374.png)

### System Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 89.25 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Chrome Canary: 94.0.4603.0
    Firefox: 88.0.1
    Safari: 14.1.2
  npmPackages:
    vitepress: ^0.15.6 => 0.15.6
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yaiks** [comment]
I'm also having this issue, but I'm confident these last commits ([this](https://github.com/vuejs/vitepress/commit/30388298078f6c951844be88da6042e396161569) and [this](https://github.com/vuejs/vitepress/commit/ef1e205cb69dca7ef59661150449ae3d9d8cea81)) will fix the issue =)

As far as I know, the issue may be caused by the deprecation of `defineEmit` as [explained here](https://github.com/vuejs/vue-next/pull/3725)

Hopefully we will get a new release soon 😄

**Comment by yaiks** [comment]
For now, one alternative is to declare the versions of sub dependencies you want to use. If using yarn, you can place in your `package.json`:

```
  "devDependencies": {
    "vitepress": "0.15.6"
  },
  "resolutions": {
    "@vitejs/plugin-vue": "1.2.3",
    "@vue/compiler-sfc": "3.1.1",
    "@vue/server-renderer": "3.1.1",
    "vite": "2.3.7",
    "vue": "3.1.1"
  },
```

If using `npm`, you can use `npm shrinkwrap` for the same goal =)

**Comment by posva** [comment]
Already fixed, will be up in next release.

---

Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
