### ISSUE TITLE
document is not defined when vitepress build

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/vitepress#3583]
### Describe the bug

I imported a lib which called document APIs. The minimized reproduction:

```
<script>
const div = document.createElement('div');
console.log(div)
</script>

# Hello World
```

It works in vitepress dev but fails in vitepress build

### Reproduction

https://github.com/Jinjiang/reproductions/tree/vitepress-document-20240219

### Expected behavior

Works as vitepress dev does

### System Info

```Text
$ npx envinfo --system --npmPackages vitepress --binaries --browsers

  System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1
    Memory: 75.17 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - ~/.asdf/installs/nodejs/20.1.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 9.6.4 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Safari: 17.4
  npmPackages:
    vitepress: 1.0.0-rc.43 => 1.0.0-rc.43
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Ah we do SSR. You’ll need to mark that component as ClientOnly or in case of libraries, import them inside onMounted. Refer - https://vitepress.dev/guide/ssr-compat

**Comment by Jinjiang** [comment]
Gotcha. It works now. Thanks!
