### ISSUE TITLE
Using the simplest example, an error occurred

### ISSUE THREAD

**Issue by TuiMao233** [vuejs/vitepress#359]
### Describe the bug

yarn docs:dev

Browser display error：
![image](https://user-images.githubusercontent.com/49724027/128883201-46040f74-790d-4a98-8c24-47a2b842550b.png)

### Reproduction

Follow the getting started case, which is https://vitepress.vuejs.org/guide/getting-started.html

### Expected behavior

Normal display index.md

### System Info

```shell
~~~
PS G:\vitePress> npx envinfo --system --npmPackages vitepress --binaries --browsers
Need to install the following packages:
  envinfo
Ok to proceed? (y) y

  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
    Memory: 3.91 GB / 7.93 GB
  Binaries:
    Node: 16.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Spartan (44.17763.831.0)
    Internet Explorer: 11.0.17763.771
  npmPackages:
    vitepress: ^0.15.6 => 0.15.6
~~~
```

### Additional context

![image](https://user-images.githubusercontent.com/49724027/128883546-5da85f64-6697-4b4c-890e-834a3e251390.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Comment by TuiMao233** [comment]
I think I have searched for related issues, but I didn't find this error. Can you tell me where it is.

**Comment by TuiMao233** [comment]
Ok i saw it, i only searched for existing problems
