### ISSUE TITLE
Linking to HTML file in public dir

### ISSUE THREAD

**Issue by newcat** [vuejs/vitepress#360]
### Describe the bug

When placing an HTML file inside the `public` folder, creating a link to it and then clicking the link, the console fills with warnings and errors instead of navigating to the HTML file.
![grafik](https://user-images.githubusercontent.com/1523157/128949245-0f45d7da-3a98-4793-a618-d78ff1f9f579.png)

### Reproduction

1. Place an HTML file inside the public dir (e. .g. `public/api/index.html`)
2. Inside a Markdown file, create a link to this HTML file:
```
[link](/api/)
[link](/api/index)
[link](/api/index.html)
```
3. Open the page and click the link

### Expected behavior

The browser should navigate to the HTML file and display it full-size (essentially replacing the VitePress app)

Interestingly: When accessing to the HTML page directly (`http://localhost:3000/api/index.html`) it renders the HTML page, so that part works.
Although clicking the link and reloading (`CTRL+R`) renders the HTML page, but when clicking the browser's back button it just changes the URL and doesn't return to the VitePress application.

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 1600X Six-Core Processor
    Memory: 7.92 GB / 15.95 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.55)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    vitepress: ^0.16.0 => 0.16.0
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
Markdown links to md or html are meant to link to other documentation files. Have you tried using a regular `<a href="...">` link?

**Comment by brc-dd** [comment]
Use absolute link for that. It will be marked as external and would work.
