### ISSUE TITLE
首页图片显示不出来

### ISSUE THREAD

**Issue by wczdsg** [vuejs/vitepress#3601]
### Describe the bug

首页图片显示不出来，图片已经放到public目录下，路径也配了
![image](https://github.com/vuejs/vitepress/assets/73579422/144460a0-913f-4f40-837d-e7521087c908)

### Reproduction

![image](https://github.com/vuejs/vitepress/assets/73579422/973e68b7-83ea-4022-a82b-89552d20f7b5)
![image](https://github.com/vuejs/vitepress/assets/73579422/7a6f766c-281e-4ee7-b016-04bd964b9b45)

### Expected behavior

正确显示图片

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 7.97 GB / 15.90 GB
  Binaries:
    Node: 21.5.0 - d:\nvm\nodejs\node.EXE
    npm: 10.2.4 - d:\nvm\nodejs\npm.CMD
    pnpm: 8.15.3 - d:\nvm\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you share the code in form some github repo? And are there any error logs in the dev console or some message in the network tab?

**Comment by brenoepics** [comment]
Also, if your config.js looks like this:
```js
export default defineConfig({
...
  srcDir: 'src',
...
```
the `public` directory should be inside `src`.
[Docs Reference](https://vitepress.dev/guide/asset-handling#the-public-directory)

**Comment by wczdsg** [comment]
> ```js
> srcDir: 'src',
> ```

Thanks very much！
