### ISSUE TITLE
Issue with Fetching <title> Tag Content from CMS

### ISSUE THREAD

**Issue by shihanjun19** [vuejs/vitepress#3609]
### Describe the bug

I have successfully fetched article content and title information using the code below. However, in both development and production modes, the value of the HTML <title> tag is rendered as {{$params.title }} | Logo. This issue occurs despite the data being correctly retrieved from the CMS as demonstrated in the code snippet provided. How can I ensure that the <title> tag correctly displays the fetched title instead of {{$params.title }} | Logo?

```
// posts/[pkg].paths.js
import axios from 'axios';

export default {
        async paths() {
        try {
            const response = await axios.get('http://127.0.0.1:1337/api/white-papers');
            const data = response.data;

            const pathsObj = data.data.map(entry => {
                console.log('文章：', entry)
                return {
                    params: {
                        id: entry.id,
                        title: entry.attributes.title,
                        pkg: entry.attributes.pathName, /* title, authors, date 等 */
                    },
                    content: entry.attributes.content
                }
            });

            // console.log('页面配置：', pathsObj)
            return pathsObj;
        } catch (error) {
            console.error('请求API失败:', error);
            // 处理错误情况，比如返回一个错误页面的路径或者其他逻辑
            return [];
        }
    }
}
```

I'm looking for solutions to dynamically update the <title> tag with content fetched from a CMS in a Vue.js or similar JavaScript framework environment.

### Reproduction

For the "Reproduction" section of your GitHub issue, you should describe the steps to replicate the problem you're facing in a clear and concise manner. Here's an example:

---

**Reproduction Steps:**

1. Set up a project connected to a CMS for fetching article titles and content.
2. Use the provided code snippet to fetch data from the CMS.
3. Observe the `<title>` tag's value in development mode using `npm run dev` or a similar command.
4. Build the project for production using `npm run build` and `npm start` or equivalent commands.
5. Notice that instead of displaying the fetched article title, the `<title>` tag shows `{{$params.title}} | Logo` in both development and production modes.

### Expected behavior

After fetching article titles and content from the CMS, the HTML <title> tag should dynamically display the title of the current article, reflecting the fetched data. For instance, if the fetched title is "Understanding Blockchain", the <title> tag in the HTML should be "Understanding Blockchain | Logo" in both development and production modes, instead of showing the placeholder {{$params.title}} | Logo.

### System Info

```Text
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600K
    Memory: 16.99 GB / 31.75 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.52)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.44 => 1.0.0-rc.44
```

### Additional context

![微信截图_20240227094747](https://github.com/vuejs/vitepress/assets/10006241/495ebd24-88f6-4144-b7ef-02f5ef29323a)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You'll need to do it using transformPageData for now. Please track #2637
