### ISSUE TITLE
Git clone the vitepress warehouse, startup error

### ISSUE THREAD

**Issue by diy4869** [vuejs/vitepress#361]
### Describe the bug

Git clone the vitepress warehouse. After executing yarn Dev and yarn docs, it cannot be started, and an error is reported after startup

github：https://github.com/diy4869/vitepress

### Reproduction

Git clone the vitepress warehouse. After executing yarn Dev and yarn docs, it cannot be started, and an error is reported after startup

### Expected behavior

Start successful

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz  
    Memory: 2.13 GB / 15.88 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.164
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.67)
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
Can't reproduce...

**Comment by diy4869** [comment]
> Can't reproduce...

After I execute npm run build-docs, I can run npm run docs，Run successfully
