### ISSUE TITLE
rendering pages...ReferenceError: self is not defined  when build

### ISSUE THREAD

**Issue by jefferryDeng** [vuejs/vitepress#3610]
### Describe the bug

in my md file, i use a component use dplayer, when i use in dev, it is ok.
when i build, show errors:  rendering pages...ReferenceError: self is not defined
i use the ClientOnly, it not ok

### Reproduction

<script lang="ts" setup>
import VPlayer from './src/index'
</script>
<ClientOnly>
  <VPlayer url="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"></VPlayer>
</ClientOnly>

### Expected behavior

when i build , it is ok like dev

### System Info

```Text
windows
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to import it dynamically inside onMounted - https://vitepress.dev/guide/ssr-compat#libraries-that-access-browser-api-on-import

**Comment by jefferryDeng** [comment]
> You need to import it dynamically inside onMounted - https://vitepress.dev/guide/ssr-compat#libraries-that-access-browser-api-on-import

how to use, and how to register componnets

**Comment by jefferryDeng** [comment]
> > You need to import it dynamically inside onMounted - https://vitepress.dev/guide/ssr-compat#libraries-that-access-browser-api-on-import
> 
> how to use, and how to register componnets

i use defineAsyncComponent solve the problem , thanks
