### ISSUE TITLE
Algolia search result is empty

### ISSUE THREAD

**Issue by galgaxy3** [vuejs/vitepress#3614]
### Describe the bug

Hello, when I was searching using Algolia, the search results on the vitepress page were not displayed. However, Algolia's console page showed 140 records. Is this a missing configuration? By the way, for the project reason, I didn't use docsearch, but Algolia's build plan

### Reproduction

The error can be seen on this website https://stackblitz.com/edit/vite-48o9dv?file=docs%2F.vitepress%2Fconfig.ts,package.json
This is the source code of the website https://github.com/galgaxy3/docs-demo

### Expected behavior

There should be a query result

### System Info

```Text
Chrome, vitepress 1.0.0-rc.44
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Seems like language is not being indexed there 👀 You probably will need to set `lang` in `attributesForFaceting` in your crawler config. Refer this comment - https://github.com/vuejs/vitepress/issues/1935#issuecomment-1433765099 or the docs for complete crawler config - https://vitepress.dev/reference/default-theme-search#crawler-config

**Comment by brc-dd** [comment]
Closing as stale.
