### ISSUE TITLE
Strange symbols appear

### ISSUE THREAD

**Issue by TuiMao233** [vuejs/vitepress#362]
### Describe the bug

![image](https://user-images.githubusercontent.com/49724027/129190981-b0e433cc-c924-4d3b-9c4e-c6e9da66d18a.png)
![image](https://user-images.githubusercontent.com/49724027/129191035-4614ca90-9ea5-41f7-8c6e-ec57114e5c5b.png)
![image](https://user-images.githubusercontent.com/49724027/129191233-3a0da6ff-9a08-4a8b-ac98-f57f0144cb46.png)

### Reproduction

yarn add vitepress

edit package.json

~~~
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:serve": "vitepress serve docs"
  }
~~~

yarn docs:dev

### Expected behavior

normal display

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
    Memory: 3.25 GB / 7.93 GB
  Binaries:
    Node: 16.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Spartan (44.17763.831.0)
    Internet Explorer: 11.0.17763.771
  npmPackages:
    vitepress: ^0.16.1 => 0.16.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
You likely have the wrong encoding in one of your files or browser.


Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by TuiMao233** [comment]
Well, I will consider it next time,
But now I want to know how to solve this problem.
If there is something wrong with my browser or file,
But it doesn’t mean that I changed multiple computers and the results were the same, right?

**Comment by TuiMao233** [comment]
This is my company’s computer, the same operation
![image](https://user-images.githubusercontent.com/49724027/129292428-6b271339-efde-45fb-b61f-4edb4bf9ed47.png)
![image](https://user-images.githubusercontent.com/49724027/129292454-ee712e9c-d864-4ff8-958f-c5b26235338d.png)
![image](https://user-images.githubusercontent.com/49724027/129292474-792a46c5-12e6-40de-98dd-a8145b40185b.png)
