### ISSUE TITLE
Vitepress - A new server instance gets opened on each hot reload

### ISSUE THREAD

**Issue by RoyalcraftDev** [vuejs/vitepress#3620]
### Describe the bug

Each time I save a file in my Vitepress project (which triggers hotreload), Vitepress will open a new a server instance. (The port increments each time and I can visit `localhost:5173`, `localhost:5174`, etc.

### Reproduction

1. Create a new vitepress project: `npm init && npm install -D vitepress`
2. Run the server after setting up the commands in your `package.json`: `npm run dev`
3. Trigger hotreload

### Expected behavior

It shouldn't have to open a server each time I trigger hotreload and re-use the same one!

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 8 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.59)
  npmPackages:
    vitepress: ^1.0.0-rc.44 => 1.0.0-rc.44
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What? Please share a reproducible example and probably a video recording. It shouldn't do this under any normal circumstances.

**Comment by brenoepics** [comment]
I've had the same problem, usually when I break something and Vitepress starts looping loading on new ports,
I'll try to reproduce that.

**Comment by brenoepics** [comment]
Hi @brc-dd,
 I managed to replicate, 
![image](https://github.com/vuejs/vitepress/assets/59066707/de029a73-65f4-4a8a-8855-af0388f0a42a)
If you edit `config.ts` very quickly this can happen, in some cases I had 15 instances running.
It doesn't affect production and if you restart it goes back to normal but it's quite annoying.

```ts
// ref: src/node/cli.ts
if (!command || command === 'dev') {
  if (argv.force) {
    delete argv.force
    argv.optimizeDeps = { force: true }
  }

  const createDevServer = async () => {
    const server = await createServer(root, argv, async () => {
      await server.close()
      await createDevServer()
    })
    await server.listen()
    logVersion(server.config.logger)
    server.printUrls()
    bindShortcuts(server, createDevServer)
  }
  createDevServer().catch((err) => {
    createLogger().error(
      `${c.red(`failed to start server. error:`)}\n${err.stack}`
    )
    process.exit(1)
  })
}
```

somehow, when you edit files very fast, this code will open a new server but doesn't close the older one (probably not even open yet)
```ts
      await server.close()
      await createDevServer()
```

onRestart is being called from this file which is being called 2x before server restart
https://github.com/vuejs/vitepress/blob/75115f4f8223d67dab2dc82fadaf2941aabf6330/src/node/plugin.ts#L371
