### ISSUE TITLE
`createContentLoader` API bug

### ISSUE THREAD

**Issue by keer-tea** [vuejs/vitepress#3622]
### Describe the bug

I set the srcDir option to./src and use createContentLoader, but createContentLoader gets an empty array of documents. Here's an example: https://stackblitz.com/edit/vitejs-vite-kdqe5d?file=.vitepress%2Fconfig.js

### Reproduction

https://stackblitz.com/edit/vitejs-vite-kdqe5d?file=.vitepress%2Fconfig.js

### Expected behavior

createContentLoader obtains the files in the specified directory

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 4.83 GB / 15.74 GB
  Binaries:
    Node: 18.18.0 - D:\Installation\nvm_nodejs\node.EXE
    Yarn: 1.22.21 - D:\Installation\nvm_nodejs\yarn.CMD
    npm: 8.7.0 - D:\Installation\nvm_nodejs\npm.CMD
    pnpm: 8.11.0 - D:\Installation\nvm_nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.59)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.44 => 1.0.0-rc.44
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by 0xlau** [comment]
It looks like a bug. And I linked a pull request in this issue (#3638).

Before the ` vitepress@1.0.0-rc.45 ` version, here are two solutions as follows.

1. Type "src" after `vitepress dev` command in `packages.json`.

![s1](https://github.com/vuejs/vitepress/assets/45397727/f3c8a510-6fd1-4425-9850-8ca327291216)

2. Type "src/" before the pattern mapping path in createContentLoader.

![s2](https://github.com/vuejs/vitepress/assets/45397727/8c75e02a-ad0a-46e3-bbf3-c77f8395530d)

Hope these solutions help you!
