### ISSUE TITLE
error convert attribute by `{ }` | Internal server error: Duplicate attribute

### ISSUE THREAD

**Issue by Zhengqbbb** [vuejs/vitepress#3623]
### Describe the bug

```md
*HEXSTR* := { 8 or 16 hex digits (4 / 8 bytes) }
```
===>
```html
<!-- [vitepress] Internal server error: Duplicate attribute. -->
<p 8="" or="" 16="" hex="" digits="" (4="" 8="" bytes)=""><em>HEXSTR</em> :=</p>
```
I viewed the doc: https://vitepress.dev/guide/using-vue. I see the interpolation `{{ }}` will be converted.
But this situation should be abnormal.

### Reproduction

```md
*HEXSTR* := { 8 or 16 hex digits (4 / 8 bytes) }
```

https://stackblitz.com/edit/vite-hsfy9m?file=docs%2Fexample.md

### Expected behavior

```html
<p><em>HEXSTR</em> := { 8 or 16 hex digits (4 / 8 bytes) }</p>
```

### System Info

```Text
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 387.17 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.x-cmd.root/local/data/pkg/sphere/X/l/j/h/bin/node
    npm: 10.2.4 - ~/.x-cmd.root/local/data/pkg/sphere/X/l/j/h/bin/npm
    pnpm: 8.9.2 - ~/project/lteam/x-cmd/official-doc/node_modules/.bin/pnpm
    bun: 1.0.24 - ~/.x-cmd.root/local/data/pkg/sphere/X/l/j/h/bin/bun
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.2.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to disable markdown-it-attrs (`markdown: { attrs: false }`) for that. Or adjust it's delimiters to something other than `{`/`}`

**Comment by Zhengqbbb** [comment]
```diff
- *HEXSTR* := { 8 or 16 hex digits (4 / 8 bytes) }
+ *HEXSTR* := \{ 8 or 16 hex digits (4 / 8 bytes) \}
```
