### ISSUE TITLE
bug: when you are configuring sidebar in config.*, the '<script>' or '<style>' in text will be parsed directly into a tag instead of a string

### ISSUE THREAD

**Issue by xxhls** [vuejs/vitepress#3627]
### Describe the bug

When setting the sidebar text, i want to write a simple script tag in the text, such as 'Compare <script> the difference with <script async>', however, In real rendering, both tags are converted to tags instead of strings, and cannot be displayed
![image](https://github.com/vuejs/vitepress/assets/108137214/10775157-65f3-4ba1-8606-0848425f3e6b)

### Reproduction

Here is the location [stackblitz](https://stackblitz.com/edit/vite-hiphbr)

### Expected behavior

I want to render 'This is <script> <style>', but it renders 'This is'.

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
npmPackages:
    vitepress: latest => 1.0.0-rc.44
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
use &lt; &gt; instead

**Comment by xxhls** [comment]
thank you, I get it.
