### ISSUE TITLE
inline html transform error

### ISSUE THREAD

**Issue by yonecdeng** [vuejs/vitepress#3632]
### Describe the bug

The original md document：

```
   hello <picture>
     <img src="https://github.com/markdown-it/markdown-it/assets/73653404/63aa836d-2541-40bb-a4be-aaf02495426d"/>
   </picture>
```

After executing md.render it will be：
```
   <p>hello <picture></p>
     <img src="https://github.com/markdown-it/markdown-it/assets/73653404/63aa836d-2541-40bb-a4be-aaf02495426d"/>
   </picture>
```

### Reproduction

you can try this markdown content:
```
   hello <picture>
     <img src="https://github.com/markdown-it/markdown-it/assets/73653404/63aa836d-2541-40bb-a4be-aaf02495426d"/>
   </picture>
```
### Expected behavior

I hope after executing md.render it should be：
```
   <p>hello</p><picture>
     <img src="https://github.com/markdown-it/markdown-it/assets/73653404/63aa836d-2541-40bb-a4be-aaf02495426d"/>
   </picture>
```

### System Info

<img width="1045" alt="image" src="https://github.com/markdown-it/markdown-it/assets/73653404/63aa836d-2541-40bb-a4be-aaf02495426d">

### Additional context

This seems to be caused by using some mdit plugin, because I tried it [here](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%20%20%20hello%20%3Cpicture%3E%5Cn%20%20%20%20%20%3Csource%20type%3D%5C%22image%2Favif%5C%22%20srcset%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%3FimageMogr2%2Fformat%2Favif%5C%22%3E%5Cn%20%20%20%20%20%3Cimg%20src%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%5C%22%20alt%3D%5C%22https%3A%2F%2Fpicbed-1306720359.cos.ap-guangzhou.myqcloud.com%2Fupic%2F2024-02-07-17-37-OUE54Z.webp%5C%22%20loading%3D%5C%22lazy%5C%22%2F%3E%5Cn%20%20%20%3C%2Fpicture%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D) and it converted correctly

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yonecdeng** [comment]
> With your markdown-it playground example it's reproducible if you remove extra spaces from front. But there too it's producing invalid html. In that case the error is correct.
> 
> ```
> <p>hello <picture></p>
>   <source type="image/avif" srcset="https://picbed-1306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp?imageMogr2/format/avif"/>
>   <img src="https://picbed-1306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp" alt="https://picbed-1306720359.cos.ap-guangzhou.myqcloud.com/upic/2024-02-07-17-37-OUE54Z.webp" loading="lazy"/>
> </picture>
> ```
> 
> <img alt="image" width="1246" src="https://private-user-images.githubusercontent.com/40380293/311997993-45197b12-1f14-47a8-b154-5f1f0f621aa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzMxOTgsIm5iZiI6MTcxMDU3Mjg5OCwicGF0aCI6Ii80MDM4MDI5My8zMTE5OTc5OTMtNDUxOTdiMTItMWYxNC00N2E4LWIxNTQtNWYxZjBmNjIxYWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA3MDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYjBkMTRiNGM5OTE1YTQwYThhYTg3NTk4NDc1OTJiN2M1NmQwNTJlY2ZhMTVkZDA3ZTI5ZjRlYzI5OGI1MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YioTQhamG7Gz2Pg2EktHlyGFgqXcrXfZetgSMGOB59I">
> If you don't remove spaces, then it works fine in both markdown-it playground and vitepress:
> 
> <img alt="image" width="1518" src="https://private-user-images.githubusercontent.com/40380293/311999341-a978fd3c-63dd-4917-a4c0-2c7d687b0d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzMxOTgsIm5iZiI6MTcxMDU3Mjg5OCwicGF0aCI6Ii80MDM4MDI5My8zMTE5OTkzNDEtYTk3OGZkM2MtNjNkZC00OTE3LWE0YzAtMmM3ZDY4N2IwZDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA3MDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjODEzNTZjYTgzNmI2MWZjYWYwMzUwOGQyODJkNDhlN2ViOWNkY2Y2MGY2MzIzZDM3N2VmMjU3MmY3ODM1N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nDJzFp1cdHWmjgCgF59EL-KKOkOj5fv3f2LkjtEDGX4">

thanks for your reply. i do not understand why the error is correct.

**Comment by brc-dd** [comment]
> I do not understand why the error is correct.

Notice the first line `<p>hello <picture></p>` -- There is no closing tag for picture. (In other words, paragraph is closed before picture is closed.)

**Comment by yonecdeng** [comment]
> > I do not understand why the error is correct.
> 
> Notice the first line `<p>hello <picture></p>` -- There is no closing tag for picture. (In other words, paragraph is closed before picture is closed.)

Haha I know. I probably didn't make my point clear, I was trying to say that converting into this `<p>hello <picture></p> ` shouldn't be right and why would it be converted to `<p>hello <picture></p> `?

**Comment by brc-dd** [comment]
I'm not fully sure about that. But that's according to the CommonMark standard. We cannot adjust that here.
