### ISSUE TITLE
 can vitepress  use markdown  render into  mindmap

### ISSUE THREAD

**Issue by baixjian** [vuejs/vitepress#3643]
### Is your feature request related to a problem? Please describe.

like [markmap](https://github.com/markmap/markmap?tab=readme-ov-file)

### Describe the solution you'd like

---

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brenoepics** [comment]
You can use markmap with a [markdown-it plugin](https://github.com/NeroBlackstone/markdown-it-mindmap/) by adding in .vitepress/config.js but they require u to use css and js from a cdn or download it and add to your build, I don't like this idea but it is possible.
I'm willing to collaborate to make a web mindmap render that uses markdown for vue js/md-it

**Comment by brc-dd** [comment]
This should be done via some third-party plugin or theme. We won't be implementing this in core.
