### ISSUE TITLE
CSS bug

### ISSUE THREAD

**Issue by Mt-Youya** [vuejs/vitepress#3644]
### Describe the bug

content 部分没有 overflow:hidden 导致很长的滚动条(也有可能是我的图片太大?)

[github here](https://github.com/Mt-Youya/DeepLearning-500-questions)

[site here](https://deeplearning-500-questions.pages.dev/zh-cn/ch02_%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E5%9F%BA%E7%A1%80/%E7%AC%AC%E4%BA%8C%E7%AB%A0_%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E5%9F%BA%E7%A1%80.html)

### Reproduction

我fork 别人的仓库,不是我自己写的, 它原本用的是 docsify 我想提个pr用vitepress 试试,然后就出现了这个bug

### Expected behavior

没有滚动条

### System Info

```Text
Version 122.0.6261.112 (Official Build) (64-bit)
win11
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Try adding this to css:

```css
pre, mjx-container {
  overflow-x: auto;
}

mjx-container {
  margin-bottom: -8px;
}
```
