### ISSUE TITLE
Content disappeared after navigation (refresh on page or navigation accessing to page)

### ISSUE THREAD

**Issue by fr1g** [vuejs/vitepress#3649]
### Describe the bug

As my title, in my project, seems it happens every single time in production. Every time trying access to an article and then this issue came up with the should-be-displayed splashed for a second.

### Reproduction

Seems this issue only happened in mine.
In that case, to reproduce the issue, you need to access to https://kb.corona.studio/
and choose any article, and then try to refresh the page.
and you can also try to copy that page's address and try to access it in a new tab.

### Expected behavior

The article showed normally without a totally blank page after a splash.

### System Info

```Text
Github Pages:
Current runner version: '2.314.1'
Operating System
  Ubuntu
  22.04.4
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20240304.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240304.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240304.1
Runner Image Provisioner
  2.0.359.1
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  Pages: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Complete job name: report-build-status

my local test environment (not newest vitepress, no this issue.)

  System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1
    Memory: 106.94 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 10.1.0 - /usr/local/bin/npm
  Browsers:
    Safari: 17.1
  npmPackages:
    vitepress: ^1.0.0-alpha.45 => 1.0.0-alpha.45 

(wait, is this the newest? never did i update it manually.)
```

### Additional context

I apologize if this is caused by our misoperate during configuration. Visit https://github.com/Corona-Studio/CSKB_Hosting to check our configuration, if someone found something miserable and do have an idea to fix this, please tell me, I will be sincerely appreciated for your help.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fr1g** [comment]
ooooops I forgot to paste my system info, i will fix it soon

**Comment by fr1g** [comment]
okay my test environment is presented in my issue

**Comment by fr1g** [comment]
addi: I built and tried locally via vs-code live server and there's no issue like this. which means, this only happened in *our* github pages?

**Comment by brc-dd** [comment]
Are you using cloudflare in front of your site? Please disable auto-minify from cloudflare dashboard.

**Comment by fr1g** [comment]
> Are you using cloudflare in front of your site? Please disable auto-minify from cloudflare dashboard.

Upstream maintainer disabled that for project, and this do solved. But still I'm not understand what caused that? never did it happened before...

**Comment by brc-dd** [comment]
Auto-minify removes vue hydration comments. Refer the warning note here - https://vitepress.dev/guide/deploy#netlify-vercel-cloudflare-pages-aws-amplify-render

**Comment by fr1g** [comment]
> Auto-minify removes vue hydration comments. Refer the warning note here - https://vitepress.dev/guide/deploy#netlify-vercel-cloudflare-pages-aws-amplify-render

so that's the point! thank you for your reply!
