### ISSUE TITLE
Using codeblock with ts-vue skips syntax highlighting 

### ISSUE THREAD

**Issue by jnsmalm** [vuejs/vitepress#3650]
### Describe the bug

```
```ts-vue
{{ content }}
```

will render the content without syntax highlighting.

### Reproduction

Just add that code above anywhere.

### Expected behavior

That the code gets correctly syntax highlighted

### System Info

```Text
System:
    OS: macOS 14.3.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 102.78 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
    pnpm: 8.11.0 - ~/.nvm/versions/node/v18.11.0/bin/pnpm
    bun: 1.0.29 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.3.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's documented that it won't highlight it properly because that value is not available during markdown rendering.
