### ISSUE TITLE
Syntax for colored diffs/focus in code blocks incorrect for `lua`?

### ISSUE THREAD

**Issue by sharpchen** [vuejs/vitepress#3653]
### Describe the bug

Since `// [!code focus]` for c-like languages, `# [!code focus]` for py, ruby...
so I suppose `-- [!code focus]` is for lua, however `-- # [!code focus]` currently works instead and leave the `--` ahead.
And `# [!code focus]` works for SQL but `-- [!code focus]` doesn't

### Reproduction

See: https://stackblitz.com/edit/vite-v7jayd?file=docs%2Findex.md

### Expected behavior

The documentation doesn't mention such difference that we should use corresponding commenting syntax for different language, however `//` works for `xml`, `html`...

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: latest => 1.0.0-rc.45
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Actually a simple regex is used to parse that. Creating complete ASTs depending on the provided language is expensive.

Please create a feature request or PR at https://github.com/shikijs/shiki/issues -- You'll need to change this line https://github.com/shikijs/shiki/blob/593a2edd34d694f9f92984b6a3df52a5b01b1395/packages/transformers/src/transformers/notation-map.ts#L27

As you can see from the regex, the following comment patterns are recognized - `//` `/* */` `<!-- -->` `#`
