### ISSUE TITLE
Can sidebar has external links?

### ISSUE THREAD

**Issue by gantrol** [vuejs/vitepress#3656]
### Describe the bug

The external link in siderbar seems not work.

When I click the MarkdownCanDo button, the website jumps to `https://www.gantrol.com/en/software/https:/www.markdowncando.com/` instead of `https://www.markdowncando.com/`

![image](https://github.com/vuejs/vitepress/assets/31330732/73629d56-2045-4bff-94fd-4e6827aaaba5)

### Reproduction

I write [a blog website](https://www.gantrol.com/en/CS/examples) with vitepress ([github](https://github.com/gantrol/gantrol-blog))

### Expected behavior

Here is a PR that describes the feature, https://github.com/vuejs/vitepress/pull/1881

### System Info

```Text
"vitepress": "1.0.0-rc.45"

[config file](https://github.com/gantrol/gantrol-blog/blob/main/.vitepress/config/en.ts)
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You have specified base there.
