### ISSUE TITLE
Feature: export `<VPSwitch />` for better custom theme

### ISSUE THREAD

**Issue by peterroe** [vuejs/vitepress#3660]
### Is your feature request related to a problem? Please describe.

I noticed a closed pr: https://github.com/vuejs/vitepress/pull/2347/files

If someone want to implement it by himself, it can be helpful to use the exported component (VPSwitch)

### Describe the solution you'd like

```ts
import { VPSwitch } from 'vitepress/theme'
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
To implement that particular PR one doesn't need the VPSwitch component. Refer - https://vitepress.dev/guide/extending-default-theme#on-appearance-toggle

**Comment by peterroe** [comment]
I missed the documentation on this part, thanks for the reminder 🙏
