### ISSUE TITLE
The build process is stuck

### ISSUE THREAD

**Issue by aleversn** [vuejs/vitepress#3661]
### Describe the bug

The project was built successfully and completed, but the terminal just doesn't run continue, when I deploy on GitHub, the same issue makes the deployment process got stuck and won't run the next step. 

![QQ截图20240316205934](https://github.com/vuejs/vitepress/assets/30100324/b95b63e3-042a-4692-8b1a-e8f311dabb53)

### Reproduction

Please see our repos [VFluent3](https://stackblitz.com/~/github.com/Creator-SN/VFluent3)
Then run:

```bash
yarn docs:build
```

### Expected behavior

Please help me to resolve this issue and deploy the repo.

### System Info

```Text
https://github.com/Creator-SN/VFluent3/blob/3532c3298555c2662fe42e6da4861181a33d9114/docs/.vitepress/config.mts
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
One of your libraries is hanging the process. You'll need to check which libraries don't support SSR and import them dynamically inside onMounted hook.

**Comment by aleversn** [comment]
Thanks! We've resolved the issue.
