### ISSUE TITLE
Unable to build with project root above package directory

### ISSUE THREAD

**Issue by N0W0RK** [vuejs/vitepress#3667]
### Describe the bug

Trying to have the project root outside the package directory leads to build errors as node is unavailable.

### Reproduction

I have the following directory structure:
```text
.                          # document root
├─ .vitepress              # config dir & node root 
   ├─ config.mts
   ├─ package.json         # node Package config
   └─ ...
├─ en_US                   # documentation in english
   └─ ...                  # Markdown files and subdirectories
├─ de_DE                   # documentation in german
   └─ ...                  # Markdown files and subdirectories
```
Due to the nature of the project I am working on, vitepress has to run in a yarn workspace. The current location for the workspace using vuepress is in the `.vuepress` folder. The directory structure is analogue to the one above. When executing `npx vitepress build ..` in the `.vitepress` directory some imports cannot be resolved. I believe, this is due to code beeing executed in `.` where `vue is unavailable`.

Is there a way to solve this, or is it just not reasonable to have the node config below the document root. 

### Expected behavior

I would expect the code to be executed in the cwd and therefore all imports beeing available.

### System Info

```Text
OS: Manjaro Linux 6.6.19-1-MANJARO
node: v21.6.2
vue: 3.4.21
vitepress: 1.0.0-rc.45
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Most likely not any fix unless you install vitepress at root of your monorepo. Some setting of tempDir might also work, but not sure.
