### ISSUE TITLE
does not provide an export named 'defineEmit'

### ISSUE THREAD

**Issue by chengqiangwai** [vuejs/vitepress#367]
### Describe the bug

![image](https://user-images.githubusercontent.com/23628157/129451676-8b5775f5-4788-40c0-a36f-b0192f7d8f49.png)

does not provide an export named 'defineEmit'

### Reproduction

follow  the steps in getting started the problem reeproduce.
https://vitepress.vuejs.org/guide/getting-started.html

### Expected behavior

not error

### System Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 116.41 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    vitepress: ^0.15.6 => 0.15.6
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
Update vitepress

**Comment by chengqiangwai** [comment]
My version has been lastest 0.15.6. Update to what?
![image](https://user-images.githubusercontent.com/23628157/129469199-6b78978c-9844-40cd-82af-44306fffb98c.png)

**Comment by chengqiangwai** [comment]
@posva

**Comment by posva** [comment]
It doesn't, it's 0.16. This has already been fixed.

**Comment by chengqiangwai** [comment]
Thx for your response. But when i tried to install version 0.16, it suggests that there is not version 0.16. Its version list is  
![image](https://user-images.githubusercontent.com/23628157/129508893-6d512d67-e989-4668-af36-26fa6edc9714.png)
@posva
