### ISSUE TITLE
希望增加一个换算器

### ISSUE THREAD

**Issue by SO16532** [vuejs/vitepress#3670]
### Is your feature request related to a problem? Please describe.

希望增加一个换算器就是类似于wetab上面的那种，功能比较多
![617240526369a73dfa1604825503e77](https://github.com/vuejs/vitepress/assets/142719032/f7e3f995-6c3f-4dbf-9fab-f412a2398608)

### Describe the solution you'd like

希望增加一个换算器就是类似于wetab上面的那种，功能比较多 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What does this has to do with VitePress?
