### ISSUE TITLE
Vitepress is unable to build website when installed in workspace

### ISSUE THREAD

**Issue by N0W0RK** [vuejs/vitepress#3677]
### Describe the bug

When using vitepress in a yarn workspace, the build script erorrs. Depending on the setup, there are issues importing vue or even vitepress itself.

### Reproduction

```bash
mkdir -p monorepo/docs
cd monorepo
yarn init -2
echo "{\"name\": \"Monorepo\", \"packageManager\": \"yarn@4.1.1\",  \"workspaces\": [\"./docs\"]}" > package.json
echo "{\"name\": \"my-workspace\"}" > docs/package.json
yarn workspace my-workspace add -D vue vitepress
cd docs
npx vitepress init
cd ..
yarn workspace my-workspace docs:build
```

### Expected behavior

Clean build of the static website.

### System Info

```Text
OS: Manjaro Linux; 6.6.19-1-MANJARO 
node: v21.6.2
yarn: v4.1.1
vitepress: v1.0.0
vue: v3.4.21
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Add this to .vitepress/config:

```ts
import { defineConfig } from 'vitepress'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)

export default defineConfig({
  // ...

  vite: {
    resolve: {
      alias: {
        'vue/server-renderer': require.resolve('vue/server-renderer'),
        'vue': require.resolve('vue')
      }
    }
  }
})

```
