### ISSUE TITLE
Failure of  multi-language support

### ISSUE THREAD

**Issue by YoungX99** [vuejs/vitepress#368]
### Describe the bug

First of all, my English may not be good, please forgive me.
In the test of `vitepress@0.13.2` , multilanguage support worked. 
But when I upgraded `vitepress@0.16.1`, I `put the same directory configuration structure` into the framework, and when I started it, the page navigation bar didn't display properly.
In debug mode, the parameters associated with the locales cannot be seen.
Maybe I did something wrong, but my configuration item is exactly the same as @0.13.2, which is makes me confused, so I would like to ask if the configuration related to multilingual support has changed， and I suggest you check if there is any error.

### Reproduction

npm install vitepress.
npm run dev.
open the page at localhost.

### Expected behavior

In VitePress@0.13.2, The navigation bar is displayed correctly

![image](https://user-images.githubusercontent.com/61721885/129867338-f92f53a5-80e4-48d0-b983-ac9820483a97.png)
---
With the same configuration in VitePress@0.16.1, the navigation bar is not displayed, as shown in the following picture.

![image](https://user-images.githubusercontent.com/61721885/129868631-bd2e88ee-8932-46e0-aa74-5a9982cd1c51.png)
---
The personal configuration is shown in the following picture

![image](https://user-images.githubusercontent.com/61721885/129869142-c4f99e73-b70a-4c8d-8019-89850aaf9163.png)
---
In debug mode, the locale parameter is null
![image](https://user-images.githubusercontent.com/61721885/129869410-74c26eb7-c2bc-4088-9989-80ef2c2321dd.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 7.26 GB / 15.85 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.73)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    vitepress: ^0.16.1 => 0.16.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
This will be fixed at #353
