### ISSUE TITLE
Add i18n for CopyCode block

### ISSUE THREAD

**Issue by Lisio** [vuejs/vitepress#3695]
### Is your feature request related to a problem? Please describe.

CopyCode button caption, popup text and other stuff are hardcoded.

### Describe the solution you'd like

Make it configurable.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can [customize it via CSS](https://vitepress.dev/guide/extending-default-theme#customizing-css):

```css
:lang(zh) {
   --vp-code-copy-copied-text-content: '已复制'
}
```

**Comment by Lisio** [comment]
How can I customize this tooltip?
![image](https://github.com/vuejs/vitepress/assets/1868244/e1d63633-ff18-4b93-aced-7c542033ab0b)

**Comment by brc-dd** [comment]
Ah yeah. My bad. This is hardcoded.

**Comment by hestiacn** [comment]
How to customize copy code in existing project

**Comment by hestiacn** [comment]
> 如何自定义此工具提示？ ![image](https://private-user-images.githubusercontent.com/1868244/316337280-e1d63633-ff18-4b93-aced-7c542033ab0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzA4NTgsIm5iZiI6MTcxNDczMDU1OCwicGF0aCI6Ii8xODY4MjQ0LzMxNjMzNzI4MC1lMWQ2MzYzMy1mZjE4LTRiOTMtYWNlZC03YzU0MjAzM2FiMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTAwMjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjlhYzFlY2UzYmIwNDBiNjcxMTNiNDU1Yzg1ZTI5NGQ0YzUyYmU0MGVlNzNlYWI1NDA2YjFiNzIxYzg3ZWFiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lXF5IgMFnQagVx81KSvyBR3-8x6Bkirbfa37UVgYl6s)
How to customize copy code display characters in existing projects
