### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vitepress#37]
- Add playground with pages for different features
  - markdown syntax kitchen sink
  - $site / $page / $theme injections
  - default theme (test config options)
  - build
  - HMR
- Consult test setup for [Vite](https://github.com/vitejs/vite)

**Comment by kiaking** [comment]
We do have e2e test now, so, let's close this one. Maybe we should add more tests, but I think we can do that as we move forward.
