### ISSUE TITLE
Images from custom components are not working when running build

### ISSUE THREAD

**Issue by fractalf** [vuejs/vitepress#3700]
### Describe the bug

I have a custom component that renders an image for each markdown. It works fine running in dev, but not when building. VitePress does not detect it and copy it to the assets folder

### Reproduction

`VPDocHeader.vue`

```vue
<script setup>
import { useData } from 'vitepress/dist/client/theme-default/composables/data'
import { useRoute } from 'vitepress'

const { frontmatter: fm } = useData()
const route = useRoute()
</script>

<template>
    <div>
        <img class="rounded-t-xl" :src="route.path + (fm.image || 'banner.jpg')">
    </div>
</template>
```
`.vitepress/theme/index.js` (simplified for this example)

```js
import VPDocHeader from '../components/VPDocHeader.vue'
export default {
    Layout() {
        return h(DefaultTheme.Layout, null, {
            'doc-before': () => h(VPDocHeader),
        })
    },
}
```

When running this with `npm run dev` it is rendered out like this

```html
<img class="rounded-t-xl" src="/articles/001-vitepress-as-a-blog/banner.jpg">
```

### Expected behavior

I would expect VitePress to copy this to to assets etc when building

### System Info

```Text
Linux EndeavourOS
VitePress 1.0.1
NodeJs 21.7.1
```

### Additional context

I know I can probably solve this by rewriting to use `public/` ..but I would rather keep the images where the markdown files are.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That string is not statically analyzable. In dev it works because stuff outside public is also served and browsers resolve that during runtime. If you want it to work you'll either need to keep it in public or import that image and then pass it as prop. Importing in frontmatter is not supported though yet (it's planned but vite is missing certain public APIs).

**Comment by brc-dd** [comment]
> When you say "finterprinted", you are talking about the cache-bust string in the filename right?

Yeah. 

> This out of the box example also doesn't work then, event though it's in the documentation.

It's using `/cool-feature-icon.svg` -- base relative path -- which are for content inside public directory.

**Comment by fractalf** [comment]
Ok, cool, thanks.

I made a quick script to fix this, pasting it here for reference if anyone else has use for it

```js
// .vitepress/config.mjs
export default defineConfig({
    ..
    async buildEnd(siteConfig) {
        // Get each article (markdown with frontmatter data)
        const articles = await createContentLoader('/articles/**/*.md').load()
        for (const article of articles) {
            // article.url is the directory where I keep the images
            const image = article.frontmatter.image || 'banner.jpg'
            const src = __dirname + '/..' + article.url + image
            const dst = __dirname + '/dist' + article.url + image
            fs.copyFileSync(src, dst);
        }
    },
    ..
})
