### ISSUE TITLE
Hydration completed but contains mismatches

### ISSUE THREAD

**Issue by fractalf** [vuejs/vitepress#3702]
### Describe the bug

`Hydration completed but contains mismatches.`

![image](https://github.com/vuejs/vitepress/assets/5707457/fcc9674e-df81-4156-b7d2-7f30eae67f88)

First, yes I know there are already a few issues regarding this, but still I couldn't seem to find an answer to the problem. So I've gathered as much info as possible here to be used for debug.

Second, I know the meaning of the error. The rendered HTML differs on server/client.

This happens because of a markdown-it plugin I added.

I do not understand why the server and client would render two versions of the markup.

### Reproduction

This is a stripped down  version of the markdown file in question

```md
z

![](./vitepress-init.jpg)

y

![](./colours.png "Test")

x
```

This is the markdown-it plugin I added. It will use the "Test" title of the image and use it to make a caption under the image.

This works fine in dev mode.

```js
// .vitepress/config.mjs
..
markdown: {
    // Adding a markup-it plugin
    config: md => {
        const _super = md.renderer.rules.image
        md.renderer.rules.image = function (tokens, idx, options, env, self) {
            if (tokens[idx].attrs[2]) {
                const title = tokens[idx].attrs[2][1]
                const src = tokens[idx].attrs[0][1]
                const alt = tokens[idx].content
                return `
                    <figure>
                        <img src="${src}" alt="${alt}" title="${title}" />
                        <figcaption align="center">
                            <small style="opacity: 0.8">${title}</small>
                        </figcaption>
                    </figure>`
            }
            return _super(tokens, idx, options, env, self)
        }
    }
},
..
```

This is the **SERVER** rendered markup 
(or what I see when `CTRL+u`)

```html
<div>
    <p>z</p>
    <p><img src="/assets/vitepress-init.P2GuQSTo.jpg" alt="" /></p>
    <p>y</p>
    <p>
        <figure>
            <img src="/assets/colours.H7Z7cb1m.png" alt="" title="Test" />
            <figcaption align="center"><small style="opacity: 0.8;">Test</small></figcaption>
        </figure>
    </p>
    <p>x</p>
</div>
```

This is the **CLIENT**  rendered markup
(or what I see when I inspect in the browser `F12`)

```html
<div>
    <p>z</p>
    <p><img src="/assets/vitepress-init.P2GuQSTo.jpg" alt="" /></p>
    <p>y</p>
    <p></p>
    <figure>
        <img src="/assets/colours.H7Z7cb1m.png" alt="" title="Test" />
        <figcaption align="center"><small style="opacity: 0.8;">Test</small></figcaption>
    </figure>
</div>
```

So looks like the client has problems rendering. The `<figure>` should be inside the empty `<p>`, but it's not.

I couldn't find in the core code where the server and client did the actual rendering, so I couldn't debug this further.

Any help appreciated, thanks a lot

### Expected behavior

I would expect the server and client to render the same output

### System Info

```Text
Linux
VitePress v1.0.1
Node 21.7.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
figure inside paragraph tag is not valid HTML. p only allows flow elements.

**Comment by brc-dd** [comment]
Might be better to use some plugin like this https://github.com/Antonio-Laguna/markdown-it-image-figures instead of writing it yourself.

**Comment by fractalf** [comment]
Thanks again  Divyansh!

I spend most of the day digging deeper into this, 'cause I find it interesting, but yea seems like there is no "quick and easy" solution to this problem without using a plugin.

I tried out a lot of core-hacking markdown-it just to figure out how it works, but it was a deep rabbit hole.

I found out I'm not the only one who's had these thoughts:

* https://publishing-project.rivendellweb.net/customizing-markdown-it/
* https://github.com/markdown-it/markdown-it/issues/795

..anyway, I learned a lot, but still ended up using one of the plugins you mentioned.

I did a slight modification, for reference I paste it here

Thanks for your help!

```js
import imageFigures from 'markdown-it-image-figures'
..
export default defineConfig({
    ..
    markdown: {
        config: md => {
            // https://github.com/Antonio-Laguna/markdown-it-image-figures
            md.use(imageFigures, { figcaption: true })

            // https://github.com/markdown-it/markdown-it/blob/master/docs/examples/renderer_rules.md
            const proxy = (tokens, idx, options, env, self) => self.renderToken(tokens, idx, options)

            const defaultFigCaptionOpenRenderer = md.renderer.rules.figcaption_open || proxy;
            const defaultSmallOpenRenderer = md.renderer.rules.small_open || proxy;

            md.renderer.rules.figcaption_open = function(tokens, idx, options, env, self) {
                const small = new Token("small_open", "small", 1);
                small.attrs = [['style', 'opacity:0.8;']]
                return `${defaultFigCaptionOpenRenderer(tokens, idx, options, env, self)}${defaultSmallOpenRenderer([small], 0, options, env, self)}`;
            };

            const defaultFigCaptionCloseRenderer = md.renderer.rules.figcaption_close || proxy;
            const defaultSmallCloseRenderer = md.renderer.rules.small_close || proxy;
            md.renderer.rules.figcaption_close = function(tokens, idx, options, env, self) {
                const small = new Token("small_close", "small", -1);
                return `${defaultSmallCloseRenderer([small], 0, options, env, self)}${defaultFigCaptionCloseRenderer(tokens, idx, options, env, self)}`;
            };
        }
    },
```

**Comment by 2BAB** [comment]
> figure inside paragraph tag is not valid HTML. p only allows flow elements as children. Might be better to use some plugin like this https://github.com/arve0/markdown-it-implicit-figures or https://github.com/Antonio-Laguna/markdown-it-image-figures instead of writing it yourself.

Hi @brc-dd  I've tried both of them, they are all good when working in `:docs:dev`, but failed with `:docs:build`. The error does not contain any useful information to me, would like to seek your help on how to set them up. 

```
import implicitFigures from 'markdown-it-implicit-figures'
...
  markdown: {
    config: md => {
      md.use(implicitFigures, {
        figcaption: "alt",
        keepAlt: true,
      })
      // md.use(imageFigures, { 
      //   figcaption: "alt"
      //  })
    }
}    
```

<img width="753" alt="image" src="https://github.com/vuejs/vitepress/assets/5710495/623f51a0-461b-4fef-a2f6-4f22b87a2108">
