### ISSUE TITLE
previous / next error

### ISSUE THREAD

**Issue by moominka** [vuejs/vitepress#3703]
### Describe the bug

all but one prev / next links ok (defined in config.mts)

### Reproduction

            { text: "A", link: "/blah/page-0" },
            { text: "B", link: "/blah/page-1" },
            { text: "C", link: "blah/page-2" },
            { text: "D", link: "/blah/page-3" },
            { text: "E", link: "/blah/page-4" },

### Expected behavior

all link forwards and backwards, but if missing prepended / then only page 0,1,3,4 have correct next/prev linkages

the missing prepended / in config for 

blah/page-2 

means loading this page will produce only 

next page -> /blah/page-0

### System Info

```Text
irrelevant
```

### Additional context

n/a

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not a bug. Garbage in, garbage out.

**Comment by moominka** [comment]
true! <relevant-emoji/>

the reason I filled it was that regardless as to whether a relative link is used in the sidebar or not, the link is to the correct document location

        { text: "B", link: "/blah/page-2" },

-> //example.org/blah/page-2

        { text: "C", link: "blah/page-2" },

-> //example.org/blah/page-2

but the next / previous behaviour changes

It felt worth documenting in case someone else was scratching their head looking for their ‘picnic’ error.

Thank you for your work and prompt reply, much appreciated.
