### ISSUE TITLE
Can't install "No matching version found for @vue/devtools-kit@^7.0.25"

### ISSUE THREAD

**Issue by ovensi** [vuejs/vitepress#3714]
### Describe the bug

I use pnpm to install vitepress, pnpm add -D vitepress, the following message appears: 
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @vue/devtools-kit@^7.0.25

This error happened while installing the dependencies of vitepress@1.0.0
 at @vue/devtools-api@7.0.25

The latest release of @vue/devtools-kit is "7.0.24".

If you need the full list of all 25 published versions run "$ pnpm view @vue/devtools-kit versions".
Progress: resolved 12, reused 6, downloaded 0, added 0

### Reproduction

I use pnpm to install vitepress, pnpm add -D vitepress, the following message appears: 
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @vue/devtools-kit@^7.0.25

This error happened while installing the dependencies of vitepress@1.0.0
 at @vue/devtools-api@7.0.25

The latest release of @vue/devtools-kit is "7.0.24".

If you need the full list of all 25 published versions run "$ pnpm view @vue/devtools-kit versions".
Progress: resolved 12, reused 6, downloaded 0, added 0

### Expected behavior

Installation successful

### System Info

```Text
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1
    Memory: 461.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 123.0.6312.86
    Edge: 120.0.2210.133
    Firefox: 124.0.1
    Safari: 17.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Are you using a custom npm registry?

**Comment by ovensi** [comment]
> Are you using a custom npm registry?

Thank you for your reminder. The problem has been resolved😄
