### ISSUE TITLE
Uncaught ReferenceError: can't access lexical declaration 'K' before initialization

### ISSUE THREAD

**Issue by gander** [vuejs/vitepress#3717]
### Describe the bug

```
Uncaught ReferenceError: can't access lexical declaration 'K' before initialization
    vi https://preview-extend-template.gander-pl.pages.dev/assets/chunks/framework.v9o0AzEe.js:13
    <anonymous> https://preview-extend-template.gander-pl.pages.dev/assets/chunks/theme.DDSRElNe.js:1
framework.v9o0AzEe.js:13:10217
```

### Reproduction

+ https://github.com/gander/gander.pl/tree/preview/extend-template
+ https://github.com/gander/gander.pl/tree/preview/extend-template-inherit

`.vitepress/theme/index.js`
```js
import { h } from 'vue'
import DefaultTheme from 'vitepress/theme'
import Footer from "./Footer.vue";

export default {
    extends: DefaultTheme,
    Layout() {
        return h(DefaultTheme.Layout, null, {
            'layout-bottom': () => h(Footer)
        })
    }
}
```

`.vitepress/theme/Footer.vue`
```vue
<script setup>
const telemetryImg = import.meta.env.VITE_TELEMETRY_IMG;
</script>

<template>
  <div class="telemetry" v-if="telemetryImg">
    <img :src="telemetryImg" alt="">
  </div>
</template>

<style scoped>
.telemetry {
  text-align: center;
}
.telemetry img {
  display: inline-block;
  max-width: 66px;
}
</style>
```

### Expected behavior

Display image in footer

### System Info

```Text
System:
    OS: Linux 6.5 Linux Mint 21.3 (Virginia)
  Browsers:
    Chrome: 123.0.6312.86
  Cloudflare:
    Node: 20.5.1
    bun: 1.0.35
```

### Additional context

https://preview-extend-template.gander-pl.pages.dev/

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Seems like a circular reference. Which environment variables should be set locally to reproduce this? It's not reproducible by just cloning and building.

**Comment by gander** [comment]
@brc-dd 

```dotenv
VITE_TELEMETRY_IMG=https://up.gander.pl/telemetry/clnzoxcy10001vy2ohi4obbi0/cltzm76630002p94d9omanfh2/badge.svg
```

Occurs after deploy:
+ https://preview-extend-template.gander-pl.pages.dev/
+ https://preview-extend-template-inhe.gander-pl.pages.dev/

**Comment by brc-dd** [comment]
Still not reproducible:

<img width="1048" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/da5b94df-ad4e-471d-9ffe-9c59b49c068e">

Most likely is being caused by something else. Try disabling sentry once and re-deploying.

**Comment by gander** [comment]
Removed all Sentry code, and still occurs: https://preview-rid-sentry.gander-pl.pages.dev/

![obraz](https://github.com/vuejs/vitepress/assets/421597/1d79a6aa-0d16-4891-89b7-222c8a34d1b0)

**Comment by brc-dd** [comment]
I'm still seeing sentry stuff in your site 👀 

<img width="1014" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/b6bd1243-e8be-49c3-b814-6e6e6ce0f581">

**Comment by gander** [comment]
That's weird. This plugin should only be run while building, but I see it leaving a lot of baggage.

**Comment by gander** [comment]
This was definitely it. After restoring the normally working Sentry, but removing the Sentry Release plugin, it stopped throwing the error there. Thanks for the help!
