### ISSUE TITLE
v1.0.1 lastUpdated can't show

### ISSUE THREAD

**Issue by Shuaiqizheng** [vuejs/vitepress#3719]
### Describe the bug
lastUpdatedtime can't show in v1.0.1

related config.mts :

import { defineConfig } from 'vitepress'

export default defineConfig({
  lastUpdated: true ,
  themeConfig: {
    lastUpdated: {
      text: '最后更新于',
      formatOptions: {
        dateStyle: 'short',
        timeStyle: 'medium'
      }
    }
  }
})

### Reproduction

1

### Expected behavior

Please fix it！

### System Info

```Text
1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide a reproducible example. Your project should be a git repo and you should've committed your files for it to work.

**Comment by brc-dd** [comment]
It's showing fine 👀 

<img width="756" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/ac1d9360-8272-491b-85ae-bffbbf5243a4">

**Comment by brc-dd** [comment]
Yeah. I'm using 1.0.1. How are you building and previewing your project?
