### ISSUE TITLE
build error: TypeError: _ctx.a is not a function

### ISSUE THREAD

**Issue by Linhieng** [vuejs/vitepress#3728]
### Describe the bug

build error: TypeError: _ctx.a is not a function.

![image](https://github.com/vuejs/vitepress/assets/73024851/647e8b65-7c5a-48f5-9464-fbea5c6410a2)

### Reproduction

You can paste the follow txt in the markdown:

```md
$S_n = \frac{{a(1 - r^n)}}{{1 - r}}$
```

and you will recevied a build error.

But, other Math Equations can normally build, like:

```md
$S_N$
```

### Expected behavior

Normal output page, even if it does not render mathematical formulas.

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 6.04 GB / 15.37 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    vitepress: ^1.0.1 => 1.0.1
```

### Additional context

When I follow the step of [math-equations  - docs] the error disappeared. 

[math-equations  - docs]: https://vitepress.dev/guide/markdown#math-equations

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Linhieng** [comment]
You can see the detail in my [github action#3]: 

![image](https://github.com/vuejs/vitepress/assets/73024851/4b7b8d15-cf69-4ace-9d44-384a73a3d732)


[github action#3]: https://github.com/Linhieng/Lim-note-DSA/actions/runs/8491376723/job/23263288586

**Comment by brc-dd** [comment]
https://vitepress.dev/guide/using-vue#escaping 

You can add something like this if you don't want to use vue interpolation in inline code ever - https://github.com/vuejs/vitepress/discussions/3724#discussioncomment-8963669
