### ISSUE TITLE
Can support for meta keywords be added?

### ISSUE THREAD

**Issue by HappyLeiLei** [vuejs/vitepress#3733]
### Is your feature request related to a problem? Please describe.

I have modified the source code myself, but it needs to be customized again every time I upgrade. 
Hope to add support for meta keywords.

### Describe the solution you'd like

Tried to modify 7 files of the source code 
 as shown below
<img width="351" alt="image" src="https://github.com/vuejs/vitepress/assets/25144943/28299ecd-66d2-4c8e-aea4-73932e16caed">

### Additional context

[vitepress1.0.2（改造版-支持md 内使用 keywords）.zip](https://github.com/vuejs/vitepress/files/14831944/vitepress1.0.2.-.md.keywords.zip)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/frontmatter-config#head

**Comment by HappyLeiLei** [comment]
> https://vitepress.dev/reference/frontmatter-config#head

The original document has been updated, thank you very much.
