### ISSUE TITLE
useCopyCode Documentation

### ISSUE THREAD

**Issue by donnimsipa** [vuejs/vitepress#3734]
### Describe the bug

The Vitepress documentation lacks proper guidance on the usage of useCopyCode hook, which is essential for implementing copy-to-clipboard functionality in code blocks.

### Reproduction

1. Navigate to the Vitepress documentation site.
2. Look for documentation related to useCopyCode hook or copy-to-clipboard functionality.
3. Observe the absence of clear instructions or examples on how to use useCopyCode.

### Expected behavior

The Vitepress documentation should provide comprehensive guidance, including usage examples and explanations, for the useCopyCode hook, enabling users to easily implement copy-to-clipboard functionality in their projects.

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Pentium(R) CPU N4200 @ 1.10GHz
    Memory: 2.03 GB / 7.83 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    vitepress: ^1.0.0-rc.45 => 1.0.0-rc.45
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It’s not meant to be used externally and is tied to the DOM we generate for code fences. So, in a blank theme the copy code button should still work without any additional steps. What is your use case?

**Comment by donnimsipa** [comment]
I want to create something similar to useCopyCode directly within 'Custom Containers', but it seems that it's not feasible based on your explanation. Thank you for responding, and I will create a 'code' within 'Custom Containers' so that the 'copy code' appears instead of directly creating a copy button in 'Custom Containers'
