### ISSUE TITLE
More than one Output target !

### ISSUE THREAD

**Issue by aadrian** [vuejs/vitepress#3736]
### Is your feature request related to a problem? Please describe.

A VitePress "project" seems to have a single usage/purpose (per project) - e.g. MPA Site, or "online help" or "blog".

However this is not how documentation is mostly managed (well maybe except for demos) : there's **one set of documents** (e.g. Markdown content files) than will be used to produce **several outputs** from the **same** content: e.g. 
1. an online help (SPA or MPA) 
2. "single long page document" (for offline use, but split per language) , 
3. several PDFs (mostly per language split),   
4. Simple HTML files/fragments for contextual help inside the application (so no header/navigation/anchors ).

To achieve the above with VitePress, one would need several separate Projects that share the same Markdown content.

### Describe the solution you'd like

Have a "goal" or "target" section that would allow to configure inside the same project the issues mentioned above (even themes, base url,, etc. since they can different based on the output target).

### Describe alternatives you've considered

https://asciidoctor.org/  and other similar systems allow all the above, but with VitePress is not seem possible for now.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's currently out of scope for the project. VitePress will remain a SSG and as such can be used to generate MPAs.
