### ISSUE TITLE
Add "GitLab" to list of social icons

### ISSUE THREAD

**Issue by stritti** [vuejs/vitepress#3750]
### Is your feature request related to a problem? Please describe.

I would like to point to a repository at GitLab instead of GitHub.

### Describe the solution you'd like

Add social icon for GitLab to the list to be selectable at `themeConfic.socialLinks{}`

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by stritti** [comment]
Okay, thanks for alternative. Probably this is already documented and I have not seen this possibility.

**Comment by brc-dd** [comment]
refer the example - https://vitepress.dev/reference/default-theme-config#sociallinks

**Comment by stritti** [comment]
Oh, yes sure. I was blind. Sorry.
