### ISSUE TITLE
It is recommended to support Hong Kong Holidays

### ISSUE THREAD

**Issue by duhanmin** [vuejs/vitepress#3753]
### Is your feature request related to a problem? Please describe.

It is recommended to support Hong Kong Holidays

### Describe the solution you'd like

It is recommended to support Hong Kong Holidays

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Wrong repo.
