### ISSUE TITLE
can't be with `@unocss/transformer-variant-group`

### ISSUE THREAD

**Issue by Skiyee** [vuejs/vitepress#3754]
### Describe the bug

````
```ts
const unocss = 'vitepress:(unocss)'
```
````
with `@unocss/transformer-variant-group` generate 👇
```
const unocss = 'vitepress:unocss'
```
should generate 👇
```
const unocss = 'vitepress:(unocss)'
```

### Reproduction

https://stackblitz.com/edit/vite-rggqvj?file=docs%2F.vitepress%2Fvite.config.ts,docs%2F.vitepress%2Funo.config.ts,docs%2Fexample.md

### Expected behavior

```ts
const unocss = 'vitepress:(unocss)'
```

### System Info

```Text
System: os: window-11
Binaries: pnpm: 8.15.3
npmPackages: vitepress: 1.0.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not a vitepress bug. That plugin is modifying the code, vitepress is just rendering what it gets.
