### ISSUE TITLE
Broken sidebar when loading page

### ISSUE THREAD

**Issue by florian-sattler** [vuejs/vitepress#3756]
### Describe the bug

First of all: Thank you all very much for your work on this amazing software! 👍 

When navigating to page using a direkt link the sidebar overlap the content of the page:

![image](https://github.com/vuejs/vitepress/assets/65666934/726ef0a4-950f-4f87-bb57-f5b304b07416)

However when accessing the page from the main page, everything looks normal:

![image](https://github.com/vuejs/vitepress/assets/65666934/d9fce76e-ed50-4f93-ba97-a9d2440c6df6)

The problem seems to be caused by a missing class on two elements. Take a look at the developer console:

Broken:
![image](https://github.com/vuejs/vitepress/assets/65666934/02333a4d-2617-4911-ac00-a138d3d102c5)

Working:
![image](https://github.com/vuejs/vitepress/assets/65666934/70f7ad5a-2f94-4705-aaaa-ffd41cac2794)

Notice how the class `.has-sidebar` is missing on the first (`.VPLocalNav`) and third element (`#VPContent`) below the header (`.VPNav`)

When manually adding this class in the browers dev tools the site looks normal again 😄 

### Reproduction

See above.

### Expected behavior

The sidebar should be located on the side not above the page content.

### System Info

```Text
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 12.23 GB / 15.61 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Chrome: 123.0.6312.105
  npmPackages:
    vitepress: ^1.0.2 => 1.0.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It seems like a hydration mismatch. Can you share this using a repo or https://vitepress.new

**Comment by mikeboe** [comment]
Same for me, when you go on the nested page through the link directly, the layout breaks. When you go through the home page, the layout is correct. Using 1.0.2. Strangely, happens only in production in docker for me, in dev and with preview locally it seems fine.

**Comment by brc-dd** [comment]
@mikeboe Can you share the link where you've hosted it?

**Comment by mikeboe** [comment]
Can I share somewhere privately? It's still WIP

**Comment by brc-dd** [comment]
> Can I share somewhere privately?

Yeah I'm on [discord](https://chat.vuejs.org/) (#vitepress channel).

Looks like your server is serving home page for all pages. How are you hosting your site? Have you added some rewrite rule or something?

**Comment by mikeboe** [comment]
You're right, I have an error in nginx configuration, now it works. Thanks man.

**Comment by florian-sattler** [comment]
I'm also running an Nginx stack. This could very well be the problem. I will investigate this and get back to you.

Would it make sense to add a 'docker' section to the [deployment section](https://github.com/vuejs/vitepress/blob/main/docs/guide/deploy.md)  of the docs? I imagine other people might also run this page inside a container. I would be happy to create a pull request with a first draft of the new section.

**Comment by mikeboe** [comment]
This did the job for me: [add nginx config example #3235](https://github.com/vuejs/vitepress/issues/3235#issuecomment-1869655412). I was missing `$uri.html` in the nginx conf.

```
server {
    listen 80;
    location / {
        root /app/build;
        index index.html;
        try_files $uri $uri/ $uri.html =404;
    }
}
```

**Comment by florian-sattler** [comment]
I can confirm this is a nginx issue. I erroneously served `index.html` as a backup, which in turn loaded the article with the wrong page initialization as described above.

**Comment by florian-sattler** [comment]
@brc-dd Should I propose a docs section?

**Comment by brc-dd** [comment]
Yeah, contributions are welcome. Thanks!

 Just add Nginx's routing related config there. Other stuff and dockerfile, etc. is probably not needed. You can pick whatever works best from this thread or #3235 or #2837.
