### ISSUE TITLE
rewrite URL got 404 in build mode

### ISSUE THREAD

**Issue by hyunicode** [vuejs/vitepress#3766]
### Describe the bug

my rewrite rules are as follow, it works fine on dev mode, but url is not automatically converted on build mode. I can change the url manually and it does work, I am looking for a more efficient way.
`  rewrites: {
    'src/components/:pkg/docs/(.*)': ':pkg/index.md',
  },
`

### Reproduction

`  rewrites: {
    'src/components/:pkg/docs/(.*)': ':pkg/index.md',
  },
`

npm run docs:build ans see if the target url automatically converted.

### Expected behavior

url behaviour should be the same between build mode and dev mode

### System Info

```Text
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.29 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.107
    Edge: 123.0.2420.81
    Safari: 17.4.1
  npmPackages:
    vitepress: ^1.0.2 => 1.0.2
```

### Additional context

Some related discussions... but I didn't find a solution
https://github.com/vuejs/vitepress/pull/1798
https://github.com/vuejs/vitepress/issues/2276
https://github.com/vuejs/vitepress/pull/2301
https://github.com/vuejs/vitepress/issues/3062
https://github.com/vuejs/vitepress/discussions/3198

### Validations

- [x] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please share a reproducible example in form of a github repo or using https://vitepress.new

**Comment by hyunicode** [comment]
https://github.com/hyunicode/vitepress_demo
0. git clone git@github.com:hyunicode/vitepress_demo.git
1. yarn
2. yarn docs:build
3. yarn docs:preview 
4. click nav 'click here'

**Comment by brc-dd** [comment]
It's expected behavior. You need to reference using final URLs. Make it `{ text: 'click here', link: '/examples/' }`.

**Comment by hyunicode** [comment]
> It's expected behavior. You need to reference using final URLs. Make it `{ text: 'click here', link: '/examples/' }`.

In my opinion, the behavior in dev mode should be consistent with that in prod mode. Maybe all 404 can remind developers to modify their rewrite rules
