### ISSUE TITLE
当md文档中出现`{{`，会编译报错

### ISSUE THREAD

**Issue by yangdong520** [vuejs/vitepress#3778]
### Describe the bug

当md文档中出现`{{`，会编译报错

### Reproduction

当md文档中出现`{{`，会编译报错

### Expected behavior

正常显示

### System Info

```Text
node 18.17.0
"vitepress": "^1.0.2"
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's by design. Refer #480 for workaround.
