### ISSUE TITLE
Vitepress supports the use of plugins?

### ISSUE THREAD

**Issue by yyq-bit** [vuejs/vitepress#378]
### Is your feature request related to a problem? Please describe.

 I want to use the image enlargement function in vitepress, which is similar to vuepress plugin - @ vuepress / medium zoom

### Describe the solution you'd like

I hope VitePress can support the use of plugins

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by antfu** [comment]
Yes, just create `vite.config.js`

**Comment by antfu** [comment]
Yes, just create `vite.config.js`
