### ISSUE TITLE
希望支持 LaTeX3 语法高亮

### ISSUE THREAD

**Issue by xkwxdyy** [vuejs/vitepress#3781]
### Is your feature request related to a problem? Please describe.

希望官方能支持 LaTeX3 语法（expl3）高亮。

我尝试了 shiki 官网的[方法](https://shiki.tmrs.site/guide/load-lang)
按照它的配置在`.vitepress/config.mts` 中加入了
```
import { getHighlighter } from 'shiki'

const latex3 = JSON.parse(fs.readFileSync('../../LaTeX-Expl3.tmLanguage.json', 'utf8'))

const highlighter = await getHighlighter({
  langs: [latex3],
  themes: ['vitesse-light']
})

const html = highlighter.codeToHtml(code, {
  lang: 'my-lang',
  theme: 'vitesse-light'
})
```
但是 VScode 提示我
```
找不到名称“fs”。
找不到名称“code”。
```

我没有什么 ts 代码基础，不知道怎么改。但是 LaTeX3 用得也很普遍，所以希望官方能够支持，这样就不需要我额外配置了。

### Describe the solution you'd like

调用 VScode 的 [LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/LaTeX-Expl3.tmLanguage.json) 里的高亮就行

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Refer #3779
