### ISSUE TITLE
Show an error when "{}" appears in the markdown table 

### ISSUE THREAD

**Issue by fxbsujay** [vuejs/vitepress#3782]
### Describe the bug

vitepress version: 1.1.0

Show an error when {} appears in the table

![TEST01](https://github.com/vuejs/vitepress/assets/92838931/92ee2512-93d5-4842-82d9-6d9c1e4ddb9a)
![TEST02](https://github.com/vuejs/vitepress/assets/92838931/414123d9-6d06-4f0f-b6f6-7d1cf7e10aec)
![TEST03](https://github.com/vuejs/vitepress/assets/92838931/94d43c91-a67f-46de-a59a-24ba983f2297)

### Reproduction

Error occurs if "{}" or "{n}" appears in the table

### Expected behavior

![1712815636948](https://github.com/vuejs/vitepress/assets/92838931/b91d417b-3006-453a-ad7e-ac68a5ad78f6)

### System Info

```Text
Browsers:
    Google Chrome 123.0.6312.106 (64)
  npmPackages:
    vitepress: ^1.1.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah because it should be wrapped with backticks (\`). Other alternative is to set `markdown.attrs` to `false`. Or maybe escape them `\\{` `\\}`. Or maybe change attrs' delimiters to something other than `{}`
