### ISSUE TITLE
fix directory 404

### ISSUE THREAD

**Issue by fjun99** [vuejs/vitepress#3788]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

Take https://abc.com/tutorial/ as an example: 

- if there is an "index.md", https://abc.com/tutorial/ is ok.

- but https://abc.com/tutorial is 404

Can we let https://abc.com/tutorial redirect to https://abc.com/tutorial/ by default.

Thanks.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
How are you hosting your app?

**Comment by fjun99** [comment]
> How are you hosting your site?

I host my site on vercel.

**Comment by brc-dd** [comment]
In prod (`vitepress preview`) it should work fine. Fixing this in dev was explored earlier but was bit complex. If it's not working for you in deployed version, you probably need to configure vercel.

**Comment by fjun99** [comment]
> In prod (`vitepress preview`) it should work fine. Fixing this in dev was explored earlier but was bit complex. If it's not working for you in deployed version, you probably need to configure vercel.

thanks
