### ISSUE TITLE
build: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by DvShu** [vuejs/vitepress#3789]
### Describe the bug

When I run `npm run docs:build`, I get the error: ReferenceError: document is not defined

### Reproduction

If there is anything about node manipulation in my code, it will report an error. egg: document、DOMParser

### Expected behavior

When I run npm `run docs:dev` its fine! But when i run npm run `npm run docs:build` i got the error.

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
    Memory: 4.36 GB / 15.83 GB
  Binaries:
    Node: 21.7.1 - D:\developer tool\nodejs\node.EXE
    Yarn: 1.22.19 - D:\developer tool\nodejs\yarn.CMD
    npm: 10.5.0 - D:\developer tool\nodejs\npm.CMD
    pnpm: 8.15.6 - D:\developer tool\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.22621.1
```

### Additional context

![1713093865913](https://github.com/vuejs/vitepress/assets/10515836/3d426db7-0b3b-4bdb-ab7c-46b4e9858ee6)
![1713093899031](https://github.com/vuejs/vitepress/assets/10515836/8a53ba1b-592c-492d-8a76-9f1be61130f4)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/guide/ssr-compat
