### ISSUE TITLE
Font face 'Chinese Quotes' causes extra space between English letters

### ISSUE THREAD

**Issue by shadow-light** [vuejs/vitepress#3790]
### Describe the bug

A custom font-face [was added to VitePress](https://github.com/vuejs/vitepress/commit/81ae1c79cd1c0c9c31f48100f131715efc68efbd) to fix rendering issues for quotes in Chinese, but this has inadvertently caused rendering issues in English (and possibly other languages).

Curly apostrophes are particularly affected as `Can’t` turns into `Can’  t`, because the spacing of the apostrophe is much larger in some Chinese fonts. This happens on systems that default to the SimHei local font and possibly others.

### Reproduction

Add curly quotes between letters (or enable `typographer` for Markdown)

https://stackblitz.com/edit/vite-jhejpq?file=docs%2Findex.md,docs%2F.vitepress%2Fconfig.ts

But it will only reproduce when the system defaults to the SimHei font (Windows I think). 

![image](https://github.com/vuejs/vitepress/assets/42055707/87176e76-7ddb-4eea-9589-f2a9073e55ef)

### Expected behavior

Curly quotes should not take any extra space than needed.

### System Info

```Text
Reproduced on Windows systems where the local font used is SimHei.
```

### Additional context

I assume reverting this behaviour would negatively affect Chinese users, so I'll leave it to the discretion of the maintainers as to whether it should be reverted or not. It was very difficult to identify the problem though, so documenting it would at least be helpful so other users know to override the behaviour themselves.

Manually overriding `--vp-font-family-base` is a workaround.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Instead of reverting, it can be made smarter I guess. Maybe add that inside `:lang(zh), :lang(ja), :lang(ko)` selector 👀
