### ISSUE TITLE
Vitepress dose not generate sitemap with directories:doc

### ISSUE THREAD

**Issue by virskor** [vuejs/vitepress#3799]
### Describe the bug

after migrate package.json
```json
"directories": {
    "doc": "records"
  },
```
sitemap generate with sitemap.hostname but not add /records after host name

### Reproduction

sitemap.xml

### Expected behavior

loc shoud be http://test.com/records/ok.html not http://test.com/ok.html

### System Info

```Text
"vitepress": "^1.1.0"
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to set base - https://vitepress.dev/reference/site-config#base

`directories.doc` is probably some non-standard thing which vitepress doesn't recognize
