### ISSUE TITLE
Fail to start server. error: On new installation following Getting started guide.

### ISSUE THREAD

**Issue by MakerDockio** [vuejs/vitepress#380]
### Describe the bug

Failure to start server error after new installation / setup following 'Getting Started' Steps on https://vitepress.vuejs.org/guide/getting-started.html 

```
vitepress v0.17.0
vite v2.5.3
failed to start server. error:
 TypeError: Cannot destructure property 'locales' of 'siteData.themeConfig' as it is undefined.
```

### Reproduction

1. Run `mkdir vitepress-starter && cd vitepress-starter`
2. Run `npm init`
3. Run `npm i --dev vitepress`
4. Run `mkdir docs && echo '# Hello VitePress' > docs/index.md`
5. Add following to package.json`{"scripts": {"docs:dev": "vitepress dev docs", "docs:build": "vitepress build docs", "docs:serve": "vitepress serve docs"}}`
6. Run `npm run docs:dev`

### Expected behavior

Expect dev server to run

### System Info

```shell
Not applicable
OSX
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by MakerDockio** [comment]
To save any doubt I tried the with Yarn with the same resulting error.

**Comment by posva** [comment]
Okay te fix will be in the next release

**Comment by mfw78** [comment]
This absolutely should not be closed until the fix is actually done.

**Comment by thomasklemm** [comment]
Seeing the same error when following the [Getting Started](https://vitepress.vuejs.org/guide/getting-started.html) docs with vitepress 0.17.0.

```
➜  yarn docs:dev

yarn run v1.22.11
$ vitepress dev docs
vitepress v0.17.0
vite v2.5.3
failed to start server. error:
 TypeError: Cannot destructure property 'locales' of 'siteData.themeConfig' as it is undefined.
    at Object.createLangDictionary (/Users/thomasklemm/Code/Librarian/vue-ui-frameworks/node_modules/vitepress/dist/node/shared.js:27:13)
    at resolveSiteData (/Users/thomasklemm/Code/Librarian/vue-ui-frameworks/node_modules/vitepress/dist/node/config.js:80:25)
    at Object.resolveConfig (/Users/thomasklemm/Code/Librarian/vue-ui-frameworks/node_modules/vitepress/dist/node/config.js:25:24)
    at async Object.createServer (/Users/thomasklemm/Code/Librarian/vue-ui-frameworks/node_modules/vitepress/dist/node/server.js:8:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ydcjeff** [comment]
Here's a workaround: https://github.com/vuejs/vitepress/issues/379#issuecomment-910231391

**Comment by thomasklemm** [comment]
@ydcjeff Perfect, that works, thanks for the hint!
