### ISSUE TITLE
Add built-in OpenCollective support to socialLinks

### ISSUE THREAD

**Issue by ST-DDT** [vuejs/vitepress#3809]
### Is your feature request related to a problem? Please describe.

Receiving donations is one of the hardest problems for small projects/sites.

### Describe the solution you'd like

Having a `OpenCollective` link on the page hopefully helps with that (even if very little)

A SVG for that can be found here: https://github.com/simple-icons/simple-icons/blob/develop/icons/opencollective.svg

### Describe alternatives you've considered

Manually add the OpenCollective link to the list.

- https://github.com/faker-js/faker/pull/2806

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Ah, we are trying to avoid adding new icons to the core because they can't be tree shaken and end up in the bundle for every one (even if they aren't using it). If this issue gets significant upvotes we would add it, but until then I'd recommend using icon from https://simpleicons.org (and optionally pass it via svgo):

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12c2.54 0 4.894-.79 6.834-2.135l-3.107-3.109a7.715 7.715 0 1 1 0-13.512l3.107-3.109A11.943 11.943 0 0 0 12 0zm9.865 5.166-3.109 3.107A7.67 7.67 0 0 1 19.715 12a7.682 7.682 0 0 1-.959 3.727l3.109 3.107A11.943 11.943 0 0 0 24 12c0-2.54-.79-4.894-2.135-6.834z"/></svg>
```
