### ISSUE TITLE
Allow relative path for assets / scripts in out index.html

### ISSUE THREAD

**Issue by leopsidom** [vuejs/vitepress#381]
### Is your feature request related to a problem? Please describe.

I'm using vitepress in an existing project for documentation, and I want to keep the docs build in a separate directory for instance:

```
docs
  - assets
    - xxx.js
  - index.html
src
  - App.vue
```

But I can't load `/docs/index.html` since the assets use an absolute url `/assets/xxx.js`.

### Describe the solution you'd like

Can we allow relative url in the `index.html` so that when loading `docs/index.html` it's still working ?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by leopsidom** [comment]
I think I figured out, Just need to specify `base` in the `config.js`.

**Comment by Jackie1210** [comment]
@leopsidom I have meet the same case. But when i set `base` to `./` instead of `/`,  router will be different.How did you fix it?
