### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by andim27** [vuejs/vitepress#3812]
### Describe the bug

If deploy from local Mac - all is ok
But if deploy(from docker CI GitLab) - error in rollup package
![deploy_vitepress_error](https://github.com/vuejs/vitepress/assets/4599713/d0d532fc-4c14-4d73-a08d-da68033f90e6)

### Reproduction

`npm run docs:build`

### Expected behavior

No error is needed

### System Info

```Text
Running with gitlab-runner 16.11.0~pre.21.gaa21be2d (aa21be2d)
  on blue-4.saas-linux-small-amd64.runners-manager.gitlab.com/default
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
NPM issue. You might need to manually rollup to your deps -  https://github.com/npm/cli/issues/4828#issuecomment-2065690643
