### ISSUE TITLE
Hero section image error

### ISSUE THREAD

**Issue by andim27** [vuejs/vitepress#3813]
### Describe the bug

Hero image don't bind after deployment If place logo.png to /images it does not work.
This image does not compile to the assets and on real site can't get image.Please fix

### Reproduction

Set hero section
Set  image:
    src: logo.png

### Expected behavior

Should  can place logo(any images) to images directory

### System Info

```Text
after deploy
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to keep it inside public directory.
