### ISSUE TITLE
Problems with uploading the _commonjsHelpers.XXXXXX.js file generated in the assets folder to Github Pages

### ISSUE THREAD

**Issue by davay42** [vuejs/vitepress#382]
### Describe the bug

I use Github pages for hosting my site and I can't make the file _commonjsHelpers.b8add541.js get deployed there. It's just ignored during the upload. I've found that putting a `.nojekyll` file into the root of the site may help prevent github pages deleting the files and folders with underscores, but this doesn't help either. Deleting the branch and deploying it again also has no effect too.

Seems like this file is generated for loading commonJS packages and so it crashes loading only the pages that use modules like that. 

### Reproduction

my deploy script
```
cd .vitepress/dist

git init
git add -A --force
git commit -m 'deploy'

git push -f git@github.com:chromatone/chromatone.center.git master:gh-pages

cd -
```

I've added --force to git add but it doesn't help.

### Expected behavior

May be this supplementary file may be named without underscores - this may help avoiding such problems.

### System Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 996.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 91.0.2
    Safari: 14.1.2
  npmPackages:
    vitepress: 0.17.0 => 0.17.0
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yyx990803** [comment]
https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
