### ISSUE TITLE
支持 Markdown 动态渲染

### ISSUE THREAD

**Issue by linpengteng** [vuejs/vitepress#3829]
### Is your feature request related to a problem? Please describe.

例如:
- 当我部署在 github 渲染显示如下内容

  ```md
     git clone https://github.com/username/xxxx.git
  ```

- 当我部署在 gitee 渲染显示如下内容

  ```md
     git clone https://gitee.com/username/xxxx.git
  ```

### Describe the solution you'd like

Support:

<pre>
  ```md {render=window.location.href.start('https://github.com')}
     git clone https://github.com/username/xxxx.git
  ```
</pre>

<pre>
  ```md {render=window.location.href.start('https://gitee.com')}
     git clone https://gitee.com/username/xxxx.git
  ```
</pre>

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That needs too much of architecture change and SSR won't work for those parts defeating the main purpose of VitePress.

You can use something like this instead: https://vitepress.dev/guide/using-vue#unescape-in-code-blocks

````html

```sh-vue
git clone {{ gitUrl }}
```

<script setup lang="ts">
import { onMounted, ref } from 'vue'

const gitUrl = ref('')

onMounted(() => {
  if(window.location.href.start('https://gitee.com') {
    gitUrl.value = 'https://gitee.com/username/xxxx.git'
  } else {
    gitUrl.value = 'https://github.com/username/xxxx.git'
  }
})
</script>
````

**Comment by linpengteng** [comment]
thank you, it is worked.
