### ISSUE TITLE
Assets referenced in frontmatter are not resolved

### ISSUE THREAD

**Issue by reza-akbari** [vuejs/vitepress#383]
### Describe the bug

when you do `![...](./foo/bar.png)` on `build` it will get resolved to something like `/assets/bar.[hash].png`

but when you do 
```
---
image: ./foo/bar.png
---
```

the `image` property on frontmatter is not converted to the real url.

### Reproduction

1. create a markdown
2. reference an image in frontmatter

```md
---
image: ./foo/bar.png
---

<script setup>
  import { useData } from 'vitepress';
  const { frontmatter: page } = useData();
</script>

<img :src="page.image">
```
3. image works on `dev` but on `build` it won't get resolved like when you do `![...](./foo/bar.png)`

### Expected behavior

There should be a way to get a working url of the image

### System Info

```shell
System:
    OS: Linux 5.4 Alpine Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 1.05 GB / 5.80 GB
    Container: Yes
    Shell: 1.32.1 - /bin/ash
  Binaries:
    Node: 16.8.0 - /usr/local/bin/node
    npm: 7.21.0 - /usr/local/bin/npm
  npmPackages:
    vitepress: ^0.16.1 => 0.16.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by reza-akbari** [comment]
Also I use `gray-matter` to generate metadata of all markdown files. 
Is there a way to get the real url of assets manually?
```js
const { data } = require('gray-matter')(mdFileContent);
data.image  // <= this is "./foo/bar.png"

// How to get the real url "/assets/bar.[hash].png" here?
```
Thanks 🙏

**Comment by yyx990803** [comment]
You cannot use relative assets in frontmatter, it's just static data. You can just do `<img src="./foo/bar.png">`.

If you need image URLs elsewhere, put them in `<root>/public/` and reference using absolute paths.

**Comment by kaceo** [comment]
Relative assets is used everywhere inside a document, it should be possible for Vitepress to bundle them whether specified as Markdown, frontmatter or Vue. 

But currently Vitepress only handle Markdown, not frontmatter or Vue.

E.g. The relative asset (pix1.png) is bundled and hashed in basic Markdown
~~~md 
<!-- index.md -->
![a picture](./pix1.png)
~~~

But in a custom Vue image component used inside Markdown it does not bundle the asset
~~~md 
<!-- index.md -->
<Photo src="./pix1.png" />
~~~

~~~vue
<!-- Photo.vue -->
<script setup>
import {useBase} from "vitepress";
const props = defineProps({
  src: String
})
</script>
<template>
img( :src="withBase(src)" )
</template>
~~~

This is not a consistent behaviour and makes custom widgets usage different from basic markdown.
