### ISSUE TITLE
The custom rainbow theme of the UNOCSS.DEV document has different display effects under different links

### ISSUE THREAD

**Issue by artsmp0** [vuejs/vitepress#3845]
### Describe the bug

When updated to the latest version of Edge, that is, the version 124.0.2478.67 (formal version) (ARM64), Rainbow Color can take effect on some links, which is not good. 

When I use ARC browser, it is displayed normally, and itsBased on Chromium Version 123.0.6312.123 (official version) (ARM64)

preview: 
![image](https://github.com/vuejs/vitepress/assets/129932371/2b4ab84d-ad08-4525-9fa5-179a11241c70)

source: 
<img width="1001" alt="image" src="https://github.com/vuejs/vitepress/assets/129932371/d88162da-0de1-4513-acaf-47ddd6bf4fa1">

### Reproduction

https://github.com/artsmp0/vp-rainbow-theme-reproduction

### Expected behavior

Hope that the link color is normal

### System Info

```Text
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 53.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/Library/Caches/fnm_multishells/71289_1714466899919/bin/node
    Yarn: 1.22.22 - ~/Library/Caches/fnm_multishells/71289_1714466899919/bin/yarn
    npm: 10.5.0 - ~/Library/Caches/fnm_multishells/71289_1714466899919/bin/npm
    pnpm: 9.0.6 - ~/Library/Caches/fnm_multishells/71289_1714466899919/bin/pnpm
  Browsers:
    Edge: 124.0.2478.67
    Safari: 17.4
```

### Additional context

Refer to the rainbow gradient color effect of the unocss.dev documentation

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It appears to be a Chromium bug. It's not working for me on Arc too, but seems to work fine on latest stable version of Chrome, Firefox and Safari. Can you try upgrading Edge and see if this codepen works fine - https://codepen.io/divyansh_singh/pen/zYXgxbp (it shouldn't show you external link as black).
