### ISSUE TITLE
How to modify the copy code characters to Chinese. Thanks to all developers!

### ISSUE THREAD

**Issue by hestiacn** [vuejs/vitepress#3857]
### Is your feature request related to a problem? Please describe.

How to modify the copy code characters to Chinese. Thanks to all developers!

### Describe the solution you'd like

How to modify the copy code characters to Chinese. Thanks to all developers!

### Describe alternatives you've considered

How to modify the copy code characters to Chinese. Thanks to all developers!

### Additional context

How to modify the copy code characters to Chinese. Thanks to all developers!

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by hestiacn** [comment]
![030529](https://github.com/vuejs/vitepress/assets/138613406/bb918824-916a-4859-ac71-0c47e5576a20)

**Comment by userquin** [comment]
duplicated #3695

**Comment by hestiacn** [comment]
How to customize copy code in existing project
