### ISSUE TITLE
Dynamic `titleTemplate` needed

### ISSUE THREAD

**Issue by boxsnake** [vuejs/vitepress#3860]
### Is your feature request related to a problem? Please describe.

In my case, I want make different `titleTemplate` for different route patterns.

For example, I have `/guide` and `/faq`. I want to use `:title | A` for `/guide` and `:title | B` for `/faq`.

### Describe the solution you'd like

Two optional solutions:

1. Expose a build hooks, which allows users to access `pageData` and / or `siteConfig` before build stage.
2. Allow `titleTemplate` in `config.js` (`config.ts`) to use a function to generate template string according to `pageData` and `siteConfig`.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/site-config#transformpagedata

**Comment by boxsnake** [comment]
@brc-dd 

I tried `transformPageData` to change frontmatter's `titleTemplate`, but the page's `<title>` label didn't display as expected.

**Comment by boxsnake** [comment]
By the way, the doc didn't state the differences between outer `titleTemplate` and the one in `frontmatter` object.

Hope this can be updated in the doc.

Thanks.
