### ISSUE TITLE
sitemap generation does not include base url

### ISSUE THREAD

**Issue by biscuit314** [vuejs/vitepress#3863]
### Describe the bug

Setting both base: and sitemap: in the site config does not work as expected.  The hostname value in the sitemap config is used, but all paths exclude the base: path.  Adding the additional path to hostname does not fix the issue.

### Reproduction

Configure a site with the following:
```javascript
export default defineConfig({
    base: '/path/',
    sitemap: {
        hostname: 'https://example.org'
    }
})
````
### Expected behavior

The sitemap generated from the above should all begin with `https://example.org/path/...` but instead the /path/ part is missing.

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
    Memory: 4.55 GB / 15.72 GB
  Binaries:
    Node: 20.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It should be `hostname: 'https://example.org/path/'`
