### ISSUE TITLE
Favicon not found when base is set by command line

### ISSUE THREAD

**Issue by mikigo** [vuejs/vitepress#3869]
### Describe the bug

```js
// .vitepress/config.ts

head: [
        base: '/youqu/',
        ['link', {rel: 'icon', href: "/youqu/favicon.ico"}],
],
```
I need to build on two websites, one of which cannot find Favicon when using 
```shell
pnpm run build --base /
```

How to dynamically specify base using the command line in Favicon?

### Reproduction

How to dynamically specify base using the command line in Favicon?

### Expected behavior

The Favicon configuration has added a base, which can still be dynamically specified through the command line

### System Info

```Text
System:
    OS: Deepin 20.9
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 39.5 GB
  Binaries:
    Node: 18.16.1
    npm: 9.5.1
  Browsers:
    Edge: Spartan (44.22621.746.0), Chromium (106.0.1370.47)
  npmPackages:
    vitepress: 1.0.0-rc.36
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by mikigo** [comment]
help~~😂😂

**Comment by brc-dd** [comment]
You currently cannot. You can use some environment variable instead:

```sh
BASE='/' pnpm run build
```

In config:

```ts
base: process.env.BASE,
... href: `${process.env.BASE || '/'}favicon.ico` ...
```

**Comment by mikigo** [comment]
cool...I'll give it a try.thanks homie.😘😘

**Comment by mikigo** [comment]
ohno

**Comment by brc-dd** [comment]
Don't use `--base`. You need to do `BASE='/youqu/' pnpm run dev`

**Comment by mikigo** [comment]
ok, cool, bro~~

It worked. thanks 😘😘
