### ISSUE TITLE
Build fail in production mode but not in dev with highcharts-vue

### ISSUE THREAD

**Issue by mawangod** [vuejs/vitepress#3871]
### Describe the bug

When I use [highcharts-vue](https://github.com/highcharts/highcharts-vue)

everything works fine when developing

but when I want to build docs by running vitepress build docs
got an error: 

```
SyntaxError: Named export 'Chart' not found. The requested module 'highcharts-vue' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'highcharts-vue';
const { Chart } = pkg;

```

If I add the following lines 

```
  vite: {
    ssr: {
      noExternal: ['highcharts-vue', 'vue'],
    }
  }
```

in the vitepress config file, I got another error:

`ReferenceError: self is not defined`

### Reproduction

https://stackblitz.com/edit/vite-rnyxgt?file=docs%2Fdemo.vue,docs%2F.vitepress%2Fconfig.ts

### Expected behavior

build success

### System Info

```Text
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 20.79 GB / 31.24 GB
    Container: Yes
    Shell: 5.1.16 - /usr/bin/bash
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 3.6.1 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 8.19.4 - ~/Documents/gitlab/stellaroid/node_modules/.bin/npm
  Browsers:
    Chrome: 124.0.6367.60
  npmPackages:
    vitepress: ^1.1.4 => 1.1.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That library is broken. Ask its maintainers to fix their build. You can do this instead:

```ts
import { Chart } from 'highcharts-vue/src/index.js';

// noExternal: ['highcharts-vue'],
```

**Comment by mawangod** [comment]
Thank you!

**Comment by brc-dd** [comment]
It's source is correct though. You can also do this instead and you won't need ssr.noExternal or manually updating imports either:

```ts
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

export default defineConfig({
  // ...,
    vite: {
    resolve: {
      alias: [
        {
          find: /^highcharts-vue($|\?)/,
          replacement: require.resolve('highcharts-vue/src/index.js'),
        },
      ],
    },
  },
});
```

https://stackblitz.com/edit/vite-kaqtq7?file=docs/demo.vue,docs/.vitepress/config.ts

**Comment by mawangod** [comment]
Thank you again for your reactivity!

You are the best! 

Keep going & Have a lovely day!
