### ISSUE TITLE
Make the name of `public` directory customisable

### ISSUE THREAD

**Issue by dmohns** [vuejs/vitepress#3884]
### Is your feature request related to a problem?

Currently users of VitePress have to to use a directory named `public` for static asset handling.

In certain situations it could be helpful to have another name for this directory. 

- If users documentation is organised in a way, that a subdirectory called `public` holding `.md` files makes sense for their documentation.
- If users prefer to organise their documentation in a way, that static assets are not located in-between their documentation files 

### Describe the solution you'd like

Add a config option `publicDir` with default value `public` (relative to root dir) similar to `srcDir`. That configures which directory is treated as public directory for static assets.

### Describe alternatives you've considered

I couldn't figure out any alternative ways to achieve this.

### Additional context

N/A

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/issues/3203#issuecomment-1808191006

**Comment by dmohns** [comment]
Apologies, should have checked _closed_ issues as well 😇 I guess this changes the request here, to add documentation for this option 😉

**Comment by brc-dd** [comment]
are you using

**Comment by brc-dd** [comment]
are you using mpa mode?

**Comment by dmohns** [comment]
> Are you using mpa mode? If not then that part won't affect you. You need to do this:
> 
> ```ts
> // .vitepress/config.ts
> import { defineConfig } from 'vitepress'
> 
> export default defineConfig({
>   vite: {
>     publicDir: 'foo'
>   }
> })
> ```

Ohh, I see my bad. I didn't realise it's under `vite`. Apologies for my confusion. Now it works 👍
