### ISSUE TITLE
Vitepress project in monorepo reports `Failed to resolve import "xxx"`

### ISSUE THREAD

**Issue by i7eo** [vuejs/vitepress#3888]
### Describe the bug

You can check Reproduction Url test.

Everything works fine when I start the vite project(`apps/playground`) using `pnpm dev:playground`. It crashed when I started vitepress project(`apps/document`) using `pnpm dev:document`.

My monorepo project uses `node condition` to link the source code. You can check the `dev` field in `package.json` or `condition: ["dev"]` in `vite.config.ts` or `condition: ["dev"]` in `config.ts`.

### Reproduction

https://github.com/i7eo/monorepo-vitepress-bug-report

### Expected behavior

Start normally like a vite project(`apps/playground`)

### System Info

```Text
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.61 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.1.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
    Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 124.0.6367.201
    Safari: 17.4.1
    Safari Technology Preview: 17.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by i7eo** [comment]
I tested it using `ailas` as described in #1758 and #1698 but it doesn't work

**Comment by i7eo** [comment]
@brc-dd please take look of it

**Comment by i7eo** [comment]
vite project(`apps/playrgound`) wiil enter `vite:resolve` to resolve dep, vitepress project(`apps/document`) will enter `externalize-deps` to resolve dep first. When execute `externalize-deps`'s `tryNodeResolve` function, this function set `condition` filed to `[]`. How to deal it?

**Comment by brc-dd** [comment]
those aliases should be absolute paths. using relative path there would resolve differently from each file.
