### ISSUE TITLE
<details> 无法正常展开收起

### ISSUE THREAD

**Issue by chunge16** [vuejs/vitepress#3894]
### Describe the bug

国际化的英文文档里，`<details>` 无法正常展开收起，存在渲染错误

<img width="1397" alt="image" src="https://github.com/vuejs/vitepress/assets/16758420/0de51546-7afa-4e84-883e-59abb371cd3e">

### Reproduction

https://chunge16.github.io/vitepress-blogs-theme/guide/getting-started#installation

### Expected behavior

期望国际化下，可以正常展开收起

### System Info

```Text
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 73.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v22.1.0/bin/npm
    pnpm: 9.1.0 - ~/.nvm/versions/node/v22.1.0/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.208
    Edge: 124.0.2478.105
    Safari: 17.4.1
  npmPackages:
    vitepress: ^1.1.4 => 1.1.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You're missing closing `:::` for `::: code-group` here - https://github.com/chunge16/vitepress-blogs-theme/blob/efce753db371f59c42621216552cbed5ad621b4c/docs/guide/getting-started.md?plain=1#L47

**Comment by chunge16** [comment]
😭，Low error，Thanks
