### ISSUE TITLE
How to using Vite Env Variables?

### ISSUE THREAD

**Issue by QC2168** [vuejs/vitepress#3896]
### Describe the bug

My project add network request, But I need different environment variables control the request address, how should I use env in vite

[Env Variables](https://vitejs.dev/guide/env-and-mode.html#env-variables)

### Reproduction

None

### Expected behavior

I want to be able to access `import.meta.env.BASE_URL`, just like the vite project

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600KF
    Memory: 2.31 GB / 31.82 GB
  Binaries:
    Node: 18.19.0 - D:\software\nodejs\node.EXE
    npm: 10.2.3 - D:\software\nodejs\npm.CMD
    pnpm: 9.1.1 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.1.3 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vitepress: 1.0.2 => 1.0.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
`import.meta.env.BASE_URL` should work fine in client. Please share minimal reproducible example using https://vitepress.new

**Comment by QC2168** [comment]
I solved it! I should put the env file to docs folder
