### ISSUE TITLE
Some errors are reported that the location of the corresponding file cannot be found

### ISSUE THREAD

**Issue by rwerplus** [vuejs/vitepress#3897]
### Describe the bug

![image](https://github.com/vuejs/vitepress/assets/48611415/f7015bcc-3421-4b7d-981b-6d2874e82251)
The error is caused by not closing the label, but I can't find the corresponding error line after I finish writing the document

### Reproduction

1. done md doc
2. pnpm run docs:build

### Expected behavior

Displays the location of the error

### System Info

```Text
System:
    OS: Windows 11 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 13.51 GB / 39.65 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.0.5 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.22000.2600.0), Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22000.2600
  npmPackages:
    vitepress: ^1.1.4 => 1.1.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> Displays the location of the error

This is fixed. Will be there in next release.
