### ISSUE TITLE
GitHub Pages 部署失败

### ISSUE THREAD

**Issue by CosmoLau** [vuejs/vitepress#3899]
### Describe the bug

使用官方文档中的工作流部署 GitHub Pages，Actions 在执行 `npm run docs:build` 时报错，内容如下：

```text
Run npm run docs:build
> docs:build
> vitepress build
  vitepress v1.1.4
- building client + server bundles...
x Build failed in 4.75s
✖ building client + server bundles...
build error:
RollupError: Could not resolve "./doc/images/1_create_empty_project.png" from "en/advanced-topics/native-plugins/tutorial.md"
file: /home/runner/work/cocos-docs-vitepress/cocos-docs-vitepress/en/advanced-topics/native-plugins/tutorial.md
    at getRollupError (file:///home/runner/work/cocos-docs-vitepress/cocos-docs-vitepress/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at error (file:///home/runner/work/cocos-docs-vitepress/cocos-docs-vitepress/node_modules/rollup/dist/es/shared/parseAst.js:390:42)
    at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/cocos-docs-vitepress/cocos-docs-vitepress/node_modules/rollup/dist/es/shared/node-entry.js:1910[6](https://github.com/CosmoLau/cocos-docs-vitepress/actions/runs/9138290074/job/25129401928#step:6:7):24)
    at file:///home/runner/work/cocos-docs-vitepress/cocos-docs-vitepress/node_modules/rollup/dist/es/shared/node-entry.js:19066:26
Error: Process completed with exit code 1.
```

在本地开发时不会遇到这个报错，能成功通过 `npm run docs:build` 进行构建。

### Reproduction

复现仓库：https://github.com/CosmoLau/cocos-docs-vitepress
Actions：https://github.com/CosmoLau/cocos-docs-vitepress/blob/master/.github/workflows/deploy.yml

### Expected behavior

Actions 能成功运行

### System Info

```Text
System:
    OS: Windows 11 10.0.26120
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 18.76 GB / 31.95 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    bun: 1.1.8 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (124.0.2478.19)
    Internet Explorer: 11.0.26100.1
  npmPackages:
    vitepress: ^1.1.4 => 1.1.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Your file names are `.PNG` not `.png`. Rename them to fix case. It's working fine for you locally because Windows has a case-insensitive filesystem, while on GitHub actions you're using Ubuntu whose filesystem is case sensitive.

**Comment by CosmoLau** [comment]
> Your file names are `.PNG` not `.png`. Rename them to fix case. It's working fine for you locally because Windows has a case-insensitive filesystem, while on GitHub actions you're using Ubuntu whose filesystem is case sensitive.

我确定仓库中没有 `.PNG`，因为我之前在 https://github.com/vuejs/vitepress/issues/3748 中就已经反馈，如果有 `.PNG` 文件，在本地构建时就会报错（Windows 也会如此），无法成功构建，但是这个仓库在本地是能正常构建的，且我已经全局搜索过，并没有 `.PNG` 文件，已经全部替换为了 `.png`，无法成功构建的情况只在 Actions 中出现。

**Comment by brc-dd** [comment]
Well check again - 

<img width="369" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/8b8c9a1c-86d9-4944-9f03-5019ebf8af98">

**Comment by brc-dd** [comment]
You might not have committed case only changes. Do something like this and commit:

```sh
git rm -r --cached .
git add --all .
```

**Comment by brc-dd** [comment]
Your recent build failure is because [this line](https://github.com/CosmoLau/cocos-docs-vitepress/blob/d66d5b835adc9039ca64b6b966273d02ed70c3ed/zh/ui-system/components/editor/editbox.md?plain=1#L35) should be `editBox/editbox-event.png`

**Comment by CosmoLau** [comment]
> Your recent build failure is because [this line](https://github.com/CosmoLau/cocos-docs-vitepress/blob/d66d5b835adc9039ca64b6b966273d02ed70c3ed/zh/ui-system/components/editor/editbox.md?plain=1#L35) should be `editBox/editbox-event.png`

Thank you very much, Actions has been successful!

**Comment by brc-dd** [comment]
http://www.cosmolau.top/cocos-docs-vitepress/ is still broken because you haven't specified `base: '/cocos-docs-vitepress/'` in your vitepress config 👀

**Comment by CosmoLau** [comment]
> http://www.cosmolau.top/cocos-docs-vitepress/ is still broken because you haven't specified `base: '/cocos-docs-vitepress/'` in your vitepress config 👀

Because I wanted to add it under my second level domain, now http://cocos.cosmolau.top is accessible. Thanks again!😚
