### ISSUE TITLE
Changing metadata per page

### ISSUE THREAD

**Issue by cyberalien** [vuejs/vitepress#3900]
### Is your feature request related to a problem? Please describe.

I'd like to change metadata per page, such as `og:image` and `twitter:image`.

While it is possible to add entries to metadata via frontmatter, I want to replace existing entries.

### Describe the solution you'd like

Ideally I've love it metadata could accept functions as values, for example for `content` property of an entry a callback that accepts page as parameter and returns value.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
If you can generalize that function then you can use https://vitepress.dev/reference/site-config#transformpagedata 👀

**Comment by cyberalien** [comment]
Works perfectly. Thanks!
