### ISSUE TITLE
Report an EBADPLATFORM error during installation on MacOS

### ISSUE THREAD

**Issue by arooe** [vuejs/vitepress#3907]
### Describe the bug

Hi sir, When I tried to install vitepress by running the command `npm add -D vitepress`, 

![image](https://github.com/vuejs/vitepress/assets/92929085/2f550b9e-4d2b-4ee5-b2ce-b83517cd50fc)

it reports an error:
```
npm error code EBADPLATFORM
npm error notsup Unsupported platform for esbuild-darwin-arm64@0.14.49: wanted {"os":"darwin","cpu":"arm64"} (current: {"os":"darwin","cpu":"x64"})
npm error notsup Valid os:   darwin
npm error notsup Actual os:  darwin
npm error notsup Valid cpu:  arm64
npm error notsup Actual cpu: x64
npm error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-05-20T08_58_27_221Z-debug-0.log
```

![image](https://github.com/vuejs/vitepress/assets/92929085/8fbcd8b7-ddc1-41de-a9b6-a730616d798a)

Here is the log:
[2024-05-20T08_58_27_221Z-debug-0.log](https://github.com/vuejs/vitepress/files/15375040/2024-05-20T08_58_27_221Z-debug-0.log)

### Reproduction

run the command `npm add -D vitepress` on M1 Mac mini in VSCode

### Expected behavior

Vitepress installed successfully.

### System Info

```Text
MacOS 14.4.1 (23E224)
Mac mini M1, 2020
VSCode info:

Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z (1 wk ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

![image](https://github.com/vuejs/vitepress/assets/92929085/ce72094c-88df-4639-9504-ec696edb52d2)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you verify what's your node version? Can you try upgrading it to latest LTS?

I'm not sure but your node/npm looks broken because it's detecting `cpu` as `x64` on m1. `cpu` should be `arm64` on m1.

**Comment by ukea** [comment]
node version is v21.7.1
![image](https://github.com/vuejs/vitepress/assets/92929085/f546607d-3c30-4d03-bb04-f7e2b2174883)

**Comment by ukea** [comment]
Maybe it's because my vscode is Universal, not Apple Silicon? I guess.
![image](https://github.com/vuejs/vitepress/assets/92929085/f772692c-fb5f-488e-94f2-90dcc089efd6)

**Comment by brc-dd** [comment]
Is it happening if you run from mac terminal instead of vscode's integrated one?

**Comment by brc-dd** [comment]
Can you share the output of following commands - 

```sh
npm --version
node -e "console.log(process.arch)"
```

**Comment by ukea** [comment]
The same with the mac terminal. Maybe this is something wrong with package "esbuild-darwin-arm64"? @brc-dd 
![image](https://github.com/vuejs/vitepress/assets/92929085/9f6d2018-1813-4382-a425-026440f8ecfa)

And the output of the prompt above is:
```
10.8.0
x64
```

![image](https://github.com/vuejs/vitepress/assets/92929085/5a9cf384-9874-4bce-8ca8-dfef66fe4a9e)

Obviously my mac is not the x64 cpu

![image](https://github.com/vuejs/vitepress/assets/92929085/4a09bc1b-fcec-48ed-a990-b3b2daee74ab)


Many thanks~

**Comment by brc-dd** [comment]
It seems the issue is with your node installation. Can you try re-installing it? `node -e "console.log(process.arch)"` should log `arm64` on m1.

**Comment by brc-dd** [comment]
Closing as stale. Please reopen if you're still facing issue. The most likely cause is your node installation, but can't tell for sure.
