### ISSUE TITLE
Cannot watch for changes in route query parameters using `useRoute()`

### ISSUE THREAD

**Issue by g-dx** [vuejs/vitepress#3908]
### Is your feature request related to a problem? Please describe.

I'd like to write the following code on one of my VitePress pages:

```vue
<script setup>
import { useRoute } from 'vitepress';
import { watch } from 'vue';

const route = useRoute();

watch(route.query, (newQuery) => {
  // Do something....
});
</script>
```

However, the current [useRoute()](https://vitepress.dev/reference/runtime-api#useroute) object does not provide access to query parameter information.

### Describe the solution you'd like

I'd like to be able to access the `search`  property of the current location as is possible in `vue-router`:

https://router.vuejs.org/api/interfaces/RouteLocationNormalizedLoaded.html#query

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
use `useUrlSearchParams` from vueuse instead

**Comment by g-dx** [comment]
Thanks for the recommendation!
