### ISSUE TITLE
About the order of use of markdown-it plugins

### ISSUE THREAD

**Issue by QC-L** [vuejs/vitepress#391]
### Describe the bug

When localizing documents, it is necessary to retain the original anchor points, e.g.

```
# Getting Started
```

in Chinese

```
# 快速开始 {#getting-started}
```

In this case, I need to use markdown-it-attrs, but the source code uses markdown-it-anchor, and attrs needs to be executed before anchor.

markdown-it-anchor is described in the [documentation](https://github.com/valeriangalliat/markdown-it-anchor#explicit-ids)：

> markdown-it-anchor is designed to reuse any existing id, making markdown-it-attrs a perfect fit for this use case. Make sure to load it before markdown-it-anchor!

### Reproduction

None

### Expected behavior

None

### System Info

```shell
None
```

### Additional context

I think there are two solutions:

1. add `markdown-it-attrs` to the source code
2. add a pre-selection for loading plugins

```js
  // pre config
  if (options.preConfig) {
    options.preConfig(md)
  }

  // custom plugins
  md.use(componentPlugin)
    .use(highlightLinePlugin)
    .use(preWrapperPlugin)
    .use(snippetPlugin, srcDir)
    .use(hoistPlugin)
    .use(containerPlugin)
    .use(extractHeaderPlugin)
    .use(linkPlugin, {
      target: '_blank',
      rel: 'noopener noreferrer',
      ...options.externalLinks
    })

    // 3rd party plugins
    .use(anchor, {
      slugify,
      permalink: anchor.permalink.ariaHidden({}),
      ...options.anchor
    })
    .use(toc, {
      slugify,
      includeLevel: [2, 3],
      format: parseHeader,
      ...options.toc
    })
    .use(emoji)
	// ...

  // apply user config
  if (options.config) {
    options.config(md)
  }
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by antfu** [comment]
I would vote for including `markdown-it-attrs` as a part of vitepress giving it's quite a common use case for translated documentation.

**Comment by QC-L** [comment]
Okay, then I will go to modify PR #392

**Comment by QC-L** [comment]
Done, please see #393
