### ISSUE TITLE
SyntaxError: The requested module 'xxxx' does not provide an export named 'createMap'

### ISSUE THREAD

**Issue by CLD5186** [vuejs/vitepress#3911]
### Describe the bug

I am using vitepress to build my own component library documentation. But I found that my component library works fine when running locally (pnpm run docs: dev). But when I was building and packaging the document, I found an error.
The error content is as follows:
build error:
The requested module 'xxxxx' does not provide an export named 'createMap'
file:///Users/xxxx/Desktop/rowell/docs/.vitepress/.temp/app.js?t=1716450835231:6
import { createMap } from "xxxx-map";
         ^^^^^^^^^
SyntaxError: The requested module 'rowell-map' does not provide an export named 'createMap'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async build (file:///Users/xxxx/Desktop/xxx/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.12.12_async-validator@4.2.5_post_ukdolohmhfcax7uakvmfazy3f4/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46734:24)
I thought there was a problem with my component library, but when I used pnpm create vite to build a Vue initialization project and installed my component library. There is no problem with packaging the project.

### Reproduction

no

### Expected behavior

no

### System Info

```Text
no
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That package likely has broken exports. Do something like this to force transpile it:

```ts
// .vitepress/config.ts

export default defineConfig({
  // ...
  vite: {
    ssr: {
      noExternal: ['package-name']
    }
  }
})
```

**Comment by brc-dd** [comment]
closing as stale, please reopen with repro if it's still broken
