### ISSUE TITLE
Ability to generate index page that lists all sub-pages recursively

### ISSUE THREAD

**Issue by peterbe** [vuejs/vitepress#3912]
### Is your feature request related to a problem? Please describe.

I don't maintain the `.md` files I build. They come from copying all the `**/*.md` files from another repo. 
But I'd like to create site maps for all articles. A page that lists all links and their titles all in one big page. 
The `**/*.md` files I copy use a `README.md` for various directories. Something like this:

```
- foo/
    -  some-page.md
    - other-page.md
    - README.md
```
I'd love to create, from this:
```
- /foo/some-page.html
- /foo/other-page.html
- /foo/readme.html
- /foo/index.html
```

And that `index.html` page would look something like this:

```html
<!-- foo/index.html -->

<ul>
  <li><a href="/foo/some-page.html">Some Page Title</a></li>
  <li><a href="/foo/other-page.html">Other page Title here</a></li>
  <li><a href="/foo/readme.html">README</a></li>
</ul>
```

I *could* try to write a script that generates these `index.html` files by doing some `fs.readdirSync('foo')` and generate the `index.md` file programmatically, but how would I get the titles of those pages?

### Describe the solution you'd like

A config choice like:
```
    indexPage: true
```

### Describe alternatives you've considered

Write a script that generates a `index.md` file from reading the `**/*.md` files. 

### Additional context

New to vitepress :)

### Validations

- [x] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [x] Read the [docs](https://vitepress.dev).
- [x] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [x] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/guide/data-loading#createcontentloader ?

**Comment by brc-dd** [comment]
Closing as stale. You can easily use createContentLoader in data loader files to get array of files and create your list element by iterating over them.
