### ISSUE TITLE
Traslation issue

### ISSUE THREAD

**Issue by BlockJack** [vuejs/vitepress#3926]
### Describe the bug

After I set the locale to zh-CN, the default text of the sidebar and appearance button are still English, please check the attachments below (in red circles
![localeSettings](https://github.com/vuejs/vitepress/assets/41741319/dc42a7f0-3221-41e5-8ccb-2cf7544816da)
).
![onThisPage](https://github.com/vuejs/vitepress/assets/41741319/14a8de9d-35e0-4149-8b3a-0d1cf0ff0551)
![appearance](https://github.com/vuejs/vitepress/assets/41741319/e62581d6-d369-40f3-b904-d403158ddd38)

### Reproduction

1. set locale to zh-CN
2. run the server to check apperance toggle button and the sidebar

### Expected behavior

'Appearance' text should be translated to Chinese, sth like '外观'.
'On this page' text on the right sidebar should be translated to Chinese too.

### System Info

```Text
OS: Windows 10
Node: v21.6.2
npm: 10.4.0
vitepress: latest
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Those need to be manually specified:

```ts
themeConfig: {
    docFooter: {
      prev: '上一页',
      next: '下一页'
    },

    outline: {
      label: '页面导航'
    },

    lastUpdated: {
      text: '最后更新于',
      formatOptions: {
        dateStyle: 'short',
        timeStyle: 'medium'
      }
    },

    langMenuLabel: '多语言',
    returnToTopLabel: '回到顶部',
    sidebarMenuLabel: '菜单',
    darkModeSwitchLabel: '主题',
    lightModeSwitchTitle: '切换到浅色模式',
    darkModeSwitchTitle: '切换到深色模式'
}
```

**Comment by BlockJack** [comment]
thank you @brc-dd , can you let me know how to set the paragraph text for 404 page?

**Comment by brc-dd** [comment]
```ts
themeConfig: {
  notFound: {
    code: '...',
    title: '...',
    quote: '...',
    linkLabel: '...',
    linkText: '...'
  }
}
```

**Comment by BlockJack** [comment]
It's working now , thank you @brc-dd
