### ISSUE TITLE
sidebar配置需要优化

### ISSUE THREAD

**Issue by virskor** [vuejs/vitepress#3933]
### Is your feature request related to a problem? Please describe.

当sidebar配置因为文件目录较多时，sidebar会被打包进入所有页面的HTML中，这将导致__VP_HASH_MAP__过大。

### Describe the solution you'd like

希望根据目录配置sidebar，打包时，仅引入目录下的sidebar配置文件，避免注入到所有页面的__VP_HASH_MAP__中

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Set `metaChunk: true` in your .vitepress config. It will extract that to separate file and won't exponentially increase your size.

**Comment by chenyaowen123** [comment]
我也遇到了这个问题，页面较多时建议开启比较好，当我设置了 ```metaChunk: true```，这让我的打包文件直接从500M降低至200M。这个配置比较有用，但是文档可能不够突出，我也是找了一段时间才找到。

**Comment by virskor** [comment]
设置metaChunk: true只是把sidebar打包的文件单独抽离到一个JS中去，虽然很简单解决了这个问题但是只能称为优化，因为核心的解决因该是每个目录的sidebar仅影响该目录下生成的文件，而不打包到其他路径的文件中去。这样即便1000个目录100000个sidebar menu，打包后每个目录的文件也很小，实际请求只会涉及当前目录的。

**Comment by brc-dd** [comment]
Duplicate of #3367
