### ISSUE TITLE
(build): Number header attribute render error

### ISSUE THREAD

**Issue by Zhengqbbb** [vuejs/vitepress#3939]
### Describe the bug

```sh
npm run docs:build

✓ building client + server bundles...
✖ rendering pages...
build error:
str.replace is not a function
TypeError: str.replace is not a function
```

![CleanShot 2024-06-04 at 21 22 30@2x](https://github.com/vuejs/vitepress/assets/40693636/fb971066-22c7-49d3-b70a-fe94e2f3ce10)

### Reproduction

```md
---
head:
  - - meta
    - name: robots
      content: noindex
  - - meta
    - id: 301
---
```

### Expected behavior

build success

### System Info

```Text
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 195.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.x-cmd.root/local/data/pkg/sphere/X/l/j/h/bin/node
    npm: 10.2.4 - ~/.x-cmd.root/local/data/pkg/sphere/X/l/j/h/bin/npm
    pnpm: 9.1.3 - ~/project/lteam/x-cmd/official-doc/node_modules/.bin/pnpm
    bun: 1.1.8 - ~/.x-cmd.root/local/data/pkg/sphere/X/l/j/h/bin/bun
  Browsers:
    Chrome: 125.0.6422.141
    Safari: 17.2.1
```

### Additional context

https://stackblitz.com/edit/vite-apgm1n?file=docs%2Fexample.md

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not a bug. It should be a string: `id: '301'`

It was working in earlier because it was wrongfully coercing values to string.

**Comment by Zhengqbbb** [comment]
> Not a bug. It should be a string: `id: '301'`
> 
> It was working in earlier because it was wrongfully coercing values to string.

Okay ~ But I think you can add preventive measures and fault tolerance. 
I would like to know your opinion. 
If it's not necessary, I will close the PR and ISSUE.

**Comment by brc-dd** [comment]
For numbers we can probably add it, but a better place to do that would be before the pageData hook call in markdownToVue.ts.

For other data types, it's mostly wrong. After that change many people discovered issues like they were having undefined/null value in head and vitepress wasn't failing earlier. For booleans too it isn't same as what people expect. A string value of false in attributes is also truthy.

**Comment by Zhengqbbb** [comment]
It seems that this problem still requires the user to specify the configuration type to avoid more problems, Thank u reply 🫡
I closed the ISSUE and PR
