### ISSUE TITLE
Whether to support customizing the copy code text in the code box

### ISSUE THREAD

**Issue by hestiacn** [vuejs/vitepress#3942]
### Is your feature request related to a problem? Please describe.

![b1c5d2c9334d5cb0320b1cf47aeb154](https://github.com/vuejs/vitepress/assets/138613406/a336d99d-0cff-4eeb-8150-f047ece753e4)

### Describe the solution you'd like

![b1c5d2c9334d5cb0320b1cf47aeb154](https://github.com/vuejs/vitepress/assets/138613406/da1e6829-a20c-47d5-8eb6-d71bc078d0d2)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
```ts
export default defineConfig({
  markdown: {
    codeCopyButtonTitle: 'in some other lang'
  }
})
```

**Comment by hestiacn** [comment]
Where should I add this configuration? Should I configure it in config.js or write it in css or vue component?

**Comment by brc-dd** [comment]
yeah it should work
