### ISSUE TITLE
Feature Request: Auto-generate Page Descriptions in VitePress for SEO Optimization

### ISSUE THREAD

**Issue by chenyaowen123** [vuejs/vitepress#3944]
### Is your feature request related to a problem? Please describe.

Yes, the feature request is related to a problem I've encountered while authoring Markdown documents for VitePress. Currently, there isn't an automated way to generate the description meta tag for pages, which is essential for SEO purposes. Manually crafting descriptions for each page can be time-consuming and prone to inconsistency.

我希望实现自动填充 ```description:``` 内容，然后解放双手。

### Describe the solution you'd like

I propose implementing an automated feature in VitePress that generates a description meta tag based on the content of the Markdown document. This could be achieved by integrating a summary extraction plugin similar to markdown-summary, which would analyze the document and provide a concise summary to be used as the page description.

### Describe alternatives you've considered

I've considered two main alternatives for implementing the automatic description generation feature:

1. **VSCode Extension:** Developing a VSCode extension that integrates with VitePress projects. This extension could provide a command or shortcut that, when triggered, analyzes the current open Markdown file and suggests a description based on its content. Users would have to install the extension and use it manually, but it would be a convenient way to generate descriptions directly within their development environment.
2.  **VitePress Configuration Option:** Another approach is to enhance VitePress itself with a new configuration option that allows for automatic description generation. When this feature is enabled, VitePress would automatically analyze each Markdown file during the build process and inject a description meta tag with a summary extracted from the content. This would be a seamless solution that requires no additional tools or extensions, making it accessible to all VitePress users.
3. **AI-Powered Description Generation:** Implementing an AI-based solution that analyzes the content of Markdown files and uses natural language processing to generate high-quality, engaging descriptions. This approach could potentially offer more sophisticated and context-aware descriptions, improving both user experience and SEO effectiveness.

Both alternatives have their merits. The VSCode extension offers immediate control and integration for developers who use VSCode, while the VitePress configuration option provides a more universal solution that benefits all users, regardless of their development environment.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by chenyaowen123** [comment]
我觉得可以检测一下文档里是否有这个参数，没有就自动生成一个，然后我可以自己去修改它。
I think it's possible to check if this parameter is present in the document. If not, it will be automatically generated and I can modify it myself.

```md
---
description: This is automatically filled based on the content
---
````

**Comment by chenyaowen123** [comment]
我觉得可以检测一下文档里是否有这个参数，没有就自动生成一个，然后我可以自己去修改它。
I think it's possible to check if this parameter is present in the document. If not, it will be automatically generated and I can modify it myself.

```md
---
description: This is automatically filled based on the content
---
````

**Comment by chenyaowen123** [comment]
我宁愿在config里填写参数，页面没有配置```description:```的时候，它可以自动生成
I would rather fill in the parameters in config. When the page is not configured with ` ` description: ` `, it can be automatically generated

**Comment by brc-dd** [comment]
Sorry but AI integrations are out of scope for us right now. This should be done via third-party integrations.
