### ISSUE TITLE
Hide the appearance switcher, but still honor the user’s preferred color scheme

### ISSUE THREAD

**Issue by mbostock** [vuejs/vitepress#3946]
### Is your feature request related to a problem? Please describe.

I would like to hide the appearance switcher (the dark/light mode toggle); however, I would still like VitePress to respect the user’s preferred color scheme. None of the existing [appearance settings](https://vitepress.dev/reference/site-config#appearance) appear to allow this: enabling responsive light/mark mode also enables the appearance switcher.

Apple’s human interface guidelines [expressly discourage](https://developer.apple.com/design/human-interface-guidelines/dark-mode#Best-practices) in-app appearance switchers, saying:

> **Avoid offering an app-specific appearance setting.** An app-specific appearance mode option creates more work for people because they have to adjust more than one setting to get the appearance they want. Worse, they may think your app is broken because it doesn’t respond to their systemwide appearance choice.

### Describe the solution you'd like

Maybe setting `appearance: "auto"` (ideally the default) would set the dark/light mode based on the user’s [preferred color scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) but without rendering the appearance switcher anywhere.

### Describe alternatives you've considered

I can suppress the appearance switcher with custom CSS, but it is brittle (particularly in `.VPMenu`) and likely to break in future releases of VitePress:

```css
.VPNavBarAppearance,
.VPNavScreenAppearance,
.VPMenu > .group:first-child {
  display: none !important;
}

.VPMenu > .group:nth-child(2) {
  margin-top: -13px;
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
a better workaround might be to do something like this

```ts
export default definConfig({ 
  appearance: false,
  head: [
    [
      'script',
      {},
      `document.documentElement.classList.toggle('dark', window.matchMedia('(prefers-color-scheme: dark)').matches)`
    ]
  ]
})
```

But yeah there should be a built-in option to do this. Moreover this workaround doesn't watch for changes and if you watch for changes you'll need to handle disabling transitions yourself.

**Comment by mbostock** [comment]
Thanks much, @brc-dd! I’m impressed by how quickly you implemented this. 👏
