### ISSUE TITLE
Why not support markdown region snippets?

### ISSUE THREAD

**Issue by s-elo** [vuejs/vitepress#3949]
### Is your feature request related to a problem? Please describe.

Looks like currently markdown inclusion does not support region snippet like code snippet.

### Describe the solution you'd like

File1.md
```md
<!--@include: /common/file.md#snippet{2,3} -->
```

snippet.md
```md
<!-- #region snippet -->
## snippet

<CustomComponent>
Custom content
</CustomComponent>
<!-- #endregion snippet -->
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Theo-messi** [comment]
try like this

File1.md
```md
<<< /common/file.md#snippet{2,3}
```
snippet.md 
```md
<!-- #region snippet -->
## snippet
<!-- #endregion snippet -->
```

**Comment by s-elo** [comment]
In fact, I have patched vitepress to support markdown region snippets, but I'm not sure if there any concern not implementing this feature, since looks like it is quite similar to the code region snippets.

**Comment by maxnorth** [comment]
Wild timing, I was just bumping into this and came looking for issues, didn't expect to find it was merged so recently it wasn't released yet. @brc-dd How long should I expect before this to makes it into a release? The [online docs](https://vitepress.dev/guide/markdown#markdown-file-inclusion) are currently inaccurate saying this syntax is available.

**Comment by brc-dd** [comment]
2-3 days maybe.
