### ISSUE TITLE
使用 AntDesignVue Pagination 组件中，发现单击某个页数切换，会导致页面会回滚到 Top

### ISSUE THREAD

**Issue by linpengteng** [vuejs/vitepress#3950]
### Describe the bug

单击 AntDesignVue Pagination 组件某页进行切换时，会导致当前页面会滚动到 Top。

### Reproduction

后排查发现 \<a rel="nofollow"> 这种也会起到锚链接的作用。但在其他非 vitepress 的 SPA 页面中使用，却不会有这个影响。我不太理解。

### Expected behavior

消除 \<a rel="nofollow"> 本不该有的 锚链接影响。

### System Info

```Text
System:
    OS: macOS 14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.63 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 9.2.0 - /usr/local/bin/pnpm
    bun: 1.1.12 - /usr/local/bin/bun
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.5
  npmPackages:
    vitepress: ^1.2.3 => 1.2.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Add `vp-raw` class to one of it's parent.

**Comment by linpengteng** [comment]
class="vp-raw" is effective, Thank you.

**Comment by brc-dd** [comment]
It will be fixed in next version. You won't need it then.
