### ISSUE TITLE
icon加载不出来时,用上一次离线缓存替换

### ISSUE THREAD

**Issue by pure-white-ice-cream** [vuejs/vitepress#3951]
### Is your feature request related to a problem? Please describe.

![1718035077982](https://github.com/vuejs/vitepress/assets/61543584/19be07e4-0029-4327-b73e-86807113e78d)
如图, 在线获取网站的icon, 但是有时候获取不到, 会显示空白, 很难看, 希望可以实现标题说的功能, 万分感谢

### Describe the solution you'd like

icon加载不出来时,用上一次离线缓存替换

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
wrong repo
