### ISSUE TITLE
[Question] How to write double curly brackets `{{}}` with nothing in?

### ISSUE THREAD

**Issue by 321paranoiawhy** [vuejs/vitepress#3959]
### Describe the bug

I wanna write `{{}}`, but cause vitepress handle `Vue-style interpolation`, so I try to write `\{\{\}\}`, both of them show nothing after transformed, how can I show them normally?

[Interpolation - Vitepress](https://vitepress.dev/guide/using-vue#interpolation)

### Reproduction

Both of them appear:

- `{{}}`
- `\{\{\}\}`

### Expected behavior

display `{{}}` as normal

### System Info

```Text
Just do not need
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/discussions/480

**Comment by 321paranoiawhy** [comment]
> #480

Awesome, thx!
