### ISSUE TITLE
Sitemap urls without `.html` extension

### ISSUE THREAD

**Issue by quriosapien** [vuejs/vitepress#3963]
### Is your feature request related to a problem? Please describe.

I want the url(s) generated in `sitemap.xml` to be cleanUrls, and not contain `.html` extension

### Describe the solution you'd like

A config similar to `cleanUrl` which removes the `.html` extension from sitemap generated.

### Describe alternatives you've considered

- Didn't find anything in doc about it.
- Found a middleware/hook sort of work-around on some community forums

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
When you've cleanUrls enabled, there won't be .html in sitemap too. If you've cleanUrls disabled and not have .html in sitemap, then sitemap is essentially pointing to wrong URLs which may or may not resolve depending on your server.
