### ISSUE TITLE
Linking to a .ppsx file in the public dir fails the build with "Found dead link"

### ISSUE THREAD

**Issue by plievone** [vuejs/vitepress#3965]
### Describe the bug

For some reason, I see different behavior in build when linking to public dir `.pdf` vs `.ppsx` (or `.ppt`).

### Reproduction

Copy `test.pdf` and `test.ppsx` into `/public` dir.
Insert a link to the file in `test.md`:
a) Using `[link](/test.pdf)`, `npm run build` works ok.
b) Using `[link](/test.ppsx)`, `npm run build` fails with `(!) Found dead link /test.ppsx in file test.md` even though the file is there.

### Expected behavior

I expected all the static files in `/public` to be treated the same. I do not yet have visibility into the workings of VitePress to diagnose this further, if this is some kind of user error or some interaction in dependencies of VitePress. 

### System Info

```Text
System:
    OS: macOS 13.6.7
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  npmPackages:
    vitepress: ^1.2.3 => 1.2.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
ppsx is not a vitepress recognized extension, so you’ll manually need to do something like

`process.env.VITE_EXTRA_EXTENSIONS = 'ppsx'`

on top of your config file

**Comment by brc-dd** [comment]
There is #3852 open for docs.
