### ISSUE TITLE
when reloading a page the .html extension get removed and all body disappears 

### ISSUE THREAD

**Issue by nbari** [vuejs/vitepress#3970]
### Describe the bug

The content disappears after reloading the page, what I have noticed is that if the page is /index.html after reloading becomes /index (without extension) but all the content is not displayed any more 

### Reproduction

Visit for example site https://s3m.stream/config.html reload and the URL will be changed to https://s3m.stream/config and content will disappear the 

### Expected behavior

keep showing the page content no matter if the user reloads the page

### System Info

```Text
System:
    OS: Linux 6.9 Arch Linux
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 120.99 GB / 125.70 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.3.0 - /usr/bin/node
    npm: 10.8.1 - /usr/bin/npm
    pnpm: 9.4.0 - /usr/bin/pnpm
  npmPackages:
    vitepress: ^1.0.0-rc.31 => 1.2.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Disable auto-minify in your host and vitepress is not removing that .html either. You probably have clean urls enabled in your host.

**Comment by nbari** [comment]
Hi @brc-dd thanks for the prompt reply, this is my `config.mjs`:

```

**Comment by brc-dd** [comment]
Where are you hosting your site?

**Comment by nbari** [comment]
In cloudflare pages

**Comment by brc-dd** [comment]
- login to your dashboard (https://dash.cloudflare.com/login)
- select account/website
- go to Speed > Optimization > Content Optimization
- disable Auto Minify

**Comment by nbari** [comment]
Hi, many thanks I change it to:

![image](https://github.com/vuejs/vitepress/assets/364199/85ae45b7-6c48-4342-8fe2-86c3f1a285a7)


Regarding transform rules I don't have any, this one is only enable but I think is not a problem:
![image](https://github.com/vuejs/vitepress/assets/364199/51f47968-d7fb-4e29-b749-22a07335e4f0)

**Comment by nbari** [comment]
Hi @brc-dd   :1st_place_medal: many thanks it is working now

**Comment by brc-dd** [comment]
It's still not correct though. It should send 308 for `config.html`:

<img width="329" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/f876770b-af5a-4a35-a88a-182dc1c78bf0">

Since you can't find a way to disable this, it might be better to just enable it for vitepress too:


```ts
export defineConfig({
  cleanUrls: true,
  // ... other stuff ...
})
```
