### ISSUE TITLE
Render ignored frontmatter of layout in root page

### ISSUE THREAD

**Issue by fr1g** [vuejs/vitepress#3971]
### Describe the bug

After launched the dev it thrown this exception:
20:50:08 [vitepress] Internal server error: end of the stream or a document separator is expected at line 3, column 7:
    layout: home
          ^
  Plugin: vitepress
  File: /Users/feiron/Movies/CSKB_Hosting-master/docs/index.md
      at generateError (file:///Users/feiron/Movies/CSKB_Hosting-master/node_modules/.store/vitepress@1.2.3/node_modules/vitepress/dist/node/serve-CEEKiiuH.js:22356:10)
      at throwError (file:///Users/feiron/Movies/CSKB_Hosting-master/node_modules/.store/vitepress@1.2.3/node_modules/vitepress/dist/node/serve-CEEKiiuH.js:22362:9)
      at readDocument (file:///Users/feiron/Movies/CSKB_Hosting-master/node_modules/.store/vitepress@1.2.3/node_modules/vitepress/dist/node/serve-CEEKiiuH.js:23734:5)
      at loadDocuments (file:///Users/feiron/Movies/CSKB_Hosting-master/node_modules/.store/vitepress@1.2.3/node_modules/vitepress/dist/node/serve-CEEKiiuH.js:23777:5)
      at load$1 (file:///Users/feiron/Movies/CSKB_Hosting-master/node_modules/.store/vitepress@1.2.3/node_modules/vitepress/dist/node/serve-CEEKiiuH.js:23803:19)
      at Object.safeLoad (file:///Users/feiron/Movies/CSKB_Hosting-master/node_modules/.store/vitepress@1.2.3/node_modules/vitepress/dist/node/serve-CEEKiiuH.js:23826:10)
      at parse$5 (file:///Users/feiron/Movies/CSKB_Hosting-master/node_modules/.store/vitepress@1.2.3/node_modules/vitepress/dist/node/serve-CEEKiiuH.js:25053:17)
      at parseMatter (file:///Users/feiron/Movies/CSKB_Hosting-master/node_modules/.store/vitepress@1.2.3/node_modules/vitepress/dist/node/serve-CEEKiiuH.js:25162:17)
      at matter (file:///Users/feiron/Movies/CSKB_Hosting-master/node_modules/.store/vitepress@1.2.3/node_modules/vitepress/dist/node/serve-CEEKiiuH.js:25103:10)
      at md.render (file:///Users/feiron/Movies/CSKB_Hosting-master/node_modules/.store/vitepress@1.2.3/node_modules/vitepress/dist/node/serve-CEEKiiuH.js:25288:45)

meanwhile, the page rendered as 404;
after a refresh, it displayed the root markdown and ignored the frontmatter.

here's screenshots for comparison:
<img width="1792" alt="image" src="https://github.com/vuejs/vitepress/assets/53085628/7c14cd72-fc0c-489b-b9b1-168ca998bc38">

and here's what it should be:
<img width="1792" alt="image" src="https://github.com/vuejs/vitepress/assets/53085628/76692987-1127-4409-a555-d4e73b2d8486">

other screenshots: 
<img width="433" alt="image" src="https://github.com/vuejs/vitepress/assets/53085628/0f382110-eed9-46ba-9ef5-2a82f99e0c7c">
<img width="1073" alt="image" src="https://github.com/vuejs/vitepress/assets/53085628/8ae5c63c-a793-4fce-afc1-f860fd0ec3a3">

### Reproduction

here's the online repro:
https://stackblitz.com/edit/vite-kcrtdk

- <del>Set up i18n</del> this step is not necessary
- Set up a series of frontmatter which implements default theme layout in default language path
- add "features" part after the layout setups
- write some markdown and some HTML after the end of frontmatter
- run in dev

### Expected behavior

the rendered page should display as what set-up by layout preset.

### System Info

```Text
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 50.77 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 10.1.0 - /usr/local/bin/npm
  Browsers:
    Safari: 17.5
  npmPackages:
    vitepress: ^1.0.0-alpha.45 => 1.2.3
```

### Additional context

I've checked for duplicate but I don't know if there's any expression that represents to my same meaning.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please share the relevant code preferably using https://vitepress.new

**Comment by Zhengqbbb** [comment]
https://vitepress.dev/reference/default-theme-home-page

```md
---
layout: home
---
```

![CleanShot 2024-06-26 at 00 06 19@2x](https://github.com/vuejs/vitepress/assets/40693636/33c36d46-26fc-4cd8-a5cd-d16254430da4)

**Comment by fr1g** [comment]
你貌似没抓到重点，本应根据frontmatter套用layout的部分全被渲染为markdown了。发自我的 iPhone在 2024年6月26日，00:08，Q.Ben Zheng ***@***.***> 写道：﻿
https://vitepress.dev/reference/default-theme-home-page
---
layout: home
---
***@***.*** (view on web)

**Comment by Zhengqbbb** [comment]
> 你貌似没抓到重点，本应根据frontmatter套用layout的部分全被渲染为markdown了。

所以重点能复现，可以给链接，目前图片看不出重点：https://vitepress.new/

**Comment by brc-dd** [comment]
You have invalid YAML, most like something like

```md
---
---
layout: home
```

Please check that.

**Comment by fr1g** [comment]
I've checked that already, never did I do that. Although the shown result has a horizontal line at the beginning as if there were duplicated lines of dashes. 发自我的 iPhone在 2024年6月26日，03:01，Divyansh Singh ***@***.***> 写道：﻿
You have invalid YAML, most like something like
---
---
layout: home
Please check that.

**Comment by fr1g** [comment]
谢谢，我要把这个链接添加进issue里吗？发自我的 iPhone在 2024年6月26日，02:44，Q.Ben Zheng ***@***.***> 写道：﻿

你貌似没抓到重点，本应根据frontmatter套用layout的部分全被渲染为markdown了。

所以重点能复现，可以给链接，目前图片看不出重点：https://vitepress.new/

**Comment by brc-dd** [comment]
> I've checked that already, never did I do that.

Is this the file which you're referencing - https://github.com/fr1g/docs/blob/c1b9ed428dc665777eea81d9c7ee1653d7c8b5b8/index.md?plain=1 ? It clearly has extra `---`

**Comment by fr1g** [comment]
that changes nothing, just i have tried to remove that but still发自我的 iPhone在 2024年6月26日，11:06，Divyansh Singh ***@***.***> 写道：﻿

I've checked that already, never did I do that.

Is this the file which you're referencing - https://github.com/fr1g/docs/blob/c1b9ed428dc665777eea81d9c7ee1653d7c8b5b8/index.md?plain=1 ? It clearly has extra ---

**Comment by brc-dd** [comment]
Then please share a reproducible example. We can't help without that.

**Comment by fr1g** [comment]
Someone replied before gave a link: VitePress (forked)stackblitz.comwhich said this is a repro that able to repro the issue, never did I tried since GTA OL updated recently :P发自我的 iPhone在 2024年6月26日，12:03，Divyansh Singh ***@***.***> 写道：﻿
Then please share a reproducible example. We can't help without that.

**Comment by brc-dd** [comment]
You've to open that https://vitepress.new link --> add your content there --> make sure you are getting that error there --> save it --> send us the link.

**Comment by Zhengqbbb** [comment]
> https://github.com/fr1g/docs/blob/c1b9ed428dc665777eea81d9c7ee1653d7c8b5b8/index.md?plain=2

markdown 的 frontmatter 写法有问题，很明显了已经

<img width="704" alt="image" src="https://github.com/vuejs/vitepress/assets/40693636/8cd02cff-106e-4552-8cba-8b00e59171b6">


```md
---
<YAML>
---

<hr>

### 友情链接

*CSKB的友情链接仅包含同类的知识分享/文档类网站链接. 如需要和CSKB交换友链, 请点击上方的「联系我们」与我们取得联系.*

<div style="display:grid;grid-template-columns: repeat(7, minmax(0, 1fr)); gap:.5rem;">
  <a style="display:block;border: 1px solid var(--vp-c-bg-soft);border-radius: 12px;height: 100%;background-color: var(--vp-c-bg-soft); padding:.7rem;" class="bitter" target="_blank"
     href="#" title=""
     >x</a>
</div>
```

**Comment by fr1g** [comment]
> That error usually happens when you have invalid YAML. Judging by that rendered `<hr>` before `--- layout`, I think you might be doing something like this:
> 
> ```
> ---
> ​---
> layout: home
> 
> ...
> 
> ---
> ```
> 
> Please check that and remove extra `---` lines.

sorry for my misunderstood, I've updated my issue with a new link: https://stackblitz.com/edit/vite-kcrtdk which included a repro.

**Comment by fr1g** [comment]
> > https://github.com/fr1g/docs/blob/c1b9ed428dc665777eea81d9c7ee1653d7c8b5b8/index.md?plain=2
> 
> markdown 的 frontmatter 写法有问题，很明显了已经
> 
> <img alt="image" width="704" src="https://private-user-images.githubusercontent.com/40693636/343035252-8cd02cff-106e-4552-8cba-8b00e59171b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTQyMTEsIm5iZiI6MTcxOTM5MzkxMSwicGF0aCI6Ii80MDY5MzYzNi8zNDMwMzUyNTItOGNkMDJjZmYtMTA2ZS00NTUyLThjYmEtOGIwMGU1OTE3MWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYmQ4YzI3OWZmNzQ2YjcxNTUyOTc4Y2FiYjQyODY1MTM1NzRjNjc0ZjFlZjUxN2ZlMzA2ZmEyOGNjZjY3YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kMuWahfuAEul3-m7OXiUunUvspGhOAyPbnY1QJCK44E">
> ```
> ---
> <YAML>
> ---
> 
> <hr>
> 
> ### 友情链接
> 
> *CSKB的友情链接仅包含同类的知识分享/文档类网站链接. 如需要和CSKB交换友链, 请点击上方的「联系我们」与我们取得联系.*
> 
> <div style="display:grid;grid-template-columns: repeat(7, minmax(0, 1fr)); gap:.5rem;">
>   <a style="display:block;border: 1px solid var(--vp-c-bg-soft);border-radius: 12px;height: 100%;background-color: var(--vp-c-bg-soft); padding:.7rem;" class="bitter" target="_blank"
>      href="#" title=""
>      >x</a>
> </div>
> ```

已更新repro，https://stackblitz.com/edit/vite-kcrtdk 使用默认给的frontmatter配html在后面再加上features就会出问题，确实不是额外一行的dash导致的

**Comment by brc-dd** [comment]
Where is the error? It's rendering just fine.

<img width="1235" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/9018bd39-3720-451e-8de8-1bb543268a16">

**Comment by brc-dd** [comment]
features should be outside hero, there is indentation issue

<img width="1229" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/8bcf556b-689e-4e7f-9e84-035f11346c85">

**Comment by fr1g** [comment]
> features should be outside hero, there is indentation issue
> 
> <img alt="image" width="1229" src="https://private-user-images.githubusercontent.com/40380293/343100224-8bcf556b-689e-4e7f-9e84-035f11346c85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTYxMDUsIm5iZiI6MTcxOTM5NTgwNSwicGF0aCI6Ii80MDM4MDI5My8zNDMxMDAyMjQtOGJjZjU1NmItNjg5ZS00ZTdmLTllODQtMDM1ZjExMzQ2Yzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5NTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNDcyMDRjMjVjYzhjYzEzOTE1YWIzZGRhMzA5NDZjMGQyMWU2NjRhMTg5ZTJhYTgyNWE2MjM0NzQ0NTU2MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vkru0bseqTT7aJYiQv3lFvmVauojaQ1e_Sh1P7TNRPc">

I'm trying to make the format right but this online tool always re-formatting the entire yaml caption and each save of this file made the format weird after I removing the unexpected indentation :(

**Comment by fr1g** [comment]
Now I suspect that something removed my indentation before render right inside vitepress
*I swear I've already checked my file thousand times and I cannot find any error*

**Comment by fr1g** [comment]
> features should be outside hero, there is indentation issue
> 
> <img alt="image" width="1229" src="https://private-user-images.githubusercontent.com/40380293/343100224-8bcf556b-689e-4e7f-9e84-035f11346c85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTgzMzYsIm5iZiI6MTcxOTM5ODAzNiwicGF0aCI6Ii80MDM4MDI5My8zNDMxMDAyMjQtOGJjZjU1NmItNjg5ZS00ZTdmLTllODQtMDM1ZjExMzQ2Yzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEwMzM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNjZlMGMwMzVmYWJkMjVhMjQyZjYzYjI2ZDU2OGY3NDQ4NzQxM2RhYzcxZWRiOGU1OTI2YzJmZDdiZGNjOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sj3CtilPWO9R04_DzXVDLtT_PrCb6xs24avVJJieLYs">

I found the configuration of editor and now the format-fixed repro is presented now.
still the issue exists.

**Comment by brc-dd** [comment]
Where is the error? That page is working as expected:

<img width="1800" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/b4506edd-4bde-4763-a661-95aeef618e23">

**Comment by fr1g** [comment]
> Where is the error? That page is working as expected:
> 
> <img alt="image" width="1800" src="https://private-user-images.githubusercontent.com/40380293/343129699-b4506edd-4bde-4763-a661-95aeef618e23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDU1NjMsIm5iZiI6MTcxOTQwNTI2MywicGF0aCI6Ii80MDM4MDI5My8zNDMxMjk2OTktYjQ1MDZlZGQtNGJkZS00NzYzLWE2NjEtOTVhZWVmNjE4ZTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEyMzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDkxN2Y1MjJlN2M0MmMxYTM2YmIzYWNiZDU4Zjg5MDY4ZGE3ZjEyYTYxZmNlZTdlNWExYzhjYmYwZWI5ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sZHx6qBYWD3Wssz1gVqqD-tscPWnMi-bDaERuIqpHcw">

how about accessing route /useSame ?
this page on my site also without error, and the useSame index.md has nearly same content but failed to render

**Comment by brc-dd** [comment]
on that page it's `​---` not `---` 

they both look the same but they are not.

**Comment by fr1g** [comment]
> on that page it's `​---` not `---`
> 
> they both look the same but they are not. (there is a zero width space in first) delete that hidden character from line 30 it will work fine:
> 
> <img alt="image" width="1230" src="https://private-user-images.githubusercontent.com/40380293/343167703-6f43598c-74f5-45d8-b2b7-40a29c60c52d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTE4ODgsIm5iZiI6MTcxOTQxMTU4OCwicGF0aCI6Ii80MDM4MDI5My8zNDMxNjc3MDMtNmY0MzU5OGMtNzRmNS00NWQ4LWIyYjctNDBhMjljNjBjNTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE0MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzg3NmI2ZDY2MWRmZmRmYjlkNjg4YzA1MDMzZWE3NGViZGQxYjdmZmEwNjI3MjQ1MDQ1N2ZiZWJlNjI1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wan0-20hnq8iFHXAoWJvUWFnIRyi8yKxj9pnxrSCPOQ">
> If you're using vscode, I recommend you to install https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins to find these characters easily.

this is kind of hilarious... why this character exists here, caused by the LF/CRLF difference?
anyway thanks, it do solved the problem
