### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 321paranoiawhy** [vuejs/vitepress#3972]
### Describe the bug

Such code:

````md
```vue twoslash :line-numbers
<script setup lang="ts">
import {ref} from 'vue';

const message = ref('Hello world!');
</script>
```
````

code block line numbers would be from 1 to 2, rather than from 1 to 5, [see here](http://localhost:5173/knowledge-base/TODO#bug)

### Reproduction

using such code in `vitepress`:

````md
```vue twoslash :line-numbers
<script setup lang="ts">
import {ref} from 'vue';

const message = ref('Hello world!');
</script>
```
````

### Expected behavior

line number works correctly

### System Info

```Text
none
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by 321paranoiawhy** [comment]
![image](https://github.com/vuejs/vitepress/assets/100689670/6c2abc06-a711-482a-bd08-9a6135364cba)

**Comment by brc-dd** [comment]
Please create this at shiki/twoslash repo.
