### ISSUE TITLE
I want to use mixed rendering of Markdown files and strings, how should I do it?

### ISSUE THREAD

**Issue by landun-maotao** [vuejs/vitepress#3973]
I have some markdown source code from a server, how can I mix it with the local markdown file for rendering?
Please tell me, what should I do? Thank you.

input:
```md
<script setup>
const subTitle = "## Second Title";
</script>

# App Title

{{ subTitle }}
```
output:
```html
<h1>App Title</h1>
<h2>Second Ttitle</h2>
```

**Comment by brc-dd** [comment]
Do you want to fetch and render it during build time or each time a user visits your site?

**Comment by landun-maotao** [comment]
> Do you want to fetch and render it during build time or each time a user visits your site?

yes,

**Comment by brc-dd** [comment]
Sorry, "yes" for which part
1) during build time?
2) each time a user visits your site?

**Comment by landun-maotao** [comment]
> Sorry, "yes" for which part
> 
> 1. during build time?
> 2. each time a user visits your site?

I need part1,

**Comment by brc-dd** [comment]
part 1 doesn't need client side markdown-it

You can use https://vitepress.dev/guide/data-loading and create and import a `.data.ts` file. Inside that file:

```ts
import { createMarkdownRenderer, defineLoader } from 'vitepress'

const config = (globalThis as any).VITEPRESS_CONFIG
const md = await createMarkdownRenderer(config.srcDir, config.markdown, config.site.base, config.logger)

const subTitle = '...'

export interface Data {
  subTitle: string
}

declare const data: Data

export default defineLoader({
  load(): Data {
    return {
      subTitle: md.render(subTitle)
    }
  }
})
```

Then in your page:

```vue
<script setup>
import { subTitle } from './path/to/your.data.js'
</script>

<div v-html="subTitle" />
```

**Comment by landun-maotao** [comment]
> part 1 doesn't need client side markdown-it
> 
> You can use https://vitepress.dev/guide/data-loading and create and import a `.data.ts` file. Inside that file:
> 
> ```ts
> import { createMarkdownRenderer, defineLoader, type SiteConfig } from 'vitepress'
> 
> const config = globalThis.VITEPRESS_CONFIG as SiteConfig
> const md = await createMarkdownRenderer(config.srcDir, config.markdown, config.site.base, config.logger)
> 
> const subTitle = '## Second Title'
> 
> export interface Data {
>   subTitle: string
> }
> 
> export declare const data: Data
> 
> export default defineLoader({
>   load(): Data {
>     return {
>       subTitle: md.render(subTitle)
>     }
>   }
> })
> ```
> 
> Then in your page:
> 
> ```
> # App Title
> 
> <div v-html="data.subTitle" />
> 
> <script setup lang="ts">
> import { data } from './foo.data.js'
> </script>
> ```

OK, I understand, thank you very much.

**Comment by landun-maotao** [comment]
OK, I understand, thank you very much.

**Comment by landun-maotao** [comment]
> Sorry, "yes" for which part
> 
> 1. during build time?
> 2. each time a user visits your site?



> Sorry, "yes" for which part
> 
> 1. during build time?
> 2. each time a user visits your site?

Sorry, I still want to know how to deal with part 2.

**Comment by brc-dd** [comment]
Ah, part 2 is bit tricky. You cannot use vitepress' renderer in client-side because it uses node-specific APIs. You can manually install markdown-it and try rendering but to have same output as vitepress you'll need to configure options and plugins same as ours (https://github.com/vuejs/vitepress/blob/main/src/node/markdown/markdown.ts#L196)

**Comment by landun-maotao** [comment]
> Ah, part 2 is bit tricky. You cannot use vitepress' renderer in client-side because it uses node-specific APIs. You can manually install markdown-it and try rendering but to have same output as vitepress you'll need to configure options and plugins same as ours (https://github.com/vuejs/vitepress/blob/main/src/node/markdown/markdown.ts#L196)

OK, please let me try it.

**Comment by landun-maotao** [comment]
> Ah, part 2 is bit tricky. You cannot use vitepress' renderer in client-side because it uses node-specific APIs. You can manually install markdown-it and try rendering but to have same output as vitepress you'll need to configure options and plugins same as ours (https://github.com/vuejs/vitepress/blob/main/src/node/markdown/markdown.ts#L196)

The process is cumbersome, so I decided to use the first method.
