### ISSUE TITLE
LastUpdated在Safari上不显示

### ISSUE THREAD

**Issue by BlazeSnow** [vuejs/vitepress#3974]
### Describe the bug

# <https://vitepress.dev/>
## Microsoft edge
![官网-电脑](https://github.com/vuejs/vitepress/assets/129476965/ebf0e663-df5d-4bfb-9b5f-1213375aa1ed)
## safari
![官网-ios](https://github.com/vuejs/vitepress/assets/129476965/ec3f115d-f13c-475a-9d1e-9785710d94ce)

# mywebsite
## Microsoft edge
![我的-电脑](https://github.com/vuejs/vitepress/assets/129476965/d78cd683-835d-4da8-9f90-9d581f84ad0a)
## safari
![我的-ios](https://github.com/vuejs/vitepress/assets/129476965/f60e95d1-df59-444e-9639-581128326751)

### Reproduction

LastUpdated在Safari上不显示

### Expected behavior

LastUpdated应当在Safari上显示

### System Info

```Text
Microsoft Edge
版本 126.0.2592.61 (正式版本) (64 位)

iOS 17.5.1
```

### Additional context

lastUpdated: {
			text: '上次更新时间',
			formatOptions: {
				localeMatcher: "best fit",
				weekday: undefined,
				era: undefined,
				year: "numeric",
				month: "long",
				day: "numeric",
				hour: "numeric",
				minute: "numeric",
				second: undefined,
				timeZoneName: "longGeneric",
				formatMatcher: "best fit",
				hour12: true,
				timeZone: "Asia/Chongqing"
			}
		},

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please share a minimal reproducible example in form of some git repo. I'm unable to reproduce this using just the config you've shared.

**Comment by BlazeSnow** [comment]
# <https://www.blazesnow.com/example>
## edge
![实例-电脑](https://github.com/vuejs/vitepress/assets/129476965/56990290-5e7b-4035-842a-42d86ab4290d)
## safari
![实例-ios](https://github.com/vuejs/vitepress/assets/129476965/6a015aba-0de8-4449-91f2-cc0237f44a08)

**Comment by brc-dd** [comment]
You have specified `lastUpdated: 2024-6-21 18:00` in frontmatter which is not valid yaml timestamp format - https://yaml.org/type/timestamp.html

It should be `lastUpdated: 2024-6-21 18:00:00`

Valid formats are:

```yaml
canonical:        2001-12-15T02:59:43.1Z
valid iso8601:    2001-12-14t21:59:43.10-05:00
space separated:  2001-12-14 21:59:43.10 -5
no time zone (Z): 2001-12-15 2:59:43.10
date (00:00:00Z): 2002-12-14
```
