### ISSUE TITLE
defineConfig 配置 base 属性 部分场景下出现的问题

### ISSUE THREAD

**Issue by Jeffrey-mu** [vuejs/vitepress#3975]
### Describe the bug

/** 
 * base: '/docs', 
 * 配置base 路径 
 * 资源地址部分场景无法自动填充docs路径
 * 如tailwind类名  动态img src 等等
 */ 

伪代码如下 我需要自定定义base值进行拼接。 期望可以像a标签自动解析

```vue
图片 src
<div class="grid grid-cols-4 justify-between gap-2 max-w-[400px]">
     <img v-for="item in supportFrameworks" :key="item.src" class="" :src="base + item.src" alt="">
 </div>

tailwindcss 
<section class="pt-32 relative md:min-h-[900px] pb-28 md:pb-0 md:bg-repeat-round bg-no-repeat -z-10" :class="[`bg-[url(${base}/images/mobile-bg.jpg)] md:bg-[url(${base}/images/1-2.png)]`]" style="background-size: cover; ">

```

### Reproduction

暂无

### Expected behavior

任何资源都可正常拼接base路径

### System Info

```Text
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 77.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    pnpm: 9.3.0 - /usr/local/bin/pnpm
    bun: 1.1.0 - /usr/local/bin/bun
  Browsers:
    Chrome: 126.0.6478.114
    Safari: 17.5
  npmPackages:
    vitepress: ^1.2.3 => 1.2.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It won't work because tailwind needs static classnames at build time.

**Comment by Jeffrey-mu** [comment]
> 它不起作用，因为 tailwind 在构建时需要静态类名。`:src`你可以这样做`withBase(item.src)`( `import {withBase} from 'vitepress'`)
>
Thank you for your reply, which can solve the dynamic path problem。 
> 如果需要，您可以在 tailwind 配置中将类列入安全列表，但无法使其与连接的字符串一起工作。
> 
> 更好的解决方法是将该字符串设置为变量`:style`，并在 tailwind 类名中使用该变量。
Using: style is a good solution

**Comment by brc-dd** [comment]
oh, if you're not sure how to use css variables with urls + tailwind `bg-x`, you can do something like this:

```vue
  <section
    class="relative -z-10 bg-[image:--bg] bg-cover bg-no-repeat pb-28 pt-32 md:min-h-[900px] md:bg-[image:--bg-md] md:bg-repeat-round md:pb-0"
    :style="{
      '--bg': `url('${withBase('images/mobile-bg.jpg')}')`,
      '--bg-md': `url('${withBase('images/1-2.png')}')`
    }"
  ></section>
```

**Comment by Jeffrey-mu** [comment]
> oh, if you're not sure how to use css variables with urls + tailwind `bg-x`, you can do something like this:
> 
> ```
>   <section
>     class="relative -z-10 bg-[image:--bg] bg-cover bg-no-repeat pb-28 pt-32 md:min-h-[900px] md:bg-[image:--bg-md] md:bg-repeat-round md:pb-0"
>     :style="{
>       '--bg': `url('${withBase('images/mobile-bg.jpg')}')`,
>       '--bg-md': `url('${withBase('images/1-2.png')}')`
>     }"
>   ></section>
> ```

Is this a unique style attribute of vitepress `--bg --bg-md`

**Comment by brc-dd** [comment]
> Is this a unique style attribute of vitepress --bg --bg-md

no, it can be anything, just make sure to use the same in class name - `bg-[image:--bg]` and `md:bg-[image:--bg-md]`

**Comment by Jeffrey-mu** [comment]
> > 这是 vitepress --bg --bg-md 的独特样式属性
> 
> 不，那些是 css 变量（https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties）
> 
> 你可以给它们起任何名字，只要确保在类名中使用相同的名称即可 -`bg-[image:--bg] md:bg-[image:--bg-md]`

I learned new knowledge today. Thank you very much
