### ISSUE TITLE
Unable to use aliases

### ISSUE THREAD

**Issue by norahmaria** [vuejs/vitepress#3976]
### Describe the bug

In my Vue app I use an alias for `@`, which works fine in the Vue app - but when importing any component into Vitepress that is using this alias, it fails to resolve the import.

`Failed to resolve import "@/example" from "src/Example.vue". Does the file exist?`

### Reproduction

I couldn't easily set up a reproduction example using the StackBlitz template, but made a [repository](https://github.com/norahmaria/vitepress-alias-example) with a minimal example.

The `Example.vue` component imports something from another file using the alias, and the component is used in the `example.md` Vitepress page. If you run `npm run docs:dev` and go to the `Example` page, you'll get the error.

### Expected behavior

I expect to be able to use aliases declared in my Vite config inside Vitepress, or to provide the aliases in the Vitepress config.

### System Info

```Text
System:
  OS: macOS 14.0
  CPU: (12) arm64 Apple M2 Max
  Memory: 16.44 GB / 64.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.6.1 - /opt/homebrew/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.8.1 - /opt/homebrew/bin/npm
  pnpm: 8.6.1 - ~/Library/pnpm/pnpm
Browsers:
  Chrome: 126.0.6478.63
  Safari: 17.0
```

### Additional context

I've seen some issues that could be relevant, but they seem to be about data files.

<img width="967" alt="vitepress-issue" src="https://github.com/vuejs/vitepress/assets/75345405/6ce16a10-b3c2-4c46-88f3-0687a8abb20b">

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
ah it should be `alias: { '@': fileURLToPath` in .vitepress/config.ts (without trailing slash)
