### ISSUE TITLE
Unable to run code `onload`

### ISSUE THREAD

**Issue by joepavitt** [vuejs/vitepress#3982]
### Describe the bug

No `onload` events are fired, unable to find a workaround or any other method for having two scripts load, where one is dependent upon other.

### Reproduction

```
head:
  - ['script', {}, "console.log('hello world'); window.addEventListener('load', () => {
    console.log('Creating form');
  })"]
```

Add this to the frontmatter. The `hello world` fires, but the `window`'s `load` never does. I've also tried `document.body.addEventListener...` but to no avail.

You can also try:

```html
<script setup>
  window.addEventListener('load', () => {
    console.log('Creating form from within script');
  })
</script>
```

which behaves the same

### Expected behavior

I should be able to run code `onload` of an element. 

### System Info

```Text
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 156.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v18.15.0/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.63
    Safari: 16.1
  npmPackages:
    vitepress: ^1.0.2 => 1.0.2
```

### Additional context

My specific use case here is that we are using Hubspot forms, which requires me to inject a static js file via a `<script />`, and also call a specific function that is dependent upon that script being loaded, i.e:

```html
<script src="/load/external/file" />
<script>
// run code dependent upon external file
</script>
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's because the window has already loaded before. That event won't fire twice. You can use `onMounted` from vue inside script setup.

**Comment by joepavitt** [comment]
Thanks @brc-dd - even if I added `onload` to the static HTML definitions, it still wouldn't fire. 

I will try the `onMounted` route

**Comment by brc-dd** [comment]
> even if I added onload to the static HTML definitions

Not sure what you meant by that, but it will be fired in build + preview mode if you directly visit the page. If you open it through some other page then it won't trigger because we don't do MPA navigation.
