### ISSUE TITLE
SSR issue with Teleport and conditional rendering of its children (Cannot read properties of null (reading 'nextSibling'))

### ISSUE THREAD

**Issue by TotomInc** [vuejs/vitepress#3987]
### Describe the bug

There is a SSR error on the production build output that happens with a specific user navigation (see below for reproduction steps).

When a `<Teleport />` has a conditional rendered children using `v-if`, the following error is thrown:

```shell
TypeError: Cannot read properties of null (reading 'nextSibling')
    at nextSibling (framework.w6niQ9Mc.js:17:682)
    at kt (framework.w6niQ9Mc.js:13:29640)
    at N (framework.w6niQ9Mc.js:13:21176)
    at v (framework.w6niQ9Mc.js:13:23760)
    at Object.process (framework.w6niQ9Mc.js:13:37355)
    at N (framework.w6niQ9Mc.js:13:21489)
    at v (framework.w6niQ9Mc.js:13:23760)
    at O (framework.w6niQ9Mc.js:13:23130)
    at L (framework.w6niQ9Mc.js:13:22048)
    at N (framework.w6niQ9Mc.js:13:21426)
```

### Reproduction

Minimal reproduction link: https://stackblitz.com/edit/vitepress-nextsibling-ssr-error

See the `TeleportedComponent.vue` and `error-demo.md` files.

___

**Reproduction steps**:

- Create a production build (`npm run docs:build`)
- Serve the production (`npm run docs:dev`)
- Go directly the URL where the custom component is imported
- Interact with the custom component button to trigger the menu
- An error is thrown in the console, the component doesn't work

Now, this issue can be avoided if the user go to any other page that doesn't contain the component, and go back to this page.

### Expected behavior

The conditional rendering of the children using a `v-if`, inside the `<Teleport />`, should not cause any issues on the first page load.

### System Info

```Text
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 95.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 8.15.1 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 126.1.67.123
    Chrome: 126.0.6478.126
    Safari: 17.5
  npmPackages:
    vitepress: 1.2.3 => 1.2.3
```

### Additional context

I've first noticed the issue when working on an open-source [vue3-select-component](https://github.com/TotomInc/vue3-select-component).

E.g. go to https://vue3-select-component.vercel.app/demo/single-select.html and interact with the component. You'll see the same error thrown in the console.

For reference: https://github.com/TotomInc/vue3-select-component/issues/78

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Why are you teleporting to undefined?

**Comment by TotomInc** [comment]
It shouldn't teleport to `undefined` since I've added the `:disabled` prop. According to Vue 3 docs, the teleport can be optional and dynamically enabled/disabled: https://vuejs.org/guide/built-ins/teleport.html#disabling-teleport

Since this is a feature of Vue, I've built my component on top of this.

See the following lines of the component for more details: https://github.com/TotomInc/vue3-select-component/blob/master/src/Select.vue#L433-L435

**Comment by brc-dd** [comment]
It's not a vitepress bug. You can reproduce this on vue playground.  I'm pretty sure even with disabled, Teleport is not supposed to work with non-existent targets. You can try creating an issue at https://github.com/vuejs/core 

https://play.vuejs.org/#__PROD____SSR__eNqlVMtu2zAQ/JWNiiItEMsOWvSgKkEfyKEF2hStj7rI0kphQpEESTk2DP97h5TsqIDhS6ULuY+Z2aGoXfLZmHTdc5IluausMJ4c+96QLFV7UyTeFcltoURntPW0I8sN7amxuqNLtF1+LFShKq2cJ8+SQ9VS002oe9OrmhuhuH6LqqFGuHvDasw3pXQccvl8oAYRNp47I0vP2BHltVhTJUvngpiRgetZpaFIsfJRHuHJV733WpHfGkbtsCsS+lRJUT0hcuS+GFboXFrRtmypY9Xn86ElioiAy5GOMq8n7EsN1KwWrlxJrpG4mGZGNaPy9Uw0R2q0HSYJhJhB+RL+2EkX+sztD2RhFWk0pWmaz80L6hywh4nnB4WDVWMqn08cxNb5rWRyFdBqRNJTLtIuIGAm9G0zaiRvcC4UF7NaWK680CqjSsu+UzH1LGr/kNH1YvEa+32gOg09nktk6ErbCuAs8F5/MBtaRCzAapvRSpbVUwyssGitxheU0aumac4zpP/aOVD9H4QZQDxv/KyUog2zo47tKb3AxSccbIa/yRUuDYAa0aaPTivcrAhVJIFNSLb3JpiJi5UNJCFXSqmfv8eYtz1fHeLVA1dPJ+KPbhNiRfLLsmO75iI55jxMZlyMkL778xMjTJKdrnuJ6jPJ3+xwzEHjUPYFHkL2pC6q/Rb/CUK1S3e38azcYaggNFTuY32R4D/x9czoL3Lfpe9jHxxN9n8BmuaRbw==
