### ISSUE TITLE
Hydration completed but contains mismatches.

### ISSUE THREAD

**Issue by congmucc** [vuejs/vitepress#3988]
### Describe the bug

Scenario:
1. I am encountering an issue seemingly related to Server-Side Rendering (SSR). Upon entering the website, it momentarily displays a normal article page before redirecting to a 404 error. Network requests indicate a successful 200 status (as shown in the attached image), yet the frontend persistently shows a 404 page. You can inspect the project at this GitHub repository（`https://github.com/congmucc/blog`） or directly visit `www.congmu.top`.
<img width="1246" alt="首页" src="https://github.com/vuejs/vitepress/assets/123617755/58d1f0aa-8e7f-4fb2-9cb3-83279d6acaf8">

<img width="1245" alt="例子" src="https://github.com/vuejs/vitepress/assets/123617755/1f829896-1a58-4a76-b000-cdeeaf1c0415">

2. The browser's console logs the error, "Hydration completed but contains mismatches."
<img width="1234" alt="error" src="https://github.com/vuejs/vitepress/assets/123617755/0551e73e-25a0-44e7-a199-06a070611e14">

3. Locally, everything operates without any issues. However, problems emerged after configuring Nginx. My intention was to introduce multilingual functionality. Prior to making these changes, articles rendered correctly. The errors began surfacing following the adjustments made in accordance with the official documentation. The configuration details are outlined within the README document for your reference.
<img width="1213" alt="Locally" src="https://github.com/vuejs/vitepress/assets/123617755/121c4322-5145-43ce-8314-fde02cb90e2b">

4. For insight into the configuration changes, please refer to the .vitepress/config.mts file. Notably, since its last stable operation, new additions include the locales attribute and the creation of an docs/en directory to accommodate English translations.
<img width="1204" alt="content" src="https://github.com/vuejs/vitepress/assets/123617755/162af332-ff38-4757-ab34-0988d0b2ab38">
<img width="1204" alt="content" src="https://github.com/vuejs/vitepress/assets/123617755/162af332-ff38-4757-ab34-0988d0b2ab38">

5. I have searched online, checked through VitePress's issues section, and consulted the official documentation, but I haven't found relevant solutions online or in the issues. Unfortunately, I am having difficulty understanding the official documentation.

场景：

1. 我这里出现了一个好像是ssr的错误，进入网站会闪一下正常的文章之后跳转404，网络请求中是有数据200（如下图所示），但是前端的页面总是404，项目链接：`https://github.com/congmucc/blog`， 您可以登录`www.congmu.top`进行查看

2. 控制台会爆这个错误：`Hydration completed but contains mismatches.`

3. 并且我在本地是完全没有问题的，但是配置nginx后就出现了问题，我想要添加的功能是添加多语言配置，在添加之前我是能正常显示文章的，我按照官方文档添加之后就出现了目前的错误，配置文件在我的README文档里面，您可以看一下

4. 您可以查看文件`.vitepress/config.mts`来查看我的配置文件，相比于之前能正常运行新增了`locales`属性，以及`docs/en`文件夹。

5. 我网络上搜了一下，也搜了vitepress的issues，以及官方文档，但是网络和issues没有相关的答案，官方文档我看不懂
Looking forward to getting a reply, thank you!!!

### Reproduction

directly visit `www.congmu.top`

### Expected behavior

Scenario:
1. I am encountering an issue seemingly related to Server-Side Rendering (SSR). Upon entering the website, it momentarily displays a normal article page before redirecting to a 404 error. Network requests indicate a successful 200 status (as shown in the attached image), yet the frontend persistently shows a 404 page. You can inspect the project at this GitHub repository（`https://github.com/congmucc/blog`） or directly visit `www.congmu.top`.

2. The browser's console logs the error, "Hydration completed but contains mismatches."

3. Locally, everything operates without any issues. However, problems emerged after configuring Nginx. My intention was to introduce multilingual functionality. Prior to making these changes, articles rendered correctly. The errors began surfacing following the adjustments made in accordance with the official documentation. The configuration details are outlined within the README document for your reference.

4. For insight into the configuration changes, please refer to the .vitepress/config.mts file. Notably, since its last stable operation, new additions include the locales attribute and the creation of an `docs/en` directory to accommodate English translations.

5. I have searched online, checked through VitePress's issues section, and consulted the official documentation, but I haven't found relevant solutions online or in the issues. Unfortunately, I am having difficulty understanding the official documentation.

### System Info

```Text
browsers
```

### Additional context

<img width="1204" alt="content" src="https://github.com/vuejs/vitepress/assets/123617755/b2fab6a2-7c22-4d11-88c9-55574489da91">
<img width="1234" alt="error" src="https://github.com/vuejs/vitepress/assets/123617755/f91bce1d-2185-42fa-96af-e9d34e21dad1">
<img width="1246" alt="首页" src="https://github.com/vuejs/vitepress/assets/123617755/460aead3-7417-4cf2-b2c7-20749fd95c24">
<img width="1213" alt="Locally" src="https://github.com/vuejs/vitepress/assets/123617755/7b7abcb3-e968-4ae7-8c57-5019f0d5b124">
<img width="1245" alt="例子" src="https://github.com/vuejs/vitepress/assets/123617755/2d27062c-35d7-4c9a-973f-389def29c92c">

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by congmucc** [comment]
Sorry, my english is bad,My expected behavior should be that the page produces the correct article information and can switch between Chinese and English languages

**Comment by Zhengqbbb** [comment]
```sh
DEBUG='*' pnpm run build
DEBUG='*' pnpm run preview
```

**Comment by brc-dd** [comment]
You've specified `base: './'` in your vite config. Relative bases are not supported.

**Comment by congmucc** [comment]
> You've specified `base: './'` in your vite config. Relative bases are not supported.您已在 vite 配置中指定 `base: './'` 。不支持相对碱基。

那我该如何正确的设置呢？

**Comment by congmucc** [comment]
> You've specified `base: './'` in your vite config. Relative bases are not supported.您已在 vite 配置中指定 `base: './'` 。不支持相对碱基。

So how do I set it up correctly?

**Comment by brc-dd** [comment]
You can just remove that line.

**Comment by congmucc** [comment]
> ```shell
> DEBUG='*' pnpm run build
> DEBUG='*' pnpm run preview
> ```

wait，I've never used this model before, so let me learn

**Comment by congmucc** [comment]
> You can just remove that line. Why did you add that? 👀您可以删除该行。你为什么要添加它？👀

I forgot, it seemed that I wanted to set up something at the time

**Comment by congmucc** [comment]
> You've specified `base: './'` in your vite config. Relative bases are not supported. Removing it works fine.

oh，this great, you're right, this problem was solved.

**Comment by congmucc** [comment]
> You can just remove that line. Why did you add that? 👀

Thank you very very very much

**Comment by Zhengqbbb** [comment]
Remove: https://github.com/congmucc/blog/blob/191bf1cd4cc7baf420832b5dd470473c738b4779/.vitepress/config.mts#L16

**Comment by congmucc** [comment]
> Remove: https://github.com/congmucc/blog/blob/191bf1cd4cc7baf420832b5dd470473c738b4779/.vitepress/config.mts#L16

It's been solved.,It's me who has to 'vite.config.ts' in the configuration is wrong.,Thank you.,Thank you.
