### ISSUE TITLE
How to Internationalize Everything?

### ISSUE THREAD

**Issue by TAYBI** [vuejs/vitepress#3994]
How to Internationalize Everything?

For example, I want to change the "Doc" label text and the hints in search. How can I do that?

![image](https://github.com/vuejs/vitepress/assets/38045842/d2ec6a9f-fb8b-4a47-a7eb-25035eb005cf)
![image](https://github.com/vuejs/vitepress/assets/38045842/28342fc6-6c9b-41c5-93fb-49bd0fb1273a)

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/default-theme-search#local-search-i18n, https://vitepress.dev/reference/default-theme-config#outline
