### ISSUE TITLE
dev works but build not work

### ISSUE THREAD

**Issue by JiuRanYa** [vuejs/vitepress#3995]
### Describe the bug

This is a same issue #2137.

If I build with `debug=true`, all things work.

I just want to know Is there any better way to debug the error in vitepress.

So confused. I got noting with the error message.

![image](https://github.com/vuejs/vitepress/assets/58846658/f7df5c3b-528f-44a8-841e-87774a574894)

### Reproduction

Nothing

### Expected behavior

works

### System Info

```Text
mac m3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can't help without reproduction.
