### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vitepress#40]
Ref: https://vuepress.vuejs.org/theme/default-theme-config.html#search-box

**Comment by appbest** [comment]
国庆期间，编写全站搜索组件与 代码在线运行组件
[搜索文档模板](https://github.com/appbest/QuickDocs)

**Comment by fimbault** [comment]
Would be nice to use https://www.meilisearch.com

**Comment by meganmeiyang** [comment]
hi should you update the doc as well: https://vitepress.vuejs.org/guide/theme-search.html
thanks ~

**Comment by Eviwang** [comment]
```
 themeConfig: {
    search: true,
    searchMaxSuggestions: 10
  }
```
not work.

**Comment by brc-dd** [comment]
@Eviwang This was for older versions. Refer https://github.com/vuejs/vitepress/issues/1078 and https://github.com/vuejs/vitepress/issues/670 for updated stuff.
