### ISSUE TITLE
vitepress使用import动态导入xx.vue文件时报错，TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".vue" 

### ISSUE THREAD

**Issue by zhanglp520** [vuejs/vitepress#4002]
### Describe the bug

const getCode = async () => {
const url=ref(`test.vue`)
    const res = await import(/* @vite-ignore */ `${url}?raw`);
    return res.default;
};
const code= getCode ();
console.log('code=>',code);

使用import动态导入vue文件，获取文件的内容事，报错。
执行命令pnpm run docs:dev  不会报错。
当执行pnpm run docs:build  报错。报错如下
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".vue" for \examples\src\views\crud\baseDefault.vue
Node.js v16.19.0
Node.js v18.18.2
Node.js v20.10.0
Node.js v21.5.0
都测试过依然存在此问题。问题存在vitepress项目，而vite项目测试打包是么问题的。

### Reproduction

执行命令：pnpm run docs:build

### Expected behavior

执行 pnpm run docs:build能正常打包。即使能绕过报错也可以。

### System Info

```Text
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 4.40 GB / 15.89 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Chromium (126.0.2592.68)
    Internet Explorer: 11.0.22621.3527
```

### Additional context

![image](https://github.com/vuejs/vitepress/assets/110772402/b8e85c49-9859-4d3f-b6e8-b92969372525)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Read - https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations and remove `/* @vite-ignore */`

Something like this will work:

```ts
const getCode = async () => {
  const url = ref('test')
  const res = await import(`./${url.value}.vue?raw`)
  return res.default
}
```
