### ISSUE TITLE
Hide prev/next buttons when there is only 1 candidate

### ISSUE THREAD

**Issue by Trinovantes** [vuejs/vitepress#4003]
### Is your feature request related to a problem? Please describe.

I have a root index file with some text that also contains a table of contents to child pages. However, the next page link on the root file simply points to itself which I think is a bit confusing for readers.

I would like the option to programmatically hide prev/next buttons on pages that circles back to itself because it's very tedious to manually add `prev:false` and `next: false` to every page that falls under this case.

Here's the sidebar links that causes the issue for me:
```json
    [
        {
            "text": "Introduction",
            "base": "/",
            "link": "introduction/index",
            "items": [
                {
                    "text": "A",
                    "base": "/",
                    "link": "introduction/a"
                },
                {
                    "text": "B",
                    "base": "/",
                    "link": "introduction/b"
                }
            ]
        }
    ]
```

### Describe the solution you'd like

Either:

* An explicit option like `hidePrevNextWhenSingleChild`
* Allow `themeConfig.docFooter.prev` and `themeConfig.docFooter.next` to accept a callback function that allows the user to check the current page and link candidates and return true/false

### Describe alternatives you've considered

I'm currently running a script to read my sidebar config and programmatically editing the frontmatter of index pages that match my criteria but this is very error prone.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
link should start with slash

**Comment by brc-dd** [comment]
remove `/index` from that link, it'll work fine.
