### ISSUE TITLE
md文件名包含百分号会报错

### ISSUE THREAD

**Issue by kainy** [vuejs/vitepress#4006]
### Describe the bug

URI is malformed

### Reproduction

新建文章 4%4.md ，然后编译会报错，无法打开页面。

### Expected behavior

期望正常打开页面，不提示报错信息：URI is malformed

### System Info

```Text
MacOS chrome
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not supported. Won't fix.

**Comment by kainy** [comment]
> Not supported. Won't fix.

方便告知理由麽? 我理解這種場景還蠻常見的，特別是從別的程序遷移到 vitepress 的時候。

**Comment by brc-dd** [comment]
> 我理解這種場景還蠻常見的

It's not common at all. You're the first one to report this. Special characters like % have different meaning in URLs and will mess up the routing.
