### ISSUE TITLE
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'https:' Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'https:'

### ISSUE THREAD

**Issue by wspromise** [vuejs/vitepress#4007]
### Describe the bug

build error:
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'https:'
Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'https:'
    at new NodeError (node:internal/errors:405:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:149:11)
    at defaultLoad (node:internal/modules/esm/load:99:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:417:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:288:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at #createModuleJob (node:internal/modules/esm/loader:312:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:265:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:251:17)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:21)

### Reproduction

，，，

### Expected behavior

normal

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 9.1.3 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: 1.2.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wspromise** [comment]
vitePress build failed

**Comment by brc-dd** [comment]
Please provide minimal reproducible example.

**Comment by wspromise** [comment]
https://stackblitz.com/edit/vite-nnfopi?file=docs%2F.vitepress%2Fconfig.ts

**Comment by wspromise** [comment]
> Please provide minimal reproducible example, preferably using https://vitepress.new

https://stackblitz.com/edit/vite-nnfopi?file=docs%2F.vitepress%2Fconfig.ts

**Comment by brc-dd** [comment]
Looks like you haven't saved it. That link is just opening a fork of template.

**Comment by wspromise** [comment]
> Looks like you haven't saved it. That link is just opening a fork of template.

https://stackblitz.com/edit/vite-qg6fun?file=docs%2F.vitepress%2Fconfig.ts,package.json

**Comment by brc-dd** [comment]
```ts
// 引入图标库
import 'https://lf1-cdn-tos.bytegoofy.com/obj/iconpark/icons_11053_364.62f38b08ba47924e13314f4c49fbf675.es5.js';
```

as the error says this is not supported.

**Comment by wspromise** [comment]
Thank you, you are right
