### ISSUE TITLE
npm run docs:build -> [vitepress] spawn git EAGAIN

### ISSUE THREAD

**Issue by TONY-STARK-TECH** [vuejs/vitepress#4008]
### Describe the bug

```
➜  npm run docs:build

> docs:build
> vitepress build .


  vitepress v1.2.3

x Build failed in 20.52s
✖ building client + server bundles...
build error:
[vitepress] spawn git EAGAIN
file: xx/xx/docs/software/windows/navicat-charts-viewer-win.md
[vitepress] spawn git EAGAIN
file: xx/xx/docs/software/windows/navicat-charts-viewer-win.md
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Reproduction

-

### Expected behavior

-

### System Info

```Text
System:
    OS: macOS 12.7.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 169.53 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v18.20.3/bin/npm
    pnpm: 9.1.4 - ~/Library/pnpm/pnpm
    bun: 1.1.12 - /usr/local/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    vitepress: ^1.2.3 => 1.2.3
```

### Additional context

-

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide minimal reproducible example and output of `git --version`.

**Comment by TONY-STARK-TECH** [comment]
git version 2.44.0

**Comment by TONY-STARK-TECH** [comment]
i don't think it was caused by `git`; 

...

**Comment by brc-dd** [comment]
are you able to run this command from where you're running docs:build:

```sh
git log -1 --pretty="%ai" path/to/your/navicat-charts-viewer-win.md
```

**Comment by TONY-STARK-TECH** [comment]
> ```shell
> git log -1 --pretty="%ai"
> ```

<img width="253" alt="image" src="https://github.com/vuejs/vitepress/assets/165481157/083eb6c3-e35d-4ef5-95f6-7ea0d945f659">

its a dynamic generate page；

will generate about more than 2000 pages.

**Comment by TONY-STARK-TECH** [comment]
[pkg].md
```md
---
layout: doc
---

<script setup>
import { useData } from 'vitepress'
import { onMounted } from 'vue'

const { params } = useData()

onMounted(() => {
    document.title = params.value.title + ' For Windows'
})

</script>

<h1>{{ $params.title }} For Windows</h1>

::: info
{{ $params.lu }}[our mail](mailto:xxx@gmail.com)
:::

download URL：
<a v-for="dl in $params.download" :href="dl.url" style="margin-left: 20px;" target="_blank">
    {{ dl.type === 'bdp' ? 'A' : 'B' }}
</a>

PWD：
<span v-for="dl in $params.download" style="margin-left: 20px;">
    {{ dl.type === 'bdp' ? 'A(' + dl.pwd + ')' : 'B(' + dl.pwd + ')' }}
</span>

<!-- @content -->

```

[pkg].path.hs
```md
export default {
  paths() {
    return [{"params":{"pkg":"zettlr-win","title":"Free xxx","lu":"2024-06-12 18:02","download":[{"type":"bdp","url":"https://xxx","pwd":"95a"},{"type":"quk","url":"https://xxx","pwd":"Uxm"}]}, ... ]
```

**Comment by brc-dd** [comment]
I've pushed a fix, but I'm not sure if it will work. You can try building vitepress locally and using it or maybe wait for next release and give it a try.

**Comment by brc-dd** [comment]
Seems like you're trying to use clean urls (urls without .html) but haven't set cleanUrls: true in your config.

**Comment by TONY-STARK-TECH** [comment]
vercal ～ 

ok，i'll set this prop and have a try. very thanks.

**Comment by brc-dd** [comment]
On vercel, you need to set it inside vercel.json too: https://vercel.com/docs/projects/project-configuration#cleanurls

https://vitepress.dev/guide/routing#generating-clean-url
