### ISSUE TITLE
Dynamic images used inside custom theme don't get bundled

### ISSUE THREAD

**Issue by mzenz** [vuejs/vitepress#4010]
### Describe the bug

Importing images dynamically inside a Vitepress custom theme via `import.meta.url` (as documented in [Vite's docs](https://vitejs.dev/guide/assets#new-url-url-import-meta-url)) only works in development/HMR mode. When building the site, Vitepress fails to bundle the dynamically-loaded images.

This feature is useful for building generic theme Vue components that "augments" a markdown document's rendered content, for example to add a custom thumbnail image to a blog post card. Another very important reason to resolve such urls is for SEO purposes where we can programmatically link images to `<meta>` tags (e.g. `og:image`, etc).

[Vitepress docs](https://vitepress.dev/guide/asset-handling) don't seem to mention how to do this properly, and since it works in dev/HMR mode but not in build/PROD mode I'm assuming it's a bug of some kind.

Thoughts?

### Reproduction

- `git clone https://github.com/mzenz/vitepress-dynamic-images-bug.git`
- `cd vitepress-dynamic-images-bug`
- `pnpm install`
- `pnpm build && pnpm preview`

### Expected behavior

Just like in HMR/dev mode, thumbnail image should display along rendered markdown document.

### System Info

```Text
System:
  OS: Linux 6.9 Fedora Linux 40 (Workstation Edition)
  CPU: (16) x64 AMD Ryzen 9 6900HS with Radeon Graphics
  Memory: 26.34 GB / 38.50 GB
  Container: Yes
  Shell: 3.7.0 - /usr/bin/fish
Binaries:
  Node: 20.12.2 - /usr/bin/node
  Yarn: 1.22.22 - /usr/bin/yarn
  npm: 10.5.0 - /usr/bin/npm
  pnpm: 9.0.6 - /usr/bin/pnpm
npmPackages:
  vitepress: ^1.2.3 => 1.2.3
```

### Additional context

Compare results with running in dev mode via `pnpm dev` where thumbnail image displays properly.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's not supported in vite too. That document you've linked states that:

> However, **_the URL string must be static so it can be analyzed_**, otherwise the code will be left as is, which can cause runtime errors if build.target does not support import.meta.url

> Does not work with SSR

You can ask the users to store such images in their [public directory](https://vitepress.dev/guide/asset-handling#the-public-directory) and then you can just do `<img src="frontmatter.thumbnail" ... />`
