### ISSUE TITLE
⠴ rendering pages...file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/.vitepress/.temp/docs_components_charts.md.js?t=1719917833866:7662   return dom.getAttribute ? dom.getAttribute(key) : dom[key];              ^  TypeError: Cannot read properties of null (reading 'getAttribute')

### ISSUE THREAD

**Issue by wspromise** [vuejs/vitepress#4011]
### Describe the bug

mment will be removed to avoid issues.
✓ building client + server bundles...
⠴ rendering pages...file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/.vitepress/.temp/docs_components_charts.md.js?t=1719917833866:7662
  return dom.getAttribute ? dom.getAttribute(key) : dom[key];
             ^

TypeError: Cannot read properties of null (reading 'getAttribute')
    at getAttribute (file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/.vitepress/.temp/docs_components_charts.md.js?t=1719917833866:7662:14)
    at getInstanceByDom (file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/.vitepress/.temp/docs_components_charts.md.js?t=1719917833866:23786:20)
    at init$1 (file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/.vitepress/.temp/docs_components_charts.md.js?t=1719917833866:23764:25)
    at drawChart (file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/.vitepress/.temp/docs_components_charts.md.js?t=1719917833866:73221:15)
    at file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/.vitepress/.temp/docs_components_charts.md.js?t=1719917833866:73236:13

Node.js v18.20.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Reproduction

太多了，没办法写

### Expected behavior

normal

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 9.1.3 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: 1.2.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please share a minimal, reproducible example, preferably using https://vitepress.new. We can't possibly know what you've coded with just that error message.

请提供一个最小的、可复现的示例，最好使用 https://vitepress.new。仅凭错误信息我们无法知道你编写了什么代码。

**Comment by wspromise** [comment]
https://stackblitz.com/~/github.com/wspromise/components-ui?file=package.json

**Comment by wspromise** [comment]
pnpm run docs:build

return dom.getAttribute ? dom.getAttribute(key) : dom[key];
^

TypeError: Cannot read properties of null (reading 'getAttribute')

**Comment by brc-dd** [comment]
That op-template repo is private. But there it might be because of this:

```
::: details 查看代码
::: code-group
```

If you need to nest them, you need to increase dots and close both of them later:

```
:::: details 查看代码
::: code-group

...

:::
::::
```

**Comment by wspromise** [comment]
It seems that this is not the error. It is because echarts is used. There is no problem when running, but the packaging will fail.

**Comment by wspromise** [comment]
![Snipaste_2024-07-03_17-49-19](https://github.com/vuejs/vitepress/assets/43053038/09dd5b0f-c6f9-427c-a0a3-e56ee7eb66b3)

**Comment by brc-dd** [comment]
Ah, maybe need to wrap that with `<ClientOnly>` as those APIs won't be available on SSR render.

**Comment by wspromise** [comment]
Thank you very much, you are indeed a big shot, your ability is unique
