### ISSUE TITLE
Blockquotes support this style?

### ISSUE THREAD

**Issue by baixjian** [vuejs/vitepress#4013]
### Describe the bug

> 原作者： [https://github.com/xxx](https://github.com/xxx)
### Reproduction

-

### Expected behavior

-

### System Info

```Text
-
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah they do:

<img width="1035" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/2fddec46-9fe2-4ce8-b933-23c44d19664c">

What's the issue?

**Comment by brc-dd** [comment]
Please reopen if you still have doubts/issues.
