### ISSUE TITLE
使用数据统计功能

### ISSUE THREAD

**Issue by zhengjiaocc** [vuejs/vitepress#4015]
### Is your feature request related to a problem? Please describe.

怎么样引入数据统计功能呢，例如51LA的数据统计和他的外挂组件

### Describe the solution you'd like

在文档里添加解决方案

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I don't speak Chinese and Google Translate isn't working on their docs site, but looking at the screenshots, I think you just need to save that `js-sdk-pro.min.js` to your public directory and add it via head - https://vitepress.dev/reference/site-config#head

```ts
import { defineConfig } from 'vitepress'

export default defineConfig({
  head: [
    ['script', { src: '/js-sdk-pro.min.js' }],
    ['script', {}, `LA.init({ id: '...', hashMode: true })`]
  ]
})
```

It's showing some toggle button for vue/react too, but code for that is not shown in the docs. So, the head might be somewhat different than above example.
