### ISSUE TITLE
Why is it that when the project content is not changed, many files are modified after each build?

### ISSUE THREAD

**Issue by Perrywzp** [vuejs/vitepress#4016]
### Describe the bug

Why is it that when the project content is not changed, many files are modified after each build?
like app.[hash].js chunk.[hash].js metadata.[hash].js
like this 
![image](https://github.com/vuejs/vitepress/assets/10015609/ac04e507-111a-4189-9e7f-f64ebc35487d)

### Reproduction

...

### Expected behavior

can don`t change that files after build, when we did`nt change any files in the project.

### System Info

```Text
win10
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Because they need to be fingerprinted. If even a single character in that file is changed, the hash of all files that depend on that file will change.

**Comment by Perrywzp** [comment]
but i didn`t change any file。but when repeat build this project , the resource has changed.

**Comment by brc-dd** [comment]
Sorry. Did you rename or move any file? Can you share your repo or create some dummy one to show the example?

**Comment by Perrywzp** [comment]
i think you can try init a clean project , create sidebar like under picture.
![image](https://github.com/vuejs/vitepress/assets/10015609/876769e2-cc8f-410c-9a52-0ca4482c9ffc)
and add metadata props in themconfig or not. then try repeat build , compare the resource , you will find a lot of changed files。like html or like metadata.[hash].js
