### ISSUE TITLE
Components at the start of a line/paragraph don't render their contents as Markdown

### ISSUE THREAD

**Issue by segevfiner** [vuejs/vitepress#4017]
### Describe the bug

Components at the start of a line/paragraph don't render their contents as Markdown despite other Markdown renders doing so.

### Reproduction

https://stackblitz.com/edit/vite-jgrywo?file=docs%2Findex.md

Look at "Some Markdown" line. I expected it to render as Markdown...

### Expected behavior

It should render as Markdown. When rendered by other systems at least it does. e.g. VS Code Markdown preview.

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: latest => 1.2.3
```

### Additional context

VitePress:
![Screenshot](https://github.com/vuejs/vitepress/assets/24731903/b5813979-8069-4735-842c-8ba553e29057)

VS Code:
![Screenshot](https://github.com/vuejs/vitepress/assets/24731903/a14b7977-2a26-4ffb-a86a-abd8938a0852)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Markdown should be separated from HTML/Vue content by new lines - https://spec.commonmark.org/0.31.2/#html-blocks

**Comment by segevfiner** [comment]
@brc-dd That's not correct. This is inline HTML according to spec compliant parsers. Not block HTML. e.g. From markdown-it parsing:
<details><summary>markdown-it tokens</summary>

```json
{
      "type": "inline",
      "tag": "",
      "attrs": null,
      "map": [
        1,
        2
      ],
      "nesting": 0,
      "level": 1,
      "children": [
        {
          "type": "html_inline",
          "tag": "",
          "attrs": null,
          "map": null,
          "nesting": 0,
          "level": 0,
          "children": null,
          "content": "<SomeComp>",
          "markup": "",
          "info": "",
          "meta": null,
          "block": false,
          "hidden": false
        },
        {
          "type": "text",
          "tag": "",
          "attrs": null,
          "map": null,
          "nesting": 0,
          "level": 0,
          "children": null,
          "content": "Some ",
          "markup": "",
          "info": "",
          "meta": null,
          "block": false,
          "hidden": false
        },
        {
          "type": "link_open",
          "tag": "a",
          "attrs": [
            [
              "href",
              "https://vitepress.dev"
            ]
          ],
          "map": null,
          "nesting": 1,
          "level": 0,
          "children": null,
          "content": "",
          "markup": "",
          "info": "",
          "meta": null,
          "block": false,
          "hidden": false
        },
        {
          "type": "text",
          "tag": "",
          "attrs": null,
          "map": null,
          "nesting": 0,
          "level": 1,
          "children": null,
          "content": "Markdown",
          "markup": "",
          "info": "",
          "meta": null,
          "block": false,
          "hidden": false
        },
        {
          "type": "link_close",
          "tag": "a",
          "attrs": null,
          "map": null,
          "nesting": -1,
          "level": 0,
          "children": null,
          "content": "",
          "markup": "",
          "info": "",
          "meta": null,
          "block": false,
          "hidden": false
        },
        {
          "type": "html_inline",
          "tag": "",
          "attrs": null,
          "map": null,
          "nesting": 0,
          "level": 0,
          "children": null,
          "content": "</SomeComp>",
          "markup": "",
          "info": "",
          "meta": null,
          "block": false,
          "hidden": false
        }
      ],
      "content": "<SomeComp>Some [Markdown](https://vitepress.dev)</SomeComp>",
      "markup": "",
      "info": "",
      "meta": null,
      "block": true,
      "hidden": false
    },
```
</details>

And it clearly rendering correctly in other CommonMark parsers/renderers that are spec compliant. Please reopen.

**Comment by brc-dd** [comment]
There is no way to tell if a vue component is an inline html element so all of them are treated a block ones by default, and behave like them:

<img width="923" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/f94bcf69-2fa6-4147-a6ea-59f5dd0bb510">

**Comment by segevfiner** [comment]
But that doesn't match other CommonMark renderers... Which seem quite capable of deciding based on the rules laid out in the CommonMark spec. This causes quite an issue for me... Looks like I'll have to look at a different project then... 😢 

AFAIK, the rule is basically this:
> Start condition: line begins with a complete [open tag](https://spec.commonmark.org/0.31.2/#open-tag) (with any [tag name](https://spec.commonmark.org/0.31.2/#tag-name) other than pre, script, style, or textarea) or a complete [closing tag](https://spec.commonmark.org/0.31.2/#closing-tag), followed by zero or more spaces and tabs, followed by the end of the line.
End condition: line is followed by a [blank line](https://spec.commonmark.org/0.31.2/#blank-line).

**Comment by brc-dd** [comment]
The rules in commonmark spec don't cover vue in markdown. Yeah feel free to use other projects.

**Comment by segevfiner** [comment]
Well... if vitepress followed the rule outlined in the CommonMark spec for identifying HTML block elements to identify Vue syntax, which is basically HTML, with some slight differences, it wouldn't result in such rendering differences. With the downside of requiring a newline when a component is at the start of a line to be treated as block, where otherwise it would have been treated as inline. (Vitepress will need to identify inline Vue components as well if it doesn't now).

IMHO I think this is more correct and faithful to the CommonMark spec, and also to MDX (Although MDX purposefully breaks CommonMark in other areas). That is, this also works correctly in MDX.

**Comment by brc-dd** [comment]
If we start treating Vue components in markdown as inline then we will end up with `<p><SomeComponent>...</SomeComponent></p>` and if `<SomeComponent>` renders any block element like `<div>` it will result in invalid HTML. And there isn't any feasible way to tell if a component has any such element during markdown to vue conversion step.

MDX is able to handle these thing because it's parser and renderer is written with that in mind. For example, even `<div>*md*</div>` despite being treated like inline HTML elements won't render a wrapping `<p>` there.

We are not big and paid enough to create a spec and write a parser+renderer compliant to that. We are just hacking our way through markdown-it. Like I said earlier, use some MDX tool if you want that. VitePress won't fix this and Nuxt's MDC doesn't support Vue like syntax for component. The only choice is using React/Preact based frameworks like Next.js (nextra / fuma) or Docusaurus / Vocs if you want to use components inside markdown. Or just go native and create web components or something and use them in your commonmark compliant renderer.
