### ISSUE TITLE
在 Markdown 中创建链接，跳转 html 文件会进入 404 。同样的路径可以正常打开 md 文件【If you create a link in Markdown, the html file will go to 404. The same path can open the md file normally】

### ISSUE THREAD

**Issue by wangshangluobai** [vuejs/vitepress#4020]
### Describe the bug

在同一个md文件中创建两个链接【Create two links in the same md file】
```md
[示例页面 index12](/index12){target="_self"}
[示例页面 underline](/underline){target="_self"}
```
前者[示例页面 index12]可以正常打开显示文件内容【The former [示例页面 index12] opens normally to display the contents of the file】
但后者会进入404页面【The latter will result in a 404 page】
![1720071298368](https://github.com/vuejs/vitepress/assets/50696755/ae2fa631-70ad-4fc3-8ce7-c45422feb41c)

### Reproduction

https://github.com/wangshangluobai/otherchannel.git
相关文件在此仓库【Relevant documents are in this warehouse】

### Expected behavior

我期望和 文档中的演示一致 【I expect to be consistent with the presentation in the documentation】
https://vitepress.dev/zh/guide/routing

#链接到非 VitePress 页面

像正常打开[pure.html](https://vitepress.dev/pure)文件一样，在我的示例中打开相似的html文件
【As a normal open [pure HTML] (https://vitepress.dev/pure) file, open in my example similar to the HTML file】

### System Info

```Text
控制台等无输出信息，进入404页面
```

### Additional context

![image](https://github.com/vuejs/vitepress/assets/50696755/fcfd2cb4-3cc1-40e0-a5da-64924abe182e)
![image](https://github.com/vuejs/vitepress/assets/50696755/4f2f0cba-4810-4ecb-bd84-973dc669272f)
![image](https://github.com/vuejs/vitepress/assets/50696755/ab64f5e1-d622-442c-93d4-73e42f475f2b)
![image](https://github.com/vuejs/vitepress/assets/50696755/f6de6884-7446-440a-aaf1-55045dd0a27f)
![image](https://github.com/vuejs/vitepress/assets/50696755/6782e6f8-f889-42b1-a934-f3028111e400)
![image](https://github.com/vuejs/vitepress/assets/50696755/aebf9d2c-a23a-4d23-a208-4c4ea72c13fc)
![image](https://github.com/vuejs/vitepress/assets/50696755/71da7609-2a2b-4de0-8ee5-64dd1f7a3de7)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wangshangluobai** [comment]
在文档中的效果是正常的，应该是我忽略了什么，或许是路径配置的不正确，但我查看了文档的源码，并没有发现什么特殊的地方，是因为html文件不需要打包，直接放在public中，所以我不能像引用md文件一样引用html文件吗？【The effect in the document is normal, it should be that I ignored something, perhaps the path configuration is incorrect, but I looked at the source code of the document, and did not find anything special, because the html file does not need to be packaged, directly placed in public, so I can not reference the html file like the md file?】

**Comment by brc-dd** [comment]
Ah you need to keep the html files in public/ directory

**Comment by wangshangluobai** [comment]
我注意到了文档源码中是放在了public中，是必须要这样做吗？【I noticed that the document source code is placed in public, is it necessary to do so?】

**Comment by brc-dd** [comment]
Yes. If you don't keep it in `public`, it will not be there in `dist`. It might work fine in dev without public too. But in production build only your dist directory will be served.

**Comment by wangshangluobai** [comment]
Thank you very much for your help。orz
