### ISSUE TITLE
vitepress可以打开PDF或者查看pdf的插件推荐吗？

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [vuejs/vitepress#4023]
### Is your feature request related to a problem? Please describe.

vitepress可以打开PDF或者查看能pdf的插件可以的推荐吗？

### Describe the solution you'd like

个人知识文档库中有很多pdf格式的文档，所以想知道vitepress可以打开PDF的方法，如何实现？现目前采用Vue项目的方式提示不能解析，或者查看能pdf的插件可以的推荐吗？

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can embed pdf directly using html - https://stackoverflow.com/q/17784037/11613622 or use some vue-specific package like https://github.com/hrynko/vue-pdf-embed 

(you'll need to store your pdf files in your public directory)

**Comment by jiaoxiaoyuan** [comment]
感谢，已得到解决。
