### ISSUE TITLE
Document link 404 mentioned in issue 1773

### ISSUE THREAD

**Issue by mikigo** [vuejs/vitepress#4026]
### Describe the bug

https://github.com/vuejs/vitepress/issues/1773

URL: https://vitepress.vuejs.org/guide/theme-home-page

Visit 404

### Reproduction

https://github.com/vuejs/vitepress/issues/1773

URL: https://vitepress.vuejs.org/guide/theme-home-page

Visit 404

### Expected behavior

https://github.com/vuejs/vitepress/issues/1773

URL: https://vitepress.vuejs.org/guide/theme-home-page

Visit 404

### System Info

```Text
Linux
vitepress:1.3.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Those are more than an year old issues. Just search on the site:

<img width="618" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/b55f4d7f-4774-4ee9-914a-9724caf22080">


https://vitepress.dev/reference/default-theme-home-page#home-page
