### ISSUE TITLE
[plugin:vite:vue] Element is missing end tag

### ISSUE THREAD

**Issue by Uxspy** [vuejs/vitepress#4031]
### Describe the bug

I'm using html in .md files, if the html content is similar like the following, vitepress(run dev or run build) report "Element is missing end tag"

```html
... <pre data-language="javascript" id="PZrJj" class="ne-codeblock language-javascript"><code>const foo = 'foo'

function bar() {
  const b = 'b'
  return b
}

</code></pre> ...
```

Everything works well after I removed all the line-breaks(`\r\n`) inside the `<code></code>` tag, like this:

```html
...<pre data-language="javascript" id="PZrJj" class="ne-codeblock language-javascript"><code>const foo = 'foo'
function bar() {
  const b = 'b'
  return b
}
</code></pre>...
```

### Reproduction

👆🏻

### Expected behavior

Expect works when using <pre><code>...</code><pre> in .md files with line-breaks

### System Info

```Text
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 91.86 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.3/bin/yarn
  npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
Browsers:
  Chrome: 126.0.6478.127
  Edge: 126.0.2592.87
  Safari: 17.5
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide minimal reproducible example. That code is working fine - https://stackblitz.com/edit/vite-dejjqk?file=docs%2Findex.md

**Comment by pk5ls20** [comment]
> Please provide a minimal reproducible example. That code is working fine - [stackblitz.com/edit/vite-dejjqk?file=docs%2Findex.md](https://stackblitz.com/edit/vite-dejjqk?file=docs%2Findex.md)

https://stackblitz.com/edit/vite-t3cvwmct?file=docs%2Findex.md can reproduce this issue

**In short, it's the presence of unclosed html tags in the MarkDown file that is causing this error**

**Comment by brc-dd** [comment]
> In short, it's the presence of unclosed html tags in the MarkDown file that is causing this error

That's not the author's original problem. And if you're writing invalid html it will obviously throw.
