### ISSUE TITLE
jenkins 部署vitepress，打包完后打包命令不能自动退出

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [vuejs/vitepress#4033]
### Describe the bug

jenkins 部署vitepress，使用npm run build(vitepress build)命令打包，打包成功完后npm run build不像常规Vue项目直接退出，我需要如何修改？因为npm run build没有主动停下退出，jenkins一直在执行。
<img width="1465" alt="image" src="https://github.com/vuejs/vitepress/assets/25316619/3b45f5a0-5bb5-4761-aa98-4ea6704eb069">
<img width="1249" alt="image" src="https://github.com/vuejs/vitepress/assets/25316619/24002cb6-97df-47c5-b8dd-d8e33fef45ff">

### Reproduction

jenkins 部署vitepress，使用npm run build(vitepress build)命令打包，打包成功完后npm run build不像常规Vue项目直接退出，我需要如何修改？因为npm run build没有主动停下退出，jenkins一直在执行。

### Expected behavior

jenkins 部署vitepress，使用npm run build(vitepress build)命令打包，打包成功完后npm run build不像常规Vue项目直接退出，我需要如何修改？因为npm run build没有主动停下退出，jenkins一直在执行。

### System Info

```Text
jenkins 部署vitepress，使用npm run build(vitepress build)命令打包，打包成功完后npm run build不像常规Vue项目直接退出，我需要如何修改？因为npm run build没有主动停下退出，jenkins一直在执行。
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What happens if you run `npm run build` locally? Does it terminate?

**Comment by jiaoxiaoyuan** [comment]
没有主动退出。
![image](https://github.com/vuejs/vitepress/assets/25316619/a877f592-f6b2-4b1e-a2ee-93cea2befe6b)
感谢，可能是打包有警告的原因，我再修改试试。

**Comment by brc-dd** [comment]
Ah, no. Those warnings are not related. Check for setTimeout/setInterval kind of thing. Those block the exit.

**Comment by shellRaining** [comment]
个人建议，你可以在发 issue 的时候提供更多信息，比如是在做了什么操作后（例如引入新的模块），出现输入构建命令无法退出的现象，实在没有头绪可以尝试二分配置，直到正常工作。我看到你也提了一些类似的 issue，以后可以注意一下。祝你顺利解决！

**Comment by brc-dd** [comment]
If https://github.com/jiaoxiaoyuan/code-docs-me is your repo, then you have such code at:

- .vitepress/theme/components/Home/components/TimeView.vue:11
- page/Home/index.vue:8
- .vitepress/theme/components/Home/index.vue:120 -- you can leave this if you want, as setTimeout will ultimately resolve within 2s after build.

Move the setInterval to `onMounted` or something. And clear such timers in `onUnmounted`.

**Comment by jiaoxiaoyuan** [comment]
非常感谢，是setInterval的问题。
