### ISSUE TITLE
withBase 表现异常

### ISSUE THREAD

**Issue by peiyanlu** [vuejs/vitepress#4034]
### Describe the bug

之前我一直在使用 `vitepress: ^1.0.0-beta.5` 版本，近期升级最新版本之后发现 `withBase` 出现了问题，某些地方的  `withBase`  不生效了，当我回退到 `1.0.0-beta.5` 版本，`withBase` 表现恢复正常。查看版本更新记录发现并没有对 `withBase` 作出更改。

### Reproduction

https://github.com/peiyanlu/vite-press/blob/docs-deploy/docs/archive/components/DocTimeline.vue#L125

### Expected behavior

`withBase` 表现正常

### System Info

```Text
System:
    OS: Windows 11 10.0.26100
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13980HX
    Memory: 13.04 GB / 31.63 GB
  Binaries:
    Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.4.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.26100.1
  npmPackages:
    vitepress: 1.3.0 => 1.3.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Make sure your paths start with `/`.

**Comment by peiyanlu** [comment]
> Make sure your `doc.path` starts with `/`.

谢谢，加上 `/` 可以了
