### ISSUE TITLE
Error: config must export or return an object.

### ISSUE THREAD

**Issue by asasugar** [vuejs/vitepress#4036]
### Describe the bug

When I set `nav` in `config.mts` and import it through a js, this js can only set export default

#### config.mts
```mts
import { nav } from './config';
export default defineConfig({
  title: '@luckycomponents/docs',
  description: 'A VitePress Site',
  lang: 'zh-CN',
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav,
  }
}
```

#### config/index.ts

```ts
export * from './nav';
```

#### config/nav.ts

```ts
function getNav() {
  return [
    { text: 'Home', link: '/' },
    { text: 'Examples', link: '/markdown-examples' },
  ];
}

export const nav = getNav();
```

When I change `config/index.ts` to

```ts
export default {
 ...
}
```

there will be no error!

### Reproduction

 I want it to support export * from 'xx'

### Expected behavior

I want it to support export * from 'xx'

### System Info

```Text
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 3.16 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
    pnpm: 8.15.6 - ~/.nvm/versions/node/v16.17.0/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    vitepress: ^1.3.0 => 1.3.0
```

### Additional context

I want it to support export * from 'xx'

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's expected behavior. .vitepress/config/index.ts takes preference over .vitepress/config.ts

You should do `export default defineConfig({ ... })` in .vitepress/config/index.ts if that file is present.
