### ISSUE TITLE
v1.3.0 Mobile Nested Menu Does Not Display Subtitles

### ISSUE THREAD

**Issue by CadenSkyHub** [vuejs/vitepress#4042]
### Describe the bug

**v1.3.0 手机端嵌套菜单不显示小标题**
**v1.3.0 Mobile Nested Menu Does Not Display Subtitles**

`NavItem[]`

```ts
const navBar: DefaultTheme.NavItem[] = [
    {text: '首页', link: '/index'},
    //-----------
    {
        text: '工具集',
        items: [
            {
                text: '工具1',
                noIcon:true,
                items: [
                    {text: 'a', link: '/a'},
                    {text: 'a', link: '/a'},
                    {text: 'a', link: '/a'},
                ]
            },
            {
                text: '工具2',
                items: [
                    {text: 'b', link: '/b'},
                    {text: 'b', link: '/b'},
                    {text: 'b', link: '/b'},
                ]
            }
        ]
    },
    //-----------
    {text: '关于我', link: '/about'}
]
```

手机端显示：
Mobile display:
![image-20240714171615571](https://github.com/user-attachments/assets/8bb0820e-b8d4-492b-a7b9-8ead2e67a5b5)

电脑端显示：
Computer display:
![image-20240714171646379](https://github.com/user-attachments/assets/c98239d5-6776-4d59-88be-dd97112e4362)

> 当我使用 v1.2.3 时一切正常。
> Everything worked fine when I was using v1.2.3.

My English is terrible, and I used a translation tool, so I hope this is understandable.

### Reproduction

I have reproduced the issue. [stackblitz](https://stackblitz.com/edit/vite-bro9hm?file=docs%2F.vitepress%2Fconfig.ts)

### Expected behavior

正常显示
Displayed normally

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 38.28 GB / 63.19 GB
  Binaries:
    Node: 18.20.4 - ~\AppData\Local\fnm_multishells\106552_1720946934721\node.EXE
    npm: 10.7.0 - ~\AppData\Local\fnm_multishells\106552_1720946934721\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Fixed in 1.3.1
