### ISSUE TITLE
[commonjs--resolver] Invalid URL

### ISSUE THREAD

**Issue by congmucc** [vuejs/vitepress#4044]
### Describe the bug

I want to build my project, but it failed, and the error failed.
```
x Build failed in 10.91s
✖ building client + server bundles...
build error:
[commonjs--resolver] Invalid URL
[commonjs--resolver] Invalid URL
TypeError [PLUGIN_ERROR]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:637:13)
    at Object.resolveId (file:///C:/Users/Administrator/Desktop/Project/blog/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:20482:19)
    at file:///C:/Users/Administrator/Desktop/Project/blog/node_modules/.pnpm/rollup@4.18.1/node_modules/rollup/dist/es/shared/node-entry.js:19743:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/Users/Administrator/Desktop/Project/blog/node_modules/.pnpm/rollup@4.18.1/node_modules/rollup/dist/es/shared/node-entry.js:19643:28)
    at async resolveId (file:///C:/Users/Administrator/Desktop/Project/blog/node_modules/.pnpm/rollup@4.18.1/node_modules/rollup/dist/es/shared/node-entry.js:18324:26)
    at async ModuleLoader.resolveId (file:///C:/Users/Administrator/Desktop/Project/blog/node_modules/.pnpm/rollup@4.18.1/node_modules/rollup/dist/es/shared/node-entry.js:18727:15)
    at async Object.resolveId (file:///C:/Users/Administrator/Desktop/Project/blog/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:12701:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/Users/Administrator/Desktop/Project/blog/node_modules/.pnpm/rollup@4.18.1/node_modules/rollup/dist/es/shared/node-entry.js:19643:28)
    at async resolveId (file:///C:/Users/Administrator/Desktop/Project/blog/node_modules/.pnpm/rollup@4.18.1/node_modules/rollup/dist/es/shared/node-entry.js:18324:26)
```

and `pnpm dev` is success.

my project address is : `https://github.com/congmucc/blog`

### Reproduction

![image](https://github.com/user-attachments/assets/844faed7-46f3-45dc-86d3-123efd175cd1),I'm weird about this packing error, I haven't modified much of anything

### Expected behavior

I want it to run `pnpm build`  successfully

### System Info

```Text
Debugger attached.
Need to install the following packages:
envinfo@7.13.0
Ok to proceed? (y) y
Debugger attached.

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 3.69 GB / 15.86 GB
  Binaries:
    Node: 18.18.1 - E:\nodejs\node.EXE
    npm: 10.5.2 - E:\nodejs\npm.CMD
    pnpm: 9.5.0 - E:\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vitepress: ^1.3.1 => 1.3.1
```

### Additional context

![image](https://github.com/user-attachments/assets/844faed7-46f3-45dc-86d3-123efd175cd1)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You have a file named

```
watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBA5LqaIOeRnw==,size_20,color_FFFFFF,t_70,g_se,x_16#pic_center.png
```

Remove `#` from it and `docs/后端/Java/框架/SpringBoot/JUnit5/JUnit5.md` Characters like `#` and `?` that have special meaning in URL are not allowed in file names.

**Comment by congmucc** [comment]
> You have a file named您有一个名为
> 
> ```
> watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBA5LqaIOeRnw==,size_20,color_FFFFFF,t_70,g_se,x_16#pic_center.png
> ```
> 
> Remove `#` from it and update the url in `docs/后端/Java/框架/SpringBoot/JUnit5/JUnit5.md` `#` 从中删除并更新 url `docs/后端/Java/框架/SpringBoot/JUnit5/JUnit5.md`
> 
> Characters like `#` and `?` that have special meaning in URL are not allowed in file names.文件名中不允许使用 URL `#` 中具有特殊含义的 and `?` 等字符。

thinks，that's right

**Comment by congmucc** [comment]
> You have a file named您有一个名为
> 
> ```
> watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBA5LqaIOeRnw==,size_20,color_FFFFFF,t_70,g_se,x_16#pic_center.png
> ```
> 
> Remove `#` from it and update the url in `docs/后端/Java/框架/SpringBoot/JUnit5/JUnit5.md` `#` 从中删除并更新 url `docs/后端/Java/框架/SpringBoot/JUnit5/JUnit5.md`
> 
> Characters like `#` and `?` that have special meaning in URL are not allowed in file names.文件名中不允许使用 URL `#` 中具有特殊含义的 and `?` 等字符。

thanks， that's right.

**Comment by congmucc** [comment]
> You have a file named您有一个名为
> 
> ```
> watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBA5LqaIOeRnw==,size_20,color_FFFFFF,t_70,g_se,x_16#pic_center.png
> ```
> 
> Remove `#` from it and update the url in `docs/后端/Java/框架/SpringBoot/JUnit5/JUnit5.md` `#` 从中删除并更新 url `docs/后端/Java/框架/SpringBoot/JUnit5/JUnit5.md`
> 
> Characters like `#` and `?` that have special meaning in URL are not allowed in file names.文件名中不允许使用 URL `#` 中具有特殊含义的 and `?` 等字符。

Can i konw why you can find the error, I want to learn.

**Comment by brc-dd** [comment]
I just clicked on that Object.resolveId file in error stack trace (the top one) and added a `console.log(id)` statement there and ran vitepress build. It then showed that file name where it was breaking.

**Comment by congmucc** [comment]
> I just opened that Object.resolveId file in error stack trace (the top one) and added a `console.log(id)` statement there and ran vitepress build. It then showed that file name where it was breaking.
Thank you for teaching
