### ISSUE TITLE
Add Persian Language to the Documentation

### ISSUE THREAD

**Issue by amir78729** [vuejs/vitepress#4047]
### Is your feature request related to a problem? Please describe.

As a native Persian speaker and a developer who frequently uses VitePress, I often find myself frustrated by the lack of Persian language documentation. This can be a barrier for Persian-speaking developers who might not be fluent in English, making it difficult to fully utilize and contribute to the VitePress project.

### Describe the solution you'd like

I would like to contribute to the VitePress documentation by adding a Persian language option. This would involve translating the existing documentation into Persian and ensuring that all future updates are also translated. This addition would make the documentation more accessible to Persian-speaking developers, thereby fostering a more inclusive and diverse community.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/issues/3850#issuecomment-2087959370
