### ISSUE TITLE
mailto: links in sidebar and navbar

### ISSUE THREAD

**Issue by MartinMalinda** [vuejs/vitepress#405]
### Is your feature request related to a problem? Please describe.

I tried to have a link object like this in my config: `{ text: 'info@mycompany.com', link: 'mailto: info@mycompany.com' },` and it didn't work.

### Describe the solution you'd like

Would be nice if `{ text: 'info@mycompany.com', link: 'mailto: info@mycompany.com' },` just worked!

### Describe alternatives you've considered

So far I just have an email address in the sidebar without a link. 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by MartinMalinda** [comment]
There was this fix: https://github.com/vuejs/vitepress/pull/173/files but that only fixes mailto links in the markdown content, not sidebar or navbar.

**Comment by MartinMalinda** [comment]
Also now when I'm thinking about it - if it worked as a link it might also be displayed as the "next link" at the bottom of the page which wouldn't be very convenient.

**Comment by kiaking** [comment]
I think it make sense to have mail to link in navbar, for example having menu item like `Contact Us` make total sense. But not so sure on the sidebar.

Because as you said, it's not very clear what to do with prev-next link, and might just be too complicated.

Let's add this feature to nav, but leave it from sidebar at the moment.

**Comment by kecrily** [comment]
I just tried it. Already support ah

Just like what you wrote (I'm not sure if this is because `next-theme` has been changed in some way)
```js
{
  text: 'Contact',
  link: 'mailto:info@test.com'
}
```

**Comment by kiaking** [comment]
Nice! Thank you for testing out 👍 👍 👍
