### ISSUE TITLE
markdown-it-video hydration issue on Firefox

### ISSUE THREAD

**Issue by hamishwillee** [vuejs/vitepress#4053]
### Describe the bug

The [markdown-it-video](https://www.npmjs.com/package/markdown-it-video) plugin works fine for displaying youtube video on Chrome browser, but on Firefox I get a hydration warning and the video is not displayed:

![](https://private-user-images.githubusercontent.com/5368500/347720986-83652579-383c-4754-b8c6-1fdd7fe71dd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjM0NjAsIm5iZiI6MTcyMDc2MzE2MCwicGF0aCI6Ii81MzY4NTAwLzM0NzcyMDk4Ni04MzY1MjU3OS0zODNjLTQ3NTQtYjhjNi0xZmRkN2ZlNzFkZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMDU0NjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M5OWZjZjNlZjJmZjY3NzYwNjI0ZDYwNTU1NTk5ODQxZWNjOGYwYTk0ODQzYTNkNGVlODJiMjNjOTcyNzFkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._GgQLgGfp5tzb0JxKtlMDrzL9kJrGCGCQNOIVQAPFnw)

This is to be expected, based on https://github.com/vuejs/vitepress/issues/2441, because according to the markdown-it-video docs the `@[youtube](dQw4w9WgXcQ)` is rendered using `div` inside `p` as shown:

```
<p><div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" id="youtubeplayer" type="text/html" width="640" height="390"
  src="//www.youtube.com/embed/dQw4w9WgXcQ"
  frameborder="0"/></div></p>
```

So not technically a bug in vitepress, but the only easy way I've found to embed video (why is this not supported by default?) breaks on Firefox.

I don't really need this to work, but I think it is a bug that there is now easy way to add support. What's the best way?

### Reproduction

in my (javascript) config file as shown below added

```js
import markdownItVideo from "markdown-it-video";

// ...


  markdown: {
    math: true,
    config: (md) => {
      // use more markdown-it plugins!
      md.use(markdownItVideo);
    },
  },
```

That's it - then in markdown anywhere have `@[youtube](https://youtu.be/-dkQG8YLffc)`.

The test videos that work on chrome but not Firefox can be found here https://docs.px4.io/main/en/concept/flight_tasks.html#video

### Expected behavior

Some reasonably straightforward mechanism for adding youtube videos to a vitepress site.
I guess that might be as simple as you saying "you have to fix the markdown-it-video plugin` - but I'm hoping for a workaround - i.e. parsing the source markdown to some other format 

### System Info

```Text
Note, only affects built version.

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 5.92 GB / 31.83 GB
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vitepress: ^1.3.1 => 1.3.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
try using this one - https://github.com/rotorz/markdown-it-block-embed

**Comment by hamishwillee** [comment]
That one doesn't appear to work at all (renders as `@[youtube](https://youtu.be/orvng_11ngQ?t=560)`. It is possible that I am using it wrong - all I did was install plugin package an update the config as [here](https://github.com/PX4/PX4-user_guide/pull/3294/files):

```js
//import markdownItVideo from "markdown-it-video";
import blockEmbedPlugin from "markdown-it-block-embed";


// ...
    config: (md) => {
      // use more markdown-it plugins!
      //md.use(markdownItVideo);
      md.use(blockEmbedPlugin);
    },
  },
```

**Comment by brc-dd** [comment]
Seems to work fine

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/1cfb45f2-f3a0-4a74-837d-91ed65116e15">

https://stackblitz.com/edit/vite-thbmsl?file=docs/.vitepress/config.ts,docs/index.md

Your builds are failing, not sure how to check that on your PR.

**Comment by hamishwillee** [comment]
Thank you. In my docs I had a comment after the video as shown below. Once I remove that, it works in **local** build (it works with or without the comment in your https://stackblitz.com/ example). That's a bit flaky.

```
@[youtube](https://youtu.be/orvng_11ngQ?t=560) <!-- datestamp:video:youtube:20200720:Overview of multicopter control from sensors to motors — PX4 Developer Summit Virtual 2020 From 9min20sec - Section on flight tasks-->
```

I am still trying to resolve the (unrelated) build issues so I can test it when deployed. Will get back to you.

**Comment by brc-dd** [comment]
Yeah I'm not sure about how well that plugin is able to handle edge cases. There is another one that does it right - https://www.npmjs.com/package/@dwk/markdown-it-embed

However, I think in longer run and for better performance, it will be just better to use `lite-youtube-embed` and do it like:

```md
<lite-youtube videoid="orvng_11ngQ" params="start=560" />
```

**Comment by hamishwillee** [comment]
Sounds reasonable, though I personally would need dummy-proof instructions for integrating that into vitepress.

**Comment by brc-dd** [comment]
https://stackblitz.com/edit/vite-6yrurb?file=docs/index.md

**Comment by hamishwillee** [comment]
@brc-dd I tried both `<lite-youtube>` and `markdown-it-block-embed`. Both work on chrome and on Firefox.

I prefer the original markdown-alike syntax because it renders as a link - so on Github or if you were to use another SSG that does not understand the custom tag you still get "something" useful. Despite that, I've moved to `<lite-youtube>` because I don't trust `markdown-it-block-embed` to cope with the edge cases. Something to think about though.

I think it would be useful to have an example of embedding  `<lite-youtube>` in the docs - as it shows both how you can embed the custom component, and also provides support for video at the same time. Of course this is up to you - but I see video support as a pretty fundamental part of many docs sites.

Thanks very much for all your help. I am enjoying vitepress.

**Comment by brc-dd** [comment]
An examples page/repo has been long due. We probably will start keeping these things there once I've got time 🫠 Closing this for now.
