### ISSUE TITLE
update notes on base in gitlab deploy guide

### ISSUE THREAD

**Issue by urswilke** [vuejs/vitepress#4055]
### Describe the bug

When following the steps in https://vitepress.dev/guide/getting-started, the production build doesn't work. 

### Reproduction

First I used 
```
npx vitepress init
```
to create [this repo](https://gitlab.com/urswilke/vitepress_from_template2).

I used all the default settings, apart from setting `./docs` in
```
Where should VitePress initialize the config?
  ./docs
```

Then, I run:
```
npm run docs:build 
```

When opening the file `docs/.vitepress/dist/index.html`, this results in the CORS errors in the following screenshot:

![Screenshot from 2024-07-17 10-39-06](https://github.com/user-attachments/assets/6e5263b3-8509-4d93-88a8-00617b59a4c7)

### Expected behavior

The production build should result in the same as on the dev server (which works).

### System Info

```Text
System:
    OS: Linux 6.9 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 20.41 GB / 31.12 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 22.4.1 - /usr/bin/node
    npm: 10.8.2 - /usr/bin/npm
  npmPackages:
    vitepress: ^1.3.1 => 1.3.1
```

### Additional context

On chrome, the site isn't correctly built either.
The deploy on gitlab pages also doesn't work (see [here](https://vitepress-from-template2-urswilke-295c17a73cbd456dc43a7cf324dd1.gitlab.io/)).

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You need to serve the dist directory. Directly opening generated html files won't work.  Run `vitepress preview docs`.

**Comment by urswilke** [comment]
do I have to commit the files generated in the `public` folder to the gitlab repo to make the deploy on gitlab pages work?

**Comment by brc-dd** [comment]
I've never used gitlab. We have externally contributed docs though - https://vitepress.dev/guide/deploy#gitlab-pages

**Comment by urswilke** [comment]
I wasn't able to make it work on gitlab.
The build didn't work with github actions either. See [here](https://github.com/urswilke/vitepress_from_template2) for the same repo on github.

**Comment by brc-dd** [comment]
For github, remove `outDir: "../public",` from your config.

**Comment by urswilke** [comment]
Thanks a lot for your help!

**Comment by brc-dd** [comment]
For your gitlab pages, I think you should remove base and it should work 👀

**Comment by urswilke** [comment]
That was it. For github actions, you need to set:
```
base: "/vitepress_from_template2/"
```
whereas, for gitlab pages you need to set
```
outDir: "../public"
```
Thanks again!
