### ISSUE TITLE
Support i18n in `contentLoader`

### ISSUE THREAD

**Issue by Barbapapazes** [vuejs/vitepress#4072]
### Is your feature request related to a problem? Please describe.

Hello,

Actually, I have to create a loader for each language, and then import all of them in my vue component.

```ts
// @ts-expect-error - vitepress types are not available
import { data as rootData } from '../../data/posts.data'
// @ts-expect-error - vitepress types are not available
import { data as frData } from '../../data/fr-posts.data'
import { computed } from 'vue';

const data: Record<string, any> = {
  root: rootData,
  fr: frData
}

const {  localeIndex  } = useData()

const posts = computed(() => data[localeIndex.value])
```

### Describe the solution you'd like

I would like to have to only create a single content loader and based on my locales configuration (and maybe an option) retrive all content.

For example: `posts/*.md` should get `posts/*.md` (the root) and `fr/posts/*.md` (the fr locale).

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This should already work. Can you share an example where createContentLoader doesn't respect glob?

Also, regarding those ts-expect-error comments in your code, you need to declare types in your data file - those files are not generated by vitepress - https://vitepress.dev/guide/data-loading#typed-data-loaders (for createContentLoader the Data type should be array of ContentData, refer docs above that section too)

**Comment by brc-dd** [comment]
Ah, if you want to have a single content loader, you can adjust your glob:

```ts
import {
  createContentLoader,
  type ContentData,
  type SiteConfig
} from 'vitepress'

export type Data = Record<string, ContentData[]>

declare const data: Data
export { data }

const config: SiteConfig = (globalThis as any).VITEPRESS_CONFIG
const locales = Object.keys(config.userConfig.locales ?? {})

export default createContentLoader('**/posts/**/*.md', {
  transform(data) {
    const grouped: Data = {}
    data.forEach((item) => {
      let locale = item.url.split('/')[1]
      locale = locales.includes(locale) ? locale : 'root'
      ;(grouped[locale] ??= []).push(item)
    })

    return grouped
  }
})
```

**Comment by Barbapapazes** [comment]
This works wonderfully! Thank you.

> export type Data = Record<string, ContentData[]>
> export declare const data: Data

This is cool to have types! Until now, I had a `ts-expect-error. 😅
