### ISSUE TITLE
Translate the "Copied" text in Code blocks

### ISSUE THREAD

**Issue by mrredtree** [vuejs/vitepress#4074]
### Is your feature request related to a problem? Please describe.

Hello. When writing a code block like this:
```
hello
```

everyone can click on a button to Copy Code.

If I am not missing something else... every text in VitePress interface can be translated, except the message "Copied" that appears when clicking on the "Copy Code" button.

### Describe the solution you'd like

I tried to discover if this string comes from an internal plugin or from VitePress and I could not discover.
It may be a small thing, but I would appreciate if someone could discover this and allow us to translate the "Copied" string.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by niansi-z** [comment]
Maybe you can check the src/client/theme - the default/styles/components/vp-doc.css file, in 506, modified - vp - code - copy - copied text - the content and repack

**Comment by niansi-z** [comment]
Perhaps you can check 'src/client/theme-default/styles/components/vp-doc.css', go to line 506 in the file, modify '--vp-code-copy-copied-text-content', and then rebuild and run the application.

**Comment by brc-dd** [comment]
You don't need to modify it in the source. You can override using custom CSS - https://vitepress.dev/guide/extending-default-theme#customizing-css

```css
:root {
   --vp-code-copy-copied-text-content: 'your text here'
}

/* or if you want to change only for a locale: */

:lang(zh) {
   --vp-code-copy-copied-text-content: '已复制'
}
```
