### ISSUE TITLE
Sitemap doesn't seem to be generating in v1.3.1

### ISSUE THREAD

**Issue by lewislarsen** [vuejs/vitepress#4079]
### Describe the bug

The sitemap seemingly isn't being generated for my instance of Vitepress. 

Below is a snippet from my configuration file, I have read the documentation and from what I know, I've configured the base path correctly as page navigation is functional in production. I deploy with GitHub pages if that makes any difference, however I can't get a sitemap to generate locally either. (With an adjusted hostname)

```
    base: "/",
    sitemap: {
      hostname: 'https://docs.vanguardbackup.com/'
    },
```

My full configuration file can be found [here](https://github.com/vanguardbackup/docs/blob/bc401a3676e1f27444d1bf302249f4c724522c1d/.vitepress/config.mjs#L39).

### Reproduction

Create a Vitepress project, define the hostname and base and visit the /sitemap.xml path.

### Expected behavior

The sitemap should be generated and accessible at /sitemap.xml.

### System Info

```Text
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 87.41 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.0 - /opt/homebrew/bin/node
    npm: 10.8.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 18.0
  npmPackages:
    vitepress: ^1.3.1 => 1.3.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
sitemap is not part of themeConfig, move it outside that
