### ISSUE TITLE
Successfully run dev ,but build fail

### ISSUE THREAD

**Issue by dddssw** [vuejs/vitepress#4083]
### Describe the bug

![image](https://github.com/user-attachments/assets/3cd1e734-86d4-4a7e-8c95-f8288bc2db10)
I don't know how to deal with it.It looks like a esm module
![image](https://github.com/user-attachments/assets/cab020ee-3bde-48e7-8758-e78df4b81873)

### Reproduction

https://stackblitz.com/edit/vite-fg6rv7?file=docs%2Findex.md,package.json

### Expected behavior

I don't know what happed.The dev and build should be consistent at least

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13500H
    Memory: 6.16 GB / 15.65 GB
  Binaries:
    Node: 22.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.3.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vitepress: ^1.3.1 => 1.3.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
gsap doesn't ship valid ESM. They use ESM syntax but haven't added `"type": "module"` in their package.json, which makes node treat their files as CJS (with invalid syntax). You'll need to tell vite to force transpile it to valid ESM so that it can be resolved by node properly.
 
```ts
// .vitepress/config.ts

export default defineConfig({
  // ...

  vite: {
    ssr: {
      noExternal: ['gsap'],
    },
  },
}
```

**Comment by dddssw** [comment]
Thank
