### ISSUE TITLE
vitepress不支持插件吗？

### ISSUE THREAD

**Issue by moonsky-all** [vuejs/vitepress#4084]
### Is your feature request related to a problem? Please describe.

看了一下vuepress是支持插件的，仔细检查了一下vitepress好像不支持插件（文档里没写），貌似只能通过修改 markdown 配置项的方式实现插件，希望有别的更简单集成插件的方式，类似 vite 插件那样，import 后执行一个函数的方式

### Describe the solution you'd like

希望有更简单的方式集成插件

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
There are plugins, you can search the web or npm. But there isn't proper plugin API yet. Track #3966 for that.
