### ISSUE TITLE
Why 'footer' config no support 'div' tag?

### ISSUE THREAD

**Issue by Wesley-0808** [vuejs/vitepress#4085]
### Reproduction

-

### Expected behavior

-

### System Info

```Text
-
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Footer uses `p` tag and `div` cannot be inside `p` as per the HTML5 spec.
