### ISSUE TITLE
When the sidebar configuration exceeds four levels, the title style generated by parsing the content is missing

### ISSUE THREAD

**Issue by Yxiuchao** [vuejs/vitepress#409]
### Describe the bug

When the default theme is used, when the sidebar configuration is greater than or equal to four layers, the navigation menu title style of the content md file parsing is missing
![image](https://user-images.githubusercontent.com/48636987/136543834-a804bdcc-2394-4f49-b081-f9eeb49778d3.png)

### Reproduction

![image](https://user-images.githubusercontent.com/48636987/136544140-1e1dfd3e-d185-4453-8923-d315d9861799.png)
![Uploading image.png…]()

### Expected behavior

Regardless of whether the parsed style of several layers of content is correct, or the level is configurable

### System Info

```shell
vitepress:0.19.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by lhttjdr** [comment]
This is because currently the default theme only supports up to 4 levels.
```css
.sidebar
  > .sidebar-links     /* level 1*/
  > .sidebar-link
  > .sidebar-links    /* level 2*/
  > .sidebar-link
  > .sidebar-links    /* level 3*/
  > .sidebar-link
  > .sidebar-links   /* level 4*/
  > .sidebar-link
  > .sidebar-link-item {
  display: block;
  padding: 0.3rem 1.5rem 0.3rem 4rem;  /* indent 4rem */
  line-height: 1.4;
  font-size: 0.9rem;
  font-weight: 400;
}
```

By adding some custom `css` styles, it can be solved.
```css
.sidebar
  > .sidebar-links     /* level 1*/
  > .sidebar-link
  > .sidebar-links    /* level 2*/
  > .sidebar-link
  > .sidebar-links    /* level 3*/
  > .sidebar-link
  > .sidebar-links   /* level 4*/
  > .sidebar-link
  > .sidebar-links   /* level 5*/
  > .sidebar-link
  > .sidebar-link-item {
  display: block;
  padding: 0.3rem 1.5rem 0.3rem 5rem;  /* indent 5rem */
  line-height: 1.4;
  font-size: 0.9rem;  /*you can choose a smaller font size for level 5 if you like*/
  font-weight: 400;
}
```

Perhaps it's a good idea to make the default theme support up to 6 levels, I think, just like `h1`~`h6`.

**Comment by kiaking** [comment]
Not relevant to `next-theme` anymore.
