### ISSUE TITLE
Set the default lang on creating the project

### ISSUE THREAD

**Issue by chenxi2035** [vuejs/vitepress#4090]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

We just want a single lang on many situations, so I suggest to set the default lang on initializing, give an option to select the supported lang. I searched the documents and issues, but didn't get an answer.
`
pnpm vitepress init
`

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/site-config#lang
