### ISSUE TITLE
I want to use the search component in the navigation elsewhere. 

### ISSUE THREAD

**Issue by rosa5500** [vuejs/vitepress#4092]
I want to use the search component in the navigation elsewhere. 
Is there any way to use it directly?
I searched for the source code using <VPSNavBarSearch />, but I failed to import it.
Or through Vite?

<img width="949" alt="image" src="https://github.com/user-attachments/assets/40c8488a-ae4b-4ac7-b759-0ff5cab6f3a7">

------------------------------

我想在其他地方使用导航中的搜索的这个组件。
有什么办法直接使用吗？
我查找源码是<VPNavBarSearch />，但是我引用失败了。
或者通过vite？

<img width="1290" alt="image" src="https://github.com/user-attachments/assets/35bd9a90-3b31-4da1-a8e8-61bd5674734c">

**Comment by brc-dd** [comment]
It's this one - https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPNavBarSearch.vue

Can be imported directly from dist:

```ts
import VPNavBarSearch from 'vitepress/dist/client/theme-default/components/VPNavBarSearch.vue'
```

**Comment by rosa5500** [comment]
> It's this one - https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPNavBarSearch.vue
> 
> Can be imported directly from dist:
> 
> ```ts
> import VPNavBarSearch from 'vitepress/dist/client/theme-default/components/VPNavBarSearch.vue'
> ```

thanks!!
It succeeded!
(I used the same method to import yesterday, but the import failed. I forgot where I imported it yesterday. I can no longer reproduce it. Thank you very much.)
