### ISSUE TITLE
support protobuf highlight

### ISSUE THREAD

**Issue by cruvie** [vuejs/vitepress#4094]
### Is your feature request related to a problem? Please describe.

The language 'protobuf' is not loaded, falling back to 'txt' for syntax highlighting.

### Describe the solution you'd like

support protobuf highlight

### Describe alternatives you've considered

I found shiki has already supported protobuf https://github.com/shikijs/shiki/pull/446

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
shiki doesn't support that - https://github.com/shikijs/textmate-grammars-themes/blob/57d88ad0bfccc6c50a5ea7bb9715f2a7d9b7f9d4/packages/tm-grammars/index.js#L2242-L2252

Create a PR there to fix it. That PR was probably reverted (most like accidentally by their bot).
