### ISSUE TITLE
base配置打包之后少了斜杠，变成https:/www.baidu.com/logo.svg

### ISSUE THREAD

**Issue by chenyulun** [vuejs/vitepress#4095]
### Describe the bug

构建之后有些`http://`变成了`http:/`少了一个斜杠

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/8002c32b-ecd2-4626-bd7f-2c2e9b1b6359">

### Reproduction

```ts
export default defineConfig({
  base: 'https://www.baidu.com/',
  // ...
  })
  ```md
---
# https://vitepress.dev/reference/default-theme-home-page
layout: home

hero:
  name: "PUI前端知识库"
  text: "提供前端生态工具和解决方案"
  tagline: 让开发变得更简单
  image:
    src: /logo.svg
    alt: PUI
  actions:
    - theme: brand
      text: 开发指南
      link: /guide
    - theme: alt
      text: API
      link: /api

features:
  - title: PUI组件
    details: 提供银行通用的移动端UI组件库
  - title: 脚手架
    details: 提供银行通用的移动端脚手架
  - title: 工具库
    details: 提供银行通用的工具库
---
  ```

### Expected behavior

期望能正确处理base

### System Info

```Text
System:
    OS: macOS 12.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 17.04 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/Library/Caches/fnm_multishells/29829_1722424042245/bin/node
    Yarn: 1.22.22 - ~/Library/pnpm/yarn
    npm: 9.8.1 - ~/Library/Caches/fnm_multishells/29829_1722424042245/bin/npm
    pnpm: 9.6.0 - ~/Library/pnpm/pnpm
    bun: 1.0.29 - ~/.bun/bin/bun
    Watchman: 2023.10.09.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 127.0.6533.72
    Chrome Canary: 129.0.6626.0
    Edge: 127.0.2651.74
    Safari: 16.1
```

### Additional context

```json
{
  "name": "knowledge-docs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:preview": "vitepress preview docs"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "vitepress": "^1.3.1"
  }
}
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
base is not meant for those cases. It is needed if you're deploying to a subpath.

if you're deploying to `https://some-domain.com/` -- remove base
if you're deploying to `https://some-domain.com/some-path/` -- set base to `/some-path/`

**Comment by chenyulun** [comment]
These 2 places don't agree, and that's a problem, is it simply replacing the double slash to become a single slash?
@brc-dd

**Comment by brc-dd** [comment]
Absolute URLs are not supported in base and don't mean anything. It's garbage in, garbage out.

**Comment by chenyulun** [comment]
ok! tks!
