### ISSUE TITLE
页面导航问题求教

### ISSUE THREAD

**Issue by senhao-xu** [vuejs/vitepress#4096]
如图所示，我想将导航标题级别提升，展示更多的，但是它是显示到2级标签。
![image](https://github.com/user-attachments/assets/b8efef12-0e09-4052-b968-7023b45fe7ad)

我参考了文档，但是没有找到相关配置，就是这样的效果

![image](https://github.com/user-attachments/assets/c1cc4bb4-c311-48c7-b5c7-73e95e0bb158)

请问，我该怎么做

**Comment by brc-dd** [comment]
https://vitepress.dev/zh/reference/default-theme-config#outline
