### ISSUE TITLE
Hero images are not built correctly

### ISSUE THREAD

**Issue by Squidies** [vuejs/vitepress#4097]
### Describe the bug

Hero Images should be included correctly when running `docs:build`

### Reproduction

`npm run docs:build`

### Expected behavior

Hero images to be included correctly when building.

### System Info

```Text
System:
    OS: macOS 14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 461.46 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
    Yarn: 4.1.1 - ~/.nvm/versions/node/v20.12.0/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.12.0/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.73
    Chrome Canary: 129.0.6628.0
    Safari: 17.5
  npmPackages:
    vitepress: ^1.3.1 => 1.3.1
```

### Additional context

hero images should be included in the build process correctly

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Keep them in public directory. Strings in frontmatter are not treated like assets.
