### ISSUE TITLE
手机端英文显示效果似乎不佳

### ISSUE THREAD

**Issue by shuizhutieniu** [vuejs/vitepress#4118]
![微信图片_20240809104333](https://github.com/user-attachments/assets/95a9b9c1-5833-4b3d-8cd6-9ddd457203b6)
不知道是否是我手机的问题，英文字体太细了

**Comment by brc-dd** [comment]
Update your iOS. It was a bug in one the safari versions.

**Comment by shuizhutieniu** [comment]
Thank you
