### ISSUE TITLE
`lastUpdated` Feature Seems Not Displaying Date on Server Deployment Without Git

### ISSUE THREAD

**Issue by shuizhutieniu** [vuejs/vitepress#4119]
I have enabled the `lastUpdated` feature, but the last updated date is not being displayed. I understand that the method you implemented to show the last updated date involves fetching the date of the last commit. However, my project is deployed on a server without a Git environment. Is there a solution to this issue?

**Comment by shuizhutieniu** [comment]
thank you

**Comment by brc-dd** [comment]
Are you not using git? (I mean outside your server?)

**Comment by shuizhutieniu** [comment]
> Are you not using git? (I mean outside your server?)

I do. I have just created a dummy Git repository and after placing the code in it and making a commit, the last updated date is now displaying correctly.
