### ISSUE TITLE
actionText prop on VPTeamMembers components doesn't works

### ISSUE THREAD

**Issue by ValentinBrebion** [vuejs/vitepress#4124]
### Describe the bug

i'm writting a doc using vitepress (v1.3.2) and i discovered VPTeamMembers components. 
So i use those props:
`// URL for the sponsor page for the member.
  sponsor?: string

  // Text for the sponsor link. Defaults to 'Sponsor'.
  actionText?: string`

and wanted to change the default sponsor text but it didn't change. It still display sponsor.

### Reproduction

---
layout: page
---
```<script setup>
import {
  VPTeamPage,
  VPTeamPageTitle,
  VPTeamMembers
} from 'vitepress/theme'

const members = [
  {
    avatar: '/developpementLogo.jpg',
    name: 'Our Team',
    sponsor: 'www.google.fr',
    actionText: 'Discover' //it suppose to change 'Sponsor' into 'Discover'
  }
]
</script>


<VPTeamPage>
  <VPTeamPageTitle>
    <template #title>
      Our Team
    </template>
    <template #lead>
      The development of VitePress is guided by an international
      team, some of whom have chosen to be featured below.
    </template>
  </VPTeamPageTitle>
  <VPTeamMembers
    :members="members"
  />
</VPTeamPage>


### Expected behavior

it suppose to change Sponsor word like this but didn't work

![discover](https://github.com/user-attachments/assets/e60dbe64-189f-4ee4-a60a-39be41b45074)



### System Info

```Text
System
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
<img width="1062" alt="image" src="https://github.com/user-attachments/assets/a489ebc8-5c6d-4c72-b4e2-e4670100e21c">

Please provide a minimal reproducible example using https://vitepress.new. The code you've provided is working fine.

**Comment by ValentinBrebion** [comment]
I'm sorry, I don't know what happens in my repo. I think the bug is due to bad upgrade version.
i deleted what I made, i created a new branch where i made the upgrade and merged in develop branch and then i integrated what I wanted and it works !

Thanks you for your feedback and sorry for the disturbance
ValTech
