### ISSUE TITLE
Add `StackOverflow` icon to the `SocialLinkIcon` type.

### ISSUE THREAD

**Issue by Achintha444** [vuejs/vitepress#4135]
### Is your feature request related to a problem? Please describe.

 Hi team, currently there is no `StackOverlfow` icon in the `SocialLinkIcon` type, which makes it difficult for the developers to add their relevant StackOverflow links to their documentation sites.

### Describe the solution you'd like

Add the `StackOverflow` icon to the `SocialLinkIcon` type,.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Use custom SVG. New icons won't be added unless there is significant demand.

https://vitepress.dev/reference/default-theme-config#sociallinks . You can get SVG from https://simpleicons.org/
