### ISSUE TITLE
Reference the current page to a shared file

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/vitepress#4136]
### Is your feature request related to a problem? Please describe.

Imagine the case I want two different route show the exact same content, and I want to store that `.md` file someone else for reference from those 2 routes

### Describe the solution you'd like

Files:
- `/docs/shared/foo.md`
- `/docs/category-1/bar.md`
- `/docs/category-2/baz.md`

However, I want `/category-1/bar` and `/category-2/baz` to show exactly the same content as stored in `/docs/shared/foo.md`

I can use `srcExclude` to not generate the route for `/shared/foo`, but there's no way I can make route `/category-1/bar` and `/category-2/baz` to show the content of `/docs/shared/foo.md`

### Describe alternatives you've considered

Maybe we can have something in the frontmatter to makes it work like this:
```md
---
reference: ../shared/foo.md
---
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/guide/markdown#markdown-file-inclusion ?

**Comment by xsjcTony** [comment]
Seems solid, the title is a bit different as I thought so I didn't found it🤣.

Just want to confirm that as long as I put the `shared` folder into `srcExclude`, it will not generate the route right? And will it get parsed if it's referenced from another file if it's in `srcExclude`?

I'll give it a try tomorrow anyway, if everything works well, I'll close this. Thanks!

**Comment by brc-dd** [comment]
> Just want to confirm that as long as I put the shared folder into srcExclude, it will not generate the route right? And will it get parsed if it's referenced from another file if it's in srcExclude?

Yes.

**Comment by xsjcTony** [comment]
Tried it today, works perfectly. Thanks!
