### ISSUE TITLE
LastupDateTime does not work correctly

### ISSUE THREAD

**Issue by ZtfCoder** [vuejs/vitepress#4139]
### Describe the bug

I compiled the product and pushed it to another repository through GitHub workflow. How can I make lastUpdating Time work correctly? Now, lastUpdating Time is always the latest time from another repository

### Reproduction

no

### Expected behavior

Correctly display lastUpdating Time

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 4.65 GB / 15.85 GB
  Binaries:
    Node: 18.20.3 - C:\Program Files\nodejs\node.EXE    
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD      
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD       
    pnpm: 8.10.0 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.21 - ~\.bun\bin\bun.EXE
  Browsers:
    Chrome: 127.0.6533.119
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    vitepress: ^1.3.1 => 1.3.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ZtfCoder** [comment]
https://github.com/ZtfCoder/blog      ---use store
https://github.com/ZtfCoder/ZtfCoder.github.io    ---use view

**Comment by ZhongxuYang** [comment]
Same problem, I suspect it's caused by the behavior of some plugins/dependencies.

**Comment by brc-dd** [comment]
vitepress uses git timestamp for lastUpdated. If you're just copying and committing things from one repo to another, the last commit time of all the files will change.

**Comment by ZtfCoder** [comment]
How should I operate correctly

**Comment by brc-dd** [comment]
Ah, I just re-read your question. You just need to add `fetch-depth: 0` to actions/checkout:

```yaml
      - name: Checkout
        uses: actions/checkout@v4 
        with:
          persist-credentials: false
          fetch-depth: 0
```

https://github.com/ZtfCoder/blog/blob/master/.github/workflows/main.yml#L16

**Comment by ZtfCoder** [comment]
> 啊，我刚刚重新阅读了你的问题。您只需要添加到操作/结帐：`fetch-depth: 0`
> 
> ```yaml
>       - name: Checkout
>         uses: actions/checkout@v4 
>         with:
>           persist-credentials: false
>           fetch-depth: 0
> ```
> 
> https://github.com/ZtfCoder/blog/blob/master/.github/workflows/main.yml#L16

Thank you, the last update time is now displayed correctly. Thank you very much!
