### ISSUE TITLE
有中文文档吗

### ISSUE THREAD

**Issue by linjialiang** [vuejs/vitepress#414]
### Is your feature request related to a problem? Please describe.

有中文文档吗

### Describe the solution you'd like

有中文文档吗

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ryanmoyo** [comment]
> https://vitepress.docschina.org/
> 
> > I have finished the translation with other contributors under the development model of Docschina 「印记中文」, Docschina is also responsible for many other document translations, and I am mainly responsible for vitepress translation. If you have any questions, please tell me directly.

Perhaps you can close this issue now.

**Comment by kiaking** [comment]
Ah cool thanks! Currently, Vue 3 docs is under refreshment. It uses VitePress and I think we'll have some update on VitePress as well. Then we can think of how translations should officially handled.

**Comment by linjialiang** [comment]
@linjialiang @ryanmoyo thank you
