### ISSUE TITLE
I couldn't find any relevant information in the document, and I'm wondering if this is a specific syntax?

### ISSUE THREAD

**Issue by ericgll** [vuejs/vitepress#4142]
### Describe the bug

the content within `{{ title }}` is not being displayed, and I don't understand why.

### Reproduction

[minimal](https://stackblitz.com/edit/vite-ucrpnh?file=docs%2Fexample.md)

### Expected behavior

Expecting `{{ title }}` to display correctly.

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.38 GB / 15.86 GB
  Binaries:
    Node: 18.20.3 - D:\nodejs\node.EXE
    npm: 10.7.0 - D:\nodejs\npm.CMD
    pnpm: 9.7.0 - D:\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/discussions/480

**Comment by ericgll** [comment]
thanks
