### ISSUE TITLE
Allow aside depth customization

### ISSUE THREAD

**Issue by jasonkuhrt** [vuejs/vitepress#4143]
### Is your feature request related to a problem? Please describe.

I would like to show level 2 and 3 titles in the aside. Currently, it only supports showing level 2.

### Describe the solution you'd like

Extend the config for aside to accept e.g. `{ depth: 2 }`.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/default-theme-config#outline

**Comment by jasonkuhrt** [comment]
Thanks @brc-dd! I missed outline, maybe in part because I didn't know that was the term.
