### ISSUE TITLE
When exporting a function and importing it through an alias: Failed to resolve import  from ... . Does the file exist?

### ISSUE THREAD

**Issue by michaelcozzolino** [vuejs/vitepress#4148]
### Describe the bug

in my vitepress project i am trying to use a component that uses an exported function and a type. the imports i tried are the following:

```
 import { test } from '@/test.ts';  // function import through alias not working
// import { test } from './test.ts'; // function, working
 import { A } from '@/testType.ts'; // working
// import { A } from './testType.ts'; // working
``` 
[plugin:vite:import-analysis] Failed to resolve import "@/test.ts" from "src/components/HelloWorld.vue". Does the file exist?
### Reproduction

https://stackblitz.com/edit/vitejs-vite-xaqvvy?file=src%2Fcomponents%2FHelloWorld.vue

### Expected behavior

All the imports i listed, should work

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (7) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: ^1.3.3 => 1.3.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Your aliases are wrong and vite command is failing too. Also you haven't configured alias for vitepress.

**Comment by brc-dd** [comment]
https://stackblitz.com/edit/vitejs-vite-mbgzua?file=vite.config.ts,docs/.vitepress/config.ts
