### ISSUE TITLE
How to enable environment file support?

### ISSUE THREAD

**Issue by jorekai** [vuejs/vitepress#415]
Hey, while implementing some documentation i need access to environment files. Currently, while reading in `.env.production` i am not able to receive env vars during build time. I am trying to specify an environment file via env-cmd with `env-cmd -f .env.production vitepress build docs` .

The docs do not specify clearly how to make use of custom environment file.

**Comment by kiaking** [comment]
@patak-js Is this something possible with Vite?

**Comment by brc-dd** [comment]
Hi, is this happening on latest version too? I am able to use `FOO=bar vitepress build docs` without any issue. Not sure about `env-cmd`. Can you provide a minimal, reproducible example for  this.

**Comment by brc-dd** [comment]
Closing this as stale, feel free to comment and reopen if the issue persists.
