### ISSUE TITLE
vitepress无法指定打包产物路径

### ISSUE THREAD

**Issue by thompsonjiang** [vuejs/vitepress#4155]
### Describe the bug

在vite.config.ts文件中配置了outDir为‘/’根路径，但未生效

### Reproduction

在vite.config.ts文件中配置了outDir为‘/’根路径，但未生效

### Expected behavior

vitepress可以指定打包路径

### System Info

```Text
vitepress 1.3.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
configure it in .vitepress/config.ts. Also it should be a relative path.

**Comment by thompsonjiang** [comment]
> Configure it in .vitepress/config.ts. Also it should be a relative path.

Thanks for help. But,it does not work.

![55415454](https://github.com/user-attachments/assets/702140ac-0557-4c53-ae30-538bfc9b3e17)

**Comment by brc-dd** [comment]
It's not inside build. https://vitepress.dev/reference/site-config#outdir

```ts
export default defineConfig({
  // ...,
  outDir: '../aaa'
})
```

**Comment by thompsonjiang** [comment]
Oh no."build" come from chatGPT.
