### ISSUE TITLE
当项目中使用了自动导入插件 unplugin-auto-import,想在文档md文件中引入某个组件报错

### ISSUE THREAD

**Issue by lcyhyl** [vuejs/vitepress#4156]
### Describe the bug

当项目中使用了自动导入插件,想在文档md文件中引入某个组件报错,提示 ref is not defined，如图所示
![image](https://github.com/user-attachments/assets/4daee68f-65b8-4591-9c35-943a7951c0c7)
![image](https://github.com/user-attachments/assets/33e9b90d-66a6-4af9-931c-0a98d1704aa2)

### Reproduction

无

### Expected behavior

请问需要如何去调整

### System Info

```Text
win11.谷歌
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please share you vite.config.ts and .vitepress/config.ts files.

**Comment by lcyhyl** [comment]
> Please share you vite.config.ts and .vitepress/config.ts files.

我已经解决了，请帮我关闭它吧，谢谢
