### ISSUE TITLE
node20.10.0安装vitepress失败

### ISSUE THREAD

**Issue by ddmy** [vuejs/vitepress#4157]
### Describe the bug

官网说支持node版本18+，我的node版本是20.10.0，安装时报错，@achrinza/node-ipc@9.2.2 对node版本有要求
![image](https://github.com/user-attachments/assets/2e03b42c-f346-427e-b256-ca3525340923)

### Reproduction

cli新建目录 运行 `yarn add -D vitepress`

### Expected behavior

能够正常安装

### System Info

```Text
System:
    OS: macOS 14.6.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 27.87 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 7.12.2 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.6
```

### Additional context

![image](https://github.com/user-attachments/assets/da721b6f-2627-4ca5-b0e3-f783a557b2dc)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It is likely coming from some other dep in your package.json. We don't use that package.

**Comment by ddmy** [comment]
> It is coming from some other dep in your package.json. We don't use that package. Please share your package.json. Most likely you've vue/cli installed.

![image](https://github.com/user-attachments/assets/744d058e-ac2f-44dc-ba5c-f74833e4e433)
This is my newly created empty directory. There is something strange about this problem

**Comment by brc-dd** [comment]
Try running `npx find-up-cli package.json`

**Comment by ddmy** [comment]
> Try running `npx find-up-cli package.json`

Sure enough, after running this command, I found a package.json in my current user directory. After deleting this file, I can install it normally. I thought package.json would only search the current directory. It seems that I still need to understand it specifically. Thank you very much!
