### ISSUE TITLE
SyntaxError: The requested module 'vue' does not provide an export named 'default'

### ISSUE THREAD

**Issue by Atw-Lee** [vuejs/vitepress#4158]
### Describe the bug

build error:
The requested module 'vue' does not provide an export named 'default'
file:///Users/lee/Codes/Work/PanSoft/pan-ui-vue/apps/docs/.vitepress/.temp/index.gDrBdFYw.js:1
import require$$0, { defineComponent, createVNode, ref, computed, watch, Fragment, watchEffect, createTextVNode, toRaw, mergeModels, useModel, openBlock, createBlock, unref, mergeProps, createSlots, withCtx, normalizeClass, createElementBlock, createElementVNode, toDisplayString, renderList, renderSlot, normalizeProps, nextTick } from "vue";

SyntaxError: The requested module 'vue' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async build (file:///Users/lee/Codes/Work/PanSoft/pan-ui-vue/node_modules/.pnpm/vitepress@1.3.3_@algolia+client-search@4.24.0_@types+node@22.0.0_async-validator@4.2.5_less@4_vyupewqor5ionkpvva6zm6cw7u/node_modules/vitepress/dist/node/serve-lJPQ9bCN.js:47053:24)

### Reproduction

{
  "name": "docs",
  "private": true,
  "scripts": {
    "dev": "vitepress dev",
    "docs:build": "vitepress build",
    "docs:preview": "vitepress preview"
  },
  "dependencies": {
    "@panui-vue/base": "workspace:*",
    "@panui-vue/pro": "workspace:*",
    "@panui-vue/icon": "workspace:*",
    "@panui-vue/excel": "workspace:*",
    "vue": "^3.4.31",
    "lodash-es": "^4.17.21",
    "@formily/vue": "^2.3.2",
    "dayjs": "1.11.12"
  },
  "devDependencies": {
    "@faker-js/faker": "^8.4.1",
    "@vitepress-demo-preview/component": "^2.3.2",
    "@vitepress-demo-preview/plugin": "^1.2.3",
    "postcss": "^8.4.40",
    "rollup-plugin-visualizer": "^5.12.0",
    "typescript": "^5.2.2",
    "vitepress": "^1.3.3",
    "@types/lodash-es": "^4.17.12",
    "@vitejs/plugin-vue-jsx": "^4.0.0"
  }
}

### Expected behavior

Normal build

### System Info

```Text
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 185.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.7.1 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.120
    Edge: 127.0.2651.105
    Safari: 17.6
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Atw-Lee** [comment]
<img width="546" alt="image" src="https://github.com/user-attachments/assets/f901fe26-e86e-441a-b31d-ff6ceeb9eab7">

**Comment by brc-dd** [comment]
Please share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) using https://vitepress.new or a github repository.
