### ISSUE TITLE
Problem with docs:serve when base is set

### ISSUE THREAD

**Issue by tk1** [vuejs/vitepress#416]
### Describe the bug

The built pages are not displayed correctly when using a base path.

### Reproduction

Set a base path not equal to `/` e.g. `/test/` . After 

```
yarn docs:build
yarn docs:serve
```

browse to http://localhost:5000/test/

### Expected behavior

correct rendering of pages

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 46.44 GB / 63.88 GB
  Binaries:
    Node: 16.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.11.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.38)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    vitepress: ^0.19.2 => 0.19.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Yeah this is because the `dist` folder structure. We need to tweak the folder after the build, before serve. It could be nice if we have a way to handle this.

**Comment by aantipov** [comment]
Why isn't it considered as a bug?

[Documentation](https://vitepress.vuejs.org/guide/configuration.html) suggests the following structure 
![image](https://user-images.githubusercontent.com/427621/142376122-bf2484df-be97-4925-b06a-eb6e024310f0.png)
and the following scripts 
![image](https://user-images.githubusercontent.com/427621/142376178-59298983-6506-43f1-89a3-7a0094547080.png)

Developers do what Documentation says and it doesn't work: `docs:serve` script doesn't work.
