### ISSUE TITLE
render '__VP_STATIC_START__'

### ISSUE THREAD

**Issue by huyanhai** [vuejs/vitepress#417]
### Describe the bug

When i build my website and visit it,One Page has '__VP_STATIC_START__' text.
![image](https://user-images.githubusercontent.com/28421572/137108113-574810d7-47a5-4a73-a450-92c4bab77d32.png)
![image](https://user-images.githubusercontent.com/28421572/137108177-11d30bb8-7ddd-4da7-bd22-915ed1541a51.png)

### Reproduction

Use {base:'xxx/xxx'} setting in config.js

### Expected behavior

I hope '__VP_STATIC_START__' is not render my website. 

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 758.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 14.1.1
  npmPackages:
    vitepress: ^0.20.0 => 0.20.0
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by huyanhai** [comment]
The page is https://static.melbdelivery.com/easi-packages-antd/0.0.33/website/index.html.
step 1:open this url
step 2:visit guide
setp 3: choose install and change quick start .

**Comment by posva** [comment]
Open a new issue once you have a **boiled down** reproduction in a github repository
