### ISSUE TITLE
Ignoring Subheaders

### ISSUE THREAD

**Issue by ajiho** [vuejs/vitepress#4171]
### Is your feature request related to a problem? Please describe.

I hope that when the global outline-level is deep, I can hide specific subheadings in the markdown file.

Is there any temporary solution? Thank you

### Describe the solution you'd like

reference：https://docsify.js.org/#/more-pages?id=ignoring-subheaders

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
In next minor version you'll be able to use

```
## Header {.ignore-header}
```
