### ISSUE TITLE
pages contains `process.env.NODE_ENV !== 'production'` report 404 error

### ISSUE THREAD

**Issue by Alanscut** [vuejs/vitepress#419]
### Describe the bug

any page which contains `process.env.NODE_ENV !== 'production'`, it will report 404 error

### Reproduction

step 1: clone https://github.com/Alanscut/vitepress-demo

step 2: run the project

step 3: visit the page
![image](https://user-images.githubusercontent.com/21104054/137422087-36365a9b-0e3d-4dcf-843c-a353da19f7aa.png)

### Expected behavior

could visit the page normally, the page will show:
![image](https://user-images.githubusercontent.com/21104054/137420751-c91d672e-b3fb-4574-bbaa-a212555a2fea.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 7.05 GB / 15.90 GB
  Binaries:
    Node: 12.22.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - E:\npm\repo\yarn.CMD
    npm: 7.21.1 - ~\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.50)
    Internet Explorer: 11.0.19041.1202
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Alanscut** [comment]
This seems to be a bug of https://github.com/vitejs/vite

**Comment by soetz** [comment]
More precisely, my observations are it’s just `process.env.NODE_ENV` that makes it break.

I was about to report the same thing so I have another [example repo](https://github.com/soetz/vitepress-bug-example).

**Comment by mrcego** [comment]
It could be nice to merge that pull request knowing the issue is resolved on it.

**Comment by Akryum** [comment]
Same issue here: https://github.com/vuejs/devtools/blob/6d8aba08346528847b361b0991073934bd324531/docs/plugin/plugins-guide.md

**Comment by mrcego** [comment]
News about this issue?

**Comment by kiaking** [comment]
I can reproduce this issue too, but how come current [Vite site is working](https://vitejs.dev/guide/env-and-mode.html#production-replacement) 🤔 It's using 0.22.4 (the latest) I think.

**Comment by kiaking** [comment]
Oh, OK. Build works. It's failing on Dev mode only. Still we need to fix this.

**Comment by meteorlxy** [comment]
I found the cause is that `process.env.NODE_ENV` is being statically replaced even in dev mode. 🤔

**Comment by brc-dd** [comment]
This looks much better than than that `wbr` workaround:

```md
`{{ 'process' + '.env.NODE_ENV' }} !== 'production'`
```

**Comment by meteorlxy** [comment]
I found the reason, vite always statically replaces `process.env.NODE_ENV` in dev mode

https://github.com/vitejs/vite/blob/cad27ee8c00bbd5aeeb2be9bfb3eb164c1b77885/packages/vite/src/node/plugins/clientInjections.ts#L57-L64

Now the solution is simple: always "escape" `process.env` in dev mode. I'll send a PR later.
