### ISSUE TITLE
Github页面部署后图片与icon无法加载，本地可以正常显示

### ISSUE THREAD

**Issue by Mskins** [vuejs/vitepress#4203]
### Describe the bug

Github页面部署后图片与icon无法加载，本地可以正常显示。
I am encountering an issue where images and icons cannot be loaded after deploying to GitHub Pages. These images and icons display correctly when viewed locally.

### Reproduction

no

### Expected behavior

I want to know where the problem lies.

### System Info

```Text
win11，edge
```

### Additional context

![PixPin_2024-09-15_23-32-49](https://github.com/user-attachments/assets/d3f0e475-e72a-449e-83a1-9a4d20b0dc35)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Try running vitepress build command and preview command locally. It should show broken images too. Most likely you need to move your images referenced from frontmatter to the public directory.

**Comment by Mskins** [comment]
OK,thank you.The problem has been solved.
