### ISSUE TITLE
Markdown absolute links to plaintext files in public directory attempts to link as HTML

### ISSUE THREAD

**Issue by lifehackerhansol** [vuejs/vitepress#4208]
### Describe the bug

If there is a plaintext file in public directory, and the file extension is unrecognized (i.e. `.txt` files are recognized, but `.ini`, or any random combination of file extensions, are not), the build system is attempting to convert the links to append `.html` to it. This causes the link to 404.

### Reproduction

NOTE: this reproduces a scenario in the testing environment. **docs:build doesn't even run because, as a result of the below generation, the link is being treated as dead.**

Add this to `/public/hello.ini`:
```ini
[helloworld]
```

And then have any page link to it like so:
```md
[download hello.ini](/hello.ini)
```

And it will generate:
```html
<a href="/hello.ini.html">download hello.ini</a>
```

### Expected behavior

The docs seem to suggest that files in the `public` directory will be copied as-is to the output directory; the same logic should apply to links. That is to say, there should be no `.html` suffix in the `href` and either the download or the browser opening the resulting file in plaintext should proceed.

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 4.95 GB / 31.92 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    vitepress: ^1.3.4 => 1.3.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
```
process.env.VITE_EXTRA_EXTENSIONS = 'ini'
```

Put this on top of your .vitepress config file.
