### ISSUE TITLE
Option for AutoCorrect/AutoFormat-like feature

### ISSUE THREAD

**Issue by thdoan** [vuejs/vitepress#4213]
### Is your feature request related to a problem? Please describe.

It would be nice to an have option to enable automatic text replacements similar to Microsoft Word's AutoCorrect and AutoFormat features.

### Describe the solution you'd like

These replacements would be especially helpful (except when inside a code block):

- `""` to `“”`
- `''` to `‘’`
- `--` to `—`
- `1/2` to `½`
- `(c)` to `©`
- `(r)` to `®`
- `(tm)` to `™`
- `+/-` to `±`
- `<=` to `≤`
- `>=` to `≥`
- `...` to `…`
- `->` to `→`
- `<-` to `←`
- `-->` to `🡒`
- `<--` to `🡐`
- `=>` to `⇒`
- `<=` to `⇐`

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
```ts
export default defineConfig({
  markdown: {
    typographer: true,
  },
});
```

https://github.com/markdown-it/markdown-it

some of those replacements you mentioned are not supported and should be done via third party markdown-it plugins if possible
