### ISSUE TITLE
Inquiry: Customizing "On this page" Navigation Title in VitePress

### ISSUE THREAD

**Issue by shuizhutieniu** [vuejs/vitepress#4220]
I am wondering if there is currently a feature that allows customization of the "On this page" navigation title. If not, I would like to suggest adding this capability to enable better customization for different contexts.
![image](https://github.com/user-attachments/assets/007fc955-9005-4866-8518-8b3a04f28d81)

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/default-theme-config#outline

**Comment by shuizhutieniu** [comment]
I'm sorry I don't know how to change the navigation title of each page, I've tried:

```raw
---
outline:
  label: 'myTitle'
  level: [2, 4]
---
```

But it didn't work.

**Comment by brc-dd** [comment]
https://stackblitz.com/edit/vite-49kuwj?file=docs/index.md,docs/.vitepress/config.ts

**Comment by shuizhutieniu** [comment]
> https://stackblitz.com/edit/vite-49kuwj?file=docs/index.md,docs/.vitepress/config.ts

Thank you for your answer, but I want each page to have a given navigation title, so I think it needs to be modified using "frontmatter", so I tried the methods mentioned above, but it didn't work

**Comment by brc-dd** [comment]
Overriding label per page via frontmatter is not supported. Why do you need it?

**Comment by shuizhutieniu** [comment]
I had a strange idea. Thank you all the same
