### ISSUE TITLE
Hydration mismatch only occurs when reloading in the production build.

### ISSUE THREAD

**Issue by ubugeeei** [vuejs/vitepress#4231]
### Describe the bug

Possible similar issues:
- https://github.com/vuejs/vitepress/issues/4099
- https://github.com/vuejs/vitepress/issues/4167
- https://github.com/vuejs/vitepress/issues/3780

---

Hydration mismatch occurs only when reloading a specific page in the production build.
It can be reproduced locally as well.
It doesn’t happen in the development build, nor when navigating through the sidebar.

https://github.com/user-attachments/assets/2bb6387c-2d62-4dc2-96e4-ecd5bdf3491f

### Reproduction

This repository (my product)

https://github.com/ubugeeei/reading-vuejs-core-vapor

```sh
git clone https://github.com/ubugeeei/reading-vuejs-core-vapor
cd reading-vuejs-core-vapor
ni
DEBUG='*' nr build
DEBUG='*' nr preview
```

---

※ During the initial build, a fetch to GitHub will run, so it may take a little time.
(From the second time onward, the cache will be used)

The plugin implementation is here.
https://github.com/ubugeeei/reading-vuejs-core-vapor/tree/9fa8c614c6047241dc2a6bdac39dca1815318d6a/.vitepress/plugins/markdown-it/github

### Expected behavior

Hydration should complete normally and the screen should render correctly even after reloading.

### System Info

```Text
System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 43.41 GB / 96.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.16.0 - ~/.volta/tools/image/node/20.16.0/bin/node
    Yarn: 1.22.22 - ~/.volta/tools/image/yarn/1.22.22/bin/yarn
    npm: 10.8.1 - ~/.volta/tools/image/node/20.16.0/bin/npm
    pnpm: 9.7.1 - ~/.volta/tools/image/pnpm/9.7.1/bin/pnpm
    bun: 1.1.27 - ~/.bun/bin/bun
  Browsers:
    Chrome: 129.0.6668.70
    Safari: 16.3
  npmPackages:
    vitepress: ^1.3.4 => 1.3.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Your plugin seems to be generating div inside p which will break html

```html
<p><a href="https://github.com/vuejs/core-vapor/blob/30583b9ee1c696d3cb836f0bfd969793e57e849d/packages/compiler-vapor/src/ir/index.ts#L22" target="_blank" rel="noreferrer"><div class="github-source">
```

first point - https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch

**Comment by ubugeeei** [comment]
Oops! I see, I completely missed that.
Thank you, I’ll close it.

**Comment by brc-dd** [comment]
`md.renderer.rules.text` thing in your plugin won't work, you'll need to first adjust parser (using something like `md.inline.ruler.before`) to make those links separate block-level tokens.

**Comment by ms264556** [comment]
> Your plugin seems to be generating div inside p which will break html

I had a similar issue with invalid html 'silently' breaking my interactive pages: https://github.com/vuejs/vitepress/discussions/4191

It would be super useful if there was some way of having html errors break the build, so I don't have to run docs:preview then visit every page looking for "hydration completed but contains mismatches" warnings in the console.

**Comment by brc-dd** [comment]
@ms264556 I'm not sure if there is any easy way to do that. People usually have e2e tests for those kind of things that capture browser warnings and errors. Alternatively if you want only the invalid html related errors, then there is https://html-validate.org/ which is what Nuxt uses in one of their modules.

**Comment by ms264556** [comment]
> People usually have e2e tests for those kind of things that capture browser warnings and errors for all entries in sitemap

Yes, I have this now :smirk:. 

I'd been *hoping* your SSG had visibility into the hydration process, so that this request would be straightforward.
