### ISSUE TITLE
Error occurred when using team components

### ISSUE THREAD

**Issue by wolono** [vuejs/vitepress#4238]
### Describe the bug

I added team component feedback error in index.md
![image](https://github.com/user-attachments/assets/c011afbb-5b81-49f9-9c58-4244fc902a86)

### Reproduction

---
layout: home

hero:
  name: VitePress
  text: Vite & Vue powered static site generator.
  tagline: Simple, powerful, and performant. Meet the modern SSG framework you've always wanted.
  actions:
    - theme: brand
      text: Get Started
      link: /example
    - theme: alt
      text: View on GitHub
      link: https://github.com/vuejs/vitepress
---

<script setup>
import { VPTeamMembers } from 'vitepress/theme'

const members = [
  {
    avatar: 'https://www.github.com/yyx990803.png',
    name: 'Evan You',
    title: 'Creator',
    links: [
      { icon: 'github', link: 'https://github.com/yyx990803' },
      { icon: 'twitter', link: 'https://twitter.com/youyuxi' }
    ]
  },
  ...
]
</script>

# Our Team

Say hello to our awesome team.

<VPTeamMembers size="small" :members="members" />

### Expected behavior

normal

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: latest => 1.3.4
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wolono** [comment]
https://stackblitz.com/edit/vite-udgrmq?file=docs%2Findex.md

**Comment by brc-dd** [comment]
remove that `...` -- it was meant to indicate that there can be more entries similar to above.

**Comment by wolono** [comment]
How should I use team in index.md

**Comment by brc-dd** [comment]
https://stackblitz.com/edit/vite-syhdt2?file=docs/index.md

**Comment by wolono** [comment]
Thanks
