### ISSUE TITLE
Feature request: add social link icon for JSR to default template

### ISSUE THREAD

**Issue by dirkluijk** [vuejs/vitepress#4256]
### Is your feature request related to a problem? Please describe.

JSR is an alternative for NPM, where you can publish ESM-only TypeScript packages. It's mainly promoted by Deno, but can also be used in Node.js.

### Describe the solution you'd like

It would be nice to have a `jsr` social link available in the default template of Vitepress, so it's easier to link to your package on jsr.io.

A possible SVG:
```svg
<svg viewBox="0 0 13 7" aria-hidden="true">
<g>
<path d="M1,3h1v1h1v-3h1v4h-3"/>
<path d="M5,1h3v1h-2v1h2v3h-3v-1h2v-1h-2"/>
<path d="M9,2h3v2h-1v-1h-1v3h-1"/>
</g>
</svg>
```
(we would have to check if we have permissions for this SVG to be used)

### Describe alternatives you've considered

Providing a custom SVG.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I'm personally inclined to add this. But let's still wait for some upvotes here otherwise it'd be unfair to other icons that are still pending (like #4135).

And regarding SVG, we will use one from https://simpleicons.org.

**Comment by dirkluijk** [comment]
Makes sense, agreed!
