### ISSUE TITLE
the html tag style content in markdown cause error 'Element is missing end tag'

### ISSUE THREAD

**Issue by wbxl2000** [vuejs/vitepress#4258]
### Describe the bug

when I add html tag style content in markdown, the plugin:vite:vue will be error

<img width="1357" alt="image" src="https://github.com/user-attachments/assets/fb76a527-0a72-4182-8b63-36a88969d330">

### Reproduction

https://stackblitz.com/edit/vite-nk7jtp?file=docs%2Findex.md

just in the index.md

### Expected behavior

compile successfully

### System Info

```Text
no need.
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wbxl2000** [comment]
move from https://github.com/vitejs/vite-plugin-vue/issues/455

**Comment by brc-dd** [comment]
Please escape that tag:

```md
[how to use `<video>`](https://...)

alternatively

[how to use &lt;video&gt;](https://...)

or

[how to use \<video\>](https://...)
```
