### ISSUE TITLE
Unable to customizing the home page color

### ISSUE THREAD

**Issue by yangmingshan** [vuejs/vitepress#4262]
### Describe the bug

Ref: https://vitepress.dev/reference/default-theme-home-page#customizing-the-name-color
Overriding `--vp-home-hero-name-color` and other variables are not working after build.

### Reproduction

https://github.com/vue-mini/vue-mini/tree/vitepress-reproduce

1. Clone the repo
2. pnpm install
3. pnpm docs:build
4. pnpm docs:preview
5. See the home page，it should look like https://vuemini.org/

### Expected behavior

CSS variables overriding should work.

### System Info

```Text
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 10.84 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - ~/.local/state/fnm_multishells/77380_1728494719725/bin/node
    npm: 10.9.0 - ~/.local/state/fnm_multishells/77380_1728494719725/bin/npm
    pnpm: 9.12.1 - ~/.local/state/fnm_multishells/77380_1728494719725/bin/pnpm
    bun: 1.1.24 - ~/.bun/bin/bun
  Browsers:
    Chrome: 129.0.6668.90
    Safari: 17.6
  npmPackages:
    vitepress: ^1.4.0 => 1.4.0
```

### Additional context

It's a CSS order issue.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
#4098 ?
