### ISSUE TITLE
Console throws an error when the markdown content includes ` {{a.xxx}} `

### ISSUE THREAD

**Issue by zhourunjie1988** [vuejs/vitepress#4265]
When the Markdown content includes expressions like \`{{a.xxx}}`\, the console throws an error: "Cannot read properties of undefined". I tried to modify the original Markdown to the content below:
```
<code>&lbrace;&lbrace; {{a.xxx}} &rbrace;&rbrace;</code>
```
and it renders correctly. Is there a better solution? Why is the content inside `` parsed as an expression?
![image](https://github.com/user-attachments/assets/4c6bfde2-a624-4e45-9a08-f299f8bacb88)

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/discussions/480
