### ISSUE TITLE
Navigation bar disappears

### ISSUE THREAD

**Issue by Theo-Messi** [vuejs/vitepress#4277]
### Describe the bug

The navigation bar of https://vitepress.dev/ disappears

### Reproduction

<img width="493" alt="image" src="https://github.com/user-attachments/assets/2144ed7d-a01f-4dae-a716-b333d41df812">

### Expected behavior

无

### System Info

```Text
无
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
fixed
