### ISSUE TITLE
image markdown not working as expected

### ISSUE THREAD

**Issue by tomoayan** [vuejs/vitepress#4285]
### Describe the bug

image embed markdown not rendering as a image insted it is rendered as a plain text when link (of media/image) have spaces.
`![An image](/image inside public.png)` - renders as plain text
`![An image](/image-inside-public.png)` - renders as normal image

<br>

**why can't i use "-" or "_"?**
I am making a personal blog, something like obsidian publish, using obsidian as a cms. I already have many many attachments in the vault and can't change/rename every attachment's name one by one.

### Reproduction

![An image](/image inside public.png)

### Expected behavior

render as a image

### System Info

```Text
System (WSL):
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 4.80 GB / 7.45 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.16.0 - /usr/bin/node
    npm: 10.9.0 - /usr/bin/npm
    pnpm: 9.12.1 - /usr/bin/pnpm
  npmPackages:
    vitepress: ^1.4.1 => 1.4.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Because that's how commonmark and URLs in general work:

<img width="998" alt="image" src="https://github.com/user-attachments/assets/5eaf194a-51f3-4ff8-9818-1f170cc29e4b">

You can't have spaces in URLs. You'll need to encode ` ` to `%20`:

<img width="1180" alt="image" src="https://github.com/user-attachments/assets/c4283acd-a91d-4937-b1c5-517bbb52d62c">
