### ISSUE TITLE
Markdown files are not rebuilt when their "includes" change

### ISSUE THREAD

**Issue by everdimension** [vuejs/vitepress#4289]
### Describe the bug

I have the following vitepress structure:

```
docs-vitepress
├── endpoints.md
├── entities.md
├── generated
│   ├── endpoints.md
│   └── entities.md
├── index.md
└── overview.md
```

`enpoints.md` simply contains an include of `./generated/endpoints.md`:

```md
<!--@include: ./generated/endpoints.md-->
```

This is done to avoid the `/generated/` path segment in the URL.

**Problem:** When content of `/generated/endpoints.md` changes, content of `/endpoints.md` doesn't change

### Reproduction

https://github.com/everdimension/vitepress-watch-included-issue

### Expected behavior

It's expected that when content of `/generated/endpoints.md` changes, the updates will be reflected in the build

### System Info

```Text
OS: macOS 13.5.1
Memory: 16 GiB
Architecture: aarch64


  System:
    OS: macOS 13.5.1
    CPU: (8) x64 Apple M1
    Memory: 25.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0
    Yarn: 1.22.19
    npm: 10.2.5
  Browsers:
    Chrome Canary: 131.0.6778.0
    Safari: 16.6
  npmPackages:
    vitepress: ^1.4.1 => 1.4.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/pull/2581

**Comment by everdimension** [comment]
Awesome, thanks!

I didn't find this in the docs

**Comment by brc-dd** [comment]
Ok this has regressed. Actually you shouldn't be needing any extra config. I just saw my old comment -  https://github.com/vuejs/vitepress/issues/117#issuecomment-1732388826

**Comment by brc-dd** [comment]
Fixed in latest version. You can remove that additional config. It's not needed.
