### ISSUE TITLE
Prev / Next links

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vitepress#43]
Ref: https://vuepress.vuejs.org/theme/default-theme-config.html#prev-next-links

This one may be tricky since VitePress doesn't include the whole site's page metadata (for bundle size considerations). We may need to extract this information at build time and include it directly in each individual page's metadata (`$page`)

**Comment by akauppi** [comment]
This is a vital feature for me. Will be happy to help; try out; discuss approaches from a user point of view.

**Comment by Spice-Z** [comment]
Hi !
I tried to solve this issue, and created [PR](https://github.com/vuejs/vitepress/pull/56)!

I want vitepress core team to check my PR, but I'm not sure who to mention... 🤔 
@yyx990803  ?
