### ISSUE TITLE
HMR not working with `@include` syntax

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/vitepress#4303]
### Describe the bug

If you change the file with `@include`, it works, but if you change the `.md` file get included, it won't update.
Although it's showing `hmr update` in CLI, but it's just not updating in the page.

### Reproduction

Will provide one if above is not clear, really busy at the moment.🙏

### Expected behavior

Content should update correctly

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 9.53 GB / 31.69 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.2 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (128.0.2739.79)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vitepress: ^1.4.1 => 1.4.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/issues/4289

**Comment by xsjcTony** [comment]
Thanks.

**Comment by brc-dd** [comment]
Manually configuring cache: false shouldn't be needed. It has regressed. I've reopened that issue. Please track it instead.
