### ISSUE TITLE
How to disable all styles for a .vp-doc table

### ISSUE THREAD

**Issue by qianmoQ** [vuejs/vitepress#4309]
### Describe the bug

![image](https://github.com/user-attachments/assets/5ea2461c-44d2-4ba6-bb8c-fa1af01bfb0f)

My component style is the red box on the left, and the blue box on the right is the default of vitepress, which causes the style of my component to be overwritten. How can I configure the table style without using vitepress and use the style of my component?

我的组件样式是左侧红框的，右侧蓝框是 vitepress 默认的，导致覆盖了我组件的样式，我怎么才能配置不使用 vitepress 的 table 样式，用我组件的样式

### Reproduction

None

### Expected behavior

None

### System Info

```Text
None
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/guide/markdown#raw

**Comment by qianmoQ** [comment]
Thank you
