### ISSUE TITLE
我在vitepress中引入了tailwindcss，但是在md文档中使用class属性不生效。

### ISSUE THREAD

**Issue by xaitx** [vuejs/vitepress#4315]
我在vitepress中引入了tailwindcss，但是在md文档中使用class属性不生效。
![image](https://github.com/user-attachments/assets/87351f6d-f88d-4a79-b032-e5dd6d2d0942)
![image](https://github.com/user-attachments/assets/76012bc9-5e5f-460c-a2fc-514202c3a998)

**Comment by brc-dd** [comment]
Check if you've included markdown files in `content` in your tailwind config. https://tailwindcss.com/docs/content-configuration
