### ISSUE TITLE
Add support for emojis in the sidebar

### ISSUE THREAD

**Issue by Veetaha** [vuejs/vitepress#4319]
I tried to add this item to the sidebar to denote an experimental feature:

```js
{
    text: "🔬 overwritable",
    link: "/reference/builder/member/overwritable",
}
```

but it rendered without the 🔬 symbol:
![image](https://github.com/user-attachments/assets/7c4a4751-520a-4af5-bab8-11b65d77a78b)

I think it makes sense to allow emojis there. This still looks nice (I just added this manually via dev tools for demo purposes):

![image](https://github.com/user-attachments/assets/3905fe63-2cd5-4ca6-a514-5aa84f04d300)

**Comment by brc-dd** [comment]
Seems to work fine 👀 

<img width="150" alt="image" src="https://github.com/user-attachments/assets/970aaff2-fedf-4e12-ac1c-b6341290d0a9">

https://stackblitz.com/edit/vite-jn4gzs?file=docs/.vitepress/config.ts

**Comment by Veetaha** [comment]
Indeed, maybe I just didn't update the page :flushed:, I though I did, but now that I try it again I can't reproduce this. I'll close this issue, thanks!

**Comment by brc-dd** [comment]
I'm seeing some issues with restarting being unreliable. Probably something changed in newer vite versions. Tracking it along bun support in #4313
