### ISSUE TITLE
构建后首页丢失特效颜色

### ISSUE THREAD

**Issue by 404forever1** [vuejs/vitepress#4325]
dev可以正常显示
![image](https://github.com/user-attachments/assets/0d4ef388-4322-4c53-9bfe-cd2d059ff1eb)

**Comment by 404forever1** [comment]
<style>
:root {
  --vp-home-hero-name-color: transparent;
  --vp-home-hero-name-background: -webkit-linear-gradient(120deg, #bd34fe 30%, #41d1ff);

  --vp-home-hero-image-background-image: linear-gradient(-45deg, #bd34fe 50%, #47caff 50%);
  --vp-home-hero-image-filter: blur(40px);
}
</style>

**Comment by 404forever1** [comment]
解决了，将内容移动到custom.css

**Comment by brc-dd** [comment]
Duplicate of #4098
