### ISSUE TITLE
配置 markdown.theme 主题未完全生效

### ISSUE THREAD

**Issue by xiechen1201** [vuejs/vitepress#4333]
### Describe the bug

当我配置了在 .vitepress/config.mjs 中配置`markdown.theme: { light: 'night-owl', dark: 'night-owl' }`后，当页面为白天模式的时候，代码块的样式并没有完全生效，背景颜色还是白色。

以下是我的配置：

```js
// Markdown 配置
  markdown: {
    // 代码块主题
    theme: {
      light: 'night-owl',
      dark: 'night-owl'
    }
  }
```

以下是实际的效果：
![image](https://github.com/user-attachments/assets/6c9c4723-b062-44d7-8808-46efd4a89895)

以下是我的版本：

```json
{
  "devDependencies": {
      "vitepress": "^1.4.2"
   }
}
```

### Reproduction

https://stackblitz.com/edit/vite-2suua2?file=docs%2F.vitepress%2Fconfig.ts

### Expected behavior

希望无论是明亮模式还是黑暗模式都可以显示为 night-owl 的黑色主题

### System Info

```Text
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1
    Memory: 91.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 17.1.2
  npmPackages:
    vitepress: ^1.4.2 => 1.4.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Duplicate of #3154
