### ISSUE TITLE
shiki language lazy loading not working with twoslash

### ISSUE THREAD

**Issue by kravetsone** [vuejs/vitepress#4334]
### Describe the bug

I wants to build my documentation with `bunx vitepress build docs` (running in node) but it fails with `[vitepress] Language `js` not found, you may need to load it first`

Solved by downgrading to `1.4.2`

[Repository](https://github.com/gramiojs/documentation) 

[CICD logs](https://github.com/gramiojs/documentation/actions/runs/11645088846/job/32427726195)

### Reproduction

https://github.com/gramiojs/documentation/commit/561ce311bbcaf448b716e28a3b412f8a37966a2f

### Expected behavior

Should work

### System Info

```Text
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 7700 8-Core Processor
    Memory: 1.36 GB / 31.15 GB
  Binaries:
    Node: 22.10.0 - ~\AppData\Local\fnm_multishells\639520_1730573241452\node.EXE
    npm: 10.9.0 - ~\AppData\Local\fnm_multishells\639520_1730573241452\npm.CMD
    bun: 1.1.34 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (130.0.2849.46)
  npmPackages:
    vitepress: ^1.4.3 => 1.4.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hmm, twoslash is causing issues with lazy loading, but even if I disable it, curl and tree are causing issues. I don't see any language file for those. Weird.

**Comment by brc-dd** [comment]
Pushed a temporary patch in v1.4.4. Keeping the issue open though.

**Comment by brc-dd** [comment]
Should work fine with 1.4.5
