### ISSUE TITLE
Invalid parsing of `|` under the backticks in markdown tables

### ISSUE THREAD

**Issue by Veetaha** [vuejs/vitepress#4338]
### Describe the bug

I tried writing this table:

```
| Form                            | Meaning
|---------------------------------|----------------------------
| `#[builder(with = |...| expr)]` | Custom *infallible* closure
```

and this was rendered:

![image](https://github.com/user-attachments/assets/bd362fad-fec8-462d-a298-ec714a09114f)

I assume the `|` inside of backticks is invalidly interpreted as the termination of the cell.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's same as github.

```
| Form                            | Meaning
|---------------------------------|----------------------------
| `#[builder(with = |...| expr)]` | Custom *infallible* closure
```

is rendered as 

| Form                            | Meaning
|---------------------------------|----------------------------
| `#[builder(with = |...| expr)]` | Custom *infallible* closure

You'll need to escape `|` using backslash:

```
| Form                            | Meaning
|---------------------------------|----------------------------
| `#[builder(with = |...| expr)]` | Custom *infallible* closure
```

| Form                            | Meaning
|---------------------------------|----------------------------
| `#[builder(with = \|...\| expr)]` | Custom *infallible* closure

**Comment by Veetaha** [comment]
Thanks for the clarification! I've added `prettier`
