### ISSUE TITLE
Build script does not work with Yarn Berry

### ISSUE THREAD

**Issue by lukeeno** [vuejs/vitepress#435]
### Describe the bug

I created a new project by following the instructions [here](https://vitepress.vuejs.org/guide/getting-started.html). I only added `yarn set version berry`. Also, there is a small undocumented issue that I had to manually add Vue 3 dependency.

When I run `yarn docs:build`, it does not work.

```
vitepress v0.20.0
⠸ building client + server bundles...EROFS: read-only filesystem, mkdir '/node_modules/vitepress/dist/client/app/temp'
✖ building client + server bundles...
build error:
 [Error: ENOTDIR: not a directory, unlink '/home/lukeeno/vitepress-starter/.yarn/cache/vitepress-npm-0.20.0-e06cb3d514-59d85243c3.zip/node_modules/vitepress/dist/client/app/temp'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'unlink',
  path: '/home/lukeeno/vitepress-starter/.yarn/cache/vitepress-npm-0.20.0-e06cb3d514-59d85243c3.zip/node_modules/vitepress/dist/client/app/temp'
}
```

### Reproduction

```bash
mkdir vitepress-starter && cd vitepress-starter
yarn init -y
yarn set version berry
yarn add --dev vitepress vue@^3.2.13
mkdir docs && echo '# Hello VitePress' > docs/index.md
yarn vitepress build docs
```

### Expected behavior

It should build the docs.

### System Info

```shell
System:
    OS: Linux 5.14 undefined
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 3.50 GB / 15.50 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.11.1 - /usr/bin/node
    Yarn: 3.1.0 - /usr/bin/yarn
    npm: 8.1.0 - /usr/bin/npm
  Browsers:
    Chromium: 95.0.4638.54
    Firefox: 93.0
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by lukeeno** [comment]
When I use `nodeLinker: "node-modules"`, it works. So this applies only to Plug'n'Play.

**Comment by jonaskuske** [comment]
This happens because Yarn PnP installs packages as read-only, so packages can't write into their install directory. Unfortunately vitepress' current `tempDir` is set to its install location, so yarn throws this error.

A quick fix without having to switch over to `nodeLinker` entirely is to run **`yarn unplug vitepress`**, which installs `vitepress` in a regular, writable directory instead of a read-only zip archive.

The real fix is to change the `tempDir` to somewhere outside the `vitepress` package root, as my PR does.

**Comment by lukeeno** [comment]
Thank you very much! You are right. I also thought it is because of the read-only zip files, but wasn't sure. Thanks for PR. Looking forward to use your fix. You are quick! 🥳
