### ISSUE TITLE
本地搜索功能，不能搜索到中文，只能搜索到段落的第一个字或标点符号后面的汉字

### ISSUE THREAD

**Issue by jspsh** [vuejs/vitepress#4350]
### Describe the bug

本地搜索功能，不能搜索到中文，只能搜索到段落的第一个字或标点符号后面的汉字

### Reproduction

本地搜索功能，不能搜索到中文，只能搜索到段落的第一个字或标点符号后面的汉字

### Expected behavior

本地搜索功能，不能搜索到中文，只能搜索到段落的第一个字或标点符号后面的汉字

### System Info

```Text
本地搜索功能，不能搜索到中文，只能搜索到段落的第一个字或标点符号后面的汉字
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please track - https://github.com/vuejs/vitepress/issues/4049#issuecomment-2230316869

(please comment on that thread if those solutions don't work)
