### ISSUE TITLE
Introducing three column column layout for "on this page" section

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/vitepress#436]
### Is your feature request related to a problem? Please describe.

Generally, a lengthy docs page require "on this page" and most docs framework including gridsome docs, nuxt docs, docus, etc provide a third column "on this page" for navigating between the different section on the page.

VuePress & VitePress provides the same "on this page" section in the left sidebar for that page when that page is opened but I guess making the left sidebar consistent across different pages will be a good choice.

### Describe the solution you'd like

Adding thrid column on right for on this page section instead of showing it in left sidebar.third

### Describe alternatives you've considered

I created my own theme.

Another alternative can be providing another three-column layout theme just like the default theme.

### Additional context

I know this is a big change so this is just thought as VitePress is still in its early stage.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jd-0001** [comment]
New vuejs 3 docs have this layout but that theme is tightly coupled with vuejs docs.

**Comment by kiaking** [comment]
We have this in `theme-next` 👍
