### ISSUE TITLE
FR: Code Block that renders Vue file component and source code

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/vitepress#437]
### Is your feature request related to a problem? Please describe.

In order to create good documentation of a standalone Vue component, we want to show many usage examples.

Every usage example is a Vue file.

We need to be able to import a Vue file in Vitepress, show its source code as CodeBlock.
- Not just a single code block like you can already do in Vitepress, but a Codeblock with tabs on top that split up the source code in `template` / `script` / `style` tabs.
- Also, another tab should say `example` rendering the actual imported Vue component.

### Describe the solution you'd like

The ideal syntax would look something like this:
```html
<CodeBlockComponent filename="blitz-form/Basics - Basic Example" />
```
And here is a video of how it would render in Vitepress:

https://user-images.githubusercontent.com/3253920/140631280-adae2d0b-47d9-4172-b105-f6f4ee5f41f4.mp4

(I have styled this a little bit to fit my docs style, but of course the styling can be way more bare-bones and we can overwrite the styling with CSS.)

### Describe alternatives you've considered

I actually already finished this feature for VitePress. I created my custom solution.

Under the hood I'm using a combination of these import methods:
```js
import(`../docs/${filename}.vue`) // for the component
// and
import(`../docs/${filename}.vue?raw`) // for the source code
```

~~Everything works when I'm using the VitePress development server. However, as soon as I build and deploy my code to a hosting service, all the Code Blocks break.~~

~~I searched a lot for solutions, but this is not my strongest point. This past week I tried a bunch of things but still haven't found out how to make it work.~~

(See next comment, where I explain how I fixed it)

### Additional context

I would love to request for an official solution for what I'm trying to do.

I believe a lot of developers who want to share a Vue component and whip up a quick VitePress documentation about their component, would love this feature.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by mesqueeb** [comment]
I was able to fix it by hardcoding the file paths : )

```js
// instead of:
import(`../docs/${filename}.vue`)
import(`../docs/${filename}.vue?raw`)

// hardcode all use cases to Eg.:
import(`../docs/MyComponent.vue`)
import(`../docs/MyComponent.vue?raw`)
```

I still think however, this would be a very handy native VitePress component for devs to use!

So I will keep the feature request open.

If there is a request for it I can try to make a PR with my own implementation.

**Comment by aibayanyu20** [comment]
Maybe you can use [vite-plugin-vitepress-demo](https://www.npmjs.com/package/vite-plugin-vitepress-demo)

**Comment by brc-dd** [comment]
Closing due to lack of interest.
