### ISSUE TITLE
No `theme.d.ts` file in the installed library

### ISSUE THREAD

**Issue by roamiiing** [vuejs/vitepress#438]
### Describe the bug

I want to use TS for my theme config, but I get the following error:
```
TS2307: Cannot find module 'vitepress/theme' or its corresponding type declarations.
```
I think it happens because there is no `theme.d.ts` in the `files` array of `package.json`.

### Reproduction

1. Install vitepress
2. Create `docs/.vitepress/theme/index.ts` file
3. Type `import DefaultTheme from 'vitepress/theme'`
4. Get the error from the IDE

### Expected behavior

No type error

### System Info

```shell
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 25.62 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.1 - ~/.nvm/versions/node/v16.4.1/bin/node
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.1/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox Developer Edition: 92.0
    Safari: 14.1
  npmPackages:
    vitepress: ^0.20.1 => 0.20.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yyx990803** [comment]
https://github.com/vuejs/vitepress/pull/489#issuecomment-1013711820
