### ISSUE TITLE
A way to configure the directory for docs instead of the root folder

### ISSUE THREAD

**Issue by kaesar** [vuejs/vitepress#4384]
### Is your feature request related to a problem? Please describe.

Currently, I have three small blogs due to different approaches. I have customized certain things in the theme design when downloading VitePress, for example, to include in these projects native web components that can be loaded as an html tag from a simple Markdown (.md) file, besides include TailwindCSS.
I am not interested in doing a Fork and would like to evaluate if it is possible to change the directory of the Vitepress documents (separating or decoupling the content of the mechanism) in order to have versatility and not having to copy in each project folder the theme and components (I mean, an `srcDir` different from `root`).

### Describe the solution you'd like

One idea would be to allow the base directory of Vitepress to be different from the root, separating or decoupling the content of the theme or template (although I would understand if it is a matter of design).
What is wanted is to use the modified Vitepress theme on different blogs without having to copy it to each project (thinking in multi-project of content)

### Describe alternatives you've considered

1. I have tried to apply on each of the three Vitepress blogs with the custom theme ( just that it can lead to theme desynchronization).

2. Another way is to have every blog under root folder and change `srcDir` in `config.mjs` according the blog selected.

3. Using a symbolic link but eventualy some errors occurs cause it resolves another path (e.g. `../../path`) and finally doesn't work.

### Additional context

The project with native web components that can be use in Markdown (.md) is: <https://github.com/kaesar/onmind-cui>

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Ah, not sure if I understood your problem correctly, but you can just import your shared theme and config?

```
- shared/
-       /theme/index.ts
-       /theme/...other stuff...
-       /config/index.ts
-       /config/...other stuff...
- blog1/
-      /.vitepress/theme/index.ts (export default from '/../shared/theme/index.js')
```

**Comment by kaesar** [comment]
Yes, basically is about to share the theme. I will check this then.
Thank you, this entry could be closed.
