### ISSUE TITLE
Typescript definitions lack "plugins" property

### ISSUE THREAD

**Issue by snuup** [vuejs/vitepress#4392]
### Describe the bug

When configuring vitepress with a config.mts file, adding a plugins property works but typescript complains because 

export interface LocaleSpecificConfig<ThemeConfig = any>

does not have a plugins property defined

### Reproduction

as above

### Expected behavior

no typescript error

### System Info

```Text
Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.3.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.2 - ~\AppData\Roaming\npm\pnpm.CMD

  npmPackages:
    vitepress: ^1.5.0 => 1.5.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide the code you've written. VitePress doesn't have plugins.
