### ISSUE TITLE
导航中插入的<T>，两个尖括号没有对齐

### ISSUE THREAD

**Issue by AlanQtten** [vuejs/vitepress#4399]
### Describe the bug

![image](https://github.com/user-attachments/assets/80d0d809-50d2-448f-bc83-5b428e690b33)

### Reproduction

直接打开控制台修改官方sidebar里的文字，插入<T>即可复现

### Expected behavior

文字对齐

### System Info

```Text
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 141.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.18.0 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 17.4.1
  npmPackages:
    vitepress: ^1.5.0 => 1.5.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That's a glyph. Add space between `s` and `<`.
