### ISSUE TITLE
Footnote integration with "On This Page"

### ISSUE THREAD

**Issue by AmitMY** [vuejs/vitepress#4402]
### Describe the bug

When using `markdown-it-footnote`, I manage to get footnotes on the page.
However, when the footnote is on a header 
![image](https://github.com/user-attachments/assets/9e7e9624-889f-4bad-80e1-abe9ad48ba57)
the "On this page" section shows it in an undesired way
![image](https://github.com/user-attachments/assets/b2c7d633-d90b-438d-8f0f-8d9b0a6c6487)

### Reproduction

https://stackblitz.com/edit/vitepress-footnote-bug

<img width="995" alt="image" src="https://github.com/user-attachments/assets/bd1b6ba2-29cb-469d-8819-c4d7ee410a2a">

### Expected behavior

The footnote should be removed from the "On This Page" area

### System Info

```Text
reproduced on stackblitz.
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You'll need to adjust mdit config to this:

```ts
md.use(footnote)
const orig = md.renderer.rules.footnote_ref!
md.renderer.rules.footnote_ref = (...args) => {
  return orig(...args).replace(
    '<sup class="',
    '<sup class="ignore-header '
  )
}
```

**Comment by brc-dd** [comment]
Since this is an official mdit plugin, I updated the outline code to ignore footnote-ref by default. From next version you won't need that workaround.

You can use the preview version for now too - `npm add -D https://pkg.pr.new/vitepress@1832617`
