### ISSUE TITLE
single page and run in local

### ISSUE THREAD

**Issue by frankie-zeng** [vuejs/vitepress#4407]
### Is your feature request related to a problem? Please describe.

build a single page or mutli pages, all run run locally.

### Describe the solution you'd like

work with vite single page plugin?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's out of scope for now. Use vite + vue + unplugin-vue-markdown or some other framework that supports relative base.
