### ISSUE TITLE
Vercel has a Chinese path problem

### ISSUE THREAD

**Issue by BlazeSnow** [vuejs/vitepress#4408]
### Describe the bug

> 该问题似乎只出现于Google Chrome，使用Microsoft Edge时无法复现问题。Google Chrome的版本号为131.0.6778.109。
>
> The issue appears to be specific to Google Chrome and does not appear to be repeated when using Microsoft Edge. The version number of Google Chrome is 131.0.6778.109.

使用`vercel.com`，当网页的路径中存在中文时，如：`/cnpath/中文.html`，网页会先报错`404`，刷新后报错`500`，显示`MIDDLEWARE_INVOCATION_FAILED`。

Using `vercel.com`， when a Chinese character exists in the path of a webpage, such as `/cnpath/中文.html`， the webpage will first return an error of `404`， then refresh and return an error of `500` with the message `MIDDLEWARE_INVOCATION_FAILED`.

![1](https://github.com/user-attachments/assets/f48083bd-31d1-4ce9-b7b1-0609e8689fd9)
![2](https://github.com/user-attachments/assets/29006163-895c-461c-abdc-9739a4f06eb0)

### Reproduction

https://blazesnow-vitepressissue.vercel.app/

https://github.com/BlazeSnow/VitepressIssue

### Expected behavior

使用vercel.com，当网页的路径中存在中文时，不应报错404或500，而是像GitHub pages或Cloudflare pages一样正常显示。

With vercel.com, when there is Chinese in the path of a web page, it should not report an error of 404 or 500, but display normally like GitHub pages or Cloudflare pages.

### System Info

```Text
System:
    OS: Windows 11 10.0.26100
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 4.21 GB / 15.69 GB
  Binaries:
    Node: 23.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    vitepress: ^1.5.0 => 1.5.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not sure seems to open fine for me on chrome too:

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/d9e8e81a-5b78-4693-9f88-5e37b5793274">

Check if some of your extension is interfering.

**Comment by BlazeSnow** [comment]
我禁用了所有的chrome插件，但是页面仍为404和500。

I disabled all chrome plugins, but the pages are still 404 and 500.

![屏幕截图 2024-12-06 233151](https://github.com/user-attachments/assets/f9988340-5ddf-406e-9f5b-f5d9434b6129)

**Comment by brc-dd** [comment]
Hmm, can you try clearing your browser and dns cache? (Ctrl + Shift + R on page; for dns cache go to `chrome://net-internals/#dns` and click clear host cache)

**Comment by BlazeSnow** [comment]
我重置了DNS和VPN，但是问题仍然出现，每次刷新时页面的错误ID也在变化。

I reset the DNS and VPN, but the problem still occurs and the error ID of the page changes with each refresh.

**Comment by brc-dd** [comment]
Check if you see any logs on Vercel -- Log in to vercel. Select your project. You'll see some navbar like this:

<img width="787" alt="image" src="https://github.com/user-attachments/assets/b12dda2c-f6ab-4f25-8cd5-a1cdcf345b65">

When you have that page open, try re-visiting the page on Chrome.

**Comment by BlazeSnow** [comment]
好像Vercel最近进行了更新，我看不到任何日志，包括代码为200的页面。

It seems that Vercel has been updated recently and I can't see any logs, including the page with code 200.

**Comment by BlazeSnow** [comment]
我发现问题出现在进入网站的方式。作为网站的所有者，我是从vercel的部署界面点击链接进入网页，此时网页的路径有中文时，会出现404和500的报错；但是我删去Cookies，直接输入链接进入网页时，就不会出现以上问题。经过多次删去Cookies后不同进入网页的方式的测试，问题更可能出现在vercel的toolbar而不是vitepress。

I found that the problem was the way to access the site. As the owner of the website, I clicked the link to enter the page from the deployment interface of vercel. At this time, when the path of the page has Chinese, there will be 404 and 500 errors; However, when I delete the Cookies and enter the link directly to the web page, the above problem does not occur. After several tests of different ways of accessing web pages after deleting Cookies, the problem is more likely to occur in the toolbar of vercel than in vitepress.

**Comment by brc-dd** [comment]
Was this fixed? Maybe try contacting vercel support. VitePress itself doesn't create or register any middleware, it just generates pure HTML/CSS/JS.

**Comment by BlazeSnow** [comment]
没解决，但是问题不是出现在vitepress，而是vercel toolbar。当我禁用了vercel toolbar后，页面都能正常显示了。

Not solved, but the problem is not with vitepress, but with vercel toolbar. After I disabled the vercel toolbar, the pages were displayed normally.

![屏幕截图 2024-12-14 152709](https://github.com/user-attachments/assets/5bea8339-ac6f-49a1-8c81-a6bc2c5e7f85)
