### ISSUE TITLE
Config 'base' option works on dev, but doesn't quite work on build/production. in Default Theme

### ISSUE THREAD

**Issue by JohnBrayden** [vuejs/vitepress#4414]
## Describe the bug
When I enable the `base` property in the config file, it works fine in the development environment (`dev`), but it doesn't work at all in production, and I encounter several issues that I couldn't identify or resolve. Please note that I am not using any custom or complex themes; I am only working with the default theme and `.md` files.

### Version?:

I am using `vitepress version ^1.5.0`.

### Errors:

![Error](https://github.com/user-attachments/assets/bacc6c31-b20a-4950-8517-977d1774a940)

![Error2](https://github.com/user-attachments/assets/99f2b82f-87e7-47e1-b4af-4c803e81bc51)

### Reproduction

1 - Create the application using the command: **npx vitepress init**
2 - Configure the `base` property in the config file, set it to: (`/docs/`)
3 - Test the application in the development environment.
4 - Build the site for production.
5 - Uploaded it to GitHub.
6 - Deployed it on Netlify.

### Expected behavior

I expect my site to display correctly and function normally under the `mysite.org/docs/` path without any issues. This includes proper loading of all assets (CSS, JS, and images) and correct handling of internal links in both development and production environments.

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 7.22 GB / 15.85 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.47.1.
    Curl: 8.9.1 - C:\Windows\system32\curl.EXE
  IDEs:
    VSCode: 1.95.3 - C:\Users\PCD\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 16.11.35425.106 (Visual Studio Community 2019), 17.12.35527.113 (Visual Studio Community 2022)
  Browsers:
    Edge: Chromium (131.0.2903.70)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
How are you deploying it to github/netlify? If you've configured base then for github pages it should be same as the repo name. If you're deploying for netlify or your github repo is of form <user/org>.github.io, then you need to configure outDir to something like `.vitepress/dist/docs`.

**Comment by JohnBrayden** [comment]
Thank you! It worked successfully. I kept searching extensively through the VitePress documentation, but I couldn’t find a clear solution or even anything related to configuring the base and resolving its issues.
