### ISSUE TITLE
docs: Google Analytics example valid on dev, builds invalid javascript. 

### ISSUE THREAD

**Issue by dCastanho** [vuejs/vitepress#4420]
### Describe the bug

When attempting to add Google Analytics to my vitepress site, I noticed that the javascript code generated on build, using the [example from the documentation](https://vitepress.dev/reference/site-config#example-using-google-analytics) generates invalid javascript. Instead of:

```
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'TAG_ID');
```

The resulting `index.html` has:

```
window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","TAG_ID");
```

Notice the missing `()` in Date constructor and the `,` instead of `;`. However, when executed in dev, the generated code (visible in the browser inspector) is correct. 

Am I doing something wrong, or is there a bug here? 

### Reproduction

Minimal reproduction is:

- `npx vitepress init` 
- Use all the defaults.
- Add the snippet from documentation to the site config
- run `npm run docs:build`

### Expected behavior

The result should be
```
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'TAG_ID');
```

### System Info

```Text
System:
    OS: macOS 14.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.6.0 - ~/.nvm/versions/node/v22.6.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v22.6.0/bin/npm
  Browsers:
    Chrome: 131.0.6778.109
  npmPackages:
    vitepress: ^1.5.0 => 1.5.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Both JS snippets behave the same. In build it's minified. `new Date` and `new Date()` both are same. comma instead of `;` also doesn't matter in this case.

**Comment by dCastanho** [comment]
Hm, my misunderstanding then, when I deploy the built version it does not seem work - I assumed it was due to this, but there must be another reason. Apologies for the time wasted!

**Comment by brc-dd** [comment]
Check in your browser's devtools' network tab if gtag script is being loaded with correct id. You can also use google tag assistant. https://support.google.com/tagassistant/answer/10039345?hl=en

**Comment by dCastanho** [comment]
Ah, spot on! Seems like my ad blocker was preventing the analytics. Thank you very much, I will keep this in mind for the future!
