### ISSUE TITLE
content in hosited tags not processed by vite plugin

### ISSUE THREAD

**Issue by kagawagao** [vuejs/vitepress#443]
### Describe the bug

content in `hosited tags` not processed by vite plugin

### Reproduction

- markdown file

```md
<script setup>
import { Button } from 'ant-design-vue'
</script>

# Demo

<Button>Demo</Button>
```

- config

```ts
import { UserConfig } from 'vitepress/dist/node';
import Components from 'unplugin-vue-components/vite';
import { AntDesignVueResolver } from 'unplugin-vue-components/resolvers';

const config: UserConfig = {
  title: 'Demo',
  description: 'Demo',
  vite: {
    plugins: [
      Components({
        resolvers: [AntDesignVueResolver()],
      }),
    ],
  },
};

export default config;
```

### Expected behavior

content in `hoisted tags` also processed by vite plugin

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 37.09 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.11.01.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 95.0.4638.69
    Chrome Canary: 98.0.4707.0
    Edge: 95.0.1020.53
    Firefox: 91.0.2
    Safari: 15.1
  npmPackages:
    vitepress: ^0.20.1 => 0.20.1 
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
What is hoisted tag?

**Comment by kagawagao** [comment]
https://vitepress.vuejs.org/guide/using-vue.html#script-style-hoisting

**Comment by kiaking** [comment]
Hah. Does this work if you don't use vite plugin and directly import the component? And what is the difference? Styles not being applied?

**Comment by kagawagao** [comment]
> Hah. Does this work if you don't use vite plugin and directly import the component? And what is the difference? Styles not being applied?

yep, styles not being applied

**Comment by kiaking** [comment]
Does this work if you don't use vite plugin and directly import the component?

**Comment by kagawagao** [comment]
but this issue appeared a long time ago, not sure if it can be reproduced

**Comment by kiaking** [comment]
Oh, OK. If it doesn't reproduce, then that's great news 👍 Would be helpful if you can try out, but if not, I'll close this issue in 1 weak if there's no response.

**Comment by kagawagao** [comment]
> Oh, OK. If it doesn't reproduce, then that's great news 👍 Would be helpful if you can try out, but if not, I'll close this issue in 1 week if there's no response.

I'll try to reproduce and give feedback
