### ISSUE TITLE
The style does not take effect when using the markdown extension plugin with tailwindcss

### ISSUE THREAD

**Issue by ajiho** [vuejs/vitepress#4433]
### Describe the bug

I have written a markdown it plugin, and the code is as follows
```js
export default defineConfig({
  title: "My Awesome Project",
  markdown: {
    config: (md) => {
      md.block.ruler.before(
        "paragraph",
        "myplugin",
        function (state, startLine, endLine) {
          var ch,
            token,
            pos = state.bMarks[startLine] + state.tShift[startLine],
            max = state.eMarks[startLine];
          ch = state.src.charCodeAt(pos);

          if (ch !== 0x40 /*@*/ || pos >= max) {
            return false;
          }

          let text = state.src.substring(pos, max);
          let rg = /^@\s(.*)/;
          let match = text.match(rg);

          if (match && match.length) {
            let result = match[1];

            // Create the opening token for the h1 tag
            token = state.push("heading_open", "h1", 1);
            token.markup = "@";
            token.map = [startLine, state.line];
            // Add class to the h1 tag
            token.attrs = [["class", "bg-red-300"]];

            // Create the inline content inside the h1 tag
            token = state.push("inline", "", 0);
            token.content = result;
            token.map = [startLine, state.line];
            token.children = [];

            // Create the closing token for the h1 tag
            token = state.push("heading_close", "h1", -1);
            token.markup = "@";

            state.line = startLine + 1;
            return true;
          }
        }
      );
    },
  },
  });
```

It's just a simple syntax parse(This is not the main point, it is just a simple plugin written to illustrate the issue)

Enter the following content in the markdown file
```
@ header  ->   <h1 class="bg-red-300">header</h1>  
```

I have followed the [tailwindcss guide](https://tailwindcss.com/docs/guides/vite#vue)Installation

Then start the development server
```bash
npm run docs:dev
```

But its'. bg-red-300 'style did not take effect
![image](https://github.com/user-attachments/assets/f99eed64-49b2-4565-a6fb-d8fdaae033a5)

But when I continued to input an HTML fragment carrying 'bg-red-300' in markdown, it took effect
![image](https://github.com/user-attachments/assets/ef331c48-4718-4662-bd77-d2e0848af485)

![image](https://github.com/user-attachments/assets/b2506252-dfc4-4f20-8d20-1955fe6cbc38)

When I deleted the HTML fragment carrying 'bg-red-300' and restarted the development server, it had no effect again

refer to:
https://github.com/ajiho/vitepress-tailwindcss-markdown-it

This problem has been bothering me for a long time, can you help me?

### Reproduction

[refer to](https://github.com/ajiho/vitepress-tailwindcss-markdown-it)

### Expected behavior

After the parse plugin of markdown it renders, the tailwindcss style should take effect immediately

### System Info

```Text
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 1.36 GB / 7.91 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.86)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    vitepress: ^1.5.0 => 1.5.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
tailwind works by scanning the source. In your contents property in tw config you probably will have md/vue files. But that class is not in those files, so the corresponding CSS is not generated. You'll need to safelist it - https://tailwindcss.com/docs/content-configuration#safelisting-classes

This issue is solved by tailwind v4 which uses a vite plugin to scan intermediate source.
