### ISSUE TITLE
关于在vitepress1.5version中，使用markdown文本中出现 `style={{key：value}}` 有双重括号的时候就会报错404

### ISSUE THREAD

**Issue by geniusmanyxh** [vuejs/vitepress#4438]
### Describe the bug

双重花括号在markdown文本中编译失败404，无法正确显示文本内容。

## 4、jsx的语法规则

- 定义虚拟DOM时，不要写括号
- 标签中混入JS表达式时要用`{}`
- 样式的类名指定不要用`class`，要用`className`
- 内联样式，要用`style={{key：value}}`的形式去写
- 只有一个根标签
- 标签必须闭合
- 标签首字母小写，则该标签会转为`html`中同名元素，若`html`中无该标签对应的同名元素则报错
- 若标签首字母大写，`react`就去渲染对应的组件，若组件没有定义，则报错

### Expected behavior

我觉得这个在编译的时候做一下处理，要兼容md通用格式

### System Info

```Text
index.md:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### Additional context

<img width="1280" alt="Snipaste_2024-12-21_01-08-57" src="https://github.com/user-attachments/assets/439fc447-d419-4705-ad57-66aa6b94731a" />
<img width="1280" alt="Snipaste_2024-12-21_01-07-28" src="https://github.com/user-attachments/assets/ea971ff8-985c-40af-a967-4e79426185f8" />

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/discussions/480
