### ISSUE TITLE
Variable "--vp-c-text-1" is incorrect in the bundle ouput

### ISSUE THREAD

**Issue by khang-nd** [vuejs/vitepress#4439]
### Describe the bug

https://github.com/vuejs/vitepress/blob/3eb4374af286362d7f4257b288fd2d5b9173dcba/src/client/theme-default/styles/vars.css#L177

Incorrectly output as:
```
  --vp-c-text-1: rgba(60, 60, 67);
```

### Reproduction

This can be found easily from the npm repo: https://www.npmjs.com/package/vitepress?activeTab=code

Then go to `dist/client/theme-default/styles/vars.css`, line 177.

### Expected behavior

Should be
```
  --vp-c-text-1: rgba(60, 60, 67, 1);
```

### System Info

```Text
Not relevant
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It was changed in recent version. On the latest version it's still rgb one.
