### ISSUE TITLE
docs:dev works but docs:build reports an error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module...

### ISSUE THREAD

**Issue by smallseapig** [vuejs/vitepress#4440]
### Describe the bug

I use [vitepress@latest](https://github.com/vuejs/vitepress) to document and the [tiny-vue@3.19.0](https://github.com/opentiny/tiny-vue) component library, which works fine when running, but when I used the `docs:build`, I got an error with an error message of `Error [ERR_MODULE_NOT_FOUND]: Cannot find module...`

### Reproduction

https://stackblitz.com/edit/vite-e44qnyyo?file=docs%2F.vitepress%2Ftheme%2Findex.js

### Expected behavior

`docs:build` executed successfully

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 2.60 GB / 15.73 GB
  Binaries:
    Node: 18.20.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.3.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Make it `noExternal: [/@opentiny\//],`

**Comment by smallseapig** [comment]
I tried but it didn't work. Could you please execute the build command in the sandbox I sent

**Comment by brc-dd** [comment]
Yeah I had already tested. Seems to be working fine:

<img width="773" alt="image" src="https://github.com/user-attachments/assets/c383d9e6-30ba-44c8-a6bd-ab8893167839" />

**Comment by smallseapig** [comment]
Just tried again a few times, probably my local cache, I re-created the new project, finally succeeded, thank you so much!!!!
