### ISSUE TITLE
Using lastUpdated in frontmatter is invalid

### ISSUE THREAD

**Issue by ajiho** [vuejs/vitepress#4448]
### Describe the bug

When using lastUpdated as Date in frontmatter, even in non git environments, the input time should be displayed directly

### Reproduction

NOT REQUIRED

### Expected behavior

foo.md
```
---
lastUpdated: '2024-12-25T10:30:00Z'
---

# foo
xxxx
```
Even if I don't use the Git environment, it should still display the time

I have checked and found that the relevant [issues ](https://github.com/vuejs/vitepress/issues/4119)have been closed, but when I tested, the time still did not display

I have also created a Vitepress test and found that if using Git, configuring it in FrontMatter can be effective in forcing override

What I mainly want to express is that if frontmatter is forced to set lastUpdated, whether it uses the Git environment or not, it should display this given time

### System Info

```Text
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 1.18 GB / 7.91 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE      
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.86)
    Internet Explorer: 11.0.19041.3636
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
remove the quotes
