### ISSUE TITLE
route.path doesn't work correctly with base option

### ISSUE THREAD

**Issue by aantipov** [vuejs/vitepress#446]
### Describe the bug

I noticed that `route.path` works differently in SSR and Runtime.
In SSR `route.path` doesn't include the `base` value.
In Runtime `route.path` includes the `base` value.
It causes `Hydration completed but contains mismatches.` error

### Reproduction

1. Define Vitepress config with `base` option
```js
module.exports = {
  base: '/blog/',
  lang: 'en-US',
  title: 'The Blog',
};
```
2. Create two vue components: `<Blog />` to be served at `/blog/` and `<Article />` to be served at inner routes
3. Use custom layout component in `.vitepress/theme/index.js`
```js
export default {
  ...DefaultTheme,
  Layout,
};
```
3. Define routing logic in `Layout.vue` component
```js
<template>
  <div>
    <Blog v-if="isIndex" />
    <Article v-else />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from 'vitepress';
import Blog from './Blog.vue';
import Article from './Article.vue';

const route = useRoute();
const isIndex = computed(() => {
  return route.path.replace(/index.html$/, '') === '/';
});
</script>

```

### Expected behavior

I expect that
1. Blog component  is served at `/blog/`
2. Article component is served at `/blog/**/*` routes
3. No `Hydration completed but contains mismatches.` error in the console
4. No blinking screen that happens because the page is rendered as Article in SSR and then transformed into Blog during hydration

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 176.77 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - ~/.nvm/versions/node/v16.1.0/bin/npm
  Browsers:
    Brave Browser: 92.1.28.106
    Chrome: 96.0.4664.45
    Firefox: 90.0.2
    Safari: 15.0
  npmPackages:
    vitepress: ^0.20.1 => 0.20.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Done!
