### ISSUE TITLE
`navLink` module false positives

### ISSUE THREAD

**Issue by userquin** [vuejs/vitepress#453]
### Describe the bug

When we have 2 links on navbar containing the former the latter there is a false positive match.

https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/composables/navLink.ts#L19

### Reproduction

Just use for example 2 links like this:

`/somedirectory/svelte` and `/somedirectory/sveltekit`.

When navigating to `/somedirectory/svelte` link, then once in the page, the navbar will show both as `active` (also the parent, in the example `/somedirectory/`).

Clone this repo and checkout `docs/sveltekit` branch: https://github.com/antfu/vite-plugin-pwa (if not found, then the PR 176 will be merged and the branch deleted, just use the `main` branch).

You will need `pnpm` installed globally, once cloned and checkout the `docs/sveltekit` branch, go to `docs/.vitepress/theme/composables/navLink.ts` and comment this 2 if statements on line 25 (the code is the same here):

```ts
      if (routePath === '/frameworks/sveltekit' && itemPath === '/frameworks/svelte' && active)
        active = false
      // fix /examples/sveltekit and /examples/svelte
      if (routePath === '/examples/sveltekit' && itemPath === '/examples/svelte' && active)
        active = false
```

Run from root folder `pnpm install && pnpm run build` and then `pnpm run docs` to run the docs site, go to Frameworks nav bar and select Svelte entry, you will see that `Getting Started`, `Svelte` and `SvelteKit` links will be active.

### Expected behavior

Should be only one/two matches.

### System Info

```shell
I'm testing with `node16`.


npx envinfo --system --npmPackages vitepress --binaries --browsers

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 47.82 GB / 63.95 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.34)
    Internet Explorer: 11.0.19041.1202
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Duplicate #259
