### ISSUE TITLE
Navigation stops working after some time

### ISSUE THREAD

**Issue by aantipov** [vuejs/vitepress#454]
### Describe the bug

I noticed it a couple times at my VitePress blog https://moiva.io/blog/ and also at https://vitejs.dev/guide/

If a page stays open for some time, then, at a certain moment, navigation stops working.

Here are a couple screenshots:
![image](https://user-images.githubusercontent.com/427621/144199270-1f7f6a9b-df9a-4292-bdac-6979ab4773a7.png)

![image](https://user-images.githubusercontent.com/427621/144199311-f4a8e6a6-6e3f-418f-a77d-94c480b6fbf9.png)

![image](https://user-images.githubusercontent.com/427621/144199517-b1caea79-eacb-4687-b637-16514030330a.png)

Page reload fixes the problem.

My guess is that the website has been updated in the meantime, all the assets have been replaced by the new ones and the server doesn't serve the old ones anymore => navigation stops working.

### Reproduction

described above

### Expected behavior

If my guess is correct and the problem is caused by the update of the site in the meantime, then my suggestion would be to fallback to full-page load if a script can't be resolved

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 438.10 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Brave Browser: 95.1.31.88
    Chrome: 96.0.4664.55
    Firefox: 90.0.2
    Safari: 15.1
  npmPackages:
    vitepress: ^0.20.1 => 0.20.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
This is because of a new deployment. There is an open issue about having stable assets files
