### ISSUE TITLE
repo and docsRepo config parameters and navbar repository link

### ISSUE THREAD

**Issue by mariomka** [vuejs/vitepress#457]
### Describe the bug

There is an issue around `repo` and `docsRepo` config parameters.
When both of them are defined, `repo` isn't used in any part of the application. I think it should be used, at least, for the navbar repository link instead of `repoDocs` but maintain using `repoDocs` for the editing links.

I can submit a PR to fix it.

### Reproduction

There is an issue around `repo` and `docsRepo` config parameters.
When both of them are defined, `repo` isn't used in any part of the application. I think it should be used, at least, for the navbar repository link instead of `repoDocs` but maintain using `repoDocs` for the editing links.

I can submit a PR to fix it.

### Expected behavior

`repo` parameter should be used for the repository link in the navbar.

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.27 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 89.0.2
    Safari: 15.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kleisauke** [comment]
I also noticed the same wrong behavior. It looks like a bug here:
https://github.com/vuejs/vitepress/blob/51978a3ff5a4db189062ee7da0b272cf8ff37433/src/client/theme-default/composables/repo.ts#L15

I think that should be:
```diff
--- a/src/client/theme-default/composables/repo.ts
+++ b/src/client/theme-default/composables/repo.ts
@@ -12,7 +12,7 @@ export function useRepo() {
 
   return computed(() => {
     const theme = site.value.themeConfig as DefaultTheme.Config
-    const name = theme.docsRepo || theme.repo
+    const name = theme.repo || theme.docsRepo
 
     if (!name) {
       return null
```
(i.e., prefer `repo` above `docsRepo` for the navbar repository link)

**Comment by mariomka** [comment]
A workaround is hiding navbar repository link with css, see: https://vitepress.vuejs.org/guide/theming.html#customizing-css

```csss
.theme > .nav-bar > .nav > .nav-links > .item:last-child {
    display: none;
}
```

**Comment by kiaking** [comment]
This settings has been modified in VitePress Next.
