### ISSUE TITLE
Copy to clipboard button in code snippets

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/vitepress#473]
### Is your feature request related to a problem? Please describe.

It will be great to add copy to clipboard button in code snippets for longer code snippets where dragging requires window scroll

### Describe the solution you'd like

Add copy to clipboard button in default theme

### Describe alternatives you've considered

None

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Any proposal for the UI? Because currently the top-right of a code block shows language.

**Comment by WebMechanic** [comment]
This is available as a [plugin for Prism](https://prismjs.com/download.html#themes=prism-funky&languages=markup+css+clike+javascript) (need to scroll down the page), but it's unclear to me how they could be added to the configuration inside VitePress. 

I'd also love to have this feature and potentially use other Prism plugins.

**Comment by rogier-stegeman** [comment]
Would love this feature!

> Any proposal for the UI? Because currently the top-right of a code block shows language.

How about moving the language to the bottom right? See any page on the [Vuetify docs](https://vuetifyjs.com/en/features/accessibility/) for an example.
Copy button could also fade in on hover like it does on GitHub.

**Comment by WebMechanic** [comment]
> How about moving the language to the bottom right? 

I put this in my custom theme stylesheet:
```css
div[class*="language-"]::before {
  top: initial; /* or unset */
  bottom: .6em;
}
```

**Comment by kiaking** [comment]
This is cool idea and we should do it! Although, I think this can be done after 1.0.0 release as a feature addition, so probably I'll not be working on with this anytime soon.

If someone wants to jump in, that's super welcome!

**Comment by WebMechanic** [comment]
I don't believe the single "copy" feature should be a built into Vitepress.
Rather allow for a simple integration of **other (official) Prism plugins** so ppl can add whatever they want and place it wherever they want in their code blocks. Maybe even make use of Prism's themes.
https://prismjs.com/plugins/

**Comment by brc-dd** [comment]
@WebMechanic We won't be using prism anymore from the next release. #627

**Comment by WebMechanic** [comment]
@brc-dd ok. Thanks for the heads up.

**Comment by kiaking** [comment]
Done! Thanks to @brc-dd for the amazing work 🎉
