### ISSUE TITLE
Text bugging out

### ISSUE THREAD

**Issue by jeweetzelfWasTaken** [vuejs/vitepress#475]
### Describe the bug

So I installed VitePress, but when I just wanted it to say on the home page 'Hello World', it showed this: 
![image](https://user-images.githubusercontent.com/67839219/146807060-ea5a874c-10b5-4353-8930-e4b6dad179d0.png)
And I just entered this:
![image](https://user-images.githubusercontent.com/67839219/146807124-1fed07f1-6bee-4144-a273-8152cd3750ee.png)

Don't know why, I think this is a bug

### Reproduction

I installed it and made an index.md file, with 'Hello World' in it.

### Expected behavior

Just to show 'Hello World'

### System Info

```shell
System:
    OS: Windows 10 10.0.19042     
    CPU: (4) x64 Intel(R) Core(TM) i5-3437U CPU @ 1.90GHz
    Memory: 655.02 MB / 3.87 GB   
  Binaries:
    Node: 16.6.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.16.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.1266), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    vitepress: ^0.20.9 => 0.20.9
```

### Validations

- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You likely have something wrong with your file or browser encoding. Use UTF encoding

**Comment by Gokulr1612** [comment]
Hi,

I have the same issue as well. Browser encoding is right though!
