### ISSUE TITLE
Support setting sidebar depth in themeConfig for default theme

### ISSUE THREAD

**Issue by FrodeI** [vuejs/vitepress#482]
### Is your feature request related to a problem? Please describe.

Currently sidebar depth can be specified per page in the frontmatter section. It would be convenient to set a global default sidebar depth in themeConfig. In situations where pages are auto-generated, adding the frontmatter block may not be so easy. 

### Describe the solution you'd like

Add  support for `sidebarDepth` in `themeConfig`.

Sidebar depth specified in the frontmatter block should take priority over what's defined in `themeConfig`. If `sidebarDepth` is not defined, either in the page or in `themeConfig`, `Infinity` should be used to avoid breaking changes.

### Describe alternatives you've considered

The default theme in vuepress supports setting sidebarDepth in sidebar groups as well, which could be nice, but I guess the most important is to have a global default available.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Closing due to the change of Sidebar behavior in theme next. Now the outline is displayed outside of sidebar.

**Comment by puyt** [comment]
@kiaking I couldn't find it anywhere but can we configure the depth of the outline sidebar?
