### ISSUE TITLE
__VP_HASH_MAP__ is not defined

### ISSUE THREAD

**Issue by radiorz** [vuejs/vitepress#485]
### Describe the bug

I run script that is 'vitepress dev' and the broswer told me that __VP_HASH_MAP__ is not defined
and I couldnt use it in dev mode.
But when I build and serve it ,it seems correct.

### Reproduction

# enviroments
- vitepress 0.20.10 
- node 14.17.4

I run script that is 'vitepress dev' and the broswer told me that __VP_HASH_MAP__ is not defined
and I couldnt use it in dev mode.
But when I build and serve it ,it seems correct.

### Expected behavior

use dev correctly

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 9.56 GB / 23.86 GB
  Binaries:
    Node: 16.13.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.17 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 8.1.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    vitepress: ^0.20.10 => 0.20.10
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yyx990803** [comment]
`__VP_HASH_MAP__` is never accessed during dev, so there's nothing I can do without an actual reproduction.
