### ISSUE TITLE
Missing trailing slash in nested directories gives 404

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#490]
### Describe the bug

Suppose I have a folder structure like this:

```txt
.
├─ index.md
├─ foo
│  ├─ index.md
│  ├─ one.md
│  └─ two.md
```

Now, if I open `host/foo/` it renders `./foo/index.md`, but if I open `host/foo` then it gives 404 error. 

### Reproduction

Description is sufficient.

### Expected behavior

It should render `./foo/index.md` if there is no `./foo.md` present.

### System Info

Using `vitepress@0.21.4` with `yarn@3.1.1` and `node@16.13.1`.

<sub>PS: That `npx envinfo --system --npmPackages vitepress --binaries --browsers` command given in the issue form doesn't work on newer Windows and Insider versions as they don't have WMIC.</sub>

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yyx990803** [comment]
This is expected. Missing trailing slash requires special handling in deployment server (e.g. Netlify does this by default), not from VitePress.
