### ISSUE TITLE
Feature: social images (twitter/og)

### ISSUE THREAD

**Issue by jbandi** [vuejs/vitepress#504]
### Is your feature request related to a problem? Please describe.

It would be nice if sites based on VitePress could support social link preview images with the corresponding meta tags (Twitter and OpenGraph).

I personally try to build my Blog based on VitePress, and for a Blog I think social link preview images are important.

Currently VitePress does not support tilte and descripption for social link previews (Twitter and OpenGraph) but not Images.

This can for instance be observed with the following site:
https://www.opengraph.xyz/url/https%3A%2F%2Fblog.vuejs.org%2Fposts%2Fvue-3-as-the-new-default.html/

### Describe the solution you'd like

I suggest that a default social image can be specified in `.vitepress/config.ts`. This image is then referenced in meta tags for Twitter and OpenGraph like this:
```
 <meta name="twitter:image" content="/images/example.png">
 <meta property="og:image" content="/images/example.png">
```

The above image can be overridden in each Markdown page by specifying a specific social image in frontmatter like this:
```
---
image: ./images/vue.png
---
```

I am using a version of VitePress that contains PR #498 here:
https://blog.jonasbandi.net/posts/20211231-a-new-beginning.html
(Source: https://github.com/jbandi/blog.jonasbandi.net)

As you can see here the social link image preview is working:
https://www.opengraph.xyz/url/https%3A%2F%2Fblog.jonasbandi.net%2Fposts%2F20211231-a-new-beginning.html/

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I have certain concerns regarding this feature request and your PR #498.

First, one can still do this using frontmatter:

```yaml
head:
  - - meta
    - name: image
      property: 'og:image'
      content: https://foo.bar/baz.png
```

Can also be set for the whole site using `head` property in the site config.

Second, your demo site has meta tag like this:

```html
<meta property="og:image" content="/images/vue.png">
```

Relative links are not valid candidates for `content` of `og:image` ([ref](https://stackoverflow.com/a/9858694/11613622)), though many platforms resolve them properly.

Also, you've forgot to wrap `image` with `withBase`.

<details>
  <summary>Also, we don't need these four changes. (Click to expand.)</summary>
  <img src="https://user-images.githubusercontent.com/40380293/150637656-989161b0-7157-4007-902f-93810650a6da.png"/>
</details>

**Comment by kiaking** [comment]
Slightly different but https://github.com/vuejs/vitepress/issues/551 is trying to solve same problem in a more big picture.

Let's discuss further over there on how to tackle this issue.
