### ISSUE TITLE
logo lost when deployment

### ISSUE THREAD

**Issue by Sooia** [vuejs/vitepress#505]
### Describe the bug

Hello, I lost my logo when deploying the website.

The following is my index.md (main page), I set my logo with `heroImage: ./img/logo.jpg`:
```md
---
home: true
heroImage: ./img/logo.jpg
heroAlt: jun.run
heroText: 奔跑吧，俊！
tagline: —— 前端工程师的必备知识库
actionText: 开始
actionLink: /js/default
features:
  - title: 简约
    details: 言简意赅
  - title: 实用
    details: 高频考点
  - title: 高效
    details: 图文并茂
footer: MIT Licensed | Copyright © jun.run
---

```

When I run my website locally:
![image](https://user-images.githubusercontent.com/92929085/150532744-4c647e7e-d87a-4880-924c-e97fedd33448.png)

When I deploy it online using Vercel:
![image](https://user-images.githubusercontent.com/92929085/150532801-3b2d4a7f-b24c-4044-82e1-2aeea647088a.png)

I found that logo.png is not moved to `/docs/.vitepress/dist/` when delpoying.

### Reproduction

clone the repo to local, and run `yarn docs:build`, or deploy directly to Vercel using `yarn docs:build`.

### Expected behavior

![image](https://user-images.githubusercontent.com/92929085/150532801-3b2d4a7f-b24c-4044-82e1-2aeea647088a.png)

### System Info

```shell
"vitepress": "^0.21.6"
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by chrisrueger** [comment]
Same here.

**Comment by chrisrueger** [comment]
Never mind - we solved it by using the `public` folder (https://vitepress.vuejs.org/guide/assets.html#public-files)

**Comment by Sooia** [comment]
I also solved it by using the public folder. Thank you so much! @chrisrueger
