### ISSUE TITLE
Mount and Initialize mermaid via  markdown-it-textual-uml as markdown-it plugin

### ISSUE THREAD

**Issue by johanjvrens** [vuejs/vitepress#518]
### Describe the bug

Struggling to get [mermaid](https://mermaid-js.github.io/mermaid/#/) to work in vitepress through [markdown-it](https://github.com/markdown-it/markdown-it) plugin called [markdown-it-textual-uml](https://github.com/manastalukdar/markdown-it-textual-uml).

Getting the following error output in console:
```
Uncaught (in promise) ReferenceError: require is not defined
    at Proxy.mounted (index.md:6:9)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2667:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:356:32)
    at flushJobs (runtime-core.esm-bundler.js:401:9)
```

### Reproduction

Add markdown-it-textual-uml as an dependency - `npm install markdown-it-textual-uml --save`

And add the following snippet to .vitepress/config.js
```js
 markdown: {
    lineNumbers: true,
    config: (md) => {
      md.use(require("markdown-it-textual-uml"));
    },
  },
```

Add the following snippet to the index.md file with 
```js
<script>
let mermaid = null
export default {
    mounted() {
        if (mermaid == null) {
        mermaid = require('mermaid')
        }
        mermaid.initialize({
        startOnLoad: true,
        theme: 'forest'
        })
    }
}
</script>
```

Add the following snippet in index.md
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

### Expected behavior

See a mermaid graph load on index.md
![image](https://user-images.githubusercontent.com/8234230/152335287-975de891-9b6a-4ac7-84b8-8cd25476874b.png)

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 92.18 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/opt/node@16/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Safari: 15.3
  npmPackages:
    vitepress: ^0.21.6 => 0.21.6
```

### Additional context

[Additional steps for mermaid to run in markdown-it-textual-uml](https://github.com/manastalukdar/markdown-it-textual-uml#additional-steps-for-mermaid)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by mszkb** [comment]
I think the problem is that markdown.config is removed from the Site Config.
Reference: https://vitepress.vuejs.org/guide/differences-from-vuepress.html#site-config

I got mermaidjs to work, but with a unsatisfactory workaround: https://github.com/mszkb/vitepress-mermaid-js
And sadly without markdown-it.

**Comment by emersonbottero** [comment]
Another one poor vitepress plugin (don't judge me. Is my second one.. 😐)
https://github.com/emersonbottero/vitepress-plugin-mermaid

It works without using components inside markdowns.

**Comment by emersonbottero** [comment]
Another poor vitepress plugin (don't judge me, is my second one.. 😐)
https://github.com/emersonbottero/vitepress-plugin-mermaid

It works without using components inside markdowns.

**Comment by kiaking** [comment]
I guess those are valid solutions 👀
