### ISSUE TITLE
nested templates not being compiled

### ISSUE THREAD

**Issue by jose3dat** [vuejs/vitepress#519]
### Describe the bug

Greetings:

I'm building a `story` for a custom element, imported in the `config.js` file as global component. 

When I nest the component more than **twice**, I get the `template` content rendered as plain text. Is as if vue is not picking it up to render the actually template, but instead using it as plain text content.

So, picture a component who's `<template>` simply renders a `<div class="spacer"><slot /></div>`. If I would style said `div` with a `padding: 8px`, it is expected that by nesting it 3 levels deep, I would end up with 3 div html elements, each pushing its child `8px` in. 

The result is basically:

```html
<div class="spacer">
  <div class="spacer">
    <div class="spacer"><slot /></div>
  </div>
</div>
```

> **notice** how on line 5, I get back the actual, non-compiled template.

### Reproduction

- create a custom component, say a <Test> component with a `<slot />`
- import it to vitepress
- write a `md` story and nest the component three times:

```md
<test>
  <test></test>
  <test>
      <test>I get rendered as text, even if I contain an HTML element, such as a `<button>`</test>
  </test>
</test>
```

### Expected behavior

template compiler should keep going through deeper levels of components and render them as HTML elements.

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1
    Memory: 119.95 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Safari: 15.3
  npmPackages:
    vitepress: ^0.21.6 => 0.21.6
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by mhiguera** [comment]
I've foud out that it works if you enclose them in a `<div>`

**Comment by brc-dd** [comment]
![image](https://user-images.githubusercontent.com/40380293/176395520-7c63ac31-1d60-4a0b-91b6-2614f2038442.png)

This appears to be fixed in the latest release.
