### ISSUE TITLE
NavBar in Default Theme Layout can not be hidden

### ISSUE THREAD

**Issue by yiliang114** [vuejs/vitepress#522]
### Describe the bug

NavBar in Default Theme Layout can not be hidden

### Reproduction

According to the [code](https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/Layout.vue#L85) and [code](https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/Layout.vue#L44),  when `showNavbar`  is `false`,  NavBar will not to be render, so I can just set `title`, `themeConfig.logo`, `themeConfig.repo` and `themeConfig.nav` to `undefined`. But actually `site.value.title` will always have a default value `VitePress` from [code](https://github.com/vuejs/vitepress/blob/main/src/node/config.ts#L246), it causes  `showNavbar` has value forever, and  NavBar can not be hidden.

### Expected behavior

The  default NavBar component should be hidden.

### System Info

```shell
"vitepress": "0.21.6"
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yiliang114** [comment]
By the way, I find the page of [Code of Conduct](https://vuejs.org/coc) is not found.

**Comment by brc-dd** [comment]
This option is no longer present in the new theme. If you want to hide navbar, you can do that by putting this CSS:

```css
.VPNavBar {
    display: none;
}
```

**Comment by shadow-light** [comment]
It would be nice to be able to hide the navbar only on some pages, but doesn't seem like that's possible with custom CSS?

I'd like to hide it just for the homepage so it is nice and clean and only shows the homepage buttons.

A workaround is hiding the navbar whenever the sidebar is also hidden with:

`.VPNav.no-sidebar {display: none;}`

**Comment by brc-dd** [comment]
@shadow-light You can add styles directly in markdown too. There is no need to add that globally.

**Comment by shadow-light** [comment]
Also on wide screen `VPContent` has padding-top for the navbar despite it being hidden. A workaround for this issue is not straightforward. Can this issue be reopened?

**Comment by kiaking** [comment]
Yeah I think we can add this feature. But it's not a defect really. Could you open a new issue with feature request instead?
