### ISSUE TITLE
.md file cannot contain `process.env.node_env`

### ISSUE THREAD

**Issue by long-life233** [vuejs/vitepress#528]
### Describe the bug

In the .md file, just contain characters `process.env.node_env`, you will throw an error` syntaxerror: missing) After Argument List`, and the corresponding page will also report the error Page Not Found

### Reproduction

In the .md file, as long as Process.env.node_env this word, VitePress will not find the corresponding page.

### Expected behavior

You can use process.env.node_env this word

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 1.13 GB / 7.85 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.43)
    Internet Explorer: 11.0.19041.1202
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yyx990803** [comment]
Closing as duplicate
