### ISSUE TITLE
KaTeX/MathJax implementation

### ISSUE THREAD

**Issue by ngctnnnn** [vuejs/vitepress#529]
### Is your feature request related to a problem? Please describe.

I am frustrated and find it difficult in implement LaTeX onto the vitepress

### Describe the solution you'd like

There are many packages on applying LaTeX to the website, e.g. Mathjax

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Use any KaTeX markdown-it plugin. There shouldn't be much issue IG.

**Comment by magnetenstad** [comment]
Using @brc-dd 's suggestion, I get this error when trying to build.
```
vitepress v0.22.3
✓ building client + server bundles...
✖ rendering pages...
build error:
 TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
```

**Comment by leonbohmann** [comment]
Same error here

**Comment by leonbohmann** [comment]
Did not find that issue, is the fix using the compilerOptions a valid thing? Did not try that yet..

**Comment by brc-dd** [comment]
@leonbohmann It should be, but it is not working for me. Tried something like this. Got the same error.

```js
import { defineConfig } from 'vitepress'
import markdownItKatex from 'markdown-it-katex'

const customElements = [
  'math',
  'maction',
  'maligngroup',
  'malignmark',
  'menclose',
  'merror',
  'mfenced',
  'mfrac',
  'mi',
  'mlongdiv',
  'mmultiscripts',
  'mn',
  'mo',
  'mover',
  'mpadded',
  'mphantom',
  'mroot',
  'mrow',
  'ms',
  'mscarries',
  'mscarry',
  'mscarries',
  'msgroup',
  'mstack',
  'mlongdiv',
  'msline',
  'mstack',
  'mspace',
  'msqrt',
  'msrow',
  'mstack',
  'mstack',
  'mstyle',
  'msub',
  'msup',
  'msubsup',
  'mtable',
  'mtd',
  'mtext',
  'mtr',
  'munder',
  'munderover',
  'semantics',
  'math',
  'mi',
  'mn',
  'mo',
  'ms',
  'mspace',
  'mtext',
  'menclose',
  'merror',
  'mfenced',
  'mfrac',
  'mpadded',
  'mphantom',
  'mroot',
  'mrow',
  'msqrt',
  'mstyle',
  'mmultiscripts',
  'mover',
  'mprescripts',
  'msub',
  'msubsup',
  'msup',
  'munder',
  'munderover',
  'none',
  'maligngroup',
  'malignmark',
  'mtable',
  'mtd',
  'mtr',
  'mlongdiv',
  'mscarries',
  'mscarry',
  'msgroup',
  'msline',
  'msrow',
  'mstack',
  'maction',
  'semantics'
]

export default defineConfig({
  markdown: {
    config: (md) => {
      md.use(markdownItKatex)
    }
  },
  vue: {
    template: {
      compilerOptions: {
        isCustomElement: (tag) => customElements.includes(tag)
      }
    }
  }
})
``

**Comment by brc-dd** [comment]
Using MathJax is much easier actually. You just need to do this:

```js
import mathjax3 from 'markdown-it-mathjax3';

const customElements = ['mjx-container'];

export default {
  markdown: {
    config: (md) => {
      md.use(mathjax3);
    },
  },
  vue: {
    template: {
      compilerOptions: {
        isCustomElement: (tag) => customElements.includes(tag),
      },
    },
  },
};
```

Complete demo: https://github.com/brc-dd/vitepress-mathjax3

Output:

![image](https://user-images.githubusercontent.com/40380293/174973629-e04d1ab7-b195-40ab-ba42-adc7d23f4070.png)

**Comment by noClaps** [comment]
To add on to this, you can also use
```css
mjx-container>svg {
    display: block;
    margin: auto;
}
```
in your CSS to center the equations like KaTeX did.

**Comment by wlbksy** [comment]
Could you provide  a page on this LaTeX topic in the doc @noClaps , thanks !

**Comment by noClaps** [comment]
@wlbksy I'm sorry, I don't understand what you mean. The VitePress documentation doesn't have a page on LaTeX at the moment, and seeing as it's an external plugin, they probably won't add one.

**Comment by AetaBeta** [comment]
> Using MathJax is much easier actually. You just need to do this:
> 
> ```js
> import mathjax3 from 'markdown-it-mathjax3';
> 
> const customElements = ['mjx-container'];
> 
> export default {
>   markdown: {
>     config: (md) => {
>       md.use(mathjax3);
>     },
>   },
>   vue: {
>     template: {
>       compilerOptions: {
>         isCustomElement: (tag) => customElements.includes(tag),
>       },
>     },
>   },
> };
> ```
> 
> Complete demo: https://github.com/brc-dd/vitepress-mathjax3
> 
> Output:
> 
> ![image](https://user-images.githubusercontent.com/40380293/174973629-e04d1ab7-b195-40ab-ba42-adc7d23f4070.png)
why my latex fomula can not stay in one line with other text when it complied

**Comment by AetaBeta** [comment]
<img width="262" alt="image" src="https://user-images.githubusercontent.com/68657810/187636229-95d22f99-02d5-424e-8386-8296951f39db.png">

**Comment by brc-dd** [comment]
> why my latex fomula can not stay in one line with other text when it complied

@AetaBeta You probably haven't added styles. See the linked repo. You need to set `display: inline-block` on `mjx-container`.

**Comment by qyingkou** [comment]
@brc-dd 👍 
https://github.com/vuejs/vitepress/issues/529#issuecomment-1162767122
According to this issue, the configuration can indeed be successful, so that the mathematical formula can be displayed.

But the browser console shows a lot of warning messages，as follows：
<img width="947" alt="image" src="https://user-images.githubusercontent.com/46431594/210204260-a149e411-bc17-4558-9c2b-b4d9689e7c27.png">
How to deal with these warning messages, and how to make these unresolvable components be parsed correctly?

**Comment by brc-dd** [comment]
@qyingkou Refer my comment on that issue just above the one you linked 😅 https://github.com/vuejs/vitepress/issues/529#issuecomment-1151186631

**Comment by qyingkou** [comment]
> @qyingkou Refer my comment on that issue just above the one you linked 😅 [#529 (comment)](https://github.com/vuejs/vitepress/issues/529#issuecomment-1151186631)
> 
> It shouldn't be required for mathjax though. You need it only for katex.

@brc-dd ：Thank you for your reply, maybe I didn't make it clear.
I use "markdown-it-mathjax3" package, I completely copied the demo folder structure and configuration content you wrote. [brc-dd/vitepress-mathjax3](https://github.com/brc-dd/vitepress-mathjax3/blob/main/index.md)

However, a lot of warning messages appeared, many components could not be resolved.
Can you tell me how should I parse it correctly?

**Comment by brc-dd** [comment]
@qyingkou Ah, `markdown-it-mathjax3` has added AssistiveMML extension in its latest version. You'll need to have a config like this:

```ts
import mathjax3 from 'markdown-it-mathjax3';

const customElements = [
  'mjx-container',
  'mjx-assistive-mml',
  'math',
  'maction',
  'maligngroup',
  'malignmark',
  'menclose',
  'merror',
  'mfenced',
  'mfrac',
  'mi',
  'mlongdiv',
  'mmultiscripts',
  'mn',
  'mo',
  'mover',
  'mpadded',
  'mphantom',
  'mroot',
  'mrow',
  'ms',
  'mscarries',
  'mscarry',
  'mscarries',
  'msgroup',
  'mstack',
  'mlongdiv',
  'msline',
  'mstack',
  'mspace',
  'msqrt',
  'msrow',
  'mstack',
  'mstack',
  'mstyle',
  'msub',
  'msup',
  'msubsup',
  'mtable',
  'mtd',
  'mtext',
  'mtr',
  'munder',
  'munderover',
  'semantics',
  'math',
  'mi',
  'mn',
  'mo',
  'ms',
  'mspace',
  'mtext',
  'menclose',
  'merror',
  'mfenced',
  'mfrac',
  'mpadded',
  'mphantom',
  'mroot',
  'mrow',
  'msqrt',
  'mstyle',
  'mmultiscripts',
  'mover',
  'mprescripts',
  'msub',
  'msubsup',
  'msup',
  'munder',
  'munderover',
  'none',
  'maligngroup',
  'malignmark',
  'mtable',
  'mtd',
  'mtr',
  'mlongdiv',
  'mscarries',
  'mscarry',
  'msgroup',
  'msline',
  'msrow',
  'mstack',
  'maction',
  'semantics',
  'annotation',
  'annotation-xml',
];

export default {
  markdown: {
    config: (md) => {
      md.use(mathjax3);
    },
  },
  vue: {
    template: {
      compilerOptions: {
        isCustomElement: (tag) => customElements.includes(tag),
      },
    },
  },
};
```

**Comment by qyingkou** [comment]
Like the  configuration as Katex，thanks @brc-dd 

It seems that there will be some components that cannot be parsed after updating the package in the future,  just add the name of the component （that reported the error） to customElements.

**Comment by brc-dd** [comment]
Yeah. Should we add this to core? I guess using latex is a fairly popular demand and most of the other frameworks support it out of the box. /cc @kiaking

**Comment by qyingkou** [comment]
Latex is important for the expressiveness of document typesetting. 
More and more development documents need to explain algorithms, and algorithms need mathematical formulas.
Let us see which lucky package gets integrated into the core...

**Comment by brc-dd** [comment]
Yeah, I agree. But the main problem is the package size. Adding it will nearly double the VitePress' installation size! We probably can make it an optional peer dep.

**Comment by qyingkou** [comment]
I agree！
I wonder which library you will choose. 
From the comparison of KateX and MathJax, the former seems to render faster.  [KateX](https://katex.org)

**Comment by wlbksy** [comment]
[docusaurus](https://docusaurus.io/docs/markdown-features/math-equations) makes LaTeX default

**Comment by nkbai** [comment]
> 

it doesn't render multiline latex correctly, it  works only for single line latex.

for example:
```
$$
H=H1(\alpha) \\
k=ECVRF\_nonce\_generation(SK,H) \\
\Gamma =H^x \\
c=H2(H,\Gamma,B^k,H^k) \\
s=k+cx
$$
```
render as :
![image](https://user-images.githubusercontent.com/10471399/228840728-29610461-b7d2-40c4-a4f6-c78ddedda181.png)

```
证明其实就是想证明我这里的$\Gamma=H^x$,而不是通过什么其他方式得到的.
```
render as ： 
![image](https://user-images.githubusercontent.com/10471399/228840968-3eefff05-8bdc-4618-98f5-30cf3f20df0b.png)

**Comment by wlbksy** [comment]
> Yeah, I agree. But the main problem is the package size. Adding it will nearly double the VitePress' installation size! We probably can make it an optional peer dep.

Could the team make this happen, please~

**Comment by Fanisting** [comment]
For the repo above, I still got the results that inline math is unavailable. I modified the existing CSS solution and it works. Here is the new code in `mathjax3.css`:
`mjx-container {
  display: inline-block;
  margin: auto 2px -2px;
}

mjx-container > svg {
  margin: auto;
  display: inline-block;
}`

**Comment by laplacetw** [comment]
Hi there, how can I enable/disable Katex using frontmatter, or is it not needed ?

**Comment by brc-dd** [comment]
@theadanielskocher Refer https://vitepress.dev/guide/markdown#math-equations

**Comment by brc-dd** [comment]
Add it inside your defineConfig call.

```ts
export default defineConfig({
  title: '...',
  ....,
  markdown: {
    math: true
  }
})
```
