### ISSUE TITLE
"Import Code Snippets" not working

### ISSUE THREAD

**Issue by WebMechanic** [vuejs/vitepress#530]
### Discussed in https://github.com/vuejs/vitepress/discussions/527

<div type='discussions-op-text'>

<sup>Originally posted by **WebMechanic** February 11, 2022</sup>
Hello,

I have a fresh install of VitePress to document our new Style Guide and wanted to use the [Import Code Snippets](https://vitepress.vuejs.org/guide/markdown.html#import-code-snippets) feature for .js, .css and .html fragments, but the file(s) are not included. I tried all sorts of pathnames with/without the `base`, relative, absolute, all to no avail.
Everything else works like a charme.

The project is a simple Vite Vue project. I then installed VitePress with yarn. 
It resides in `src/_docs/.vitepress`.

Here's the config file
```js
import {defineConfig} from 'vitepress'
export default defineConfig({
    base: '/src/_docs/',
    title: "The Style Guide",
    markdown: {
        lineNumbers: false,
        toc: {includeLevel: [1, 2]},
    }
}
```
</div>

It's not clear to me, if this requires some special care for Prism. Configuration seems very different fro what I can find on Lea Verou's site.

**Comment by kiaking** [comment]
Please provide a valid reproduction. snippets import is working on VitePress docs so I have no idea what it's doing to you 👀
