### ISSUE TITLE
Your application tried to access vue, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound

### ISSUE THREAD

**Issue by busyhe** [vuejs/vitepress#531]
### Describe the bug

use yarn2 build docs

### Reproduction

yarn 

yarn add vitepress -D
vitepress serve docs

### Expected behavior

build success

### System Info

```shell
❯ node -v
v16.13.2
❯ npm -v
8.4.1
❯ yarn -v
3.1.1

"vitepress": "^0.22.1"
```

### Additional context

![Xnip2022-02-14_14-47-47](https://user-images.githubusercontent.com/17348825/153813796-b6b19a35-599a-4c0a-a8e1-81145a69f3bc.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You also need to install `vue` as a `dependency`/`devDependency`.

```
yarn add -D vue
```

**Comment by busyhe** [comment]
@brc-dd It's work. Thanks

**Comment by brc-dd** [comment]
@busyhe Keep this issue open. We probably need to add this to the docs to avoid any future confusion.
