### ISSUE TITLE
in markdown file, use image file, image file exists and path correct, but image load failed

### ISSUE THREAD

**Issue by ccpwcn** [vuejs/vitepress#534]
### Describe the bug

- building client + server bundles...Could not resolve './_media/ArrayList-inherit.jpg' from docs\java\Java基础入门\类和实例.md
✖ building client + server bundles...
Could not resolve './_media/ArrayList-inherit.jpg' from docs\java\Java基础入门\类和实例.md (x2)

### Reproduction

# markdown file path
docs/java/Java基础入门/类和实例.md

# image file path
docs/java/Java基础入门/_media/ArrayList-inherit.jpg

# in markdown file using
`![ArrayList类继承关系](./_media/ArrayList-inherit.jpg "ArrayList类继承关系")`

or 

`![ArrayList类继承关系](_media/ArrayList-inherit.jpg "ArrayList类继承关系")`

# then, run `yarn docs:build` building
compile error and failed
```text
- building client + server bundles...Could not resolve './_media/ArrayList-inherit.jpg' from docs\java\Java基础入门\类和实例.md
✖ building client + server bundles...
Could not resolve './_media/ArrayList-inherit.jpg' from docs\java\Java基础入门\类和实例.md (x2)
```

# other information
when use `<img :src="$withBase('./_media/ArrayList-inherit.jpg')" alt="ArrayList类继承关系" />`  , no errors.

### Expected behavior

no errors, compile success

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 16.46 GB / 31.85 GB
  Binaries:
    Node: 14.18.2 - E:\apps\node-v14\node.EXE
    Yarn: 1.22.10 - E:\apps\node-v14\node_global\yarn.CMD
    npm: 7.20.0 - E:\apps\node-v14\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.50)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    vitepress: ^0.22.2 => 0.22.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide a complete reproduction. Based on the information you've currently provided, I'm unable to reproduce the issue.

**Comment by brc-dd** [comment]
Closing this as stale.
