### ISSUE TITLE
How should one import an SFC in a markdown file?

### ISSUE THREAD

**Issue by roj1512** [vuejs/vitepress#535]
Here's the vitepress project: https://github.com/grammyjs/grammy

I'm creating `/site/docs/.vuepress/components/SomeComponent.vue` and trying to import it in `/site/docs/guide/README.md` this way:

```html
<script setup>
  import SomeComponent from '../components/SomeComponent.vue'
</script>
```

But I'm getting this:

![image](https://user-images.githubusercontent.com/49933115/153932261-ce3ab009-ecef-4ce7-aa86-6f3426508b82.png)

How should the custom component be imported?

**Comment by yyx990803** [comment]
It fails because your path is wrong. It should be `../.vitepress/components/xxx.vue`.
