### ISSUE TITLE
failed to install with yarn 

### ISSUE THREAD

**Issue by prashantnirgun** [vuejs/vitepress#544]
### Describe the bug

package.json
```
{
  "name": "vitepress-starter",
  "version": "1.0.0",
  "license": "ISC",
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:serve": "vitepress serve docs"
  },
  "devDependencies": {
    "vitepress": "^0.22.2"
  }
}
```
yarn 
warning "vitepress > @docsearch/js > @docsearch/react@3.0.0-alpha.50" has unmet peer dependency "@types/react@>= 16.8.0 < 18.0.0".
warning "vitepress > @docsearch/js > @docsearch/react@3.0.0-alpha.50" has unmet peer dependency "react@>= 16.8.0 < 18.0.0".
warning "vitepress > @docsearch/js > @docsearch/react@3.0.0-alpha.50" has unmet peer dependency "react-dom@>= 16.8.0 < 18.0.0".
warning "vitepress > @docsearch/js > @docsearch/react > @algolia/autocomplete-preset-algolia@1.5.2" has unmet peer dependency "@algolia/client-search@^4.9.1".
[4/4] Building fresh packages...
success Saved lockfile.

### Reproduction

yarn or npm install 

### Expected behavior

successful installation

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    Memory: 217.65 MB / 5.71 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.19.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 98.1.35.101
    Firefox: 97.0.1

```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Those are just warnings (not errors).

Duplicate of #472.

**Comment by prashantnirgun** [comment]
K closing the ticket and following [#472](https://github.com/vuejs/vitepress/issues/472)
