### ISSUE TITLE
Please create a category for help required

### ISSUE THREAD

**Issue by prashantnirgun** [vuejs/vitepress#549]
### Is your feature request related to a problem? Please describe.

I have some queries if I asked them under bug its not the right place, So I request you to create a new category for help required category to ask question. 

### Describe the solution you'd like

Create a new Category like 'Help Required' or Ask Questions, Do we have any forum or discord to ask questions ?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We do have a Discord server: https://discord.com/invite/HBherRA

You can also ask it at discussions tab: https://github.com/vuejs/vitepress/discussions

**Comment by prashantnirgun** [comment]
Thanks
