### ISSUE TITLE
How to read sitedata and pagedata inside vue component with default theme

### ISSUE THREAD

**Issue by prashantnirgun** [vuejs/vitepress#550]
### Describe the bug

Its not an bug its help required, I am using default theme how do I read siteData or page data ie chapter, topic custom variables inside vue script
file : Test.vue
```
<template>
  <div>Hi from Test</div>
</template>
<script>
import { defineComponent } from "vue";
import useSiteData from "vitepress";
export default defineComponent({
  setup() {
    const siteData = useSiteData();
    console.log("context", siteData);
  },
});
</script>
```
Console Error : 
 The requested module '/@fs/home/prashant/www/vitepress/node_modules/vitepress/dist/client/index.js' does not provide an export named 'default'
router.js:83          GET http://localhost:3000/hashmap.json 404 (Not Found)

Test.md
```
---
chapter : 1
topic : 1
---
# Test
<Test />
<script setup>
import Test from './Test.vue';
</script>
```

### Reproduction

go to chrome developer tool and console tab to view error details

### Expected behavior

I should able read the custom variable chapter & topic variable 

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    Memory: 558.27 MB / 5.71 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.19.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 98.1.35.101
    Firefox: 97.0.1
 "devDependencies": {
    "postcss": "^8.4.6",
    "sass": "^1.49.8",
    "stylus": "^0.56.0",
    "vitepress": "^0.22.2",
    "tailwindcss": "^3.0.23"
  },
  "dependencies": {
    "autoprefixer": "^10.4.2"
  },
  "postcss": {
    "plugins": {
      "tailwindcss": {},
      "autoprefixer": {}
    }
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
First there is a typo: `import { useSiteData } from "vitepress";` -- you need to do named import instead of default one. Second, this was removed in v0.15.0 in favor of `useData`.

Refer: https://github.com/vuejs/vitepress/blob/0c31bbac8593291ce6aecf17b38b16392239f58f/CHANGELOG.md#breaking-changes-2

---

```js
// before
import { useSiteDataByRoute, usePageData } from 'vitepress'
const site = useSiteDataByRoute()
const page = usePageData()
const theme = computed(() => site.value.themeConfig)

// after
import { useData } from 'vitepress'
const { site, page, theme } = useData()
```

**Comment by prashantnirgun** [comment]
Yes Thanks @brc-dd brc-dd how come I miss https://vitepress.vuejs.org/guide/using-vue.html#templating
