### ISSUE TITLE
API to change head content

### ISSUE THREAD

**Issue by aboutsimon** [vuejs/vitepress#551]
### Is your feature request related to a problem? Please describe.

Currently, there is no documented way to programmatically change or add `head` tags to the page at build time, that i'm aware of. I know that i can add `head` tags in the config or via `frontmatter`, but in some cases that is not sufficient. For example, when i want to add head tags based on existing meta data, like generating an `og:image` based on `frontmatter` ([gatsby-remark-twitter-cards](https://www.npmjs.com/package/gatsby-remark-twitter-cards) is an example in react land).

### Describe the solution you'd like

A clean API to programmatically change or add `head` tags, prior to SSG.

### Describe alternatives you've considered

Obviously i could dynamically add `head` tags to the page, but for some tags that is not a viable solution. For example, social media sites usually don't execute JS on the page, so any dynamically added Open Graph tags will not be considered.

Another option would be hacking something together around [rollup's transform hook](https://rollupjs.org/guide/en/#transform), but i would rather use a more dedicated vitepress API directly.

### Additional context

Maybe i'm missing something here and this is already possible - then please point me in the right direction.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by jimbo2150** [comment]
The social media tags were added to Frontmatter for the [VitePress website](https://raw.githubusercontent.com/vitejs/vite/v3.1.6/docs/blog/announcing-vite3.md), but they don't appear to be applying (either on the VitePress site or mine) and [don't appear to be documented](https://vitepress.vuejs.org/config/frontmatter-configs). Is that a bug?

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/site-config#transformhead
