### ISSUE TITLE
Adding prev next arrow on both sides of the page for wide layout

### ISSUE THREAD

**Issue by laoshaw** [vuejs/vitepress#553]
### Is your feature request related to a problem? Please describe.

For a long page I just want to skip to prev|next page fast, I now have to scroll down all the way to the bottom to find the left|right arrow. Would like to have a left and right arrow at the middle of the page for easier access instead, which is what gitbook, mdbook and others do by default. This is the only major feature I feel missing comparing to gitbook etc in vuepress and vitepress.

### Describe the solution you'd like

Something like below(screenshot of a gitbook page)

![image](https://user-images.githubusercontent.com/18351761/155336241-20fbb963-fbb6-4bce-b811-e10d2e23e0c3.png)

### Describe alternatives you've considered

For very narrow screen those arrow might need to turn off as it takes space, otherwise they can just stay on.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Might be interesting idea 👀 I think we need some try and errors on designing the UI, but I think it's cool feature to have it on the list.

**Comment by kecrily** [comment]
If it is only displayed on the large screen, is it possible to put it together with the TOC as a resident toolbar?

Since it is now a three column design continue to add things to the Doc, I think it might be a bit cramped.

**Comment by kiaking** [comment]
Ah, good point. That might be interesting 🤔  Well in space perspective, we have more space left and right in 768px – 1280px range, so I think it's possible to add this arrows on those screen sizes.

In that case those arrows moving to aside on > 1280px might be confusing...

We should consider the design on every screen break point. But Having this in aside section sounds fair idea. Since I'm planning to have some kind of way to show aside section in > 1280px screen too.

**Comment by Andrew-web-coder** [comment]
Personally, I don't like them and don't see the point since the navigation links are easily accessible on both the right and left sides.

**Comment by kiaking** [comment]
Closing this for now. Not getting so much attention, and I think this is not super common feature. Might be confusing 🤔
