### ISSUE TITLE
"Live" Code Blocks

### ISSUE THREAD

**Issue by richardtallent** [vuejs/vitepress#554]
### Is your feature request related to a problem? Please describe.

I'm using VitePress to document our coding standards and our design system. I want to show examples of the code we would use (HTML and Vue components) *and* how that code would render.

I can import and use Vue components in the markdown (and HTML) without issue. But to show both the "live" and "source" views of that code, I have to copy my live code into a separate markdown code block, which means now I have *two* blocks of code to manage and synchronize for each example.

### Describe the solution you'd like

I'd like a new directive for "```" code blocks that, when viewed in VitePress, shows up as a tabbed interface with two tabs: (1) the rendered version of that code (using the normal rendering done by VitePress, supporting Vue and HTML), and (2) the normal way the code block would be otherwise rendered.

I *believe* this would simply require detecting this directive, duplicating the code within the block as non-fenced code, and wrapping the pair in a simple tabbed Vue component.

Obviously for more complex examples, the VitePress version of the live code will differ from what needs to be shown to the user, so that is a challenge (the Vue docs themselves have this challenge). But for simple examples of using Vue components and HTML with no additional script involved, it would really help.

My suggestion would be something like "```html:live", where the ":live" bit either comes before or after any row number highlights (I don't think it would matter).

### Describe alternatives you've considered

Copying and pasting between markdown code blocks to markdown live code, keeping them synchronized as the code is updated.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by treystout** [comment]
Are there existing plugins for this in vuepress? I was debating how to accomplish this in my own project and was curious what the pros/cons are of using something like embedded fiddlle or codepen widgets vs having a built-in way to do it. Either way +1 on the directive.

**Comment by brc-dd** [comment]
Why not simply create a Vue component that does that? Or maybe one can write a markdown-it plugin for this (either from scratch or just using markdown-it-container)?

**Comment by brc-dd** [comment]
Closing this for now as it can easily be accomplished by custom components or external plugins.

**Comment by elevatebart** [comment]
Here is my take on it using `vue-live` https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/examples/docgen-vite/docs/.vitepress.

Would love some feedback.

**Comment by emersonbottero** [comment]
> Here is my take on it using `vue-live` https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/examples/docgen-vite/docs/.vitepress.
> 
> Would love some feedback.

@elevatebart  Make It a vitepress-plugin!
And i would prefer Monaco because of intelisense 😉
