### ISSUE TITLE
Change createMarkdownRenderer base to default to `''`

### ISSUE THREAD

**Issue by ST-DDT** [vuejs/vitepress#555]
https://github.com/vuejs/vitepress/commit/804954cf4d5417b1abcba9854ed5f064348292c5#diff-332834eb76757b8e31926e411cef34f7207564d0bf5fd00a185b41d97b3403bfR53

This change is not backwards compatible, it would be nice if the value could be set by default.

_Originally posted by @ST-DDT in https://github.com/vuejs/vitepress/pull/502#issuecomment-1051312775_

**Comment by ST-DDT** [comment]
It would also be nice if the parameter could be renamed to `linkBase` or be annotated with some JSDocs , so its clear what it does.

**Comment by brc-dd** [comment]
`base` is by default `/` (ref: https://vitepress.vuejs.org/config/basics.html#base)

> It would also be nice if the parameter could be renamed to `linkBase` or be annotated with some JSDocs , so its clear what it does.

Throughout the codebase, base is referred by `base` only, and (almost every time) means the same thing that is written in the docs.

> This change is not backwards compatible,

Whatever done in that PR is an internal API, and not meant to be used directly.

---

That said, we can probably change this:

https://github.com/vuejs/vitepress/blob/06ad0d8386626eab2e98af1b591ac34295d9f7ed/src/node/markdownToVue.ts#L30

to `base: '/',`. It won't matter much for default working of VitePress anyway.

**Comment by ST-DDT** [comment]
> Whatever done in that PR concerns an internal API, and not meant to be used directly.

https://github.com/vuejs/vitepress/blob/main/CHANGELOG.md#0203-2021-12-07

I thought this meant it is public API.
Nevermind then.
Is there something similar (md `string` to `html` string) that is is public api?
