### ISSUE TITLE
[npx] Cannot find module 'vue'

### ISSUE THREAD

**Issue by hyrious** [vuejs/vitepress#557]
### Describe the bug

I tried to run vitepress through `npx` without installing it in the local package. And starting from 0.21.4 (I didn't narrow down the version number precisely) `npx vitepress build` won't work, but `npx vitepress dev` works fine.

```bash
> npx vitepress build docs
vitepress v0.21.4
- building client + server bundles...
✓ building client + server bundles...
- rendering pages...
✖ rendering pages...
build error:
 Error: Cannot find module 'vue'
Require stack:
- /home/runner/work/esbuild-dev/esbuild-dev/docs/.vitepress/.temp/app.js
```

Full output see the table below:

| version | behavior | log |
|---------|----------|-----|
| 0.20.9  | `dev` fine, `build` fine | [gh action log](https://github.com/hyrious/esbuild-dev/runs/4613503146?check_suite_focus=true#step:5:12) |
| 0.21.4 ~ 0.22.3 | `dev` fine, `build` error | [gh action log](https://github.com/hyrious/esbuild-dev/runs/4824411193?check_suite_focus=true#step:5:18) |

### Reproduction

Try this command without installing vitepress:

```bash
npx vitepress build docs
```

### Expected behavior

The `build` command should work.

### System Info

```shell
  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz
    Memory: 6.00 GB / 11.89 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.62)
    Internet Explorer: 11.0.19041.1202
```

### Additional context

I noticed #324 has similar situation but the error message differs.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by hyrious** [comment]
@brc-dd noluck, same error

**Comment by yyx990803** [comment]
This isn't a supported use case because VitePress SSR is executed from a temp build directory in your project. It assumes VitePress itself (and thus Vue) is installed locally.
