### ISSUE TITLE
How to install vuepress plugin into vitepress

### ISSUE THREAD

**Issue by prashantnirgun** [vuejs/vitepress#558]
### Describe the bug

Hi I am new to vitepress please help I want to install Medium -zoom (yarn add -D @Vue#8625press/plugin-medium-zoom) plugin I install the package 
is there something I am missing
```
//package.json
"devDependencies": {
    "@vuepress/plugin-medium-zoom": "^1.9.7",
    "@vuepress/shared-utils": "^1.9.7",
    "postcss": "^8.4.6",
    "sass": "^1.49.8",
    "stylus": "^0.56.0",
    "tailwindcss": "^3.0.23",
    "vitepress": "^0.22.2"
  },
  "dependencies": {
    "autoprefixer": "^10.4.2",
    "markdown-it-imsize": "^2.0.1"
  },
  "postcss": {
    "plugins": {
      "tailwindcss": {},
      "autoprefixer": {}
    }
  } 
```
// docs/vite.config.ts```
import { defineConfig } from "vite";
import medium from "@vuepress/plugin-medium-zoom";

export default defineConfig({
  plugins: [medium],
});
```
firstly I was getting following error so I installed yarn add -D @Vue#8625press/shared-utils
```
failed to load config from /home/prashant/www/vitepress/docs/vite.config.js
failed to start server. error:
 Error: Cannot find module '@vuepress/shared-utils'
```
then I installed yarn add  markdown-it-imsize
```
failed to load config from /home/prashant/www/vitepress/docs/vite.config.js
failed to start server. error:
 Error: Cannot find module 'markdown-it-emoji/lib/data/full.json'
``` now its showing new missing dependancy ```failed to load config from /home/prashant/www/vitepress/docs/vite.config.js
failed to start server. error:
 Error: Cannot find module 'lru-cache'
```

### Reproduction

yarn dev

### Expected behavior

should start server with the zoom feature

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    Memory: 1.38 GB / 5.71 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.19.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 98.1.35.103
    Firefox: 97.0.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
VitePress is different from VuePress, hence you can't install VuePress plugin 🙇‍♂️
