### ISSUE TITLE
Why my Vue-style interpolation `{{ 1 + 1 }}`  rendered as `2` ?

### ISSUE THREAD

**Issue by drylint** [vuejs/vitepress#559]
### Describe the bug

My markdown text:

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/80906525/155890963-b51635a5-4b51-47c7-a7c2-b1236c756a4b.png">

```md
# Test

You can use Vue-style interpolation in markdown, such as `{{ 1 + 1 }}`.

```

But it rendered as:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/80906525/155890922-5e57942a-b66d-4cab-9fd6-c85fcea7ddf4.png">

### Reproduction

1. Create a vitepress project;
2. Add a index.md file and input text:

```md
# Test

You can use Vue-style interpolation in markdown, such as `{{ 1 + 1 }}`.

```

### Expected behavior

# Test

You can use Vue-style interpolation in markdown, such as `{{ 1 + 1 }}`.

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 16.68 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Safari: 15.3
  npmPackages:
    vitepress: ^0.22.3 => 0.22.3
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/discussions/480#discussioncomment-2225141

**Comment by drylint** [comment]
Thanks, but I think it goes against markdown's inline code grammar. it should not to parse anything in \`anything\`.

**Comment by drylint** [comment]
> [#480 (comment)](https://github.com/vuejs/vitepress/discussions/480#discussioncomment-2225141)

Thanks, but I think it goes against markdown's inline code grammar. it should not to parse anything in \`anything\`.

**Comment by kiaking** [comment]
Well I would say inline code block syntax is just a syntax, and you're getting the right syntax there (2 is wrapped with `code`).

Because VitePress is Vue powered builder, and that's the key feature, I think this should kept as is.
