### ISSUE TITLE
Can add the navigation bar logo and web favicon?

### ISSUE THREAD

**Issue by godxiaoji** [vuejs/vitepress#560]
### Is your feature request related to a problem? Please describe.

The current version does not support logo display. The document effect is weakened, and it is difficult to distinguish in the browser tab bar.

### Describe the solution you'd like

1. Support logo settings in config.js.
2. Support logo or favicon settings in `Head`.

### Validations

- [x] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Simply adding `favicon.ico` to your `public` folder should pick that up.

If you want to add properties to head, then you can modify your `.vitepress/config.js`:

```js
module.exports = {
  title: 'Title of the site',
  description: 'Description of the site',
  head: [
    ['link', { rel: "apple-touch-icon", sizes: "180x180", href: "/assets/favicons/apple-touch-icon.png"}],
    ['link', { rel: "icon", type: "image/png", sizes: "32x32", href: "/assets/favicons/favicon-32x32.png"}],
    ['link', { rel: "icon", type: "image/png", sizes: "16x16", href: "/assets/favicons/favicon-16x16.png"}],
    ['link', { rel: "manifest", href: "/assets/favicons/site.webmanifest"}],
    ['link', { rel: "mask-icon", href: "/assets/favicons/safari-pinned-tab.svg", color: "#3a0839"}],
    ['link', { rel: "shortcut icon", href: "/assets/favicons/favicon.ico"}],
    ['meta', { name: "msapplication-TileColor", content: "#3a0839"}],
    ['meta', { name: "msapplication-config", content: "/assets/favicons/browserconfig.xml"}],
    ['meta', { name: "theme-color", content: "#ffffff"}],
  ],
  // ...
}
```

**Comment by godxiaoji** [comment]
> ```js
> head: [
>     ['link', { rel: "apple-touch-icon", sizes: "180x180", href: "/assets/favicons/apple-touch-icon.png"}],
>     ['link', { rel: "icon", type: "image/png", sizes: "32x32", href: "/assets/favicons/favicon-32x32.png"}],
>     ['link', { rel: "icon", type: "image/png", sizes: "16x16", href: "/assets/favicons/favicon-16x16.png"}],
>     ['link', { rel: "manifest", href: "/assets/favicons/site.webmanifest"}],
>     ['link', { rel: "mask-icon", href: "/assets/favicons/safari-pinned-tab.svg", color: "#3a0839"}],
>     ['link', { rel: "shortcut icon", href: "/assets/favicons/favicon.ico"}],
>     ['meta', { name: "msapplication-TileColor", content: "#3a0839"}],
>     ['meta', { name: "msapplication-config", content: "/assets/favicons/browserconfig.xml"}],
>     ['meta', { name: "theme-color", content: "#ffffff"}],
>   ],
> ```

It is verified that the way is feasible. But the path to pulickDir  is not clearly stated, It in `docs` neither `root` nor `.vitepress`.
