### ISSUE TITLE
vitepress build hangs after a successful build

### ISSUE THREAD

**Issue by saxon-y** [vuejs/vitepress#562]
### Describe the bug

When I reference a `vue single-file component` in markdown, it still hangs after the build command is completed.
Already discussed in issue #64

### Reproduction

https://codesandbox.io/s/busy-bush-bexhv1

### Expected behavior

process exit after build completed

### System Info

```shell
"vitepress": "^0.22.3"
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by hcg1023** [comment]
Have the same problem

**Comment by hcg1023** [comment]
The reason for this problem is that we executed a setInterval in the SFC script, and I now use `if(typeof window! == 'undefined') ` skips its execution and is normal @saxon-y

**Comment by saxon-y** [comment]
well done!!! 666呀，兄得

**Comment by hcg1023** [comment]
> @hcg1023 做得好！！！666呀，兄得

哈哈，nice

**Comment by kiaking** [comment]
Closing the issue since seems like it found a solution. And also it's documented to be careful on running client side code.
