### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by knyttl** [vuejs/vitepress#567]
### Is your feature request related to a problem? Please describe.

When using vitepress for things like Terms and Conditions, it would be beneficial to be able to export them to PDF.

### Describe the solution you'd like

when having `/my-doc.html`, it would be great to also have `/my-doc.pdf` which would render the same file's PDF version.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by posva** [comment]
Closing in favor of https://github.com/vuejs/vitepress/issues/593
