### ISSUE TITLE
vitepress server .md.undefined.lean.js

### ISSUE THREAD

**Issue by Greasen** [vuejs/vitepress#574]
### Describe the bug

.vitepress -> config.ts
base: '/base/'

打包构建后，/base/assets/.md.undefined.lean.js 文件出现，
这个文件在我的项目中并未出现，在打包后的文件中也未出现，请问这个文件是怎么来的？

### Reproduction

.vitepress -> config.ts
base: '/base/'

打包构建后，/base/assets/.md.undefined.lean.js 文件出现，
这个文件在我的项目中并未出现，在打包后的文件中也未出现，请问这个文件是怎么来的？

### Expected behavior

.vitepress -> config.ts
base: '/base/'

打包构建后，/base/assets/.md.undefined.lean.js 文件出现，
这个文件在我的项目中并未出现，在打包后的文件中也未出现，请问这个文件是怎么来的？

### System Info

```shell
System:
    OS: Microsoft Windows 10
    CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz，2904 Mhz，6 个内核，12 个逻辑处理器
    Memory: 16 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.2
    npm: 8.1.2
  Browsers:
    Chrome: 99.0.4844.51
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you test if applying this patch helps:

```diff
diff --git a/dist/client/app/utils.js b/dist/client/app/utils.js
index 0411dde2de1581dd50e779dc82093268a103a3d9..047102a11fbd7f5b05b2fdf189221888f9bd16d1 100644
--- a/dist/client/app/utils.js
+++ b/dist/client/app/utils.js
@@ -31,7 +31,7 @@ export function pathToFile(path) {
         // /foo/bar.html -> ./foo_bar.md
         if (inBrowser) {
             const base = import.meta.env.BASE_URL;
-            pagePath = pagePath.slice(base.length).replace(/\//g, '_') + '.md';
+            pagePath = (pagePath.slice(base.length).replace(/\//g, '_') || 'index') + '.md';
             // client production build needs to account for page hash, which is
             // injected directly in the page's html
             const pageHash = __VP_HASH_MAP__[pagePath.toLowerCase()];
```

**Comment by Greasen** [comment]
> 您能否测试应用此补丁是否有帮助：
> 
> ```diff
> 差异 --git a/dist/client/app/utils.js b/dist/client/app/utils.js
> 索引 0411dde2de1581dd50e779dc82093268a103a3d9..047102a11fbd7f5b05b2fdf189221888f9bd16d1 100644
> --- a/dist/client/app/utils.js 
> +++ b/dist/client/app/utils.js 
> @@ -31,7 +31,7 @@ export function pathToFile(path) {
>          // /foo/bar.html -> ./foo_bar.md
>          如果（在浏览器中）{
>              常量基数 = import.meta.env.BASE_URL;
> -             pagePath = pagePath.slice(base.length).replace(/\//g, '_') + '.md'; 
> +             pagePath = (pagePath.slice(base.length).replace(/\//g, '_') || 'index') + '.md';
>              // 客户端生产构建需要考虑页面哈希，即
>              // 直接注入到页面的html中
>              常量 pageHash = __VP_HASH_MAP__[pagePath.toLowerCase()];
> ```

你好，问题我已经解决了，vitepress的 config.ts 和 vite.config.ts 的 root 配置没有配置好；
谢谢你的回复；

**Comment by cschensai** [comment]
> 
请问 你怎么配置的 我也出现这个问题了
