### ISSUE TITLE
Internal server error: [@vue/compiler-sfc] <script> and <script setup> must have the same language type.

### ISSUE THREAD

**Issue by ljcremer** [vuejs/vitepress#575]
### Describe the bug

I am trying to use vue inside the markup but it seems like I cannot use typescript

### Reproduction

If I add the following line in my markup file I get the error:

```md
<script setup lang="ts">
```

### Expected behavior

Would like to use typescript in the markdown if possible. 

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 7.01 GB / 15.85 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.20.6 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.30)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vitepress: ^0.22.3 => 0.22.3
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by LinusBorg** [comment]
We use Vitepress, script setup and typescript for the vuejs.org docs, so it definitely *is* possible.

You need to share a reproduction, at the very least the code throwing an error.

**Comment by ljcremer** [comment]
Thanks Linus. I will have to do a bit of work to publish a reproduction. 

Is the script setup typescript done in the markdown file?

In the meantime can you maybe give me a link to a page where this is done in the documentation?

**Comment by LinusBorg** [comment]
Oh, you add that in a markup file - I totally missed that part, my bad. That might indeed not be well supported right now. 

A real reproduction would nonetheless be welcomed.

**Comment by posva** [comment]
You need to close the `<script>`. If that's not it create a new issue with a boiled down repro.
