### ISSUE TITLE
Element is missing end tag Error when used inside a link like [SimpleLink<T>] ("somewhere")

### ISSUE THREAD

**Issue by botteroxom** [vuejs/vitepress#576]
### Describe the bug

content inside [] should not be parsed as html 

### Reproduction

just use 
```
[SimpleLink<T>] ("somewhere")
```
in any md file

### Expected behavior

The page should render even with "Element is missing end tag" when inside [ ]

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz   
    Memory: 16.55 GB / 31.88 GB
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE        
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.30)
    Internet Explorer: 11.0.19041.1202
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> content inside [] should not be parsed as html

Why not?

**Comment by botteroxom** [comment]
Hi , I miss this thread.
thanks for the info. I'll try and regex that replace those cases.

To give you context ...

the T in this case is not an html tag.. 
is used in C# to define a generic parameter of type T.

page example using it 
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/generics

there is a link with [List<T>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1) in the docs

those links along with the documentation md files are generated from source code by a tool so is not something that I typed.

**Comment by brc-dd** [comment]
Probably ask that tool's authors to generate headers wrapped in back ticks. This isn't valid MD. And on msdn, they are probably escaping those brackets other wise no browser would've redered it.
