### ISSUE TITLE
want more flexibility in the customization part

### ISSUE THREAD

**Issue by xxholly32** [vuejs/vitepress#58]
i want use vitepress become a ui component display website. so i import my sfc in enhanceApp. But at meantime i must config my own `Layout.vue` and `notfound.vue` component. That is not what i want. i liked defaulte theme (vuepress old player) very mush. 

```js
import Layout from '/@theme/Layout.vue';
import Helloworld from "../components/index"

export default {
  Layout,
  // NotFound,
  enhanceApp({ app, router, siteData }) {
    app.use(Helloworld) 
  }
}
```

i think `@theme/index` should not config default layout and enhanceApp at same time or in the same file. or at least it must follow `Convention over configuration` rule.

if follow [vuepress default theme file system](https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/theme-default) and `Convention over configuration`, it will be better

maybe use `@theme/layouts/`, `@theme/components/`

and here is a bug, when a create emptyfile `theme` in `.vitepress` .it will crash

**Comment by kiaking** [comment]
Yeah this is good feature to have. At the moment, you can do this to extend the default theme.

```js
import DefaultTheme from 'vitepress/dist/client/theme-default'  // To extend default theme.
import Helloworld from '../components/index'

export default {
  ...DefaultTheme,
  enhanceApp({ app }) {
    app.use(Helloworld)
  }
}
```
