### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wuduo0701** [vuejs/vitepress#592]
### Describe the bug

运行npm run docs:build 命令，为什么打包会受node_modules的影响。该如何修复这个问题
 Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/linjiahao7/Documents/Project/web-jac-plus/docs/node_modules/lodash-es/lodash.js
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/56730345/160794817-069cf7d8-a148-4ec7-81a1-3f48651d86a6.png">

### Reproduction

npm run docs:build

### Expected behavior

怎么去修复这个问题，才能打包成功

### System Info

```shell
System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 217.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Firefox: 98.0.2
    Safari: 14.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
Hello, make sure to always provide a reproduction so we can check.

Open a new issue with a reproduction that follows those instructions if you manage to create a boiled-down reproduction.

**Comment by yl-199807** [comment]
我也遇到了，请问你解决了吗

**Comment by linxiang07** [comment]
各位有谁解决了吗，我也遇到了这个问题

**Comment by wuduo0701** [comment]
> 各位有谁解决了吗，我也遇到了这个问题

你好 上次我是把引入的lodash-es改为引入lodash 可以成功打包

**Comment by linxiang07** [comment]
> 

好吧，我是从 `lodash` 改成 `lodash-es` 才出现的这个问题，我是为了减少打包体积
