### ISSUE TITLE
export to pdf 

### ISSUE THREAD

**Issue by laoshaw** [vuejs/vitepress#593]
### Is your feature request related to a problem? Please describe.

not really

### Describe the solution you'd like

a plugin or built-in feature of vitepress that I can export the document to PDF, to annotate offline

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
I think this is too heavy feature to be built in to the core. Having such an 3rd party lib might be really cool though 👍

**Comment by posva** [comment]
You can also use a browser extension: https://chrome.google.com/webstore/detail/save-as-pdf/kpdjmbiefanbdgnkcikhllpmjnnllbbc

**Comment by yadunandanbhat** [comment]
> I think this is too heavy feature to be built in to the core. Having such an 3rd party lib might be really cool though 👍

There is! See [markdown-pdf](https://github.com/alanshaw/markdown-pdf/), But it might be a hassle integrating it.

**Comment by ourongxing** [comment]
try to use https://github.com/busiyiworld/web-printer/tree/main/packages/vitepress

**Comment by condorheroblog** [comment]
you can use this https://github.com/condorheroblog/vitepress-export-pdf

Born specifically for `VitePress`, convert your desired web page into a PDF.

![](https://github.com/vuejs/vitepress/assets/47056890/d12e2ef4-2372-4854-9cdd-b61ceea5b5d7)
