### ISSUE TITLE
Build error, window not defined

### ISSUE THREAD

**Issue by Roman-00** [vuejs/vitepress#596]
### Discussed in https://github.com/vuejs/vitepress/discussions/595

<div type='discussions-op-text'>

<sup>Originally posted by **Roman-00** April  4, 2022</sup>
Good afternoon, 
I ran into such a problem that when building the project, he swears on the window
![example-error](https://user-images.githubusercontent.com/58338625/161504465-ea2d12ce-7a03-41cc-b11c-b823749a6879.jpg)
![example-using-window](https://user-images.githubusercontent.com/58338625/161504475-7869596b-4b68-449a-b9e8-3c12088eba42.jpg)
.

Please tell me what is the problem?</div>

**Comment by LinusBorg** [comment]
vitepress uses server-side rendering in node to build your HTML pages. Node doesn't have a `window`object. So you need to check for its presence before trying to use it.

**Comment by Roman-00** [comment]
Thank you so much for the explanation! 
But are there mechanisms to separate the server and client code?

**Comment by Roman-00** [comment]
> vitepress uses server-side rendering in node to build your HTML pages. Node doesn't have a `window` object. So you need to check for its presence before trying to use it.

Thank you so much for the explanation!
But are there mechanisms to separate the server and client code?

**Comment by LinusBorg** [comment]
no.

**Comment by Roman-00** [comment]
> no. you need to guard for that.

Thank you so much

**Comment by khusseini** [comment]
Just FYI, I had the same issue, but because of 3rd party packages./
I wrapped my component in `<ClientOnly>` and that worked like a charm.
