### ISSUE TITLE
Building with `mode: 'development'` throws errors, generates all pages as 404s

### ISSUE THREAD

**Issue by catrope** [vuejs/vitepress#598]
### Describe the bug

We use VitePress to build a demo website for a component library. To allow the Vue browser tools to work on this demo website, we would like to build and publish the website in production mode.

I thought that adding `mode: 'development'` to our `vite.config.ts` would accomplish this, but it throws errors like this when building:
```
⠦ rendering pages...Error: Cannot find module '/introduction/usage.md?t=1649205963799'
Require stack:
- /home/catrope/git/codex/packages/codex-docs/docs/.vitepress/.temp/app.js
- /home/catrope/git/codex/packages/codex-docs/node_modules/vitepress/dist/node/serve-9874c5ac.js
- /home/catrope/git/codex/packages/codex-docs/node_modules/vitepress/dist/node/cli.js
- /home/catrope/git/codex/packages/codex-docs/node_modules/vitepress/bin/vitepress.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at /home/catrope/git/codex/packages/codex-docs/docs/.vitepress/.temp/app.js:2098:12
    at loadPage (/home/catrope/git/codex/packages/codex-docs/docs/.vitepress/.temp/app.js:185:18)
    at Object.go (/home/catrope/git/codex/packages/codex-docs/docs/.vitepress/.temp/app.js:178:12)
    at renderPage (/home/catrope/git/codex/packages/codex-docs/node_modules/vitepress/dist/node/serve-9874c5ac.js:40217:10)
    at Object.build (/home/catrope/git/codex/packages/codex-docs/node_modules/vitepress/dist/node/serve-9874c5ac.js:40362:15) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/catrope/git/codex/packages/codex-docs/docs/.vitepress/.temp/app.js',
    '/home/catrope/git/codex/packages/codex-docs/node_modules/vitepress/dist/node/serve-9874c5ac.js',
    '/home/catrope/git/codex/packages/codex-docs/node_modules/vitepress/dist/node/cli.js',
    '/home/catrope/git/codex/packages/codex-docs/node_modules/vitepress/bin/vitepress.js'
  ]
}
```
This error repeats for every Markdown file. The build then says it has succeeded, and it does produce a directory structure with HTML files, but all of them contain a 404 error page.

I also tried adding `vue: { isProduction: false }` to the VitePress config, but that doesn't appear to make the development tools work.

### Reproduction

- In `docs/vite.config.ts`,add `mode: 'development'` at the top level (our full Vite config is [here](https://github.com/wikimedia/design-codex/blob/main/packages/codex-docs/docs/vite.config.ts))
- Run `vitepress build docs`
- Lots of errors are thrown, and a build is generated that contains only 404 pages

### Expected behavior

A static site is built that has the correct content in it (not just 404 pages), and that uses the development build of Vue rather than the production build. At minimum, enabling development mode shouldn't blow everything up.

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 1.89 GB / 15.39 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.9.1/bin/yarn
    npm: 8.5.3 - ~/.nvm/versions/node/v16.9.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Chromium: 100.0.4896.60
    Firefox: 98.0.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment]
Hello, make sure to always provide a reproduction so we can check. From the error it looks like you need to configure vite to serve from an upper folder.

Open a new issue with a reproduction that follows those instructions if you manage to create a boiled-down reproduction.
