### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by silvandiepen** [vuejs/vitepress#6]
Vitepress dev completely works, only when I try to build I get an error;

### Result;

```bash
vitepress-test / npx vitepress build
npx: installed 400 in 15.494s
vitepress v0.1.1
building client bundle...
build error:
 { [Error: ENOENT: no such file or directory, rmdir '/Users/username/.npm/_npx/83716/lib/node_modules/vitepress/lib/app/temp']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rmdir',
  path:
   '/Users/username/.npm/_npx/83716/lib/node_modules/vitepress/lib/app/temp' }
```

### details;
- Terminal ZSH
- Node v11.15.0
- Mac OS 10.15.4

### What I did;

- ✅ Create a new folder
- ✅ npm init -y
- ✅ npm install -D vitepress
- ✅ echo '# Hello VitePress' > index.md
- ✅ npx vitepress 
- 😢 npx vitepress build

### I've tried;
- Switching node version (8,10 and 11)
- Create a new clean folder (see result above)
- Build in Netlify

**Comment by brattonross** [comment]
I believe that Node needs to be >= v12.10.0 for the use of fs.rmdir recursive flag (see #3 )

**Comment by silvandiepen** [comment]
So true, stupid I didn't try a newer version.
