### ISSUE TITLE
Is vitepress auto register components in `.vitepress/components`?

### ISSUE THREAD

**Issue by beetaa** [vuejs/vitepress#60]
**Describe the bug**
When I use the components directly in markdown file, It raised a waring with `vue.js:1099 [Vue warn]: Failed to resolve componen` as:

![image](https://user-images.githubusercontent.com/5688224/89114794-f0f3d400-d4b2-11ea-901a-46a94d19814a.png)

Does vitepress auto register components in `.vitepress/components`? or where can I put the `.vue` files and how to use them? thank you.

**To Reproduce**

**Expected behavior**

**System Info**
- vitepress version:
- vite version:
- Node version:
- OS version:

**Additional context**

**Comment by em2046** [comment]
Seems like vitepress recommend import components clearly.
You can use gulp script auto generate import code like this [register-components.ts](https://github.com/em2046/nova-next/blob/master/build/tasks/register-components.ts)
It generate code that import and register all `.vue` file in `.vitepress/components` directory.

reference:
[@vuepress/plugin-register-components](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-register-components/index.js)

**Comment by beetaa** [comment]
> Seems like vitepress recommend import components clearly.
> You can use gulp script auto generate import code like this [register-components.ts](https://github.com/em2046/nova-next/blob/master/build/tasks/register-components.ts) [](/em2046/nova-next/blob/HEAD@{2020-08-02T13:23:25Z}/build/tasks/register-components.ts)
> It generate code that import and register all `.vue` file in `.vitepress/components` directory.
> 
> reference:
> [@vuepress/plugin-register-components](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-register-components/index.js) [](/vuejs/vuepress/blob/HEAD@{2020-08-02T13:23:25Z}/packages/%40vuepress/plugin-register-components/index.js)

SUPER useful info. thank you so much. @em2046 👍

**Comment by cloydlau** [comment]
The auther said he's not sure if he's going to be keeping this feature yet because we can import components from .md by adding a <script/> tag, but I'm not sure how to do that properly.

**Comment by antfu** [comment]
Maybe you can try this: https://github.com/antfu/vite-plugin-components

It's built for Vite, haven't been tested out on Vitepress though. If anyone would like to try it out, I am happy to help with making it fit Vitepress.

**Comment by xxholly32** [comment]
Officials said vitepress will be no plug-in system, (all customization is done in themes) .  <https://github.com/vuejs/vitepress#will-this-become-the-next-vuepress-in-the-future>

but i think plug-in is the best way to add users requiements like this issues. and vitepress-client can add plugin in [here](https://github.com/vuejs/vitepress/blob/master/src/client/app/index.ts#L109) ,perhaps vitepress-server can add plug-in system too.
