### ISSUE TITLE
My solution for custom components accessing relative assets  -- Vite's static asset handling and enhanced Markdown hoisting

### ISSUE THREAD

**Issue by kaceo** [vuejs/vitepress#607]
### Is your feature request related to a problem? Please describe.

Currently Markdown is first-class in Vitepress in terms of asset-handling.  Vue, frontmatter are second class.

E.g. create a markdown page:

~~~md
<!-- index.md -->
This is an image
![](./image/myimage.png)
~~~

Vitepress parses into a Vue component, plus the image file is also added to the bundle pipeline for asset handling.

Compare with a user-defined Vue component:

~~~vue
//MyImage.vue
<template>
<img :src="withPath(src)">
</template>

<script setup>
import { withPath } from 'vitepress'
const props = defineProps({ src: String })
</script>
~~~

~~~md
<!-- index.md -->
This is an image defined as Vue component.
<script setup>
import MyImage from './components/MyImage.vue'
</script>

<MyImage src="./image/myimage.png" />
~~~

The second case, Vitepress generates a target filename that is original source path with Base prepended.  **But the filename is not the same as the Markdown-generated filename**.  Also the image file is not added to the build.

Same problem also happen to images referenced in frontmatter are also unprocessed by asset pipelines, e.g. HeroImage on the Home page.

New users of Vitepress are always confused about this --- e.g. see #505 and #301

### Describe the solution you'd like

Of course not every property or frontmatter string are assets, only some of them.  

Hence the user should have a choice of which strings should be hashed and added to the asset pipeline.

Vitepress already provides a function "withBase" for customising URLs, but this is not enough for image assets. 

I would like to see user-callable functions that:
- resolves the URL correctly in both Dev and Build cases
- adds the file to the hash/build asset pipeline
- and behaves correctly with the rest of Vite and Rollup 

This will allow custom components to behave identically with Markdown, which is the original promise of Vitepress (i.e. "every Markdown page is translated into a Vue SFC component")

### Describe alternatives you've considered

1) The usual fallback of putting all images into "public" directory.  Not an elegant solution.

2) Defining path prefix constants in themeConfig.  Does not resolve all user cases.

3) Extending the Vite config to process extra directories.  Two moving targets instead of one.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kaceo** [comment]
After studying the VIte documentation in depth, I found a partial solution:   Instead of passing relative static asset files to custom property as strings, they can be "hinted" to Vite as requiring special treatment.

~~~md
<!-- Original index.md -->
Using custom components to display images
<script setup>
import MyImage from './components/MyImage.vue'
</script>

<MyImage src="./image/myimage.png" />
~~~

Change the above declaration to the following:

~~~md
<!-- Hinted index.md -->
Using custom components to display images
<script setup>
import MyImage from './components/MyImage.vue'
import imageurl from "./image/myimage.png"
</script>

<MyImage :src="imageurl" />
~~~

This strategy pushes the image filename into Vite's radar and asset handling pipeline.  The custom component's props receive the actual URL pathname of the image file (post hash and compression).

**Comment by kaceo** [comment]
Although it is possible to use <script> to hint the relative static asset before one custom component, it is troublesome if a markdown page contains many custom components that need hinting.  This is because each page can only contain one set of scripts, so all the filenames that need hinting must be collated into one place.

In my current project, there are between 40 to 100 custom image components per Markdown page.  This is a complex and unnecessary task to have to rearrange lines of documentation.

Perhaps a smarter solution is to provide a Markdown-it plugin to extend the syntax for hinting static assets: e.g.  a custom component can be created as a Markdown syntax block , 

<component>
import file1 from "./image/pix1.png"
<MyImage :src="file1" />
</component>

Then Vitepress can parse the Markdown and combine all the component scripts together, producing valid SFC outputs.

**Comment by kaceo** [comment]
Currently each Markdown document is parsed into an equivalent Vue SFC file, and any Script and Style tags found inside are "hoisted" into the output Vue file.  

However, if the author put in several scripts and styles sections, the converted file will be rejected by Vue as incorrect format.  

To make my strategy of making each component a "mini-script" with its own setup import statements, it is necessary for Vitepress to explicitly support each MD page to have multiple "script setup" sections.

Then Vitepress needs to concatenate all the setup scripts together into one script section.

I'll experiment with patching the Markdown processing of Vitepress, likely to be "hoist" and "component" scripts in /src/node/markdown/plugins/

**Comment by kaceo** [comment]
I have created a file "hint.js" which can either be a drop-in replacement for /src/node/markdown/plugin/hoist.ts, or it can chained into the .vitepress/config.js as a markdown plugin.

File located at https://gist.github.com/kaceo/fb335b5147e5615410477278424e56e9

With this change, a Markdown file can now have multiple sections of <script>, <script setup> and <style> anywhere inside the file, and similar type sections will be merged automatically during rendering.

__usage__

So using this new hoisting mechanism, this is how you use the Custom Component with a relative image asset:

~~~
<script setup>
import MyComponent from './component/mycomponent.vue'
import mypix from "./image/picture.png"
</script>
<MyComponent :src="mypix" 
caption="A caption" />
~~~

If you think this is a good enhancement to Vitepress please merge it into the repo, because I have no idea how to do that.

**Comment by kiaking** [comment]
Well I think the current behaviour makes sense. When you do `![...](...)`, VitePress is just helping out with markdown. On the other hand when you use Vue Component, it's more raw use case, and having to import image (or any assets) manually feels natural.

I mean how would VitePress know whether `./image/picture.png` is image or just a string?

In markdown, `![]()` this we know it's an image. But `<MyComponent :text="./image/picture.png">`, maybe this could just be a string user trying to display `./image/picture.png` and not the path to a file.

So I don't think we should cover this use case. Just import assets in markdown within `<script>` tag 👍
