### ISSUE TITLE
When hosting, I have already brought down this project for hosting in a subdirectory https://domain.com/ms/guide , can't get to js files and styles, writes 404

### ISSUE THREAD

**Issue by Roman-00** [vuejs/vitepress#610]
### Discussed in https://github.com/vuejs/vitepress/discussions/609

<div type='discussions-op-text'>

<sup>Originally posted by **Roman-00** April 25, 2022</sup>
When hosting, I have already brought down this project for hosting in a subdirectory https://domain.com/ms/guide , can't get to js files and styles, writes 404. How can I specify the path to styles and js files when building
![error1](https://user-images.githubusercontent.com/58338625/165007891-da912638-fc87-43a4-a466-a9aa928ddf61.jpg)

Can I somehow register the path to the files myself within vitepress?</div>

**Comment by brc-dd** [comment]
https://vitepress.vuejs.org/config/basics.html#base

Set your `base` to `/ms/guide/`.

**Comment by Roman-00** [comment]
Thank you very much.
