### ISSUE TITLE
[Algolia] Index creation

### ISSUE THREAD

**Issue by ennioVisco** [vuejs/vitepress#613]
### Describe the bug

Hello, I don't understand from the docs how an index should be built. If it is supposed to be automatically built, then it simply doesn't.

### Reproduction

Just set algolia following official docs.

### Expected behavior

Search should provide results.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 99.66 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 99.0.1
    Safari: 15.4
  npmPackages:
    vitepress: ^0.22.3 => 0.22.3
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yyx990803** [comment]
Algolia docsearch is a service - you should apply for access at https://docsearch.algolia.com/

**Comment by initdc** [comment]
https://segmentfault.com/a/1190000041480102/
