### ISSUE TITLE
 Algolia Search : transformItems  not work

### ISSUE THREAD

**Issue by Alsmile** [vuejs/vitepress#614]
### Is your feature request related to a problem? Please describe.

 Algolia Search : transformItems  not work.

![image](https://user-images.githubusercontent.com/1797302/165214041-f3cd225c-19b6-4347-b508-6fd883210dd2.png)

### Describe the solution you'd like

I want http://hostname/prefix/guide/  ->  http://hostname/guide/

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by initdc** [comment]
Two ways
1. reform your source code dir struct
2. rewrite URL with Cloudflare transform rule

**Comment by initdc** [comment]
`console.log(item.url)` first

**Comment by brc-dd** [comment]
Not possible to do it using config as functions are not serializable (x-ref https://github.com/vuejs/vitepress/issues/1381#issuecomment-1337162977). Manually create an Algolia component and register it in on of the navbar slots.
