### ISSUE TITLE
[pnpm run dev] error TS7016: Could not find a declaration file for module 'minimist'

### ISSUE THREAD

**Issue by shinshin86** [vuejs/vitepress#618]
## Description

I followed [this VitePress Contributing Guide](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md) and ran `pnpm run dev`.
I got the following error.

```sh
src/node/cli.ts:2:22 - error TS7016: Could not find a declaration file for module 'minimist'. '/Users/username/repo/vitepress/node_modules/.pnpm/minimist@1.2.5/node_modules/minimist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/minimist` if it exists or add a new declaration (.d.ts) file containing `declare module 'minimist';`
```

My running environment is as follows.

```sh
$node -v
v16.14.0
$ pnpm -v
7.0.0
```

## Steps to Resolve
Performing the following according to the error message will resolve the problem.

```sh
pnpm add -D -w @types/minimist
```
Is this happening only in my environment?

If this is a problem that is occurring in this project, I am considering to pull request a diff of this response.

```diff
diff --git a/package.json b/package.json
index ceb50b9..55ed6a4 100644
--- a/package.json
+++ b/package.json
@@ -94,6 +94,7 @@
     "@types/lru-cache": "^5.1.0",
     "@types/markdown-it": "^12.0.1",
     "@types/micromatch": "^4.0.2",
+    "@types/minimist": "^1.2.2",
     "@types/node": "^15.6.1",
     "@types/polka": "^0.5.3",
     "chalk": "^4.1.1",
```

### Reproduction

This occurred by executing the following command.

```sh
git clone https://github.com/vuejs/vitepress.git
cd vitepress
pnpm install
pnpm run dev
```

### Expected behavior

Successful completion of the following commands.

```sh
pnpm run dev
```

### System Info

```shell
System:
    OS: macOS 11.6.5
    CPU: (8) arm64 Apple M1
    Memory: 70.13 MB / 8.00 GB
    Shell: 5.8 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Chrome Canary: 103.0.5036.0
    Firefox: 96.0.2
    Safari: 15.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> Is this happening only in my environment?

No, happening on mine too. Feel free to create a PR.

**Comment by shinshin86** [comment]
Thanks for the reply.
I have created a PR(https://github.com/vuejs/vitepress/pull/622).
