### ISSUE TITLE
 there is no documentation for update default components 

### ISSUE THREAD

**Issue by denniarems** [vuejs/vitepress#620]
how can i update the css properties of this file ? bcoz every styles are scoped node_modules/vitepress/dist/client/theme-default/components/Page.vue

**Comment by brc-dd** [comment]
Could you please rephrase that? I'm not sure I understand what you mean.

PS: Is [this](https://vitepress.vuejs.org/guide/theming.html#customizing-css) what you're looking for? You can override those styles by doing something like this in your custom stylesheet:

```css
.page {
    /* ... */
}

.page > .container {
    /* ... */
}

.page > .container > .content {
    /* ... */
}
```

**Comment by kiaking** [comment]
There is documentation for this in both current, and in `next-theme` branch as mentioned by @brc-dd
