### ISSUE TITLE
NOTICE: VitePress Next Development is in progress

### ISSUE THREAD

**Issue by kiaking** [vuejs/vitepress#626]
We've started the ~bland~ brand new default theme development in `next` branch. Due to major update to the theme components, many open issues related to theme will be handled in this `next` branch.

`1.0.0-alpha`'s main objective is to make Vite 3 docs site work as a benchmark. Any feature request or issues which is not directly related to Vite 3 docs will be handled in `1.0.0` milestone.

We hope to release `1.0.0-alpha` sometime soon so that users can try out the new theme. Here is the [discussion thread in Vite](https://github.com/vitejs/vite/discussions/8262) describing whole todos.

See all the list of issues stacking up at:

`1.0.0-alpha`: https://github.com/vuejs/vitepress/projects/1
`1.0.0`: https://github.com/vuejs/vitepress/milestone/1

**Comment by LinusBorg** [comment]
>We've started the **bland** new default theme 

PSA: Don't worry, it's not going to be bland - it's brand-new, and shaping up to be amazing!

**Comment by kiaking** [comment]
Alpha is out, so I'll be closing this issue 🎉
