### ISSUE TITLE
Add internationalization feature

### ISSUE THREAD

**Issue by kiaking** [vuejs/vitepress#631]
related https://github.com/vuejs/vitepress/issues/628

VitePress Next don't have this feature yet. Let's implement it. While doing so, I would also like to suggest new config structure for `locales` option.

Currently, we must define two `locales` when defining multi locale site. One in app config level, and one in theme config level.

I think it's much easier to just be able to define locale on top level only.

```js
export default {
  // Top level config for default and fallbacks.
  lang: 'en',
  title: 'VitePress',
  themeConfig: { ... }
  
  // All other locale settings.
  locales: {
    fr: {
      lang: 'fr',
      title: 'VitePress',
      themeConfig: { ... }
    },

    ja: {
      lang: 'ja',
      title: 'VitePress',
      themeConfig: { ... }
    }
  }
}
```

This should make typings much simpler too (maybe). It should eliminate weird situation like in #628 🤔 

Also, maybe not required for 1.0.0 release, but consider #291 as well.

**Comment by xfq** [comment]
FWIW, W3C has a [Developing Localizable Manifests document](https://www.w3.org/TR/localizable-manifests/) (since `.vitepress/config.js` is also a manifest file).

**Comment by brc-dd** [comment]
Let's also track #902 here.

**Comment by fvsch** [comment]
Is the intent for RTL layouts to use CSS logical properties?
I could work on that for the default theme, if that helps.

**Comment by trincadev** [comment]
I think this issue is related to https://github.com/vuejs/vitepress/issues/41

**Comment by Zhengqbbb** [comment]
@brc-dd I'm ready use the test package `vitepress@npm:@brc-dd/vitepress@next` in my website to support i18n. Thx u great work
And I noticed

> Don't override themeConfig.algolia and themeConfig.carbonAds at locale-level.

That I have a question, **Have some way to configure algolia search to support i18n**
my config: [en](https://github.com/Zhengqbbb/cz-git/blob/dd976879fb7787f74d7719f35690369a1b8d13a8/docs/.vitepress/config/en.ts#L16-L23) | [zh](https://github.com/Zhengqbbb/cz-git/blob/dd976879fb7787f74d7719f35690369a1b8d13a8/docs/.vitepress/config/zh.ts#L16-L25)
preview link: https://deploy-preview-80--cz-git.netlify.app/zh/
You can try search, it disappeared after I clicked it, sure my console should be warn it if it not support.

**Comment by brc-dd** [comment]
@Zhengqbbb Yeah the Algolia part is not properly implemented yet.

@trincadev Actually this issue is for v1 (alpha, formerly next), and that issue was for v0 (yeah v0 had i18n support).

**Comment by lmtr0** [comment]
Hi there, whats the implementation status of this issue? is there a branch I can try out with the most advance features?
