### ISSUE TITLE
[next] Hide title if logo is specified

### ISSUE THREAD

**Issue by sifferhans** [vuejs/vitepress#637]
### Is your feature request related to a problem? Please describe.

I want to use a logo for my documentation site, but when I add a logo in the config file, the page title is pushed to the side of the logo. I am using the `next-theme`, which I know isn't finished :)

See the image below.

![image](https://user-images.githubusercontent.com/18753964/169671366-2dc6dfcd-a18f-4cac-abb4-a1abf0d089ae.png)

### Describe the solution you'd like

It would be nice to hide the title in the header if there is a logo specified - or at least have the option to hide it.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
We should definitely have this feature 👍

**Comment by kiaking** [comment]
Done!
