### ISSUE TITLE
Support multi-line indented vue codes in markdown files

### ISSUE THREAD

**Issue by hyp530** [vuejs/vitepress#638]
### Is your feature request related to a problem? Please describe.

This works in Vuepress@Next, but doesn't work in VitePress (treated as an **Indented Code Block**):

```html
<a-collapse>
    <a-collapse-item>
        <div> Content </div>
    </a-collapse-item>
</a-collapse>
```

This works in the current version of VitePress :

```html
<a-collapse>
<a-collapse-item>
<div> Content </div>
</a-collapse-item>
</a-collapse>
```

### Describe the solution you'd like

Suggests to support: (i) multi-line indented vue codes in vitepress, (ii) provide an option in confit.ts to disable **Indented Code Blocks**, which would trigger lots of troubles in a markdown file. 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Seems like we can't have 4 indent. So this also works.

```html
<a-collapse>
  <a-collapse-item>
  <div> Content </div>
  </a-collapse-item>
</a-collapse>
```

When ever we have more than 4 spaces, it gets treated as code block by markdown parser 👀  Not sure how to fix it but we should.

**Comment by brc-dd** [comment]
Is this present on the next-theme branch? I am not able to reproduce this:

![image](https://user-images.githubusercontent.com/40380293/170556481-6e9ee897-2410-42b8-add4-da385d36a65f.png)

**Comment by brc-dd** [comment]
These changes need to be made at `src\node\markdown\plugins\component.ts` in order to fix this.

https://github.com/vuepress/vuepress-next/blob/f91651c3c7248fdabfa19cb9bdcdba4c28622eec/packages/@vuepress/markdown/src/plugins/customComponentPlugin/htmlBlockRule.ts#L17-L30

**Comment by kiaking** [comment]
Well done! Thank you so much @brc-dd

**Comment by meteorlxy** [comment]
I propose to extract the markdown package / plugins to a standalone project, so that we don't need to fork the code like this 🤣 

I'd say I've fixed lots of markdown rendering issues like this one when development vuepress-next, and add lots of unit tests for those fixes.
