### ISSUE TITLE
build done, but process still alive

### ISSUE THREAD

**Issue by cn-ia** [vuejs/vitepress#64]
**Describe the bug**
My personal simple project uses `vitepress build` in CI environment.
The build process should exit after build done, but my build-job seems never finish.

**To Reproduce**
Execute `vitepress build`

**Expected behavior**
The process should exit after built successfully.

**System Info**
- vitepress version: v0.5.0
- vite version: v1.0.0-rc.4
- Node version: v12.16.2
- OS version: Windows 10

**Additional context**
If I modify "node_modules\vitepress\dist\node\build\build.js", it works:
```js
async function build(buildOptions = {}) {
    // ...
    console.log('done.');
    // Make the build process exit.
    process.exit(0);
}
exports.build = build;
```

**Comment by cn-ia** [comment]
Workaround? `(npm run build &) && sleep 30`

**Comment by x1B** [comment]
I see the same behavior on macOS / Node 14 by just following the `README.md` instructions.
Vitepress `0.3.1` seems to be the last release where `npx vitepress build` exits after rendering pages.
So I suspect that the bug (assuming it is one) was introduced with commit a7db9a7 (vite update).

**Comment by cn-ia** [comment]
@x1B Thanks guy.

This may be a problem with vite builds.

I explored the code-execute-path in my workspace (and debug and comment some dist-code in node_modules/).

I mofified the local file "node_modules\.pnpm\vite@1.0.0-rc.4\node_modules\vite\dist\node\esbuildService.js", and it seems work:
```js
// lazy start the service
//// A singleton?
let _service;

//// In debug mode, the `ensureService()` invoked multiple times, 
//// but the other invoke `startService()` again since `_service` still be `undefined`. 
//// Concurrent?
let _serviceList = []; 
const ensureService = async () => {
    if (!_service) {
        _service = await esbuild_1.startService();
        _serviceList.push(_service);
    }
    return _service;
};
exports.stopService = () => {
    //// Stop all the other collected service (Cause by some forked child process that serving the transform service?)
    _serviceList.forEach(o => o !== _service && o.stop());
    _serviceList.splice(0, _serviceList.length);

    _service && _service.stop();
    _service = undefined;
};
```

code-execution-path:
- node_modules\vitepress\bin\vitepress.js (line 28: `.build(argv)`)
- node_modules\vitepress\dist\node\build\build.js (line 24: `await bundle_1.bundle(siteConfig, buildOptions);`)
- node_modules\vitepress\dist\node\build\bundle.js (line 121: `const clientResult = await vite_1.build(viteOptions);`)
- node_modules\.pnpm\vite@1.0.0-rc.4\node_modules\vite\dist\node\cli.js (line 173: `await require('./build')[options.ssr ? 'ssrBuild' : 'build'](options)`)
- node_modules\.pnpm\vite@1.0.0-rc.4\node_modules\vite\dist\node\build\index.js (line 277: `enableEsbuild` (if comment the plugin, build will exit normally. Intresting...))
- node_modules\.pnpm\vite@1.0.0-rc.4\node_modules\vite\dist\node\build\buildPluginEsbuild.js (line 38: `esbuildService_1.transform`)
- node_modules\.pnpm\vite@1.0.0-rc.4\node_modules\vite\dist\node\esbuildService.js (line 36: `let _service;` (Concurrent?))

Any suggestions or comments are welcome. 😄

**Comment by x1B** [comment]
@cn-ia I think that you described the exact problem 👍. I think it can be solved differently though, by actually making sure that `startService()` is called at most once. I proposed a solution in vitejs/vite#693 and I'll see if I can open a PR.

**Comment by cn-ia** [comment]
This issue will be closed if [vite/issues/693](https://github.com/vitejs/vite/issues/693) PR merged.

**Comment by cn-ia** [comment]
The PR merged.

**Comment by cn-ia** [comment]
The PR merged.

**Comment by cn-ia** [comment]
The PR merged.

**Comment by saxon-y** [comment]
This bug appear again in version 0.21.6
<img width="156" alt="Snipaste_2022-03-01_15-12-19" src="https://user-images.githubusercontent.com/49136621/156122153-faaacbc3-4837-4b4f-abfb-3ba0832d4024.png">

**Comment by cn-ia** [comment]
> This bug appear again in version 0.21.6 <img alt="Snipaste_2022-03-01_15-12-19" width="156" src="https://user-images.githubusercontent.com/49136621/156122153-faaacbc3-4837-4b4f-abfb-3ba0832d4024.png">

No hang in my environment.
```txt
vitepress v0.21.6
✓ building client + server bundles...
✓ rendering pages...
build complete in 3.25s.
```

**Comment by saxon-y** [comment]
But it definitely happened, I guess it has something to do with some library I'm referencing.

**Comment by saxon-y** [comment]
If there is a vue single-file component in the project, it will cause this problem. After I remove all the vue single-file components, the build is normal.

**Comment by cn-ia** [comment]
Try the latest version `release: v0.22.3`, if still not work for u, show the smallest insensitive `vue single-file component`, I will have a try in my env in free time. Or create an issue about it.

**Comment by saxon-y** [comment]
ok, i will create an additional.
