### ISSUE TITLE
[next] Add Collapsable feature to SidebarGroup

### ISSUE THREAD

**Issue by hyp530** [vuejs/vitepress#640]
### Is your feature request related to a problem? Please describe.

User experience is bad when I have too many SidebarGroups.  The Collapsable feature of SidebarGroup (similar to VuePress@Next) would be very necessary, which should be quite commonly required.

### Describe the solution you'd like

I understand VitePress might intend to provide a mininal default theme, rather than create another vuepress.  But still, I would strongly recommend you to add this feature.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Thanks for bringing it up! Yes, this is included in the plan 👍

**Comment by kiaking** [comment]
Done!
