### ISSUE TITLE
Create button.md file, controller warning

### ISSUE THREAD

**Issue by zguiyang** [vuejs/vitepress#650]
### Describe the bug

1. Create a Component folder in the ' 'docs'' directory and create a button.md folder inside
2. Run the ' 'dev' command, and a warning letter appears on the console

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/24975063/170007529-62d50e31-5e28-4f8f-905a-43313c5f4aa0.png">

<img width="2238" alt="image" src="https://user-images.githubusercontent.com/24975063/170007720-28deaec3-b623-4774-90ad-d5d72fe351ac.png">

### Reproduction

1. Create a Component folder in the ' 'docs'' directory and create a button.md folder inside
2. Run the ' 'dev' command, and a warning letter appears on the console

### Expected behavior

The console has no warning information

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 257.09 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    npm: 8.9.0 - ~/.nvm/versions/node/v14.19.2/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0.1
    Safari: 15.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
I can't reproduce this. Maybe it has something to do with the content of `button.md`? Could you delete all content from `button.md` and try again?

**Comment by zguiyang** [comment]
> I can't reproduce this. Maybe it has something to do with the content of `button.md`? Could you delete all content from `button.md` and try again?

Sorry, I tested it again and it doesn't seem to be vitepress
