### ISSUE TITLE
Markdown gets compiled to component without `.md` prefix when using `<script setup>`

### ISSUE THREAD

**Issue by zguiyang** [vuejs/vitepress#657]
### Describe the bug

Creating a ``<script setup></script>`` in a Markdown file and writing anything to the ``<script setup> xxx </script>`` caused component rendering problems

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/24975063/170244719-112330e7-70e2-4de6-819f-2ed3b1aa7ec6.png">

The preview page found that the``.md`` suffix was missing when Markdown was rendered as a ``VUE component``
<img width="2027" alt="image" src="https://user-images.githubusercontent.com/24975063/170251437-b83d1af2-ef04-4be8-8338-82ad7c293eae.png">

If I change the code to be

````
---
title: Button
---

# Button

Commonly used button.

## Basic usage

:::demo Use `type`, `plain`, `round` and `circle` to define Button's style.

button/basic

:::

## Disabled Button

:::demo Use `disabled` attribute to determine whether a button is disabled. It accepts a `Boolean` value.

button/size

:::


````

or

````
---
title: Button
---

# Button

Commonly used button.

 const demos = import.meta.globEager('../examples/button/*.vue')

<script setup>


</script>

## Basic usage

:::demo Use `type`, `plain`, `round` and `circle` to define Button's style.

button/basic

:::

## Disabled Button

:::demo Use `disabled` attribute to determine whether a button is disabled. It accepts a `Boolean` value.

button/size

:::

````

Render normal

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/24975063/170251822-78f1056c-536c-416b-af0c-d1b0c538bc24.png">

### Reproduction

1. Initialize a Vuepress project
2. Create a markdown file in the docs directory
3. Write the Script label in the document. The content of the label cannot be empty
4. The ``.md `` suffix is missing when rendering vue components

### Expected behavior

The component renders normally with a script in markdown
``button.md`` should be rendered as ``<Button.md>`` vue component

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 1.38 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    npm: 8.9.0 - ~/.nvm/versions/node/v14.19.2/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0.1
    Safari: 15.4
  npmPackages:
    vitepress: 0.22.3 => 0.22.3
```

### Additional context

The ``.md `` suffix is missing, warning appears on the console

<img width="792" alt="image" src="https://user-images.githubusercontent.com/24975063/170254126-9bd532c7-ab1c-44bd-9ab9-19122e21d25e.png">

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
I can't reproduce this. PLease provide reproduction repo 👍

**Comment by zguiyang** [comment]
> I can't reproduce this. PLease provide reproduction repo 👍

After initializing a project, add 

````
<script setup>
console.log ( 123456 )
</script>
````

 to index.md in the docs directory

Run the ``vitepress dev docs`` command
 index.md is rendered as a Vue component named``<Index>``
A VUE component named ``<Index.md>`` should be expected

My replay code is:  [demo](https://github.com/zguiyang/vitepress-test-demo)

**Comment by kiaking** [comment]
Oh OK now I see. yeah this might be unexpected, but do you have any issues with it? The page it working fine. Why is't bad `<Index.md>` being `<Index>`? What is "caused component rendering problems" for you?

**Comment by zguiyang** [comment]
> Oh OK now I see. yeah this might be unexpected, but do you have any issues with it? The page is working fine. Why is it bad `<Index.md>` being `<Index>`? What is "caused component rendering problems" for you?

The reason I think it's a rendering problem is:

If my file was named ``button.md``, it would logically render as ``<Button>``, which would cause a warning on the console, and to avoid this warning, it would seem to render as <Button.md >

warning log:
````
[Vue warn]: Do not use built-in or reserved HTML elements as component id: button 
 at <Button> 
 at <VitePressContent class="content" > 
 at <Page key=3 > 
 at <Layout> 
 at <VitePressApp>
 
````

My careful testing revealed that the problem was caused by the addition of the ``setup`` tag to the``script`` tag

If this is not a bug, can you optimize the presentation of this warning message or the rendering name of the component?

**Comment by kiaking** [comment]
OK finally understood. That make sense, and I can imagine that becoming an issue since I'm pretty much sure people would create file name like `button.md` 😅  Let's fix this before 1.0.0 👍

**Comment by zguiyang** [comment]
> OK finally understood. That make sense, and I can imagine that becoming an issue since I'm pretty much sure people would create file name like `button.md` 😅 Let's fix this before 1.0.0 👍

nice 👍 👍👍

**Comment by brc-dd** [comment]
Strange enough, but this is not happening if I am locally linking VitePress. It happens only if I use the published version.

Using local version (first) vs using registry version (second):

![image](https://user-images.githubusercontent.com/40380293/170868537-b3a791ce-1bbf-4013-9849-ac2083606dd6.png)![image](https://user-images.githubusercontent.com/40380293/170868588-ff7b0bc5-9468-44a1-b74c-73643e67dda3.png)

**Comment by kiaking** [comment]
Done!
