### ISSUE TITLE
Add an option to disable `markdown-it-attrs` plugin

### ISSUE THREAD

**Issue by kiaking** [vuejs/vitepress#662]
See #629

```js
export default {
  markdown: {
    // Pass `false` to disable this plugin.
    attrs: false
  }
}
```

**Comment by atian25** [comment]
should we also support to enable/disable it by frontmatter ?

**Comment by kiaking** [comment]
No, I don't think so. This option should be enabled by default and if someone wants to turn off, that mean they have some trouble with it like in #629.

By enabling/disabling on per page bases, I think that's just gonna bring in more troubles the authors 😅

**Comment by kiaking** [comment]
Done!
