### ISSUE TITLE
md 文件引入vue失败

### ISSUE THREAD

**Issue by meikang123** [vuejs/vitepress#667]
### Describe the bug

![image](https://user-images.githubusercontent.com/16129828/170627730-210d55a9-7159-40a6-9bd5-d6c6ff461c4e.png)
![image](https://user-images.githubusercontent.com/16129828/170627782-3ae8ec1d-628a-4460-ae95-24d15e38a089.png)

### Reproduction

引入外部资源

### Expected behavior

起作用

### System Info

```shell
...
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
You can't use `lang="ts"` inside markdown file. Remove it and it should work fine 👍

**Comment by meikang123** [comment]
> You can't use `lang="ts"` inside markdown file. Remove it and it should work fine 👍

关闭了也是不行的  我都有尝试了
