### ISSUE TITLE
LastUpdated display 'en' time when default lang is 'zh-CN'

### ISSUE THREAD

**Issue by CNMathon** [vuejs/vitepress#668]
### Describe the bug

LastUpdated display 'en' time when default lang is 'zh-CN'.

Just like this
![image](https://user-images.githubusercontent.com/44454223/170663464-62ddc0cd-9cd5-4248-b3fe-36ca2631bf49.png)

### Reproduction

1. config `.vitepress/config.ts` like this.
```ts
import { defineConfig } from 'vitepress'

export default defineConfig({
  lang: 'zh-CN',
  base: '/docs/',
  lastUpdated: true,
  themeConfig: {
    docsBranch: 'master',
    lastUpdated: '最后更新时间',
  }, 
})
```
2. Run `yarn build:docs`.

### Expected behavior

Expected to show `2022-5-27 16:06:35`.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.02 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/.npm-global/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 94.0.1
    Safari: 15.5
  npmPackages:
    vitepress: ^0.22.4 => 0.22.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Let's make this configuarable 👍

**Comment by brc-dd** [comment]
@kiaking There is already a PR #642 regarding this, but it targets `main` branch.

**Comment by kiaking** [comment]
@brc-dd Thanks! Hmmm... sad to say but I think we have drop that PR. We're planning to release 1.0.0-alpha pretty soon. But, good to have PR that shows how to fix the issue, so when implementing this feature to "Next", let's come back here 👍

**Comment by brc-dd** [comment]
Ah I didn't noticed there is no last updated in next theme.

**Comment by kiaking** [comment]
Done!

**Comment by CNMathon** [comment]
@kiaking How soon is this feature expected to be released?

**Comment by brc-dd** [comment]
@CNMathon 2-3 days.

**Comment by CNMathon** [comment]
> @CNMathon 2-3 days.

@brc-dd OK, Thanks~
