### ISSUE TITLE
[next] add Last Updated feature

### ISSUE THREAD

**Issue by kiaking** [vuejs/vitepress#669]
We don't have this yet in `next-theme`, and we should.

Keep in mind:

- https://github.com/vuejs/vitepress/issues/668

**Comment by stafyniaksacha** [comment]
Do you plan to have a page that contains recently updated content?

**Comment by kiaking** [comment]
Probably not in 1.0.0. But that's cool feature to have man 👍

**Comment by kiaking** [comment]
Done!
