### ISSUE TITLE
Cannot use <script setup lang="ts"> in markdown file

### ISSUE THREAD

**Issue by olivervorasai** [vuejs/vitepress#693]
### Describe the bug

Using script setup with `lang="ts"` causes  `[plugin:vite:vue] [@vue/compiler-sfc] <script> and <script setup> must have the same language type.` error. The error does not occur if `lang="ts"` is removed.

https://github.com/vuejs/vitepress/issues/575 is the same issue except a reproduction is included in this issue.

### Reproduction

Minimal reproduction available here: https://github.com/olivervorasai/vitepress-starter-ts-bug

1. `npm install`
2. `npm run docs:dev`

This reproduction was creating using the following documentation:
- https://vitepress.vuejs.org/guide/getting-started.html#step-1-create-a-new-project
- https://vitepress.vuejs.org/guide/using-vue.html#using-components

### Expected behavior

Vitepress should render with or without `lang="ts"`.

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 9.27 GB / 15.85 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.1 => 1.0.0-alpha.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kecrily** [comment]
See https://github.com/vuejs/vitepress/issues/667#issuecomment-1140420881

**Comment by brc-dd** [comment]
As stated by the error: `<script> and <script setup> must have the same language type`. We inject a `<script>` block by default to each md file. But since not everyone uses TS, it doesn't has `lang` set to `ts`.

As a workaround, add empty `<script>` block with `lang="ts"` to your :

```vue
<script lang="ts"></script>
```
