### ISSUE TITLE
[next] support external for editlink

### ISSUE THREAD

**Issue by RainKolwa** [vuejs/vitepress#694]
### Is your feature request related to a problem? Please describe.

My project is hosted on [GitLab](gitlab.com), so I configured editLink as below:

```js
editLink: {
    repo: 'https://gitlab.com/foo/bar',
    branch: 'main',
    dir: 'docs',
    text: '在 GitLab 上编辑此页',
}
```

but the editlink turned out to be `https://github.com/https://gitlab.com/foo/bar/docs/edit/main/docs/application/management.md`

### Describe the solution you'd like

I noticed before `v1.0.0`, we have a `isExternal` function to tell if use `github.com` or `repo` config directly as base url.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Except for leading `https://github.com/`, that URL is fine right? Or do GitLab's edit links look different?

**Comment by RainKolwa** [comment]
Yes, except for the leading the URL is fine.

**Comment by alexeyvokin** [comment]
I was also surprised that this functionality has degraded

**Comment by kiaking** [comment]
@brc-dd @kecrily This is kinda getting complicated 😅 Before we were using this info to display GitHub social link logo on Nav bar as well, so it made sense to have these small options. But now, this option is really only used for this edit link. So, how about we make config simpler?

```ts
editLink: {
  path: 'https://github.com/vuejs/vitepress/edit/next/docs/{:path}',
  text: '在 GitLab 上编辑此页',
}
```

The `{:path}` gets replaced with the file path. All other stuff like repo, branch, dir just go into the static url string. Straight forward and user may configure it freely.

What do you think?

**Comment by brc-dd** [comment]
@kiaking Seems right. In pattern we are simply replacing `:repo`, `:branch` and `:path`. Since repo and branch aren't being used anywhere else, there is no need for us to inject them in pattern. Users can specify them directly in pattern.

**Comment by kecrily** [comment]
If we won't be reusing these options elsewhere, then let's drop the baggage and simply get on with it.
