### ISSUE TITLE
Docs content style error when use container as folder name

### ISSUE THREAD

**Issue by RainKolwa** [vuejs/vitepress#696]
### Describe the bug

I created a folder named `container` inside `docs`, then I found that everything aligns center on docs under this directory.

https://github.com/vuejs/vitepress/blob/0927a7393b3b484d49a2d06d5b41073b40cec244/src/client/theme-default/components/VPDoc.vue#L38

https://github.com/vuejs/vitepress/blob/0927a7393b3b484d49a2d06d5b41073b40cec244/src/client/theme-default/components/VPDoc.vue#L81-L84

### Reproduction

Create a folder named `container` under `docs`, and create one page under it.

### Expected behavior

Style not been affected.

### System Info

```shell
No need.
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kecrily** [comment]
I don't understand what you mean

**Comment by brc-dd** [comment]
> I don't understand what you mean

@kecrily Try creating a directory named `container` and place some file (`foo.md`) inside that. The content of `container/foo` is getting misaligned.

**Comment by brc-dd** [comment]
Okay got it:

Clone this repo: https://github.com/brc-dd/vitepress-container-bug and open /foo or /container/foo.
