### ISSUE TITLE
[Default Theme] Style: Change font-size of navbar menu item from 13px to 14px

### ISSUE THREAD

**Issue by hyp530** [vuejs/vitepress#708]
### Describe the bug

Normal font-size of nav item is 14px in vitepress. 
However, the fontsize of a nav item with child items is 13px,.

### Reproduction

None.

### Expected behavior

 Change font-size of the navbar menu item from 13px to 14px.

### System Info

```shell
None.
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
The line height also appears to be different. Thanks we'll look into that.
