### ISSUE TITLE
Can the author add the function of packaging component library in vite? | 作者大大能否在vite中增加封装组件库的功能？

### ISSUE THREAD

**Issue by misitebao** [vuejs/vitepress#71]
**Is your feature request related to a problem? Please describe.**

- At present, a component library is being developed. The component packaging scheme used is the package function of Vue cli. Since webpack is used, the packaged files will be relatively large and have been used by rollup. Therefore, I want to use rollup to package and use Vue cli to write sample documents. However, the package code and examples will be divided into two sets, which is very troublesome. I would like to make two To merge together, that is, to complete these two operations directly in vite.

- 目前，正在开发一个组件库。使用的组件打包方案是Vue cli的打包功能。由于使用了webpack，打包的文件将相对较大，并且已被rollup使用。因此，我希望使用rollup打包并使用Vue cli编写示例文档。但是，软件包的代码和示例会被分成两套，这很麻烦。我想把两个合并在一起，也就是说，直接在vite中完成这两个操作。

**Describe the solution you'd like**
- I want to complete the package of component library and the writing of component examples in vite. 
- 我想在vite中完成组件库的打包和组件实例的编写。

**Describe alternatives you've considered**
- The combination scheme of rollup + Vue cli has been considered 
- 考虑了rollup+Vue-cli的组合方案

**Additional context**
- None 
- 无

**Comment by xxholly32** [comment]
https://github.com/xxholly32/vue-general-components

vue 2我有做封装，vue3很多东西还不稳定，不过我也在尝试做类似的工具
