### ISSUE TITLE
use algolia button text from theme config

### ISSUE THREAD

**Issue by RainKolwa** [vuejs/vitepress#713]
### Describe the bug

If I configured algolia translation in `theme config` like:
```json
{
  "themeConfig": {
    "algolia": {
      "translations": {
        "button": {
          "buttonText": "搜索",
          "buttonAriaLabel": "搜索"
        }
      }
    }
  }
}
```
When I click the search button, the text of the button changes.

### Reproduction

-

### Expected behavior

https://github.com/vuejs/vitepress/blob/31c863d14c42eba06881964b81fe1806505d6157/src/client/theme-default/components/VPNavBarSearch.vue#L79

It would be nice if the text in search box could be using the text from `theme config`.

### System Info

```shell
-
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
We should have this! But not sure about the option structure. So I guess Algolia already has that option 👀 But we're not using Algolia Dom structure directly, due to design differences. So I think we could have simpler option for VitePress. Maybe:

```js
algolia: {
  appId: '...',
  apiKey: '...',
  indexName: '...',
  buttonText: '搜索'
}
```

**Comment by RainKolwa** [comment]
I noticed that we used `theme.algolia` to initialize the search box, maybe it's better to respect the origin config from [algolia](https://docsearch.algolia.com/docs/api#translations). Otherwise, we have to config the text twice.

https://github.com/vuejs/vitepress/blob/721fa364eae3ca6b2ac38ce2850d1594e5e8c32f/src/client/theme-default/components/VPAlgoliaSearchBox.vue#L36
