### ISSUE TITLE
Allow custom title link

### ISSUE THREAD

**Issue by webigorkiev** [vuejs/vitepress#717]
### Describe the solution you'd like

In some cases, you need to change the link from the header.
Additionally base should affect title.

Thanks

**Comment by brc-dd** [comment]
> Additionally base should affect title.

Fixed this in #718.

**Comment by webigorkiev** [comment]
Thanks
For example, if I want to link to another domain. For example, to the main page of the project, and not to the main page of the documentation.

**Comment by brc-dd** [comment]
Okay, for now I would recommend using a link on navbar instead. [Refer this.](https://vitepress.vuejs.org/guide/theme-nav.html#navigation-links) We will see if this feature request gains more interest

**Comment by webigorkiev** [comment]
Yes, it is possible.
I think the issue can be closed.
