### ISSUE TITLE
[Vite Config] Support ssr.noExternal

### ISSUE THREAD

**Issue by hyp530** [vuejs/vitepress#720]
### Describe the bug

1. Failed to import arco design on demand with [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components/issues/411). 

2. In Vuepress@Next, [ssr.noExternal](https://v2.vuepress.vuejs.org/reference/bundler/vite.html#ssr-externals-issue) is supported, and I can import arco design on demand with unplugin-vue-components.

3. In vitepress,  I tried but failed with the following vite config:

``` ts
import { defineConfig } from 'vitepress'
import Components from 'unplugin-vue-components/vite';
import { ArcoResolver } from 'unplugin-vue-components/resolvers';

export default defineConfig({
    base: '/',
    title: 'VPTest',
    vite: {
        plugins: [
            Components({
                resolvers: [
                    ArcoResolver()
                ]
            })
        ],
     ssr:{
        noExternal: ['@arco-design/web-vue'],
      }
    },
})
```

### Reproduction

Reproduction: https://github.com/hyp530/vitepressTest

### Expected behavior

To support vite config - ssr.noExternal and the import of arco design on demand.

### System Info

```shell
N/A
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kecrily** [comment]
I actually feel that vitepress can have unplugin-vue-components builtin. Let's see what the maintainers think

**Comment by brc-dd** [comment]
It is working for me: https://github.com/brc-dd/vitepress-with-acro 👀
