### ISSUE TITLE
Support code groups and allow adding title to code blocks

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/vitepress#728]
### Is your feature request related to a problem? Please describe.

VueJS community is moving from JS to TS now. Hence, we have to provide both TS & JS code.

I already started using VitePress alpha in my OSS project but for another project, I prefer providing TS & JS code via code groups like VuePress.

### Describe the solution you'd like

Provide code blocks via markdown (using component is bit ugly for markdown only content). We can inspire from Nuxt content 2 for new syntax

<pre>
:::code group

:::group{ts}

```ts
const a: number = 1
```

:::

:::group{js}

```js
const a = 1
```

:::

:::
</pre>

### Describe alternatives you've considered

None

### Additional context

https://content.nuxtjs.org/guide/writing/mdc

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kecrily** [comment]
Maybe it could be simpler?

~~~markdown
:::code group
```ts
const a: number = 1
```

```js
const a = 1
```
:::
~~~

**Comment by brc-dd** [comment]
@kecrily I guess the OP meant to have title of each group too. `:::group{foo}` --> title is `foo`.

**Comment by kecrily** [comment]
We can custom group title in code block 

~~~markdown
```ts [TypeScript]
const a: number = 1
```
~~~

**Comment by Zhengqbbb** [comment]
Looking forward this feature, which will have a different experience with such code experience:
![image](https://user-images.githubusercontent.com/40693636/172436242-f645ee81-083a-4c68-a5eb-90b94e4fc2c8.png)

**Comment by marshallswain** [comment]
Can we expose the markdown-it rendered to be used inside of Tab components?  It would be really nice to be able to use Vue components to render tab groups:

```
<Tabs>
  <Tab name="TypeScript">
    ``ts
    nested fenced code block here.
    ``
  </Tab>
  <Tab name="JavaScript">
  ``js
    nested fenced code block here.
  ``
  </Tab>
</Tabs>
```

**Comment by brc-dd** [comment]
@marshallswain Sorry, I didn't get you. You can still do what you've wrote. You need to add spaces before and after the fences in this. HTML (or Vue in this case) should be separated by Markdown using empty lines.

**Comment by marshallswain** [comment]
@brc-dd wow!  I can't believe it was that simple.  I just needed the extra line breaks and it now works as expected.  Thank you!

**Comment by brc-dd** [comment]
@kecrily This is part of the CommonMark standard actually (https://spec.commonmark.org/0.29/#html-blocks). Anything that follows or is based on that will properly render that.

**Comment by alokVishu** [comment]
I am also building js + ts docs. Code groups will be a great addition to show ts and js code.

**Comment by Sepush** [comment]
I prefer nuxt's solution like the following

UI:
https://v3.nuxtjs.org/guide/directory-structure/layouts#overriding-a-layout-on-a-per-page-basis
![图片](https://user-images.githubusercontent.com/39197136/180391412-8e100e6b-e550-46a7-bbc5-11c5b32e099a.png)

Grammar:
https://github.com/nuxt/framework/blob/d135608ef0d607259c0ae6f5156c8f46ff78ddc3/docs/content/2.guide/3.directory-structure/7.layouts.md?plain=1#L140-L175

**Comment by brc-dd** [comment]
Also track #1027 here. I think we should go with what @kecrily wrote. Its similar to what we have in Nuxt too.

**Comment by VoVAllen** [comment]
Hi, I'm interested in taking this, and have some questions on the implementation. Currently code block's function (line number, highlight, etc.) is based on plugin with mdit and pure DOM operation, which is perfect for the static component. But code group (such as in nuxt doc) is a dynamic component, which seems better to have a SFC for it. What do you think? @brc-dd 

My current thought is to use a simple component wrap over the doc blocks by slot. And use pure dom operation to control the tab change inside. Any suggestion is welcomed since I'm a newbie to vue. Thanks!

Nuxt reference: https://github.com/nuxt/content/blob/v1/packages/theme-docs/src/components/global/base/CodeGroup.vue

**Comment by brc-dd** [comment]
@VoVAllen I don't think highlighting and all needs to be done in the code group component. I was thinking of just having a wrapper component (with some md sugar) that can take multiple code blocks (with titles). Regarding tab change, it can be done using basic refs, there is no need to directly manipulate DOM.

**Comment by VoVAllen** [comment]
@brc-dd Yeah actually this what I thought. I don't want to change the way of highlighting by mdit plugin. My question is whether we need a component(SFC) here or there's a simpler way than SFC. 

Current code blocks are `<code></code>`. My thought for code group is like 
```
<CodeGroup> // This logic is handles by a new SFC

// This is still handled by mdit
<code>
<code/>

<code>
<code/>

</CodeGroup>
```

What do you think?

**Comment by brc-dd** [comment]
@VoVAllen Yeah, that's similar to what others wrote. This is the intended syntax BTW:

````md
:::code-group

```js [JavaScript]
some js stuff
```

```ts [TypeScript]
some ts stuff
```

:::
````

So, if you implement such a component (the one you wrote), then we just need to add some stuff in our markdown component plugin to make it understand `:::code-group`.

**Comment by brc-dd** [comment]
Can you guys review #1560 and see if there are any issues (especially with UI). Here is the deploy preview: https://deploy-preview-1560--vitepress-docs.netlify.app/test

**Comment by jd-solanki** [comment]
Hi @brc-dd 

I am really glad that this is implemented.

UI looks a bit different than what VitePress already provides due to the following:
- white border 
  ![Screenshot 2022-10-31 at 11 35 54 AM](https://user-images.githubusercontent.com/47495003/198942282-15f7e4ca-9057-45b7-929e-cf38e714b2f9.png)

- Removing the hover effect that changes the background color will make it more consistent & minimal like VuePress
![Screenshot 2022-10-31 at 11 37 41 AM](https://user-images.githubusercontent.com/47495003/198942392-e431c629-7db2-4cc8-887a-07fe9ca9aacf.png)

- If we will have only two tabs it will look a bit weird (_header is not taking full width_)
  ![Screenshot 2022-10-31 at 11 40 34 AM](https://user-images.githubusercontent.com/47495003/198942835-ebe458bf-40e6-41ed-a49f-fdba0a9da6bf.png)


In my opinion, VuePress already has an excellent UI, why not reuse it? 🤔
