### ISSUE TITLE
change the config to search instead of algolia!

### ISSUE THREAD

**Issue by botteroxom** [vuejs/vitepress#733]
### Is your feature request related to a problem? Please describe.

While developing offline search I want to use the default config options, so we can add different search providers:

- algolia
- offline
- another one...

### Describe the solution you'd like

make the search option in the config more generic so plugin can still follow a pattern while setting searching parameter for different providers.

### Describe alternatives you've considered

```js
search:{
  algolia:{
  ...
  }
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Yeah I think this is good idea in regards to adding offline search in the future. Maybe it could be like below though.

```js
{
  search: {
    driver: 'algolia'
  },
  
  algolia: {
    ...
  }
}
```
