### ISSUE TITLE
Custom element support

### ISSUE THREAD

**Issue by pearofducks** [vuejs/vitepress#735]
### Is your feature request related to a problem? Please describe.

We're using Custom Elements to encapsulate styles from our design system, so it'd be great to be able to tell Vitepress to ignore those tags.

Super lightweight example:

```js
class ButtonExample extends HTMLElement {
  connectedCallback() {
    const designSystemCSS = '<link rel="stylesheet" type="text/css" href="designSystemURL" />'
    const target = `<div id="app"></div>`
    this.shadow = this.attachShadow({ mode: 'open' })
    this.shadow.innerHTML = designSystemCSS + target
    createApp(App) // App defined elsewhere ofc
      .mount(this.shadow.querySelector('#app'))
  }
}
```

### Describe the solution you'd like

Probably just being able to set `compilerOptions.isCustomElement` somewhere would be good enough?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! It is already supported:

```js
// .vitepress/config.js

import { defineConfig } from 'vitepress'

export default defineConfig({
  vue: {
    template: {
      compilerOptions: {
        isCustomElement: (tag) => tag.includes('-')
      }
    }
  }
})
```

**Comment by pearofducks** [comment]
Awesome, thanks!
