### ISSUE TITLE
Add option to extends social links

### ISSUE THREAD

**Issue by stafyniaksacha** [vuejs/vitepress#738]
### Is your feature request related to a problem? Please describe.

Social networks available are hard coded, so we can not include new one (such as dribble, gitlab, envato, ...)  

```ts
type SocialLinkIcon =
    | 'discord'
    | 'facebook'
    | 'github'
    | 'instagram'
    | 'linkedin'
    | 'slack'
    | 'twitter'
    | 'youtube'
```

### Describe the solution you'd like

That would be great if we can add link with icons from https://icones.js.org/ or from custom component

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We are actually thinking of modifying the interface to allow inline SVGs. Then you'll be able to use any icon you wish.

**Comment by userquin** [comment]
Use UnoCSS preset icons, adding the vite plugin, the preset and akso `@iconify/logos`

**Comment by kiaking** [comment]
I think having able to define inline svg is enough for this feature. Becasue you usually don't have that much of Social icons anyway. having decent default is cool, so I think adding GitLab makes sense for example, but other than that, I think user could just copy paste svg into config.

I really wouldn't want to complicate the system by including another package into build pipeline 👀

**Comment by stafyniaksacha** [comment]
> I think user could just copy paste svg into config.

Sounds good for me
