### ISSUE TITLE
How can I set the base url for 2 different domains.

### ISSUE THREAD

**Issue by Roman-00** [vuejs/vitepress#750]
### Discussed in https://github.com/vuejs/vitepress/discussions/749

<div type='discussions-op-text'>

<sup>Originally posted by **Roman-00** June  8, 2022</sup>
example https://roman.kz/ms/guide / - set the base path /ms/guide/, and for the domain https://roman.kz - set the base path /</div>

Is it possible to use prod dev mode

**Comment by Roman-00** [comment]
Tell me how to organize it in vitapress?

**Comment by Roman-00** [comment]
> You'll have to build it twice. Maybe you can use an environment variable to set the base?

Tell me how to organize it in vitepress?

**Comment by brc-dd** [comment]
@Roman-00 You can write scripts like this in your package.json:

```json
"build": "shx rm -rf dist/docs && shx mkdir -p dist && pnpm build:main && pnpm build:foo",
"build:main": "vitepress build docs && shx cp -r docs/.vitepress/dist dist/docs",
"build:foo": "BASE='/foo/' vitepress build docs && shx cp -r docs/.vitepress/dist dist/docs/foo",
"serve": "serve dist/docs"
```

And in your VitePress config, set base to `process.env.base || '/'`.
