### ISSUE TITLE
Click logo title area returns to '/', this is not my config 'base' value

### ISSUE THREAD

**Issue by WanderQing** [vuejs/vitepress#753]
### Describe the bug

When I click the logo title area, URL routes to '/', is not my config base property value!

### Reproduction

1. config base value in config file
2. click logo title area

### Expected behavior

Routes to my config file's 'base' value

### System Info

```shell
1. URL routes to '/'
2. 404 not found
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
fixed in #718
