### ISSUE TITLE
Custom highlight

### ISSUE THREAD

**Issue by zRains** [vuejs/vitepress#754]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

If the highlight function is passed in `options: MarkdownOptions`, this function will be invoked, otherwise the default will be used.

```ts
 const md = MarkdownIt({ 
   html: true, 
   linkify: true, 
   highlight: options.highlight || await highlight(options.theme), 
   ...options 
 }) as MarkdownRenderer 
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Yeah why not. I think this can be useful, and simple to implement. If anyone wants to tackle this, PR is welcome!
