### ISSUE TITLE
Provide text entry for `VPDocFooter`

### ISSUE THREAD

**Issue by userquin** [vuejs/vitepress#758]
### Is your feature request related to a problem? Please describe.

When the text on the link is contextual there is no way to include an alternative text to be shown on next/prev footer.

### Describe the solution you'd like

Add an optional text entry on `SidebarItem` and use it on `VPDocFooter` if configured.

### Additional context

We have a `Getting Started` on each group:

![imagen](https://user-images.githubusercontent.com/6311119/172729181-c24f6acc-022e-47ca-9099-5d5c98e63b17.png)

<br/>

Here you can check the text is not in context (the next entry should be `Getting Started | Frameworks`):

![imagen](https://user-images.githubusercontent.com/6311119/172729292-f6468f17-fb7b-468b-9cf1-c9f308bed437.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
I like the idea. For design, I think we can learn from this 👀 
https://docs.gitbook.com/spaces/what-is-a-space

**Comment by kecrily** [comment]
A late rendering. I think this is a bit more visible than the gitbook one

![image](https://user-images.githubusercontent.com/45708948/174067720-cfb3cd85-5d40-4cfe-816d-a460b238fa17.png)

**Comment by userquin** [comment]
@kiaking @kecrily I configure the title this way `Title | Section` on frontmatter section (like on the last screenshow), maybe you can access to it and use it on the next/prev links, if possible: just add also a hint  on the docs.

Just check this https://raw.githubusercontent.com/antfu/vite-plugin-pwa/userquin/feat-new-theme/docs/guide/index.md (any other page is configured this way on pwa repo)
