### ISSUE TITLE
Proper italic/cursive rendering

### ISSUE THREAD

**Issue by HipyCas** [vuejs/vitepress#759]
### Describe the bug

As of now, if you format text as italic/cursive (with either `_` or `*`) it gets transpiled to HTML as an `<em>` element, instead of `<i>`. This works in chromium-based browser (as far as I've seen), but for example doesn't show as italic in the latest Firefox versions.

### Reproduction

In a Markdown file, wrap any text in a single `_` or `*` (make it cursive), compile and search that text in the page with Firefox.

### Expected behavior

Render it to an `<i>` tag so it is properly formatted in both Chromium-based and Gecko-based (Firefox & others). Alternatively, a CSS could be included by default that formats `<em>` as italic/cursive.

### System Info

```shell
System:
  OS: Linux 5.15 Pop!_OS 21.04
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Memory: 5.75 GB / 15.48 GB
  Container: Yes
  Shell: 5.1.4 - /bin/bash
Binaries:
  Node: 16.4.1 - ~/.nvm/versions/node/v16.4.1/bin/node
  npm: 8.9.0 - ~/.nvm/versions/node/v16.4.1/bin/npm
Browsers:
  Chromium: 102.0.5005.61
  Firefox: 96.0
npmPackages:
  vitepress: ^1.0.0-alpha.1 => 1.0.0-alpha.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! This is a part of the [CommonMark Spec](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis). We cannot change the standards. Moreover `_` or `*` are not meant for italics, they are for emphasis (although mostly browsers style the content as italics). (Also `<i>` doesn't mean italics.) Quoting [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em#i_vs._em):

> This means the right one to use depends on the situation. **Neither is for purely decorative purposes, that's what CSS styling is for.**

Use custom CSS if you think you want italics for every `<em>`. Moreover, I have the latest Firefox (102.0b5) and the rendering is fine.

**Comment by brc-dd** [comment]
Okay, so this issue is not due to different CSS engine in Firefox. Our italics font is not loading there. Just for test, try setting a different font on `em`, it will be italics there too. We will fix this. Thanks for report.
