### ISSUE TITLE
Main title link not considering base option

### ISSUE THREAD

**Issue by emersonbottero** [vuejs/vitepress#761]
### Describe the bug

while setting an base in 

```js
//.vitepress/config.js
module.exports = {
  title: "ServiceNow.Core",
  description: "Your easy to use REST API integration library",
  base: "/ServiceNow.Core/",
  ...
```

expected to reflect in layout home link

### Reproduction

just set an base in the config file

### Expected behavior

the title link should consider the base

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 8.95 GB / 15.92 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\Source\Repos\emersonbottero\ServiceNow.Core\ServiceNow.Core\node_modules\.bin\yarn.CMD
    npm: 8.1.3 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 102.0.5005.63
    Edge: Spartan (44.22621.1.0), Chromium (102.0.1245.33)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.1 => 1.0.0-alpha.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! This was fixed in #718.
