### ISSUE TITLE
Slot for top or bottom of document

### ISSUE THREAD

**Issue by ronaldaug** [vuejs/vitepress#762]
### Is your feature request related to a problem? Please describe.

[According to the documentation](https://vitepress.vuejs.org/guide/theme-introduction.html#extending-the-default-theme), it seems there is no slot like before or after document content.

I just want to add global components such as `search box` or `breadcrumbs` on top of every document.

There is an option that I can add `<bread-crumbs />`  to every `.md` documents.  However, I think this is not a proper way to do it as it's used in every documents.

### Describe the solution you'd like

Adding a slot before or after the document content.

`<template #doc-before></template>`
`<template #doc-after></template>`

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by qwqcode** [comment]
a comment area after the page also need this
