### ISSUE TITLE
Nested custom containers don't work

### ISSUE THREAD

**Issue by noClaps** [vuejs/vitepress#764]
### Describe the bug

Whenever I close the inner container, it automatically closes the outer container as well, and any content afterwards gets excluded.

### Reproduction

1. Make a container using `:::`
2. Write some text inside
3. Make another container inside first container, again using `:::`
4. Type text in inner container
5. Close inner container with `:::`
6. Type some more text
7. The text after the inner container is not included in the outer container

### Expected behavior

The text after the inner container should be part of the outer container

### System Info

```shell
System:
  OS: Linux 5.17 Fedora Linux 36 (Workstation Edition)
  CPU: (8) x64 AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
  Memory: 14.57 GB / 17.57 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
  npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
npmPackages:
  vitepress: ^1.0.0-alpha.1 => 1.0.0-alpha.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That's not how nested containers are written. If you are nesting you need to increase the marker too.

```
::::

:::
// your stuff here
:::

:::
// some more stuff
:::

::::
```
