### ISSUE TITLE
Markdown formatting in custom container titles

### ISSUE THREAD

**Issue by noClaps** [vuejs/vitepress#765]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Allow custom titles of containers to be manipulated with Markdown, such as **bold**, _italics_, or hyperlinks.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! Can you explain more on what are you trying to do here?

**Comment by noClaps** [comment]
I'm trying to do something like:

```
::: info [Lorem ipsum](https://example.org)
This is some example text
```

and have the title of the container be a hyperlink like [Lorem Ipsum](https://example.org). This is especially useful for quotes as I can link it back to the source.
