### ISSUE TITLE
custom useData is not reactive

### ISSUE THREAD

**Issue by Zhengqbbb** [vuejs/vitepress#769]
### Describe the bug

When I used useData().frontmatter to make the home page, I found that when switching pages, its custom  frontmatter data did not change.

Maybe meet it in the future #631 
Maybe my usage is wrong, please let me know. Thx~

### Reproduction

I made a minimal example repository：
https://github.com/Zhengqbbb/vitepress-recurrent

```
git clone https://github.com/Zhengqbbb/vitepress-recurrent.git
pnpm install
pnpm docs:dev
```
try to try to press button

### Expected behavior

the custom frontmatter will change when switching pages

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 124.98 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Safari: 15.1
  npmPackages:
    vitepress: 1.0.0-alpha.1 => 1.0.0-alpha.1
```

### Additional context

https://user-images.githubusercontent.com/40693636/173105671-12b9c26d-78b4-4660-927e-a961a74f4e2b.mp4

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! Do it like this:

```vue
<script setup>
import { computed } from 'vue'
import { useData } from 'vitepress'

const custom = computed(() => {
  return useData().frontmatter.value.custom
})
</script>

<template>
  <ul style="width: 980px; margin: 0 auto">
    <li v-for="(val, i) in custom" :key="i">
      <p>{{ val.title }}</p>
      <p>{{ val.details }}</p>
    </li>
  </ul>
</template>
```
