### ISSUE TITLE
dup component with <img>+<p> in markdown (SSR)

### ISSUE THREAD

**Issue by gurgeous** [vuejs/vitepress#770]
### Describe the bug

Thanks for creating vitepress, we are loving it!

In markdown w/ SSR, placing a `<p>` tag directly below an image breaks rendering of the next component. The component is duplicated for some reason. Note that this bug only occurs with SSR (not `vitepress dev`).

### Reproduction

Here is some markdown to try:

```md
![](./someimage.png)
<p>sometext</p>

<MyComponent/>
```

MyComponent.vue:

```html
<template>
  <div style="width: 10rem; height: 10rem; background: red" />
</template>
```

On dev it renders as one red box, with SSR it renders as two. The SSR HTML is strange:

```html
<p><img src="..." alt=""></p>
<div style="width: 10rem; height: 10rem; background: red;"></div>
<p></p>
<div style="width:10rem;height:10rem;background:red;"></div>
```

![image](https://user-images.githubusercontent.com/526195/173143127-ee09ff89-1955-45e6-b56b-87fb1b7ef7e8.png)

### Expected behavior

Component would render properly, or at least identically, in both dev and SSR.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 135.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.asdf/installs/nodejs/16.13.2/bin/node
    Yarn: 1.22.18 - ~/.asdf/installs/nodejs/16.13.2/.npm/bin/yarn
    npm: 8.1.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 97.0.1
    Safari: 15.5
  npmPackages:
    vitepress: ^1.0.0-alpha.1 => 1.0.0-alpha.1
```

### Additional context

To workaround the issue, place a newline between the image and the `<p>` tag, like so:

```md
![](./someimage.png)

<p>sometext</p>

<MyComponent/>
```

Then everything renders properly.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! This is actually the commonmark standard. You need to separate markdown and html/vue by at least a blank line. I'm not sure why the content is being duplicated. But giving no space between md and html will generally cause issues with rendering.

**Comment by gurgeous** [comment]
I am fine with this. But shouldn't it work the same between dev and SSR? That seems like an issue.

**Comment by yyx990803** [comment]
Closing as I can no longer reproduce this in latest (1.0.0-alpha.54)
