### ISSUE TITLE
preserveValueImports will efect crash

### ISSUE THREAD

**Issue by agileago** [vuejs/vitepress#773]
### Describe the bug

see https://stackblitz.com/edit/vite-zodl7a

### Reproduction

see https://stackblitz.com/edit/vite-zodl7a

### Expected behavior

not crash

### System Info

```shell
any
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Use it along with `skipLibCheck: true` for now.

**Comment by kiaking** [comment]
Hah, we should be using `import type { DefaultTheme } from '../config'`...?
