### ISSUE TITLE
themeConfig.editLink There is no attribute pattern

### ISSUE THREAD

**Issue by k983551019** [vuejs/vitepress#775]
### Describe the bug

It's in the documentation
https://vitepress.vuejs.org/guide/theme-edit-link.html#edit-link

themeConfig.editLink
There is no attribute pattern

### Reproduction

```
export default defineConfig({
    themeConfig: {
        editLink:{
          pattern: "https://gitea.com/:path",
        }
    }
})
```

### Expected behavior

add pattern

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz
    Memory: 797.08 MB / 24.00 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.33)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-alpha.1 => 1.0.0-alpha.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by k983551019** [comment]
![image](https://user-images.githubusercontent.com/48147837/173179807-74faddad-f134-4978-a8f4-a9a4eafd8af5.png)
![image](https://user-images.githubusercontent.com/48147837/173179825-c563ba2f-a663-4e6c-92cb-954dee089c8c.png)

**Comment by kecrily** [comment]
ref https://github.com/vuejs/vitepress/pull/698
