### ISSUE TITLE
The site title in the navigation bar ignores the `base` option

### ISSUE THREAD

**Issue by hir0kio** [vuejs/vitepress#781]
### Describe the bug

The site title in the navigation bar always links to `/`, even if the [`base` option](https://github.com/vuejs/vitepress/blob/main/docs/config/app-configs.md#base) is specified in `.vitepress/config.ts`.

### Reproduction

1. In `.vitepress/config.ts`, set the `base` option to `/base/`.
2. Start the VitePress development server.
3. Go to `http://localhost:3000/base/`.
4. Click the site title in the navigation bar.
5. The browser navigates to `http://localhost:3000/`.

### Expected behavior

The browser should navigate to `http://localhost:3000/base/`.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 88.41 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.3.0 - ~/.nvm/versions/node/v18.3.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.3.0/bin/npm
  Browsers:
    Safari: 15.5
    Safari Technology Preview: 15.4
  npmPackages:
    vitepress: 1.0.0-alpha.1 => 1.0.0-alpha.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Was fixed in #718.
