### ISSUE TITLE
How can I set the base url for 2 different domains.

### ISSUE THREAD

**Issue by Roman-00** [vuejs/vitepress#784]
### Discussed in https://github.com/vuejs/vitepress/discussions/749

<div type='discussions-op-text'>

<sup>Originally posted by **Roman-00** June  8, 2022</sup>
example https://roman.kz/ms/guide / - set the base path /ms/guide/, and for the domain https://roman.kz - set the base path /</div>

**Comment by brc-dd** [comment]
Isn't this same as #750?

**Comment by Roman-00** [comment]
> Isn't this same as #750?

"BASE" is not an internal or external
command, executable program, or batch file.
![vite-one](https://user-images.githubusercontent.com/58338625/173329837-8c30c668-d942-454e-b955-18d4c94106cf.jpg)
![vite-two](https://user-images.githubusercontent.com/58338625/173329848-80c7951f-cd9f-4896-adea-fe8ea73da78d.jpg)

**Comment by Roman-00** [comment]
![vite-three](https://user-images.githubusercontent.com/58338625/173329945-d57eba82-84f2-4433-8812-ff81c18ddf9b.jpg)

**Comment by brc-dd** [comment]
First: you're using Yarn. So it'll be `yarn build:docs` instead of `pnpm build:docs`. Second, you're on Windows. So you'll need some tool like `cross-env` to set env variables.

**Comment by Roman-00** [comment]
> First: you're using Yarn. So it'll be `yarn build:docs` instead of `pnpm build:docs`. Second, you're on Windows. So you'll need some tool like [`cross-env`](https://www.npmjs.com/package/cross-env) to set env variables: `yarn build:docs && cross-env BASE='/ms/guide/' yarn build:docs`.

Thank you very much for helping me out. Thanks a lot :)
