### ISSUE TITLE
Show dynamic headers in aside outline

### ISSUE THREAD

**Issue by ElliotThiebaut** [vuejs/vitepress#785]
### Describe the bug

If you use Vue-style interpolation in a markdown title (# in markdown), the aside curtain "On this page" will show the Vue syntax and not the final text. It will also not take into account the fact that multiple secondary title exists from a loop.

### Reproduction

If you have a markdown file like this with a vfor loop and a interpolation of text for the heading:
![image](https://user-images.githubusercontent.com/60610988/173346686-c53c23d0-bec9-4b67-9663-a3d776562802.png)
```md
# My great page
## {{element.subtitle}}
```

The output will show `{{element.subtitle}}` as text in the aside curtain "On this page".
![image](https://user-images.githubusercontent.com/60610988/173346767-3c1b21fb-1712-48b2-8213-7d5dd7bce18e.png)

### Expected behavior

The output in the aside curtain "On this page" should be the string returned by Vue-style interpolation and take into account the multiple instance of the loop.
![image](https://user-images.githubusercontent.com/60610988/173347004-43c676dc-9ca5-408f-8de3-19a38554366b.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 18.71 GB / 31.73 GB
  Binaries:
    Node: 18.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.1 => 1.0.0-alpha.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Putting Vue-style interpolations in Markdown headings also messes up automatic element IDs (for anchors).
