### ISSUE TITLE
'Title' links to '/' rather than '/base', causing 404 on GitHub Pages

### ISSUE THREAD

**Issue by SirLich** [vuejs/vitepress#787]
### Describe the bug

The 'title' link in the top of the NavBar linked to the '/' instead of 'base', causing a 404 when you click it on GithubPages. 

For example, my website has a base of 'sapiens-modding-wiki' since in GithubPages the base must match the repository name: https://sirlich.github.io/sapiens-modding-wiki/

When you click the 'title', it brings me to https://sirlich.github.io instead of https://sirlich.github.io/sapiens-modding-wiki/, causing a 404 to appear. 

### Reproduction

1. Visit a site such as https://sirlich.github.io/sapiens-modding-wiki/
2. Click the 'Sapiens Modding Wiki' on the top of the navbar
3. Observe a 404
4. Reload the page to see that the https://sirlich.github.io is unrelated to current vitepress docs

### Expected behavior

I expect that I am redirected to https://sirlich.github.io/sapiens-modding-wiki/ as this matches the `base` defined in my config.

### System Info

```shell
*GitHub Pages*.
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kecrily** [comment]
We have a `base` config, you can use it custom the dir your website used.

ref https://vitepress.vuejs.org/config/app-configs.html#base

**Comment by brc-dd** [comment]
Was fixed by #718
