### ISSUE TITLE
useRoute doesn't expose url hash

### ISSUE THREAD

**Issue by hyp530** [vuejs/vitepress#788]
### Describe the bug

How to get the url hash: 

``` js 
import { useRoute } from 'vitepress'
const route = useRoute()
console.log(route.hash) // Full path with has is not exposed, and url would be redirected with hash removed.
```

### Reproduction

Not applicable.

### Expected behavior

Not applicable.

### System Info

```shell
Not applicable.
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can do this:

```vue
<script setup>
import { ref } from 'vue'

const hash = ref('')

const handleHashChange = () => {
  hash.value = window.location.hash.replace(/^#/, '')
}
window.addEventListener('hashchange', handleHashChange)
handleHashChange()
</script>

<template>
  <div>Hash is <code>{{ hash || 'null' }}</code></div>
</template>
```

**Comment by hyp530** [comment]
@brc-dd Failed to jump to a specific location using url hash, since vitepress would always convert it to a Header location. Will you change this to allow more flexible ui design?

**Comment by brc-dd** [comment]
> since vitepress would always convert it to a Header location

@hyp530 Sorry, I didn't understand that part. What are you trying to do? Can you show us some example?

**Comment by brc-dd** [comment]
Ah, I see. Thanks for the repro. We'll look into that.

**Comment by brc-dd** [comment]
Okay, so this is because of the outline component. Should we add an option to remove it?

https://github.com/vuejs/vitepress/blob/baf8083e668ce50a9d26d9398609e196237ebc95/src/client/theme-default/composables/outline.ts#L123

**Comment by hyp530** [comment]
> Okay, so this is because of the outline component.
> 
> https://github.com/vuejs/vitepress/blob/baf8083e668ce50a9d26d9398609e196237ebc95/src/client/theme-default/composables/outline.ts#L123
> 
> Should we add an option to remove it? Something like this in frontmatter maybe?
> 
> ```yaml
> ---
> outline: false
> ---
> ```

I think just no need to convert a non-Header hash  to a Header hash.  VuePress@Next works well on this.

**Comment by hyp530** [comment]
@brc-dd  BTW, there's another minor DefaultTheme issue - Algolia Button Translation setting doesn't work at first load of homepage. 

**Reproduction**:

(i) Enter [this test site](https://vite-press-test.vercel.app/), look at Algolia search button - It's in English (It should be Chinease under Translation setting).

(ii) Click the Algolia search button, the button text would change to Chinese.

**Comment by brc-dd** [comment]
@hyp530 Yeah, its a known issue. See #713

**Comment by brc-dd** [comment]
Lets track this at #903
