### ISSUE TITLE
Add Algolia integration without Doc Search

### ISSUE THREAD

**Issue by ElliotThiebaut** [vuejs/vitepress#805]
### Is your feature request related to a problem? Please describe.

Algolia without doc search is not working, I'm building a documentation that needs to be private and so Doc Search is not a option as it's only for publicly available website. Simply addinf the algolia object in the config file of vitepress does not work in this case.

There is also no documentation about how to structure the index in default Algolia, making implementation very difficult.

### Describe the solution you'd like

Fixing the issue with standard Algolia not working would be very awesome, alongside a documentation about how to structure the index and implementing it into vitepress.

### Describe alternatives you've considered

There seems to be no alternative to Doc Search.

### Additional context

Thanks for vitepress ! It's really awesome !

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
We currently don't have this feature because we're directly using Algolia DocSearch, hence this is going to be a new feature.

I think it makes to have it? But it would be a low priority until we hit v1.0.0 milestone. So we might have to depend on community members for figuring out how to implement this.

**Comment by e3d** [comment]
Searching is definitely critical for a doc site. Looking forward to it.

**Comment by fallemand** [comment]
Please, we need search functionality for private repos.
