### ISSUE TITLE
Allow excluding styles for tags like h2 in `vp-doc`

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/vitepress#808]
### Is your feature request related to a problem? Please describe.

I am rendering components in `.vp-doc` and my component's h2 gets style of VitePress which I don't want.

### Describe the solution you'd like

Add class `not-vp-doc` to omit applying styles

### Describe alternatives you've considered

none

### Additional context

I checked the source and found that all styles are written in CSS and it isn't quick to apply the `:not()` selector because there's list of `vp-doc` class usage and I might break something in hurry.

I am in hurry hence creating this issue instead of PR.

Will the team going to use SCSS in favor or refactor?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by jd-solanki** [comment]
Related #199

**Comment by kiaking** [comment]
If you're in hurry, please use custom css with `!important` or something like that for a quick fix.

Let's continue discuss the issue in #199 👍
