### ISSUE TITLE
How to programmatically change page route?

### ISSUE THREAD

**Issue by azat-io** [vuejs/vitepress#813]
### Describe the bug

![Screen Recording 2022-06-18 at 3 32 52 PM](https://user-images.githubusercontent.com/5698350/174437918-2e5d77ff-0f3c-4b29-abed-f1638f4165cb.gif)

I'm trying to change page route with the following code:

```ts
import { useRouter } from 'vitepress'
import { onMounted } from 'vue'

let router = useRouter()

onMounted(() => {
  router.go('/hello.html')
})
```

The link in the address bar of the browser changes, but the content remains the same. How can I fix it?

You can check this problem in my repo: https://github.com/azat-io/vitepress-router-example

### Reproduction

1. Clone this repo: https://github.com/azat-io/vitepress-router-example
2. Open `http://localhost:3000`
3. The link in the browser will change to `http://localhost:3000/hello.html`, but the content will be displayed for the root page
4. Refresh the page to display the correct content

### Expected behavior

Page content should change after redirect

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 42.39 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - ~/.asdf/installs/nodejs/17.2.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.4 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    vitepress: 1.0.0-alpha.2 => 1.0.0-alpha.2
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Your Layout component don't have reactivity setup so even if the layout changes, it doesn't affect. Change your `view/index.vue` to something like this and it'll work.

```vue
<script lang="ts" setup>
import { ref, computed, watchEffect, markRaw } from 'vue'
import { useData } from 'vitepress'

import PageRoot from '~/pages/root.vue'
import PagePost from '~/pages/post.vue'

let { frontmatter } = useData()

let layoutType = computed(() => frontmatter.value.layout)

let Layout = ref({})

// Switch the layout when route changes.
watchEffect(() => {
  if (layoutType.value === 'root') {
    Layout.value = markRaw(PageRoot)
  } else {
    Layout.value = markRaw(PagePost)
  }
})
</script>
```
