### ISSUE TITLE
该如何在文档中播放多媒体呢？

### ISSUE THREAD

**Issue by AgentRich** [vuejs/vitepress#814]
### Is your feature request related to a problem? Please describe.

快速构建文档，有时更希望插入一些视频能让文档使用者体验更加。但是使用文档中并没有发现可以插入多媒体的方式。
尝试了H5的video标签和iframe 都是不允许播放本地媒体文件的。
有什么方式能实现播放视频么？

### Describe the solution you'd like

最好是有配置开关。

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by AgentRich** [comment]
啊   抱歉  是我没搞明白  
浏览器默认不能播放本地的视频文件，将文件映射程url就好了

**Comment by BaoYier** [comment]
想请教一下你的 iframe 是怎么嵌入的，我dev的时候可以显示，build就会报错

**Comment by AgentRich** [comment]
>

**Comment by AgentRich** [comment]
> 想请教一下你的 iframe 是怎么嵌入的，我dev的时候可以显示，build就会报错

我用iframe失败了   直接用markdown的引用就可以   只是发布出去的时候视频得是映射出来的地址 
浏览器的同源策略问题   
我最后使用caddy给视频映射出来一个地址  然后markdown里直接引用的。
