### ISSUE TITLE
请问如何为页脚(footer)添加链接？国内工信部要求

### ISSUE THREAD

**Issue by Kit-Mrz** [vuejs/vitepress#815]
### Is your feature request related to a problem? Please describe.

国内要部署网站必须要在网站首页底部添加工信部的连接

### Describe the solution you'd like

希望提供一个简单的添加方式

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kecrily** [comment]
Since the footer config is only displayed on non-doc pages, you may need to use the footer and `doc-after` slot together.

Ref https://vitepress.vuejs.org/guide/theme-footer.html and https://vitepress.vuejs.org/guide/theme-introduction.html

**Comment by Kit-Mrz** [comment]
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/14925130/174481610-653147c8-ec3a-47a2-b5f4-7283aac1add9.png">
并没有找到作用于 footer 的 slot
<img width="647" alt="image" src="https://user-images.githubusercontent.com/14925130/174481663-af1bd22d-aaef-4b4f-9ae8-bf775652884c.png">

**Comment by Kit-Mrz** [comment]
![image](https://user-images.githubusercontent.com/14925130/174482085-25a907bc-a665-4134-aa07-7d94055191d5.png)
![image](https://user-images.githubusercontent.com/14925130/174482093-f6a95ca4-810d-426e-b25d-d1d601c1d12c.png)
我尝试过这样设置，但是依然无效，使用 aside-top，aside-bottom 是可以生效的

**Comment by kecrily** [comment]
`doc-after` slot was introduced in alpha.2, so please check the version of vitepress you are using.

**Comment by Kit-Mrz** [comment]
您好：


请问你能否帮助我解决这个问题？





我希望在网站底部，添加一个 a 标签，并且链接到&nbsp;https://beian.miit.gov.cn。





我这样添加的话，国内网站备案是无法通过的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuejs/vitepress"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月19日(星期天) 晚上9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vuejs/vitepress] 请问如何为页脚(footer)添加链接？国内工信部要求 (Issue #815)





 
doc-after slot was introduced in alpha.2, so please check the version of vitepress you are using.

**Comment by meimao** [comment]
config.fs:
`      footer: {
        message: "<a href='https://www.google.com'>this is a link</a> ",
        copyright: "....."
      }`
want to show a clickable text: 'this is a link'
but ‘<a href.. .... </a>’ shows without any change.

**Comment by Kit-Mrz** [comment]
VuePress can VitePress can't

**Comment by Charles7c** [comment]
这个问题我解决了。
vitepress官方(#1032)可能考虑到应用人群范围小，所以并没有打算调整这部分，虽然只需要将对应的代码从{{}}改成v-html即可。
你的思路也是对的，只不过使用的slot错了，可以去我的[仓库](https://github.com/charles7c/charles7c.github.io)参考下配置。

**Comment by Charles7c** [comment]
> 这个问题我解决了。 vitepress官方(#1032)可能考虑到应用人群范围小，所以并没有打算调整这部分，虽然只需要将对应的代码从{{}}改成v-html即可。 你的思路也是对的，只不过使用的slot错了，可以去我的[仓库](https://github.com/charles7c/charles7c.github.io)参考下配置。

To my surprise, vitepress officially fixed the problem the next day. 👍 
https://github.com/vuejs/vitepress/pull/1034
