### ISSUE TITLE
Copy paste code, not available online

### ISSUE THREAD

**Issue by wanlum** [vuejs/vitepress#818]
### Describe the bug

![Uploading image.png…]()

### Reproduction

step.1 enter hr.wanlum.com in browser
step.2 find some code 

error

### Expected behavior

![image](https://user-images.githubusercontent.com/11306760/174506697-de886ae2-64e0-4904-9e18-6c0702449ea2.png)

### System Info

```shell
CentOS 9
Nginx 1.21.0
```

### Additional context

no

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Your site is not being served over `https`. `navigator.clipboard` is available only in secure contexts. Was fixed by #792. The fix will be there in the next release.
