### ISSUE TITLE
copy to clipboard button style

### ISSUE THREAD

**Issue by RainKolwa** [vuejs/vitepress#819]
### Describe the bug

If the `code sample` reached a bit long, the `copy button` and `copied tip` are not clear enough to recognize.

### Reproduction

![image](https://user-images.githubusercontent.com/8369430/174545064-96a65b7e-9b3b-457d-80aa-5835994fd7e4.png)

### Expected behavior

`copy button` to be clear. 

### System Info

```shell
-
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Zelig880** [comment]
The buttons currently use opacity to achieve the light hover effect, but it would probably benefit to have a solid colour (as the hover effect is a solid colour anyway(.

For future reference this is the class (and CSS variable) that handle the hover effect of the copy button:
<img width="450" alt="Screenshot 2022-06-26 at 21 48 40" src="https://user-images.githubusercontent.com/9040770/175833420-af3ea6aa-5085-447e-a892-4da669e04f41.png">

We could change and actually define some borders instead than background-colour. This is an example of using (--vp-c-text-3) - (yeah I know it is for text, I was just trying to use existing colors):
<img width="270" alt="Screenshot 2022-06-26 at 21 58 00" src="https://user-images.githubusercontent.com/9040770/175833606-fa5b6c66-04dd-40c9-8285-1a43e2fb5102.png">


Note: If we do use background color, we should also make sure we add a black border when the button is not hovered, to avoid flicks and movement when the button is hovered!

**Comment by kiaking** [comment]
Yeah I've used opacity to make style customization a bit easier but seems like we have to use solid background 😅 

I'm fine with that. This issue is on the 1.0.0 milestone so eventually I'll fix this 👍
