### ISSUE TITLE
Unexpected `One or more pages contain dead links` for `localhost` links

### ISSUE THREAD

**Issue by JounQin** [vuejs/vitepress#822]
### Describe the bug

```md
<!-- docs/guide/getting-started.md -->
This will start a local server and open the <http://localhost:3000> page in the browser.
```

```log
(!) Found dead link http://localhost:3000 in file docs/guide/getting-started.md
```

### Reproduction

N/A

### Expected behavior

No error

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 24.57 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/Library/Caches/fnm_multishells/60250_1655730203758/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/60250_1655730203758/bin/yarn
    npm: 8.12.1 - ~/Library/Caches/fnm_multishells/60250_1655730203758/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 101.0.1
    Safari: 16.0
  npmPackages:
    vitepress: ^1.0.0-alpha.2 => 1.0.0-alpha.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kecrily** [comment]
@brc-dd 

Do you know why localhost is considered a dead link? In my opinion local links like localhost and 127.0.0.1 should not be considered as dead links, they are valid in some development, internal scenarios.

https://github.com/vuejs/vitepress/blob/06ad0d8386626eab2e98af1b591ac34295d9f7ed/src/node/markdown/plugins/link.ts#L28-L31

**Comment by brc-dd** [comment]
@kecrily  Some people unintentionally leave links like `localhost:3000/foo.html` due to copy-pasting URLs during development. It was added to prevent such scenarios. But yeah, this should be fixed IG. People have things like "go to localhost:1234".

**Comment by brc-dd** [comment]
@JounQin Are you sure? Because I'm not getting any error on doing that: https://stackblitz.com/edit/vite-jhbvp5?file=docs/index.md . Maybe you've those links in other files too?

**Comment by JounQin** [comment]
> @JounQin Are you sure? Because I'm not getting any error on doing that: [stackblitz.com/edit/vite-jhbvp5?file=docs/index.md](https://stackblitz.com/edit/vite-jhbvp5?file=docs/index.md) . Maybe you've those links in other files too?

Ah, sorry, I misremembered it with `[http://127.0.0.1:3000](http://127.0.0.1:3000)`.

`<a href="http://127.0.0.1:3000">http://127.0.0.1:3000</a>` is working as expected.

**Comment by brc-dd** [comment]
So, that's a recommended workaround for now (you won't have many such URLs anyway). When #793 gets merged, you can also ignore dead links check (not recommended, but will work). I don't think there is a way to actually fix this issue without disregarding the original cause why that check was introduced in first place.

**Comment by JounQin** [comment]
Maybe add this limitation into document would help. Closing for now because it is `expected` in the first place.

**Comment by JounQin** [comment]
Additionally, the `1:1` workaround would be `<a href="http://localhost:3000" target="_blank" rel="noreferrer noopener">http://localhost:3000</a>`.

**Comment by JounQin** [comment]
@brc-dd I found another interested thing:

```ts
// components/ExternalLink.ts
import type { AnchorHTMLAttributes } from 'react'
import { h, FunctionalComponent } from 'vue'

export type ExternalLinkProps = Omit<
  AnchorHTMLAttributes<HTMLAnchorElement>,
  'target'
>

export const ExternalLink: FunctionalComponent<ExternalLinkProps> = (
  props,
  context,
) =>
  h(
    'a',
    {
      target: '_blank',
      rel: 'noreferrer noopener',
      ...props,
    },
    context.slots.default?.(),
  )

```

The following will still emit error.

```tsx
<ExternalLink href="http://localhost:3000">http://localhost:3000</ExternalLink>
```

**Comment by brc-dd** [comment]
It's getting autolinked IG.

**Comment by JounQin** [comment]
Just found I was silly, I should use `props.href` as `children` actually.

```ts
import type { AnchorHTMLAttributes } from 'react'
import { h, FunctionalComponent } from 'vue'

export type ExternalLinkProps = Omit<
  AnchorHTMLAttributes<HTMLAnchorElement>,
  'target'
>

export const ExternalLink: FunctionalComponent<ExternalLinkProps> = (
  props,
  context,
) => {
  return h(
    'a',
    {
      target: '_blank',
      rel: 'noreferrer noopener',
      ...props,
    },
    props.href,
  )
}
```

```tsx
<ExternalLink href="http://localhost:3000"/>
```
