### ISSUE TITLE
Sidebar always showing in the home page

### ISSUE THREAD

**Issue by tarikjabiri** [vuejs/vitepress#825]
### Describe the bug

Sidebar always showing in the home page

### Reproduction

I just get started
![sidebar](https://user-images.githubusercontent.com/6343314/174688199-7a516535-7cbc-4443-9f34-fbd53c5059ed.PNG)

### Expected behavior

Sidebar hides on home

### System Info

```shell
windows
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide a minimal reproducible example.

**Comment by Loveyless** [comment]
change sidebar:{} in config.js 
like
![image](https://user-images.githubusercontent.com/88988179/174727328-93c1aed2-0145-46e8-8acd-7fae51df4bda.png)

**Comment by Loveyless** [comment]
you can look my config [here](https://github.com/Loveyless/note/blob/master/docs/.vitepress/config.js)

**Comment by tarikjabiri** [comment]
Hi,

Thank you @alexzhang1030, @Loveyless the problem resolved.

So I have to explicitly define routes when the sidebar should appear that make sense.

if I pass directly an array the side bar always showing, but the way is to pass an object.


 
Thank you for help.

**Comment by tarikjabiri** [comment]
Hi @brc-dd

I suggest that by default hide any sidebar from the layout home.

**Comment by brc-dd** [comment]
Probably need to change this line:

https://github.com/vuejs/vitepress/blob/9c2a36f5428bd98eafb6e2e9bc63f5e532b596b7/src/client/theme-default/composables/sidebar.ts#L19

to:

```js
    return frontmatter.value.sidebar !== false && sidebar.value.length > 0 && frontmatter.value.layout !== 'home'
```

**Comment by kiaking** [comment]
Ah yeah, let's do that. Home layout isn't built for Sidebar in mind so the style will never work. Home layout should always hide sidebar 👍

**Comment by WebMechanic** [comment]
> you can look my config [here](https://github.com/Loveyless/note/blob/master/docs/.vitepress/config.js)

thank you, @Loveyless ! 
that was very useful ! 👍🏻
