### ISSUE TITLE
favicon didn't respect **base** config

### ISSUE THREAD

**Issue by casyalex** [vuejs/vitepress#827]
### Describe the bug

<img width="349" alt="image" src="https://user-images.githubusercontent.com/5988630/174742476-72879305-54a8-4118-b2a3-358719d30e13.png">

As screenshot shows, even set base config, favicon ignore this setting.
And when it seems working fine in dev env. But broke in deploy env.

<img width="415" alt="Screen Shot 2022-06-21 at 15 52 40" src="https://user-images.githubusercontent.com/5988630/174746657-bc4d44e3-1197-43d0-9699-d33e5f059efb.png">

### Reproduction

Just start a random project with base config

### Expected behavior

favicon url should respect **base** config

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 145.51 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.config/yarn/global/node_modules/.bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 89.0
    Safari: 15.5
  npmPackages:
    vitepress: ^1.0.0-alpha.2 => 1.0.0-alpha.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We don't add favicon. You need to manually specify it. Refer https://github.com/vuejs/vitepress/issues/320#issuecomment-865261266. You're seeing that request (/favicon.ico) because that's what most browsers search for.
