### ISSUE TITLE
Support for other directory structures for use in non-JS projects

### ISSUE THREAD

**Issue by jthegedus** [vuejs/vitepress#844]
### Is your feature request related to a problem? Please describe.

Currently Vitepress requires this directory structure:

```
.
├─ docs
│  ├─ .vitepress
│  │  └─ config.js
│  └─ index.md
└─ package.json
```

But I just want to use Vitepress in a non-JS project, so I don't want `package.json` at my project root.

### Describe the solution you'd like

I want to have `package.json` under the `docs/` dir alongside the `.vitepress` config dir and `index.md`:

```
.
├─ .git
├─ docs
│  ├─ .vitepress
│  │  └─ config.js
│  ├─ pt-br
│  │  └─ index.md
│  ├─ package.json
│  └─ index.md
└─ rest of my project
```

### Describe alternatives you've considered

Having nested `docs/` directories works but is cumbersome:

```
.
├─ .git
├─ docs
│  ├─ docs
│  │  ├─ .vitepress
│  │  │  └─ config.js
│  │  ├─ pt-br
│  │  │  └─ index.md
│  │  └─ index.md
│  └─ package.json
└─ rest of my project
```

### Additional context

I have been using Vuepress with `vuepress-vite@2.0.0-beta.22`  this way, but haven't been keeping up with it's updates, so it might have changed this behaviour in a more recent Beta release, I am not sure.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Sure you can. You just have to cd into that `doc` directly.

```bash
cd docs
vitepress
```

You don't need docs directly at all. Don't add `docs` option to your vitepress command.

```bash
vitepress dev docs # Look for `docs` folder
vitepress dev      # Look for `cwd` folder
```

**Comment by jthegedus** [comment]
Ah, thanks. Sorry for the noise.
