### ISSUE TITLE
bug: Duplicate view when deployed with GitHub Pages

### ISSUE THREAD

**Issue by adonyssantos** [vuejs/vitepress#845]
### Describe the bug

I was deploying my project with GitHub Pages as indicated in the documentation using a `deploy.sh` file and everything works correctly until I open my web from the GH pages link.

Here a preview https://dev.adonys.me/vitepress/

I am using a custom domain with CNAME which redirects me from https://dev.adonys.me to https://adonyssantos.github.io.

### Reproduction

The only thing I did was to deploy the page with GitHub Page using a `deploy.sh` file as indicated in the official documentation.

### Expected behavior

I expected that when I enter my site from https://dev.adonys.me/vitepress to see my site correctly (no duplicate), but I enter and the same page is repeated 2 times.

### System Info

```shell
My vitepress config:

export default {
  base: '/vitepress/',
  title: 'Adonys Santos',
  description: 'Learning Vitepress.',
};
```

### Additional context

https://dev.adonys.me/vitepress/

### Validations

- [x] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Can you share the actual project? From this issue, we have no way to figure out what is going on 😅

**Comment by adonyssantos** [comment]
The problem was the Cloudflare minify. I remove the HTML minifier in the Cloudflare config with a page rule and the problem was resolved.
![image](https://user-images.githubusercontent.com/58638286/178503698-28a348f9-9186-4468-a774-e69f96d82e4c.png)

**Comment by brc-dd** [comment]
Yeah it's documented too. Enabling html minification, removes comments from the code. But Vue needs them to properly render components.
