### ISSUE TITLE
bug: build failed when sidebar config with no `items` property in `config.ts`

### ISSUE THREAD

**Issue by suressk** [vuejs/vitepress#846]
### Describe the bug

In `.vitepress/config.ts` file
When the `sidebar` config item with no `items` property, like this:
```js
module.exports = {
      // ... others config
      themeConfig: {
            sidebar: {
                  '/mood/': [
                        { text: 'Introduction' }
                  ]
            }
      }
}
```
then you run the command of `vitepress build docs`, it will build failed and throw error

### Reproduction

Just following the steps of [`official documentation`](https://vitepress.vuejs.org/guide/getting-started.html)
and don't config the `items` property or make the `items` property to be a `non-iterable` property, it will reproduce

like this:
```js
// .vitepress/config.ts
module.exports = {
      // ... others config
      themeConfig: {
            sidebar: {
                  '/mood/': [
                        { text: 'Introduction' }
                  ]
            }
      }
}
```

### Expected behavior

way1: check the sidebar config of `items` property, if it isn't esisted, skipped it

way2: update the docs of sidebar config, make sure the `items` property to be required iterable property ( like `[]`)

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 7.24.2 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.4
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kecrily** [comment]
There is something wrong with your config.

Sidebar is a feature provided by default theme, so sidebar config should be under `themeConfig`. Like

```ts
export default {
  themeConfig: {
    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Introduction', link: '/introduction' },
          { text: 'Getting Started', link: '/getting-started' },
          ...
        ]
      }
    ]
  }
}
```

[Learn more](https://vitepress.vuejs.org/guide/theme-sidebar.html)
