### ISSUE TITLE
Unable to use VitePress with Yarn Berry (Zero Install)

### ISSUE THREAD

**Issue by busyhe** [vuejs/vitepress#849]
Steps to reproduce:

```sh
md foo
cd foo
yarn init -2
yarn add -D vitepress@latest vue@latest
echo '# Hello VitePress' > index.md
yarn vitepress build
```

Error:

```txt
Your application tried to access body-scroll-lock, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

**Comment by brc-dd** [comment]
Adding body-scroll-lock and vueuse/core to noExternal will solve this error, but there is another error `@sitedata` is not being resolved properly, causing issues with dev (build works fine).

**Comment by brc-dd** [comment]
For now consider adding `body-scroll-lock` and `@vueuse/core` to your dependencies alongside `vitepress` and `vue`: 

```sh
yarn add -D body-scroll-lock @vueuse/core
```
