### ISSUE TITLE
Visiting `/docs` results `/docs.html` then 404 if `base` is set as `/docs/`

### ISSUE THREAD

**Issue by JounQin** [vuejs/vitepress#852]
### Describe the bug

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/8336744/175569550-987da428-6290-461c-b1ca-ede03db5e416.png">

<img width="929" alt="image" src="https://user-images.githubusercontent.com/8336744/175569655-51561dae-5d49-4155-ae6c-9924df2b9cdb.png">

### Reproduction

https://github.com/JounQin/test/tree/vitepress

`yarn docs:build --base /docs/ && yarn docs:serve --base /docs/`

### Expected behavior

`http://localhost:8000/docs`  (Without ending slash) should work same as `http://localhost:8000/docs/` (With ending slash)

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 17.64 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/Library/Caches/fnm_multishells/3706_1656066380637/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/3706_1656066380637/bin/yarn
    npm: 8.13.1 - ~/Library/Caches/fnm_multishells/3706_1656066380637/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 101.0.1
    Safari: 16.0
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This is expected. `/foo/` resolves to `/foo/index.html` and `/foo` resolves `/foo.html`

**Comment by JounQin** [comment]
I think `base` should be checked, `/docs` means `base`, and means `/docs/index.html`

**Comment by JounQin** [comment]
@brc-dd Please help to review #853

**Comment by brc-dd** [comment]
Regarding this I've another doubt. That /docs is technically considered outside the base. Then why is our router intercepting such a link in first place? 👀

**Comment by JounQin** [comment]
@brc-dd It results 404 as the screen shot from VP.

**Comment by JounQin** [comment]
And which ever 404 the server response, it depends on the user's server setting, `/docs` results 404 is unexpected.

**Comment by staghouse** [comment]
Just to add some color here, VuePress handles this the way to OP is requesting. Leaving out the trailing slash resolves the url to directory `index.html` which does make sense to me - the path should resolve to a usable path which is the trailing slash.

This is probably more particularly important for nested documentation pages like `/docs/something/index.md` resolving `/docs/something.html` which would never be a built path.

**Comment by ranqiangjun** [comment]
+1 to this. 

And add my two cents here:

```
  base: '/docs/',
  cleanUrls: 'with-subfolders',
```
I would visit https://example.com/docs, yeah, it works. BUT the link to the site name is `/docs/`, click the site name, the URL is changed to `https://example.com/docs/`, which is unexpected to me.

**Comment by ranqiangjun** [comment]
BTW, the extra `.html` appended to `/docs` as `/docs.html` on the screenshot happens with `cleanUrls: "off"`
