### ISSUE TITLE
`doc:build` can't pack  files into `dist`

### ISSUE THREAD

**Issue by gyhyfj** [vuejs/vitepress#858]
### Describe the bug

I want to add my `favicon.ico` and `diy.css` into my web page,  so I edit `config.js` as this:
```js
export default {
  head: [
    [
      'link',
      {
        rel: 'icon',
        type: 'image/x-icon',
        href: '/static/image/favicon.ico',
      },
    ],
    ['link', { rel: 'stylesheet', href: '/static/css/diy.css' }],
  ],
}
```
Eveything is OK when run `yarn doc:serve`, 
but when run `yarn doc:build`, my `static` fold and its files aren't packed into `dist`,  so they doesn't work when deploy.
What should I do about it?

### Reproduction

-

### Expected behavior

-

### System Info

```shell
win10
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Use `public` instead of `static`.
