### ISSUE TITLE
Add support for cs files! Yes I do use vitepress to document C# libraries 😁

### ISSUE THREAD

**Issue by emersonbottero** [vuejs/vitepress#861]
### Is your feature request related to a problem? Please describe.

Although C# is one of the available languages it does not recognize cs extension while trying to use <<< to import code.

```bash
[vite] Internal server error: No language registration for cs
```

### Describe the solution you'd like

I'm not sure how it work internally but it seems in only missing the recognition of cs files as C# language!

### Describe alternatives you've considered

If it can be done by default great.
If this needs an configuration maybe updating the docs would suffice.

### Additional context

I have support for other languages would improve the usage (and popularity) of vitepress 🤓 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by xfq** [comment]
Did you try `c#` instead of `cs`?

**Comment by emersonbottero** [comment]
> Have you tried `csharp` / `c#` instead of `cs`?
> 
> The currently supported languages are documented in https://github.com/shikijs/shiki/blob/main/docs/languages.md#all-languages

I can't replace the file extensions I'm using in the library.

I guess you misunderstood... 
I'm not trying to use ``` sintax

I'm using <<<

**Comment by xfq** [comment]
Sorry, I misunderstood. You're right, VitePress doesn't support the `<<< @/test.cs` syntax indeed.

**Comment by brc-dd** [comment]
Thanks for pointing this out. We are probably just adding the extension as the language in our snippet plugin. We should instead be mapping the extension to language the way linguist does. Also, even in fenced code blocks, we don't currently show language on top right for C# I guess. We have a hard coded list in our CSS to do that. But I guess this can be fixed in the code block plugin itself (the way we added copy, we can add another span telling the language and just style it from CSS, it will eliminate the need for hard coding).

**Comment by yxw007** [comment]
<<< @/snippets/csharp-snippets.cs{csharp}

It's work ok

**Comment by yxw007** [comment]
> ### Is your feature request related to a problem? Please describe.
> Although C# is one of the available languages it does not recognize cs extension while trying to use <<< to import code.
> 
> ```shell
> [vite] Internal server error: No language registration for cs
> ```
> 
> ### Describe the solution you'd like
> I'm not sure how it work internally but it seems in only missing the recognition of cs files as C# language!
> 
> ### Describe alternatives you've considered
> If it can be done by default great. If this needs an configuration maybe updating the docs would suffice.
> 
> ### Additional context
> I have support for other languages would improve the usage (and popularity) of vitepress 🤓
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
> * [x]  Read the [docs](https://vitepress.vuejs.org).
> * [x]  Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
> * [x]  Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

<<< @/snippets/csharp-snippets.cs{csharp}

It's work ok
