### ISSUE TITLE
Left sidebar suggestions

### ISSUE THREAD

**Issue by zihaoyy** [vuejs/vitepress#864]
### Is your feature request related to a problem? Please describe.

The distance of the left sidebar is a bit too wide, and this width occupies a large part of the main content of the page. Even if there is very little content on the left, the empty margin is a bit of a waste of space.

### Describe the solution you'd like

I hope that the left sidebar can be customized, such as specifying width, sidebar welt, etc., so that the main content can be displayed to the fullest

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can simply override `--vp-sidebar-width` to whatever you want.
