### ISSUE TITLE
`sponsor-link` hidden when `ad block` present

### ISSUE THREAD

**Issue by userquin** [vuejs/vitepress#866]
### Describe the bug

When adding `VPTeamMembers` with members with sponsor entry, all sponsor links will be hidden if the `ad block` addon present in the browser.

### Reproduction

The branch on Vitest repo: https://github.com/vitest-dev/vitest/tree/userquin/docs-update-theme

If https://github.com/vitest-dev/vitest/pull/1547 merged, just use the main branch.

The `ad block` addon must be installed in the browser to reproduce the issue.

Check also last comments on previous PR, failing in Chrome in MacOS.

Remove the `SponsorLinkFix` plugin from `docs/vite.config.ts`, then:
- run from root folder `pnpm install`
- run from root folder `pnpm run docs:serve`

### Expected behavior

The `sponsor-link` should be always visible.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   
    Memory: 46.29 GB / 63.95 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.37)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Additional context

The `SponsorLinkFix` plugin in the Vitest repo just rename any class with the  `sponsor`  key to `xsponsor` in `VPTeamMembersItem` component: the solution should avoid using the `sponsor` key.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by userquin** [comment]
The `ad block` will inject a stylesheet:

![sponsor-link-injected-style](https://user-images.githubusercontent.com/6311119/175820528-757d316b-6f6f-4cae-9ff3-37af1dd1dc9a.png)

**Comment by JounQin** [comment]
Then `ad block` can just add/update the matching class name. Why it shouldn't?

**Comment by userquin** [comment]
because it is not an ad, and shouldnt be removed

**Comment by JounQin** [comment]
> because it is not an ad, and shouldnt be removed

It `is` an ad as a user, that's why it's added.

**Comment by userquin** [comment]
so if you add sponsor-link to all buttons links in the docs,  it is an error or just ads? 

you should change the name or provide a way to allow ppl configure those links always visible

**Comment by JounQin** [comment]
> so if you add sponsor-link to all buttons links in the docs, it is an error or just ads?

Glad we didn't.

> you should change the name or provide a way to allow ppl configure those links always visible

The users can always update their matching rules, your proposed solution is not effective always.

CSS modules may help, but it is still *ad* from my view, and `ad block` is just working as expected.

**Comment by userquin** [comment]
why is it an ad? we are adding the sponsor links for ppl that build the docs for free, we are not linking to external sites, the sponsor links are part of the docs (we want the sponsor links to be on the docs).

**Comment by userquin** [comment]
This issue is about the `sponsor-link` of the team, it is not related to the ads that can be added.

I understand that there may be private sites using VitePress for the purpose you describe, but from the point of view of open source projects it makes no sense to me that we block the links to sponsor the people who have made the website

**Comment by JounQin** [comment]
Never mind, it's just my personal view, for the team, it seems they want to display sponsor links and also carbon ads always.

I suggest to use CSS module for it if you want.

**Comment by patak-dev** [comment]
The same issue happened to https://github.com/antfu/sponsorkit. @JounQin if a project decides to include sponsors links, they shouldn't count as an ad.

**Comment by patak-dev** [comment]
Thanks for the quick fix @brc-dd!
