### ISSUE TITLE
Add an example to show how to configure head (especially a favicon)

### ISSUE THREAD

**Issue by boring-plans** [vuejs/vitepress#877]
### Is your feature request related to a problem? Please describe.

When configuring the favicon of my site without a thorough unstanding on vitepress project structure, I felt confused about how to represent the icon path. I think there should be a `head` section in the app configs page (just like [this](https://vuepress.vuejs.org/zh/config/#head)), which can be a great referrence for rookie like me.

### Describe the solution you'd like

Add a head section to [this page](https://vitepress.vuejs.org/config/app-configs.html) to show how to configure head (especially a favicon) .

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Yap, we should document this 👍

**Comment by brc-dd** [comment]
Actually adding a favicon doesn't need any config. Just put a `favicon.ico` in your public directory. Config is required when you've file with some different name or base is set.

**Comment by boring-plans** [comment]
[Nice](https://vitepress.vuejs.org/config/app-configs.html#head) 🧐
