### ISSUE TITLE
Definitions and linking

### ISSUE THREAD

**Issue by xfq** [vuejs/vitepress#890]
### Is your feature request related to a problem? Please describe.

It would be nice to be able to define a term and link to it.

Now I can only add `<dfn id="term1">` to the term and use `<a href="#term1>` to link to it (see [example](https://github.com/xfq/vitepress-dfn/blob/main/docs/index.md?plain=1)), but I find that sometimes there is a problem with this. When I click the link, it sometimes jumps to the dfn, sometimes not (I can't find a reliable way to reproduce this issue, though). It seems that VP sometimes intercepts the operation of changing the page's hash?

### Describe the solution you'd like

Either `<a>some concept</a>` or a custom shorthand syntax works for me, as long as I don't have to hand-write the `href` attribute.

### Additional context

Many other documentation systems have this functionality, such as:

* https://respec.org/docs/#definitions-and-linking
* https://tc39.es/ecmarkup/#definitions
* https://github.com/whatwg/wattsi/blob/main/Syntax.md#cross-references
* https://tabatkins.github.io/bikeshed/#autolink-microsyntax
* https://www.gnu.org/software/texinfo/manual/texinfo/html_node/_0040dfn.html

Some also support [automatic pluralization](https://respec.org/docs/#automatic-pluralization).

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Lets track this at #903

**Comment by xfq** [comment]
Sorry, I don't think #903 is the same issue as this issue. This issue is a feature request, not a bug report. I mentioned `<a href="#term1>` because there is no automatic definition linking feature in VitePress, and I only use it as a workaround.

As I mentioned above, I'd like to be able to link to a definition without writing `href` by hand. There are also some examples in the "Additional context" section.

**Comment by brc-dd** [comment]
Is there any markdown-it plugin for this stuff? I can't find anything relevant on NPM.

**Comment by brc-dd** [comment]
Also, in your example you are doing this: `<a href="#concept">concepts</a>` How do you intend to infer `href` in this case?

**Comment by brc-dd** [comment]
You can use some config like this:

```js
import { defineConfig } from 'vitepress'
import csc from 'markdown-it-custom-short-codes'
import slugify from '@sindresorhus/slugify'

export default defineConfig({
  markdown: {
    config: (md) => {
      md.use(csc)
      md.renderer.rules.csc = (...args) => {
        const [tokens, idx] = args

        if (tokens[idx].tag === '~') {
          const { attrs } = tokens[idx]
          const text = Object.keys(attrs).join(' ')
          return `<dfn id="${slugify(text)}">${text}</dfn>`
        }

        if (tokens[idx].tag === '=') {
          const { attrs } = tokens[idx]
          const text = Object.keys(attrs).join(' ')
          return `<a href="#${slugify(text)}">${text}</a>`
        }

        return ''
      }
    }
  }
})
```

Then in markdown you can do `[[~ Some Concept]]` to create `dfn`, and `[[= Some Concept]]` to create link.

**Comment by xfq** [comment]
> Also, in your example you are doing this: `<a href="#concept">concepts</a>` How do you intend to infer `href` in this case?

Ideally, VP should recognize this automatically (at least for documents in English, like [1](https://respec.org/docs/#automatic-pluralization) and [2](https://tabatkins.github.io/bikeshed/#conjugating)). If that's not possible, it would be nice to have a way to manually add variants of a term.

> I am closing this issue as it likely will have very less demand and can be achieved using markdown it plugins. If we see much requests for this, then we might consider adding the support officially.

Fair enough. Thank you very much for your help!

**Comment by brc-dd** [comment]
> Ideally, VP should recognize this automatically (at least for documents in English, like [1](https://respec.org/docs/#automatic-pluralization) and [2](https://tabatkins.github.io/bikeshed/#conjugating)). If that's not possible, it would be nice to have a way to manually add variants of a term.

You can do this using some library like https://www.npmjs.com/package/pluralize. In the config I've shown change `slugify(s)` with `slugify(singular(s))`. Also that library allows you customize singularization using `addSingularRule` function.
