### ISSUE TITLE
No boolean attributtes after code snippet

### ISSUE THREAD

**Issue by Paul7Peterson** [vuejs/vitepress#891]
### Describe the bug

Apart from the `Illegal tag name. Use '&lt;' to print '<'.vue(12)`  error appearing when the snippet injection is used, after the use on a snippet injection the use of boolean attributes will inject then the attributes without value as empty strings instead of `true`.

### Reproduction

In the `index.md` file with the content: 

```md

<<< src/index.ts

...

<AppButton disabled>My button</AppButton>

```

Then `AppButton` will receive `''` as the property `disabled` value.

### Expected behavior

Should be setting the property `disabled` to `true` inside `AppButton`.

### System Info

```shell
Do not apply.
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! This is not reproducible: https://stackblitz.com/edit/vite-9kzqrs?file=docs%2Ffoo.js,docs%2FFooBar.vue,docs%2Findex.md

**Comment by Paul7Peterson** [comment]
I will try to setup an isolated version of my code that reproduces the error. Thanks.

**Comment by brc-dd** [comment]
If you can reproduce this, then please reopen the issue. I'm closing it for now.
