### ISSUE TITLE
Make it possible to change the "Previous page" and "Next page" labels in the default theme

### ISSUE THREAD

**Issue by soetz** [vuejs/vitepress#893]
### Is your feature request related to a problem? Please describe.

Right now it’s not possible to change the text in the prev/next links that are displayed at the bottom of pages with the default theme.
<img width="378" alt="Screenshot 2022-07-01 at 23 45 56" src="https://user-images.githubusercontent.com/18370980/176971436-a1d5d9d3-2cb2-4088-a94d-69307d0b20a7.png">
 
This is not very elegant when you’re working with non-English docs :)

### Describe the solution you'd like

I guess a `themeConfig.docFooter.[prev|next]` option, or something similar, would do the trick.

### Describe alternatives you've considered

One option would be building a custom theme that extends the default one and overriding [VPDocFooter.vue](https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPDocFooter.vue), but imo this feature could also benefit a lot of users of the default theme.

### Additional context

Thanks for being awesome!

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah, we should add this. I am guessing that every other such placeholder can already be customized? Like edit links and that outline thing.

**Comment by userquin** [comment]
https://github.com/vuejs/vitepress/issues/758

**Comment by soetz** [comment]
Wow, that was fast! Thanks folks!! 🔥
