### ISSUE TITLE
how to add another page

### ISSUE THREAD

**Issue by Maxhodges** [vuejs/vitepress#9]
hopefully some basic docs are in the works. Any clues on how to add more than index.md? 
Cheers!

**Comment by meta7x** [comment]
Hi, you can just add new folders and files to create new pages:

```
/
├── .vitepress/
│   ├── theme/
│   │   ├── index.js
│   │   └── Layout.vue
│   └── config.js
├── fruits/
│   ├── apple.md
│   └── banana.md
├── about.md
├── index.md
└── package.json
```

This would generate pages for `/index`, `/about`, `/fruits/apple` and `/fruits/banana`.

**Comment by emersonbottero** [comment]
router.js

`import { createRouter, createWebHistory } from 'vue-router'
import Login from '../views/Login.vue'
import Register from '../views/Register.vue'

const routerHistory = createWebHistory()

const router = createRouter({
    history: routerHistory,
    routes:[
        {
            path: '/',
            component: Login
        },
        {
            path: '/register',
            component: Register
        },
    ]
})

export default router`

main.js
`import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import './index.css'

createApp(App).use(router).mount('#app')`

and wherever you like to use them
`  <router-link to="/">Logar</router-link>
  <router-link to="/Register">Registrar</router-link>
  <router-view />`

**Comment by yyx990803** [comment]
The usage is similar to VuePress - for now this project is still WIP so please wait for proper documentation.
