### ISSUE TITLE
`client` and `theme` are not `exported` from `exports` field in `package.json`

### ISSUE THREAD

**Issue by JounQin** [vuejs/vitepress#913]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vitepress@1.0.0-alpha.4` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vitepress/package.json b/node_modules/vitepress/package.json
index bc579de..68da516 100644
--- a/node_modules/vitepress/package.json
+++ b/node_modules/vitepress/package.json
@@ -12,7 +12,9 @@
       "import": "./dist/node/index.js",
       "require": "./dist/node-cjs/index.cjs"
     },
-    "./dist/client/*": "./dist/client/*"
+    "./dist/client/*": "./dist/client/*",
+    "./client": "./client.d.ts",
+    "./theme": "./theme.d.ts"
   },
   "bin": {
     "vitepress": "bin/vitepress.js"
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by brc-dd** [comment]
Can you tell what error(s) were you getting? I don't think types need to be in `exports`.

**Comment by JounQin** [comment]
> Can you tell what error(s) were you getting? I don't think types need to be in `exports`.

```
// docs/.vitepress/theme/index.ts
import type { Theme } from 'vitepress'
import DefaultTheme from 'vitepress/theme'

import * as components from '../components'

import './index.less'

const theme: Theme = {
  ...DefaultTheme,
  enhanceApp({ app }) {
    for (const [name, Component] of Object.entries(components))
      app.component(name, Component)
  },
}

export default theme
```

**Comment by JounQin** [comment]
Although I'm not quite sure to understand why `import DefaultTheme from 'vitepress/theme'` would work:

```ts
console.log('DefaultTheme:', DefaultTheme)
```

<img width="619" alt="image" src="https://user-images.githubusercontent.com/8336744/177087116-11458cc9-1641-49c2-9799-dbca3ca5c250.png">

**Comment by JounQin** [comment]
OK, I found `vitepress/theme` is transformed into the following on client:

```js
import DefaultTheme from "/@fs/Users/JounQin/Workspaces/Alauda/vision/node_modules/vitepress/dist/client/theme-default/index.js";
console.log("DefaultTheme:", DefaultTheme);
```

So `vitepress/theme` actually points to `vitepress/dist/client/theme-default/index.js`

**Comment by JounQin** [comment]
This is a TypeScript usage related issue.

**Comment by brc-dd** [comment]
Yeah but your fix is still throwing this error in my case:

> Module 'vitepress/theme' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.

Without that fix, I was getting:

> Cannot find module 'vitepress/theme' or its corresponding type declarations.

**Comment by JounQin** [comment]
> Yeah but your fix is still throwing this error in my case:
> 
> > Module 'vitepress/theme' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.
> 
> Without that fix, I was getting:
> 
> > Cannot find module 'vitepress/theme' or its corresponding type declarations.

What command  can I run to reproduce on this project?

**Comment by JounQin** [comment]
And did you try my new fix?

<img width="572" alt="image" src="https://user-images.githubusercontent.com/8336744/177094884-3faf15b7-74cf-43a3-8e2c-6e61012669c8.png">

**Comment by brc-dd** [comment]
https://github.com/brc-dd/vp-issue

**Comment by JounQin** [comment]
OK, I'll check it ASAP.

**Comment by JounQin** [comment]
@brc-dd That's because there is no `type: "module"` field in `package.json`, so `.ts` will be compiled as `cjs`, and we have no `cjs` entry for `vitepress/theme`, you can update `package.json` with `type: 'module'`, or add a new private `package.json` under `.vitepress` with:

```json
{
  "private": true,
  "type": "module"
}
```

Then, the `.vitepress/theme/index.ts` will be considered as ESM correctly.

**Comment by JounQin** [comment]
@brc-dd See https://github.com/brc-dd/vp-issue/pull/1 for demo.

**Comment by JounQin** [comment]
Besides, `export const VPHomeHero = ComponentOptions` in `theme.d.ts` seems absolutely wrong, actually, it should be `export const VPHomeHero: ComponentOptions`, should I fix this in the same PR or a separated one?

**Comment by brc-dd** [comment]
> Besides, `export const VPHomeHero = ComponentOptions` in `theme.d.ts` seems absolutely wrong, actually, it should be `export const VPHomeHero: ComponentOptions`, should I fix this in the same PR or a separated one?

This is fixed on vite 3 branch.

**Comment by JounQin** [comment]
> This is fixed on vite 3 branch.

Glad to hear.

---

@brc-dd 

Besides, do you think is there any chance how can I apply to be a member or collaborator or vite/vitepress groups? I'd like to spend more time working on vite/vitepress in the next few days.
