### ISSUE TITLE
Hey, can you expose `isDark`

### ISSUE THREAD

**Issue by newives** [vuejs/vitepress#923]
### Is your feature request related to a problem? Please describe.

Hey, can you expose [`isDark`](https://github.com/vuejs/vitepress/blob/acca3a81c3096e24bff3524fbd3f12a55896c61c/src/client/theme-default/components/VPSwitchAppearance.vue#L7)

For example, I use hasClass to get whether there is a dark class in html or directly from storage, they are not responsive

### Describe the solution you'd like

It may be used to adapt to dark mode when paired with some component libraries, thanks

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You can use [`useDark`](https://vueuse.org/core/usedark/) from `@vueuse/core`.

**Comment by newives** [comment]
Also, the key of vueuse's theme mode variable in storage is vueuse-color-scheme, and the key of vitepress is vitepress-theme-appearance, which itself does not correspond

**Comment by brc-dd** [comment]
Ah, we have custom function for this. The code you linked wasn't the latest one. This is:

https://github.com/vuejs/vitepress/blob/bed68f134186e4fd3c0bca4c6a5871a79e4cd224/src/client/theme-default/components/VPSwitchAppearance.vue#L9-L40

https://github.com/vuejs/vitepress/blob/bed68f134186e4fd3c0bca4c6a5871a79e4cd224/src/shared/shared.ts#L14

**Comment by brc-dd** [comment]
I don't think this is reactive either. You'll probably have to use MutationObserver or something like that.

**Comment by newives** [comment]
I am currently writing this
<img width="522" alt="图片" src="https://user-images.githubusercontent.com/81661030/177530668-a4d02a9e-a7ae-4304-b172-5c3c7acfd438.png">

But I found that the button of the VPSwitch attribute appears twice in different sizes. The event of the VPSwitch attribute can be monitored on the PC, but the mobile terminal is invalid. I wonder if you have a better way?
<img width="1380" alt="图片" src="https://user-images.githubusercontent.com/81661030/177530818-bb4d732a-635b-4861-b352-684a37354a03.png">

**Comment by newives** [comment]
Get can monitor the changes of attributes in html in real time, but I don't know how to do it 😂

**Comment by brc-dd** [comment]
Try something like this: https://stackblitz.com/edit/vite-1wpj13?file=docs%2Findex.md,docs%2FTellsDark.vue

```ts
import { ref, onMounted, onBeforeUnmount } from 'vue';

const isDark = ref(null);
let observer = null;

const setDark = () => {
  isDark.value = document.documentElement.classList.contains('dark');
};

onMounted(() => {
  setDark();
  observer = new MutationObserver(setDark);
  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ['class'],
  });
});

onBeforeUnmount(() => {
  observer.disconnect();
});
```

**Comment by newives** [comment]
wow, strong, thanks, this solved my problem[❤️](https://emojipedia.org/red-heart/)
