### ISSUE TITLE
Support multi-level sidebar

### ISSUE THREAD

**Issue by cy920820** [vuejs/vitepress#926]
### Is your feature request related to a problem? Please describe.
yes

### Describe the solution you'd like

```json
 {
   "text":"level1",
   "collapsible":true,
   "collapsed":false,
   "items":[
      {
         "text":"level1-1",
         "collapsible":true,
         "collapsed":false,
         "items":[
            {
               "text":"level1-1-1 ",
               "link":"/01.1"
            },
            {
               "text":"level1-1-2 ",
               "link":"/01.2"
            }
         ]
      },
      {
         "text":"level1-2",
         "collapsible":true,
         "collapsed":false,
         "items":[
            {
               "text":"level1-2-1 ",
               "link":"/02.1"
            },
            {
               "text":"level1-2-2 ",
               "link":"/02.2"
            }
         ]
      }
   ]
}

```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
#851 should fix this

**Comment by cy920820** [comment]
> #851 should fix this

Bottom navigation error:

prev page & next page navigator is wrong.

**Comment by cy920820** [comment]
How do I turn off bottom navigation

**Comment by cy920820** [comment]
@brc-dd  Excuse me

**Comment by brc-dd** [comment]
> prev page & next page navigator is wrong.

What's the issue?

**Comment by SebasG22** [comment]
Looking forward to having this merged!
