### ISSUE TITLE
[plugin:vite:vue] Unexpected '<!--' in comment.

### ISSUE THREAD

**Issue by mouyong** [vuejs/vitepress#939]
### Describe the bug

When use tailwindui in index.md. it throw the error

![image](https://user-images.githubusercontent.com/10336437/177907508-4e418a9e-407b-4d6f-9ba6-e183670cf6b9.png)

### Reproduction

use the code: https://tailwindui.com/components/preview

![image](https://user-images.githubusercontent.com/10336437/177907440-f54cc84c-83ba-43cb-b8a1-9f17cab73e2d.png)

### Expected behavior

hope it can support  html comment.

### System Info

```shell
npx: installed 1 in 2.389s

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Gold 6161 CPU @ 2.20GHz
    Memory: 328.15 MB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/sh
  Binaries:
    Node: 14.19.1 - /www/server/nodejs/v14.19.1/bin/node
    Yarn: 1.22.18 - /www/server/nodejs/v14.19.1/bin/yarn
    npm: 6.14.16 - /www/server/nodejs/v14.19.1/bin/npm
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's working fine for me. You just have to remove empty lines from the html.

**Comment by mouyong** [comment]
Can you provide your code? I want to know the different places with me.

**Comment by brc-dd** [comment]
@mouyong https://stackblitz.com/edit/vite-u76wbw?file=docs%2Findex.md

**Comment by mouyong** [comment]
@brc-dd you are right. when I remove all tailwindui empt line, it works.

I have another question: "how can i use alpinejs in vitepress?"

when i use https://alpinejs.dev/ homepage demo. it's not work.

in config.ts
```
export default Object.assign(userConfig, {
  head: [
    ['script', { src: '//unpkg.com/alpinejs', defer: true }],
  ],
}
```

in custom page
```
---
layout: page
---

<div class="container w-3/4 mx-auto">

<div x-data="{ open: false }">
    <button @click="open = true">Expand</button>
    <span x-show="open">
      Content...
    </span>
</div>

</div>

```

when i click the Expand button, it doesn't have any action.

![image](https://user-images.githubusercontent.com/10336437/178206356-02bb78da-cff6-4b25-9cfb-506cfa5f47e0.png)

![image](https://user-images.githubusercontent.com/10336437/178206290-c25e88f3-d01d-487d-a7b1-acf2bea97519.png)

**Comment by mouyong** [comment]
I want use tailwindui in custom page.

write the custom page by vue code or html + alphine code.

Tried some possibilities but failed: the tailwindui vue component install by npm, but use in markdown is not avaliable.

how can i do.

**Comment by brc-dd** [comment]
> how can i use alpinejs in vitepress?

This will likely conflict with Vue as they have some common syntax like `@click`. Why not simply use Vue in your markdown?

**Comment by mouyong** [comment]
I want to just use vue in project. when run the demo. it need import some component.

when i register component in theme/index.ts, it not work. So try use aplinejs to instead of vue script.

![image](https://user-images.githubusercontent.com/10336437/178212465-23812508-f7ed-43dc-9e98-63d282333bb7.png)

**Comment by mouyong** [comment]
when i use x-on:click instaed of @click, it works. i have 2 question.
1. why need remove html empty linke.
2. how to use oather vue component in vitepress.

```
<div x-data="{ open: false }">
    <button x-on:click="open = !open">Expand</button>
    <span x-show="open">
      Content...
    </span>
</div>
```

**Comment by brc-dd** [comment]
That is directly working for me: https://stackblitz.com/edit/vite-jbapbj?file=docs%2Findex.md,docs%2FDropdownMenu.vue

> why need remove html empty linke.

Empty lines tell the markdown that a block has ended. So if the content below that is indented then it'll treated like a code block.

**Comment by mouyong** [comment]
The demo page is: https://mouyong.github.io/vitepress-doc-website/home.html

use in project: https://github.com/mouyong/vitepress-doc-website

**Comment by mouyong** [comment]
Thanks for you. It will be help me very much. 

> That is directly working for me: https://stackblitz.com/edit/vite-jbapbj?file=docs%2Findex.md,docs%2FDropdownMenu.vue
> 
> > why need remove html empty linke.
> 
> Empty lines tell the markdown that a block has ended. So if the content below that is indented then it'll treated like a code block.
