### ISSUE TITLE
Hope can support tailwindui

### ISSUE THREAD

**Issue by mouyong** [vuejs/vitepress#940]
### Is your feature request related to a problem? Please describe.

yes, see #939 

### Describe the solution you'd like

hope in markdown, we can write tailwindui template.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please refrain from creating multiple similar issues.
