### ISSUE TITLE
ignoreDeadLinks does not take effect

### ISSUE THREAD

**Issue by cy920820** [vuejs/vitepress#941]
### Describe the bug

add ignoreDeadLinks attr does not take effect, Compilation still fails

### Reproduction

The config.js file:

export default {
  title: 'test',
  description: 'test',
  ignoreDeadLinks: true
}

-------------
Error:

⠏ building client + server bundles...[vitepress] One or more pages contain dead links.

### Expected behavior

Compilation passed

### System Info

```shell
⠏ building client + server bundles...[vitepress] One or more pages contain dead links.
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by cy920820** [comment]
The vitepress version is ^1.0.0-alpha.4

**Comment by brc-dd** [comment]
It'll be there in alpha-5.

**Comment by cy920820** [comment]
> It'll be there in alpha-5.

when?

**Comment by brc-dd** [comment]
1 or 2 weeks I guess. Not sure though.

**Comment by cy920820** [comment]
#1084

**Comment by Joffey** [comment]
Why does this configuration item appear in 1.0.0-alpha.4?
