### ISSUE TITLE
Is there any way to support base64 image on Markdown?

### ISSUE THREAD

**Issue by okeyear** [vuejs/vitepress#945]
### Is your feature request related to a problem? Please describe.

I write some markdown files.

The image format is `![image-XXXXXXX](data://image/png;base64,....)`.

How to render the markdown base64 image to html when using "vite build" ?

### Describe the solution you'd like

pending 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! Fixed this. It should work in the next release.
