### ISSUE TITLE
Make it possible to translate some labels

### ISSUE THREAD

**Issue by soetz** [vuejs/vitepress#955]
### Is your feature request related to a problem? Please describe.

This issue is very similar to #893

I noticed some more text that is hardcoded into the default theme components, and it would be super if they were translateable.

- ["Appearance" in `VPNavScreenAppearance.vue`](https://github.com/vuejs/vitepress/blob/baf8083e668ce50a9d26d9398609e196237ebc95/src/client/theme-default/components/VPNavScreenAppearance.vue#L10)
- ["Menu" in `VPLocalNav.vue`](https://github.com/vuejs/vitepress/blob/baf8083e668ce50a9d26d9398609e196237ebc95/src/client/theme-default/components/VPLocalNav.vue#L29)
- ["Return to top" in `VPLocalNav.vue`](https://github.com/vuejs/vitepress/blob/baf8083e668ce50a9d26d9398609e196237ebc95/src/client/theme-default/components/VPLocalNav.vue#L33)

### Describe the solution you'd like

Same as #893, `themeConfig` options would do the job.

I guess they could be grouped with `themeConfig.outlineTitle`, `themeConfig.lastUpdatedText` and `themeConfig.docFooter` under something like `themeConfig.translate` or `themeConfig.customText`?

### Describe alternatives you've considered

We can still extend the theme to get this functionality, so this is not critical.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! Yeah we would fix all these issues. I am working on it. In the meanwhile, you can track #631.

**Comment by soetz** [comment]
Good to know, thanks!

I’ve looked a bit and those are the only ones that I found, but of course if I notice new ones I’ll add them :)
