### ISSUE TITLE
DOMException: Failed to execute 'querySelector' on 'Document': '#%E5%A3%A'  is not a valid selector.

### ISSUE THREAD

**Issue by gyhyfj** [vuejs/vitepress#958]
### Is your feature request related to a problem? Please describe.

When I click the right side toc , browser's  terminal will report like this :

```
DOMException: Failed to execute 'querySelector' on 'Document': '#%E5%BC%A0%E6%B8%A9%E7%9A%84%E9%80%89%E6%8B%A9' is not a valid selector.
    at l (https://www.gyhyfj.com/assets/app.db3f66e3.js:1:122893)
    at $t (https://www.gyhyfj.com/assets/app.db3f66e3.js:1:12734)
    at qe (https://www.gyhyfj.com/assets/app.db3f66e3.js:1:12813)
    at HTMLAnchorElement.n (https://www.gyhyfj.com/assets/app.db3f66e3.js:1:56863)
```

I think the reason is that the heading's language is not English , such as Chinese.
However ... everything works well as usual.
It just looked not elegant.

### Describe the solution you'd like

not yet

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Hi! This was fixed in #951. It will be there in the next release.
