### ISSUE TITLE
Line highlighting style in custom block isn't working as expected

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/vitepress#959]
### Describe the bug

Assume we have below code:

```md
:::tip

```html{1}
<div class="grid-row grid-cols-2 justify-items-stretch">
    <div></div>
    <div></div>
</div>

:::
```

With above code we get code block rendered like below:

![image](https://user-images.githubusercontent.com/47495003/178146916-44999945-bfa0-4ecb-918d-4f1796f3ad09.png)

### Reproduction

Above code (code block with highlighted lines in custom block)

### Expected behavior

It should highlight full line

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 9.52 GB / 15.57 GB
    Container: Yes
    Shell: 0.12.1 - /home/jd/.xonsh/.venv/bin/xonsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
  npmPackages:
    vitepress: 1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Additional context

None

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Probably need to add this at bottom here: https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/styles/components/custom-block.css

```css
.custom-block div[class*='language-'] code {
  background-color: transparent;
}
```
