### ISSUE TITLE
Generate IDs for headers added through Vue components or raw HTML

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/vitepress#960]
Hi,

I almost finished my lib docs and now I am refactoring demos and I want to put demo section links in my custom card.

![image](https://user-images.githubusercontent.com/47495003/178150822-9e79d5c4-672a-420f-a963-607347e8ef4c.png)

How can I convert my `h2` tag like `markdown-it` tag so it can get anchor based on its name.

**Comment by brc-dd** [comment]
Just add an id on your `h2`. Then your url will be `foo.com/currentp-page#id`.

**Comment by jd-solanki** [comment]
I know that but I had to generate id my self. I want it to auto generate like regular md content.

Moreover, I also lost on this page links.

**Comment by brc-dd** [comment]
> I know that but I had to generate id my self. I want it to auto generate like regular md content.

Probably will have to add some custom client-side script to watch DOM, get all h2 elements and add id if its not there.

> Moreover, I also lost on this page links.

Yeah it won't show. There is an open feature request for this: #785. We currently use the headers returned by our markdown plugin to generate the outline component, so it doesn't consider normal html tags, vue elements and interpolations, etc.

**Comment by jd-solanki** [comment]
Great! It looks promising. I guess this is now a feature request rather than a question.

Shall we keep it open?

Moreover, this issue issues needs to resolve two feature request hence it might take longer. I probabaly release the lib next week. May I know should I want to move on without this feauture?

> _I know OSS devs have lot on their plate so just friendly question_ 😊 

Thanks.

**Comment by brc-dd** [comment]
You probably should publish your docs without that. It's currently on low priority and frankly I'm unsure how to handle that unless generating outline completely on client side.

**Comment by sifex** [comment]
Does the rollout of build-time data loading change this? I've changed my dynamic headings to use this instead, but I still get all links using the `vue` function instead of processing the output then using that output in the outline section.

**Example:**


<img width="341" alt="CleanShot 2023-04-08 at 15 51 52@2x" src="https://user-images.githubusercontent.com/2058557/230727859-67ed3758-b139-4777-9901-30770b8a4089.png">
<img width="285" alt="CleanShot 2023-04-08 at 15 51 45@2x" src="https://user-images.githubusercontent.com/2058557/230727856-6c2be928-6c73-46fe-a423-3e8caec2a265.png">

**Comment by brc-dd** [comment]
Outline is now generated purely on client-side. So if one specifies `id` on heading elements, it will show up on the outline.

> Probably will have to add some custom client-side script to watch DOM, get all h2 elements and add id if its not there.

This I'm still unsure how to handle and **_if_** we should even handle it. As a workaround, you can use some global component like this:

```vue
<script setup lang="ts">
import slugify from '@sindresorhus/slugify'

defineProps<{
  as: 'h2' | 'h3' | 'h4'
  text: string
}>()
</script>

<template>
  <component :is="as || 'h2'" :id="slugify(text)">{{ text }}</component>
</template>
```
