### ISSUE TITLE
sidebar does not change when file under /zh/ was open

### ISSUE THREAD

**Issue by Sepush** [vuejs/vitepress#961]
### Describe the bug

sidebar does not change when file under /zh/ was open

sidebar language should folling the current language

### Reproduction
1 git clone the followin repo 
https://github.com/Sepush/vitepress-issue
2 pnpm i && pnpm docs:dev
3 click `get stared` button
4 click `简体中文` button
![image](https://user-images.githubusercontent.com/39197136/178193710-c0e041bb-4ede-43a4-b9a2-6486b4a8a8c2.png)

you will see the file has changed to /zh/guide/index.md
but the sidebar menu did not changed to Chinese follow my config under `.vitepress/config/sidebar.ts`

### Expected behavior

sidebar language should folling the current language

### System Info

```shell
win 10 chrome 103
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Sepush** [comment]
is there any config I have missing?

**Comment by xfq** [comment]
That's probably because VitePress v1 alpha version does not support i18n/l10n: https://vitepress.vuejs.org/guide/migration-from-vitepress-0.html#app-config

See also https://github.com/vuejs/vitepress/issues/631

**Comment by Sepush** [comment]
> That's probably because VitePress v1 alpha version does not support i18n/l10n: https://vitepress.vuejs.org/guide/migration-from-vitepress-0.html#app-config
> 
> See also #631

but it's works for some project in this way.
It's confusing to me.
eg. https://github.com/YunYouJun/hexo-theme-yun

**Comment by brc-dd** [comment]
> but it's works for some project in this way. It's confusing to me. eg. https://github.com/YunYouJun/hexo-theme-yun

Nope, it isn't. Open this: https://yun.yunyoujun.cn/guide/config.html

![image](https://user-images.githubusercontent.com/40380293/178268860-7df2b8b4-88c3-4610-98c0-7d1f339e4fa1.png)

**Comment by Sepush** [comment]
> Ah regarding that sidebar, you need to move that `/zh/` one above `/` here: https://github.com/Sepush/vitepress-issue/blob/main/docs/.vitepress/config/sidebar.ts

thanks a lot! That realy help me to solve my issue.
We better note this in the future doc.
