### ISSUE TITLE
The title bar does not completely cover sidebar texts

### ISSUE THREAD

**Issue by object-kaz** [vuejs/vitepress#962]
### Describe the bug

The title bar can not completely cover sidebar texts.
<img width="271" alt="81e7ba36bd7d0197428bcf36a31e0308" src="https://user-images.githubusercontent.com/54239670/178223637-e59cb463-5d62-4a1f-bd46-643ed4096a16.png">

### Reproduction

1. clone this repo
2. run `pnpm install`
3. run `pnpm build`
4. run `pnpm docs-dev`
5. open the page and then click `Guide`
6. scroll the sidebar
<img width="271" alt="81e7ba36bd7d0197428bcf36a31e0308" src="https://user-images.githubusercontent.com/54239670/178223637-e59cb463-5d62-4a1f-bd46-643ed4096a16.png">

### Expected behavior

The title bar can completely cover the sidebar text.
<img width="276" alt="dedb7f092bdd71196d7005e160b6b408" src="https://user-images.githubusercontent.com/54239670/178226135-7ee1ac44-362a-45fa-8959-da037b0ad039.png">

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 92.30 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 91.4.1
    Safari: 15.5
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
What's the issue again? This is the output on my system:

![image](https://user-images.githubusercontent.com/40380293/178228619-72c891ad-3e5a-448b-89a7-ad11c1eb655e.png)

**Comment by object-kaz** [comment]
> What's the issue again? This is the output on my system:
> 
> ![image](https://user-images.githubusercontent.com/40380293/178228619-72c891ad-3e5a-448b-89a7-ad11c1eb655e.png)
It seems to be related to the width of the page.

**Comment by object-kaz** [comment]
Device Resolution: 2560 × 1600

Execute:
```js
{clientWidth: document.documentElement.clientWidth, innerWidth: window.innerWidth, innerWidthScreen: screen.innerWidth, devicePixelRatio:window.devicePixelRatio}
```
Result:
```json
{
    "clientWidth": 1425,
    "innerWidth": 1440,
    "devicePixelRatio": 2
}
```

**Comment by brc-dd** [comment]
![image](https://user-images.githubusercontent.com/40380293/178238212-e5f5dcf1-483f-42e1-ad3b-2c9fc7365a24.png)

Still not able to reproduce.

**Comment by object-kaz** [comment]
I wrote two functions to calculate the padding:
```js
let paddingLeftTitle = (width,scrollbarWidth) => (width-scrollbarWidth-Math.min(1376,width-scrollbarWidth-64))/2
let paddingLeftSidebar = (width,scrollbarWidth) => (width-scrollbarWidth-1376)/2
```

For $1440 \le width<1440+scrollbarWidth$, 
$paddingLeftTitle=32$ 
$paddingLeftSidebar=(width-scrollbarWidth-1376)/2<32$

For $width \ge 1440+scrollbarWidth$,
$paddingLeftTitle=(width-scrollbarWidth-1376)/2=paddingLeftSidebar$

**Comment by brc-dd** [comment]
Yeah, cool finally reproduced this 😅

**Comment by object-kaz** [comment]
> Changing this seems to fix this:
> 
> https://github.com/vuejs/vitepress/blob/e0b730aa8ee9bec1fe16245c4c1a1a91f62bed42/src/client/theme-default/components/VPSidebar.vue#L97
> 
> ```css
> padding-left: max(32px, calc((100% - (var(--vp-layout-max-width) - 64px)) / 2));
> ```
> 
> Check if this works fine for you too.

Yes, it works!
