### ISSUE TITLE
Default Theme renders home page and 404 page unexpectedly

### ISSUE THREAD

**Issue by NozomuIkuta** [vuejs/vitepress#963]
### Describe the bug

I found default theme renders home page and 404 page unexpectedly, whose ways in which it happens differs from environment to another.

### Reproduction

Case 1: the current website

Case 1-1 (expected):

- Access https://vitepress.vuejs.org/
- Change the URL to https://vitepress.vuejs.org/this-page-doesnt-exist
- 404 page is rendered as expected

Case 1-2 (unexpected):

- Access https://vitepress.vuejs.org/guide/getting-started.html (or, any pages that has sidebar)
- Change the URL to https://vitepress.vuejs.org/guide/this-page-doesnt-exist
- 404 page is rendered in 2 places unexpectedly
- Click a link in sidebar to change the URL
- One of 404 pages is still there while the other is replaced by the content of the page that you chose

---

Case 2: local development

Case 2-1 (expected):

- Run `pnpm run docs` in your local
- Access http://localhost:3000/
- Change the URL to http://localhost:3000/this-page-doesnt-exist
- 404 page is rendered as expected (cf. Case 1-1)

Case 2-2 (unexpected):

- Run `pnpm run docs-build` in your local
- Run `pnpm run docs-serve` in your local
- Access http://localhost:5000/
- Change the URL to http://localhost:5000/this-page-doesnt-exist
- 404 page is broken (it seems that `div.VPHome` is rendered instead of `div.NotFound`)

Case 2-3 (unexpected):

- Run `pnpm run docs-build` in your local
- Run `pnpm run docs-serve` in your local
- Access http://localhost:5000/
- Access http://localhost:5000/guide/getting-started.html (or, any pages that has sidebar)
- Change the URL to http://localhost:5000/guide/this-page-doesnt-exist
- Home page and 404 page is rendered unexpectedly (cf. Case 1-2)
- Click a link in sidebar to change the URL
- Home page is still there while 404 page is replaced by the content of the page that you chose

### Expected behavior

Home page and 404 page are rendered only when they are supposed to be so.

### System Info

```shell
Environment 1: https://vitepress.vuejs.org/ as of Jul 11th 2022
Environment 2: my local with the head of upstream's `main` branch checked out
---
  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 1.15 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.4
---
```

### Additional context

I'm not so familiar with VitePress' implementation, so I don't have an idea at the moment.
I will post comments when I find something related.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Regarding case 2-2, sirv is having some issues. Currently (in fix/404 branch) for `/foo` its sending Not Found as plain text. But requesting `/foo/` it is sending root `index.html` file. vercel/serve is working fine with the generated output.

**Comment by brc-dd** [comment]
Hi! Can you checkout `fix/404` branch and see if the issues are resolved.
