### ISSUE TITLE
How can I config the markdown render so that the line wrap in markdown can be render as wrap ?

### ISSUE THREAD

**Issue by gyhyfj** [vuejs/vitepress#966]
### Is your feature request related to a problem? Please describe.

My editor is vscode, how can I config vitepress so that the markdown content can wrap when I enter once `enter` instead of twice ?

Just like this :

```md
text-line1
text-line2
```

only one `enter`  used after `text-line1`.

### Describe the solution you'd like

Is there any config like this?
```json
  "markdown.preview.breaks": true,
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's simply markdown.breaks : true IG.

**Comment by brc-dd** [comment]
```js
// .vitepress/config.js
export default {
  markdown: {
    breaks: true,
  },
};
```
