### ISSUE TITLE
(i18n) redirect to the corresponding homepage of language

### ISSUE THREAD

**Issue by Sepush** [vuejs/vitepress#967]
### Is your feature request related to a problem? Please describe.

Current when we change  the language then click the homepage button it won't redirect to the current language homepage. 
It's redirect to the default home page.
eg. repo https://github.com/YunYouJun/hexo-theme-yun  site https://yun.yunyoujun.cn/
step to reproduce
1 change the current language
2 click the homepage button
![image](https://user-images.githubusercontent.com/39197136/178387750-c5194b23-decb-46b4-9a25-182bdc6d812c.png)

### Describe the solution you'd like

redirect the homepage according to current language when homepage button clicked
eg. when current language is English it should redirect to the English homepage, if it's Chinese,the homepage should be Chinese one.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This is fixed on the i18n branch.

**Comment by Sepush** [comment]
> This is fixed on the i18n branch. [88266f6](https://github.com/vuejs/vitepress/commit/88266f60b58248625710ff13f539408b6e1d9968)

looks great waiting for the release

**Comment by Sepush** [comment]
Hi, could i18n branch be merged and realse a version so that we coulde get this fix.
Waiting for this fix for days.🥳
