### ISSUE TITLE
Write content process.env.node_env === 'Development' to report an error

### ISSUE THREAD

**Issue by n1203** [vuejs/vitepress#971]
### Describe the bug

The relevant expression of the environment variables in the document will cause the page to report an error cannot be displayed

### Reproduction

mkdir docs && echo '# Hello VitePress `process.env.NODE_ENV === 'development' `' > docs/index.md

### Expected behavior

![image](https://user-images.githubusercontent.com/30693884/178450551-37d0b5a8-b6d1-4b56-88b8-1a9ff7d8e1d5.png)

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) x64 Apple M1 Pro
    Memory: 30.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.5
```

### Additional context

```markdown
**Example**
General transmission:  `process.env.NODE_ENV === 'development'`
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Was fixed by #888. It'll be there in the next release.
