### ISSUE TITLE
Allow links in the homepage-layout features

### ISSUE THREAD

**Issue by MajesticString** [vuejs/vitepress#984]
### Is your feature request related to a problem? Please describe.

Currently, if the layout of a page is `home`, under `features`, links do not render (both markdown and html).

### Describe the solution you'd like

Allow markdown links in `features`
Example:
```md
---
layout: home
title: Ipsum
features:
    - title: [link](https://google.com/)
      details: [another link](https://google.com/)
---
```

### Describe alternatives you've considered

Alternatively, HTML links could be allowed:
```md
---
layout: home
title: Ipsum
features:
    - title: <a href="https://google.com/">link</a>
      details: <a href="https://google.com/">another link</a>
---
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Fixing this is simple, we just need to use `v-html` instead of `{{ foo }}` syntax in `VPFeature.vue`. But might need to add styles for links to distinguish them:

![image](https://user-images.githubusercontent.com/40380293/178953027-3c14612f-e327-4f3a-9775-97a1de663ce1.png)

**Comment by remirobichet** [comment]
Is this enhancement under developement ?

Another solution would be to let `{{ foo }}` syntax in `VPFeature.vue` and add extra optional property to feature section.
For example `link` as in the hero section and add a CTA at the end of each feature item.
