### ISSUE TITLE
Override target blank on external link

### ISSUE THREAD

**Issue by narduin** [vuejs/vitepress#997]
Hello!

I'm wondering if it's possible to override the markdown-it link plugin behaviour with external links.
I would like to set `target="_self"` instead of `_blank` but I have not been able to.

I tried to look in the source code of [this component](https://github.com/vuejs/vitepress/blob/1e9a7ac6c478c57d7336e2d7b0392f23659080d3/src/client/theme-default/components/VPLink.vue#L21) but it seems hardcoded.

I'm currently trying to extend the theme to change this component but this is not my domain of expertise so I'm a little lost.

Thanks!

**Comment by brc-dd** [comment]
That component isn't used for your markdown code. You probably need to have this config:

```js
// .vitepress/config.js
{
  markdown: {
    externalLinks: {
      target: '_self'
    }
  }
}
```

**Comment by narduin** [comment]
I was looking all over for this configuration, thank you!!
